"use strict";
define(['./DvtToolkit'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.Wj=(0,D.s)();(0,D.ra)("DvtAxis",D.Wj);D.y.l(D.Wj,D.mB,"DvtAxis");D.Wj.newInstance=function(a,b,c){var d=new D.Wj;d.Init(a,b,c);return d};D.Rk=function(a){return(0,D.TB)(new D.Ol,a)};D.Wj.getDefaults=D.Rk;D.Wj.prototype.Init=function(a,b,c){D.Wj.o.Init.call(this,a,b,c);this.vf=new D.Ol;this.Ca=new D.Pl(this);this.Ca.Df(this);this.oS=D.k;this.Ja=D.n};D.Wj.prototype.ge=function(a){a?this.M=this.vf.ah(a):this.M||(this.M=(0,D.xf)(this))};
D.Wj.prototype.Sw=function(a,b,c){this.ge(a);this.za().isLayout=D.k;this.L(D.n,b,c);a=this.C();this.za().isLayout=D.p;this.Di();var d=this.za().position;if("top"==d||"bottom"==d)return a.j<=c&&(this.oS=D.p),new D.pi(b,window.Math.min(a.j,c));d=0<a.g?window.Math.max(1,0.1*a.g):0;a.g+d<=b&&(this.oS=D.p);return new D.pi(window.Math.min(a.g+d,b),c)};D.Wj.prototype.L=function(a,b,c,d,e){this.ge(a);this.pb=b;this.Cb=c;this.Di();d||(d=0);e||(e=0);D.Ll.L(this,new D.N(d,e,b,c))};D.Wj.prototype.render=D.Wj.prototype.L;
D.x=D.Wj.prototype;D.x.lg=function(a,b){this===b&&this.Wa(a)};D.x.za=(0,D.w)("M");D.x.Ua=(0,D.w)("Ca");D.x.getWidth=(0,D.w)("pb");D.x.getHeight=(0,D.w)("Cb");D.x.S=function(){this.Ca&&(this.Ca.Bs(this),this.Ca.S(),this.Ca=D.n);D.Wj.o.S.call(this)};D.x.wZ=(0,D.v)("Ja");D.x.Vh=function(){return new D.rl(this)};D.Wj.prototype.getAutomation=D.Wj.prototype.Vh;
D.hi={};(0,D.ra)("DvtAxisConstants",D.hi);D.y.l(D.hi,D.y,"DvtAxisConstants");D.hi.Px="tickLabel";D.hi.TICK_LABEL=D.hi.Px;D.hi.Np="title";D.hi.TITLE=D.hi.Np;
D.Dl=(0,D.v)("af");D.y.l(D.Dl,D.y,"DvtAbstractAxisValueFormatter");D.Dl.prototype.Iq=(0,D.s)();
D.rl=function(a){this.ii=a;this.Qc=this.ii.za();this.lca=this.ii.Gb};(0,D.ra)("DvtAxisAutomation",D.rl);D.y.l(D.rl,D.we,"DvtAxisAutomation");D.rl.prototype.Fp=function(a){if((a=this.ii.Ua().ma(a))&&a instanceof D.Ga&&this.Qc.groups){a=a.fm().id;for(var b=0;b<this.Qc.groups.length;b++)if(this.Qc.groups[b]==a)return"item["+b+"]"}return D.n};D.rl.prototype.Ij=function(a){if(this.lca instanceof D.Yj){var b=a.indexOf("["),c=a.indexOf("]");if(0<b&&0<c)return a=a.substring(b+1,c),this.lca.Ow(this.ii.e)[a].pa()}return D.n};
D.rl.prototype.getDomElementForSubId=D.rl.prototype.Ij;
D.Ol=function(){this.Init({skyros:D.Ml,alta:D.Nl})};D.y.l(D.Ol,D.Aa,"DvtAxisDefaults");D.Nl={axisLine:{lineColor:"#9E9E9E"},majorTick:{lineColor:"rgba(196,206,215,0.4)",baselineColor:"auto"},minorTick:{lineColor:"rgba(196,206,215,0.2)"},tickLabel:{style:new D.B("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")},titleStyle:new D.B("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 12px;")};
D.Ml={position:D.n,baselineScaling:"zero",axisLine:{lineColor:"#8A8DAC",lineWidth:1,rendered:"on"},majorTick:{lineColor:"rgba(138,141,172,0.4)",lineWidth:1,rendered:"auto",lineStyle:"solid"},minorTick:{lineColor:"rgba(138,141,172,0.20)",lineWidth:1,rendered:"off",lineStyle:"solid"},tickLabel:{scaling:"auto",style:new D.B("font-size: 11px; color: #333333;"),rotation:"auto",rendered:"on"},titleStyle:new D.B("font-size: 11px; color: #737373;"),startGroupOffset:0,endGroupOffset:0,layout:{gapWidthRatio:1,
gapHeightRatio:1,titleGap:4},_useBaselineColor:D.p,isLayout:D.p};
D.Pl=function(a){this.Init(a.e,a.lg,a);this.ii=a};D.y.l(D.Pl,D.ta,"DvtAxisEventManager");D.Pl.prototype.Rs=function(a,b){b instanceof D.Ga&&b.fm()!=D.n&&this.lh(new D.ai(a,b.fm()),this.ii)};
D.Ll={};D.y.l(D.Ll,D.y,"DvtAxisRenderer");D.Ll.tsa=5;D.Ll.L=function(a,b){var c=a.za(),d=(0,D.Jl)(a.e,c,b);a.Gb=d;"off"==c.rendered||(0>=b.g||0>=b.j)||(a.wZ(b.clone()),D.Ll.fM(a,d,b),D.Ll.cM(a,d,b))};
D.Ll.fM=function(a,b,c){var d=a.za();if(d.title&&(b=d.position,!("radial"==b||"tangential"==b))){d.isLayout&&"bottom"==b&&(b="top");var e;"top"==b||"bottom"==b?(e=D.Ll.rda(a.Ua(),a,d.title,d.titleStyle,c.g,c.j),d=window.Math.ceil(d.layout.titleGap*d.layout.gapHeightRatio)):(e=D.Ll.rda(a.Ua(),a,d.title,d.titleStyle,c.j,c.g),d=window.Math.ceil(d.layout.titleGap*d.layout.gapWidthRatio));if(e){a=(0,D.C)(a.e);var f=e.cc();"top"==b?(e.ea(c.x+c.g/2-f.g/2),e.va(c.y),c.y+=f.j+d,c.j-=f.j+d):"bottom"==b?(e.ea(c.x+
c.g/2-f.g/2),e.va(c.y+c.j-f.j),c.j-=f.j+d):"left"==b?(e.lf(),e.Ge(),e.Tj(a?window.Math.PI/2:3*window.Math.PI/2),(0,D.G)(e,c.x+f.j/2,c.y+c.j/2),c.x+=f.j+d,c.g-=f.j+d):"right"==b&&(e.lf(),e.Ge(),e.Tj(a?window.Math.PI/2:3*window.Math.PI/2),(0,D.G)(e,c.x+c.g-f.j/2,c.y+c.j/2),c.g-=f.j+d)}}};D.Ll.cM=function(a,b,c){var d=a.za();"on"==d.tickLabel.rendered&&(d=d.position,"top"==d||"bottom"==d?D.Ll.cza(a,b,c):"tangential"==d?D.Ll.dza(a,b,c):D.Ll.eza(a,b,c))};
D.Ll.cza=function(a,b,c){for(var d=b.Ow(a.e),e=a.za().isLayout,f=0,g=(0,D.C)(a.e),h=0;h<d.length;h++){var j=d[h];if(j!=D.n){if(b.wV()){!e&&a.oS&&(j=D.Pa.Vb(j,c.j,c.g,a)?j:D.n);if(!j)continue;g?j.am():j.Dj();j.O(c.y)}else{if(D.Pa.sf(j).j-1>c.j)continue;j.lp();j.va(c.y)}a.Ua().ka(j,new D.Ga(j.Dq,D.n,D.n,{type:D.hi.Px,id:j.Ze()}));a.k(j);f=window.Math.max(f,D.Pa.sf(j).j)}}c.y+=f;c.j-=f;b=b.Ow(a.e,1);e=0;if(b!=D.n)for(h=0;h<b.length;h++)j=b[h],j!=D.n&&!(D.Pa.sf(j).j-1>c.j)&&(a.Ua().ka(j,new D.Ga(D.n,
D.n,D.n,{type:D.hi.Px,id:j.Ze()})),d[h]!=D.n&&(e=d[h].cc().g/2),g?j.ea(j.da()+e):j.ea(j.da()-e),j.lp(),j.va(c.y),a.k(j))};
D.Ll.eza=function(a,b,c){var d=a.za(),e=d.isLayout,f=d._alwaysAlignRight,g=d.position,d=(0,D.C)(a.e),h="radial"==g&&d||e&&"left"==g||!f&&!e&&"right"==g,j;"radial"==g?(j=c.x+c.g/2,j+=D.Ll.tsa*(d?1:-1)):j=h?c.x:c.x+c.g;for(var f=function(d){!e&&a.oS&&(d=D.Pa.Vb(d,c.g,c.j,a)?d:D.n);if(d){a.Ua().ka(d,new D.Ga(d.Dq,D.n,D.n,{type:D.hi.Px,id:d.Ze()}));d.ea(j);h?d.am():d.Dj();if("radial"==g){var f=d.ga();d.va(c.y+c.j/2-f);var l=d.C(),m=0.15*l.j,f=f+l.j/2>b.Wka()&&"circle"==a.za().polarGridShape?1:0.3,l=D.P.nA(l.x-
m,l.y,l.g+2*m,l.j,2,2,2,2),l=new D.Tb(a.e,l);l.qa("#FFFFFF",f);a.k(l)}a.k(d)}},l=b.Ow(a.e),d=0;d<l.length;d++){var m=l[d];m!=D.n&&f(m)}l=b.Ow(a.e,1);if(l!=D.n)for(d=0;d<l.length;d++)m=l[d],m!=D.n&&f(m)};D.Ll.dza=function(a,b,c){b=b.Ow(a.e);for(var d=0;d<b.length;d++){var e=b[d];if(e!=D.n){var f=e.Ze(),g=c.g/2-window.Math.abs(e.da()),h=c.j/2-window.Math.abs(e.ga());D.Pa.Vb(e,g,h,a)&&(a.Ua().ka(e,new D.Ga(e.wg()?f:D.n,D.n,D.n,{type:D.hi.Px,id:f})),e.F(c.x+c.g/2),e.O(c.y+c.j/2),a.k(e))}}};
D.Ll.rda=function(a,b,c,d,e,f){var g={type:D.hi.Np,id:D.i};c=new D.Ia(b.e,c,0,0);c.Ia(d);return D.Pa.Vb(c,e,f,b)?(a.ka(c,new D.Ga(c.Dq,D.n,D.n,g)),c):D.n};
D.sl=(0,D.s)();D.y.l(D.sl,D.y,"DvtAxisInfo");D.Jl=function(a,b,c){return b.timeAxisType&&"disabled"!=b.timeAxisType?new D.Zj(a,b,c):(0,window.isNaN)(b.dataMin)&&(0,window.isNaN)(b.dataMax)?new D.Yj(a,b,c):new D.Fl(a,b,c)};D.x=D.sl.prototype;
D.x.Init=function(a,b,c){this.e=a;this.Pc=b.position;this.mk=b._radius;"top"==this.Pc||"bottom"==this.Pc?(this.oh=c.x,this.Jh=c.x+c.g):"left"==this.Pc||"right"==this.Pc?(this.oh=c.y,this.Jh=c.y+c.j):"radial"==this.Pc?(this.oh=0,this.Jh=this.mk):"tangential"==this.Pc&&((0,D.C)(a)?(this.oh=2*window.Math.PI,this.Jh=0):(this.oh=0,this.Jh=2*window.Math.PI));this.QHa=this.Ih=this.di=this.Yf=this.Jf=this.kd=this.uc=D.n;this.qo=this.Eo=0;b.leftBuffer==D.n&&(b.leftBuffer=window.Infinity);b.rightBuffer==D.n&&
(b.rightBuffer=window.Infinity);this.M=b};D.x.G=(0,D.w)("M");D.x.Ow=(0,D.ca)(D.n);D.x.BH=(0,D.ca)(D.n);D.x.Pz=function(){return[]};D.x.dD=function(){return[]};D.x.sk=(0,D.ca)(D.n);D.x.VC=(0,D.ca)(D.n);D.x.UC=(0,D.ca)(D.n);D.x.ao=(0,D.ca)(D.n);D.x.hd=(0,D.ca)(D.n);D.x.Kz=(0,D.ca)(D.n);D.x.wV=(0,D.ca)(D.p);
D.x.Os=function(a,b,c){if("tangential"==this.Pc){var d=16/180*window.Math.PI,e=1/180*window.Math.PI,f=0.5*(0,window.parseInt)(this.M.tickLabel.style.v("font-size")),g=this.mk+f;if(c<e||c>2*window.Math.PI-e)g+=f;a=new D.Ia(a,b,window.Math.round(g*window.Math.sin(c)),window.Math.round(-g*window.Math.cos(c)));c<e||window.Math.abs(c-window.Math.PI)<e||c>2*window.Math.PI-e?a.lf():c<window.Math.PI?a.am():a.Dj();window.Math.abs(c-window.Math.PI/2)<d||window.Math.abs(c-3*window.Math.PI/2)<d?a.Ge():c<window.Math.PI/
2||c>3*window.Math.PI/2?a.Bw():a.lp()}else a=new D.Ia(a,b,c,c),a.Ge(),a.lf();a.Ia(this.M.tickLabel.style);return a};D.Cl=function(a,b,c,d){var e=!(0,D.Qa)()||1<(0,D.$i)();"radial"==a.Pc?("polygon"==a.M.polarGridShape?(d=D.Ni.QH(0,0,a.M._numGroups,d),b=new D.wh(b,d)):b=new D.Ah(b,0,0,d),(0,D.La)(b)):"tangential"==a.Pc?(b=new D.Pi(b,0,0,a.mk*window.Math.sin(d),-a.mk*window.Math.cos(d)),0.01>d%window.Math.PI/2&&e&&(0,D.Rd)(b)):(b=new D.Pi(b,d,d,d,d),e&&(0,D.Rd)(b));b.W(c);b.ia(D.p);return b};
D.Al=function(a,b,c){if(!b||0>=b.length)return D.p;var d="left"==a.Pc||"right"==a.Pc||"radial"==a.Pc,e=(0,D.C)(a.e);a=(0,D.zl)(a);for(var f,g,h,j,l=0;l<b.length;l+=c+1)if(b[l]!=D.n)if(f==D.n||g==D.n)d?(f=b[l].y,g=b[l].y+b[l].j):(f=b[l].x,g=b[l].x+b[l].g);else{if(d){if(h=b[l].y,j=b[l].y+b[l].j,h>=f&&h-a<g||h<f&&j+a>f)return D.k}else if(h=b[l].x,j=b[l].x+b[l].g,!e&&h-a<g||e&&j+a>f)return D.k;f=h;g=j}return D.p};
D.zl=function(a){var b=(0,window.parseInt)(a.M.tickLabel.style.v("font-size")),c=a instanceof D.Yj?0.3*b:1*b,b=a instanceof D.Yj?0.1*b:0.35*b;return"left"==a.Pc||("right"==a.Pc||"radial"==a.Pc)||a.wV()?b:c};D.Il=function(a,b,c){for(var d=0,e=(0,D.Al)(a,c,d);e;)d++,e=(0,D.Al)(a,c,d);if(0<d){a=[];for(c=0;c<b.length;c+=d+1)a.push(b[c]);return a}return b};D.Bl=function(a,b){for(var c=[],d=0;d<a.length;d++){var e=a[d];e==D.n?c.push(D.n):(e=e.cc(b),c.push(e))}return c};
D.Kl=function(a,b,c,d){var e=[];"undefined"==typeof d&&(d=1);for(var f=0;f<b.length;f++){var g=b[f];if(g==D.n)e.push(D.n);else{c.k(g);var h=D.Pa.sf(g),j=h.g*d,h=h.j;c.removeChild(g);g=a.wV()?new D.N(g.N()-h/2,g.K()-j/2,h,j):new D.N(g.da()-j/2,g.ga()-h/2,j,h);e.push(g)}}return e};D.x=D.sl.prototype;D.x.VU=(0,D.ca)(D.n);D.x.sW=(0,D.s)();D.x.aV=(0,D.ca)(D.n);D.x.tW=(0,D.s)();D.x.nN=(0,D.ca)(D.n);D.x.$U=(0,D.ca)(D.n);D.x.Kw=(0,D.w)("Jf");D.x.Jw=(0,D.w)("Yf");D.x.us=(0,D.w)("uc");D.x.Ww=(0,D.w)("kd");
D.x.R5=(0,D.w)("di");D.x.Q5=(0,D.w)("Ih");D.x.Pw=(0,D.ca)(0);D.x.Wka=(0,D.w)("Jh");D.x.jV=(0,D.w)("Eo");D.x.LU=(0,D.w)("qo");
D.Fl=function(a,b,c){this.Init(a,b,c)};D.y.l(D.Fl,D.sl,"DvtDataAxisInfo");D.x=D.Fl.prototype;
D.x.Init=function(a,b,c){D.Fl.o.Init.call(this,a,b,c);"top"==this.Pc||"bottom"==this.Pc?("off"!=b.tickLabel.rendered&&"off"!=b.rendered&&(this.Eo=window.Math.max(10-b.leftBuffer,0),this.qo=window.Math.max(10-b.rightBuffer,0)),(0,D.C)(a)?(this.Rh=this.Jh-this.qo,this.qj=this.oh+this.Eo):(this.Rh=this.oh+this.Eo,this.qj=this.Jh-this.qo)):"tangential"==this.Pc||"radial"==this.Pc?(this.Rh=this.oh,this.qj=this.Jh):(this.Rh=this.Jh,this.qj=this.oh);this.Jf=b.min;this.Yf=b.max;this.uc=b.viewportMin==D.n?
this.Jf:b.viewportMin;this.kd=b.viewportMax==D.n?this.Yf:b.viewportMax;this.Nf=b.step;this.iC=b.minorStep;this.j2=b.minStep;this.sh=D.n;b.tickLabel!=D.n&&(this.sh=b.tickLabel.converter);this.di=b.dataMin;this.Ih=b.dataMax;a="zero"==this.M.baselineScaling;b="on"==this.M._continuousExtent;a&&(this.di=window.Math.min(0,this.di),this.Ih=window.Math.max(0,this.Ih));c=(0,D.Gl)(this,this.Jf!=D.n?this.Jf:this.di,this.Yf!=D.n?this.Yf:this.Ih);this.di==this.Ih&&(0==this.di?this.Ih+=5*c:(this.di-=3*c,this.Ih+=
2*c));if(this.Jf==D.n)if(a&&0<=this.di)this.Jf=0;else if(b)this.Jf=this.di-0.1*(this.Ih-this.di),0<=this.di&&(this.Jf=window.Math.max(this.Jf,0));else if(!a&&this.Yf!=D.n)for(this.Jf=this.Yf;this.Jf>this.di;)this.Jf-=c;else this.Jf=window.Math.floor(this.di/c)*c;if(this.Yf==D.n)if(a&&0>=this.Ih)this.Yf=0;else if(b)this.Yf=this.Ih+0.1*(this.Ih-this.di),0>=this.Ih&&(this.Yf=window.Math.min(this.Yf,0));else if(a)this.Yf=(window.Math.floor(this.Ih/c)+1)*c;else for(this.Yf=this.Jf;this.Yf<=this.Ih;)this.Yf+=
c;this.Yf==this.Jf&&(this.Yf=100,this.Jf=0,c=(this.Yf-this.Jf)/10);this.uc==D.n&&(this.uc=this.Jf);this.kd==D.n&&(this.kd=this.Yf);if(this.uc!=this.Jf||this.kd!=this.Yf)c=(0,D.Gl)(this,this.uc,this.kd);this.Nf=this.Nf?this.Nf:c;"on"==this.M.alignTickMarks&&this.M._majorTickCount?(this.Zv=this.M._majorTickCount,this.Nf=(this.kd-this.Qz())/this.Zv,a=window.Math.pow(10,window.Math.ceil(window.Math.log(this.Nf)/window.Math.log(10)-1)),b=this.Nf/a,b=1<b&&1.5>=b?1.5:window.Math.ceil(b),this.Nf=b*a,this.kd=
this.Nf*this.Zv+this.Qz()):(this.j2!=D.n&&this.Nf<this.j2&&(this.Nf=this.j2),this.Zv=(this.kd-this.Qz())/this.Nf);this.yL=this.iC!=D.n&&2<=this.Nf/this.iC?this.M._minorTickCount?this.M._minorTickCount:this.Nf/this.iC:2;this.iC=this.Nf/this.yL};D.x.Qz=function(){return"zero"==this.M.baselineScaling||"on"==this.M._continuousExtent&&this.M.min==D.n?window.Math.ceil(this.uc/this.Nf)*this.Nf:window.Math.ceil((this.uc-this.Jf)/this.Nf)*this.Nf+this.Jf};
D.x.Ow=function(a,b){if(b&&0<b)return D.n;var c=[],d=[],d=a.Sc,e="tangential"==this.Pc;this.M.tickLabel&&this.M.tickLabel.scaling&&(this.aQ=new D.Mk(this.uc,this.kd,this.Nf,this.M.tickLabel.scaling,this.M.tickLabel.autoPrecision?this.M.tickLabel.autoPrecision:"on"));for(var f=0;f<=this.Zv;f++){var g=f*this.Nf+this.Qz();if(!(e&&g==this.kd)){var h=this.Lo(g),g=this.hd(g),h=this.Os(a,h,g);c.push(h)}}e||(d=(0,D.Bl)(c,d),c=(0,D.Il)(this,c,d));return c};
D.x.BH=function(a){var b=this.M.axisLine;return"on"==b.rendered?(b=new D.db(b.lineColor,1,b.lineWidth),(0,D.Cl)(this,a,b,this.qj)):D.n};
D.x.Pz=function(a){var b=[],c,d,e=this.M.majorTick;if("off"==e.rendered)return b;d=e.lineColor;var f=new D.db(d,1,e.lineWidth);e.lineStyle&&f.V((0,D.Md)(e.lineStyle));var g=f.clone();"inherit"!=e.baselineColor&&(d="auto"==e.baselineColor?D.O.il(d,0.4):e.baselineColor,g.Es(d));g.ha(e.baselineWidth!=D.n?e.baselineWidth:e.lineWidth);g.V((0,D.Md)(e.baselineStyle?e.baselineStyle:e.lineStyle));for(e=0;e<=this.Zv;e++)c=e*this.Nf+this.Qz(),"tangential"==this.Pc&&c==this.kd||(d=0==c?g:f,c=this.hd(c),d=(0,D.Cl)(this,
a,d,c),b.push(d));return b};D.x.dD=function(a){var b=[],c,d=this.M.minorTick;if("on"!=d.rendered)return b;var e=new D.db(d.lineColor,1,d.lineWidth);d.lineStyle&&e.V((0,D.Md)(d.lineStyle));for(d=-1;d<=this.Zv;d++)for(var f=d*this.Nf+this.Qz(),g=1;g<this.yL;g++){c=f+g*this.iC;if(c>this.kd)break;c<this.uc||(c=this.hd(c),c=(0,D.Cl)(this,a,e,c),b.push(c))}return b};D.x.sk=function(a){return a<this.uc||a>this.kd?D.n:this.hd(a)};
D.x.VC=function(a){var b=window.Math.min(this.Rh,this.qj),c=window.Math.max(this.Rh,this.qj);a<b?a=b:a>c&&(a=c);return this.ao(a)};D.x.UC=function(a){a<this.uc?a=this.uc:a>this.kd&&(a=this.kd);return this.hd(a)};D.x.ao=function(a){return this.uc+(a-this.Rh)/(this.qj-this.Rh)*(this.kd-this.uc)};D.x.hd=function(a){return this.Rh+(a-this.uc)/(this.kd-this.uc)*(this.qj-this.Rh)};D.x.Kz=function(){var a=0;0>this.kd?a=this.kd:0<this.uc&&(a=this.uc);return this.sk(a)};
D.x.Lo=function(a){if(this.sh&&(this.sh.getAsString||this.sh.format)){if(this.aQ)return this.aQ.Iq(a,this.sh);if(this.sh.getAsString)return this.sh.getAsString(a);if(this.sh.format)return this.sh.format(a)}else{if(this.aQ)return this.aQ.Iq(a);var b=window.Math.log(this.Nf)/window.Math.log(10),b=window.Math.max(window.Math.ceil(-b),0);return a.toFixed(b)}};
D.Gl=function(a,b,c){if(a.Nf)return a.Nf;a=c-b;if(0==a)return 0==b?10:window.Math.pow(10,window.Math.floor(window.Math.log(b)/window.Math.LN10)-1);b=window.Math.log(a)/window.Math.log(10);b=window.Math.pow(10,window.Math.ceil(b)-2);a=window.Math.round(a/b);return(10<=a&&14>=a?2:15<=a&&19>=a?3:20<=a&&24>=a?4:25<=a&&45>=a?5:46<=a&&80>=a?10:20)*b};D.x=D.Fl.prototype;D.x.VU=(0,D.w)("Zv");D.x.sW=function(a){this.Zv=a;this.Nf=(this.kd-this.uc)/this.Zv};D.x.aV=(0,D.w)("yL");
D.x.tW=function(a){this.yL=a;this.iC=this.Nf/this.yL};D.x.nN=(0,D.w)("Nf");D.x.$U=(0,D.w)("iC");D.x.Pw=function(){return(this.Yf-this.Jf)/64};D.x.jV=function(){return("top"==this.Pc||"bottom"==this.Pc)&&(0,D.C)(this.e)?this.qo:this.Eo};D.x.LU=function(){return("top"==this.Pc||"bottom"==this.Pc)&&(0,D.C)(this.e)?this.Eo:this.qo};
D.Yj=function(a,b,c){this.Init(a,b,c)};D.y.l(D.Yj,D.sl,"DvtGroupAxisInfo");
D.Yj.prototype.Init=function(a,b,c){D.Yj.o.Init.call(this,a,b,c);a=(0,D.C)(a);if(("top"==this.Pc||"bottom"==this.Pc)&&a)c=this.oh,this.oh=this.Jh,this.Jh=c;this.Oo=b.groups;c=0<b.endGroupOffset?(0,window.Number)(b.endGroupOffset):0;var d=0<b.startGroupOffset?(0,window.Number)(b.startGroupOffset):0;this.di=0;this.Ih=this.Oo.length-1;this.Jf=b.min==D.n?this.di-d:b.min;this.Yf=b.max==D.n?this.Ih+c:b.max;this.uc=b.viewportMin==D.n?this.Jf:b.viewportMin;this.kd=b.viewportMax==D.n?this.Yf:b.viewportMax;
var e=(0,D.Ql)(this,b.viewportStartGroup),f=(0,D.Ql)(this,b.viewportEndGroup);-1!=e&&(this.uc=e-d);-1!=f&&(this.kd=f+c);this.aja=a?b.rightBuffer:b.leftBuffer;this.bea=a?b.leftBuffer:b.rightBuffer;this.Afa=D.p;this.Yya=b._renderGridAtLabels;this.Xv=D.n};D.Sl=function(a,b,c,d){var e,f=(0,D.C)(a.e);a.Afa=D.k;(0,D.Rl)(a,d,d,b);for(var g=0;g<b.length;g++)d=b[g],d!=D.n&&(e=d.da(),d.ea(0),d.va(0),f?d.Tj(window.Math.PI/2):d.Tj(3*window.Math.PI/2),d.F(e));c=(0,D.Kl)(a,b,c);return(0,D.Il)(a,b,c)};
D.Yj.prototype.wV=(0,D.w)("Afa");D.Rl=function(a,b,c,d){b=window.Math.max(b-a.aja,0);c=window.Math.max(c-a.bea,0);var e=(0,D.C)(a.e);a.oh+=(b-a.Eo)*(e?-1:1);a.Jh-=(c-a.qo)*(e?-1:1);for(e=0;e<d.length;e++){var f=d[e];f&&f.ea(a.sk(e))}a.Eo=b;a.qo=c};D.x=D.Yj.prototype;D.x.Ow=function(a,b){if(b&&0<b)return D.n;this.Xv||(this.Xv=this.M0(a));return this.Xv};
D.x.M0=function(a){for(var b=[],c=a.Sc,d="top"==this.Pc||"bottom"==this.Pc,e=(0,D.C)(a),f=this.Oo.length,g,h,j=0;j<f;j++){var l=(0,D.Ok)(this,j),m=this.sk(j);m!=D.n?(h=this.Os(a,l,m),b.push(h),g||(g=h)):b.push(D.n)}if("tangential"==this.Pc)return b;a=g.cc();d&&(this.M._startOverflow!=D.n&&this.M._endOverflow!=D.n?(f=this.M._startOverflow,e=this.M._endOverflow):(g=h.cc(),f=e?a.g+a.x-this.oh:this.oh-a.x,e=e?this.Jh-g.x:g.g+g.x-this.Jh),(f>this.aja||e>this.bea)&&(0,D.Rl)(this,f,e,b));e=[];e=(0,D.Kl)(this,
b,c,0.3);f=(0,D.Kl)(this,b,c);if(!(0,D.Al)(this,f,0))return b;if(d){if("auto"==this.M.tickLabel.rotation){if((0,D.Al)(this,e,0))return(0,D.Sl)(this,b,c,a.j/2);e=(0,D.Bl)(b,c);return(0,D.Al)(this,e,0)?(0,D.Sl)(this,b,c,a.j/2):b}e=(0,D.Bl)(b,c);return(0,D.Il)(this,b,e)}return(0,D.Il)(this,b,f)};D.x.BH=function(a){var b=this.M.axisLine;return"on"==b.rendered?(b=new D.db(b.lineColor,1,b.lineWidth),(0,D.Cl)(this,a,b,0)):D.n};
D.x.Pz=function(a){var b=[],c,d=this.M.majorTick,e=new D.db(d.lineColor,1,d.lineWidth);d.lineStyle&&e.V((0,D.Md)(d.lineStyle));d=d.rendered;if("on"==d||"auto"==d&&"tangential"==this.Pc)for(var d=this.Oo.length,f=0;f<d;f++){if(this.Yya)c=this.sk(f);else if(this.sk(f+0.5))c=this.sk(f+0.5);else continue;c!=D.n&&(c=(0,D.Cl)(this,a,e,c),b.push(c))}return b};D.x.sk=function(a){return a<this.uc||a>this.kd?D.n:this.hd(a)};
D.x.VC=function(a){var b=window.Math.min(this.oh,this.Jh),c=window.Math.max(this.oh,this.Jh);a<b?a=b:a>c&&(a=c);return this.ao(a)};D.x.UC=function(a){a<this.uc?a=this.uc:a>=this.kd&&(a=this.kd);return this.hd(a)};D.x.ao=function(a){return this.uc+(a-this.oh)/((this.Jh-this.oh)/(this.kd-this.uc))};D.x.hd=function(a){return this.oh+(a-this.uc)*((this.Jh-this.oh)/(this.kd-this.uc))};D.Ok=function(a,b){b=window.Math.round(b);if(0>b||b>=a.Oo.length)return D.n;var c=a.Oo[b];c&&c.name&&(c=c.name);return c};
D.Ql=function(a,b){if(b==D.n)return-1;for(var c=-1,d=0;d<a.Oo.length;d++)if(b==(0,D.Ok)(a,d)){c=d;break}return c};D.Yj.prototype.Pw=(0,D.ca)(1);
D.Mk=function(a,b,c,d,e){this.af=new D.wa;this.Init(a,b,c,d,e)};D.y.l(D.Mk,D.Dl,"DvtLinearScaleAxisValueFormatter");
D.Mk.prototype.Init=function(a,b,c,d,e){this.Gia={};this.$r=[];this.dea={};var f=function(a,b,c){var d;this.af&&c&&(d=(0,D.ob)(this.af,c,D.n));c={Cs:b,cGa:d};this.Gia[a]=c;this.$r.push(c);this.dea[b]=c};f.call(this,"none",0);f.call(this,"thousand",3,"SCALING_SUFFIX_THOUSAND");f.call(this,"million",6,"SCALING_SUFFIX_MILLION");f.call(this,"billion",9,"SCALING_SUFFIX_BILLION");f.call(this,"trillion",12,"SCALING_SUFFIX_TRILLION");f.call(this,"quadrillion",15,"SCALING_SUFFIX_QUADRILLION");this.$r.sort(function(a,
b){return a.Cs<b.Cs?-1:a.Cs>b.Cs?1:0});var g=D.p,h,j,f=D.p;"off"!==e&&(f=D.k);d||(d="auto");if(d=this.Gia[d])j=d.Cs;"number"!==typeof j&&(g=D.k);if(g)if(g=window.Math.max(window.Math.abs(a),window.Math.abs(b)),g=(0,D.El)(g),j=0,g<=this.$r[0].Cs)j=this.$r[0].Cs;else if(g>=this.$r[this.$r.length-1].Cs)j=this.$r[this.$r.length-1].Cs;else for(d=this.$r.length-1;0<=d;d--)if(this.$r[d].Cs<=g){j=this.$r[d].Cs;break}f===D.k&&(0==c&&a==b?(a=j-(0,D.El)(b),h=0>=a?3+a:window.Math.max(a,4)):h=window.Math.max(j-
(0,D.El)(c),0));this.jAa=f;this.A3=j;this.j0=h};
D.Mk.prototype.Iq=function(a,b){var c=(0,window.parseFloat)(a);if((0,window.isNaN)(c))return a;var d;if(0<this.A3){for(d=0;d<this.A3;d++)c/=10;d=this.dea[this.A3].cGa}if(b&&b.getAsString)c=b.getAsString(c);else if(b&&b.format)c=b.format(c);else if(this.jAa&&!(0,window.isNaN)((0,window.parseFloat)(c))&&(c=(0,window.parseFloat)((new window.Number(c)).toFixed(this.j0)),c=""+c,0<this.j0)){-1==c.indexOf(".")&&(c+=".");for(var e=c.substring(c.indexOf(".")+1).length;e<this.j0;)c+="0",e++}"string"===typeof d&&
(c+=d);return c};D.El=function(a){a=0<=a?a:-a;var b=0;if(1E-15>a)return 0;if(window.Infinity==a)return window.Number.MAX_VALUE;if(10<=a)for(;10<=a;)b+=1,a/=10;else if(1>a)for(;1>a;)b-=1,a*=10;return b};
D.Zj=function(a,b,c){this.Init(a,b,c)};D.y.l(D.Zj,D.sl,"DvtTimeAxisInfo");
D.Zj.prototype.Init=function(a,b,c){D.Zj.o.Init.call(this,a,b,c);"top"==this.Pc||"bottom"==this.Pc?(!b._isOverview&&"on"==b.tickLabel.rendered&&(this.Eo=window.Math.max(10-b.leftBuffer,0),this.qo=window.Math.max(10-b.rightBuffer,0)),(0,D.C)(a)?(this.Rh=this.Jh-this.qo,this.qj=this.oh+this.Eo):(this.Rh=this.oh+this.Eo,this.qj=this.Jh-this.qo)):(this.Rh=this.oh,this.qj=this.Jh);this.sh=D.n;b.tickLabel!=D.n&&(this.sh=b.tickLabel.converter);this.Oo=b.groups;this.di=b.dataMin;this.Ih=b.dataMax;this.El=
1<this.Oo.length?(this.Ih-this.di)/(this.Oo.length-1):0;this.bp=b.step;a=0<b.endGroupOffset?b.endGroupOffset*this.El:0;c=0<b.startGroupOffset?b.startGroupOffset*this.El:0;this.Jf=b.min!=D.n?b.min:this.di-c;this.Yf=b.max!=D.n?b.max:this.Ih+a;this.uc=b.viewportMin==D.n?this.Jf:b.viewportMin;this.kd=b.viewportMax==D.n?this.Yf:b.viewportMax;0==this.El&&(this.El=(this.kd-this.uc)/6);b.viewportStartGroup!=D.n&&(this.uc=b.viewportStartGroup-c);b.viewportEndGroup!=D.n&&(this.kd=b.viewportEndGroup+a);this.xw=
this.kd-this.uc;this.uS=this.bC=this.gga=this.Xv=D.n;this.u1=D.k;b=new D.wa;this.Qm=[(0,D.ob)(b,"MONTH_SHORT_JANUARY",D.n),(0,D.ob)(b,"MONTH_SHORT_FEBRUARY",D.n),(0,D.ob)(b,"MONTH_SHORT_MARCH",D.n),(0,D.ob)(b,"MONTH_SHORT_APRIL",D.n),(0,D.ob)(b,"MONTH_SHORT_MAY",D.n),(0,D.ob)(b,"MONTH_SHORT_JUNE",D.n),(0,D.ob)(b,"MONTH_SHORT_JULY",D.n),(0,D.ob)(b,"MONTH_SHORT_AUGUST",D.n),(0,D.ob)(b,"MONTH_SHORT_SEPTEMBER",D.n),(0,D.ob)(b,"MONTH_SHORT_OCTOBER",D.n),(0,D.ob)(b,"MONTH_SHORT_NOVEMBER",D.n),(0,D.ob)(b,
"MONTH_SHORT_DECEMBER",D.n)]};
D.Lk=function(a,b,c){var d=D.n,e=D.n,f="left"==a.Pc||"right"==a.Pc;if(a.sh&&a.sh.getAsString)d=a.sh.getAsString(b);else if(a.sh&&a.sh.format)d=a.sh.format(b);else if(31536E6<=a.bp)d=(0,D.tl)(a,b,D.p,D.p,D.k);else if(31536E6<=a.xw||24192E5<=a.bp){if(c==D.n||c.getMonth()!=b.getMonth())d=(0,D.tl)(a,b,D.p,D.k,D.p);if(c==D.n||c.getYear()!=b.getYear())e=(0,D.tl)(a,b,D.p,D.p,D.k)}else if(24192E5<=a.xw||864E5<=a.bp){if(c==D.n||c.getDate()!=b.getDate())d=(0,D.tl)(a,b,D.k,D.p,D.p);c==D.n||c.getYear()!=b.getYear()?
e=(0,D.tl)(a,b,D.p,D.k,D.k):c.getMonth()!=b.getMonth()&&(e=(0,D.tl)(a,b,D.p,D.k,D.p))}else{if(36E5<=a.xw||6E4<=a.bp){if(c==D.n||c.getHours()!=b.getHours()||c.getMinutes()!=b.getMinutes())d=(0,D.ul)(a,b,D.p)}else if(c==D.n||c.getSeconds()!=b.getSeconds())d=(0,D.ul)(a,b,D.k);if(f){if(c==D.n||c.getDate()!=b.getDate())e=(0,D.tl)(a,b,D.k,D.k,D.p)}else c==D.n||c.getYear()!=b.getYear()?e=(0,D.tl)(a,b,D.k,D.k,D.k):c.getMonth()!=b.getMonth()?e=(0,D.tl)(a,b,D.k,D.k,D.p):c.getDate()!=b.getDate()&&(e=(0,D.tl)(a,
b,D.k,D.p,D.p))}return[d,e]};D.tl=function(a,b,c,d,e){var f=b.getFullYear(),g;g=a.Qm&&12<=a.Qm.length?a.Qm[b.getMonth()]:b.toString().split(" ")[1];b=b.getDate();if(a.Qm&&17<a.Qm.length){var h=a.Qm[17],f=f+a.Qm[16];b+=h}h="DMY";a.Qm&&15<a.Qm.length&&(h=a.Qm[15]);a="";for(var j=0;j<h.length;j++)c&&"D"==h[j]?a+=b+" ":d&&"M"==h[j]?a+=g+" ":e&&"Y"==h[j]&&(a+=f+" ");return 0<a.length?a.slice(0,a.length-1):a};
D.ul=function(a,b,c){var d=b.getHours(),e=b.getMinutes();b=b.getSeconds();var f="",g="",h=D.p;a.Qm!=D.n&&14<a.Qm&&(f=a.Qm[12],g=a.Qm[13],h="t"==a.Qm[14]);a=""!=f&&""!=g;var j;a&&(j=g,12<d?(d-=12,j=g):0==d?(j=f,d=12):12>d&&(j=f));d=(10>d?"0"+d:""+d)+":"+(10>e?"0"+e:""+e);c&&(d+=":"+(10>b?"0"+b:""+b));return a?h?j+" "+d:d+" "+j:d};
D.vl=function(a){return 316224E5<=a.El?316224E5:26784E5<=a.El||316224E5<=a.xw?26784E5:864E5<=a.El||26784E5<=a.xw?864E5:36E5<=a.El||864E5<=a.xw?36E5:3E5<=a.El||36E5<=a.xw?3E5:6E4<=a.El||3E5<=a.xw?6E4:5E3<=a.El||6E4<=a.xw?5E3:1E3};
D.yl=function(a,b,c){var d=[],e;e=new window.Date(a);if(31536E6<=c&&316224E5>=c){e.setMonth(0,1);e=e.getTime();for(e<a&&(e=(0,D.wl)(e));e<=b;)d.push(e),e=(0,D.wl)(e)}else if(24192E5<=c&&26784E5>=c){e.setDate(1);e=e.getTime();for(e<a&&(e=(0,D.xl)(e));e<=b;)d.push(e),e=(0,D.xl)(e)}else{e.setMonth(0,1);864E5>c&&e.setHours(0,0,0,0);for(e=e.getTime()+window.Math.ceil((a-e.getTime())/c)*c;e<=b;)d.push(e),e+=c}return d};D.wl=function(a){a=new window.Date(a);a.setFullYear(a.getFullYear()+1);return a.getTime()};
D.xl=function(a){a=new window.Date(a);a.setMonth(a.getMonth()+1);return a.getTime()};D.x=D.Zj.prototype;
D.x.M0=function(a){var b=[],c=[],d=[],e=[],f=[],g=D.n,h=0,j=0,l=a.Sc,j=(0,D.C)(a),m="left"==this.Pc||"right"==this.Pc,o="off"!=this.M.zoomAndScroll;if(o)var q=D.k;var r=0;m&&(0,D.lh)()&&(r=0.2*(0,window.parseInt)(this.M.tickLabel.style.v("font-size")));var t=[],h=0;if(this.bp!=D.n)t=(0,D.yl)(this.uc,this.kd,this.bp);else if("mixedFrequency"==this.M.timeAxisType)this.bp=(0,D.vl)(this),t=(0,D.yl)(this.uc,this.kd,this.bp),h=window.Math.floor(this.El/this.bp)-1;else{for(var u=0;u<this.Oo.length;u++)this.Oo[u]>=
this.uc&&this.Oo[u]<=this.kd&&t.push(this.Oo[u]);this.bp=this.El;u=new D.Ia(a,(0,D.Lk)(this,new window.Date(t[0]))[0],0,0);if(((m?D.Pa.sf(u).j:u.cc().g)+(0,D.zl)(this))*(t.length-1)>window.Math.abs(this.Rh-this.qj))this.bp=(0,D.vl)(this),t=(0,D.yl)(this.uc,this.kd,this.bp),h=window.Math.floor(this.El/this.bp)-1}0==t.length&&(t=[this.uc]);for(u=0;u<t.length;u++){var z=t[u],A=this.sk(z);if(A!=D.n){var z=new window.Date(z),F=(0,D.Lk)(this,z,g),g=F[0],F=F[1];g!=D.n?(d.push({text:g,aBa:F!=D.n?A+r:A}),
e.push(A)):(d.push(D.n),e.push(D.n));b.push(D.n);o&&q&&(A=this.uc?this.sk(this.uc):A,q=D.p);F!=D.n?(g=this.Os(a,F,F!=D.n?A-r:A),f.push(A),m||(j?g.Dj():g.am()),c.push(g),this.u1=D.p):(c.push(D.n),f.push(D.n));g=z}}a=b;for(var H=[],E=[],j=0;j<d.length;j++)d[j]!=D.n&&(H.push(d[j]),E.push(D.n));for(var M="left"==this.Pc||"right"==this.Pc,S=this,q=function(a){E[a]==D.n&&(H[a].label=S.Os(l.e,H[a].text,H[a].aBa),E[a]=M?D.Pa.sf(H[a].label):H[a].label.cc(l));return M?E[a].j:E[a].g},j=(q(0)+(0,D.zl)(this))*
(H.length-1),r=window.Math.abs(this.Rh-this.qj),h=window.Math.max(h,0<r?window.Math.ceil(j/r)-1:0),j=D.k;j;){for(j=0;j<H.length;j++)0==j%(h+1)?(q(j),H[j].Kna=D.p):H[j].Kna=D.k;j=(0,D.Al)(this,E,h);h++}for(j=q=0;j<d.length;j++)d[j]!=D.n&&!d[j].Kna&&(a[j]=d[j].label,q++);h=q;d=c;a=(0,D.Bl)(c,l);if(!a||0>=a.length)j=D.p;else{for(var q="left"==this.Pc||"right"==this.Pc,j=(0,window.parseInt)(this.M.tickLabel.style.v("font-size")),j=q?0.1*j:0.3*j,r=0,J,aa,A=0;A<a.length;A++)a[A]!=D.n&&(q?(t=a[A].y,u=a[A].y+
a[A].j):(t=a[A].x,u=a[A].x+a[A].g),J!=D.n&&(aa!=D.n&&(t>=J&&t-j<aa||t<J&&u+j>J))&&(d[A]=D.n),d[A]!=D.n&&(J=t,aa=u,r++));j=r}if(!o&&1<j&&h<=1.5*j){b=c;c=D.n;for(o=0;o<b.length;o++)b[o]!=D.n&&b[o].lf()}if(m&&c!=D.n){var m=b,o=c,oa=0.1*(0,window.parseInt)(this.M.tickLabel.style.v("font-size"));J=function(a,b){return b.y>=a.y&&b.y-oa<a.y+a.j||b.y<a.y&&b.y+b.j+oa>a.y?D.k:D.p};d=D.n;a=D.p;for(aa=0;aa<m.length;aa++)if(m[aa]&&o[aa])if(m[aa].lp(),o[aa].Bw(),d&&J(d,D.Pa.sf(m[aa]))){a=D.k;break}else if(m[aa+
1]&&J(D.Pa.sf(m[aa]),D.Pa.sf(m[aa+1]))){a=D.k;break}else d=D.Pa.sf(o[aa]);else if(m[aa]||o[aa])if(q=m[aa]?m[aa]:o[aa],d&&J(d,D.Pa.sf(q))){a=D.k;break}else d=D.Pa.sf(q);if(a){q=a=d=D.n;for(aa=0;aa<m.length;aa++)o[aa]?(m[aa]=D.n,o[aa].Ge(),h=D.Pa.sf(o[aa]),a&&J(a,h)&&(m[d]=D.n),q=h):m[aa]&&(h=D.Pa.sf(m[aa]),q&&J(q,h)?m[aa]=D.n:(a=h,d=aa))}}this.Xv=b;this.gga=c;this.bC=e;this.uS=f};D.x.Ow=function(a,b){if(b&&1<b)return D.n;this.Xv||this.M0(a);return 1==b?this.gga:this.Xv};
D.x.BH=function(a){var b=this.M.axisLine;return"on"==b.rendered?(b=new D.db(b.lineColor,1,b.lineWidth),(0,D.Cl)(this,a,b,10)):D.n};
D.x.Pz=function(a){var b=this.M.majorTick;if("on"!=b.rendered)return[];var c=[];if(this.u1)for(var d=0;d<this.bC.length;d++)this.bC[d]!=D.n&&this.Xv[d]!=D.n&&c.push(this.bC[d]);else for(d=0;d<this.uS.length;d++)this.uS[d]!=D.n&&c.push(this.uS[d]);var e=new D.db(b.lineColor,1,b.lineWidth);b.lineStyle&&e.V((0,D.Md)(b.lineStyle));b=[];for(d=0;d<c.length;d++)c[d]>=this.Rh&&c[d]<=this.qj&&b.push((0,D.Cl)(this,a,e,c[d]));return b};
D.x.dD=function(a){var b=this.M.minorTick;if("on"!=b.rendered||this.u1)return[];for(var c=[],d=0;d<this.bC.length;d++)this.bC[d]!=D.n&&this.Xv[d]!=D.n&&c.push(this.bC[d]);var e=new D.db(b.lineColor,1,b.lineWidth);b.lineStyle&&e.V((0,D.Md)(b.lineStyle));b=[];for(d=0;d<c.length;d++)c[d]>=this.Rh&&c[d]<=this.qj&&b.push((0,D.Cl)(this,a,e,c[d]));return b};D.x.sk=function(a){return a<this.uc||a>this.kd?D.n:this.hd(a)};
D.x.VC=function(a){var b=window.Math.min(this.Rh,this.qj),c=window.Math.max(this.Rh,this.qj);a<b?a=b:a>c&&(a=c);return this.ao(a)};D.x.UC=function(a){a<this.uc?a=this.uc:a>this.kd&&(a=this.kd);return this.hd(a)};D.x.ao=function(a){return this.uc+(a-this.Rh)/(this.qj-this.Rh)*(this.kd-this.uc)};D.x.hd=function(a){return this.Rh+(a-this.uc)/(this.kd-this.uc)*(this.qj-this.Rh)};D.x.OU=function(){return window.Math.abs(this.hd(this.uc+this.El)-this.hd(this.uc))};D.x.Pw=(0,D.w)("El");
D.x.jV=function(){return("top"==this.Pc||"bottom"==this.Pc)&&(0,D.C)(this.e)?this.qo:this.Eo};D.x.LU=function(){return("top"==this.Pc||"bottom"==this.Pc)&&(0,D.C)(this.e)?this.Eo:this.qo};
});