"use strict";
define(['./DvtToolkit', './DvtSubcomponent'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.UB=(0,D.s)();(0,D.ra)("DvtBaseTreeView",D.UB);D.y.l(D.UB,D.mB,"DvtBaseTreeView");D.x=D.UB.prototype;D.x.Init=function(a,b,c){D.UB.o.Init.call(this,a,b,c);this.Ca=this.hE(this,a,this.Wa,this);this.Ca.Df(this);this.Vk=new D.ad(a);this.w0=new D.Xe(this);(0,D.bd)(this.Ca,this.Vk);this.WX=this.Ba=D.n;this.$ea=D.p;this.CL=D.n};
D.x.L=function(a,b,c){this.pb=b;this.Cb=c;this.Ca&&this.Ca.zc();this.pn&&!a&&(a=this.WX);a&&(this.WX=a);a&&(b=this.Wu(a),this.HI(b));c=new D.N(0,0,this.pb,this.Cb);this.xo(c);b=new D.I(this.e);this.k(b);this.n4&&(this.DZ=new D.Nn(this.e,this.Ca),this.DZ.DG=D.k);this.Fi(b,c);this.pn&&(this.HW=D.k,this.pn.stop());var d=new D.N(0,0,this.pb,this.Cb);c=D.p;if(this.ca){if(this.FI&&a)if(D.cg.isSupported(this.FI))this.pn=D.cg.EH(this.e,this.FI,this.ca,b,d,this.cE),c=D.k;else if(this.LL&&"auto"==this.FI){this.kj=
this.rX();this.k(this.kj);var d=new D.Ye(this.e,this.kj),e=this.LL,f=this.Pa,g=this.LS,h=this.ey;d.SJ=D.p;d.LL=e;d.LS=g;(0,D.Me)(h,e)||(0,D.Me)(g,f)?(d.SJ=D.k,g=(0,D.Hb)(e),h=(0,D.Hb)(f),g.push(e),h.push(f),(0,D.Ke)(d,g,h)):(0,D.Ke)(d,[e],[f]);this.pn=d.os()}}else this.pn=this.tX(b,d);this.LS=this.LL=D.n;this.pn&&(this.Ca.Bs(this),this.pn.Md(this.Kp,this),this.pn.play());c?this.al=this.ca:this.ca&&this.removeChild(this.ca);this.ca=b;a?(this.wG(),(0,D.nC)(this,!this.pn)):this.FY()};D.x.Wu=(0,D.ca)(D.n);
D.x.xo=(0,D.s)();D.x.Fi=(0,D.s)();D.XB=function(a,b){var c=new D.D(a.e,0,0,a.pb,a.Cb);(0,D.La)(c);b.k(c)};D.VB=function(a,b){if(a.ey&&0<a.ey.length){var c=a.Pa?a.Pa.Of():D.n;a.Hl&&(0,D.xu)(a.Ca,a.Hl.Tc());a.Hl=D.cf.L(a,b,a.ey,c);(0,D.yu)(a.Ca,a.Hl.Tc())}else a.Hl&&(0,D.xu)(a.Ca,a.Hl.Tc()),a.Hl=D.n};D.WB=function(a,b){var c=D.n;if(a.fga&&a.PZ)for(var d=0;d<a.PZ.length;d++){var e=a.PZ[d];if(e.id==a.fga){c=e.ku;break}}if(a.Via||a.cda||c)a.Ba=D.ef.L(a,b,a.yh.legendSize,a.yh.legendColor,a.Via,a.cda,c)};
D.ZB=function(a,b){if(a.Yp){var c=new D.Ia(a.e,a.Yp,a.pb/2,a.Cb/2);c.lf();c.Ge();D.Pa.Vb(c,a.pb-4,a.Cb-4,a);b.k(c)}};D.YB=function(a){return a.Pa&&0<a.Pa.yc()};D.x=D.UB.prototype;D.x.tX=function(a,b){return D.cg.isSupported(this.GW)?D.cg.KH(this.e,this.GW,a,b,this.cE):D.n};D.x.Kp=function(){this.kj&&(this.removeChild(this.kj),this.kj=D.n);this.al&&(this.removeChild(this.al),this.al=D.n);this.HW=D.p;this.pn=D.n;this.Ca.Df(this);(0,D.nC)(this,D.k)};D.x.rX=function(){return new D.I(this.e)};D.x.Cx=function(a){return new D.ff(a)};
D.x.hE=function(a,b,c,d){return new D.ec(a,b,c,d)};D.x.Y9=(0,D.ba)();D.x.Ua=(0,D.w)("Ca");D.oC=function(a,b){var c=b,d=a.ub();if(d)for(var e=0;e<d.length;e++)var f=(0,D.oC)(d[e],b+1),c=window.Math.max(c,f);return c};
D.UB.prototype.HI=function(a){this.LL=this.Pa;this.LS=this.ey;this.Rl=a.mGa;this.yh=a.wna?a.wna:{};this.Pa=a.root;this.Yp=a.u5;this.ey=a.GAa;this.WIa=new D.cb(a.FBa,a.GBa);this.XIa=new D.db(a.EBa);this.GW=a.S4;this.FI=a.JAa;this.cE=a.HAa;this.AP=a.sHa;this.Rn=a.vHa;this.eha=a.bna;a.C8&&(this.n4=a.C8);this.eha?(this.Mb=new D.fd(a.bna),this.SB=a.ZGa):this.Mb=D.n;this.Ca.tA(this.Mb);this.Ca.Bx=a.b5;(0,D.gk)(this.Ca,this.Cx(this.Ca));this.Pa&&(this.mq=(0,D.oC)(this.Pa,0));this.PZ=a.ku;this.fga=a.VFa;
this.Via=a.qHa;this.cda=a.ZAa};D.UB.prototype.FY=function(){for(var a=this.Mb?this.Mb.getSelection():[],b=0;b<a.length;b++)a[b].Pb(D.k)};D.UB.prototype.wG=function(){if(this.Mb&&this.SB){var a=[];(0,D.pC)(this,this.Pa,a);(0,D.kd)(this.Mb,this.SB,a);this.SB=D.n}};D.nC=function(a,b){var c=D.n,d=a.CL;d&&(c=(0,D.Je)(a.Pa,d),a.Ca.Fs(c));b&&(a.CL=D.n);c||(c=a.Y9(a.Pa),a.Ca.Fs(c));b&&a.xp(a.vV())};D.UB.prototype.xp=function(a){this.$ea=a;this.Ca.xp(a)};D.UB.prototype.vV=(0,D.w)("$ea");
D.pC=function(a,b,c){if(b&&(c.push(b),b=b.ub()))for(var d=0;d<b.length;d++)(0,D.pC)(a,b[d],c)};D.UB.prototype.IE=function(a){return this.Mb?a[0]:D.n};D.UB.prototype.ay=function(a){a.Ma()||(this.Mb.cj(a,D.p),this.Ca.Hq());a=[];for(var b=this.Mb.getSelection(),c=0;c<b.length;c++)a.push(b[c].getId());return a};D.UB.prototype.$x=function(){for(var a=[],b=this.Mb.getSelection(),c=0;c<b.length;c++)a.push(b[c].MP());return a};D.UB.prototype.dta=function(a){a instanceof D.Ea&&(0,D.Ce)(this,a.getId(),D.p)};
D.Ce=function(a,b,c){c&&a.Pa&&b==a.Pa.getId()&&a.ey&&0<a.ey.length?(a.CL=b,a.Wa(new D.qC(a.ey[0].id))):c||a.Wa(new D.qC(b));a.e.Vd().zc()};D.UB.prototype.i6=function(a){return this.Ca.ma(a)};D.UB.prototype.jc=function(){this.af||(this.af=new D.wa);return this.af};D.UB.prototype.Vh=function(){return new D.Te(this)};D.UB.prototype.getAutomation=D.UB.prototype.Vh;
D.UB.prototype.Oj=function(a,b,c){return this.Vk.Oj(c)};D.UB.prototype.kl=function(a,b){return this.Vk.kl(a,b)};

D.Ye=function(a,b){this.Init(a,b)};D.y.l(D.Ye,D.Ze,"DvtBaseTreeAnimationHandler");D.Me=function(a,b){if(!b||!a)return D.p;for(var c=0;c<a.length;c++)if(a[c].id==b.getId())return D.k;return D.p};
D.Xe=(0,D.v)("I");D.y.l(D.Xe,D.$d,"DvtBaseTreeDropTarget");
D.ec=function(a,b,c,d){this.Init(b,c,d);this.I=a};D.y.l(D.ec,D.ta,"DvtBaseTreeEventManager");D.x=D.ec.prototype;D.x.yo=function(a){D.ec.o.yo.call(this,a);var b=this.ma(a.target);b&&(a=a.shiftKey,b.Xq&&b.Xq()&&(0,D.Ce)(this.I,b.getId(),a))};D.x.mh=function(a){D.ec.o.mh.call(this,a);a=this.ma(a.target);(0,D.De)(this,a)};D.x.zo=function(a){D.ec.o.zo.call(this,a);(a=this.ma(a.target))&&a.Xw&&a.Xw()};
D.x.fj=function(a){D.ec.o.fj.call(this,a);var b=this.ma(a.target);b&&b.Uq&&(a=(a=this.ma(a.relatedTarget))&&a.getId?a.getId():D.n,(b.getId()==D.n||a!=b.getId())&&b.Uq())};D.x.rm=function(a){var b=D.p,b=this.Ie();13==a.keyCode&&!a.ctrlKey?(b=this.Ie(),b.Xq&&b.Xq()&&(a.shiftKey&&(b=this.I.Pa),(0,D.Ce)(this.I,b.getId(),a.shiftKey)),a.preventDefault(),b=D.k):b=D.ec.o.rm.call(this,a);return b};
D.x.Su=function(a){a=this.ma(a.target);(0,D.De)(this,a);this.uK&&this.uK!=a&&(this.uK.Uq(),this.uK=D.n);a&&a instanceof D.ub&&this.uK!=a&&(this.uK=a,a.Xw())};D.x.HA=function(a){(a=this.ma(a.target))&&a.Xq&&a.Xq()&&(0,D.Ce)(this.I,a.getId(),D.p)};D.De=function(a,b){b&&(b instanceof D.Zb&&b.jy)&&(0,D.Ce)(a.I,b.getId(),D.p)};
D.qb=(0,D.s)();D.y.l(D.qb,D.y,"DvtBaseTreeParser");D.x=D.qb.prototype;D.x.Init=function(a){this.I=a;this.Yo=new D.td;this.i2=window.Infinity;this.c2=-window.Infinity};
D.x.parse=function(a){a=a.replace(/&Oslash;/gi,"\u00f8");var b=this.Yo.parse(a);a=this.qm(b);var b=b.ub(),c;c=(0,D.$e)(b,"f");var d=c.length;if(0<d){for(var e,f,g={},h=0;h<d;h++)e=c[h],f=e.q("name"),g[f]=D.K.pl(e);c=g}else c=D.n;a.C8=c;this.Rl=0;e=(0,D.$e)(b,"n");d=[];for(c=0;c<e.length;c++)(f=this.uG(e[c],a.C8))&&d.push(f);a.mGa=this.Rl;if(1==d.length)c=d[0];else{c=this.I;for(f=e=0;f<d.length;f++)e+=d[f].yc();c=this.qn(c,{size:e,OAa:D.k,nka:D.k});(0,D.He)(c,d)}a.root=c;for(c=0;c<b.length;c++)if(e=
b[c],d=a,e)if(f=e.getName(),"spb"==f){f=e;e=d;var j=f,g=j.q("popupId"),h=j.q("triggerType"),l=j.q("alignId"),j=j.q("align"),g=new D.Od(g,h,l,j);f=f.q("T");e.BI||(e.BI={});e.BI[f]||(e.BI[f]=[]);e.BI[f].push(g);d.Ina||(d.Ina=[]);d.Ina.push(D.i)}else if("menus"==f)d.b5||(d.b5=new D.af(this.I.e)),d.b5.add(e);else if("ag"==f){h=e;g=D.i;e=h.q("id");f=h.q("T");if("continuous"==h.q("t")){var g=h.q("minValue"),l=h.q("maxValue"),j=h.q("minLabel"),m=h.q("maxLabel"),h=h.q("ramp").split(";");g==D.n&&(g=this.i2);
l==D.n&&(l=this.c2);g=new D.fb(g,l,j,m,h)}else{g=new D.hb;h=h.ub();for(l=0;l<h.length;l++){var o=h[l];o&&(j=o.q("g"),m=o.q("l"),o={color:o.q("c"),pattern:o.q("p")},g.add(j,m,o))}}d.ku||(d.ku=[]);d.ku.push({ku:g,B8:f,id:e})}else if("styles"==f)d.vHa=this.c3(e,d);else if("a"==f){f=[];e=e.ub();for(g=0;g<e.length;g++)h=e[g].q("id"),l=e[g].q("l"),f.push({id:h,text:l});d.GAa=f}else if("resources"==f){f={};e=e.getAttributes();for(g=0;g<e.length;g++)f[e[g].name]=e[g].value;d.wna=f}this.Go(a.root,a);return a};
D.x.qn=(0,D.ca)(D.n);D.x.qm=function(a){var b={},c=a.q("sel");b.bna="none"==c?D.n:"single"==c?"s":"m";b.sHa=a.q("sort");if(c=a.q("selIds"))b.ZGa=c.split(",");b.u5=a.q("emptyText");b.VFa=a.q("ls");b.qHa=a.q("sv");b.ZAa=a.q("cv");if(c=a.q("adu"))b.HAa=c/1E3;b.JAa=a.q("adc");b.S4=a.q("adi");return b};
D.x.Xu=function(a){var b={};b.B8=a.q("T");b.kGa=a.q("M");b.gU=a.q("ag");b.id=a.q("id");b.size=(0,window.Number)(a.q("s"));b.color=a.q("c");b.pattern=a.q("p");b.label=a.q("l");b.yHa=a.q("tt");b.DV=a.q("ld");b.DBa=a.q("d");b.nka="t"==a.q("di")?D.k:D.p;b.YGa=a.q("nsel");var c=a.q("tn");c&&(b.Ona=c);if(a=a.q("ls"))b.xu=new D.B(a);b.gU!=D.n&&(this.c2=window.Math.max(this.c2,b.gU),this.i2=window.Math.min(this.i2,b.gU));return b};
D.x.uG=function(a,b){if(!a||"n"!=a.getName())return D.n;this.Rl++;var c=this.Xu(a),c=this.qn(this.I,c,b);(0,D.He)(c,this.aT(a,c,b));return c};D.x.aT=function(a,b,c){var d=[];a=a.ub();for(var e=0;e<a.length;e++){var f=a[e];f&&("el"==f.getName()?c&&b.Kaa&&b.Kaa((0,D.bf)(f)):b.Za()&&d.push(this.uG(f,c)))}return d};
D.x.Go=function(a,b){if(a){var c=a.cp;if(b.BI){var d=b.BI[c];d&&a.uA(d)}if(b.ku)for(var e=0;e<b.ku.length;e++)if(d=b.ku[e],d.B8==c){if(d.ku instanceof D.fb&&(c=a,d=d.ku.get(c.uta)))c.Ug=d;break}if(c=a.ub())for(d=0;d<c.length;d++)this.Go(c[d],b)}};D.$e=function(a,b){for(var c=[],d=0;d<a.length;d++){var e=a[d];e&&e.getName()==b&&c.push(e)}return c};
D.qb.prototype.c3=function(a,b){var c={},d=new D.B(a.q("top"));c.BACKGROUND_STYLE=d;c.ANIMATION_UPDATE_COLOR_STYLE=d.v("-tr-animation-update-color");d=new D.B(a.q("node"));c.LABEL_TEXT_DEFAULT_STYLE=d;var e=d.clone().Ob(new D.B(a.q("node-hover"))),f=d.clone().Ob(new D.B(a.q("node-selected")));b.FBa=a.q("dsf");b.EBa=a.q("dsb");b.GBa=a.q("dso");this.kY(d,e,f,c);this.naa(a,c);d=new D.B(a.q("rootText"));c.TEXT_STYLE=d;d=new D.B(a.q("attrType"));c.ATTRIBUTE_TYPE_STYLE=d;d=new D.B(a.q("attrValue"));c.ATTRIBUTE_VALUE_STYLE=
d;d=new D.B(a.q("drillText"));c.DRILL_TEXT_STYLE=d;d=new D.B(a.q("currentText"));c.CURRENT_TEXT_STYLE=d;return c};D.qb.prototype.kY=(0,D.s)();D.qb.prototype.naa=(0,D.s)();
D.ub=(0,D.s)();D.y.l(D.ub,D.y,"DvtBaseTreeNode");D.Fe=new D.Ee("#000000",2,5,5,45,0.5);
D.ub.prototype.Init=function(a,b,c){this.I=a;this.cp=b.B8;this.h2=b.kGa;this.uta=b.gU;this.Oa=b.id;this.ok=b.size;this.Ug=b.color?b.color:"#000000";this.Zo=b.pattern;this.Bz=b.label;this.Ey=b.yHa;this.Im=b.xu;this.sR=b.DBa;this.Dg=b.nka;this.VE=b.OAa;this.gt=1;this.sS=D.n;this.Zd=D.p;this.n4=c;b.Ona?(0,D.Ge)(this,b.Ona):c&&c.content?(0,D.Ge)(this,"content"):c&&c.rootContent&&(0,D.Ge)(this,"rootContent");this.bJ=D.p;this.pw=b.YGa;this.jd=a.jc()};
D.He=function(a,b){if(b!=D.n)for(var c=0;c<b.length;c++)b[c].Bf=a;a.ve=b};D.ub.prototype.ub=(0,D.w)("ve");D.Hb=function(a){var b=[],c,d;if(!a.Ke())return b;for(var e=0;e<a.ve.length;e++)d=a.ve[e],c=(0,D.Hb)(d),b.push(d),b=b.concat(c);return b};D.Jb=function(a){var b=a.Bf;b&&(b.sS=a)};D.ub.prototype.rD=function(a){return!a||!this.Bf?D.p:this.Bf==a?D.k:this.Bf.rD(a)};
D.Db=function(a,b,c){var d=[];if(0>c)return d;if(0==c)return[a];if(b.Ke()){a=b.ub();for(var e=0;e<a.length;e++)b=a[e],d=d.concat((0,D.Db)(b,b,c-1))}return d};D.Ie=function(a){var b=[],c;if(!a.Ke())return[a];for(var d=0;d<a.ve.length;d++)c=a.ve[d],c=(0,D.Ie)(c),b=b.concat(c);return b};D.Je=function(a,b){if(a.getId()==b)return a;for(var c=D.n,d=a.ub(),e=d.length,c=D.n,f=0;f<e;f++)if(c=d[f],c=(0,D.Je)(c,b))return c;return D.n};D.x=D.ub.prototype;D.x.getId=(0,D.w)("Oa");D.x.yc=(0,D.w)("ok");D.x.Eb=(0,D.w)("Ug");
D.x.Oe=(0,D.w)("Ey");D.x.tk=(0,D.w)("Ug");D.x.Z=(0,D.w)("gt");D.x.B=function(a){this.gt=a;this.H&&this.H.B(this.gt)};D.x.Za=(0,D.w)("Dg");D.x.Xq=function(){return"r"==this.sR||"ir"==this.sR};D.x.uA=(0,D.v)("Rc");D.x.zd=(0,D.w)("Rc");D.x.Gw=(0,D.w)("h2");D.x.L=(0,D.s)();D.x.Iu=function(a){var b=this.ub();if(b!=D.n)for(var c=0;c<b.length;c++)b[c].L(a)};D.x.Rf=function(){(0,D.Jb)(this);return this};D.x.of=function(){return new D.N(0,0,0,0)};D.x.$m=(0,D.ca)(D.n);
D.x.Xf=function(){this.Zd=D.k;this.Oc();this.Xw&&this.Xw()};D.x.Mc=function(){this.Zd&&(this.Zd=D.p,this.sc());this.Uq&&this.Uq()};D.x.vg=(0,D.w)("Zd");D.x.Xw=function(){this.bJ=D.k};D.x.Uq=function(){this.bJ=D.p};D.x.$b=function(){return"off"!=this.pw&&this.I.eha!=D.n};D.x.Ma=(0,D.w)("Td");D.x.Pb=function(a){this.Td=a;this.$j()};D.x.Oc=(0,D.s)();D.x.sc=(0,D.s)();D.x.Oj=function(a){return this.I.IE(a)};D.x.kl=function(){return this.I.ay(this)};D.x.$C=function(){return this.I.$x()};D.x.MP=(0,D.w)("H");
D.x.fD=(0,D.ca)(D.n);D.x.contains=(0,D.ca)(D.p);D.x.vl=function(){return[]};D.x.Co=(0,D.s)();D.x.ig=function(a,b){a.SJ||(0,D.Ke)(a,b.ub(),this.ub());var c=b.vl(),d=this.vl(),e;if(!D.Hc.dh(c,d)&&(e=new D.Le(this.I.e,this,this.I.cE),(0,D.T)(e.R,"typeNumberArray",this,this.vl,this.Co,d),a.add(e,1),d=this.ok!=b.ok,e=D.O.eV(this.Ug)!=D.O.eV(b.Ug),this.Co(c),(c=(0,D.Ub)(this,D.n,"ANIMATION_UPDATE_COLOR_STYLE"))&&(d||e)))this.Ug=c};
D.x.$g=function(a){if(!a.SJ||!a.SJ||!(a.LL.getId()==this.getId()||(0,D.Me)(a.LS,this))){this.B(0);var b=new D.Oe(this.I.e,this,this.I.cE);a.add(b,2);for(b=0;b<this.ve.length;b++)this.ve[b].$g(a)}};D.x.vi=function(a,b){b.k(this.H);var c=new D.Pe(this.I.e,this,this.I.cE);a.add(c,0);if(!a.SJ)for(c=0;c<this.ve.length;c++)this.ve[c].vi(a,b)};D.x.Ke=function(){return this.ve!=D.n&&0<this.ve.length};D.Eb=function(a){var b=0;for(a=a.Bf;a;)b++,a=a.Bf;return b};
D.ub.prototype.mE=function(){return this.Zo?new D.id(this.Zo,this.Ug):new D.cb(this.Ug)};D.Qe=function(a){return a.Zo?"#000000":D.O.bm(a.Ug)};D.Yb=function(a,b){var c=(0,D.Qe)(a);b.qa(c);var d=[];d.push(a.I.Rn.LABEL_TEXT_DEFAULT_STYLE);a.Im&&d.push(a.Im);b.Ia((0,D.Re)(d));D.Se===D.k&&b.qa(c)};D.Ub=function(a,b,c){(a=a.I.Rn[c])&&(b=a);return b};D.yb=function(a){var b=11;(a=a.I.Rn.LABEL_TEXT_DEFAULT_STYLE.JH())&&(b=(0,window.parseFloat)(a));return b};D.ub.prototype.ra=(0,D.w)("H");
D.ub.prototype.Of=(0,D.w)("Bz");D.ub.prototype.Kaa=function(a){a&&!this.xM&&(0,D.Ge)(this,"content");this.mi=a};D.Ge=function(a,b){b&&(a.xM=a.n4[b])};D.ub.prototype.Ng=function(){return this.Xq()};D.ub.prototype.$j=(0,D.s)();
D.Zb=function(a,b,c,d,e){this.Init(c,d,e);this.vb=a;this.Oa=b;this.jy=D.p};D.y.l(D.Zb,D.Ga,"DvtBaseTreePeer");D.Zb.prototype.getId=(0,D.w)("Oa");D.Zb.prototype.pma=(0,D.w)("jy");D.Zb.prototype.q8=(0,D.v)("jy");D.Zb.prototype.Uq=function(){this.vb&&this.vb.Uq&&this.vb.Uq()};
D.cf=(0,D.s)();D.y.l(D.cf,D.y,"DvtTreeBreadcrumbsRenderer");D.cf.wra=6;D.cf.Lra="color: #003286;";
D.cf.L=function(a,b,c,d){var e=a.e,f=[];f.push(a.Rn.TEXT_STYLE);f.push(new D.B(D.cf.Lra));f.push(a.Rn.DRILL_TEXT_STYLE);var f=(0,D.Re)(f).toString(),g=f+"text-decoration: underline;",h=[];h.push(a.Rn.TEXT_STYLE);h.push(a.Rn.CURRENT_TEXT_STYLE);h=(0,D.Re)(h).toString();e=new D.df(e,a.dta,a,{xu:f,m7:g,l7:g,mka:h});a.k(e);c=c.slice(0).reverse();c.push({text:d});e.L({items:c},b.g);d=e.C();(0,D.G)(e,b.x,b.y);d=d.j+D.cf.wra;b.y+=d;b.j-=d;a.removeChild(e);return e};
D.ef=(0,D.s)();D.y.l(D.ef,D.y,"DvtTreeLegendRenderer");D.ef.Tra=4;D.ef.dt=7;D.ef.JP=24;D.ef.Sra=11;D.ef.yba="#636363";D.ef.gIa="color:"+D.ef.yba+";";
D.ef.L=function(a,b,c,d,e,f,g){var h=a.e,j=a.Ua(),l=new D.I(h);a.k(l);var m=D.ef.cM(h,a,l,b.g,c,d,e,f,g),o=a.yh.alta?D.n:"#000000",q=[];q.push(a.Rn.TEXT_STYLE);var q={borderColor:o,xu:(0,D.Re)(q)},o=D.eb.X7(h,j,l,b.g,b.j,g,q),r=m?m.C():D.n,t=o?o.C():D.n;if(m&&!o)m.F(b.y+(b.g-r.g)/2);else if(o&&!m)o.F(b.y+(b.g-t.g)/2);else if(o&&m){var u=b.g-D.ef.JP;r.g+t.g>u&&(r.g>u/2&&t.g>u/2?(l.removeChild(m),l.removeChild(o),m=D.ef.cM(h,a,l,u/2,c,d,e,f,g),o=D.eb.X7(h,j,l,u/2,b.j,g,q)):r.g>t.g?(j=u-t.g,l.removeChild(m),
m=D.ef.cM(h,a,l,j,c,d,e,f,g)):(c=u-r.g,l.removeChild(o),o=D.eb.X7(h,j,l,c,b.j,g,q)),r=m.C(),t=o.C());(0,D.C)(h)?(o.F(b.x),m.F(b.x+b.g-r.g)):(m.F(b.x),o.F(b.x+b.g-t.g))}g=l.C();l.O(b.y+b.j-g.j);b.j-=g.j+D.ef.Tra;a.removeChild(l);return l};
D.ef.cM=function(a,b,c,d,e,f,g,h){var j=(0,D.C)(a),l=b.Ua(),m=D.n;if(g||h){m=new D.I(a);c.k(m);var o=[];o.push(b.Rn.TEXT_STYLE);o.push(b.Rn.ATTRIBUTE_TYPE_STYLE);c=(0,D.Re)(o);o=[];o.push(b.Rn.TEXT_STYLE);o.push(b.Rn.ATTRIBUTE_VALUE_STYLE);var o=(0,D.Re)(o),q,r,t,u;b=0;g&&(q=new D.Ia(a,e,0,0),q.Ia(c),m.k(q),t=q.cc().g,r=new D.Ia(a,g,0,0),r.Ia(o),m.k(r),u=r.cc().g,b=t+u+D.ef.dt);var z,A,F,H;e=0;h&&(z=new D.Ia(a,f,0,0),z.Ia(c),m.k(z),F=z.cc().g,A=new D.Ia(a,h,0,0),A.Ia(o),m.k(A),H=A.cc().g,e=F+H+D.ef.dt);
d-=D.ef.JP;b+e>d&&(a=d/2,b>a&&e>a?(D.Pa.Vb(r,a-t-D.ef.dt,window.Infinity,m)?(u=r.cc().g,l.ka(r,new D.Ga(g))):(m.removeChild(q),m.removeChild(r),r=D.n,u=0),D.Pa.Vb(A,a-F-D.ef.dt,window.Infinity,m)?(H=A.cc().g,l.ka(A,new D.Ga(h))):(m.removeChild(z),m.removeChild(A),A=D.n,H=0)):b>e?D.Pa.Vb(r,d-e-t-D.ef.dt,window.Infinity,m)?(u=r.cc().g,l.ka(r,new D.Ga(g))):(m.removeChild(q),m.removeChild(r),r=D.n,u=0):D.Pa.Vb(A,d-b-F-D.ef.dt,window.Infinity,m)?(H=A.cc().g,l.ka(A,new D.Ga(h))):(m.removeChild(z),m.removeChild(A),
A=D.n,H=0));d=0;j?(A&&(A.ea(d),d+=H+D.ef.dt,z.ea(d),d+=F+D.ef.JP),r&&(r.ea(d),d+=u+D.ef.dt,q.ea(d))):(r&&(q.ea(d),d+=t+D.ef.dt,r.ea(d),d+=u+D.ef.JP),A&&(z.ea(d),d+=F+D.ef.dt,A.ea(d)))}return m};
D.ff=function(a){this.Init(a)};D.y.l(D.ff,D.gf,"DvtBaseTreeKeyboardHandler");D.ff.prototype.cI=function(a){return this.Yi(a)&&!a.ctrlKey};D.ff.prototype.tD=function(a){return 32==a.keyCode&&a.ctrlKey};
D.dc=(0,D.s)();D.y.l(D.dc,D.Aa,"DvtBaseTreeDefaults");D.We={emptyText:"No data to display",nodeDefaults:{labelStyle:new D.B("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 11px;")},styleDefaults:{_attributeTypeTextStyle:new D.B("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:12px;font-weight:bold;color:#4F4F4F"),_attributeValueTextStyle:new D.B("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:12px;")},_resources:{}};
D.dc.prototype.Init=function(a){a={skyros:D.Sa.Ob(a.skyros,D.We),alta:D.Sa.Ob(a.alta,{})};D.dc.o.Init.call(this,a)};
D.mb=(0,D.s)();D.y.l(D.mb,D.y,"DvtBaseTreeJsonUtils");
D.mb.prototype.E8=function(a){var b;b="\x3c"+this.VO();b+=this.wJ(a);b+="\x3e\n";if(a&&a.nodes)for(var c=a.nodes,d=0;d<c.length;d++)b+=(0,D.Be)(this,a,c[d]);c="\x3ca/\x3e\n"+this.cZ(a);c+=this.yJ(a);if(d=a.attributeGroups?a.attributeGroups[0]:D.n)if(a='\x3cag id\x3d"'+d.id+'"',"continuous"==d.attributeType)a+=this.Ea("t","continuous"),a+=this.Ea("ramp",d.colors.join(";")),a+=this.Ea("minValue",d.min),a+=this.Ea("maxValue",d.max),a+=this.Ea("minLabel",d.minLabel),a+=this.Ea("maxLabel",d.maxLabel),
a+="/\x3e";else{a+="\x3e\n";for(var d=d.groups,e=0;e<d.length;e++)a+="\x3ci",a+=this.Ea("g",d[e].id),a+=this.Ea("l",d[e].label),a+=this.Ea("c",d[e].color),a+=this.Ea("p",d[e].pattern),a+="/\x3e\n";a+="\x3c/ag\x3e\n"}else a="";c=c+a+("\x3c/"+this.VO()+"\x3e");return b+=c};D.mb.prototype.Ea=function(a,b){return b!=D.n?" "+a+'\x3d"'+b+'"':""};D.mb.prototype.VO=(0,D.ca)(D.n);
D.mb.prototype.wJ=function(a){var b;b=""+this.Ea("sv",a.sizeLabel);b+=this.Ea("cv",a.colorLabel);var c=a.attributeGroups?a.attributeGroups[0]:D.n;c&&(b+=this.Ea("ls",c.id));for(var c=a.selectedNodes?a.selectedNodes:[],d="",e=0;e<c.length;e++)0<d.length&&(d+=","),d+=c[e];0<d.length&&(b+=this.Ea("selIds",d));b+=this.Ea("adu",a.animationDuration);b+=this.Ea("adc",a.animationOnDataChange);b+=this.Ea("emptyText",a.emptyText);b+=this.Ea("sel",a.selection);return b+=this.Ea("sort",a.sorting)};
D.Be=function(a,b,c){var d;d="\x3cn"+a.xJ(b,c);if(c&&c.nodes&&0<c.nodes.length){d+=a.Ea("di","t");d+="\x3e\n";c=c.nodes;for(var e=0;e<c.length;e++)d+=(0,D.Be)(a,b,c[e]);d+="\x3c/n\x3e\n"}else d+="/\x3e\n";return d};
D.mb.prototype.xJ=function(a,b){var c;c=""+this.Ea("id",b.id);c+=this.Ea("s",b.value);c+=this.Ea("c",b.color);c+=this.Ea("l",b.label);c+=this.Ea("p",b.pattern);c+=this.Ea("tt",b.shortDesc?b.shortDesc:b.tooltip);c+=this.Ea("ls",b.labelStyle?b.labelStyle:a.nodeDefaults.labelStyle);var d=b.drilling?b.drilling:a.nodeDefaults.drilling;"insert"==d?c+=this.Ea("d","i"):"replace"==d?c+=this.Ea("d","r"):"insertAndReplace"==d&&(c+=this.Ea("d","ir"));return c+=this.Ea("nsel",b.selectable?b.selectable:"auto")};
D.mb.prototype.cZ=(0,D.s)();D.mb.prototype.yJ=function(a){var b;b="\x3cstyles "+this.Ea("attrType",a.styleDefaults._attributeTypeTextStyle);return b+=this.Ea("attrValue",a.styleDefaults._attributeValueTextStyle)};
D.Te=function(a){this.dAa=a;this.Pa=a.Pa};(0,D.ra)("DvtTreeAutomation",D.Te);D.y.l(D.Te,D.we,"DvtTreeAutomation");D.Te.prototype.Fp=function(a){var b=this.dAa.i6(a);if(!b)return D.n;if(b instanceof D.ub){a="";if(!this.Pa.VE){if(b==this.Pa)return"node[0]";a+="[0]"}a=(b=this.ER(b,this.Pa.ub()))?a+b:a;if(0<a.length)return"node"+a}return D.n};D.Te.prototype.ER=function(a,b){if(b&&0<b.length)for(var c=0;c<b.length;c++){if(b[c]==a)return"["+c+"]";var d=this.ER(a,b[c].ub());if(d)return"["+c+"]"+d}return D.n};
D.Te.prototype.Ij=function(a){return!this.Pa.VE&&(a=a.substring(0,a.indexOf("["))+a.substring(a.indexOf("]")+1),"node"==a)?this.Pa.MP().pa():(a=(0,D.Ue)(this,this.Pa,a))?a.ra().pa():D.n};D.Te.prototype.getDomElementForSubId=D.Te.prototype.Ij;D.Ue=function(a,b,c){var d=c.indexOf("["),e=c.indexOf("]");if(0<=d&&0<=e)return d=c.substring(d+1,e),c=c.substring(e+1),e=c.indexOf("]"),0<=c.indexOf("[")&&0<=e?(0,D.Ue)(a,b.ub()[d],c):b.ub()[d]};
D.Ve=function(a,b,c){var d=c.shift();b=b.ub();return 0==c.length?b[d]:0<c.length?(0,D.Ve)(a,b[d],c):D.n};D.Te.prototype.Lc=function(a){!this.Pa.VE&&0==a[0]&&a.shift();a=0==a.length?this.Pa:(0,D.Ve)(this,this.Pa,a);return{color:a.Eb(),label:a.Of(),selected:a.Ma()==D.i?D.p:a.Ma(),size:a.yc(),tooltip:a.Oe()}};D.Te.prototype.getNode=D.Te.prototype.Lc;
});