"use strict";
define(['./DvtToolkit', './DvtAxis'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.CC=(0,D.s)();(0,D.ra)("DvtGauge",D.CC);D.y.l(D.CC,D.mB,"DvtGauge");D.CC.prototype.Init=function(a,b,c,d){D.CC.o.Init.call(this,a,b,c);this.jd=new D.Sz;this.vca=d;this.vca||(this.ta=this.hE(),this.ta.Df(this),(0,D.Qa)()||(0,D.gk)(this.ta,this.Cx(this.ta)),this.setId("gauge1000"+window.Math.floor(1E9*window.Math.random())),this.uF=new D.D(a,0,0),(0,D.La)(this.uF),this.k(this.uF));this.dB=D.p;this.lG=D.n};
D.CC.prototype.ge=function(a){this.M=a;(0,D.yp)()||(this.M.animationOnDisplay="none",this.M.animationOnDataChange="none")};
D.CC.prototype.L=function(a,b,c){a?this.ge(a):this.M||this.ge(D.n);this.M.thresholds&&(this.M.thresholds=this.M.thresholds.sort(D.EC));!(0,window.isNaN)(b)&&!(0,window.isNaN)(c)&&(this.pb=b,this.Cb=c);c=this.av;this.av=[];b=new D.I(this.e);this.Ha(b,0);this.Fi(b,this.pb,this.Cb);var d=a!=D.n,e=this.pb,f=this.Cb;this.yb&&this.yb.stop();a=D.p;var g=this.dB?"none":this.za().animationOnDataChange,h=this.dB?"none":this.za().animationOnDisplay,j=this.za().animationDuration/1E3;if(h||g){e=new D.N(0,0,e,
f);f=this.e;if(!this.ca&&"none"!==h&&this.av[0]!=D.n)this.yb=D.cg.KH(f,h,b,e,j),this.yb||(this.yb=this.SW(this.av,h,j));else if(this.ca&&"none"!=g&&d&&this.av[0]!=D.n)if(this.yb=D.cg.EH(f,g,this.ca,b,e,j))a=D.k;else{d=this.av;g=[];for(h=0;h<c.length;h++){var e=d[h],l=c[h].be(),f=e.be();e.ue(l);l=new D.Le(this.e,e,j);(0,D.T)(l.R,"typeNumberArray",e,e.be,e.ue,f);g.push(l)}this.yb=new D.rj(this.e,g)}a||this.removeChild(this.ca);this.yb&&(this.yb.play(),this.yb.Md(this.tC,this));a&&(this.al=this.ca);
this.ca=b}this.uF&&this.M.readOnly===D.p&&(this.uF.ha(this.pb),this.uF.xa(this.Cb));this.vca||(c=this.getParent()==this.e.Sc,a=D.xz.vN(this),this.M.readOnly&&c?(this.e.Hf("img"),(0,D.qv)(this.e,a)):(b.Hf("img"),(0,D.Oa)(b,"label",a),this.l3=this.l3!=D.n?this.l3+1:0,c=this.getId()+"_"+this.l3,b.setId(c),(0,D.Sh)(this.e,b),(b=this.Ua())&&b.ka(this.uF,this.ma(),D.k)))};D.CC.prototype.render=D.CC.prototype.L;D.x=D.CC.prototype;
D.x.ma=function(){var a=D.xz.vN(this),b=D.Hz.Eb(this);return new D.Ga(D.n,a,b)};D.x.Fi=(0,D.s)();D.x.SW=(0,D.ca)(D.n);D.x.Ru=(0,D.ca)(D.n);D.x.tC=function(){this.al&&(this.removeChild(this.al),this.al=D.n);this.yb=D.n};D.x.FJ=(0,D.w)("jd");D.x.za=(0,D.w)("M");D.x.Ua=(0,D.w)("ta");D.x.QP=function(a,b){this.dB=D.k;this.lG=this.M.value;this.GJ(a,b)};D.x.GJ=function(a,b){this.M.value=D.xz.fU(this.M,this.Ru(a,b));this.L();this.Wa(new D.Wz(this.lG,this.M.value,D.p))};
D.x.PP=function(a,b){this.GJ(a,b);this.Wa(new D.Wz(this.lG,this.M.value,D.k));this.dB=D.p;this.lG=D.n};D.x.hE=function(){return new D.Cz(this)};D.EC=function(a,b){return a.max&&b.max?a.max-b.max:a.max?-window.Infinity:window.Infinity};D.CC.prototype.Vh=function(){return new D.wz(this)};D.CC.prototype.getAutomation=D.CC.prototype.Vh;D.CC.prototype.Cx=function(a){return new D.Vz(a,this)};
D.wz=(0,D.v)("oe");(0,D.ra)("DvtGaugeAutomation",D.wz);D.y.l(D.wz,D.we,"DvtGaugeAutomation");D.wz.prototype.getValue=function(){return this.oe.za().value};D.wz.prototype.getValue=D.wz.prototype.getValue;D.wz.prototype.wDa=function(){return D.xz.Nq(this.getValue(),this.oe)};D.wz.prototype.getMetricLabel=D.wz.prototype.wDa;
D.Sz=(0,D.s)();D.y.l(D.Sz,D.Tz,"DvtGaugeBundle");D.Sz._defaults={EMPTY_TEXT:"No data to display"};D.Sz.prototype.ej=function(a){return D.Sz._defaults[a]};D.Sz.prototype.kr=(0,D.ca)("DvtGaugeBundle");
D.vz=(0,D.s)();D.y.l(D.vz,D.Aa,"DvtGaugeDefaults");D.$z={skin:"alta",color:"#393737",metricLabel:{style:new D.B("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")}};D.aA={skin:"skyros",min:0,max:100,color:"#313842",borderColor:D.n,visualEffects:"auto",emptyText:D.n,animationOnDataChange:"none",animationOnDisplay:"none",animationDuration:500,readOnly:"true",metricLabel:{rendered:"off",scaling:"auto",style:new D.B,textType:"number"},__layout:{outerGap:1,labelGap:3}};
D.vz.prototype.Init=function(a){a={skyros:D.Sa.Ob(a.skyros,D.aA),alta:D.Sa.Ob(a.alta,D.$z)};D.vz.o.Init.call(this,a)};D.Jz=function(a){return"skyros"==a.za().skin};
D.yz={};D.y.l(D.yz,D.y,"DvtGaugeDataUtils");D.yz.ru=function(a){a=a.za();return!a||(0,window.isNaN)(a.value)||a.value===D.n?D.p:D.k};D.yz.lD=function(a,b){var c=a.za(),d=b?b:c.value,c=c.thresholds;if(!c)return-1;for(var e=0;e<c.length;e++)if(d<=c[e].max)return e;return c.length-1};D.yz.TH=function(a,b){var c=a.za().thresholds;return c&&0<=b&&b<c.length?c[b]:D.n};D.yz.sKa=function(a,b){var c=a.za().referenceLines;return c&&0<=b&&b<c.length?c[b]:D.n};
D.Cz=function(a){this.Init(a.e,a.Wa,a);this.oe=a;this.zk=D.p};D.y.l(D.Cz,D.ta,"DvtGaugeEventManager");D.x=D.Cz.prototype;D.x.xl=function(a){this.oe.za().readOnly===D.p?(this.zk=D.k,this.zc(),a=(0,D.Dz)(this,a.pageX,a.pageY),this.oe.QP(a.x,a.y)):D.Cz.o.xl.call(this,a)};D.x.un=function(a){this.zk?(this.zk=D.p,a=(0,D.Dz)(this,a.pageX,a.pageY),this.oe.PP(a.x,a.y)):D.Cz.o.un.call(this,a)};
D.x.Lp=function(a){if(this.zk){var b=(0,D.Dz)(this,a.pageX,a.pageY);this.oe.GJ(b.x,b.y)}(this.P$()||!this.zk)&&D.Cz.o.Lp.call(this,a)};D.x.P$=(0,D.ca)(D.p);
D.x.nJ=function(a){if(D.Wv.Ce===a.type&&this.oe.za().readOnly===D.p){this.zk=D.k;var b=(0,D.Dz)(this,a.touches[0].pageX,a.touches[0].pageY);this.oe.QP(b.x,b.y);a.preventDefault()}else D.Wv.gj===a.type&&this.zk?(b=(0,D.Dz)(this,a.touches[0].pageX,a.touches[0].pageY),this.oe.GJ(b.x,b.y),a.preventDefault()):D.Wv.Kh===a.type&&this.zk?(this.zk=D.p,b=(0,D.Dz)(this,a.changedTouches[0].pageX,a.changedTouches[0].pageY),this.oe.PP(b.x,b.y),a.preventDefault()):D.Cz.o.nJ.call(this,a)};
D.Dz=function(a,b,c){b=(0,D.gc)(a.e,b,c);return a.oe.Fb(b)};D.Cz.prototype.at=(0,D.s)();
D.Vz=function(a,b){this.Init(a,b)};D.y.l(D.Vz,D.gf,"DvtGaugeKeyboardHandler");D.Vz.prototype.Init=function(a,b){D.Vz.o.Init.call(this,a);this.oe=b};
D.Vz.prototype.lo=function(a){var b=a.keyCode,c=(0,D.C)(this.oe.e);if(38==b||b==(c?37:39))b=this.oe,b.M.readOnly||(c=b.M.value,b.M.value=b.M.step!=D.n?D.xz.fU(b.M,b.M.value+b.M.step):window.Math.min(window.Math.max(b.M.value+(b.M.max-b.M.min)/100,b.M.min),b.M.max),b.L(),b.Wa(new D.Wz(c,b.M.value,D.k))),a.preventDefault();else if(40==b||b==(c?39:37))b=this.oe,b.M.readOnly||(c=b.M.value,b.M.value=b.M.step!=D.n?D.xz.fU(b.M,b.M.value-b.M.step):window.Math.min(window.Math.max(b.M.value-(b.M.max-b.M.min)/
100,b.M.min),b.M.max),b.L(),b.Wa(new D.Wz(c,b.M.value,D.k))),a.preventDefault()};
D.Hz={};D.y.l(D.Hz,D.y,"DvtGaugeStyleUtils");D.Hz.Kba=["#ed6647","#fad55c","#68c182"];D.Hz.Iba=["#D62800","#FFCF21","#84AE31"];D.Hz.Iba=["#D62800","#FFCF21","#84AE31"];D.Hz.fra={startAngle:202.5,angleExtent:225,anchorX:100,anchorY:103,metricLabelBounds:{x:80,y:86,width:40,height:34},indicatorLength:0.85,tickLabelHeight:20,tickLabelWidth:30,radius:60,majorTickCount:6};
D.Hz.gra={startAngle:202.5,angleExtent:225,anchorX:100,anchorY:103,metricLabelBounds:{x:83,y:86,width:34,height:34},indicatorLength:0.85,tickLabelHeight:20,tickLabelWidth:30,radius:60,majorTickCount:6};D.Hz.ira={startAngle:202.5,angleExtent:225,anchorX:100,anchorY:103,metricLabelBounds:{x:83,y:86,width:34,height:34},indicatorLength:0.85,tickLabelHeight:20,tickLabelWidth:30,radius:60,majorTickCount:6};
D.Hz.jra={startAngle:220.5,angleExtent:261.1,anchorX:100,anchorY:100,metricLabelBounds:{x:82,y:133,width:36,height:34},indicatorLength:0.85,tickLabelHeight:20,tickLabelWidth:30,radius:61,majorTickCount:6};D.Hz.kra={startAngle:195.5,angleExtent:210.8,anchorX:100,anchorY:100,metricLabelBounds:{x:84,y:135,width:32,height:35},indicatorLength:0.98,tickLabelHeight:20,tickLabelWidth:30,radius:63,majorTickCount:6};
D.Hz.mra={startAngle:207.6,angleExtent:235,anchorX:100,anchorY:95.8,metricLabelBounds:{x:83,y:125,width:34,height:40},indicatorLength:1.05,tickLabelHeight:20,tickLabelWidth:30,radius:64,majorTickCount:6};D.Hz.Vra={startAngle:220.5,angleExtent:261.1,anchorX:100,anchorY:100,metricLabelBounds:{x:80,y:82,width:40,height:40},indicatorLength:0.82,tickLabelHeight:20,tickLabelWidth:30,radius:58,majorTickCount:6};
D.Hz.Wra={startAngle:201,angleExtent:222,anchorX:100.2,anchorY:89,metricLabelBounds:{x:80,y:70,width:41,height:39},indicatorLength:1.23,tickLabelHeight:20,tickLabelWidth:30,radius:56,majorTickCount:6};D.Hz.Yra={startAngle:211,angleExtent:242,anchorX:100,anchorY:91.445,metricLabelBounds:{x:78,y:75,width:44,height:38},indicatorLength:1.1,tickLabelHeight:20,tickLabelWidth:30,radius:58,majorTickCount:6};
D.Hz.xra={startAngle:220.5,angleExtent:261.5,metricLabelBounds:{x:80,y:82,width:40,height:40},indicatorLength:0.85,tickLabelHeight:20,tickLabelWidth:30,radius:60,majorTickCount:6};D.Hz.yra={startAngle:201,angleExtent:222,anchorX:100.2,anchorY:89,metricLabelBounds:{x:80,y:73,width:40,height:36},indicatorLength:1.23,tickLabelHeight:20,tickLabelWidth:30,radius:56,majorTickCount:6};
D.Hz.Ara={startAngle:201,angleExtent:222,anchorX:100.2,anchorY:99.5,metricLabelBounds:{x:80,y:83,width:41,height:36},indicatorLength:1.1,tickLabelHeight:20,tickLabelWidth:30,radius:58,majorTickCount:6};D.Hz.lra={anchorX:42,anchorY:510};D.Hz.hra={anchorX:187,anchorY:388};D.Hz.Xra={anchorX:227,anchorY:425};D.Hz.zra={anchorX:227,anchorY:425};
D.Hz.Eb=function(a){var b=a.za(),c=D.yz.lD(a),d=D.yz.TH(a,c);return d&&(!(a instanceof D.Iz)||a instanceof D.Iz&&"onIndicator"==b.thresholdDisplay)?D.Hz.sN(a,d,c):b.color};D.Hz.Ch=function(a){var b=a.za(),c=D.yz.TH(a,D.yz.lD(a));return c&&c.borderColor&&(!(a instanceof D.Iz)||a instanceof D.Iz&&"onIndicator"==b.thresholdDisplay)?c.borderColor:b.borderColor};
D.Hz.yla=function(a){var b=a.za(),c=D.yz.lD(a),d=D.yz.TH(a,c);return d&&(!(a instanceof D.Iz)||a instanceof D.Iz&&"onIndicator"!=b.thresholdDisplay)?D.Hz.sN(a,d,c):b.plotArea.color};D.Hz.sN=function(a,b,c){if(b.color)return b.color;if(c<D.Hz.Kba.length)return(0,D.Jz)(a)?D.Hz.Iba[c]:D.Hz.Kba[c]};
D.Hz.LCa=function(a){return"rectangleAlta"===a?D.Hz.ira:"domeAlta"===a?D.Hz.gra:"circleAntique"===a?D.Hz.jra:"rectangleAntique"===a?D.Hz.mra:"domeAntique"===a?D.Hz.kra:"circleLight"===a?D.Hz.Vra:"rectangleLight"===a?D.Hz.Yra:"domeLight"===a?D.Hz.Wra:"circleDark"===a?D.Hz.xra:"rectangleDark"===a?D.Hz.Ara:"domeDark"===a?D.Hz.yra:D.Hz.fra};D.Hz.MCa=function(a){return"needleAntique"===a?D.Hz.lra:"needleLight"===a?D.Hz.Xra:"needleDark"===a?D.Hz.zra:D.Hz.hra};
D.xz={};D.y.l(D.xz,D.y,"DvtGaugeRenderer");D.xz.iZ=2;D.xz.sba=1;D.xz.mA=function(a,b,c){var d=a.za(),e=d.emptyText;e||(e=(0,D.ob)(a.FJ(),"EMPTY_TEXT",D.n));var f=c.g-2*D.xz.iZ,g=c.j-2*D.xz.sba;c=new D.Ia(a.e,e,c.x+c.g/2,c.y+c.j/2);d.metricLabel.style.v("font-size")||d.metricLabel.style.V("font-size","13px");c.Ia(d.metricLabel.style);c.lf();c.Ge();D.Pa.Vb(c,f,g,b)&&c.wg()&&a.Ua().ka(c,new D.Ga(e))};
D.xz.Nq=function(a,b){var c=b.za(),d="percent"==c.metricLabel.textType;d&&(a=100*D.xz.IH(c,c.min,a));var e=D.n;"on"==c.metricLabel.rendered&&c.metricLabel.converter&&(e=c.metricLabel.converter);var f=D.n;"on"==c.metricLabel.rendered&&c.metricLabel.scaling&&(f=c.metricLabel.scaling);return D.xz.mea(a,b,e,f,c.metricLabel.autoPrecision?c.metricLabel.autoPrecision:"on",d)};
D.xz.yU=function(a,b){var c=b.za(),d="percent"==c.tickLabel.textType;d&&(a=100*D.xz.IH(c,c.min,a));var e=D.n;"on"==c.tickLabel.rendered&&c.tickLabel.converter&&(e=c.tickLabel.converter);var f=D.n;"on"==c.tickLabel.rendered&&c.tickLabel.scaling&&(f=c.tickLabel.scaling);return D.xz.mea(a,b,e,f,c.tickLabel.autoPrecision?c.tickLabel.autoPrecision:"on",d)};
D.xz.mea=function(a,b,c,d,e,f){var g=b.za();b=a;b=g.min;var g=g.max,h=g-b,j=D.n;(0,window.isNaN)(h)||(j=h/(1E3>h?100:1E3));d=new D.Mk(b,g,j,d,e);if(c&&c.getAsString)b=d.Iq(a,c);else{if(c&&c.format)return d.Iq(a,c);b=d.Iq(a)}return f?(0,window.String)(b)+"%":b};D.xz.IH=function(a,b,c){a=(c-b)/(a.max-a.min);return a=window.Math.min(window.Math.max(0,a),1)};D.xz.vN=function(a){var b=a.za(),c=D.yz.TH(a,D.yz.lD(a));return c&&c.shortDesc!=D.n?c.shortDesc:b.shortDesc!=D.n?b.shortDesc:D.xz.Nq(b.value,a)};
D.xz.Z7=function(a,b,c,d){var e=a.za();if("on"==e.metricLabel.rendered){var f=D.xz.Nq(e.value,a),g=c.g,h=c.j;a=new D.Ia(a.e,f,c.x+c.g/2,c.y+c.j/2);a.Ia(e.metricLabel.style);var j=e.metricLabel.style.v("font-size");if(!e.metricLabel.style.v("font-size")){var j=window.Math.max(e.max.toString().length,e.min.toString().length,f.length),l="";"percent"==e.metricLabel.textType&&(j=window.Math.max(3,f.length),l+="%");for(e=0;e<j;e++)l+="0";a.Dd(l);j=a.Qw(c);a.Dd(f);a.Wf(j)}a.Ge();a.lf();d!=D.n&&a.qa(d);D.Pa.Vb(a,
g,h,b)&&a.ia(D.p)}};D.xz.fU=function(a,b){var c=(0,window.Number)(a.step);if(c&&0<c){var d=(b-a.min)/c;return 0.5<d?window.Math.max(window.Math.min(a.max,window.Math.round(d)*c+a.min),a.min):a.min}return b};
D.JC=(0,D.s)();(0,D.ra)("DvtLedGauge",D.JC);D.y.l(D.JC,D.CC,"DvtLedGauge");D.Nz=function(a,b,c,d){var e=new D.JC;e.Init(a,b,c,d);return e};D.JC.newInstance=D.Nz;D.JC.prototype.Init=function(a,b,c,d){D.JC.o.Init.call(this,a,b,c,d);this.vf=new D.Az};D.JC.prototype.ge=function(a){D.JC.o.ge.call(this,this.vf.ah(a));"auto"==this.M.animationOnDisplay&&(this.M.animationOnDisplay="zoom");"auto"==this.M.animationOnDataChange&&(this.M.animationOnDataChange="alphaFade");this.M.readOnly=D.k};
D.JC.prototype.Fi=function(a,b,c){D.Kz.L(this,a,b,c)};
D.Az=function(){this.Init({skyros:D.zz,alta:{}})};D.y.l(D.Az,D.vz,"DvtLedGaugeDefaults");D.zz={type:"circle"};
D.Kz={};D.y.l(D.Kz,D.y,"DvtLedGaugeRenderer");D.Kz.pIa=1/6;D.Kz.Isa="M-42,36.6Q-50,36.6,-46.54,28.6L-4,-43.07Q0,-50,4,-43.07L46.54,28.6Q50,36.6,42,36.6Z";D.Kz.Dsa=[-50,36.6,0,-50,50,36.6];D.Kz.Jsa=[-50,36.6,0,-50,50,36.6];D.Kz.Hba=[-13.05,-12.94,-50,-11.13,-21.06,11.9,-30.74,47.6,0.1,27.18,31.06,47.44,21.17,11.79,50,-11.39,13.05,-13.01,-0.06,-47.59];D.Kz.Csa=[-50,-11.22,-16.69,-17.94,0,-47.55,16.69,-17.94,50,-11.22,26.69,13.8,30.9,47.56,0,33.42,-30.9,47.56,-26.69,13.8];D.Kz.Gsa="M0,45L21,45Q24.414,44.414,25,41L25,10L42,10Q48.5,9.1,45,4L2,-38Q0,-39,-2,-38L-45,4Q-48.5,9.1,-42,10L-25,10L-25,41Q-24.414,44.414,-21,45Z";
D.Kz.Bsa=[25,48,25,8,47.5,8,0,-39,-47.5,8,-25,8,-25,48];D.Kz.Hsa=[25,48,25,8,47.5,8,0,-39,-47.5,8,-25,8,-25,48];
D.Kz.L=function(a,b,c,d){if(D.yz.ru(a)){var e=a.za(),f=e.__layout.outerGap,g=e&&(0<=e.size||1>e.size)?window.Math.sqrt(e.size):1;c=new D.N(f+(c-2*f)*(1-g)/2,f+(d-2*f)*(1-g)/2,(c-2*f)*g,(d-2*f)*g);D.Kz.eM(a,b,c);D.Kz.r3(a,b,c);"on"==e.metricLabel.rendered&&(D.Se!==D.k&&e.metricLabel.style.v("color")!=D.n?D.xz.Z7(a,b,D.Kz.Eea(a,c),D.n):(d=D.O.bm(D.Hz.Eb(a)),e.metricLabel.style.V("color",d),D.xz.Z7(a,b,D.Kz.Eea(a,c),d)))}else D.xz.mA(a,b,new D.N(0,0,c,d))};
D.Kz.eM=function(a,b,c){var d=a.e,e=a.za(),f=e.type,g=D.Hz.Eb(a),h=D.Hz.Ch(a),j=c.x+c.g/2,l=c.y+c.j/2,m=window.Math.min(c.g,c.j)/2,o=(0,D.Jz)(a),q,r=window.Math.min(c.g/100,c.j/100);"rectangle"==f?d=new D.D(d,c.x,c.y,c.g,c.j):"diamond"==f?d=new D.wh(d,[j-m,l,j,l-m,j+m,l,j,l+m]):"star"==f||"triangle"==f||"arrow"==f?("star"==f?q=o?D.Kz.Hba:D.Kz.Csa:"triangle"==f?q=o?D.Kz.Isa:D.Kz.Dsa:"arrow"==f&&(q=o?D.Kz.Gsa:D.Kz.Bsa),o&&"triangle"==f||o&&"arrow"==f?(q=D.P.yW(q,c.x+c.g/2,c.y+c.j/2,r,r),d=new D.Tb(d,
q)):(q=D.Ni.scale(q,r,r),q=D.Ni.translate(q,c.x+c.g/2,c.y+c.j/2),d=new D.wh(d,q))):d=new D.Ah(d,j,l,m);o||"none"==e.visualEffects?d.qa(g):(j=[D.O.Mg(g,-0.09,0.04),D.O.Mg(g,-0.04,-0.05)],l=e&&0==e.rotation%90?e.rotation:0,d.J(new D.bb("arrow"==f||"star"==f||"triangle"==f?l-90:270,j,[1,1],[0,1])));h&&d.La(h);h=a.Ua();(j=D.xz.vN(a))&&h&&h.ka(d,new D.Ga(D.n,j,g));l=o?e.rotation+90:e.rotation;if(0!=l&&("arrow"==f||"triangle"==f))d=D.Kz.x3(a,b,d,c);b.k(d)};
D.Kz.x3=function(a,b,c,d){var e=a.za();a=new D.I(a.e);b.k(a);a.k(c);b=e&&0==e.rotation%90?e.rotation:0;e=new D.jd;e.rotate(window.Math.PI*b/180);c.sa(e);b=a.C();c=d.x+d.g/2-(b.x+b.g/2);d=d.y+d.j/2-(b.y+b.j/2);b=new D.jd;b.translate(c,d);a.sa(b);return a};D.Kz.r3=function(a,b,c){var d=a.za(),e=d.type;"none"!=d.visualEffects&&(0,D.Jz)(a)&&("rectangle"==e?D.Kz.mza(a,b,c):"diamond"==e?D.Kz.lza(a,b,c):"triangle"==e?D.Kz.oza(a,b,c):"star"==e?D.Kz.nza(a,b):"arrow"==e?D.Kz.jza(a,b,c):D.Kz.kza(a,b,c))};
D.Kz.mza=function(a,b,c){var d=0.05*c.g,e=0.05*c.j;c=new D.N(c.x+d,c.y+e,c.g-2*d,c.j-2*e);a=new D.D(a.e,c.x,c.y,c.g,c.j);a.ia(D.p);b.k(a);b=new D.bb(270,"#FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF".split(" "),[0.75,0.5,0.15,0,0.2,0.4,0.2],[0,0.05,0.4,0.6,0.8,0.9,1]);a.J(b)};
D.Kz.lza=function(a,b,c){var d=0.05*c.g,e=0.05*c.j,e=new D.N(c.x+d,c.y+e,c.g-2*d,c.j-2*e);c=e.x+e.g/2;d=e.y+e.j/2;e=window.Math.min(e.g,e.j)/2;a=new D.wh(a.e,[c-e,d,c,d-e,c+e,d,c,d+e]);a.ia(D.p);b.k(a);b=new D.bb(270,"#FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF".split(" "),[0.75,0.5,0.15,0,0.2,0.4,0.2],[0,0.05,0.4,0.6,0.8,0.9,1]);a.J(b)};
D.Kz.oza=function(a,b,c){var d=0.05*c.g,e=0.05*c.j,f=(0,D.Jz)(a),d=new D.N(c.x+d,c.y+e,c.g-2*d,c.j-2*e),e=D.Kz.Jsa,g=window.Math.min(d.g/100,d.j/100),e=D.Ni.scale(e,g,g),e=D.Ni.translate(e,c.x+c.g/2,c.y+c.j/2);c=new D.wh(a.e,e);e=(e=a.za())&&0==e.rotation%90?e.rotation:0;f=new D.bb(f?e-90:360-e,["#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF"],[0.3,0.55,0,0.25,0.1],[0,0.05,0.4,0.9,1]);c.J(f);c=D.Kz.x3(a,b,c,d);c.ia(D.p);b.k(c)};
D.Kz.jza=function(a,b,c){var d=0.05*c.g,e=0.05*c.j,f=(0,D.Jz)(a),d=new D.N(c.x+d,c.y+e,c.g-2*d,c.j-2*e),e=D.Kz.Hsa,g=window.Math.min(d.g/100,d.j/100),e=D.Ni.scale(e,g,g),e=D.Ni.translate(e,c.x+c.g/2,c.y+c.j/2);c=new D.wh(a.e,e);e=(e=a.za())&&0==e.rotation%90?e.rotation:0;f=new D.bb(f?e-90:360-e,["#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF"],[0.3,0.55,0,0.25,0.1],[0,0.05,0.4,0.9,1]);c.J(f);c=D.Kz.x3(a,b,c,d);c.ia(D.p);b.k(c)};
D.Kz.nza=function(a,b){var c=new D.Tb(a.e,D.Kz.Hba),d=a.za(),d=360-(d&&0==d.rotation%90?d.rotation:0),e=D.Hz.Eb(a),e=[D.O.il(e,0.9),e,D.O.Jka(e)],d=new D.bb(d,e,[1,1,1],[0.1,0.4,0.8]);c.J(d);c.ia(D.p);b.k(c)};
D.Kz.kza=function(a,b,c){var d=0.05*c.g,e=0.05*c.j;c=new D.N(c.x+d,c.y+e,c.g-2*d,c.j-2*e);var d=c.x+c.g/2,e=c.y+c.j/2,f=window.Math.min(c.g,c.j)/2,g=new D.Ah(a.e,d,e,f);g.ia(D.p);b.k(g);var h=new D.Pk(["#FFFFFF","#FFFFFF","#FFFFFF"],[0,0.25,0.5],[0.15,0.7,0.95],d,e-0.6*f,1.5*f,[c.x,c.y,c.g,c.j]);g.J(h);g=0.6*f;f*=0.4;e-=0.3*f;a=new D.Ay(a.e,d,e-f,g,f);a.ia(D.p);b.k(a);b=new D.Pk(["#FFFFFF","#FFFFFF","#FFFFFF"],[0,0.2,0.5],[0.6,0.8,1],d,e,g,[c.x,c.y,c.g,c.j]);a.J(b)};
D.Kz.Eea=function(a,b){var c=a.za(),d=c.type,c=0==c.rotation%90?c.rotation:0,e=window.Math.min(b.g,b.j),f=b.x+b.g/2-e/2,g=b.y+b.j/2-e/2,h=e,j=e;"triangle"==d?0==c?(f+=0.2*e,g+=0.25*e,h-=0.4*e,j-=0.3*e):90==c?(f+=0.05*e,g+=0.2*e,h-=0.3*e,j-=0.4*e):180==c?(f+=0.2*e,g+=0.05*e,h-=0.4*e,j-=0.3*e):270==c&&(f+=0.25*e,g+=0.2*e,h-=0.3*e,j-=0.4*e):"arrow"==d?0==c?(f+=0.2*e,g+=0.2*e,h-=0.4*e,j-=0.4*e):90==c?(f+=0.05*e,g+=0.2*e,h-=0.28*e,j-=0.4*e):180==c?(f+=0.2*e,g+=0.2*e,h-=0.4*e,j-=0.4*e):270==c&&(f+=0.23*
e,g+=0.2*e,h-=0.28*e,j-=0.4*e):"star"==d?(f+=0.25*e,g+=0.25*e,h-=0.5*e,j-=0.4*e):"diamond"==d?(f+=0.15*e,g+=0.15*e,h-=0.3*e,j-=0.3*e):"rectangle"==d?(f+=0.1*e,g+=0.1*e,h-=0.2*e,j-=0.2*e):"circle"==d&&(f+=0.15*e,g+=0.15*e,h-=0.3*e,j-=0.3*e);return new D.N(f,g,h,j)};
D.Iz=(0,D.s)();(0,D.ra)("DvtStatusMeterGauge",D.Iz);D.y.l(D.Iz,D.CC,"DvtStatusMeterGauge");D.DC=function(a,b,c){var d=new D.Iz;d.Init(a,b,c);return d};D.Iz.newInstance=D.DC;D.x=D.Iz.prototype;D.x.Init=function(a,b,c){D.Iz.o.Init.call(this,a,b,c);this.vf=new D.uz;this.vZ=D.n};D.x.ge=function(a){D.Iz.o.ge.call(this,this.vf.ah(a))};D.x.Fi=function(a,b,c){D.Pz.L(this,a,b,c)};
D.x.SW=function(a,b,c){b=[];for(var d=0;d<a.length;d++){var e=a[d],f=e.be();"horizontal"==this.M.orientation?e.ue([f[0],f[0],f[2],f[3]]):"vertical"==this.M.orientation?e.ue([f[0],f[1],f[3],f[3]]):"circular"==this.M.orientation&&e.ue([f[0],f[1],0,f[3],f[4]]);var g=new D.Le(this.e,e,c);(0,D.T)(g.R,"typeNumberArray",e,e.be,e.ue,f);g.R.Sj(function(a){return(0,D.BB)(a,0.7)});b.push(g)}return new D.rj(this.e,b)};
D.x.Ru=function(a,b){if("horizontal"==this.M.orientation)return this.vZ.VC(a);if("vertical"==this.M.orientation)return this.vZ.VC(b);if("circular"==this.M.orientation){var c=D.Kb.V7(window.Math.atan2(b-this.Cb/2,a-this.pb/2))-270,c=(c+720)%360;0<=c&&360>=c||(c=360<c?360-c<c-360?0:360:0-c<c?0:360);if((0,D.C)(this.e))for(c=360-c;0>c;)c+=360;var d=this.M.min;return c/360*(this.M.max-d)+d}};
D.uz=function(){this.Init({skyros:D.sz,alta:D.tz})};D.y.l(D.uz,D.vz,"DvtStatusMeterGaugeDefaults");D.tz={color:"#393737",metricLabel:{style:new D.B("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")},plotArea:{color:"#f5f6f7",borderColor:"#D6DFE6"}};D.sz={color:"#313842",indicatorSize:1,metricLabel:{style:new D.B("color: #333333;")},orientation:"horizontal",plotArea:{color:"#AAAAAA",borderColor:"#C6C6C6",rendered:"auto"},thresholdDisplay:"onIndicator"};
D.Pz={};D.y.l(D.Pz,D.y,"DvtStatusMeterGaugeRenderer");D.Pz.L=function(a,b,c,d){if(D.yz.ru(a)){var e=a.za(),f=e.__layout.outerGap;c=new D.N(f,f,c-2*f,d-2*f);"horizontal"==e.orientation||"vertical"==e.orientation?(D.Pz.Xt(a,b,c),D.Pz.eM(a,b,c)):"circular"==e.orientation&&(e=window.Math.min(c.g,c.j),D.xz.Z7(a,b,new D.N(c.x+c.g/2-0.325*e,c.y+c.j/2-0.25*e,0.65*e,0.5*e),D.n),D.Pz.Tya(a,b,c))}else D.xz.mA(a,b,new D.N(0,0,c,d))};
D.Pz.Tya=function(a,b,c){var d=a.za(),e=0,f=d.value,g=d.thresholds,h=window.Math.min(c.g,c.j),j=0.3125*h,l=0.4625*h,m=1.5*window.Math.PI,e=2*e*window.Math.PI;if(g&&"off"!=d.plotArea.rendered&&"all"==d.thresholdDisplay)for(var o=0;o<g.length;o++){var q=D.Hz.sN(a,g[o],o),e=g[o].max?g[o].max:d.max,r=0==o?d.min:g[o-1].max,m=1.5*window.Math.PI+2*window.Math.PI*D.xz.IH(d,d.min,r),e=D.xz.IH(d,r,e),e=2*e*window.Math.PI;D.Pz.v0(a,b,c,m,e,j,l,q,D.k)}else"off"!=d.plotArea.rendered&&(!("auto"==d.plotArea.rendered&&
"onIndicator"==d.thresholdDisplay)&&"all"!=d.thresholdDisplay)&&(q=D.Hz.yla(a),m=1.5*window.Math.PI,e=2*window.Math.PI,D.Pz.v0(a,b,c,m,e,j,l,q,D.k));if((g=d.indicatorSize)&&1!=g)h*=0.075*(1-g),j+=h,l-=h;m=1.5*window.Math.PI;e=D.xz.IH(d,d.min,f);e=2*e*window.Math.PI;D.Pz.v0(a,b,c,m,e,j,l,D.Hz.Eb(a),D.p);if(j=d.referenceLines)for(l=0;l<j.length;l++)h=j[l].color?j[l].color:"black",g=j[l].lineWidth?j[l].lineWidth:2,m=j[l].lineStyle,f=j[l].value,f=1.5*window.Math.PI+2*D.xz.IH(d,d.min,f)*window.Math.PI,
D.Pz.xva(a,b,c,f,h,g,m);c=new D.D(a.e,c.x,c.y,c.g,c.j);(0,D.La)(c);b.k(c);((b=D.xz.vN(a))||a.za().readOnly===D.p)&&a.Ua().ka(c,new D.Ga(D.n,b,D.Hz.Eb(a)))};
D.Pz.eM=function(a,b,c){var d=a.za(),e=(0,D.C)(a.e),f="vertical"==d.orientation,g={layout:{}};g.layout.gapRatio=0;g.timeAxisType="disabled";g.position=f?"left":"bottom";g.min=d.min;g.max=d.max;g.dataMin=d.min;g.dataMax=d.max;g.tickLabel={rendered:"off"};g=(0,D.Jl)(a.e,g,c);a.vZ=g;var h=0;0>=d.max?h=d.max:0<=d.min&&(h=d.min);h=g.sk(h);"off"!=d.plotArea.rendered&&!("auto"==d.plotArea.rendered&&"onIndicator"==d.thresholdDisplay)&&(h=g.hd(d.min));var j=g.hd(d.value),j=f?window.Math.max(c.y,window.Math.min(c.y+
c.j,j)):window.Math.max(c.x,window.Math.min(c.x+c.g,j)),l=0,l=0>d.min&&0>d.value?g.hd(d.min):g.hd(d.max),m,o,q,r,t,u,z,A=0;f?(m=c.x,o=c.x+c.g,r=h,q=window.Math.min(c.y,window.Math.min(c.y+c.j,l)),t=c.x+(1-d.indicatorSize)/2*c.g+0.5,u=c.x+c.g*(1-(1-d.indicatorSize)/2)-0.5,A=h-0.5,z=j+0.5):(m=h,o=window.Math.max(c.x,window.Math.max(c.x+c.g,l)),q=c.y,r=c.y+c.j,t=e?h-0.5:h+0.5,u=e?j+0.5:j-0.5,z=c.y+(1-d.indicatorSize)/2*c.j+0.5,A=c.y+c.j*(1-(1-d.indicatorSize)/2)-0.5);l=D.k;j==h&&(l=D.p);var F=D.Hz.Ch(a),
H=d.plotArea.borderColor,E=d.thresholds,j=f?0:270;if(E&&"off"!=d.plotArea.rendered&&"all"==d.thresholdDisplay)for(h=E.length-1;0<=h;h--){var M=h,S=D.Pz.wv(a,a.e,m,o,q,r,D.k),J=new D.Vf("pacp"+a.getId());h==E.length-1?f?(0,D.Wf)(J,0,0,c.g+2,r-q+2,0,0):e?(0,D.Wf)(J,g.hd(d.max),0,c.g+2,r-q+2,0,0):(0,D.Wf)(J,0,0,c.g+2,r-q+2,0,0):f?(0,D.Wf)(J,0,g.hd(d.max),o-m+2,1*window.Math.abs(d.max-E[E.length-2-M].max)/window.Math.abs(d.min-d.max)*c.j,0,0):e?(0,D.Wf)(J,0,0,1*(d.max-(E[E.length-2-M].max==D.n?100:E[E.length-
2-M].max))/window.Math.abs(d.min-d.max)*c.g,r-q+2,0,0):(0,D.Wf)(J,0,0,1*window.Math.abs(E[M].max-d.min)/window.Math.abs(d.min-d.max)*c.g,r-q+2,0,0);(0,D.Xf)(S,J);if(e||f)M=E.length-1-h;S.qa(D.Hz.sN(a,E[M],M));S.La(H);D.Pz.ria(a,b,S,D.Hz.sN(a,E[M],M),j)}else"off"!=d.plotArea.rendered&&(!("auto"==d.plotArea.rendered&&"onIndicator"==d.thresholdDisplay)&&"all"!=d.thresholdDisplay)&&(S=f?D.Pz.wv(a,a.e,m,o,g.hd(d.max),g.hd(d.min),D.k):D.Pz.wv(a,a.e,g.hd(d.min),g.hd(d.max),q,r,D.k),h=D.Hz.yla(a),S.qa(h),
S.La(H),D.Pz.ria(a,b,S,h,j));h=D.Pz.wv(a,a.e,t,u,z,A,D.k);a.av.push(h);e=D.Hz.Eb(a);!(0,D.Jz)(a)&&"none"!=d.visualEffects?(m=[D.O.Mg(e,-0.09,0.04),D.O.Mg(e,-0.04,-0.05)],m=new D.bb(j,m,[1,1],[0,1]),h.J(m)):h.qa(e);F&&h.La(F);l&&b.k(h);h=D.Pz.wv(a,a.e,t,u,z,A,D.k);D.Pz.r3(a,b,h,l,j);if(A=d.referenceLines)for(h=0;h<A.length;h++)e=A[h].color?A[h].color:"white",u=A[h].value,z=d.indicatorSize,f?(t=((1-z)/2+z)*c.g,l=c.x+(1-z)/4*c.g,u=g.hd(u),l=new D.Pi(a.e,l,u,l+t,u)):(t=((1-z)/2+z)*c.j,l=g.hd(u),u=c.y+
(1-z)/4*c.j,l=new D.Pi(a.e,l,u,l,u+t)),t=new D.db(e,1,A[h].lineWidth?A[h].lineWidth:2),A[h].lineStyle&&t.V((0,D.Md)(A[h].lineStyle)),l.W(t),t=new D.Ee(D.O.Fu(0,0,0,0.8),0.75,3,3,50,1,2,D.p,D.p,D.p),b.k(l),(0,D.Xg)(l,t);c=new D.D(a.e,c.x,c.y,c.g,c.j);(0,D.La)(c);b.k(c);((b=D.xz.vN(a))||d.readOnly===D.p)&&a.Ua().ka(c,new D.Ga(D.n,b,e))};D.Pz.wv=function(a,b,c,d,e,f,g){return new D.Qz(a,b,c,d,e,f,g)};
D.Pz.r3=function(a,b,c,d,e){"none"!=a.za().visualEffects&&(0,D.Jz)(a)&&(e=new D.bb(e,["#FFFFFF","#FFFFFF","#FFFFFF"],[0.5,0.3125,0],[0,0.3,1]),c.J(e),a.av.push(c),c.ia(D.p),d&&b.k(c))};D.Pz.ria=function(a,b,c,d,e){var f=a.za();c.ia(D.p);b.k(c);"none"!=f.visualEffects&&((0,D.Jz)(a)?(a=[D.O.il(d,0.9),d,D.O.Jka(d)],e=new D.bb(e,a,[1,1,1],[0,0.04,0.73])):(a=[D.O.Mg(d,-0.04,-0.05),D.O.Mg(d,-0.09,0.04)],e=new D.bb(e,a,[1,1],[0,1])),c.J(e))};
D.Pz.Xt=function(a,b,c){var d=a.za(),e=(0,D.C)(a.e),f="vertical"==d.orientation,g=new D.Ia(a.e,""),h=D.xz.Nq(d.value,a),j=d.__layout.labelGap;g.Ia(d.metricLabel.style);if(f&&"on"==d.metricLabel.rendered){var l=0<d.max?d.max:d.min,l=D.xz.Nq(l,a),m=new D.Ia(a.e,l);m.Ia(d.metricLabel.style);e=new D.N(c.x,c.y+0.8*c.j,c.g,0.2*c.j);f=(f=d.metricLabel.style.v("font-size"))?(0,window.parseInt)(f):m.Qw(e);m=m.cc();c.j-=m.j;l=m.g;g.Wf(f);g.Dd(h);g.ea(c.x+c.g/2);g.va(c.y+c.j);c.j-=j;g.lf();D.Pa.Vb(g,c.g,c.j,
b)}else if(!f&&"on"==d.metricLabel.rendered){var f=(f=d.metricLabel.style.v("font-size"))?(0,window.parseInt)(f):13,o=D.xz.Nq(d.min,a),m=D.xz.Nq(d.max,a),m=window.Math.max(m.toString().length,o.toString().length),o="";"percent"==d.metricLabel.textType&&(m=3,o+="%");for(var q=0;q<m;q++)o+="0";g.Dd(o);18>c.j&&(f=g.Qw(c));g.Wf(f);var r;if(0<d.max||"off"!=d.plotArea.rendered||!("auto"==d.plotArea.rendered&&"onIndicator"==d.thresholdDisplay))l=0<d.max?d.max:d.min,l=D.xz.Nq(l,a),m=new D.Ia(a.e,l),m.Ia(d.metricLabel.style),
m.Wf(f),m=g.cc(),r=e?c.x+m.g:c.x+c.g,l=m.g,e&&(c.x+=m.g+j),c.g-=m.g+j;if(0>d.min&&"on"!=d.plotArea.rendered&&!("auto"==d.plotArea.rendered&&"onIndicator"==d.thresholdDisplay)){f=D.xz.Nq(d.min,a);o=new D.Ia(a.e,f);o.Ia(d.metricLabel.style);a=o.cc();if(0>d.value||0>=d.max)r=e?c.x+c.g:c.x+a.g,l=a.g;e||(c.x+=a.g+j);c.g-=a.g+j}g.Dd(h);g.ea(r);g.va(c.y+c.j/2);g.Ge();g.Dj();D.Pa.Vb(g,l,c.j,b)}};D.Pz.ot=function(a,b,c){return{x:window.Math.cos(c)*b+a.g/2+a.x,y:window.Math.sin(c)*b+a.j/2+a.y}};
D.Pz.v0=function(a,b,c,d,e,f,g,h,j){var l=a.e;(0,D.C)(a.e)&&(d=window.Math.PI-d-e,d=0<d?d:d+2*window.Math.PI);j?c=new D.Tb(l,D.Pz.Vja(c,d,e,f,g)):(c=new D.Rz(l,c,d,e,f,g),a.av.push(c));c.qa(h);(a=D.Hz.Ch(a))&&!j&&c.La(a);b.k(c)};D.Pz.xva=function(a,b,c,d,e,f,g){var h=a.e,j=window.Math.min(c.g,c.j),l=0.275*j,j=0.5*j;(0,D.C)(a.e)&&(d=window.Math.PI-d,d=0<d?d:d+2*window.Math.PI);a=D.Pz.ot(c,l,d);c=D.Pz.ot(c,j,d);h=new D.Pi(h,a.x,a.y,c.x,c.y);e=new D.db(e,1,f);g&&e.V((0,D.Md)(g));h.W(e);b.k(h)};
D.Pz.Vja=function(a,b,c,d,e){var f,g,h;c<2*window.Math.PI?(f=D.Pz.ot(a,e,b),g=D.Pz.ot(a,e,b+c),h=D.Pz.ot(a,d,b+c),a=D.Pz.ot(a,d,b),e=D.P.moveTo(f.x,f.y)+D.P.arcTo(e,e,c,1,g.x,g.y)+D.P.lineTo(h.x,h.y)+D.P.arcTo(d,d,c,0,a.x,a.y)+D.P.closePath()):(f=D.Pz.ot(a,e,b),g=D.Pz.ot(a,e,b+c/2),h=D.Pz.ot(a,d,b),a=D.Pz.ot(a,d,b+c/2),e=D.P.moveTo(f.x,f.y)+D.P.arcTo(e,e,c/2,1,g.x,g.y)+D.P.arcTo(e,e,c/2,1,f.x,f.y),0<d&&(e+=D.P.moveTo(a.x,a.y)+D.P.arcTo(d,d,c/2,0,h.x,h.y)+D.P.arcTo(d,d,c/2,0,a.x,a.y)),e+=D.P.closePath());
return e};
D.Qz=function(a,b,c,d,e,f,g){this.Init(a,b,c,d,e,f,g)};D.y.l(D.Qz,D.D,"DvtStatusMeterGaugeIndicator");D.Qz.prototype.Init=function(a,b,c,d,e,f,g){D.Qz.o.Init.call(this,b);this.oe=a;this.zza=g;this.ixa="vertical"==a.za().orientation;this.pA(c,d,e,f)};
D.Qz.prototype.pA=function(a,b,c,d){this.gp=a;this.hp=b;this.wAa=c;this.xAa=d;var e=window.Math.min(a,b),f=window.Math.min(c,d);a=window.Math.abs(a-b);c=window.Math.abs(d-c);(0,D.ch)(this,e,f,a,c);this.zza&&(e=(this.ixa?a:c)*((0,D.Jz)(this.oe)?0.25:0.15),2.5<=e&&(0,D.dm)(this,e,e))};D.Qz.prototype.be=function(){return[this.gp,this.hp,this.wAa,this.xAa]};D.Qz.prototype.ue=function(a){a&&4==a.length&&this.pA(a[0],a[1],a[2],a[3])};
D.Rz=function(a,b,c,d,e,f){this.Init(a,b,c,d,e,f)};D.y.l(D.Rz,D.Tb,"DvtStatusMeterGaugeCircularIndicator");D.Rz.prototype.Init=function(a,b,c,d,e,f){D.Rz.o.Init.call(this,a);(0,D.Uz)(this,b,c,d,e,f)};D.Uz=function(a,b,c,d,e,f){b&&b instanceof D.N?a.Ja=b:b=a.Ja;a.bd=c;a.ld=d;a.pi=e;a.Sh=f;a.Ek(D.Pz.Vja(b,c,d,e,f))};D.Rz.prototype.be=function(){return[this.Ja,this.bd,this.ld,this.pi,this.Sh]};D.Rz.prototype.ue=function(a){a&&5==a.length&&(0,D.Uz)(this,a[0],a[1],a[2],a[3],a[4])};
D.FC=(0,D.s)();(0,D.ra)("DvtDialGauge",D.FC);D.y.l(D.FC,D.CC,"DvtDialGauge");D.GC=function(a,b,c){var d=new D.FC;d.Init(a,b,c);return d};D.FC.newInstance=D.GC;D.x=D.FC.prototype;D.x.Init=function(a,b,c){D.FC.o.Init.call(this,a,b,c);this.vf=new D.Yz;this.tZ=D.n};
D.x.ge=function(a){var b=a.background,c=a.indicator;"string"===typeof b&&(a.background=D.Hz.LCa(b),a.background.images=a._backgroundImages);"string"===typeof c&&(a.indicator=D.Hz.MCa(c),a.indicator.images=a._indicatorImages);D.FC.o.ge.call(this,this.vf.ah(a))};D.x.Fi=function(a,b,c){D.Zz.L(this,a,b,c)};
D.x.SW=function(a,b,c){b=[];for(var d=0;d<a.length;d++){var e=a[d],f=e.be(),g=D.Zz.bta(this);e.fh(g);g=new D.Le(this.e,e,c);(0,D.T)(g.R,"typeNumberArray",e,e.be,e.ue,f);g.R.Sj(function(a){return(0,D.BB)(a,0.7)});b.push(g)}return new D.rj(this.e,b)};
D.x.Ru=function(a,b){var c=D.Kb.V7(window.Math.atan2(b-this.tZ.y,a-this.tZ.x));0>=c&&(c+=360);var d=(0,D.C)(this.e),e=this.za().background,f=d?180+e.startAngle:360-e.startAngle,e=e.angleExtent,g=f+e;if(d){g=f;for(f-=e;0>f;)f+=360,g+=360}c+360>=f&&c+360<=g?c+=360:c>=f&&c<=g||(c=c>g?f+360-c<c-g?f:g:f-c<c+360-g?f:g);c=(c-f)/e;d&&(c=1-c);d=this.M.min;return c*(this.M.max-d)+d};
D.Yz=function(){this.Init({skyros:D.Xz,alta:{}})};D.y.l(D.Yz,D.vz,"DvtDialGaugeDefaults");D.Xz={background:{startAngle:180,angleExtent:180,indicatorLength:0.7},metricLabel:{style:new D.B("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")},tickLabel:{scaling:"auto",style:new D.B("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")}};
D.Zz={};D.y.l(D.Zz,D.y,"DvtDialGaugeRenderer");D.Zz.L=function(a,b,c,d){D.yz.ru(a)?(c=new D.N(0,0,c,d),D.Zz.eM(a,b,c),D.Zz.Xt(a,b,c)):D.xz.mA(a,b,new D.N(0,0,c,d))};
D.Zz.eM=function(a,b,c){var d=a.za(),e=D.Zz.Uua(a,c);b.k(e);d.background.majorTickCount&&d.background.radius&&D.Zz.rza(a,b,c);var f=D.Zz.Xua(a,c),g=new D.I(a.e),h=new D.Bz(a.e);b.k(g);g.k(h);h.k(f);var j=f.C(),l=D.Zz.Iea(a,d.value),e=D.Zz.uea(a,c),m=D.Zz.$va(a,j);c=D.Zz.awa(a,c,j);j=new D.jd;j.translate(-m.x,-m.y);j.scale(c,c);f.sa(j);h.fh(l);j=new D.jd;j.translate(e.x,e.y);g.sa(j);a.av.push(h);((d=d.shortDesc)||a.za().readOnly===D.p)&&a.Ua().ka(b,new D.Ga(D.n,d));a.tZ=e};
D.Zz.Uua=function(a,b){var c=a.za().background,d=(0,D.C)(a.e),e=(0,D.Qa)(),f=e?2*b.g:b.g,g=e?2*b.j:b.j,h=c.images;if(h&&0<h.length){var j,l,m,e=[];for(j=0;j<h.length;j++){var o="rtl"==h[j].dir;d&&o?e.push(h[j]):!d&&!o&&e.push(h[j])}h=0<e.length?e:h;for(j=0;j<h.length;j++){var q=h[j],o=q.src,e=q.width,q=q.height,r=o&&-1<o.search(".svg");0==j&&(l=e,m=q);if(r||e>=f&&q>=g||j==h.length-1){var f=new D.Xa(a.e,o,0,0,e,q),t=new D.jd,g=window.Math.min(b.g/e,b.j/q),h=(b.g-g*e)/2;j=(b.j-g*q)/2;t.scale(g,g);t.translate(h,
j);f.sa(t);r&&(0,D.Og)()&&(o=D.Gd.Pj(a.e,o,D.y.Ej(f,f.xZ)))&&f.xZ(o);b.x+=h;b.y+=j;b.g=g*e;b.j=g*q;!(0,window.isNaN)(c.anchorX)&&!(0,window.isNaN)(c.anchorY)&&(c._anchorX=d?b.x+b.g-b.g*c.anchorX/l:b.x+b.g*c.anchorX/l,c._anchorY=b.y+b.j*c.anchorY/m);c.metricLabelBounds&&(e={},e.width=b.g*c.metricLabelBounds.width/l,e.height=b.j*c.metricLabelBounds.height/m,e.y=b.y+b.j*c.metricLabelBounds.y/m,e.x=d?b.x+b.g-b.g*c.metricLabelBounds.x/l-e.width:b.x+b.g*c.metricLabelBounds.x/l,c._metricLabelBounds=e);d=
window.Math.min(b.g/l,b.j/m);c._radius=c.radius*d;c._tickLabelHeight=c.tickLabelHeight*b.j/m;c._tickLabelWidth=c.tickLabelWidth*b.g/l;return f}}}return D.n};
D.Zz.Xua=function(a,b){var c=a.za().indicator,d=D.Zz.Bea(a,b),e=(0,D.Qa)()?2*d:d,f,g,h=c.images;if(h&&0<h.length)for(var j=0;j<h.length;j++){var l=h[j],d=l.src,m=l.width,l=l.height,o=d&&-1<d.search(".svg");0==j&&(f=m,g=l);if(o||l>=e||j==h.length-1)return e=new D.Xa(a.e,d,0,0,m,l),o&&(0,D.Og)()&&D.Gd.Pj(a.e,d,D.y.Ej(e,e.xZ))&&(e.ha(m),e.xa(l)),!(0,window.isNaN)(c.anchorX)&&!(0,window.isNaN)(c.anchorY)&&(c._anchorX=c.anchorX*m/f,c._anchorY=c.anchorY*l/g),e}return D.n};
D.Zz.bta=function(a){var b=a.za().background;a=(0,D.C)(a.e)?180-b.startAngle:b.startAngle;return window.Math.PI*(90-a)/180};D.Zz.Iea=function(a,b){var c=a.za(),d=c.background,e=c.min,c=c.max;b=window.Math.max(window.Math.min(b,c),e);e=(b-e)/(c-e);c=(0,D.C)(a.e);return window.Math.PI*(90-((c?180-d.startAngle:d.startAngle)-e*(c?-d.angleExtent:d.angleExtent)))/180};
D.Zz.uea=function(a,b){var c=a.za().background,d=c._anchorX,c=c._anchorY;return!(0,window.isNaN)(d)&&!(0,window.isNaN)(c)?new D.L(d,c):new D.L(b.x+b.g/2,b.y+b.j/2)};D.Zz.Bea=function(a,b){var c=window.Math.min(b.g,b.j)/2;return a.za().background.indicatorLength*c};D.Zz.$va=function(a,b){var c=a.za().indicator,d=c._anchorX,c=c._anchorY;return!(0,window.isNaN)(d)&&!(0,window.isNaN)(c)?new D.L(d,c):new D.L(b.x+b.g/2,b.y+b.j)};D.Zz.awa=function(a,b,c){return D.Zz.Bea(a,b)/c.j};
D.Zz.Xt=function(a,b,c){var d=a.za();if("on"==d.metricLabel.rendered){var e=D.xz.Nq(d.value,a),f=c.x+c.g/2,g=c.y+c.j/2,h=c.g,j=c.j,l=d.background._metricLabelBounds;l&&(f=l.x+l.width/2,g=l.y+l.height/2,c.g=l.width,c.j=l.height);f=new D.Ia(a.e,e,f,g);!d.metricLabel.style.v("color")&&d.background._isDark&&d.metricLabel.style.V("color","#CCCCCC");f.Ia(d.metricLabel.style);g=(0,window.parseInt)(d.metricLabel.style.JH());if(!g){g=window.Math.max(D.xz.Nq(d.max,a).length,D.xz.Nq(d.min,a).length,e.length);
l="";"percent"==d.metricLabel.textType&&(g=window.Math.max(3,e.length),l+="%");for(d=0;d<g;d++)l+="0";f.Dd(l);g=f.Qw(c);f.Dd(e);f.Wf(g)}f.lf();f.Ge();D.Pa.Vb(f,h,j,b)&&f.wg()&&a.Ua().ka(f,new D.Ga(e))}};
D.Zz.rza=function(a,b,c){var d=a.za(),e=(0,D.C)(a.e);if(d.background.radius&&d.background.majorTickCount){var f=d.background._radius,g=d.min,h=d.max,j=d.background.majorTickCount,l=12,m=new D.N(u,r,c.g,c.j),o=d.metricLabel.style.v("font-size");d.background._tickLabelHeight&&!o&&(m.j=d.background._tickLabelHeight);d.background._tickLabelWidth&&!o&&(m.g=d.background._tickLabelWidth);if(!o){var q=new D.Ia(a.e,"",u,r),l=window.Math.max(D.xz.yU(d.max,a).length,D.xz.yU(d.min,a).length),o="";"percent"==
d.tickLabel.textType&&(l=window.Math.max(3,D.xz.yU(100,a).length-1),o+="%");for(u=0;u<l;u++)o+="0";q.Dd(o);l=q.Qw(m)}for(o=0;o<j;o++){u=g+window.Math.abs(h-g)*o/(j-1);e&&(u=g+window.Math.abs(h-g)*(j-1-o)/(j-1));var q=D.xz.yU(u,a),r=D.Zz.Iea(a,u),t=D.Zz.uea(a,c),u=t.x+f*window.Math.cos(r-window.Math.PI/2),r=t.y+f*window.Math.sin(r-window.Math.PI/2),q=new D.Ia(a.e,q,u,r);!d.tickLabel.style.v("color")&&d.background._isDark&&d.tickLabel.style.V("color","#CCCCCC");q.Ia(d.tickLabel.style);d.tickLabel.style.v("font-size")||
q.Wf(l);q.lf();q.Ge();D.Pa.Vb(q,m.g+0.5,m.j+0.5,b)&&q.wg()&&a.Ua().ka(q,new D.Ga(q.Dq))}}};
D.Bz=function(a){this.Init(a)};D.y.l(D.Bz,D.I,"DvtDialGaugeIndicator");D.Bz.prototype.fh=function(a){var b=new D.jd;b.rotate(a);this.sa(b);this.Ata=a};D.Bz.prototype.be=function(){return[this.Ata]};D.Bz.prototype.ue=function(a){a&&1==a.length&&this.fh(a[0])};
D.HC=(0,D.s)();(0,D.ra)("DvtRatingGauge",D.HC);D.y.l(D.HC,D.CC,"DvtRatingGauge");D.IC=function(a,b,c){var d=new D.HC;d.Init(a,b,c);return d};D.HC.newInstance=D.IC;D.x=D.HC.prototype;D.x.Init=function(a,b,c){D.HC.o.Init.call(this,a,b,c);this.vf=new D.Gz};D.x.ge=function(a){D.HC.o.ge.call(this,this.vf.ah(a))};D.x.Fi=function(a,b,c){var d=this.za().__layout.outerGap,e=this.M.max;this.ok=window.Math.min(c-2*d,(b-2*d)/e);this.Ja=new D.N((this.pb-this.ok*e)/2,d,this.ok*e,this.Cb-2*d);D.Lz.L(this,a,b,c)};
D.x.ma=function(){return new D.Oz(this)};D.x.Ru=function(a){if(D.yz.ru(this)){a=window.Math.max(window.Math.min(a,this.Ja.x+this.Ja.g),this.Ja.x);var b=0,b=(0,D.C)(this.e)?window.Math.max((this.Ja.x+this.Ja.g-a)/this.ok,this.M.min):window.Math.max((a-this.Ja.x)/this.ok,this.M.min);return D.xz.fU(this.M,b)}return D.n};D.cA=function(a){(0,D.Mz)(a,a.M.value,"render")};D.HC.prototype.QP=function(a,b){(0,D.Mz)(this,this.Ru(a,b),"hover")};
D.HC.prototype.GJ=function(a,b){var c=this.Ru(a,b);(0,D.Mz)(this,c,"hover");this.Wa(new D.Wz(this.M.value,c,D.p))};D.HC.prototype.PP=function(a,b){var c=this.M.value;this.M.value=this.Ru(a,b);this.M.changed=D.k;this.L();this.Wa(new D.Wz(c,this.M.value,D.p));this.Wa(new D.Wz(c,this.M.value,D.k))};
D.Mz=function(a,b,c,d){if(D.yz.ru(a)){d||(d=a.ca);var e=(0,D.C)(a.e);b=window.Math.max(window.Math.min(b,a.M.max),0);var f=0,g=b*a.ok,h=b*a.ok;"render"==c&&(f=b*a.ok,g=0);e?(b=d.aa(0),c=new D.Vf("unsel"+a.getId()),(0,D.Wf)(c,a.Ja.x,a.Ja.y,a.Ja.g-h,a.Ja.j),(0,D.Xf)(b,c),b=d.aa(1),c=new D.Vf("sel"+a.getId()),(0,D.Wf)(c,a.Ja.x+a.Ja.g-h,a.Ja.y,f,a.Ja.j),(0,D.Xf)(b,c),d=d.aa(2),f=new D.Vf("hover"+a.getId()),(0,D.Wf)(f,a.Ja.x+a.Ja.g-h,a.Ja.y,g,a.Ja.j)):(b=d.aa(0),c=new D.Vf("unsel"+a.getId()),(0,D.Wf)(c,
a.Ja.x+h,a.Ja.y,a.Ja.g-h,a.Ja.j),(0,D.Xf)(b,c),b=d.aa(1),c=new D.Vf("sel"+a.getId()),(0,D.Wf)(c,a.Ja.x,a.Ja.y,f,a.Ja.j),(0,D.Xf)(b,c),d=d.aa(2),f=new D.Vf("hover"+a.getId()),(0,D.Wf)(f,a.Ja.x,a.Ja.y,g,a.Ja.j));(0,D.Xf)(d,f)}};D.HC.prototype.hE=function(){return new D.bA(this)};
D.Gz=function(){this.Init({skyros:D.Ez,alta:D.Fz})};D.y.l(D.Gz,D.vz,"DvtRatingGaugeDefaults");D.Fz={unselectedState:{shape:"star",color:"#C4CED7",borderColor:D.n},selectedState:{shape:"star",color:"#F8C15A",borderColor:D.n},hoverState:{shape:"star",color:"#007CC8",borderColor:D.n},changedState:{shape:"star",color:"#ED2C02",borderColor:D.n}};
D.Ez={min:0,max:5,unselectedState:{shape:"star",color:"#F2F2F2",borderColor:"#B6B6B6"},selectedState:{shape:"star",color:"#F8C15A",borderColor:"#F5A700"},hoverState:{shape:"star",color:"#66A7DA",borderColor:"#4A86C5"},changedState:{shape:"star",color:"#F8C15A",borderColor:"#959595"},step:1};
D.Oz=function(a){this.Init();this.oe=a};D.y.l(D.Oz,D.Ga,"DvtRatingGaugePeer");D.Oz.prototype.Oe=function(a,b,c){a=this.oe.za();b=this.oe.Ua().zk?D.yz.lD(this.oe,this.oe.Ru(b,c)):D.yz.lD(this.oe);return(b=D.yz.TH(this.oe,b))&&b.shortDesc?b.shortDesc:a.shortDesc};
D.Lz={};D.y.l(D.Lz,D.y,"DvtRatingGaugeRenderer");D.Lz.LP=["circle","diamond","rectangle","star","triangle"];
D.Lz.L=function(a,b,c,d){if(D.yz.ru(a)){var e=a.za(),f=e.__layout.outerGap,g=e.max,h=window.Math.min(d-2*f,(c-2*f)/g);d=new D.N((c-h*g)/2,f,h*g,d-2*f);c=D.yz.TH(a,D.yz.lD(a));var j=e.selectedState.color,l=e.changedState.color,m=e.selectedState.borderColor,o=e.changedState.borderColor;c&&c.color&&(l=j=c.color);c&&c.borderColor&&(o=m=c.borderColor);f={value:0,type:e.unselectedState.shape,color:e.unselectedState.color,borderColor:e.unselectedState.borderColor,visualEffects:e.visualEffects};j={value:0,
type:e.selectedState.shape,color:j,borderColor:m,visualEffects:e.visualEffects};l={value:0,type:e.changedState.shape,color:l,borderColor:o,visualEffects:e.visualEffects};o={value:0,type:e.hoverState.shape,color:e.hoverState.color,borderColor:e.hoverState.borderColor,visualEffects:e.visualEffects};"dot"==e.unselectedState.shape&&(f.type="circle",f.visualEffects="none",f.size=0.05);m=new D.I(a.e);b.k(m);var q=new D.I(a.e);b.k(q);var r=new D.I(a.e);b.k(r);(0,D.Mz)(a,e.value,"render",b);for(var t=0;t<
g;t++){if("none"!=e.unselectedState.shape){var u=(0,D.Nz)(a.e,D.n,D.n,D.k);m.k(u);(0,D.G)(u,d.x+t*h,d.y+d.j/2-h/2);-1==D.Hc.Fa(D.Lz.LP,f.type)&&(f.type="star");u.L(f,h,h)}e.changed?(u=(0,D.Nz)(a.e,D.n,D.n,D.k),q.k(u),(0,D.G)(u,d.x+t*h,d.y+d.j/2-h/2),-1==D.Hc.Fa(D.Lz.LP,l.type)&&(l.type="star"),u.L(l,h,h)):(u=(0,D.Nz)(a.e,D.n,D.n,D.k),q.k(u),(0,D.G)(u,d.x+t*h,d.y+d.j/2-h/2),-1==D.Hc.Fa(D.Lz.LP,j.type)&&(j.type="star"),u.L(j,h,h));u=(0,D.Nz)(a.e,D.n,D.n,D.k);r.k(u);(0,D.G)(u,d.x+t*h,d.y+d.j/2-h/2);
-1==D.Hc.Fa(D.Lz.LP,o.type)&&(o.type="star");u.L(o,h,h)}g=new D.D(a.e,d.x,d.y,d.g,d.j);(0,D.La)(g);b.k(g);(c&&c.shortDesc?c.shortDesc:e.shortDesc)&&a.Ua().ka(g,new D.Oz(a))}else D.xz.mA(a,b,new D.N(0,0,c,d))};
D.bA=function(a){this.Init(a.e,a.Wa,a);this.oe=a;this.fK=this.zk=D.p;this.zfa=(0,D.Vb)();this.f4=D.p};D.y.l(D.bA,D.Cz,"DvtRatingGaugeEventManager");D.x=D.bA.prototype;D.x.zo=function(a){if(this.oe.za().readOnly===D.p&&!this.fK){var b=(0,D.Dz)(this,a.pageX,a.pageY),c=this.oe;(0,D.Mz)(c,c.Ru(b.x,b.y),"hover");this.zk=D.k}D.Cz.o.zo.call(this,a)};
D.x.fj=function(a){if(this.oe.za().readOnly===D.p){if(this.zfa&&this.fK&&this.f4){this.f4=D.p;return}(0,D.Dz)(this,a.pageX,a.pageY);(0,D.cA)(this.oe);this.fK=D.p}D.Cz.o.fj.call(this,a)};D.x.xl=function(a){this.fK||(this.oe.za().readOnly===D.p?(this.zk=D.k,this.zc(),a=(0,D.Dz)(this,a.pageX,a.pageY),this.oe.QP(a.x,a.y)):D.Cz.o.xl.call(this,a))};
D.x.un=function(a){this.zk&&(this.oe.za().readOnly===D.p?(this.zk=D.p,a=(0,D.Dz)(this,a.pageX,a.pageY),this.oe.PP(a.x,a.y),(0,D.cA)(this.oe),this.fK=D.k,this.zfa&&(this.f4=D.k)):D.Cz.o.un.call(this,a))};D.x.P$=(0,D.ca)(D.k);
});