"use strict";
define(['./DvtToolkit'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.BC=(0,D.s)();(0,D.ra)("DvtLegend",D.BC);D.y.l(D.BC,D.mB,"DvtLegend");D.ib=function(a,b,c){var d=new D.BC;d.Init(a,b,c);return d};D.BC.newInstance=D.ib;D.BC.getDefaults=function(a){return(0,D.TB)(new D.iz,a)};D.BC.prototype.Init=function(a,b,c){D.BC.o.Init.call(this,a,b,c);this.setId("legend1000"+window.Math.floor(1E9*window.Math.random()));this.vf=new D.iz;this.ta=new D.oz(this);this.ta.Df(this);this.Ig=[];this.Ja=D.n;this.u4=[];this.af=new D.wa};D.BC.prototype.FJ=(0,D.w)("af");
D.BC.prototype.ge=function(a){a?this.M=this.vf.ah(a):this.M||(this.M=(0,D.xf)(this))};D.BC.prototype.Sw=function(a,b,c){this.ge(a);this.za().isLayout=D.k;a=D.qz.L(this,new D.N(0,0,b,c));this.za().isLayout=D.p;return a};D.BC.prototype.getPreferredSize=D.BC.prototype.Sw;
D.BC.prototype.L=function(a,b,c){this.ge(a);this.za().isLayout=D.p;this.Di();this.Ig=[];this.Ja=D.n;this.u4=[];!(0,D.Qa)()&&"none"!=this.za().hideAndShowBehavior&&(0,D.gk)(this.ta,new D.mz(this.ta,this));return D.qz.L(this,new D.N(0,0,b,c))};D.BC.prototype.render=D.BC.prototype.L;D.BC.prototype.bn=function(a){(0,D.Th)(a,this.Ig)};D.BC.prototype.highlight=D.BC.prototype.bn;
D.BC.prototype.lg=function(a,b){var c=a.Ga();("categoryRollOver"==c||"categoryRollOut"==c)&&"dim"==this.za().hoverBehavior&&(0,D.Uh)(a,this.Ig);(this==b||"showPopup"==c||"hidePopup"==c)&&this.Wa(a)};D.BC.prototype.za=(0,D.w)("M");D.BC.prototype.Ua=(0,D.w)("ta");D.BC.prototype.S=function(){this.ta&&(this.ta.Bs(this),this.ta.S(),this.ta=D.n);D.BC.o.S.call(this)};D.BC.prototype.destroy=D.BC.prototype.S;D.BC.prototype.wZ=(0,D.v)("Ja");D.BC.prototype.Vh=function(){return new D.bz(this)};
D.BC.prototype.getAutomation=D.BC.prototype.Vh;
D.ei={};(0,D.ra)("DvtLegendConstants",D.ei);D.y.l(D.ei,D.y,"DvtLegendConstants");D.ei.dE="background";D.ei.BACKGROUND=D.ei.dE;D.ei.sE="legendItem";D.ei.LEGEND_ITEM=D.ei.sE;D.ei.Np="title";D.ei.TITLE=D.ei.Np;
D.bz=function(a){this.Ba=a;this.Qc=this.Ba.za()};(0,D.ra)("DvtLegendAutomation",D.bz);D.y.l(D.bz,D.we,"DvtLegendAutomation");D.bz.prototype.Fp=function(a){if((a=this.Ba.Ua().ma(a))&&a instanceof D.cz)if(a=a.getData(),a=(0,D.dz)(this,a,this.Qc))return"section"+a;return D.n};
D.dz=function(a,b,c){if(c.sections&&0<c.sections.length){for(var d=0;d<c.sections.length;d++){if(c.sections[d]==b)return"["+d+"]";var e=(0,D.dz)(a,b,c.sections[d]);if(e)return"["+d+"]"+e}return D.n}if(c.items&&0<c.items.length){for(a=0;a<c.items.length;a++)if(c.items[a]==b)return":item["+a+"]";return D.n}};
D.Hk=function(a,b,c){if(c.sections&&0<c.sections.length){for(var d=0;d<c.sections.length;d++){var e=(0,D.Hk)(a,b,c.sections[d]);if(e)return"["+d+"]"+e}return D.n}if(c.items&&0<c.items.length){for(a=0;a<c.items.length;a++)if(c.items[a].text==b.name)return":item["+a+"]";return D.n}};
D.Gk=function(a,b,c){var d=c.indexOf("["),e=c.indexOf("]");if(0<=d&&0<=e){var d=c.substring(d+1,e),f=c.indexOf(":");c=c.substring(e+1);e=c.indexOf("]");return 0<=c.indexOf("[")&&0<=e?(0,D.Gk)(a,b.sections[d],c):0==f?b.items[d]:b.sections[d]}};D.bz.prototype.Ij=function(a){a=(0,D.Gk)(this,this.Qc,a);for(var b=this.Ba.Ig,c=0;c<b.length;c++){var d=b[c].getData();if(a==d)return b[c].ze()[0].pa()}return D.n};D.bz.prototype.getDomElementForSubId=D.bz.prototype.Ij;D.bz.prototype.UH=function(){return this.Qc.title};
D.bz.prototype.getTitle=D.bz.prototype.UH;D.bz.prototype.getItem=function(a){for(var b,c=a.shift(),d=this.Qc;c!=D.i;)0<a.length?d=d.sections[c]:b=d.items[c],c=a.shift();return{text:b.text?b.text:D.n}};D.bz.prototype.getItem=D.bz.prototype.getItem;D.bz.prototype.UDa=function(a){for(var b,c=a.shift(),d=this.Qc;c!=D.i;)0<a.length?d=d.sections[c]:b=d.sections[c],c=a.shift();return{title:b.title?b.title:D.n,items:b.items?(0,D.ez)(b.items):D.n,sections:b.sections?(0,D.fz)(this,b.sections):D.n}};
D.bz.prototype.getSection=D.bz.prototype.UDa;D.ez=function(a){for(var b=[],c=0;c<a.length;c++)b.push({text:a[c].text});return b};D.fz=function(a,b){for(var c=[],d=0;d<b.length;d++)c.push({title:b[d].title?b[d].title:D.n,items:b[d].items?(0,D.ez)(b[d].items):D.n,sections:b[d].sections?(0,D.fz)(a,b[d].sections):D.n});return c};
D.iz=function(){this.Init({skyros:D.gz,alta:D.hz})};D.y.l(D.iz,D.Aa,"DvtLegendDefaults");D.hz={skin:"alta",textStyle:new D.B("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;"),titleStyle:new D.B("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 11px; color: #333333;"),colors:D.Lj};
D.gz={skin:"skyros",orientation:"vertical",position:D.n,backgroundColor:D.n,borderColor:D.n,textStyle:new D.B("font-size: 11px; color: #333333;"),titleStyle:new D.B("font-size: 12px; color: #003d5b;"),titleHalign:"start",hideAndShowBehavior:"none",hoverBehavior:"none",scrolling:"asNeeded",halign:"center",valign:"middle",colors:D.Mj,markerShape:"square",lineWidth:3,layout:{gapWidthRatio:1,gapHeightRatio:1,outerGapWidth:3,outerGapHeight:3,titleGap:3,symbolGapWidth:5,symbolGapHeight:4,rowGap:0,columnGap:8,
sectionGapHeight:6,sectionGapWidth:15},isLayout:D.p};D.jz=function(a,b){return window.Math.ceil(b*a.layout.gapWidthRatio)};D.kz=function(a,b){return window.Math.ceil(b*a.layout.gapHeightRatio)};
D.oz=function(a){this.Init(a.e,a.lg,a);this.Ba=a};D.y.l(D.oz,D.ta,"DvtLegendEventManager");D.x=D.oz.prototype;D.x.Rs=function(a,b){var c=D.n;b instanceof D.Ga&&b.fm()!=D.n?c=b.fm():b instanceof D.cz&&(c=b.getId(),c={type:D.ei.sE,id:c});this.lh(new D.ai(a,c),this.Ba)};D.x.mh=function(a){D.oz.o.mh.call(this,a);var b=this.ma(a.target);if(b){var c=(0,D.nz)(this,b),b=(0,D.pz)(this,b);(c||b)&&a.stopPropagation()}};
D.x.zo=function(a){D.oz.o.zo.call(this,a);var b=this.ma(a.target);b&&(this.tz(b,D.k)&&a.stopPropagation(),this.at(b))};D.x.fj=function(a){D.oz.o.fj.call(this,a);var b=this.ma(a.target);b&&this.tz(b,D.p)&&a.stopPropagation()};D.x.Su=function(a){var b=this.ma(a.target);if(b){a=a.Tna;var c=(0,D.nz)(this,b),b=(0,D.pz)(this,b);(c||b)&&a&&a.preventDefault()}};D.x.PX=function(a){var b=this.ma(a.target);this.tz(b,D.k)&&a.stopPropagation()};D.x.OX=function(a){var b=this.ma(a.target);this.tz(b,D.p)&&a.stopPropagation()};
D.x.lP=function(a){var b=this.ma(a.target);this.tz(b,D.k)&&a.stopPropagation()};D.x.ZI=function(a){var b=this.ma(a.target);this.tz(b,D.p)&&a.stopPropagation()};
D.nz=function(a,b){if("none"==a.Ba.za().hideAndShowBehavior)return D.p;var c=b.Wh?b.Wh():D.n;if(!c||0>=c.length)return D.p;for(var d=b.getData(),e=d.categoryVisibility,f=b.ze(),g=0;g<f.length;g++){var h=f[g];h instanceof D.Ed?h.wI(b.Eb()):h instanceof D.D&&b.$j(h)}c=c[0];"hidden"==e?(d.categoryVisibility="visible",a.lh(new D.pf(D.pf.EE,c),a.Ba)):(d.categoryVisibility="hidden",a.lh(new D.pf(D.pf.Qx,c),a.Ba));return D.k};
D.pz=function(a,b){return b&&b.Fj&&b.Fj()?(a.lh(new D.nl("action",b.Fj(),b.getId()),a.Ba),D.k):D.p};D.oz.prototype.tz=function(a,b){if("none"==this.Ba.za().hoverBehavior)return D.p;var c=a&&a.Wh?a.Wh():D.n;if(!c||0>=c.length)return D.p;this.lh(new D.Wk(b?"categoryRollOver":"categoryRollOut",c[0]),this.Ba);return D.k};
D.mz=function(a,b){this.Init(a,b)};D.y.l(D.mz,D.gf,"DvtLegendKeyboardHandler");D.mz.prototype.Init=function(a,b){D.mz.o.Init.call(this,a);this.Ba=b};D.mz.prototype.lo=function(a){var b=a.keyCode,c=this.ta.Ie();if(9==b){if(c)return a.preventDefault(),c;b=this.Ba.Ig;if(0<b.length)return a.preventDefault(),this.hN(b)}else if(13==b||32==b)c&&(0,D.nz)(this.Ba.Ua(),c);else return D.mz.o.lo.call(this,a)};
D.cz=function(a,b,c,d){this.Init(a,b,c,d)};D.y.l(D.cz,D.y,"DvtLegendObjPeer");D.x=D.cz.prototype;D.x.Init=function(a,b,c,d){this.Ba=a;this.Me=b;this.Ffa=c;this.Oa=c.id?c.id:c.text;this.Al=c.action;this.Rza=c._spb;this.kf=d;this.Zd=D.p;if(this.Al)for(a=0;a<this.Me.length;a++)this.Me[a].setCursor("pointer")};D.x.getData=(0,D.w)("Ffa");D.x.Eb=function(){return this.Ffa.color};D.x.getId=(0,D.w)("Oa");D.x.ze=(0,D.w)("Me");D.x.Wh=function(){return[this.Oa]};D.x.te=(0,D.w)("kf");D.x.Fj=(0,D.w)("Al");
D.x.zd=(0,D.w)("Rza");D.x.vc=function(){if("none"!=this.Ba.za().hideAndShowBehavior){var a=this.Ba.FJ(),b=[(0,D.ob)(a,"hidden"==this.getData().categoryVisibility?"STATE_HIDDEN":"STATE_VISIBLE")];return(0,D.$b)(this.getData().text,b,a)}return D.n};D.x.$j=function(a){(0,D.ac)()||(0,D.Oa)(a,"label",this.vc())};D.x.Rf=function(a){return a.type==D.Cb?this:(0,D.$f)(this,a,this.Ba.Ig)};D.x.of=function(a){return this.Me[0]?this.Me[0].C(a):new D.N(0,0,0,0)};
D.x.$m=function(){return this.Me[0]?this.Me[0].pa():D.n};D.x.Xf=function(){this.Zd=D.k;this.Me[0]&&this.Me[0].La((0,D.lz)())};D.x.Mc=function(){this.Zd=D.p;this.Me[0]&&this.Me[0].W(D.n)};D.x.vg=(0,D.w)("Zd");
D.qz={};D.y.l(D.qz,D.y,"DvtLegendRenderer");D.qz.asa=5;D.qz.bsa=2;D.qz.Zra=0.6;D.qz.oba=10;
D.qz.L=function(a,b){var c=a.za(),d=a.e,e="off"!=c.scrolling;c.isLayout||D.qz.aM(a,b);var f=(0,D.jz)(c,c.layout.outerGapWidth),g=(0,D.kz)(c,c.layout.outerGapHeight);b.x+=f;b.y+=g;b.g-=2*f;b.j-=2*g;a.wZ(b);if(0>=b.g||0>=b.j)return new D.pi(0,0);var h=e?new D.rz(d,b):new D.I(d);a.k(h);var j=b.clone(),l=D.qz.fM(a,h,c.title,j,D.n);if(l){var m=l.cc(),o=(0,D.kz)(c,c.layout.titleGap);j.y+=m.j+o;j.j-=window.Math.floor(m.j+o)}j=D.qz.qza(a,h,j);l=l?(0,D.Ac)(m,j):j;l.j>b.j&&(e&&h.m8(l.j),l.j=b.j);if(c.isLayout)return new D.pi(l.g+
2*f,l.j+2*g);e=c.hAlign!=D.n?c.hAlign:c.halign;"center"==e?h.F(b.x-l.x+(b.g-l.g)/2):"end"==e&&((0,D.C)(d)?h.F(b.x-l.x):h.F(b.x-l.x+b.g-l.g));c=c.vAlign!=D.n?c.vAlign:c.valign;"middle"==c?h.O(b.y-l.y+(b.j-l.j)/2):"bottom"==c&&h.O(b.y-l.y+b.j-l.j);h=a.u4;for(c=0;c<h.length;c++)(0,D.Ui)(l,h[c].CEa,h[c].text,h[c].text.cc().g);return new D.pi(l.g+2*f,l.j+2*g)};
D.qz.aM=function(a,b){var c=a.za(),d=c.backgroundColor,c=c.borderColor;if(d||c){var e=new D.D(a.e,b.x,b.y,b.g,b.j);d?e.qa(d):(0,D.La)(e);c&&(e.La(c),(0,D.Rd)(e));a.Ua().ka(e,new D.Ga(D.n,D.n,D.n,{type:D.ei.dE,id:D.i}));a.k(e)}};
D.qz.fM=function(a,b,c,d,e,f){var g=a.za(),h=(0,D.C)(b.e);if(!c)return D.n;c=new D.Ia(b.e,c,d.x,d.y);var j=e&&e.titleStyle?new D.B(e.titleStyle):g.titleStyle;c.Ia(j);return D.Pa.Vb(c,d.g,window.Infinity,b)?(a.Ua().ka(c,new D.Ga(c.Dq,D.n,D.n,{type:D.ei.Np,id:D.i})),h&&c.ea(d.x+d.g-c.cc().g),g.isLayout?b.removeChild(c):f||a.u4.push({text:c,CEa:e&&e.titleHalign?e.titleHalign:g.titleHalign}),c):D.n};
D.qz.qza=function(a,b,c){var d=a.za();d.symbolWidth==D.n&&d.symbolHeight==D.n?(d.symbolWidth=D.qz.oba,d.symbolHeight=D.qz.oba):d.symbolWidth==D.n?d.symbolWidth=d.symbolHeight:d.symbolHeight==D.n&&(d.symbolHeight=d.symbolWidth);for(var e=(0,D.kz)(d,d.layout.sectionGapHeight),f=(0,D.jz)(d,d.layout.sectionGapWidth),g=D.qz.qwa(a),h="vertical"!=d.orientation,d=d.sections,j=D.n,l=c.clone(),m,o=0;o<d.length;o++)h?(m=D.qz.nia(a,b,d[o],l,g),m.g>l.g?(l.g<c.g&&(c.y+=m.j+e,c.j-=m.j+e),m=m.g<=c.g?D.qz.nia(a,b,
d[o],c,g):D.qz.tia(a,b,d[o],c,g,D.k),c.y+=m.j+e,c.j-=m.j+e,l=c.clone()):(l.g-=m.g+f,(0,D.C)(a.e)||(l.x+=m.g+f))):(m=D.qz.tia(a,b,d[o],c,g,D.p),c.y+=m.j+e,c.j-=m.j+e),j=j?(0,D.Ac)(j,m):m;return j};
D.qz.tia=function(a,b,c,d,e,f){if(c){var g=a.za(),h="off"!=g.scrolling,j=(0,D.jz)(g,g.layout.symbolGapWidth),l=(0,D.kz)(g,g.layout.rowGap),m=(0,D.jz)(g,g.layout.columnGap),o=(0,D.C)(a.e),q=d.clone();h&&(q.j=window.Infinity);var r=(h=D.qz.fM(a,b,c.title,q,c))?h.cc():new D.N(o?q.x+q.g:q.x,q.y,0,0);if(!c.items)return r;0<r.j&&(r.j+=(0,D.kz)(g,g.layout.titleGap),q.y+=r.j,q.j-=r.j);var t=D.qz.zua(a,q,e,c.items,f);f=t.numCols;var h=t.numRows,t=t.width,u=q.y,z=h*(e+l)-l,A=window.Math.min(f*(t+m)-m,q.g);
d=new D.N(o?d.x+d.g-window.Math.max(A,r.g):d.x,d.y,window.Math.max(A,r.g),z+r.j);if(g.isLayout)return d;if(0==h||0==f)return r;g=t-g.symbolWidth-j;j=0;r=1;z=c.items.length;for(A=0;A<z;A++)D.qz.sK(a,b,c.items[A],q,g,e,A),q.y+=e+l,j++,j===h&&r!==f&&(q.y=u,q.g-=t+m,o||(q.x+=t+m),j=0,r++);return d}};
D.qz.nia=function(a,b,c,d,e){if(c){var f=a.za(),g=f.symbolWidth,h=(0,D.jz)(f,f.layout.symbolGapWidth),j=(0,D.jz)(f,f.layout.columnGap),l=c.items.length,m=(0,D.C)(a.e),o=d.clone(),q=D.qz.fM(a,b,c.title,d,c,D.k),r=q?q.cc():new D.N(m?d.x+d.g:d.x,d.y,0,0);if(c.items)0<r.g&&(o.g-=r.g+j,m||(o.x+=r.g+j));else return r;var t=[],u=d.g-o.g,z,A;for(A=0;A<l;A++)z=c.items[A],z=window.Math.ceil(D.qz.Qea(a,z.text)),u+=z+g+h+j,t.push(z);0<l&&(u-=j);r=new D.N(m?d.x+d.g-u:d.x,d.y,u,window.Math.max(e,r.j));if(f.isLayout||
u>d.g)return b.removeChild(q),r;for(A=0;A<l;A++)z=c.items[A],D.qz.sK(a,b,z,o,t[A],e,A),d=t[A]+g+h,o.g-=d+j,m||(o.x+=d+j);return r}};
D.qz.zua=function(a,b,c,d,e){for(var f=a.za(),g=0,h=0;h<d.length;h++){var j=D.qz.Qea(a,d[h].text);j>g&&(g=j)}a=f.symbolWidth;j=(0,D.kz)(f,f.layout.rowGap);h=(0,D.jz)(f,f.layout.columnGap);f=window.Math.ceil(a+(0,D.jz)(f,f.layout.symbolGapWidth)+g);e?(e=window.Math.min(window.Math.floor((b.g+h)/(f+h)),d.length),c=window.Math.ceil(d.length/e)):window.Infinity==b.j?(e=1,c=d.length):(c=window.Math.min(window.Math.floor((b.j+j)/(c+j)),d.length),e=window.Math.ceil(d.length/c),c=window.Math.ceil(d.length/
e));b=window.Math.min(f,(b.g-h*(e-1))/e);return b<a?{width:0,numCols:0,numRows:0}:{width:b,numCols:e,numRows:c}};D.qz.qwa=function(a){var b=a.za();a=new D.Ia(a.e,"Test");a.Ia(b.textStyle);a.Ge();a=D.Pa.sf(a).j;return window.Math.ceil(window.Math.max(a,b.symbolHeight+(0,D.kz)(b,b.layout.symbolGapHeight)))};D.qz.Qea=function(a,b){var c=a.za(),d=new D.Ia(a.e,b);d.Ia(c.textStyle);return d.cc().g};
D.qz.sK=function(a,b,c,d,e,f,g){var h=a.za(),j=a.e,l=(0,D.C)(j),m=h.symbolWidth,o=(0,D.jz)(h,h.layout.symbolGapWidth),q=(0,D.jz)(h,h.layout.columnGap),r=l?d.x+d.g-m:d.x,t=l?d.x+d.g-m-o:d.x+m+o;g=D.qz.Yua(a,r,d.y,f,c,g);var u=c.text,z;if(u&&(z=D.qz.Zua(b,e,u,h.textStyle)))z.ea(t),z.va(d.y+f/2),l&&z.Dj();b.k(g);d=new D.D(j,l?t-e-q/2:r-q/2,d.y,m+o+e+q,f);(0,D.La)(d);b.k(d);b=[d,g,z];if(!b||!c)z=D.n;else{z=new D.cz(a,b,c,z!=D.n?z.Dq:D.n);a.Ig.push(z);for(e=0;e<b.length;e++)a.Ua().ka(b[e],z)}"hidden"==
c.categoryVisibility&&z&&g.wI(z.Eb());"none"!=a.za().hideAndShowBehavior&&(d.Hf("img"),z.$j(d))};D.qz.Zua=function(a,b,c,d){c=new D.Ia(a.e,c);c.Ge();c.Ia(d);return c=D.Pa.Vb(c,b,window.Infinity,a)?c:D.n};
D.qz.Yua=function(a,b,c,d,e,f){var g=a.za();e.markerShape||(e.markerShape=g.markerShape);if(!e.color){var h=g.colors;e.color=h[f%h.length]}e.lineWidth||(e.lineWidth=g.lineWidth);f=g.symbolWidth;g=window.Math.min(f,g.symbolHeight);h=e.type!=D.n?e.type:e.symbolType;"line"==h?(e.lineWidth=window.Math.min(e.lineWidth,D.qz.asa),h=D.qz.nda(a.e,b,c,f,d,e)):"lineWithMarker"==h?(e.lineWidth=window.Math.min(e.lineWidth,D.qz.bsa),h=D.qz.nda(a.e,b,c,f,d,e),"hidden"!=e.categoryVisibility&&h.k(D.qz.pda(a,b,c,f,
d,g*D.qz.Zra,e))):h=D.qz.pda(a,b,c,f,d,g,e);return h};D.qz.pda=function(a,b,c,d,e,f,g){var h=a.e,j=a.za();a=g.markerShape;var l=g.markerColor?g.markerColor:g.color,m=g.pattern;c+=(e-f)/2;b+=(d-f)/2;m?(f=new D.Ed(h,a,j.skin,0,0,f,f),f.J(new D.id(m,l,"#FFFFFF")),(0,D.G)(f,b,c)):(f=new D.Ed(h,a,j.skin,b,c,f,f),f.qa(l));g.borderColor&&f.La(g.borderColor,D.n,g._borderWidth?g._borderWidth:1);"square"==a&&(0,D.Rd)(f);return f};
D.qz.nda=function(a,b,c,d,e,f){c+=e/2;a=new D.Pi(a,b,c,b+d,c);b=new D.db(f.color,1,f.lineWidth);f=f.lineStyle;"dashed"==f?b.Uj((0,D.Md)(f),"4,2,4"):"dotted"==f&&b.Uj((0,D.Md)(f),"2");a.W(b);(0,D.Rd)(a);return a};
});