"use strict";
define(['./DvtToolkit'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.Vl={nm:function(){return(0,D.Qa)()}};D.y.l(D.Vl,D.y,"DvtTimeUtils");D.Vl.We=function(a,b,c,d){c=(c-a)*d;a=b-a;return 0==c||0==a?0:c/a};D.Vl.Xe=function(a,b,c,d){b=c*(b-a);return 0==b||0==d?a:b/d+a};
D.ek=function(a,b,c){this.Init(a,b,c)};(0,D.ra)("DvtOverview",D.ek);D.y.l(D.ek,D.I,"DvtOverview");
D.ek.prototype.Init=function(a,b,c){D.ek.o.Init.call(this,a);this.fb=b;this.ja=c;this.Kn=this.vu()?7:6;if(this.fb!=D.n||this.ja!=D.n)D.Vl.nm()?(this.U(D.Wv.Ce,this.RX,D.p,this),this.U(D.Wv.gj,this.QX,D.p,this),this.U(D.Wv.Kh,this.NX,D.p,this),this.U(D.Cb,this.YI,D.p,this)):(this.U(D.Yq,this.KX,D.p,this),this.U(D.Zq,this.JX,D.p,this),this.U(D.Cb,this.YI,D.p,this),this.U(D.cj,this.Gp,D.p,this),this.U(D.Wt,this.uo,D.p,this),this.U(D.Vt,this.EA,D.p,this),this.U(D.Hn,this.j$,D.p,this),this.U(D.In,this.k$,
D.p,this));this.n1=0};D.ek.prototype.vA=function(a,b){var c=this.We(a),d=this.We(b);if(!(c<this.jq||d>(0,D.Xv)(this))){var e=window.Math.max(d-c,(0,D.Yv)(this));0<e&&(0<=c&&d<=this.pb)&&(d=this.aa(1),this.Zi()?(0,D.Zv)(this,d,this.pb-(c+e)):(0,D.Zv)(this,d,c),(0,D.$v)(this,d,e),(0,D.aw)(this))}};D.bw=function(a){return a.yR==D.n?D.p:-1!=a.yR.indexOf("zoom")};
D.ek.prototype.L=function(a,b,c){if(a==D.n){var d=this.sg,e=this.Vg,f=this.aa(1),g=(0,D.cw)(this,f);f!=D.n&&0!=g&&(this.sia=D.Vl.Xe(d,e,g,this.pb));this.Di()}b!=D.n&&c!=D.n&&(this.pb=b,this.Cb=c);a&&(a=this.Wu(a),this.Go(a));a=this.fb!=D.n||this.ja!=D.n;this.vH(b,c);if(a){e=(d=this.lc())?new D.D(this.e,0,0,b,0,"window"):new D.D(this.e,0,0,0,c,"window");e.qa(this.WT,this.nAa);(0,D.Rd)(e);if(!(0,D.bw)(this)){var h=(0,D.dw)(),j=(0,D.ew)();if(d){var l=(b-36)/2,m=D.P.moveTo(l,0)+D.P.hc(l+3,6,l+8,8)+D.P.lineTo(l+
28,8)+D.P.hc(l+33,6,l+36,0);D.P.closePath();g=D.P.moveTo(l,0)+D.P.hc(l+3,-6,l+8,-8)+D.P.lineTo(l+28,-8)+D.P.hc(l+33,-6,l+36,0);D.P.closePath();var f=new D.D(this.e,0,0,b,h,"lhb"),h=new D.D(this.e,0,0,b,h,"rhb"),o="row-resize";if(this.Y0)var q=(0,D.fw)(this,b,10),l=(0,D.fw)(this,b,10);else q=(0,D.gw)(this,l),l=(0,D.gw)(this,l)}else l=(c-36)/2,m=D.P.moveTo(0,l)+D.P.hc(6,l+3,8,l+8)+D.P.lineTo(8,l+28)+D.P.hc(6,l+33,0,l+36),D.P.closePath(),g=D.P.moveTo(0,l)+D.P.hc(-6,l+3,-8,l+8)+D.P.lineTo(-8,l+28)+D.P.hc(-6,
l+33,0,l+36),D.P.closePath(),f=new D.D(this.e,0-j,0,h,c,"lhb"),h=new D.D(this.e,j,0,h,c,"rhb"),o="col-resize",this.Y0?(q=(0,D.fw)(this,10,c),l=(0,D.fw)(this,10,c)):(q=(0,D.gw)(this,l),l=(0,D.gw)(this,l));f.qa(this.WT,0);h.qa(this.WT,0);(0,D.Rd)(f);(0,D.Rd)(h);m=new D.Tb(this.e,m,"lh");g=new D.Tb(this.e,g,"rh");m.qa(this.VK);m.La(this.VK);g.qa(this.VK);g.La(this.VK);this.WT==this.VK&&((0,D.Rd)(m),(0,D.Rd)(g));f.setCursor(o);h.setCursor(o);m.setCursor(o);g.setCursor(o);q.setCursor(o);l.setCursor(o);
e.k(f);e.k(m);e.k(q);e.k(h);e.k(g);e.k(l)}e.setCursor("move");this.k(e);e=d?new D.Pi(this.e,b-this.uN(),0,b-this.uN(),c,"tab"):"above"==this.VS?new D.Pi(this.e,0,this.wk(),b,this.wk(),"tab"):new D.Pi(this.e,0,c-this.wk(),b,c-this.wk(),"tab");e.La(this.Xza,this.Yza);(0,D.Rd)(e);this.oja=e;this.k(e);this.Yq()&&(d?(e=new D.D(this.e,0,0,b,0,"lbg"),f=new D.D(this.e,0,0,b,0,"rbg")):(e=new D.D(this.e,0,0,0,c,"lbg"),f=new D.D(this.e,0,0,0,c,"rbg")),e.qa(this.ega,this.wxa),this.k(e),f.qa(this.zia,this.vza),
this.k(f),D.Vl.nm()&&j!=D.i&&((0,D.ew)(),d?(d=new D.D(this.e,0,0,b,j,"lbgrh"),j=new D.D(this.e,0,0,b,j,"rbgrh")):(d=new D.D(this.e,0,0,j,c,"lbgrh"),j=new D.D(this.e,0,0,j,c,"rbgrh")),d.qa(this.ega,0),this.k(d),j.qa(this.zia,0),this.k(j)))}this.Wna(b,c);if(this.L0!=D.n)for(j=0;j<this.L0.length;j++)f=this.L0[j],d=b,e=c,o=(0,window.parseInt)(f.q("rs"),10),g=(0,window.parseInt)(f.q("re"),10),f=f.q("c"),o!=D.n&&g!=D.n&&(h=(0,D.hw)(this),o=this.We(o),g=this.We(g)-o,this.Zi()&&(o=h-o-g),d=this.lc()?new D.D(this.e,
0,o,d-this.uN(),g,"ftr"):new D.D(this.e,o,"above"==this.VS?this.wk():0,g,e-this.wk(),"ftr"),f!=D.n&&d.qa(f,0.4),d.setCursor("move"),(0,D.Rd)(d),this.k(d));this.d0==D.n||(0,window.isNaN)(this.d0)||(j=this.We(this.d0),this.lc()?j=new D.Pi(this.e,0,j,b,j,"ocd"):(this.Zi()&&(j=b-j),j=new D.Pi(this.e,j,0,j,c,"ocd")),j.La(this.hva),(0,D.Rd)(j),this.k(j));this.XN(b,c);a&&(e=this.aa(1),this.lc()?(a=e.ga(),j=e.ga()+e.getHeight()-1,this.vu()||(0,D.Og)()?(d=0,h=b-1):(d=1,h=b),e=new D.Pi(this.e,0,a,b,a,"lh"),
f=new D.Pi(this.e,0,j,b,j,"rh"),g=new D.Pi(this.e,d,0,d,a,"ltb"),b=new D.Pi(this.e,d,j,d,c,"rtb"),c=new D.Pi(this.e,h,a,h,j,"bb"),a=new D.Pi(this.e,d,a,d,j,"tb")):(a=1,this.vu()&&(a=0),j=c-1,d=e.da(),h=e.da()+e.getWidth()-1,e=new D.Pi(this.e,d,a,d,j,"lh"),f=new D.Pi(this.e,h,a,h,j,"rh"),g=new D.Pi(this.e,0,window.Math.max(0,a-1),d+1,window.Math.max(0,a-1),"ltb"),b=new D.Pi(this.e,h-1,window.Math.max(0,a-1),b,window.Math.max(0,a-1),"rtb"),c=new D.Pi(this.e,d,j,h,j,"bb"),a=new D.Pi(this.e,d,a,h,a,"tb")),
(0,D.Rd)(e),(0,D.Rd)(f),(0,D.Rd)(g),(0,D.Rd)(b),(0,D.Rd)(c),(0,D.Rd)(a),"none"!=this.rAa&&e.La(this.qAa),this.k(e),"none"!=this.tAa&&f.La(this.sAa),this.k(f),"none"!=this.uua&&this.n_&&(g.La(this.n_),b.La(this.n_)),this.k(g),this.k(b),"none"!=this.pAa&&c.La(this.oAa),this.k(c),"none"!=this.vAa&&a.La(this.uAa),this.k(a),this.vu()&&(b=this.lc()?D.P.moveTo(6,0)+D.P.lineTo(0,5)+D.P.lineTo(5,5)+D.P.lineTo(5,17)+D.P.lineTo(0,17)+D.P.lineTo(6,22)+D.P.lineTo(12,17)+D.P.lineTo(7,17)+D.P.lineTo(7,5)+D.P.lineTo(12,
5)+D.P.closePath():D.P.moveTo(5,0)+D.P.lineTo(0,6)+D.P.lineTo(5,12)+D.P.lineTo(5,7)+D.P.lineTo(17,7)+D.P.lineTo(17,12)+D.P.lineTo(22,6)+D.P.lineTo(17,0)+D.P.lineTo(17,4)+D.P.lineTo(5,4)+D.P.lineTo(5,0)+D.P.closePath(),b=new D.Tb(this.e,b,"arr"),b.qa("#ffffff"),b.La("#000000"),b.eb(D.p),this.k(b),this.AG=b),a=this.lc(),c=this.aa(1),b=(0,D.hw)(this),j=a?this.Cb:this.pb,e=this.T,f=this.sg,g=this.Vg,a=this.sia,d=D.Vl.Xe(f,g,0,e),e=D.Vl.Xe(f,g,j,e),d=this.We(d),j=window.Math.min(j,this.We(e)),a=this.We(a),
j-=d,this.Zi()?(0,D.Zv)(this,c,b-a-j):(0,D.Zv)(this,c,a),(0,D.$v)(this,c,j),(0,D.aw)(this),c=this.T,a=this.sg,j=this.Vg,d=D.Vl.Xe(a,j,1,b),b=D.Vl.Xe(a,j,2,b),d=D.Vl.We(a,j,d,c),this.l1=D.Vl.We(a,j,b,c)-d);this.nfa!=D.n&&(this.n1=window.Math.max(0,D.Vl.We(this.sg,this.Vg,this.nfa,this.T)));0<this.n1&&(b=this.n1/this.l1,this.Zi()&&(b=0-b),(0,D.Jm)(this,b))};D.ek.prototype.render=D.ek.prototype.L;D.x=D.ek.prototype;D.x.wla=function(){return new D.iw(this)};D.x.Wu=function(a){return this.wla(a).parse(a)};
D.x.Go=function(a){this.sg=a.start;this.Vg=a.end;this.T=a.width;this.sia=a.c8;this.d0=a.currentTime;this.nfa=a.iFa;this.Kta=a.IAa;this.jq=window.Math.max(0,a.UFa);this.BG=window.Math.max(0,a.UGa);(0,window.isNaN)(this.jq)&&(this.jq=0);(0,window.isNaN)(this.BG)&&(this.BG=0);this.gz=a.orientation;this.VS=a.hna;this.Dfa=a.zV;a.vka!=D.n&&(this.yR=a.vka.split(" "));a.z7!=D.n&&0<a.z7&&(this.Iga=a.z7);this.tua=a.RAa;this.CM=a.Rna;a.Rna!=D.n&&(this.BM=this.CM.xHa);this.L0=a.XBa;this.uua=a.borderTopStyle;
this.n_=a.borderTopColor;this.WT=a.I8;this.nAa=a.Yna;this.vAa=a.Q8;this.tAa=a.O8;this.pAa=a.K8;this.rAa=a.M8;this.uAa=a.P8;this.sAa=a.N8;this.oAa=a.J8;this.qAa=a.L8;this.Lwa=a.V6;this.VK=a.R6;this.Y0=a.Lla;this.Zea=a.$la;this.Wea=a.Wla;this.mya=a.C7;this.hva=a.m5;this.Zza=a.D8;this.Xza=a.Pna;this.Yza=a.Qna;this.ega=a.Bma;this.wxa=a.Ama;this.zia=a.yna;this.vza=a.xna};D.x.We=function(a){return window.Math.max(0,D.Vl.We(this.sg,this.Vg,a,(0,D.hw)(this)))+this.jq};
D.x.Xe=function(a){return D.Vl.Xe(this.sg,this.Vg,window.Math.max(0,a-this.jq),(0,D.hw)(this))};D.x.Zi=function(){return!this.lc()&&"true"==this.Dfa};D.x.lc=function(){return"vertical"==this.gz};D.hw=function(a){return a.lc()?a.Cb-a.jq-a.BG:a.pb-a.jq-a.BG};D.Xv=function(a){return a.lc()?a.Cb-a.BG:a.pb-a.BG};D.Yv=function(a){return a.l2!=D.n?a.l2:a.Iga!=D.n?(a.l2=D.Vl.We(a.sg,a.Vg,a.sg+a.Iga,(0,D.hw)(a)),a.l2):10};D.ew=function(){return D.Vl.nm()?(0,D.dw)()/2:0};
D.dw=function(){return D.Vl.nm()?30:10};D.jw=function(a){var b=a.getId();return"lh"==b||"rh"==b||"lhb"==b||"rhb"==b||"grpy"==b||"lbgrh"==b||"rbgrh"==b||a.getParent()!=D.n&&"grpy"==a.getParent().getId()};D.ek.prototype.uN=function(){if(this.CM==D.n)return 0;if(this.DM==D.n){var a=(0,window.parseInt)(this.CM.width,10);this.DM=!(0,window.isNaN)(a)&&a<this.pb?a:40}return this.DM};
D.ek.prototype.wk=function(){if(this.CM==D.n)return 0;if(this.nja==D.n){var a=(0,window.parseInt)(this.CM.height,10);this.nja=!(0,window.isNaN)(a)&&a<this.Cb?a:20}return this.nja};D.kw=function(a){return D.Vl.nm()&&a.targetTouches!=D.n?0<a.targetTouches.length?a.targetTouches[0].pageX:D.n:a.pageX};D.lw=function(a){return D.Vl.nm()&&a.targetTouches!=D.n?0<a.targetTouches.length?a.targetTouches[0].pageY:D.n:a.pageY};D.ek.prototype.Yq=(0,D.ca)(D.p);D.mw=function(a){return a.Yq()?a.aa(3):D.n};
D.nw=function(a){return a.Yq()?a.aa(4):D.n};D.ow=function(a){return a.Yq()&&!(0,D.bw)(a)?a.aa(6):D.n};D.pw=function(a,b,c,d){a.lc()?(-1!=c&&b.Vj(c),-1!=d&&b.sl(d)):(-1!=c&&b.Fk(c),-1!=d&&b.Ei(d))};D.qw=function(a,b){return a.lc()?b.an():b.xk()};D.ek.prototype.BF=function(a){a=a.target;if(a!=D.n){var b=a.getId();if(b==D.n)return D.n;if("_border"==b.substr(b.length-7))return this.N5(a);if("tick"!=b.substr(0,4)&&"ltb"!=b&&"rtb"!=b&&"bb"!=b&&"tab"!=b)return a}return D.n};
D.Im=function(a){return"window"==a.getId()||"ftr"==a.getId()||"sta"==a.getId()||(0,D.jw)(a)?D.k:D.p};D.ek.prototype.vu=function(){return window&&window.vu};D.ek.prototype.vH=function(a,b){var c=new D.D(this.e,0,0,a,b,"bg");c.qa(this.mya);(0,D.Rd)(c);this.k(c);return c};D.fw=function(a,b,c){return new D.Xa(a.e,a.Y0,(b-a.Zea)/2,(c-a.Wea)/2,a.Zea,a.Wea,"grpy")};
D.gw=function(a,b){var c=new D.I(a.e,"grpy"),d=a.Lwa;if(a.lc()){for(var e=8+b,f=3,g=0;9>g;g++){var h=new D.Pi(a.e,e+2*g,f,e+2*g+1,f,"dot1"+g);h.La(d);c.k(h);f+=2;h=new D.Pi(a.e,e+1+2*g,f,e+1+2*g+1,f,"dot2"+g);h.La(d);c.k(h);f+=2;h=new D.Pi(a.e,e+2*g,f,e+2*g+1,f,"dot3"+g);h.La(d);c.k(h);f=3}h=new D.Pi(a.e,e+18,f,e+18+1,f,"dot4");h.La(d);c.k(h);f+=4;h=new D.Pi(a.e,e+18,f,e+18+1,f,"dot5")}else{e=3;f=8+b;for(g=0;9>g;g++)h=new D.Pi(a.e,e,f+2*g,e,f+2*g+1,"dot1"+g),h.La(d),c.k(h),e+=2,h=new D.Pi(a.e,e,f+
1+2*g,e,f+1+2*g+1,"dot2"+g),h.La(d),c.k(h),e+=2,h=new D.Pi(a.e,e,f+2*g,e,f+2*g+1,"dot3"+g),h.La(d),c.k(h),e=3;h=new D.Pi(a.e,e,f+18,e,f+18+1,"dot4");h.La(d);c.k(h);e+=4;h=new D.Pi(a.e,e,f+18,e,f+18+1,"dot5")}h.La(d);c.k(h);(0,D.Rd)(c);return c};D.rw=function(a,b){return a.lc()?b.getHeight():b.getWidth()};D.cw=function(a,b){return a.lc()?b.K():b.N()};
D.Zv=function(a,b,c){c=window.Math.max(0,c);a.lc()?b.O(c):b.F(c);if(a.Yq()){(0,D.mw)(a).ha(c);b=c+(0,D.rw)(a,b);var d=(0,D.nw)(a);d.ea(b);d.ha(window.Math.max(0,a.pb-b));D.Vl.nm()&&!(0,D.bw)(a)&&(d=(0,D.ew)(),(a.Yq()&&!(0,D.bw)(a)?a.aa(5):D.n).ea(c-d),(0,D.ow)(a).ea(b))}};
D.$v=function(a,b,c){c=window.Math.max((0,D.Yv)(a),c);var d=c=window.Math.min(a.lc()?a.Cb:a.pb,c);a.lc()?b.xa(d):b.ha(d);if(a.Yq()){var d=(0,D.cw)(a,b)+c,e=(0,D.nw)(a);e.ea(d);e.ha(window.Math.max(0,a.pb-d));D.Vl.nm()&&!(0,D.bw)(a)&&(0,D.ow)(a).ea(d)}(0,D.bw)(a)||(d=b.aa(3),e=b.aa(4),b=b.aa(5),a.lc()?(e.O(c),d.O(c-(0,D.dw)()),b.O(c-10)):(e.F(c),d.F(c-(0,D.dw)()),b.F(c-10)))};
D.ek.prototype.Wna=function(a,b){if(this.BM!=D.n){this.lc();for(var c=(0,D.hw)(this),d=0;d<this.BM.length;d++){var e=this.BM[d],f=(0,window.parseInt)(e.q("time"),10),f=this.We(f),e=e.q("label"),g=0;d+1<this.BM.length?(g=(0,window.parseInt)(this.BM[d+1].q("time"),10),g=this.We(g)-f):g=c-f;this.Zi()&&(f=c-f);this.dU(f,a,b,"tick"+d);this.P4(f,e,a,b,g,"label"+d)}}};
D.ek.prototype.dU=function(a,b,c,d){a=this.lc()?new D.Pi(this.e,0,a,b,a,d):new D.Pi(this.e,a,0,a,c,d);b=new D.db(this.Zza);b.V(1,3);a.W(b);(0,D.Rd)(a);this.k(a)};D.ek.prototype.P4=function(a,b,c,d,e,f){this.lc()?a=new D.Ia(this.e,b,4,a,f):(c="above"==this.VS?2:d-this.wk()+2,a=new D.Ia(this.e,b,a+5,c,f));a.Ia(new D.B("font-weight:bold"));D.Pa.Vb(a,e,window.Infinity,this);a.Jya=a.Dq};D.ek.prototype.XN=(0,D.s)();
D.Jm=function(a,b){var c=a.aa(1);c.aa(3);c.aa(4);c.aa(5);if(b!=(0,D.cw)(a,c)){var d=a.aa(a.ua()-a.Kn),e=a.aa(a.ua()-(a.Kn-1)),f=a.aa(a.ua()-(a.Kn-2)),g=a.aa(a.ua()-(a.Kn-3)),h=a.aa(a.ua()-(a.Kn-4)),j=a.aa(a.ua()-(a.Kn-5));if(a.lc())var l=c.K,m=c.O,o=d.an,q=d.Vj,r=d.Sq,t=d.sl,u=e.an,z=e.Vj,A=e.Sq,F=e.sl,H=f.Sq,E=f.sl,M=g.an,S=g.Vj,J=h.an,aa=h.Vj,oa=h.Sq,ka=h.sl,gb=j.an,zb=j.Vj,Ma=j.Sq,kc=j.sl;else l=c.N,m=c.F,o=d.xk,q=d.Fk,r=d.eo,t=d.Ei,u=e.xk,z=e.Fk,A=e.eo,F=e.Ei,H=f.eo,E=f.Ei,M=g.xk,S=g.Fk,J=h.xk,
aa=h.Fk,oa=h.eo,ka=h.Ei,gb=j.xk,zb=j.Fk,Ma=j.eo,kc=j.Ei;var Ob=a.jq,hg=(0,D.Xv)(a),Tc=(0,D.rw)(a,c);b=window.Math.max(Ob,window.Math.min(hg-Tc,b));Ob="off"!==a.Kta?new D.fm(a.e,0.5,0,D.gm):D.n;(0,D.sw)(Ob,c,l,m,b);(0,D.sw)(Ob,d,o,q,b);(0,D.sw)(Ob,d,r,t,b);(0,D.sw)(Ob,e,u,z,b+Tc);(0,D.sw)(Ob,e,A,F,b+Tc);(0,D.sw)(Ob,f,H,E,b+1);(0,D.sw)(Ob,g,M,S,b+Tc-1);(0,D.sw)(Ob,h,J,aa,b);(0,D.sw)(Ob,j,gb,zb,b);(0,D.sw)(Ob,h,oa,ka,b+Tc);(0,D.sw)(Ob,j,Ma,kc,b+Tc);a.Yq()&&(c=(0,D.mw)(a),(0,D.sw)(Ob,c,c.getWidth,c.ha,
b),Tc=b+Tc,c=(0,D.nw)(a),d=c.getWidth,e=c.ha,f=c.da,g=c.ea,h=a.lc()?a.Cb:a.pb,(0,D.sw)(Ob,c,d,e,h-Tc),(0,D.sw)(Ob,c,f,g,Tc),D.Vl.nm()&&!(0,D.bw)(a)&&(c=(0,D.ew)(),d=a.Yq()&&!(0,D.bw)(a)?a.aa(5):D.n,e=d.da,f=d.ea,g=(0,D.ow)(a),h=g.da,j=g.ea,(0,D.sw)(Ob,d,e,f,b-c),(0,D.sw)(Ob,g,h,j,Tc)));Ob!=D.n&&Ob.play()}};D.sw=function(a,b,c,d,e){a!=D.n?(0,D.T)(a,"typeNumber",b,c,d,e):d.call(b,e)};
D.ek.prototype.KX=function(a){var b=this.BF(a);if(b&&!("bg"==b.getId()||"ocd"==b.getId()))if("label"==b.getId().substr(0,5)&&b instanceof D.Ia)b.wg()&&this.e.Vd().AI(a.pageX,a.pageY,b.Jya,"#000000");else if(this.AG!=D.n&&(0,D.jw)(b)&&(a=(0,D.gc)(this.e,a.pageX,a.pageY),a=this.Fb(a),this.lc()?(0,D.G)(this.AG,a.x+6,a.y-10):(0,D.G)(this.AG,a.x-6,a.y-20),this.AG.eb(D.k)),"window"==b.getId()||"ftr"==b.getId()||"arr"==b.getId()||(0,D.jw)(b))this.vu()&&this.setCursor("move");else return b};
D.ek.prototype.JX=function(a){this.Km==D.n&&this.setCursor("default");a=this.BF(a);if(a!=D.n)return(0,D.jw)(a)&&this.AG!=D.n&&this.AG.eb(D.p),a};
D.ek.prototype.YI=function(a,b,c){a.stopPropagation();var d=this.BF(a);if(d&&!("window"==d.getId()||(0,D.jw)(d)))if("bg"==d.getId()||"label"==d.getId().substr(0,5)||"ocd"==d.getId()||"lbg"==d.getId()||"rbg"==d.getId()){b==D.i&&(b=a.pageX);c==D.i&&(c=a.pageY);a=(0,D.gc)(this.e,b,c);a=this.Fb(a);this.lc()?(c=a.y,d=this.Cb):(c=a.x,d=this.pb);a=this.aa(1);b=c-(0,D.rw)(this,a)/2;(0,D.Jm)(this,b);this.Zi()&&(c=this.pb-c);var e=this.Xe(c);c=new D.Fm("scrollTime");c.setTime(e);b=window.Math.max(0,window.Math.min(b,
d-(0,D.rw)(this,a)));this.Zi()?(d=this.Xe(this.pb-(b+(0,D.rw)(this,a))),a=this.Xe(this.pb-b)):(d=this.Xe(b),a=this.Xe(b+(0,D.rw)(this,a)));(0,D.tw)(c,d);(0,D.uw)(c,a);this.dispatchEvent(c)}else return d};D.ek.prototype.Gp=function(a){(0,D.vw)(this,a)};
D.vw=function(a,b){b.stopPropagation();var c=a.BF(b);if(c!=D.n&&(0,D.Im)(c)){if("ftr"==c.getId()||"sta"==c.getId())c=a.aa(1);a.VR=(0,D.kw)(b);a.mfa=(0,D.lw)(b);if((0,D.jw)(c)){var d=a.aa(1);a.Zi()?(a.u2=a.pb-d.da(),a.F2=a.u2-d.getWidth()):(a.F2=d.da(),a.u2=a.F2+d.getWidth());"grpy"==c.getParent().getId()&&(c=c.getParent());var e=c.getId();"grpy"==e&&(c=d.IU(c),e=c.getId());if("lh"==e||"rh"==e)c=d.IU(c),e=c.getId();"lbgrh"==e&&(c=d.aa(0));"rbgrh"==e&&(c=d.aa(d.ua()-3));D.Vl.nm()||(a.lc()?(c.va(-20),
c.xa(2*(c.getHeight()+20))):(c.ea(-20),c.ha(2*(c.getWidth()+20))));d=c.getCursor();e=a.aa(1);e!=D.n&&e.setCursor(d);if(a.Yq()){var e=(0,D.mw)(a),f=(0,D.nw)(a);e!=D.n&&f!=D.n&&(e.setCursor(d),f.setCursor(d))}}a.Km=c;c=new D.Fm("dropCallback");a.dispatchEvent(c)}};D.ek.prototype.uo=function(a){(0,D.ww)(this,a)};
D.ww=function(a,b){b!=D.n&&b.stopPropagation();if(a.Km!=D.n){if("window"==a.Km.getId())a.zka(0,0,0);else if((0,D.jw)(a.Km)){a.z5();D.Vl.nm()||(a.lc()?(a.Km.va(0),a.Km.xa((0,D.dw)())):(a.Km.ea(0),a.Km.ha((0,D.dw)())));var c=a.aa(1);c!=D.n&&c.setCursor("move");if(a.Yq()){var c=(0,D.mw)(a),d=(0,D.nw)(a);c!=D.n&&d!=D.n&&(c.setCursor("default"),d.setCursor("default"))}}a.Km=D.n;a.VR=-1}};D.ek.prototype.EA=function(a){(0,D.xw)(this,a)};
D.xw=function(a,b){b.stopPropagation();if(a.Km!=D.n&&-1!=a.VR){var c=(0,D.kw)(b),d=(0,D.lw)(b),e=c-a.VR,f=d-a.mfa;a.VR=c;a.mfa=d;"window"==a.Km.getId()?a.ama(0,e,f):"lh"==a.Km.getId()||"lhb"==a.Km.getId()?(0,D.yw)(a,b,e,f,D.k):("rh"==a.Km.getId()||"rhb"==a.Km.getId())&&a.U6(b,e,f)}};D.x=D.ek.prototype;
D.x.RX=function(a){var b=a.targetTouches[0];this.eH=b.pageX;this.MC=b.pageY;2==a.targetTouches.length?(a.preventDefault(),b=a.targetTouches[1],this.fH=b.pageX,this.KM=b.pageY,20>window.Math.abs(this.MC-this.KM)?this.rK=0:this.KM=this.fH=this.MC=this.eH=D.n):(0,D.vw)(this,a)};
D.x.QX=function(a){a.preventDefault();if(this.fH!=D.n&&this.KM!=D.n)if(50>this.rK)this.rK++;else{var b=a.targetTouches[1];this.U6(D.n,b.pageX-this.fH,0);this.fH=b.pageX;this.rK=0}else{b=a.targetTouches[0];if(this.eH!=b.pageX||this.MC!=b.pageY)this.MC=this.eH=D.n;(0,D.xw)(this,a)}};D.x.NX=function(a){this.fH!=D.n&&this.KM!=D.n?this.z5():((0,D.ww)(this,a),this.eH!=D.n&&this.MC!=D.n&&this.YI(a,this.eH,this.MC));this.KM=this.fH=this.MC=this.eH=D.n};
D.x.j$=function(a){var b=a.keyCode;if(37===b||39===b)b=37===b?-1:1,(a.shiftKey?this.U6:this.ama).call(this,a,b,b)};D.x.k$=function(a){var b=a.keyCode;if(37===b||39===b)b=37===b?-1:1,(a.shiftKey?this.z5:this.zka).call(this,a,b,b)};D.x.ama=function(a,b,c){(0,D.zw)(this,"scrollPos",b,c)};D.x.zka=function(a,b,c){(0,D.zw)(this,"scrollEnd",b,c)};
D.zw=function(a,b,c,d){var e=a.aa(1),f=(0,D.cw)(a,e),g=(0,D.rw)(a,e),h=a.jq,j=(0,D.Xv)(a);c=a.lc()?d:c;f+c<=h?((0,D.Zv)(a,e,h),g=a.Zi()?-2:-1):f+g+c>=j?((0,D.Zv)(a,e,j-g),g=a.Zi()?-1:-2):((0,D.Zv)(a,e,f+c),g=a.Zi()?(j-g-f-a.jq)*a.l1:(f-a.jq)*a.l1);(0,D.aw)(a);b=new D.Fm(b);b.hh(g);a.Zi()?(g=a.Xe(a.pb-(f+(0,D.rw)(a,e))),e=a.Xe(a.pb-f)):(g=a.Xe(f),e=a.Xe(f+(0,D.rw)(a,e)));(0,D.tw)(b,g);(0,D.uw)(b,e);a.dispatchEvent(b)};D.ek.prototype.U6=function(a,b,c){(0,D.yw)(this,a,b,c,D.p)};
D.yw=function(a,b,c,d,e){var f=(0,D.hw)(a);d=a.lc()?d:c;if(0!=d){c=a.aa(1);var g=(0,D.cw)(a,c),h=(0,D.rw)(a,c);if(e){if(h-d<=(0,D.Yv)(a)||g+d<=a.jq)return;b=a.lc()?(0,D.gc)(a.e,(0,D.kw)(b),(0,D.lw)(b)).y:(0,D.gc)(a.e,(0,D.kw)(b),(0,D.lw)(b)).x;b=a.Fb(b);if(0<d&&b<=g||0>d&&b>=g)return;(0,D.Zv)(a,c,g+d);(0,D.$v)(a,c,h-d)}else{if(h+d<=(0,D.Yv)(a)||g+h+d>=(0,D.Xv)(a))return;b=a.lc()?(0,D.gc)(a.e,(0,D.kw)(b),(0,D.lw)(b)).y:(0,D.gc)(a.e,(0,D.kw)(b),(0,D.lw)(b)).x;b=a.Fb(b);if(0<d&&b<=g+h||0>d&&b>=g+h)return;
(0,D.$v)(a,c,h+d)}(0,D.aw)(a);b=a.Xe((0,D.rw)(a,c));b=f*(a.Vg-a.sg)/(b-a.sg);a.tma()&&(f=new D.Fm("rangeChanging"),(0,D.Lc)(f,"newSize",b),b=a.Zi()?e:!e,(0,D.Lc)(f,"endHandle",b),e?(0,D.Lc)(f,"expand",0>d):(0,D.Lc)(f,"expand",0<d),a.Zi()?(e=a.Xe(a.pb-((0,D.cw)(a,c)+(0,D.rw)(a,c))),c=a.Xe(a.pb-(0,D.cw)(a,c))):(e=a.Xe((0,D.cw)(a,c)),c=a.Xe((0,D.cw)(a,c)+(0,D.rw)(a,c))),(0,D.tw)(f,e),(0,D.uw)(f,c),a.dispatchEvent(f))}};D.ek.prototype.tma=(0,D.ca)(D.k);
D.ek.prototype.z5=function(){var a=this.sg,b=this.Vg,c=this.T,d=(0,D.hw)(this),e=this.aa(1),f=this.Xe((0,D.rw)(this,e)),a=d*(b-a)/(f-a),b=this.Xe(this.F2),d=this.Xe(this.u2);this.Zi()?(f=this.Xe(this.pb-((0,D.cw)(this,e)+(0,D.rw)(this,e))),e=this.Xe(this.pb-(0,D.cw)(this,e))):(f=this.Xe((0,D.cw)(this,e)),e=this.Xe((0,D.cw)(this,e)+(0,D.rw)(this,e)));var g=new D.Fm("rangeChange");(0,D.Lc)(g,"oldSize",c);(0,D.Lc)(g,"newSize",a);(0,D.Lc)(g,"oldStartTime",b);(0,D.Lc)(g,"oldEndTime",d);(0,D.tw)(g,f);(0,D.uw)(g,
e);this.dispatchEvent(g)};D.aw=function(a){var b=a.aa(1),c=a.aa(a.ua()-a.Kn),d=a.aa(a.ua()-(a.Kn-1)),e=a.aa(a.ua()-(a.Kn-2)),f=a.aa(a.ua()-(a.Kn-3)),g=a.aa(a.ua()-(a.Kn-4)),h=a.aa(a.ua()-(a.Kn-5));(0,D.pw)(a,c,(0,D.cw)(a,b),(0,D.cw)(a,b));(0,D.pw)(a,d,(0,D.cw)(a,b)+(0,D.rw)(a,b),(0,D.cw)(a,b)+(0,D.rw)(a,b));(0,D.pw)(a,e,-1,(0,D.cw)(a,b)+1);(0,D.pw)(a,f,(0,D.qw)(a,d)-1,-1);(0,D.pw)(a,g,(0,D.qw)(a,c),(0,D.qw)(a,d));(0,D.pw)(a,h,(0,D.qw)(a,c),(0,D.qw)(a,d))};
D.ek.prototype.dispatchEvent=function(a){D.km.dispatchEvent(this.fb,this.ja,this,a)};
D.iw=function(a){this.Init(a)};D.y.l(D.iw,D.y,"DvtOverviewParser");D.iw.prototype.Init=(0,D.v)("I");D.iw.prototype.parse=function(a){return this.qm(a)};
D.iw.prototype.qm=function(a){var b={};b.IAa=a.animationOnClick;a.startTime!=D.n&&(b.start=a.startTime);a.endTime!=D.n&&(b.end=a.endTime);b.start==D.n&&(b.start=(new window.Date).getTime());if(b.end==D.n||b.end<=b.start)b.end=b.start+864E5;a.currentTime!=D.n&&(b.currentTime=a.currentTime);a.initialFocusTime!=D.n&&(b.iFa=a.initialFocusTime);b.orientation="horizontal";a.orientation!=D.n&&(b.orientation=a.orientation);b.vka=a.featuresOff;b.z7=a.minimumWindowSize;b.UFa=a.leftMargin;b.UGa=a.rightMargin;
if(a.viewportEndTime!=D.n){var c=a.viewportEndTime,d=b.start;a.viewportStartTime!=D.n&&a.viewportStartTime<c&&(d=a.viewportStartTime);b.width=a.viewportEndPos!=D.n?(0,D.Aw)(b.start,b.end,d,c,a.viewportEndPos):(0,D.Aw)(b.start,b.end,d,c,this.I.pb);b.c8=d}else b.c8=b.start;0==b.width&&(b.width=1E3);b.hna="below";b.eO="none";b.zV=(0,D.C)(this.I.e).toString();a.rtl!=D.n&&(b.zV=a.rtl.toString());b.R6="#FFFFFF";b.V6="#B3C6DB";b.I8="#FFFFFF";b.Yna=1;b.Q8="solid";b.O8="solid";b.K8="solid";b.M8="solid";b.P8=
"#4F4F4F";b.N8="#4F4F4F";b.J8="#4F4F4F";b.L8="#4F4F4F";b.C7="#E6ECF3";b.m5="#C000D1";b.D8="#BCC7D2";b.Pna="#e5e5e5";b.Qna=1;b.Bma="#FFFFFF";b.Ama=0.7;b.yna="#FFFFFF";b.xna=0.7;a.style!=D.n&&(a.style.handleFillColor!=D.n&&(b.R6=a.style.handleFillColor),a.style.handleTextureColor!=D.n&&(b.V6=a.style.handleTextureColor),a.style.handleBackgroundImage!=D.n&&(b.Lla=a.style.handleBackgroundImage),a.style.handleWidth!=D.n&&(b.$la=a.style.handleWidth),a.style.handleHeight!=D.n&&(b.Wla=a.style.handleHeight),
a.style.windowBackgroundColor!=D.n&&(b.I8=a.style.windowBackgroundColor),a.style.windowBackgroundAlpha!=D.n&&(b.Yna=a.style.windowBackgroundAlpha),a.style.windowBorderTopStyle!=D.n&&(b.Q8=a.style.windowBorderTopStyle),a.style.windowBorderRightStyle!=D.n&&(b.O8=a.style.windowBorderRightStyle),a.style.windowBorderBottomStyle!=D.n&&(b.K8=a.style.windowBorderBottomStyle),a.style.windowBorderLeftStyle!=D.n&&(b.M8=a.style.windowBorderLeftStyle),a.style.windowBorderTopColor!=D.n&&(b.P8=a.style.windowBorderTopColor),
a.style.windowBorderRightColor!=D.n&&(b.N8=a.style.windowBorderRightColor),a.style.windowBorderBottomColor!=D.n&&(b.J8=a.style.windowBorderBottomColor),a.style.windowBorderLeftColor!=D.n&&(b.L8=a.style.windowBorderLeftColor),a.style.overviewBackgroundColor!=D.n&&(b.C7=a.style.overviewBackgroundColor),a.style.currentTimeIndicatorColor!=D.n&&(b.m5=a.style.currentTimeIndicatorColor),a.style.timeIndicatorColor!=D.n&&(b.D8=a.style.timeIndicatorColor),a.style.leftFilterPanelColor!=D.n&&(b.Bma=a.style.leftFilterPanelColor),
a.style.leftFilterPanelAlpha!=D.n&&(b.Ama=a.style.leftFilterPanelAlpha),a.style.rightFilterPanelColor!=D.n&&(b.yna=a.style.rightFilterPanelColor),a.style.rightFilterPanelAlpha!=D.n&&(b.xna=a.style.rightFilterPanelAlpha));return b};D.Aw=function(a,b,c,d,e){a=e*(b-a);c=d-c;return 0==a||0==c?0:a/c};
D.Fm=function(a){this.Init("overview");this.Xl=a};D.y.l(D.Fm,D.tb,"DvtOverviewEvent");D.Fm.prototype.Wi=(0,D.w)("Xl");D.Fm.prototype.setTime=function(a){(0,D.Lc)(this,"time",a)};D.Fm.prototype.getTime=function(){return this.Lj("time")};D.tw=function(a,b){(0,D.Lc)(a,"newStartTime",b)};D.uw=function(a,b){(0,D.Lc)(a,"newEndTime",b)};D.Fm.prototype.hh=function(a){(0,D.Lc)(this,"pos",a)};D.Fm.prototype.Sf=function(){return this.Lj("pos")};
});