"use strict";
define(['./DvtToolkit'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.Gs=function(a,b,c){this.Init(a,b,c)};D.y.l(D.Gs,D.I,"DvtComboBox");D.Gs.prototype.Init=function(a,b,c){D.Gs.o.Init.call(this,a,D.n,b);this.D=c;this.kS=[];this.ob=[];this.tja=[];this.Qn=0;this.c_=this.uQ=D.p;this.e2=new D.N(0,0,0,0);this.pc=new D.N(0,0,0,0);this.EM=a.Vd();this.v1=(0,D.Qa)();this.sb=(0,D.TK)(this,b+"_cl");this.k(this.sb);this.pK=new D.I(a);this.pK.ia(D.p);this.k(this.pK);this.d1=new D.sm(a,100,this.wpa,this,1);this.Bha=new D.sm(a,100,this.Cpa,this,1);this.x0=D.p};
D.Gs.prototype.sO=function(a){this.Qn=a;this.uQ||(0,D.UK)(this);a=new D.VK("cbItemChange",a,this.pg);this.pg=D.n;this.Tb(a)};
D.TK=function(a,b){var c=a.e,d=a.e,e=a.C(),e=new D.D(d,0,0,e.g,e.j,b+"_up");(0,D.dm)(e,D.R.yY);(0,D.La)(e);e.k((0,D.WK)(d,e.getWidth(),e.getHeight()));var f=a.e,d=a.C(),d=new D.D(f,0,0,d.g,d.j,b+"_up");d.La(D.R.FO);d.J(new D.bb(0,[D.R.R9,D.R.Q9]));(0,D.dm)(d,D.R.yY);d.k((0,D.WK)(f,d.getWidth(),d.getHeight()));var f=a.e,g=a.C(),g=new D.D(f,0,0,g.g,g.j,b+"_up");(0,D.dm)(g,D.R.yY);g.La(D.R.FO);g.J(new D.bb(0,[D.R.Q9,D.R.R9]));g.k((0,D.WK)(f,g.getWidth(),g.getHeight()));c=new D.Na(c,e,d,g,D.n,b);(0,D.he)(c,
a.XI,a);c.setCursor("pointer");a.v1||c.U(D.cj,a.e$,D.p,a);c.kB=D.k;return c};D.x=D.Gs.prototype;D.x.Cj=function(a,b,c,d,e){a.ia(D.p);this.ob.push(a);this.tja.push(b);b=D.R.Hm(this.e,c?c:a);var f=this.e2,g=this.C();b.g>f.g&&(f.g=b.g,g.g=b.g+16);b.j>f.j&&(f.j=b.j,g.j=b.j);this.e2=f;b=D.n;c&&(d&&e)&&(b=[],b[0]=c,b[1]=d,b[2]=e);this.kS.push(b);this.uQ||(this.removeChild(this.sb),this.sb=(0,D.TK)(this,a.getId()),this.Ha(this.sb,0),(0,D.UK)(this))};D.x.getItem=function(a){return this.ob[a]};
D.x.z6=function(){var a=this.Qn;return 0>a||a>this.ob.length-1?D.n:this.ob[a]};
D.x.XI=function(a){(0,D.ke)(a);this.c_&&(this.c_=D.p,this.Xp&&(this.Xp.eb(D.p),this.Xp.getParent().removeChild(this.Xp),this.Xp=D.n));a=this.e;for(var b=this.D?this.D.comboBox:D.n,c=(0,D.te)(b,"paddingLeft",0),d=(0,D.te)(b,"paddingBottom",0),e=(0,D.te)(b,"paddingRight",0),f=(0,D.te)(b,"paddingInner",0),g=(0,D.te)(b,"paddingTop",0),h=this.e,j,l,m,o=new D.I(h,"__dd"),q=0;q<this.ob.length;q++)m=this.ob[q],j=D.R.Hm(h,m),l=new D.I(h,"__it"+q),(0,D.G)(l,c,g),l.k(m),m.ia(D.k),m.setCursor("pointer"),g+=j.j+
f,this.ta&&(j=new D.ie(this,this.upa,this.e$,D.n,D.n,D.n,this.tja[q]),this.ta.ka(m,j)),o.k(l);b=D.R.BBa(h,this.e2.g+c+e,g+d-f,b);b.k(o);o=(0,D.te)(this.D,"background-color",D.n);c=(0,D.te)(this.D,"backgroundAlpha",1);b.La((0,D.te)(this.D,"border-color",D.n),(0,D.te)(this.D,"borderAlpha",1));o&&b.qa(o,c);this.Xp=b;b=D.R.Hm(a,this.Xp);this.k(this.Xp);o=this.sb.C();b=(0,D.C)(a)?-b.g+1*o.g/4:3*o.g/4;(0,D.G)(this.Xp,b,3*o.j/4);this.sb.ia(D.p);(0,D.Zi)(this.sb,D.k);this.Tb(new D.VK("cbShowDropdown"));(a=
a.Sc)&&(this.v1?a.U(D.Wv.Ce,this.kP,D.k,this):a.U(D.Wt,this.kP,D.k,this))};D.x.wpa=function(){(0,D.Fs)(this);this.uQ||(0,D.UK)(this)};D.x.kP=function(){this.x0=D.p;this.Bha.reset();this.Bha.start()};D.x.Cpa=function(){this.x0||(this.d1.reset(),this.d1.start())};D.x.e$=function(){(0,D.ke)()};
D.x.upa=function(a){this.x0=D.k;this.d1.stop();(0,D.ke)(a);var b;b=a.target;for(var c,d;b;){if((d=b.getId())&&b instanceof D.I&&"__it"==d.substr(0,4)){c=b;break}b=b.getParent()}b=c;var e;this.Xp&&b&&(c=this.Xp.aa(0))&&(e=c.Ve(b));(0,D.Fs)(this);this.pg=a;this.sO(e)};D.Fs=function(a){a.Xp&&(a.Xp.eb(D.p),(0,D.Zi)(a.sb,D.p),a.Tb(new D.VK("cbHideDropdown")),a.c_=D.k);var b=a.e.Sc;b&&(a.v1?b.Ra(D.Wv.Ce,a.kP,D.k,a):b.Ra(D.Wt,a.kP,D.k,a));a.sb.ia(D.k)};D.Gs.prototype.C=(0,D.w)("pc");D.Gs.prototype.qp=(0,D.w)("ob");
D.UK=function(a){var b=D.k,c=a.Qn;if(a.kS&&a.kS.length>c&&(c=a.kS[c])&&2<c.length)(0,D.Hs)(a.sb,c[0]),(0,D.Js)(a.sb,c[1]),(0,D.Is)(a.sb,c[2]),b=D.p;b&&(0<a.pK.ua()&&a.pK.up(0),a.pK.k(a.z6()))};D.WK=function(a,b,c){var d=[];d.push(b-12,c/2-2);d.push(b-4,c/2-2);d.push(b-8,c/2+2);d.push(b-12,c/2-2);a=new D.wh(a,d,D.n);a.La(D.R.FO);a.qa(D.R.FO);a.ia(D.p);return a};D.Gs.prototype.mW=(0,D.v)("ta");D.XK=function(a,b,c,d,e,f){this.Init(a,b,c,d,e,f)};D.y.l(D.XK,D.D,"DropdownItemSprite");
D.XK.prototype.Init=function(a){D.D.o.Init.call(this,a)};
D.VK=function(a,b,c){this.Init(a,b,c)};D.y.l(D.VK,D.jI,"DvtComboBoxEvent");D.VK.prototype.Init=function(a,b,c){D.VK.o.Init.call(this,"comboBoxEvent");b===D.i&&(b=-1);this.CI=a;this.Ht=b;this.xF=c};D.VK.prototype.Fa=(0,D.w)("Ht");
D.ge=function(a,b,c){this.Init(a,b,c)};D.y.l(D.ge,D.I,"DvtBaseControl");D.ge.prototype.Init=function(a,b,c){D.ge.o.Init.call(this,a);this.ba=b;this.e=a;this.EM=a.Vd();this.jd=c};D.ge.prototype.Vd=(0,D.w)("EM");
D.gL=function(a,b,c,d,e){this.Init(a,b,c,d,e)};D.y.l(D.gL,D.ge,"DvtZoomInButton");D.x=D.gL.prototype;D.x.Init=function(a,b,c,d,e){D.gL.o.Init.call(this,a,c,d);this.g_=D.p;this.$T=new D.sm(a,100,this.Spa,this);this.PC=new D.sm(a,250,this.SX,this,1);this.Tm=b;(0,D.he)(this.Tm,this.Qpa,this);this.ta=e;a=new D.ie(this,D.n,this.Rpa,this.I$,this.I$,D.n,(0,D.ob)(this.jd,"CONTROL_PANEL_ZOOMIN"));this.ta.ka(this.Tm,a);this.k(this.Tm)};
D.x.Qpa=function(){if(!this.$T.eh()){var a=this.ba.Fc(),a=(0,D.kB)(this.ba,a),b=new D.fm(this.e,this.ba.Qa());(0,D.ds)(this.ba,a,D.i,D.i,b);b.play()}};D.x.Rpa=function(){this.g_=D.k;this.$T.stop();this.PC.stop();this.PC.start()};D.x.I$=function(){this.g_&&(this.g_=D.p,this.$T.stop(),this.PC.stop())};D.x.SX=function(){this.$T.start()};D.x.Spa=function(){var a=this.ba.Fc();(0,D.ds)(this.ba,(0,D.kB)(this.ba,a))};D.x.gh=function(a){this.Tm.setCursor(a?"pointer":D.n);this.Tm.gh(a);(0,D.je)(this.Tm)};
D.hL=function(a,b,c,d,e){this.Init(a,b,c,d,e)};D.y.l(D.hL,D.ge,"DvtZoomOutButton");D.x=D.hL.prototype;D.x.Init=function(a,b,c,d,e){D.hL.o.Init.call(this,a,c,d);this.h_=D.p;this.aU=new D.sm(a,100,this.Vpa,this);this.PC=new D.sm(a,250,this.SX,this,1);this.Um=b;(0,D.he)(this.Um,this.Tpa,this);this.ta=e;a=new D.ie(this,D.n,this.Upa,this.J$,this.J$,D.n,(0,D.ob)(this.jd,"CONTROL_PANEL_ZOOMOUT"));this.ta.ka(this.Um,a);this.k(this.Um)};
D.x.Tpa=function(){if(!this.aU.eh()){var a=this.ba.Fc(),a=(0,D.lB)(this.ba,a),b=new D.fm(this.e,this.ba.Qa());(0,D.ds)(this.ba,a,D.i,D.i,b);b.play()}};D.x.Upa=function(){this.h_=D.k;this.aU.stop();this.PC.stop();this.PC.start()};D.x.J$=function(){this.h_&&(this.h_=D.p,this.aU.stop(),this.PC.stop())};D.x.SX=function(){this.aU.start()};D.x.Vpa=function(){var a=this.ba.Fc();(0,D.ds)(this.ba,(0,D.lB)(this.ba,a))};D.x.gh=function(a){this.Um.setCursor(a?"pointer":D.n);this.Um.gh(a);(0,D.je)(this.Um)};
D.iL=function(a,b,c,d,e){this.Init(a,b,c,d,e)};D.y.l(D.iL,D.ge,"DvtZoomToFitButton");D.iL.prototype.Init=function(a,b,c,d,e){D.iL.o.Init.call(this,a,c,d);this.hu=b;(0,D.he)(this.hu,this.Wpa,this);this.hu.setCursor("pointer");this.ta=e;a=new D.ie(this,D.n,D.n,D.n,D.n,D.n,(0,D.ob)(this.jd,"CONTROL_PANEL_ZOOMTOFIT"));this.ta.ka(this.hu,a);this.k(this.hu)};D.iL.prototype.Wpa=function(){var a=new D.fm(this.e,this.ba.Qa());this.ba.oo(a);a.play()};
D.YK=function(a,b,c,d,e,f,g){this.Init(a,b,c,d,e,f,g)};D.y.l(D.YK,D.ge,"DvtPanControl");D.x=D.YK.prototype;
D.x.Init=function(a,b,c,d,e,f,g){D.YK.o.Init.call(this,a,d,e);this.Jha=new D.sm(a,50,this.Mpa,this);this.$J=D.p;this.YS=new D.L(20,20);this.Io=f?f:16777215;b.k(c);c&&(this.bl=c,this.bl.eb(D.p),this.bl.U(D.Wv.Ce,this.q$,D.p,this),(0,D.Qa)()||(this.bl.U(D.Cb,this.q$,D.p,this),this.bl.U(D.cj,this.Dpa,D.p,this),this.bl.U(D.Wt,this.Hpa,D.p,this),this.bl.U(D.Yq,this.Gpa,D.p,this),this.bl.U(D.Zq,this.Fpa,D.p,this)),this.bl.U(D.Vt,this.Epa,D.p,this));this.On=b;this.On.U(D.Wv.Ce,this.r$,D.p,this);(0,D.Qa)()||
(this.On.U(D.Cb,this.r$,D.p,this),this.On.U(D.cj,this.Ipa,D.p,this),this.On.U(D.Wt,this.s$,D.p,this),this.On.U(D.Yq,this.Lpa,D.p,this),this.On.U(D.Zq,this.Kpa,D.p,this),this.On.U(D.Vt,this.Jpa,D.p,this));this.Vt=D.R.iBa(a,g);this.Vt.k(this.On);this.k(this.Vt)};D.x.r$=function(a){(0,D.ke)(a)};D.x.Ipa=function(a){(0,D.ke)(a);this.$J=D.k;this.bl&&this.bl.eb(D.p);a=(0,D.iB)(this.ba,a);a=this.On.Fb(a);(0,D.ZK)(this,a.x,a.y,this.On.bh);this.W2=new D.L(a.x,a.y);this.Jha.start();this.Kha=0};
D.x.s$=function(a){this.$J&&((0,D.ke)(a),this.$J=D.p,this.bl&&this.bl.eb(D.k),this.Jha.stop());this.On.Ur(a);this.Vd().zc()};D.x.Lpa=function(a){this.bl&&this.bl.eb(D.k);var b=(0,D.ob)(this.jd,"CONTROL_PANEL_PAN");this.Vd().xO(a.pageX,a.pageY,b,a.target)};D.x.Kpa=function(a){this.s$(a);this.bl&&this.bl.eb(D.p)};D.x.Jpa=function(a){(0,D.ke)(a);a=(0,D.iB)(this.ba,a);a=this.On.Fb(a);this.$J?((0,D.ZK)(this,a.x,a.y,this.On.bh),this.W2=new D.L(a.x,a.y)):(0,D.ZK)(this,a.x,a.y,this.On.Hh)};
D.x.Mpa=function(){if(this.$J){var a=window.Math.atan2(this.YS.y-this.W2.y,this.YS.x-this.W2.x),b=window.Math.cos(a),a=window.Math.sin(a),c=15;this.Kha++;40<this.Kha&&(c*=3);this.ba.Dk(c*b,c*a)}};D.x.q$=function(a){(0,D.ke)(a);this.ba.zW()};D.x.Dpa=function(a){(0,D.ke)(a)};D.x.Hpa=function(a){(0,D.ke)(a);this.Vd().zc()};D.x.Gpa=function(a){var b=(0,D.ob)(this.jd,"CONTROL_PANEL_ZOOMANDCENTER");this.Vd().xO(a.pageX,a.pageY,b,a.target);this.bl.eb(D.k);(0,D.ke)(a)};
D.x.Fpa=function(a){this.Vd().zc();(0,D.ke)(a)};D.x.Epa=function(a){(0,D.ke)(a)};D.ZK=function(a,b,c,d){d.Tj(window.Math.atan2(c-a.YS.y,b-a.YS.x)-window.Math.PI/4)};
D.dL=function(a){this.Init("dvtPZCPExpand");this.Xl=a};D.y.l(D.dL,D.tb,"DvtControlPanelEvent");D.dL.prototype.Wi=(0,D.w)("Xl");
D.me=function(a,b,c){this.Init(a,b,c)};D.y.l(D.me,D.I,"DvtControlPanel");D.$K=[0,0.25,0.5,0.75,1];
D.me.prototype.Init=function(a,b,c){D.me.o.Init.call(this,a);this.a_=this.qQ=D.p;this.ba=b.ba;this.Io=b.Ll;this.jd=b.jc();this.Il=(0,D.qe)(b);this.EM=a.Vd();this.D=D.n;if(this.I=b)this.D=this.I.ts(),this.D.centerButtonDisplayed||(this.Io&=-17,this.I.Ll=this.Io);this.BAa=D.$K;this.xn=D.p;this.ek=this.D.backgroundAlpha;this.ta=new D.qB(a,D.n,b);this.ta.Zr.push(D.me);this.ta.Df(this);this.ta.ka(this,this);this.ud=c;this.JLa=D.p;(0,D.Rd)(this)};D.me.prototype.Vd=(0,D.w)("EM");
D.rB=function(a){a.qQ=D.k;a.$a.ia(D.p);a.Ed.ia(D.p);a.$a.B(a.D.backgroundDragAlpha);a.Ed.B(a.D.borderDragAlpha)};D.wB=function(a){a.qQ=D.p;a.$a.ia(D.k);a.Ed.ia(D.k);a.a_?a.om(D.n):a.wl(D.n)};D.me.prototype.dI=(0,D.ca)(D.k);D.me.prototype.bo=function(){var a=0,a=this.dI()?D.Bt.nV():D.Bt.bo();return window.Math.max((0,D.te)(this.D,"tabSize",0),a)};
D.aL=function(a){var b=a.e,c=new D.I(b),d=a.bo(),e=(0,D.C)(b);a.$a=D.Bt.Zja(b,d,a.D,e);a.Ed=D.Bt.g5(b,d,a.D,e);a.Iua=D.R.Hm(b,a.Ed);a.Jc=D.R.pU(a.e,a.Il,a.bo(),a.D,e);(0,D.he)(a.Jc,a.XI,a);a.Jc.setCursor("pointer");b=new D.ie(a,D.n,D.n,D.n,D.n,D.n,(0,D.ob)(a.jd,"CONTROL_PANEL"));a.ta.ka(a.Jc,b);a.Ed.k(a.Jc);c.k(a.$a);c.k(a.Ed);return c};
D.bL=function(a){var b=a.e,c=new D.I(b);a.$a=new D.I(b);a.Ed=new D.I(b);c.k(a.$a);c.k(a.Ed);var d=(0,D.C)(b),e=0,f=new D.I(b),g;g=0;var h=a.e,j=a.dI();0!=(a.Io&16)&&(a.Vt=D.R.jBa(h,a.ba,a.jd,a.Io,a.Il,a.D),j&&(a.gw=D.R.fka(h,a.D),a.RL=D.R.fka(h,a.D),f.k(a.RL),f.k(a.gw)),f.k(a.Vt),g++);a.Ki=D.R.nU(a.e,a.Il,a.bo(),a.D,(0,D.C)(a.e));(0,D.he)(a.Ki,a.CX,a);a.Ki.setCursor("pointer");h=new D.ie(a,D.n,D.n,D.n,D.n,D.n,(0,D.ob)(a.jd,"CONTROL_PANEL"));a.ta.ka(a.Ki,h);f.k(a.Ki);a.tr=new D.I(a.e);a.mJ(a.tr);0<
a.tr.ua()?(f.k(a.tr),g++):a.tr=D.n;var h=e,e=a.e,l=D.n,j=(0,D.te)(a.D,"openCloseButtonWidth",0),m=(0,D.te)(a.D,"buttonWidth",0),o=(0,D.te)(a.D,"tabSize",0),q=a.bo(),r=(0,D.te)(a.D.hbar,"paddingLeft",0),t=(0,D.te)(a.D.hbar,"paddingInner",0);d?(a.Ki.F(0),h+=j,a.tr&&(l=D.R.Hm(e,a.tr),h+=t,(0,D.G)(a.tr,h,(q-l.j)/2),h+=window.Math.max(l.g,m)),a.Vt&&(h+=t,l=3.5,(0,D.G)(a.Vt,h,l),a.gw&&(0,D.G)(a.gw,h,l),a.RL&&(0,D.G)(a.RL,h,l),l=D.R.Hm(e,a.Vt),h+=l.g),h+=r):(a.Vt&&(h+=r,l=3.5,(0,D.G)(a.Vt,r,l),a.gw&&(0,D.G)(a.gw,
r,l),a.RL&&(0,D.G)(a.RL,r,l),l=D.R.Hm(e,a.Vt),h+=t+l.g,h+=1),a.tr&&(l=D.R.Hm(e,a.tr),0==h&&(h+=r),(0,D.G)(a.tr,h,(q-l.j)/2),h+=l.g,h=window.Math.max(h+t,o)),a.Ki.F(h),h+=j);e=h;h=D.n;j=a.Io&16||a.D&&a.D.panelDrawerStyles&&0==g?(0,D.te)(a.D.vbar,"paddingTop",0):0;a.dI()&&0!=(a.Io&16)&&(j+=D.Bt.bo()-a.bo());if(0!=(a.Io&256)||0!=(a.Io&4097))h=new D.I(b),h.O(f.K()+a.bo()),o=h,0!=(a.Io&256)&&(q=(0,D.te)(a.D.vbar,"paddingInner",0),r=(0,D.te)(a.D.vbar,"paddingLeft",0),a.hu=D.R.vBa(a.e,a.ba,a.jd,a.ta,a.Il,
a.D),(0,D.G)(a.hu,r,a.hu.K()+j),r=D.R.Hm(a.e,a.hu),o.k(a.hu),j+=r.j,j+=q),o=h,q=D.n,r=(0,D.te)(a.D.vbar,"paddingInner",0),t=(0,D.te)(a.D.vbar,"paddingLeft",0),0!=(a.Io&4097)&&(a.Tm=D.R.tBa(a.e,a.ba,a.jd,a.ta,a.Il,a.D),(0,D.G)(a.Tm,t,a.Tm.K()+j),q=D.R.Hm(a.e,a.Tm),o.k(a.Tm),j+=q.j+r,a.Um=D.R.uBa(a.e,a.ba,a.jd,a.ta,a.Il,a.D),(0,D.G)(a.Um,t,a.Um.K()+j),q=D.R.Hm(a.e,a.Um),o.k(a.Um),j+=q.j,o=a.ba.Fc(),q=(0,D.kB)(a.ba,o),r=(0,D.lB)(a.ba,o),a.Tm&&a.Tm.gh(o!=q),a.Um&&a.Um.gh(o!=r)),a.Ed.k(h);var r=h,t=g,
o=a.e,u=(0,D.te)(a.D,"openCloseButtonWidth",0),q=(0,D.te)(a.D,"tabSize",0),e=(l=(0,D.te)(a.D,"panelDrawerStyles",D.n))?e:e-u,m=a.bo(),z=0,A=0;l?l&&0==t&&(A=d?-q:q):(z=d?u:0,A=d?u:0);if(0<t||l){var F=u=D.n,F=(0,window.parseInt)((0,D.te)(a.D,"border-radius",0));l?(d=0<t&&r!=D.n?D.Bt.aY:D.Bt.bY,u=D.Bt.Wma(o,F,e,m,d,q),F=D.Bt.Wma(o,F,e,m,d,q)):(u=D.Bt.$ja(o,e,a.bo(),!d,a.D),F=D.Bt.$ja(o,e,a.bo(),!d,a.D));u.La((0,D.te)(a.D,"border-color",D.n));u.J(D.n);(0,D.G)(u,f.N()+z,f.K());f.Ha(u,0);F.qa((0,D.te)(a.D,
"background-color",D.n));(0,D.G)(F,f.N()+A,f.K());a.$a.k(F)}a.Ed.k(f);d=h;e=a.e;o=(0,D.C)(e);q=(0,D.te)(a.D,"openCloseButtonWidth",0);!a.tr&&0==(a.Io&16)?o?(f.F(0-f.N()),f.O(0),d&&(D.R.Hm(e,d),f.F(f.N()-q),d.O(0))):d?(e=(0,D.te)(a.D,"tabSize",0),(0,D.G)(d,0,0),(0,D.G)(f,f.N()+e,0)):(0,D.G)(f,f.N(),0):o&&d&&(e=D.R.Hm(e,f),o=(0,D.te)(a.D,"tabSize",0),f.F(0),d.F(e.g+e.x-o));d=h;o=j;h=a.e;d&&(e=d.ua(),e=1<e||a.hu==D.n||1<g||0<g&&1==e,j=D.n,a.D&&a.D.panelDrawerStyles&&(j=0<g?D.Bt.dY:D.Bt.cY),f=D.R.Hm(h,
f),o+=4,g=e?o:window.Math.max(f.j,o),g+=(0,D.te)(a.D.vbar,"paddingBottom",0),f=D.Bt.KGa(h,g,a.D,j,a.bo()),g=D.Bt.JGa(h,g,e,a.D,j,a.bo()),(0,D.G)(f,d.N(),d.K()),a.$a.k(f),d.Ha(g,0));a.Gva=D.R.Hm(b,c);return c};D.me.prototype.mJ=(0,D.s)();D.me.prototype.zO=function(){this.xn||(2===this.ud?this.zB():1===this.ud&&this.HK())};D.me.prototype.XI=function(a){(0,D.ke)(a);this.xn||(this.HK(),this.Vd()&&this.Vd().zc())};
D.me.prototype.HK=function(){this.xn=D.k;this.ia(D.p);var a=(0,D.bL)(this);this.k(a);(0,D.cL)(this);var b=this.aa(0),c=b.C(),d=(0,D.te)(this.D,"openCloseButtonWidth",0);if(c&&0!=c.g){var e=a.C(),f=new D.fm(this.e,0.25);b.B(1);a.B(0);(0,D.T)(f,"typeNumber",b,b.Z,b.B,0);(0,D.T)(f,"typeNumber",a,a.Z,a.B,1);a.Nd(c.g/e.g);(0,D.T)(f,"typeNumber",a,a.Sb,a.Nd,1);if((0,D.C)(this.e)){a.F(b.N());var g=e.g+e.x;(0,D.T)(f,"typeNumber",a,a.N,a.F,b.N()+d-g)}a.Cd(c.j/e.j);(0,D.T)(f,"typeNumber",a,a.Wb,a.Cd,1);f.Md(function(){b.getParent().removeChild(b);
this.xn=D.p;this.ia(D.k)},this);f.play()}else b.getParent().removeChild(b),(0,D.C)(this.e)?(e=(0,D.Sn)(this.e,a),g=window.Math.floor(e.g+e.x),c=d-g):c=0,(0,D.G)(a,c,0);this.ud=2;a=new D.dL("show");this.Tb(a)};D.cL=function(a){var b=D.p;a.e.Sc&&(b=D.k);b?(0,D.eL)(a):(0,D.fL)(a)};D.me.prototype.CX=function(a){(0,D.ke)(a);this.xn||this.zB()};
D.me.prototype.zB=function(){this.xn=D.k;var a=(0,D.aL)(this);this.k(a);(0,D.cL)(this);var b=this.aa(0),c=new D.fm(this.e,0.25);b.B(1);a.B(0);(0,D.T)(c,"typeNumber",b,b.Z,b.B,0);(0,D.T)(c,"typeNumber",a,a.Z,a.B,1);var d=this.Iua,e=this.Gva;(0,D.T)(c,"typeNumber",b,b.Sb,b.Nd,d.g/e.g);(0,D.C)(this.e)&&(0,D.T)(c,"typeNumber",b,b.N,b.F,a.N());(0,D.T)(c,"typeNumber",b,b.Wb,b.Cd,d.j/e.j);c.Md(function(){b.getParent().removeChild(b);this.xn=D.p},this);c.play();this.ud=1;a=new D.dL("hide");this.Tb(a)};
D.me.prototype.om=function(){this.a_=D.k;this.qQ||(0,D.eL)(this)};D.me.prototype.wl=function(){this.a_=D.p;this.qQ||(0,D.fL)(this)};D.eL=function(a){a.$a.B(a.D.backgroundHoverAlpha);a.Ed.B(a.D.borderHoverAlpha);a.gw&&a.gw.B(a.D.backgroundHoverAlpha)};D.fL=function(a){a.$a.B(a.ek);a.Ed.B(a.D.borderAlpha);a.gw&&a.gw.B(a.ek)};D.me.prototype.C=function(){this.pc||(this.pc=D.me.o.C.call(this));return this.pc};
D.me.prototype.jn=function(){var a;a=1==this.ud?(0,D.aL)(this):(0,D.bL)(this);this.$a.B(this.ek);this.Ed.B(this.D.borderAlpha);this.k(a)};D.me.prototype.Kq=(0,D.w)("Il");D.eB=function(a,b){a.Tm&&a.Tm.gh(b)};D.fB=function(a,b){a.Um&&a.Um.gh(b)};
D.oB={};D.y.l(D.oB,D.y,"DvtControlPanelDefaults");
D.oB.HY={"fill-type":"solid",backgroundAlpha:1,backgroundDragAlpha:1,borderDragAlpha:1,panelDrawerStyles:D.k,buttonWidth:42,buttonHeight:42,buttonRadius:0,openCloseButtonWidth:42,tabSize:42,paddingTop:15,paddingSide:-1,imageWidth:24,imageHeight:24,centerButtonDisplayed:D.p,scrollbarBackground:"linear-gradient(bottom, #dce2e7 0%, #f8f8f8 8%)",scrollbarBorderColor:"#dce2e7",scrollbarHandleColor:"#abb0b4",scrollbarHandleHoverColor:"#333333",scrollbarHandleActiveColor:"#333333",comboBox:{paddingTop:0,
paddingBottom:0,paddingLeft:0,paddingRight:0,paddingInner:0,itemHeight:30,imagePadding:0,itemPadding:10},vbar:{paddingTop:0,paddingBottom:0,paddingLeft:0,paddingRight:0,paddingInner:0},hbar:{paddingTop:0,paddingBottom:0,paddingLeft:0,paddingRight:0,paddingInner:0}};D.oB.IY={"fill-type":"solid"};
D.oB.AA={"fill-type":"gradient","border-color":"#ffffff","background-color":"#ffffff","border-radius":6,backgroundAlpha:0.5,backgroundHoverAlpha:1,backgroundDragAlpha:0.5,borderAlpha:1,borderHoverAlpha:1,borderDragAlpha:0.5,tabSize:26,buttonWidth:22,buttonHeight:22,buttonRadius:3,paddingTop:5,paddingSide:5,imageWidth:22,imageHeight:20,openCloseButtonWidth:10,centerButtonDisplayed:D.k,comboBox:{paddingTop:2,paddingBottom:6,paddingLeft:3,paddingRight:3,paddingInner:2,itemHeight:22,radius:4,imagePadding:2,
itemPadding:7},vbar:{paddingTop:2.5,paddingBottom:2.5,paddingLeft:2,paddingRight:2,paddingInner:2},hbar:{paddingTop:2,paddingBottom:2,paddingLeft:3,paddingRight:3,paddingInner:2}};D.oB.ah=function(a){var b=D.oB.LB(a);return a?D.Sa.Ob(a,b):b};D.oB.LB=function(a){var b=D.n;return b=a&&"skyros"===a.skin?D.Sa.Ob(D.oB.IY,D.oB.AA):a&&"alta"===a.skin?D.Sa.Ob(D.oB.HY,D.oB.AA):D.Sa.clone(D.oB.AA)};
D.qB=function(a,b,c){this.Init(a,b,c)};D.y.l(D.qB,D.ta,"DvtControlPanelEventManager");D.x=D.qB.prototype;D.x.xl=function(a){var b=this.ma((0,D.ua)(a));D.qB.o.xl.call(this,a);b&&(b.Gp&&b.Gp(a),a.stopPropagation())};D.x.un=function(a){var b=this.ma((0,D.ua)(a));D.qB.o.un.call(this,a);b&&(b.uo&&b.uo(a),a.stopPropagation())};D.x.fj=function(a){var b=this.ma((0,D.ua)(a));D.qB.o.fj.call(this,a);b&&(b.rE&&b.rE(a),a.stopPropagation())};
D.x.mh=function(a){var b=this.ma((0,D.ua)(a));D.qB.o.mh.call(this,a);b&&(b.dd&&b.dd(a),a.stopPropagation())};D.x.Vu=function(a){D.qB.o.Vu.call(this,a);var b=this.ma((0,D.ua)(a));b&&b.om&&b.om(a)};D.x.Uu=function(a){D.qB.o.Uu.call(this,a);var b=this.ma((0,D.ua)(a));b&&b.wl&&b.wl(a)};D.x.$s=function(a){var b=this.ma((0,D.ua)(a));b&&(b.dd&&b.dd(a),a.stopPropagation())};D.x.qE=function(a){a.Hz();(0,D.ke)(a)};
D.ie=function(a,b,c,d,e,f,g){this.Init(a,b,c,d,e,f,g)};D.y.l(D.ie,D.y,"DvtControlPanelEventHandlerProxy");D.x=D.ie.prototype;D.x.Init=function(a,b,c,d,e,f,g){this.ja=a;this.Ft=b;this.Yea=d;this.MR=c;this.NR=e;this.OR=f;this.kf=g};D.x.dd=function(a){this.Ft&&this.Ft.call(this.ja,a)};D.x.Gp=function(a){this.MR&&this.MR.call(this.ja,a)};D.x.uo=function(a){this.Yea&&this.Yea.call(this.ja,a)};D.x.rE=function(a){this.NR&&this.NR.call(this.ja,a)};D.x.gP=function(a){this.OR&&this.OR.call(this.ja,a)};
D.x.te=(0,D.w)("kf");
D.Bt={};D.y.l(D.Bt,D.y,"DvtControlPanelLAFUtils");D.Bt.dY="top";D.Bt.cY="right";D.Bt.bY="left";D.Bt.aY="bottom";D.Bt.Yaa=47;D.Bt.Xaa=26;D.Bt.Od=window.Math.sin(window.Math.PI/4);D.Bt.Pd=window.Math.tan(window.Math.PI/8);D.Bt.bo=function(){return D.Bt.Yaa};D.Bt.nV=function(){return D.Bt.Xaa};D.Bt.$ja=function(a,b,c,d,e){b||(b=86);c||(c=47);d===D.i&&(d=D.k);e=(0,window.parseInt)((0,D.te)(e,"border-radius",0));return D.Bt.fGa(a,e,b-2*e,c-2*e,d)};
D.Bt.fGa=function(a,b,c,d,e){var f=c+b,g=d+b,h=D.P.moveTo(f+b,g+b),h=h+D.P.lineTo(f-c,g+b),f=f-c,h=h+D.P.lineTo(f-b,g+b),h=h+D.P.lineTo(f-b,g-d),g=g-d;e?(h+=D.P.hc(-b+f,-D.Bt.Pd*b+g,-D.Bt.Od*b+f,-D.Bt.Od*b+g)+D.P.hc(-D.Bt.Pd*b+f,-b+g,f,-b+g)+D.P.lineTo(f,-b+g),h+=D.P.lineTo(f+c+b,-b+g),h+=D.P.lineTo(f+c+b,g+d)):(h+=D.P.lineTo(f-b,-b+g),h+=D.P.lineTo(f+c,-b+g),f+=c,h+=D.P.hc(D.Bt.Pd*b+f,-b+g,D.Bt.Od*b+f,-D.Bt.Od*b+g)+D.P.hc(b+f,-D.Bt.Pd*b+g,b+f,g)+D.P.lineTo(f+b,g+d));h+=D.P.closePath();return new D.Tb(a,
h)};D.Bt.Zja=function(a,b,c,d){b||(b=47);var e=(0,window.parseInt)((0,D.te)(c,"border-radius",0)),f=(0,D.te)(c,"openCloseButtonWidth",0);b=window.Math.max(b,(0,D.te)(c,"buttonHeight",b));d=D.R.pX(f,b,e,d);d=d.concat("Z");a=new D.Tb(a,d,"cls_shape");(d=(0,D.te)(c,"tab-color-inactive",D.n))||(d=(0,D.te)(c,"background-color",D.n));a.qa(d);return a};
D.Bt.g5=function(a,b,c,d){b||(b=47);var e=(0,window.parseInt)((0,D.te)(c,"border-radius",0)),f=(0,D.te)(c,"openCloseButtonWidth",0);b=window.Math.max(b,(0,D.te)(c,"buttonHeight",b));d=D.R.pX(f,b,e,d);d=d.concat("Z");a=new D.Tb(a,d,"cls_shape");a.La((0,D.te)(c,"border-color",D.n));a.J(D.n);return a};
D.Bt.KGa=function(a,b,c,d,e){b||(b=137);var f=(0,window.parseInt)((0,D.te)(c,"border-radius",0)),g=(0,D.te)(c,"tabSize",0),h=g-2*f,j=b+7-2*f;a=d&&e?D.Bt.Yma(a,f,g,b,d,e):D.Bt.Xma(a,f,h,j);a.qa((0,D.te)(c,"background-color",D.n));return a};D.Bt.JGa=function(a,b,c,d,e,f){b||(b=137);c||(c=D.k);var g=(0,window.parseInt)((0,D.te)(d,"border-radius",0)),h=(0,D.te)(d,"tabSize",0),j=h-2*g,l=b+7-2*g,m=D.n,m=e&&f?D.Bt.Yma(a,g,h,b,e,f):D.Bt.Xma(a,g,j,l,c);m.La((0,D.te)(d,"border-color",D.n));m.J(D.n);return m};
D.Bt.Xma=function(a,b,c,d,e){e||(e=D.k);var f=c+b,g=d,h=D.P.moveTo(f+b,g),h=e?h+(D.P.hc(b+f,D.Bt.Pd*b+g,D.Bt.Od*b+f,D.Bt.Od*b+g)+D.P.hc(D.Bt.Pd*b+f,b+g,f,b+g)+D.P.lineTo(f,b+g)):h+D.P.lineTo(f+b,g+b),h=h+D.P.lineTo(f-c,b+g),f=f-c,h=h+(D.P.hc(-D.Bt.Pd*b+f,b+g,-D.Bt.Od*b+f,D.Bt.Od*b+g)+D.P.hc(-b+f,D.Bt.Pd*b+g,-b+f,g)+D.P.lineTo(-b+f,g)+D.P.lineTo(-b+f,g-d)),g=g-d,h=h+(D.P.lineTo(f+c+b,g)+D.P.lineTo(f+c+b,g+d)+D.P.closePath());return new D.Tb(a,h)};
D.Bt.Yma=function(a,b,c,d,e,f){b=D.Bt.b$(c,d,b,e,f);return new D.Tb(a,b)};D.Bt.Wma=function(a,b,c,d,e,f){b=D.Bt.b$(c,d,b,e,f);return new D.Tb(a,b)};
D.Bt.b$=function(a,b,c,d,e){var f,g=(0,D.C)();d==D.Bt.dY&&!g&&(f=["M",a,0,"L",a,b-c,"A",c,c,0,0,1,a-c,b,"L",0,b,"L",0,0]);d==D.Bt.dY&&g?f=["M",a,0,"L",a,b,"L",c,b,"A",c,c,0,0,1,0,b-c,"L",0,0]:d==D.Bt.cY&&!g?f=["M",a,e,"L",a,b-c,"A",c,c,0,0,1,a-c,b,"L",0,b,"L",0,0,"L",a,0]:d==D.Bt.cY&&g?f=["M",0,0,"L",a,0,"L",a,b,"L",c,b,"A",c,c,0,0,1,0,b-c,"L",0,e]:d==D.Bt.bY&&!g?f=["M",0,0,"L",a-c,0,"A",c,c,0,0,1,a,c,"L",a,b-c,"A",c,c,0,0,1,a-c,b,"L",0,b]:d==D.Bt.bY&&g?f=["M",a,b,"L",c,b,"A",c,c,0,0,1,0,b-c,"L",
0,c,"A",c,c,0,0,1,c,0,"L",a,0]:d==D.Bt.aY&&!g?f=["M",0,b,"L",0,0,"L",a-c,0,"A",c,c,0,0,1,a,c,"L",a,b-c,"A",c,c,0,0,1,a-c,b,"L",e,b]:d==D.Bt.aY&&g&&(f=["M",a,b,"L",a,0,"L",c,0,"A",c,c,0,0,0,0,c,"L",0,b-c,"A",c,c,0,0,0,c,b,"L",a-e,b]);return f};
D.Rt=function(a,b,c){this.Init(a,b,c)};(0,D.ra)("DvtPanZoomComponent",D.Rt);D.y.l(D.Rt,D.mB,"DvtPanZoomComponent");D.Rt.prototype.Init=function(a,b,c){D.Rt.o.Init.call(this,a,b,c);this.WQ="initCollapsed";this.Ll=16777215;this.yf=!(0,D.Vb)()&&!((0,D.Wg)()&&17>=(0,D.nA)());this.h4=this.s3=D.n;this.Kb=""};D.Rt.prototype.GDa=(0,D.w)("ba");D.Rt.prototype.getPanZoomCanvas=D.Rt.prototype.GDa;D.qe=function(a){a.s3||(a.s3=a.M?a.M._resources:{});return a.s3};
D.Rt.prototype.jc=function(){this.af||(this.af=new D.va);return this.af};D.Rt.prototype.ts=(0,D.w)("h4");
D.Jd=function(a,b){var c=(new D.B(b.inlineStyle)).v("background-color");c&&(a.E0=c);var c={},d=b.skin;d&&(a.Kb=d,c.skin=d);(0,D.nB)(c,"background-color",b.cpBackgroundColor);(0,D.nB)(c,"border-color",b.cpBorderColor);(0,D.nB)(c,"border-radius",b.cpBorderRadius);(0,D.nB)(c,"box-shadow",b.cpBoxShadow);(0,D.nB)(c,"tab-color-inactive",b.tabBgColorInactive);(0,D.nB)(c,"tab-border-color-inactive",b.tabBorderColorInactive);(0,D.nB)(c,"scrollbarBackground",b.scrollbarBg);(0,D.nB)(c,"scrollbarBorderColor",
b.scrollbarBorderColor);(0,D.nB)(c,"scrollbarHandleColor",b.scrollbarHandleColor);(0,D.nB)(c,"scrollbarHandleActiveColor",b.scrollbarHandleActiveColor);(0,D.nB)(c,"scrollbarHandleHoverColor",b.scrollbarHandleHoverColor);c=D.oB.ah(c);a.h4=c};
D.xv=function(a,b){var c=(new D.B(b.q("inlineStyle"))).v("background-color");c&&(a.E0=c);var c={},d=b.q("skin");d&&(a.Kb=d,c.skin=d);(0,D.nB)(c,"background-color",b.q("cpBackgroundColor"));(0,D.nB)(c,"border-color",b.q("cpBorderColor"));(0,D.nB)(c,"border-radius",b.q("cpBorderRadius"));(0,D.nB)(c,"box-shadow",b.q("cpBoxShadow"));(0,D.nB)(c,"tab-color-inactive",b.q("tabBgColorInactive"));(0,D.nB)(c,"tab-border-color-inactive",b.q("tabBorderColorInactive"));(0,D.nB)(c,"scrollbarBackground",b.q("scrollbarBg"));
(0,D.nB)(c,"scrollbarBorderColor",b.q("scrollbarBorderColor"));(0,D.nB)(c,"scrollbarHandleColor",b.q("scrollbarHandleColor"));(0,D.nB)(c,"scrollbarHandleActiveColor",b.q("scrollbarHandleActiveColor"));(0,D.nB)(c,"scrollbarHandleHoverColor",b.q("scrollbarHandleHoverColor"));c=D.oB.ah(c);a.h4=c};
D.Rt.prototype.L=function(a,b,c){this.T=b;this.Y=c;this.Qy=!a;this.pJ();if(!this.Qy)if("object"==typeof a)this.ge(a);else if(!(a==D.n||0==a.length)){var d=new D.td;if(d&&(d=d.parse(a)))"r"===d.getName()&&(d=d.getFirstChild()),d&&this.oE().Fma(d)}this.Fi(a,b,c)};D.Rt.prototype.render=D.Rt.prototype.L;D.x=D.Rt.prototype;D.x.WO=function(){var a=this.Ex();return"hidden"!=a?new D.me(this.e,this,"initCollapsed"==a?1:2):D.n};D.x.Ex=(0,D.w)("WQ");D.x.oE=(0,D.ca)(D.n);D.x.Us=(0,D.s)();D.x.Rg=(0,D.s)();
D.x.pJ=(0,D.s)();
D.x.Fi=function(){if(this.E0||!this.Kb)this.mt||(this.mt=new D.D(this.e,0,0,0,0),this.k(this.mt)),this.mt.ha(this.T),this.mt.xa(this.Y),this.mt.J((0,D.pB)(this,this.E0));if(this.Qy)this.ba.dj(this.T,this.Y);else{this.ba&&(this.removeChild(this.ba),this.ba=D.n);this.ba=new D.UA(this.e,this.T,this.Y,this);this.ba.U("dvtPan",this.Us,D.p,this);this.ba.U("dvtZoom",this.Rg,D.p,this);this.k(this.ba);var a=this.WO();a&&(a.U("dvtPZCPExpand",this.Bwa,D.p,this),this.ba.Ic=a);this.ba.jn()}a=new D.Vf("comp");
(0,D.Wf)(a,this.N(),this.K(),this.T,this.Y);(0,D.Xf)(this,a)};D.x.ge=function(a){this.M=this.vf?this.vf.ah(a):a};D.x.za=(0,D.w)("M");
D.pB=function(a,b){var c,d=1;if(b&&"#7396C8"!=b){d=D.O.Z(b);c=(D.O.yd("#AECDEA")-D.O.yd("#7396C8"))/(255-D.O.yd("#7396C8"));var e=(D.O.xd("#AECDEA")-D.O.xd("#7396C8"))/(255-D.O.xd("#7396C8")),f=(D.O.wd("#AECDEA")-D.O.wd("#7396C8"))/(255-D.O.wd("#7396C8")),g=D.O.yd(b),h=D.O.xd(b),j=D.O.wd(b);c=D.O.mx(window.Math.round(g+c*(255-g)),window.Math.round(h+e*(255-h)),window.Math.round(j+f*(255-j)));e=D.O.Ti(b);c=["#FFFFFF","#FFFFFF",c,e]}else c=["#FFFFFF","#FFFFFF","#AECDEA","#7396C8"];var d=[d,d,d,d],e=
[0,45/255,190/255,1],h=a.T,f=1.7*1.7*h,g=1.7*a.Y,h=0+(h-f)/2,j=h+f/2,l=-35+g/2,m=1.5*window.Math.min(f/2,g/2);return new D.Pk(c,d,e,j,l,m,[h,-35,f,g])};D.Rt.prototype.Bwa=function(a){var b=new D.sf;(0,D.Lc)(b,"controlPanelBehavior","show"==a.Wi()?"initExpanded":"initCollapsed");this.Wa(b)};
D.UA=function(a,b,c,d){this.Init(a,b,c,d)};D.y.l(D.UA,D.I,"DvtPanZoomCanvas");
D.UA.prototype.Init=function(a,b,c,d){D.UA.o.Init.call(this,a);this.I=d;this.Lg=b;this.Wg=c;this.Pt=this.Ot=this.uz=this.xG=0;this.oq=this.qq=this.nq=this.pq=D.n;this.Ql=0.1;this.Jm=1;this.ZS=15;this.SM=0.05;this.FIa=D.p;this.jp=20;this.Ic=D.n;this.yca=this.Sp=this.ji=D.k;this.mt=new D.D(this.e,0,0,this.Lg,this.Wg);this.k(this.mt);(0,D.La)(this.mt);this.X=new D.I(this.e);this.k(this.X);this.X.sa(new D.jd);this.ht=0.5;this.ta=new D.VA(a,this.Tb,this);this.ta.Df(this);this.RIa=1;(0,D.WA)(this,b,c);
this.eB=D.p;this.Ko=D.n};D.UA.prototype.dj=function(a,b,c){this.Lg=a;this.Wg=b;c||(this.mt.ha(a),this.mt.xa(b),this.Ic&&(0,D.XA)(this),(0,D.WA)(this,a,b))};D.UA.prototype.yc=function(){return new D.pi(this.Lg,this.Wg)};D.WA=function(a,b,c){var d=new D.Vf("pzc");(0,D.Wf)(d,a.N(),a.K(),b,c);(0,D.Xf)(a,d)};D.Nq=function(a){return a.X};D.ss=function(a,b){if(b){var c=(0,D.pq)(b,a.X,a.X.na);if(c)return c}return a.X.na()};D.UA.prototype.Fc=function(a){return(0,D.ss)(this,a).Qd};
(0,D.ra)("DvtPanZoomCanvas.prototype.getZoom",D.UA.prototype.Fc);
D.UA.prototype.Dk=function(a,b,c){if(this.ji){var d=(0,D.ss)(this,c).Bb,e=(0,D.ss)(this,c).xb,f=(0,D.YA)(this,d+a),g=(0,D.bB)(this,e+b);b=f-d;var h=g-e;a=D.n;c&&(a=(0,D.pq)(c,this.X,this.X.na))&&(a=a.clone());a||(a=this.X.na().clone());a.translate(b,h);var j=this;b=function(){var a=new D.cB("panning",f,g,d,e,c);j.Tb(a)};h=function(){var a=new D.cB("panned",f,g,d,e,c);j.Tb(a)};c?((0,D.T)(c,"typeMatrix",this.X,this.X.na,this.X.sa,a),(0,D.dB)(c,b),(0,D.Kf)(c,h)):(b(),this.X.sa(a),h())}};
D.wu=function(a,b,c,d){a.ji&&(b-=(0,D.ss)(a,d).Bb,c-=(0,D.ss)(a,d).xb,a.Dk(b,c,d))};
D.UA.prototype.bE=function(a,b,c,d){if(this.Sp){!b&&0!==b&&(b=this.Lg/2);!c&&0!==c&&(c=this.Wg/2);var e=this.Fc(d),f=(0,D.Ts)(this,e*a);this.Ic&&(a=this.Fc(),f==this.Ql&&f==this.Jm?((0,D.eB)(this.Ic,D.p),(0,D.fB)(this.Ic,D.p)):a<=f&&f==this.Jm?((0,D.eB)(this.Ic,D.p),(0,D.fB)(this.Ic,D.k)):a>=f&&f==this.Ql?((0,D.eB)(this.Ic,D.k),(0,D.fB)(this.Ic,D.p)):((0,D.eB)(this.Ic,D.k),(0,D.fB)(this.Ic,D.k)));if(window.Math.round(1E5*e)!=window.Math.round(1E5*f)){var g=f/e;a=D.n;d&&(a=(0,D.pq)(d,this.X,this.X.na))&&
(a=a.clone());a||(a=this.X.na().clone());a.scale(g,g,b,c);var h=(0,D.YA)(this,a.Bb)-a.Bb,j=(0,D.bB)(this,a.xb)-a.xb;(0,D.Ss)(this,"adjustPanConstraints",f,e,d,D.n,b,c,h,j);h=(0,D.YA)(this,a.Bb)-a.Bb;j=(0,D.bB)(this,a.xb)-a.xb;a.translate(h,j);var l=this,g=function(){(0,D.Ss)(l,"zooming",f,e,d,D.n,b,c,h,j)},m=function(){(0,D.Ss)(l,"zoomed",l.Fc(),e,d,D.n,b,c,h,j)};d?((0,D.T)(d,"typeMatrix",this.X,this.X.na,this.X.sa,a),(0,D.dB)(d,g),(0,D.Kf)(d,m)):(g(),this.X.sa(a),m())}}};
D.ds=function(a,b,c,d,e){a.Sp&&(b/=a.Fc(e),a.bE(b,c,d,e))};D.UA.prototype.Pja=function(a,b){var c=this.ji;this.ji=D.k;var d=b;d||(d=this.X.C());var e=(d.x+d.g/2)*this.Fc(),d=(d.y+d.j/2)*this.Fc();(0,D.wu)(this,this.Lg/2-e,this.Wg/2-d,a);this.ji=c};
D.UA.prototype.oo=function(a,b){if(this.yca){var c=this.ji,d=this.Sp;this.Sp=this.ji=D.k;try{var e=b?b:this.X.C();if(e=(0,D.Ss)(this,"zoomToFitCalcBounds",D.n,D.n,a,e).mH){var f=window.Math.min((this.Lg-2*this.jp)/e.g,(this.Wg-2*this.jp)/e.j),f=(0,D.Ts)(this,f),g=this.Lg/2-(e.x+e.g/2)*f,h=this.Wg/2-(e.y+e.j/2)*f,j=this,l=function(){(0,D.Ss)(j,"zoomToFitBegin",D.n,D.n,a,e)},m=function(){(0,D.Ss)(j,"zoomToFitEnd",D.n,D.n,a,e)};a?(0,D.dB)(a,l):l();(0,D.ds)(this,f,0,0,a);(0,D.wu)(this,g,h,a);a?(0,D.Kf)(a,
m):m()}}finally{this.ji=c,this.Sp=d}}};D.UA.prototype.Wz=function(){var a=(0,D.Lb)(this,new D.L(0,0)),b=(0,D.Lb)(this,new D.L(this.Lg,this.Wg)),a=this.X.Fb(a),b=this.X.Fb(b);return new D.N(a.x,a.y,b.x-a.x,b.y-a.y)};
D.hB=function(a,b){if(a.eB=b)a.Ko&&(a.Ko.eh()&&a.Ko.stop(),a.Ko=D.n);else{var c=(0,D.ss)(a,D.i).Bb,d=(0,D.ss)(a,D.i).xb,e=a.Fc();a.eQ=c!=(0,D.YA)(a,c)||d!=(0,D.bB)(a,d);a.fQ=e!=(0,D.Ts)(a,e);if(a.eQ||a.fQ)a.Ko=new D.fm(a.e,0.4),a.Ko.Sj(D.gB),a.fQ&&a.bE(1,0.5*a.Lg,0.5*a.Wg,a.Ko),a.eQ&&a.Dk(0,0,a.Ko),(0,D.Kf)(a.Ko,a.Dva,a),a.eQ&&(c=new D.cB("elasticAnimBegin",D.n,D.n,D.n,D.n,a.Ko),a.Tb(c)),a.fQ&&(0,D.Ss)(a,"elasticAnimBegin",D.n,D.n,D.n,D.n,a.Ko),a.Ko.play()}};
D.UA.prototype.Dva=function(){this.Ko=D.n;if(this.eQ){var a=new D.cB("elasticAnimEnd",D.i,D.i,D.i,D.i,D.i);this.Tb(a)}this.fQ&&(0,D.Ss)(this,"elasticAnimEnd")};D.YA=function(a,b){var c=b;a.pq!=D.n&&c<a.pq&&(a.eB?(c=a.pq-c,c=a.pq-window.Math.sqrt(4*(0.01*a.Lg)*c)):c=a.pq);a.nq!=D.n&&c>a.nq&&(a.eB?(c-=a.nq,c=a.nq+window.Math.sqrt(4*(0.01*a.Lg)*c)):c=a.nq);return c};
D.bB=function(a,b){var c=b;a.qq!=D.n&&c<a.qq&&(a.eB?(c=a.qq-c,c=a.qq-window.Math.sqrt(4*(0.01*a.Wg)*c)):c=a.qq);a.oq!=D.n&&c>a.oq&&(a.eB?(c-=a.oq,c=a.oq+window.Math.sqrt(4*(0.01*a.Wg)*c)):c=a.oq);return c};D.Ts=function(a,b){var c=window.Math.max(0,b);a.Ql&&c<a.Ql&&(a.eB?(c=a.Ql-c,c=a.Ql-window.Math.sqrt(4*(0.002*(a.Jm-a.Ql))*c)):c=a.Ql);a.Jm&&c>a.Jm&&(a.eB?(c-=a.Jm,c=a.Jm+window.Math.sqrt(4*(0.002*(a.Jm-a.Ql))*c)):c=a.Jm);return c};
D.UA.prototype.jn=function(){var a=this.Ic;a&&(this.k(a),(0,D.XA)(this),a.jn())};D.XA=function(a){var b=a.I.ts(),c=(0,D.te)(b,"paddingSide",0),d=(0,D.te)(b,"paddingTop",0),b=(0,D.te)(b,"openCloseButtonWidth",0),c=(0,D.C)(a.e)?a.Lg-b-c:c;(0,D.G)(a.Ic,c,d)};D.iB=function(a,b){return(0,D.gc)(a.e,b.pageX,b.pageY)};D.Ss=function(a,b,c,d,e,f,g,h,j,l){b=new D.jB(b,c,d,e,f,new D.L(g,h),j,l);a.Tb(b);return b};D.UA.prototype.zW=function(){(0,D.Ss)(this,"zoomAndCenter")};
D.kB=function(a,b){var c;c=b+a.SM;c>a.Jm&&(c=a.Jm);return c};D.lB=function(a,b){var c;c=b-a.SM;c<a.Ql&&(c=a.Ql);return c};D.UA.prototype.Is=(0,D.v)("Ql");D.UA.prototype.Lu=function(a){0>a&&(a=1);this.Jm=a};D.UA.prototype.Ds=(0,D.v)("ht");D.UA.prototype.Qa=(0,D.w)("ht");
D.VA=function(a,b,c){this.Init(a,b,c)};D.y.l(D.VA,D.ta,"DvtPanZoomCanvasEventManager");D.x=D.VA.prototype;D.x.Init=function(a,b,c){D.VA.o.Init.call(this,a,b,c);this.Rb=c;this.ls=D.n;this.zr=this.$E=D.p;this.oQ=D.k};D.x.Df=function(a){D.VA.o.Df.call(this,a);(0,D.Wg)()?a.U("DOMMouseScroll",this.JA,D.p,this):a.U(D.hl,this.JA,D.p,this)};
D.x.xl=function(a){2!=a.button&&(a=(0,D.iB)(this.ja,a),this.Ot=a.x,this.Pt=a.y,this.xG=this.Ot,this.uz=this.Pt,this.UZ=D.k,this.RS=(0,D.ss)(this.ja,D.i).Bb,this.SS=(0,D.ss)(this.ja,D.i).xb,this.TS=this.ja.Fc(),this.oQ&&(this.cR=(new window.Date).getTime()));this.rj&&this.rj.eh()&&(this.rj.stop(),this.rj.reset())};
D.x.Lp=function(a){if(this.UZ){var b=(0,D.iB)(this.ja,a),c=b.x,b=b.y;a.ctrlKey?(this.zr||(this.fb.call(this.ja,new D.jB("dragZoomBegin")),this.zr=D.k,this.Rb.Ic&&(0,D.rB)(this.Rb.Ic),(0,D.hB)(this.ja,D.k)),a=this.TS*window.Math.pow(1+0.01*(this.uz>=b?1:-1),window.Math.abs(this.uz-b)),this.ja.ji?(0,D.ds)(this.ja,a,this.xG,this.uz):(0,D.ds)(this.ja,a,D.n,D.n)):(0,D.sB)(this,c,b);this.Ot=c;this.Pt=b}};D.x.un=function(){this.UZ=D.p;this.$E&&(0,D.tB)(this);this.zr&&(0,D.uB)(this)};
D.x.fj=function(a){if(this.UZ&&(this.$E||this.zr))(!a.relatedTarget||a.relatedTarget==D.n)&&this.un(a);D.VA.o.fj.call(this,a)};
D.x.JA=function(a){if(a.wheelDelta&&0!==a.wheelDelta&&this.ja.Sp){var b=this.ja.Fc();this.ls&&(b=this.ls,this.ls.stop(),b=this.ja.Fc(b),this.ls=D.n);this.ls=D.n;var c=a.wheelDelta;(0,D.Wg)()&&(c=-c);b*=1+this.ja.SM*c/window.Math.abs(c);c=(0,D.iB)(this.ja,a);this.e.Nz().WAa(a);this.ja.ji?(0,D.ds)(this.ja,b,c.x,c.y,this.ls):(0,D.ds)(this.ja,b,D.n,D.n,this.ls);this.ls&&((0,D.Kf)(this.ls,this.Fua,this),this.ls.play())}};D.x.Fua=function(){this.ls=D.n};D.x.Gwa=(0,D.s)();
D.x.Hwa=function(){var a=1-0.04*this.p2,a=a*a,b=this.rj.RU(),c=a*this.Qxa*b,a=a*this.Rxa*b;this.n2+=c;this.o2+=a;var b=this.RS+this.Ot-this.xG+this.n2,d=this.SS+this.Pt-this.uz+this.o2;(0,D.wu)(this.ja,b,d);var e=D.p;if(24<=this.p2)e=D.k;else{var f=(0,D.ss)(this.ja,D.i).Bb,g=(0,D.ss)(this.ja,D.i).xb;if(window.Math.abs(f-b)>window.Math.abs(c)||window.Math.abs(g-d)>window.Math.abs(a))e=D.k}e?(this.rj.stop(),this.rj.reset(),(0,D.hB)(this.ja,D.p)):this.p2++};
D.x.qE=function(a){this.ja.Sp&&(0,D.oc)(a,this.bra,this);this.ja.ji&&(0,D.oc)(a,this.vqa,this)};D.x.dP=function(a){this.ja.Sp&&(0,D.pc)(this.Qb,a,"zoomTouch");this.ja.ji&&(0,D.pc)(this.Qb,a,"panTouch");a&&a.preventDefault()};D.x.cP=function(a){this.ja.Sp&&(0,D.qc)(this.Qb,a,"zoomTouch");this.ja.ji&&(0,D.qc)(this.Qb,a,"panTouch")};
D.x.bra=function(a,b){var c=(0,D.rc)(this.Qb,"zoomTouch");1>=c.length&&((0,D.sc)(this.Qb,b.identifier,"zoomTouch","zoomTouch","zoomTouch",this.ara,this.$qa,this),this.Ot=b.pageX,this.Pt=b.pageY,this.xG=this.Ot,this.uz=this.Pt,this.RS=(0,D.ss)(this.ja,D.i).Bb,this.SS=(0,D.ss)(this.ja,D.i).xb,this.TS=this.ja.Fc(),this.QS=D.n,c=(0,D.rc)(this.Qb,"zoomTouch"),c=(0,D.vB)(this.Qb,c),this.ja.a0=c);this.rj&&this.rj.eh()&&(this.rj.stop(),this.rj.reset())};
D.x.ara=function(){var a=(0,D.rc)(this.Qb,"zoomTouch");if(2==a.length){var b;var c=this.Qb;if(2==a.length)if(b=c.Bh[a[0]],c=c.Bh[a[1]],b==D.n||c==D.n||0==b.rka&&0==c.ska)b=D.n;else{var d=b.pageX-c.pageX,e=b.pageY-c.pageY,d=window.Math.sqrt(d*d+e*e),e=b.L7-c.L7,f=b.M7-c.M7,g=(b.pageX+c.pageX)/2,h=(b.pageY+c.pageY)/2;b={PBa:d-window.Math.sqrt(e*e+f*f),rU:g,xH:h,xBa:g-(b.L7+c.L7)/2,yBa:h-(b.M7+c.M7)/2,pka:d}}else b=D.n;b&&(this.zr||(this.zr=D.k,this.Qb.Hz(),this.fb.call(this.ja,new D.jB("dragZoomBegin")),
this.Rb.Ic&&(0,D.rB)(this.Rb.Ic)),(0,D.hB)(this.ja,D.k),this.QS==D.n&&(this.QS=b.pka-b.PBa),c=this.TS*(b.pka/this.QS),d=(0,D.gc)(this.Rb.e,b.rU,b.xH),this.zc(),a=(0,D.vB)(this.Qb,a),this.ja.a0=a,(0,D.ds)(this.ja,c,d.x,d.y),this.ja.Dk(b.xBa,b.yBa))}};D.x.$qa=function(){this.zr&&(this.QS=D.n,this.Qb.l_=D.p,(0,D.uB)(this));var a=(0,D.rc)(this.Qb,"zoomTouch"),b=(0,D.vB)(this.Qb,a);this.ja.a0=b;0==a.length&&this.fb.call(this.ja,new D.jB("zoomEnd"))};
D.x.vqa=function(a,b){!this.zr&&1>=(0,D.rc)(this.Qb,"panTouch").length&&((0,D.sc)(this.Qb,b.identifier,"panTouch","panTouch","panTouch",this.uqa,this.tqa,this),this.Ot=b.pageX,this.Pt=b.pageY,this.xG=this.Ot,this.uz=this.Pt,this.RS=(0,D.ss)(this.ja,D.i).Bb,this.SS=(0,D.ss)(this.ja,D.i).xb,this.TS=this.ja.Fc(),this.oQ&&(this.cR=(new window.Date).getTime()));this.rj&&this.rj.eh()&&(this.rj.stop(),this.rj.reset())};
D.x.uqa=function(a,b){if(!this.zr&&1==(0,D.rc)(this.Qb,"panTouch").length){var c=b.pageX,d=b.pageY;(0,D.sB)(this,c,d);this.Ot=c;this.Pt=d}};D.x.tqa=function(){!this.zr&&this.$E&&(0,D.tB)(this)};D.uB=function(a){a.fb.call(a.ja,new D.jB("dragZoomEnd"));a.zr=D.p;a.Rb.Ic&&(0,D.wB)(a.Rb.Ic);(0,D.hB)(a.ja,D.p)};
D.sB=function(a,b,c){a.$E||(a.fb.call(a.ja,new D.cB("dragPanBegin")),a.$E=D.k,a.Rb.Ic&&(0,D.rB)(a.Rb.Ic),(0,D.hB)(a.ja,D.k),a.oQ&&(a.$A=[]));(0,D.wu)(a.ja,a.RS+b-a.xG,a.SS+c-a.uz);a.oQ&&(a.qxa=a.cR,a.cR=(new window.Date).getTime(),a.bw?(a.bw.eh()&&a.bw.stop(),a.bw.reset()):a.bw=new D.sm(a.e,50,a.Gwa,a,1),a.$A.push({HBa:a.cR-a.qxa,rka:b-a.Ot,ska:c-a.Pt}),5<a.$A.length&&a.$A.splice(0,1),a.bw.start())};
D.tB=function(a){a.fb.call(a.ja,new D.cB("dragPanEnd"));a.$E=D.p;a.Rb.Ic&&(0,D.wB)(a.Rb.Ic);if(a.bw&&a.bw.eh()){a.bw.stop();a.bw.reset();a.rj?a.rj.reset():a.rj=new D.sm(a.e,50,a.Hwa,a);for(var b=0,c=0,d=0,e=a.$A.length;0<a.$A.length;)var f=a.$A.pop(),b=b+f.HBa,c=c+f.rka,d=d+f.ska;a.$A=D.n;a.Qxa=c/b;a.Rxa=d/b;a.rj.setInterval(window.Math.ceil(b/e));a.p2=1;a.n2=0;a.o2=0;a.Rb.ji&&a.rj.start()}else(0,D.hB)(a.ja,D.p)};
D.Yd=function(a,b){this.Init(a,b)};D.y.l(D.Yd,D.gf,"DvtPanZoomCanvasKeyboardHandler");D.Yd.prototype.Init=function(a,b){D.Yd.o.Init(b);this.Nua=a};
D.Yd.prototype.lo=function(a){var b=a.keyCode,c=this.Nua.ba;if(33==b)a.ctrlKey||a.shiftKey?c.Dk(c.ZS,0):c.Dk(0,c.ZS);else if(34==b)a.ctrlKey||a.shiftKey?c.Dk(-c.ZS,0):c.Dk(0,-c.ZS);else if(191==b)(a=c.Ic)&&a.zO();else if((0,D.Tk)(a)||(0,D.mc)(a))(0,D.ds)(c,c.Fc()+c.SM);else if((0,D.nc)(a)||(0,D.Uk)(a))(0,D.ds)(c,c.Fc()-c.SM);else if((48==b||96==b)&&!a.ctrlKey&&!a.shiftKey)c.oo();else return D.Yd.o.lo.call(this,a)};
D.Qc=function(a,b,c,d,e,f,g,h){this.Init(a,b,c,d,e,f,g,h)};D.y.l(D.Qc,D.I,"DvtCollapsiblePanel");
D.Qc.prototype.Init=function(a,b,c,d,e,f,g,h){D.Qc.o.Init.call(this,a);this.Hg=b;this.Cc=c;this.Li=d?d:"col_northeast";(0,D.C)(this.e)&&("col_northeast"==this.Li?this.Li="col_northwest":"col_northwest"==this.Li?this.Li="col_northeast":"col_southeast"==this.Li?this.Li="col_southwest":"col_southwest"==this.Li&&(this.Li="col_southeast"));this.Il=e;this.Tv=h?h:(0,D.Dy)();this.yb=this.qB=this.EB=D.n;this.D=f;this.Tp=(0,D.te)(this.D,"border-color",D.n);this.Nh=(0,window.parseInt)((0,D.te)(this.D,"border-radius",
D.n));this.pv=(0,D.te)(this.D,"background-color",D.n);this.ek=(0,D.te)(this.D,"backgroundAlpha",1);this.IQ=g!==D.i?!g:D.p;this.ad=new D.Jf(a,0,0,b-10,c-10,3,"collapsiblePanel");this.k(this.ad);this.ad.ZK=D.p;(0,D.G)(this.ad,5,5);this.U(D.Yq,this.gP,D.p,this);this.U(D.Zq,this.rE,D.p,this)};
D.Qc.prototype.IX=function(){this.ad.refresh();var a=this.ad.C(),b=a.g+10,a=a.j+10;this.$a.Ek((0,D.cC)(this,b,a));var c="col_northwest"==this.Li||"col_southwest"==this.Li;this.Ag&&c&&this.Ag.F(b);this.Tb(new D.vt(b,a,0,0))};D.Qc.prototype.isCollapsed=(0,D.w)("IQ");D.Rc=function(a,b){a.IQ!=b&&(a.IQ=b,(0,D.dC)(a,D.k),a.Tb(new D.wL(b?"hide":"show")))};D.Qc.prototype.l6=function(){return this.Hg-27};D.Qc.prototype.k6=function(){return this.Cc-27};
D.xL=function(a,b,c){return!a.isCollapsed()?c?new D.L(1/b.x,1/b.y):new D.L(-b.x,-b.y):b};
D.dC=function(a,b){a.yb&&(a.KZ=D.k,a.yb.stop(D.k));var c="col_northwest"==a.Li||"col_northeast"==a.Li,d="col_northwest"==a.Li||"col_southwest"==a.Li,e=d?0:a.T,f=c?0:a.Y,g=new D.L(1/a.T,1/a.Y),e=new D.L(e,f),c=new D.L(d?-a.T:a.T,f-(c?0:25));b||(a.$a.B(0),a.Ag&&a.Ag.B(0));g=new D.tj(a.e,a.$a,(0,D.xL)(a,g,D.k),b?0.25:1E-5);c=new D.uj(a.e,a.Ag,(0,D.xL)(a,c),b?0.25:1E-5);e=new D.uj(a.e,a.$a,(0,D.xL)(a,e),b?0.25:1E-5);a.yb=new D.rj(a.e,g,c,e);a.yb&&(a.e.Vd().zc(),a.Ra(D.Yq,a.gP,D.p,a),a.Ra(D.Zq,a.rE,D.p,
a),a.gk&&(a.gk.Ra(D.Wv.Ce,a.vE,D.p,a),a.gk.Ra(D.Cb,a.vE,D.p,a),a.gk.Ra(D.Yq,a.gY,D.p,a),a.gk.Ra(D.Zq,a.fY,D.p,a)),a.isCollapsed()&&a.ad.B(0),a.yb.Md(a.Kp,a),a.yb.play())};
D.cC=function(a,b,c){var d=a.Nh,e,f="col_northwest"==a.Li||"col_southwest"==a.Li;25>=c&&(c=25);e=a.Tv||f?D.P.moveTo(d,0):D.P.moveTo(0,0);e+=D.P.lineTo(b-d,0);!a.Tv&&f?(e+=D.P.lineTo(b,0),e+=D.P.lineTo(b,d)):e+=D.P.hc(b,0,b,d);!a.Tv&&25==c&&f?e+=D.P.lineTo(b,c):(e+=D.P.lineTo(b,c-d),e+=D.P.hc(b,c,b-d,c));e+=D.P.lineTo(d,c);e=!a.Tv&&25==c&&!f?e+D.P.lineTo(0,c):e+D.P.hc(0,c,0,c-d);if(a.Tv||f)e+=D.P.lineTo(0,d),e+=D.P.hc(0,0,d,0);return e+=D.P.closePath()};D.x=D.Qc.prototype;
D.x.Kp=function(){this.KZ=D.p;this.yb=D.n;var a=this.$a.rc().clone();a.B(this.D.borderAlpha);this.$a.W(a);var a=this.D[D.me.CHa],b=this.$a.Ec().clone();b.B(a);this.$a.J(b);this.Ag&&this.Ag.B(this.D.borderAlpha);this.isCollapsed()||this.ad.B(1);this.U(D.Yq,this.gP,D.p,this);this.U(D.Zq,this.rE,D.p,this);this.gk&&(this.gk=this.isCollapsed()?D.R.pU(this.e,this.Il,25,this.D,D.p):D.R.nU(this.e,this.Il,25,this.D,D.p),this.Ag.k(this.gk),this.Ag.up(0),(0,D.Qa)()?this.gk.U(D.Wv.Ce,this.vE,D.p,this):(this.gk.U(D.Cb,
this.vE,D.p,this),this.gk.U(D.Yq,this.gY,D.p,this),this.gk.U(D.Zq,this.fY,D.p,this)))};D.x.vE=function(){this.e.Vd().zc();(0,D.Rc)(this,!this.isCollapsed())};D.x.gY=function(a){var b=this.isCollapsed()?this.EB:this.qB;b!=D.n&&this.e.Vd().xO(a.pageX,a.pageY,b,this.gk,D.k)};D.x.fY=function(){this.e.Vd().zc()};D.x.gP=function(){var a=this.$a.rc().clone();a.B(this.D.borderHoverAlpha);this.$a.W(a);var a=this.D.backgroundHoverAlpha,b=this.$a.Ec().clone();b.B(a);this.$a.J(b);this.Ag&&this.Ag.B(this.D.borderHoverAlpha)};
D.x.rE=function(){var a=this.$a.rc().clone();a.B(this.D.borderAlpha);this.$a.W(a);a=this.$a.Ec().clone();a.B(this.ek);this.$a.J(a);this.Ag&&this.Ag.B(this.D.borderAlpha)};
D.wL=function(a){this.Init("dvtCollapsiblePanelEvent");this.Xl=a};D.y.l(D.wL,D.tb,"DvtCollapsiblePanelEvent");D.wL.prototype.Wi=(0,D.w)("Xl");
D.Ex={};D.y.l(D.Ex,D.y,"DvtImageLAFUtils");D.Ex.eI=function(a,b){var c=new D.Xa(a,b);c.ia(D.p);D.Gd.Pj(a,b,function(a){a!=D.n&&(a.width&&a.height)&&(c.ha(a.width),c.xa(a.height))});return c};
D.R={};D.y.l(D.R,D.y,"DvtButtonLAFUtils");D.R.FHa=-6;D.R.g9=23;D.R.f9=21;D.R.bIa=20;D.R.SHa=22;D.R.RHa=20;D.R.Yaa=47;D.R.Xaa=26;D.R.Od=window.Math.sin(window.Math.PI/4);D.R.Pd=window.Math.tan(window.Math.PI/8);D.R.FO="#7C8191";D.R.Q9="#E0E1E1";D.R.R9="#F0F1F2";D.R.yY=8;D.R.Hoa="solid";D.R.Eoa="#7BA0D9";D.R.cX="#3474D3";D.R.q9="#BFD8FB";D.R.Tsa="zoominUp";D.R.Usa="zoominOver";D.R.Ssa="zoominDown";D.R.Rsa="zoominDisabled";D.R.$sa="zoomtofitUp";D.R.ata="zoomtofitOver";D.R.Zsa="zoomtofitDown";
D.R.Xsa="zoomoutUp";D.R.Ysa="zoomoutOver";D.R.Wsa="zoomoutDown";D.R.Vsa="zoomoutDisabled";D.R.nsa="pandialUp";D.R.osa="pandialOver";D.R.msa="pandialDown";D.R.vsa="recenterUp";D.R.wsa="recenterOver";D.R.usa="recenterDown";D.R.Dba="resetUp";D.R.ysa="resetOver";D.R.xsa="resetDown";D.R.qba="drillupUp";D.R.Kra="drillupOver";D.R.Jra="drillupDown";D.R.pba="drilldownUp";D.R.Ira="drilldownOver";D.R.Hra="drilldownDown";D.R.jIa="maxUp";D.R.kIa="maxOver";D.R.iIa="maxDown";D.R.mIa="restoreUp";D.R.nIa="restoreOver";
D.R.lIa="restoreDown";D.R.tra="collapseEna";D.R.ura="collapseOvr";D.R.sra="collapseDwn";D.R.Nra="expandEna";D.R.Ora="expandOvr";D.R.Mra="expandDwn";D.R.qsa="quickQueryEna";D.R.rsa="quickQueryOvr";D.R.psa="quickQueryDwn";D.R.qra="clearResultsEna";D.R.rra="clearResultsOvr";D.R.pra="clearResultsDwn";D.R.Psa="Up";D.R.lsa="Over";D.R.Gra="Down";D.R.Asa="Sel";D.R.ssa="_r";D.R.Ksa="synchronize";
D.R.jBa=function(a,b,c,d,e,f){var g=D.R.X_(a,e[D.R.nsa],f),h=new D.I(a);(0,D.G)(h,20,20);var j=D.R.X_(a,e[D.R.msa],f);(0,D.G)(j,-20,-20);h.k(j);j=new D.I(a);(0,D.G)(j,20,20);var l=D.R.X_(a,e[D.R.osa],f);(0,D.G)(l,-20,-20);j.k(l);g=new D.Na(a,g,j,h);if(0<(d&16)){var m=new D.Na(a,D.R.Y_(a,e[D.R.vsa],f),D.R.Y_(a,e[D.R.wsa],f),D.R.Y_(a,e[D.R.usa],f));(0,D.G)(m,9,9)}return new D.YK(a,g,m,b,c,d,f)};
D.R.eBa=function(a,b,c,d,e,f,g){var h=D.R.Bg(a,0,e[D.R.qba],g),j=D.R.Bg(a,1,e[D.R.Kra],g),l=D.R.Bg(a,2,e[D.R.Jra],g);e=D.R.Bg(a,0,e[D.R.qba],g);return new D.fe(a,new D.Na(a,h,j,l,e),b,c,0,d,f)};D.R.dBa=function(a,b,c,d,e,f,g){var h=D.R.Bg(a,0,e[D.R.pba],g),j=D.R.Bg(a,1,e[D.R.Ira],g),l=D.R.Bg(a,2,e[D.R.Hra],g);e=D.R.Bg(a,0,e[D.R.pba],g);return new D.fe(a,new D.Na(a,h,j,l,e),b,c,1,d,f)};
D.R.pBa=function(a,b,c,d,e,f,g){var h=D.R.Bg(a,0,e[D.R.Dba],g),j=D.R.Bg(a,1,e[D.R.ysa],g),l=D.R.Bg(a,2,e[D.R.xsa],g);e=D.R.Bg(a,0,e[D.R.Dba],g);return new D.fe(a,new D.Na(a,h,j,l,e),b,c,2,d,f)};D.R.vBa=function(a,b,c,d,e,f){var g=D.R.Bg(a,0,e[D.R.$sa],f),h=D.R.Bg(a,1,e[D.R.ata],f);e=D.R.Bg(a,2,e[D.R.Zsa],f);return new D.iL(a,new D.Na(a,g,h,e),b,c,d)};
D.R.tBa=function(a,b,c,d,e,f){var g=D.R.Bg(a,0,e[D.R.Tsa],f),h=D.R.Bg(a,1,e[D.R.Usa],f),j=D.R.Bg(a,2,e[D.R.Ssa],f);e=D.R.Bg(a,3,e[D.R.Rsa],f);return new D.gL(a,new D.Na(a,g,h,j,e),b,c,d)};D.R.uBa=function(a,b,c,d,e,f){var g=D.R.Bg(a,0,e[D.R.Xsa],f),h=D.R.Bg(a,1,e[D.R.Ysa],f),j=D.R.Bg(a,2,e[D.R.Wsa],f);e=D.R.Bg(a,3,e[D.R.Vsa],f);return new D.hL(a,new D.Na(a,g,h,j,e),b,c,d)};
D.R.fBa=function(a,b,c,d,e){var f=(0,D.te)(e,"buttonRadius",0),g=(0,D.te)(e,"buttonWidth",0),h=(0,D.te)(e,"buttonWidth",0),j=D.R.U_(a,f,g,h,e);D.R.P3(c,j,g,h+2*f,e,D.k);b=D.R.T0(a,c,b);(a=D.R.pga(a,d[b],g,h))&&j.k(a);return j};D.R.T0=function(a,b,c,d){var e="";0==b?b=D.R.Psa:1==b?b=D.R.lsa:2==b&&(b=D.R.Gra);d&&(c+=D.R.Asa,(0,D.C)(a)&&(e=D.R.ssa));return c+(b+e)};D.R.j5=function(a,b,c,d){var e=D.R.T0(a,b,D.R.Ksa,D.k);return D.R.Bg(a,b,d[e],c)};
D.R.kBa=function(a,b,c,d,e){var f=(0,D.te)(e,"buttonRadius",0);a=D.R.U_(a,f,c,d,e);D.R.P3(b,a,c,d+2*f,e,D.k);return a};D.R.cBa=function(a,b,c,d,e){b=D.R.T0(a,c,b);return D.R.Bg(a,c,d[b],e)};D.R.pU=function(a,b,c,d,e){var f=D.R.iF(a,0,c,b[D.R.Nra],d,e),g=D.R.iF(a,1,c,b[D.R.Ora],d,e);b=D.R.iF(a,2,c,b[D.R.Mra],d,e);return new D.Na(a,f,g,b)};D.R.nU=function(a,b,c,d,e){var f=D.R.iF(a,0,c,b[D.R.tra],d,e),g=D.R.iF(a,1,c,b[D.R.ura],d,e);b=D.R.iF(a,2,c,b[D.R.sra],d,e);return new D.Na(a,f,g,b)};
D.R.nBa=function(a,b){var c=D.R.jF(a,b[D.R.qsa]),d=D.R.jF(a,b[D.R.rsa]),e=D.R.jF(a,b[D.R.psa]);return new D.Na(a,c,d,e)};D.R.bBa=function(a,b){var c=D.R.jF(a,b[D.R.qra]),d=D.R.jF(a,b[D.R.rra]),e=D.R.jF(a,b[D.R.pra]);return new D.Na(a,c,d,e)};D.R.Bg=function(a,b,c,d){var e,f,g=(0,D.te)(d,"buttonRadius",0);if("undefined"===e||e==D.n)e=(0,D.te)(d,"buttonWidth",0);if("undefined"===f||f==D.n)f=(0,D.te)(d,"buttonWidth",0);b=D.R.wva(a,b,g,e,f,d);(a=D.R.pga(a,c,e,f))&&b.k(a);return b};
D.R.pga=function(a,b,c,d){var e=new D.Xa(a,b);e.ia(D.p);D.Gd.Pj(a,b,function(a){a!=D.n&&(a.width&&a.height)&&(e.ha(a.width),e.xa(a.height),(0,D.G)(e,c/2-a.width/2,d/2-a.height/2))});return e};D.R.X_=function(a,b,c){var d=new D.I(a),e=new D.Ah(a,20,20,20);e.B(0);e.qa((0,D.te)(c,"background-color",D.n));d.k(e);(a=D.Ex.eI(a,b))&&d.k(a);return d};D.R.Y_=function(a,b,c){var d=new D.I(a),e=new D.Ah(a,11,11,8);e.B(0);e.qa((0,D.te)(c,"background-color",D.n));d.k(e);(a=D.Ex.eI(a,b))&&d.k(a);return d};
D.R.iF=function(a,b,c,d,e,f){c||(c=47);b=D.R.zva(a,b,c,e,f);if(a=D.Ex.eI(a,d))d=(0,D.te)(e,"imageWidth",0),f=(0,D.te)(e,"imageHeight",0),b.k(a),(0,D.G)(a,((0,D.te)(e,"openCloseButtonWidth",0)-d)/2,(c-f)/2);return b};D.R.jF=function(a,b){var c=D.Ex.eI(a,b);c.ia(D.k);return c};
D.R.iBa=function(a,b){var c=D.R.Oda(a),d=(0,D.te)(b,"background-color",D.n),e=(0,D.te)(b,"border-color",D.n);"solid"==(0,D.te)(b,"fill-type",D.n)?(c.La(e),c.qa(d)):(c.W(new D.Kk(36,["#8D93A5","#E0EAEB",e],[1,1,1],[0,125/255,1],[0,0,40,40],1)),c.J(new D.bb(90,[d,d,"#5A83BE",d],[0.9,0.1,0,0.7],[0,105/255,150/255,1],[0,0,40,40])));return c};D.R.fka=function(a,b){var c=D.R.Oda(a),d=(0,D.te)(b,"background-color",D.n);c.La(d);c.qa(d);return c};
D.R.Oda=function(a){var b=D.P.moveTo(40,20)+D.P.hc(40,20*D.R.Pd+20,20*D.R.Od+20,20*D.R.Od+20)+D.P.hc(20*D.R.Pd+20,40,20,40)+D.P.hc(20*-D.R.Pd+20,40,20*-D.R.Od+20,20*D.R.Od+20)+D.P.hc(0,20*D.R.Pd+20,0,20)+D.P.hc(0,20*-D.R.Pd+20,20*-D.R.Od+20,20*-D.R.Od+20)+D.P.hc(20*-D.R.Pd+20,0,20,0)+D.P.hc(20*D.R.Pd+20,0,20*D.R.Od+20,20*-D.R.Od+20)+D.P.hc(40,20*-D.R.Pd+20,40,20)+D.P.closePath();return new D.Tb(a,b,"draw_pan_button")};
D.R.CT=function(a,b,c,d,e){a.La("#FFFFFF");a.W(new D.Kk(63,["#8D93A5","#E0EAEB","#FFFFFF"],[1,1,1],[0,155/255,1],[d,e,b,c],1))};
D.R.P3=function(a,b,c,d,e,f){if((0,D.te)(e,"panelDrawerStyles",D.n))!f||f&&0==a?(0,D.La)(b):(1==a||2==a)&&b.J(new D.cb("#EBECED"));else if("skyros"==e.skin)switch(a){case 1:b.J(new D.cb("#FFFFFF",0.7));b.W(new D.db((0,D.te)(e,"border-color",D.n)));break;case 2:b.J(new D.cb("#B3C6DB"));b.W(new D.db((0,D.te)(e,"border-color",D.n)));break;default:(0,D.La)(b)}else{var g,h,j;switch(a){case 3:case 0:g=["#5B868A","#FFFFFF","#FFFFFF","#5B868A"];h=[0.01,0,0.05,0.01];j=[0,120/255,130/255,1];break;case 1:D.R.CT(b,
c,d,0,0);g=["#FFFFFF","#4671B0","#4671B0","#FFFFFF"];h=[0.5,0.2,0.1,0.7];j=[0,120/255,130/255,1];break;case 2:D.R.CT(b,c,d,0,0),g=["#E0EAEB","#5B868A","#4671B0"],h=[0.1,0.3,0.6],j=[0,130/255,1]}b.J(new D.bb(90,g,h,j,[0,0,c,d]))}};
D.R.Kza=function(a,b,c,d,e){if((0,D.te)(e,"panelDrawerStyles",D.n))(0,D.La)(b);else{var f;f=(0,D.te)(e,"border-color",D.n);if("solid"==(0,D.te)(e,"fill-type",D.n)){c=(0,D.te)(e,"background-color",D.n);var g,h;switch(a){case 0:g=(0,D.te)(e,"backgroundAlpha",1);h=(0,D.te)(e,"borderAlpha",1);break;case 2:case 1:g=(0,D.te)(e,"backgroundHoverAlpha",1),h=(0,D.te)(e,"borderHoverAlpha",1)}a=new D.cb(c,g);f=new D.db(f,h)}else{var j,l,m;switch(a){case 0:j=["#FFFFFF","#5B868A","#5B868A"];l=[0,0.2,0.3];m=[0,
130/255,1];break;case 1:j=["#FFFFFF","#FFFFFF","#4671B0","#4671B0"];l=[0.1,0.2,0.1,0.6];m=[0,120/255,130/255,1];break;case 2:j=["#4671B0","#5B868A","#5B868A"],l=[0.5,0.2,0.4],m=[0,130/255,1]}a=new D.bb(0,j,l,m,[0,0,c,d]);f=new D.db(f,1,0.8)}b.W(f);b.J(a)}};
D.R.GJa=function(a,b,c,d,e,f){var g,h,j;switch(a){case 0:b.La("#FFFFFF",1,0.25);g=["#FFFFFF","#4671B0","#E0EAEB","#FFFFFF"];h=[0.6,0.3,0.3,0.8];j=[0,125/255,130/255,1];break;case 1:D.R.CT(b,c,d,e,f);g=["#4671B0","#FFFFFF","#FFFFFF","#FFFFFF"];h=[0.4,0.3,0.7,1];j=[0,70/255,200/255,1];break;case 2:D.R.CT(b,c,d,e,f),g=["#FFFFFF","#4671B0","#E0EAEB"],h=[0.6,0.5,0.8],j=[0,130/255,1]}b.J(new D.bb(90,g,h,j,[e,f,c,d]))};
D.R.pX=function(a,b,c,d){return d?["M",a,0,"L",c,0,"A",c,c,0,0,0,0,c,"L",0,b-c,"A",c,c,0,0,0,c,b,"L",a,b]:["M",0,0,"L",a-c,0,"A",c,c,0,0,1,a,c,"L",a,b-c,"A",c,c,0,0,1,a-c,b,"L",0,b]};D.R.zva=function(a,b,c,d,e){c||(c=47);var f=(0,window.parseInt)((0,D.te)(d,"border-radius",0)),g=(0,D.te)(d,"openCloseButtonWidth",0);c=window.Math.max(c,(0,D.te)(d,"buttonHeight",c));a=new D.Tb(a,D.R.pX(g,c,f,e));D.R.Kza(b,a,g,c,d);return a};D.R.wva=function(a,b,c,d,e,f){a=D.R.U_(a,c,d,e,f);D.R.P3(b,a,d,e+2*c,f);return a};
D.R.U_=function(a,b,c,d,e){if("skyros"==e.skin)return new D.D(a,0,0,c,d);c-=2*b;d-=2*b;e=c+b;var f=d+b,g=D.P.moveTo(e+b,f)+D.P.hc(b+e,D.R.Pd*b+f,D.R.Od*b+e,D.R.Od*b+f)+D.P.hc(D.R.Pd*b+e,b+f,e,b+f)+D.P.lineTo(e,f+b)+D.P.lineTo(e-c,b+f);e-=c;g+=D.P.hc(-D.R.Pd*b+e,b+f,-D.R.Od*b+e,D.R.Od*b+f)+D.P.hc(-b+e,D.R.Pd*b+f,-b+e,f)+D.P.lineTo(e-b,f)+D.P.lineTo(e-b,f-d);f-=d;g+=D.P.hc(-b+e,-D.R.Pd*b+f,-D.R.Od*b+e,-D.R.Od*b+f)+D.P.hc(-D.R.Pd*b+e,-b+f,e,-b+f)+D.P.lineTo(e,-b+f)+D.P.lineTo(e+c,-b+f);e+=c;g+=D.P.hc(D.R.Pd*
b+e,-b+f,D.R.Od*b+e,-D.R.Od*b+f)+D.P.hc(b+e,-D.R.Pd*b+f,b+e,f)+D.P.lineTo(e+b,f+d)+D.P.closePath();return new D.Tb(a,g)};
D.R.BBa=function(a,b,c,d){d=(0,D.te)(d,"radius",0);b-=2*d;c-=d;var e=b+d,f=c,g=D.P.moveTo(e+d,f)+D.P.hc(d+e,D.R.Pd*d+f,D.R.Od*d+e,D.R.Od*d+f)+D.P.hc(D.R.Pd*d+e,d+f,e,d+f)+D.P.lineTo(e,d+f)+D.P.lineTo(e-b,d+f),e=e-b,g=g+(D.P.hc(-D.R.Pd*d+e,d+f,-D.R.Od*d+e,D.R.Od*d+f)+D.P.hc(-d+e,D.R.Pd*d+f,-d+e,f)+D.P.lineTo(-d+e,f)+D.P.lineTo(-d+e,f-c)),f=f-c,g=g+(D.P.lineTo(e+b+d,f)+D.P.lineTo(e+b+d,f+c)+D.P.closePath());return new D.Tb(a,g)};D.R.Hm=function(a,b){b instanceof D.Na&&(b=b.aa(0));return(0,D.Sn)(a,b)};
D.R.G7=function(a,b){var c=D.R.Hoa,d=D.R.Eoa,e=D.R.cX,f;b&&(b.v("fill-type")&&(c=b.v("fill-type")),b.v("border-color")&&(d=b.v("border-color")),b.v("background-color")&&(e=b.v("background-color")),b.v("background")&&(f=b.v("background")));var d=new D.db(d),g;if("solid"==c)g=new D.cb(e);else{var h,j,l;if(f&&0<=f.indexOf("linear-gradient")){if(c=(0,D.Sf)(f))l=c.pk(),g=c.Cl,h=c.Bl,j=c.hv}else g=e,h=D.R.q9,g!=D.R.cX&&(h=D.O.rp(D.R.cX,D.R.q9,g)),g=[g,h],h=[0.6,0.8],j=[0,1],l=-270;g=new D.bb(l,g,h,j)}a.J(g);
a.W(d)};
D.jL={};D.y.l(D.jL,D.y,"DvtCommonLegendDefaults");D.jL.HY={rowColGap:6,separatorGap:7,indicatorSize:16,buttonSize:12,dwn:"#0572CE",ovr:"#5D5D5D",ena:"#7E7F80",separatorColor:"#D9DFE3"};D.jL.IY={dwn:"#202F48",ovr:"#184DD8",ena:"#003D5B"};D.jL.AA={rowColGap:4,separatorGap:4,indicatorSize:11,buttonSize:11,dwn:"#000000",ovr:"#245EDD",ena:"#495D7C",separatorColor:"#ADB6C7"};D.jL.ah=function(a){var b=D.jL.LB(a);return a?D.Sa.Ob(a,b):b};
D.jL.LB=function(a){var b=D.n;return b=a&&"skyros"===a.skin?D.Sa.Ob(D.jL.IY,D.jL.AA):a&&"alta"===a.skin?D.Sa.Ob(D.jL.HY,D.jL.AA):D.Sa.clone(D.jL.AA)};
D.DvtCommonLegend=function(a,b,c,d,e){this.Init(a,b,c,d,e)};D.y.l(D.DvtCommonLegend,D.I,"DvtCommonLegend");D.DvtCommonLegend.T$="isLegendDisclosed";D.DvtCommonLegend.Jqa="skin";D.x=D.DvtCommonLegend.prototype;D.x.Init=function(a,b,c,d,e){D.DvtCommonLegend.o.Init.call(this,a,D.n,b,c);this.Qh=(0,D.C)();this.T=this.JJa=b;this.Y=c;this.YP={};this.c1={};this.OJ=[];this.LE=D.p;this.bu=[];this.xza=this.rM=D.p;this.JF=[];this.oj=d;this.D=D.jL.ah(e?{skin:e}:D.n);this.w1=D.p;this.af=new D.wa};D.x.FJ=(0,D.w)("af");
D.x.cA=(0,D.w)("w1");D.x.z8=(0,D.v)("ZF");D.x.oW=function(a){a&&(this.$B=a)};D.x.Za=(0,D.w)("RF");D.x.Pe=(0,D.v)("RF");
D.mL=function(a,b,c,d,e){var f=b.q("label"),f=new D.kL(a.e,a,f,a.K3,a.D);f.L(c,d,e);if(b=b.ub())for(var g=0;g<b.length;g++){var h=b[g],j;if("item"==h.getName()){j=a;var l={};l.itemId=h.q("itemId");l.attributeGroupId=h.q("attributeGroupId");l.hideAttrs=h.q("hideAttrs");j=new D.lL(j.e,j,l,j.lL,j.D);h=h.ub();for(l=0;l<h.length;l++)if("marker"==h[l].getName()){var m=j,o=h[l],q=o.q("url"),r=o.q("shapeType"),t=o.q("color"),u=o.q("pattern");(o=o.q("opacity"))&&(o=(0,window.parseFloat)(o));m.setMarker(q,
r,t,u,o)}else"text"==h[l].getName()&&j.jh(h[l].q("value"))}else"text"==h.getName()&&(j=new D.lL(a.e,a,D.n,a.lL,a.D),j.jh(h.q("value")));j&&(j.L(f,d,e),f.Cj(j))}c.k(f);d.y=d.y-a.D.rowColGap+a.D.rowColGap;return f};
D.nL=function(a,b,c,d,e){var f=new D.kL(a.e,a,b.label,a.K3,a.D);f.L(c,d,e);var g=b.item,h;if(g)for(var j=0;j<g.length;j++){var l=a;h=g[j];var m={};m.itemId=h.itemId;m.attributeGroupId=h.attributeGroupId;m.hideAttrs=h.hideAttrs;l=new D.lL(l.e,l,m,l.lL,l.D);if(h.marker){var o=h.marker,m=o.url,q=o.shapeType,r=o.color,t=o.pattern;(o=o.opacity)&&(o=(0,window.parseFloat)(o));l.setMarker(m,q,r,t,o)}h.text&&l.jh(h.text.value);if(h=l)h.L(f,d,e),f.Cj(h)}if(b=b.text)for(j=0;j<b.length;j++)h=new D.lL(a.e,a,D.n,
a.lL,a.D),h.jh(b[j].value),h&&(h.L(f,d,e),f.Cj(h));c.k(f);d.y=d.y-a.D.rowColGap+a.D.rowColGap;return f};D.pL=function(a,b,c,d,e){var f=b.q("label"),g="true"==b.q("disclosed"),h=b.q("expandTooltip"),j=b.q("collapseTooltip"),f=new D.oL(a.e,a,f,a.I3,j,h,g,a.D);f.L(c,d,e);c=e?-1:1;if(b=b.ub())for(g=0;g<b.length;g++)h=b[g],"section"==h.getName()&&(d.x+=(a.D.buttonSize+a.D.rowColGap)*c,h=(0,D.mL)(a,h,f,d,e),d.x-=(a.D.buttonSize+a.D.rowColGap)*c,f.Cj(h));d.y=d.y-a.D.rowColGap+a.D.rowColGap;return f};
D.qL=function(a,b,c,d,e){var f=new D.oL(a.e,a,b.label,a.I3,b.collapseTooltip,b.expandTooltip,"true"==b.disclosed,a.D);f.L(c,d,e);c=e?-1:1;if(b=b.section)for(var g=0;g<b.length;g++){d.x+=(a.D.buttonSize+a.D.rowColGap)*c;var h=(0,D.nL)(a,b[g],f,d,e);d.x-=(a.D.buttonSize+a.D.rowColGap)*c;f.Cj(h)}d.y=d.y-a.D.rowColGap+a.D.rowColGap;return f};
D.rL=function(a,b,c){c.y=c.y-a.D.rowColGap+a.D.separatorGap;var d=new D.Pi(a.e,c.x,c.y,c.x,c.y);(0,D.Rd)(d);d.La(a.D.separatorColor);a.bu.push(d);var e;if("alta"==a.D.skin)e=d;else{c.y++;var f=new D.Pi(a.e,c.x,c.y,c.x,c.y);f.La("#FFFFFF");(0,D.Rd)(f);e=new D.I(a.e);e.k(d);e.k(f);a.bu.push(f)}b.k(e);c.y+=a.D.separatorGap;return e};
D.DvtCommonLegend.prototype.update=function(a,b){for(var c=this.ve.indexOf(a),c=c+1;c<this.ve.length;){var d=this.ve[c].K();this.ve[c].O(d+b);c++}this.pc.j+=b;this.Tb(new D.vt(this.pc.g,this.pc.j,0,0))};D.DvtCommonLegend.prototype.Tc=(0,D.w)("Ca");
D.DvtCommonLegend.prototype.L=function(){if(this.ZF){this.Ca=new D.sL(this.e,this.zxa,this);this.Gd=this.ZF.q("label");this.RF="true"==this.ZF.q("disclosed");var a=this.ZF.getElementsByTagName("style");if(a&&(a=a[0].ub()))for(var b=0;b<a.length;b++){var c=a[b];"legend-title"==c.getName()?this.mL=c.getTextContent():"sectionGroup-title"==c.getName()?this.I3=c.getTextContent():"section-title"==c.getName()?this.K3=c.getTextContent():"legend-item"==c.getName()&&(this.lL=c.getTextContent())}if(a=this.ZF.q("noWrap"))this.w1=
"false"==a;a=this.Qh?new D.N(this.T,0,this.T,this.Y):new D.N(0,0,this.T,this.Y);this.Ln=new D.I(this.e);this.k(this.Ln);if(this.Gd&&(b=this.cA()?new D.Nk(this.e):new D.Ia(this.e),c=a.g-a.x,this.Qh&&(c=a.g-c),0<c&&(this.Qh&&b.Dj(),this.mL&&b.Ia(new D.B(this.mL)),b.Dd(this.Gd),b.ea(a.x),b.va(a.y),D.Pa.Vb(b,c,a.j,this.Ln),b.wg()&&this.Ca.ka(b,new D.Ga(this.Gd)),(b=b.C())&&0<b.j)))a.y=a.y+b.j+this.D.rowColGap;this.ve=[];if(c=this.ZF.ub()){for(b=0;b<c.length;b++){var d=c[b];if("separatorDef"==d.getName()&&
(d=d.ub(),0<d.length&&"separator"==d[0].getName())){this.LE=D.k;break}}for(b=0;b<c.length;b++)d=c[b],a.x=this.Qh?this.T:0,"sectionGroup"==d.getName()?(this.LE&&(this.Gd||1<b)&&this.ve.push((0,D.rL)(this,this.Ln,a)),this.ve.push((0,D.pL)(this,d,this.Ln,a,this.Qh))):"section"==d.getName()&&(this.LE&&(this.Gd||1<b)&&this.ve.push((0,D.rL)(this,this.Ln,a)),this.ve.push((0,D.mL)(this,d,this.Ln,a,this.Qh)))}this.pc=this.Hj();for(a=0;a<this.bu.length;a++)this.Qh?this.bu[a].Ei(this.pc.x):this.bu[a].Ei(this.pc.g);
this.Ca.Df(this);for(b=0;b<this.OJ.length;b++)a=this.OJ[b],this.Ca.ka(a,a),this.JF&&-1<D.Hc.Fa(this.JF,a.Gj()+":"+a.Mw())&&(0,D.tL)(a,D.k)}else{this.Ca=new D.sL(this.e,this.zxa,this);this.Gd=this.$B.label;this.RF="true"==this.$B.disclosed;if(a=this.$B.style)this.mL=a["legend-title"],this.I3=a["sectionGroup-title"],this.K3=a["section-title"],this.lL=a["legend-item"];if(a=this.$B.noWrap)this.w1="false"==a;a=this.Qh?new D.N(this.T,0,this.T,this.Y):new D.N(0,0,this.T,this.Y);this.Ln=new D.I(this.e);this.k(this.Ln);
if(this.Gd&&(b=this.cA()?new D.Nk(this.e):new D.Ia(this.e),c=a.g-a.x,this.Qh&&(c=a.g-c),0<c&&(this.Qh&&b.Dj(),this.mL&&b.Ia(new D.B(this.mL)),b.Dd(this.Gd),b.ea(a.x),b.va(a.y),D.Pa.Vb(b,c,a.j,this.Ln),b.wg()&&this.Ca.ka(b,new D.Ga(this.Gd)),(b=b.C())&&0<b.j)))a.y=a.y+b.j+this.D.rowColGap;this.ve=[];if(c=this.$B.separatorDef)for(b=0;b<c.length;b++)if((d=c[b].separator)&&0<d.length){this.LE=D.k;break}c=this.$B.sectionGroup;a.x=this.Qh?this.T:0;if(c)for(b=0;b<c.length;b++)this.LE&&(this.Gd||1<b)&&this.ve.push((0,D.rL)(this,
this.Ln,a)),this.ve.push((0,D.qL)(this,c[b],this.Ln,a,this.Qh));if(c=this.$B.section)for(b=0;b<c.length;b++)this.LE&&(this.Gd||1<b)&&this.ve.push((0,D.rL)(this,this.Ln,a)),this.ve.push((0,D.nL)(this,c[b],this.Ln,a,this.Qh));this.pc=this.Hj();for(a=0;a<this.bu.length;a++)this.Qh?(this.pc.x=this.bu[a].xk()-this.pc.g,this.bu[a].Ei(this.pc.x)):this.bu[a].Ei(this.pc.g+this.bu[a].xk());this.Ca.Df(this);for(b=0;b<this.OJ.length;b++)a=this.OJ[b],this.Ca.ka(a,a),this.JF&&-1<D.Hc.Fa(this.JF,a.Gj()+":"+a.Mw())&&
(0,D.tL)(a)}this.JF&&(this.pc=this.Hj(),this.Tb(new D.vt(this.pc.g,this.pc.j,this.pc.x,this.pc.y)));this.Qh&&this.Ln.F(-this.pc.x)};D.oL=function(a,b,c,d,e,f,g,h){this.Init(a,b,c,d,e,f,g,h)};D.y.l(D.oL,D.I,"DvtCommonLegendSection");D.oL.prototype.Init=function(a,b,c,d,e,f,g,h){D.kL.o.Init.call(this,a);this.Gd=c;this.Cz=d;this.ob=[];this.Ba=b;this.qB=e;this.EB=f;this.hK=g?0:1;this.D=h};
D.uL=function(a,b,c,d,e,f,g){if(!b)return new D.Na(a.e);switch(g){case 1:g=new D.Xa(a.e,b.groupColEna,c,d,e,f);var h=new D.Xa(a.e,b.groupColOvr,c,d,e,f);b=new D.Xa(a.e,b.groupColDwn,c,d,e,f);return new D.Na(a.e,g,h,b);default:return g=new D.Xa(a.e,b.groupExpDwn,c,d,e,f),h=new D.Xa(a.e,b.groupExpOvr,c,d,e,f),b=new D.Xa(a.e,b.groupExpDwn,c,d,e,f),new D.Na(a.e,g,h,b)}};D.x=D.oL.prototype;
D.x.Xea=function(){var a=(0,D.C)()?-1:1;this.J3||(this.J3=this.Hj().j-this.Pv);0==this.hK?("alta"==this.D.skin?(a=this.sb.getParent(),a.removeChild(this.sb),this.sb=this.qy,a.k(this.sb)):this.sb.Wc([this.Dr+1.5*a,this.Er+1.5,this.Dr+9.5*a,this.Er+5.5,this.Dr+1.5*a,this.Er+9.5]),this.Jfa=D.p,this.hK=1,a=-this.J3):("alta"==this.D.skin?(a=this.sb.getParent(),a.removeChild(this.sb),this.sb=this.Fv,a.k(this.sb)):this.sb.Wc([this.Dr+1.5*a,this.Er+1.5,this.Dr+9.5*a,this.Er+1.5,this.Dr+5.5*a,this.Er+9.5]),
this.Jfa=D.k,this.hK=0,a=this.J3);if(this.Jfa)for(var b=0;b<this.ob.length;b++)this.k(this.ob[b]);else for(b=0;b<this.ob.length;b++)this.removeChild(this.ob[b]);this.Ba.update(this,a)};D.x.OR=function(){"alta"==!this.D.skin&&this.sb.qa(this.D.ovr)};D.x.NR=function(){"alta"==!this.D.skin&&this.sb.qa(this.D.ena)};D.x.MR=function(){"alta"==!this.D.skin&&this.sb.qa(this.D.dwn)};D.x.Cj=function(a){return this.ob.push(a)};
D.x.L=function(a,b,c){a.k(this);a=new D.I(this.e);this.k(a);this.Dr=b.x;this.Er=b.y;var d=c?-1:1;if("alta"==this.D.skin){var e=this.Ba.oj;this.Fv=(0,D.uL)(this,e,this.Dr,this.Er,this.D.buttonSize,this.D.buttonSize,0);this.qy=(0,D.uL)(this,e,this.Dr,this.Er,this.D.buttonSize,this.D.buttonSize,1);this.sb=this.Fv}else this.sb=new D.wh(this.e,[this.Dr+1.5*d,this.Er+1.5,this.Dr+9.5*d,this.Er+1.5,this.Dr+5.5*d,this.Er+9.5]),this.sb.qa(this.D.ena);a.k(this.sb);if((0,D.Qa)())a.U(D.Wv.Ce,this.Xea,D.p,this);
else{var f=this;this.Ba.Tc().ka(a,{te:function(){return 0==f.hK?f.qB:f.EB}});a.U(D.Cb,this.Xea,D.p,this);a.U(D.Yq,this.OR,D.p,this);a.U(D.Zq,this.NR,D.p,this);a.U(D.cj,this.MR,D.p,this)}this.hK=0;b.x+=(("alta"==this.D.skin&&c?0:this.D.buttonSize)+this.D.rowColGap)*d;this.Gd&&(d=this.Ba.cA()?new D.Nk(this.e):new D.Ia(this.e),e=b.g-b.x,c&&(e=b.g-e),0<e&&(c&&d.Dj(),this.Cz&&d.Ia(new D.B(this.Cz)),d.Dd(this.Gd),d.ea(b.x),d.va(b.y),D.Pa.Vb(d,e,b.j,a),d.wg()&&this.Ba.Tc().ka(d,new D.Ga(this.Gd)),a=d.C(),
b.y=b.y+window.Math.max(a?a.j:0,this.D.buttonSize)+this.D.rowColGap));b.x+=(this.D.buttonSize+this.D.rowColGap)*(c?1:-1);this.Pv=this.Hj().j};D.kL=function(a,b,c,d,e){this.Init(a,b,c,d,e)};D.y.l(D.kL,D.I,"DvtCommonLegendSection");D.kL.prototype.Init=function(a,b,c,d,e){D.kL.o.Init.call(this,a);this.Gd=c;this.Cz=d;this.ob=[];this.Ba=b;this.D=e};D.kL.prototype.Cj=function(a){return this.ob.push(a)};D.kL.prototype.qp=(0,D.w)("ob");
D.kL.prototype.L=function(a,b,c){a.k(this);if(this.Gd){a=this.Ba.cA()?new D.Nk(this.e):new D.Ia(this.e);var d=b.g-b.x;c&&(d=b.g-d);0<d&&(c&&a.Dj(),this.Cz&&a.Ia(new D.B(this.Cz)),a.Dd(this.Gd),a.ea(b.x),a.va(b.y),D.Pa.Vb(a,d,b.j,this),a.wg()&&this.Ba.Tc().ka(a,new D.Ga(this.Gd)),c=a.C(),b.y=b.y+(c?c.j:0)+this.D.rowColGap)}};D.lL=function(a,b,c,d,e){this.Init(a,b,c,d,e)};D.y.l(D.lL,D.I,"DvtCommonLegendRow");D.x=D.lL.prototype;
D.x.Init=function(a,b,c,d,e){D.lL.o.Init.call(this,a);this.Ba=b;this.ap=c;this.Hfa=d;this.iQ=D.p;this.D=e};D.x.Gj=function(){return this.ap.attributeGroupId};D.x.Mw=function(){return this.ap.itemId};D.x.b6=function(){return this.ap.hideAttrs};D.x.jh=(0,D.v)("Ya");D.x.setMarker=function(a,b,c,d,e){this.ST=a;this.H=b;this.Ug=c?c:"#000000";this.Zo=d;this.K2=e};D.tL=function(a,b){a.iQ=!a.iQ;a.Mn.wI(a.Ug);a.$j();b||(a.Ba.pc=a.Ba.Hj(),a.Ba.Tb(new D.vt(a.Ba.pc.g,a.Ba.pc.j,a.Ba.pc.x,a.Ba.pc.y)))};
D.lL.prototype.vc=function(){if(this.Ba.rM){var a=this.Ba.FJ(),b=[(0,D.ob)(a,this.iQ?"STATE_HIDDEN":"STATE_VISIBLE")];return(0,D.$b)(this.Ya,b,a)}return D.n};D.lL.prototype.$j=function(){(0,D.ac)()||(0,D.Oa)(this,"label",this.vc())};
D.lL.prototype.L=function(a,b,c){if(this.ap){var d=this.Ba,e=this.ap.attributeGroupId,f=this.ap.itemId;d.YP[e]==D.n&&(d.YP[e]={});d.YP[e][f]=this;this.Ba.OJ.push(this);d=this.Ba;e=this.ap.hideAttrs;d.c1[e]||(d.c1[e]=this)}a.k(this);a=b.x;c&&(b.x-=this.D.indicatorSize);var g;if(this.ST||this.H!=D.n)g=new D.Ed(this.e,this.ST?[this.ST]:this.H,this.D[D.DvtCommonLegend.Jqa],b.x,b.y,this.D.indicatorSize,this.D.indicatorSize),d=D.Ad.Qka(this.e,this.H),!this.ST&&!d&&(this.Zo?g.J(new D.id(this.Zo,this.Ug)):
g.qa(this.Ug,this.K2)),this.k(g),b.x=c?b.x-this.D.rowColGap:b.x+this.D.indicatorSize+this.D.rowColGap;this.Mn=g;g=new D.N;this.Ya&&(this.Ba.rM&&(this.Hf("img"),this.$j()),d=b.g-b.x,c&&(d=b.g-d),0>d?this.Ba.Tc().ka(this.Mn,new D.Ga(this.Ya)):(e=this.Ba.cA()?new D.Nk(this.e):new D.Ia(this.e),c&&e.Dj(),this.Hfa&&e.Ia(new D.B(this.Hfa)),e.Dd(this.Ya),e.ea(b.x),e.va(b.y),D.Pa.Vb(e,d,b.j,this)?(g=e.C(),e.wg()&&this.Ba.Tc().ka(e,new D.Ga(this.Ya))):this.Ba.Tc().ka(this.Mn,new D.Ga(this.Ya))));b.y=b.y+window.Math.max(this.D.indicatorSize,
g.j)+this.D.rowColGap;b.x=a};D.sL=function(a,b,c){this.Init(a,b,c);this.Ba=c};D.y.l(D.sL,D.ta,"DvtCommonLegendEventManager");D.x=D.sL.prototype;D.x.mh=function(a){D.sL.o.mh.call(this,a);this.Ft(a)};D.x.zo=function(a){D.sL.o.zo.call(this,a);(0,D.vL)(this,a)};D.x.fj=function(a){D.sL.o.fj.call(this,a);(0,D.vL)(this,a)};D.x.$s=function(a){D.sL.o.$s.call(this,a);this.Ft(a)};
D.x.Ft=function(a){if(this.Ba.rM){var b=this.ma(a.target);if(b instanceof D.lL){var c=b.Mw(),d=b.Gj();(0,D.tL)(b);a=new D.sI(c,d,b.iQ?"hide":"show",a);this.Ba.Tb(a)}}};D.vL=function(a,b){var c=a.ma(b.target);if(c instanceof D.lL){if(a.Ba.xza){var d=c.Mw(),e=c.Gj(),d=new D.kI(d,e,c.b6(),b.type,b);a.Ba.Tb(d)}a.Ba.rM&&a.at(c)}};
});