"use strict";
define(['./DvtToolkit', './DvtBaseTreeView'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.$B=function(a,b){this.Init(b===D.p?"sunburstRotationInput":"sunburstRotation");this.bd=a%360};(0,D.ra)("DvtSunburstRotationEvent",D.$B);D.y.l(D.$B,D.tb,"DvtSunburstRotationEvent");D.$B.TYPE="sunburstRotation";D.$B.TYPE_INPUT="sunburstRotationInput";D.$B.prototype.Fla=(0,D.w)("bd");D.$B.prototype.getStartAngle=D.$B.prototype.Fla;
D.SB=function(a,b,c){this.Init(a,b,c)};D.y.l(D.SB,D.UB,"DvtBaseSunburst");D.x=D.SB.prototype;D.x.Init=function(a,b,c){D.SB.o.Init.call(this,a,b,c);this.vf=new D.cc;this.ld=2*window.Math.PI};D.x.Wu=function(a){return(new D.pb(this)).parse(a)};D.x.HI=function(a){D.SB.o.HI.call(this,a);this.Cia=a.rotation;this.Aia=(0,D.Vb)()?"url("+this.yh.cursorRotate+"), auto":"url("+this.yh.cursorRotate+") 8 8, auto";this.bd=(360-a.xW)*D.vb/360;this.bd>window.Math.PI&&(this.bd-=D.vb)};
D.x.xo=function(a){var b=window.Math.max(window.Math.ceil(3*window.Math.min(a.g,a.j)/400),2);a.x+=b;a.y+=b;a.g-=2*b;a.j-=2*b;(0,D.VB)(this,a);(0,D.WB)(this,a);this.uja=window.Math.floor(window.Math.min(a.g,a.j)/2);this.Pa&&D.jb.io(this.uja,this.Pa,this.bd,this.ld,this.AP)};
D.x.Fi=function(a,b){(0,D.XB)(this,a);this.Hl&&a.k(this.Hl);this.Ba&&(a.k(this.Ba),this.Ba=D.n);this.gH=new D.L(b.x+b.g/2,b.y+b.j/2);if("on"==this.Cia&&(0,D.YB)(this)){var c=(0,D.Qa)()?60:15,c=new D.Ah(this.e,b.x+b.g/2,b.y+b.j/2,this.uja+c);(0,D.La)(c);c.setCursor(this.Aia);a.k(c);this.Ua().ka(c,new D.Zb(D.n,"_rotationShape"))}c=new D.I(this.e);(0,D.G)(c,this.gH.x,this.gH.y);a.k(c);if((0,D.YB)(this)){var d=new D.I(this.e);c.k(d);this.Pa.L(d);this.$t=new D.I(this.e);c.k(this.$t);this.gfa=new D.I(this.e);
c.k(this.gfa)}else(0,D.ZB)(this,a)};D.x.hE=function(a,b,c,d){return new D.fc(a,b,c,d)};D.x.tX=function(a,b){if("fan"===this.GW&&(0,D.YB)(this)){this.IZ(0);var c=new D.Le(this.e,this,this.cE);(0,D.T)(c.R,"typeNumber",this,this.Nva,this.IZ,2*window.Math.PI);return c}return D.SB.o.tX.call(this,a,b)};D.x.rX=function(){var a=D.SB.o.rX.call(this);a&&(0,D.G)(a,this.gH.x,this.gH.y);return a};
D.x.Kp=function(){if(!this.HW){this.ca.Di();var a=new D.N(0,0,this.pb,this.Cb);this.xo(a);this.Fi(this.ca,a);for(var a=this.Mb?this.Mb.getSelection():[],b=0;b<a.length;b++)a[b].Pb(D.k)}this.ld<2*window.Math.PI&&this.IZ(2*window.Math.PI);D.SB.o.Kp.call(this)};D.x.OP=function(a){this.$t.k(a);!(0,D.Vg)()&&!(0,D.Wg)()&&((0,D.Yg)(this.$t),(0,D.Xg)(this.$t,D.Fe))};D.x.Nva=(0,D.w)("ld");D.x.IZ=function(a){this.ld=a;this.xo(new D.N(0,0,this.pb,this.Cb));this.Pa&&(0,D.Pb)(this.Pa,D.k)};
D.hc=function(a,b){a.b0=b;a.GG=new D.D(a.e,0,0,a.pb,a.Cb);(0,D.La)(a.GG);a.GG.setCursor(a.Aia);a.k(a.GG);a.Ua().ka(a.GG,new D.Zb(D.n,"_rotationShape"))};D.jc=function(a,b){var c=b-a.b0;a.b0=b;a.bd+=c;a.bd<-window.Math.PI?a.bd+=2*window.Math.PI:a.bd>window.Math.PI&&(a.bd-=2*window.Math.PI);a.xo(new D.N(0,0,a.pb,a.Cb));a.Pa&&(0,D.Pb)(a.Pa,D.k);a.Wa(new D.$B(360-window.Math.round(180*a.bd/window.Math.PI),D.p))};
D.lc=function(a){a.b0=D.n;a.removeChild(a.GG);a.GG=D.n;var b=360-window.Math.round(180*a.bd/window.Math.PI);a.Wa(new D.$B(b,D.p));a.Wa(new D.$B(b,D.k))};D.ic=function(a,b,c){return window.Math.atan2(c-a.gH.y,b-a.gH.x)};
D.RB=(0,D.s)();(0,D.ra)("DvtSunburst",D.RB);D.y.l(D.RB,D.SB,"DvtSunburst");D.RB.newInstance=function(a,b,c){var d=new D.RB;d.Init(a,b,c);return d};D.RB.getDefaults=function(a){return(0,D.TB)(new D.cc,a)};D.RB.prototype.L=function(a,b,c){a?(this.M=this.vf.ah(a),(0,D.yp)()||(this.M.animationOnDisplay="none",this.M.animationOnDataChange="none")):this.M||(this.M=(0,D.xf)(this));a=(new D.lb).E8(this.M);D.RB.o.L.call(this,a,b,c)};D.RB.prototype.render=D.RB.prototype.L;
D.RB.prototype.jc=function(){this.af||(this.af=new D.nb);return this.af};
D.pb=function(a){this.Init(a)};D.y.l(D.pb,D.qb,"DvtSunburstParser");D.pb.prototype.qn=function(a,b,c){return new D.rb(a,b,c)};D.pb.prototype.qm=function(a){var b=D.pb.o.qm.call(this,a);b.rotation=a.q("r");b.xW=a.q("sa");if(b.xW===D.n||(0,window.isNaN)(b.xW))b.xW=90;return b};D.pb.prototype.Xu=function(a){var b=D.pb.o.Xu.call(this,a);b.EV=a.q("ha");b.GGa=a.q("r");return b};
D.pb.prototype.kY=function(a,b,c,d){d.NODE_DEFAULT_COLOR_STYLE=a.v("border-color");d.NODE_HOVER_COLOR_STYLE=b.v("border-color");d.NODE_SELECTED_INNER_COLOR_STYLE=c.v("-tr-inner-color");d.NODE_SELECTED_OUTER_COLOR_STYLE=c.v("-tr-outer-color")};
D.rb=function(a,b,c){this.Init(a,b,c);this.Po=b.DV?b.DV:"auto";this.UF=b.EV;this.mk=b.GGa};D.y.l(D.rb,D.ub,"DvtSunburstNode");D.vb=2*window.Math.PI;
D.rb.prototype.L=function(a){if(this.Ov){this.JS=a;this.H=this.Z_();a.k(this.H);var b=this.xM;if(!this.Bf&&(0==this.pi&&this.ld==D.vb)&&b){var c=window.Math.sqrt(2),d=this.Sh*c-4;this.Ta=-this.Sh/c+2;this.lb=-this.Sh/c+2;c=this.I.DZ;c.Jo=this.mi;0<d&&0<d&&((0,D.wb)(c,d),(0,D.xb)(c,d),c.Wf((0,D.yb)(this)),this.R_=b=D.K.LD(c,b,this.H),c=b.C(),(0,D.G)(b,this.Ta+(d-c.g)/2,this.lb+(d-c.j)/2))}else this.Ya=this.tK(this.H),this.Ya!=D.n&&(this.H.k(this.Ya),this.Zo&&(c=this.Ya.cc(),this.dp=new D.D(this.I.e,
c.x,c.y,c.g,c.j),this.dp.qa("#FFFFFF"),this.dp.ia(D.p),this.H.k(this.dp),d=this.Ya.na(),(0,D.Ab)(d)||this.dp.sa(d),this.H.k(this.Ya)));this.H.Hf("img");this.$j();this.Iu(a)}};D.rb.prototype.Pb=function(a){D.rb.o.Pb.call(this,a);this.Ma()?(this.H.Pb(D.k),this.I.OP(this.H)):(this.H.Pb(D.p),this.JS&&this.JS.k(this.H))};D.rb.prototype.Oc=function(){this.H&&this.Ov&&(this.H.Oc(),this.Ma()?this.I.OP(this.H):this.I.gfa.k(this.H))};
D.rb.prototype.sc=function(){this.H&&(this.Ov&&!this.vg())&&(this.H.sc(),!this.Ma()&&this.JS&&this.JS.k(this.H))};D.Bb=function(a){return"i"==a.sR||"ir"==a.sR};
D.rb.prototype.Rf=function(a){var b,c,d,e;if(a.type==D.Cb)return D.rb.o.Rf.call(this,a);b=a.keyCode;if(32==b&&a.ctrlKey)return this;for(e=this;e.Bf;)e=e.Bf;c=(0,D.Db)(this,e,(0,D.Eb)(this));a:{for(d=0;d<c.length;d++)if(this===c[d])break a;d=-1}var f=this.bd+this.ld/2,f=(0,D.Fb)(f);switch(b){case 38:if(this===e||180<f){if(b=this.sS)if(c=b.bd+b.ld/2,c=(0,D.Fb)(c),180<c)return b;a=(0,D.Gb)(this,a,(0,D.Hb)(this))}else a=(0,D.Ib)(this);break;case 40:if(this===e||0<=f&&180>=f){if(b=this.sS)if(c=b.bd+b.ld/
2,c=(0,D.Fb)(c),0<=c&&180>=c)return b;a=(0,D.Gb)(this,a,(0,D.Hb)(this))}else a=(0,D.Ib)(this);break;case 37:a=1==c.length?this:0==d?c[c.length-1]:c[d-1];break;case 39:a=1==c.length?this:d==c.length-1?c[0]:c[d+1];break;default:a=this}(0,D.Jb)(a);return a};D.Ib=function(a){var b=a.Bf;b&&(a=b,(0,D.Jb)(b));(0,D.Jb)(a);return a};D.Fb=function(a){a=D.Kb.V7(a);0>a?a+=360:360<a&&(a-=360);return a};D.x=D.rb.prototype;
D.x.of=function(){if(this.H){var a=this.H.C(),b=new D.L(a.x,a.y),b=(0,D.Lb)(this.H,b);a.x=b.x;a.y=b.y;return a}return new D.N(0,0,0,0)};D.x.$m=function(){return this.H?this.H.pa():D.n};D.x.KU=function(){return(0,D.Lb)(this.H,(0,D.Mb)(0.5*(this.Sh+this.pi),this.bd+this.ld/2))};D.x.mO=function(a,b,c,d){this.pi=a;this.Sh=b;this.bd=c;this.ld=d;this.Ov=D.k};D.x.mE=function(){return this.VE?(0,D.Nb)():D.rb.o.mE.call(this)};
D.x.vl=function(){var a=D.O.yd(this.Ug),b=D.O.xd(this.Ug),c=D.O.wd(this.Ug);return[this.pi,this.Sh,this.bd,this.ld,a,b,c]};D.x.Co=function(a){this.mO(a[0],a[1],a[2],a[3]);this.Ug=D.O.mx(window.Math.round(a[4]),window.Math.round(a[5]),window.Math.round(a[6]));(0,D.Pb)(this,D.p)};D.x.ig=function(a,b){b.Ov&&0<b.ld?D.rb.o.ig.call(this,a,b):this.$g(a)};D.x.contains=function(a,b){var c=(0,D.Qb)(a,b);return window.Math.sqrt(a*a+b*b)>=this.pi&&window.Math.sqrt(a*a+b*b)<=this.Sh&&(0,D.Rb)(this,c)};
D.Rb=function(a,b){for(;b<a.bd;)b+=D.vb;for(;b-a.bd>D.vb;)b-=D.vb;return b>=a.bd&&b<=a.bd+a.ld};D.Mb=function(a,b){return{x:window.Math.cos(b)*a,y:window.Math.sin(b)*a}};D.Qb=function(a,b){var c=window.Math.atan2(b,a);0>c?c+=D.vb:c>D.vb&&(c-=D.vb);return c};
D.rb.prototype.Z_=function(){if(!this.ld||0>=this.ld)return D.n;var a=(0,D.Sb)(this),a=new D.Tb(this.I.e,a);this.I.Ua().ka(a,this);a.B(this.Z());a.J(this.mE());var b=(0,D.Ub)(this,"#FFFFFF","NODE_SELECTED_INNER_COLOR_STYLE"),c=(0,D.Ub)(this,"#000000","NODE_SELECTED_OUTER_COLOR_STYLE"),d=(0,D.Ub)(this,"#FFFFFF","NODE_HOVER_COLOR_STYLE");a.W(new D.db((0,D.Ub)(this,"#FFFFFF","NODE_DEFAULT_COLOR_STYLE"),0.3));a.Gs(new D.db(d,1,3));a.Ls(new D.db(b,1,1.5),new D.db(c,1,3.5));a.Mu(new D.db(d,1,3));a.ih(this.$b());
this.VE&&(a.B(0.001),a.ia(D.p));return a};
D.Sb=function(a){var b,c,d,e;a.ld<D.vb?(b=(0,D.Mb)(a.Sh,a.bd),c=(0,D.Mb)(a.Sh,a.bd+a.ld),d=(0,D.Mb)(a.pi,a.bd+a.ld),e=(0,D.Mb)(a.pi,a.bd),b=D.P.moveTo(b.x,b.y)+D.P.arcTo(a.Sh,a.Sh,a.ld,1,c.x,c.y)+D.P.lineTo(d.x,d.y)+D.P.arcTo(a.pi,a.pi,a.ld,0,e.x,e.y)+D.P.closePath()):(b=(0,D.Mb)(a.Sh,a.bd),c=(0,D.Mb)(a.Sh,a.bd+a.ld/2),d=(0,D.Mb)(a.pi,a.bd),e=(0,D.Mb)(a.pi,a.bd+a.ld/2),b=D.P.moveTo(b.x,b.y)+D.P.arcTo(a.Sh,a.Sh,a.ld/2,1,c.x,c.y)+D.P.arcTo(a.Sh,a.Sh,a.ld/2,1,b.x,b.y),0<a.pi&&(b+=D.P.moveTo(e.x,e.y)+
D.P.arcTo(a.pi,a.pi,a.ld/2,0,d.x,d.y)+D.P.arcTo(a.pi,a.pi,a.ld/2,0,e.x,e.y)),b+=D.P.closePath());return b};
D.rb.prototype.tK=function(a){if(!this.Bz||!a||!this.Po||"off"==this.Po)return D.n;var b=D.p;if("auto"==this.Po){if(b=!(0,D.Vb)())(0,D.Wb)(),b="Windows"==D.Xb;b=b?D.p:D.k}else"rotated"==this.Po&&(b=D.k);if(b&&this.ld<2*window.Math.PI){var c=window.Math.max(this.pi,10),d=this.Sh-c-6,e=1.1*this.ld*(c+6);if(6>=e)a=D.n;else if(b=new D.Ia(this.I.e,this.Bz,0,0),b.Wf((0,D.yb)(this)),(0,D.Yb)(this,b),D.Pa.Vb(b,d,e,a)){e=(c+this.Sh)/2;if("s"==this.UF||"e"==this.UF)a.k(b),a=b.C().g,"s"==this.UF?e=c+4.5+a/2:
"e"==this.UF&&(e=c+d-4.5-a/2);a=(0,D.Mb)(e,this.bd+this.ld/2);b.lf();b.Ge();c=this.bd+this.ld/2;c=c>=D.vb?c-D.vb:c;c=0>c?c+D.vb:c;c>0.5*window.Math.PI&&c<1.5*window.Math.PI&&(c+=window.Math.PI);b.Tj(c);(0,D.G)(b,a.x,a.y);b.ia(D.p);a=b}else a=D.n}else{if(0==this.pi)b={x:0,y:0};else if(b=(0,D.Mb)((this.pi+this.Sh)/2,this.bd+this.ld/2),c=3*(0,D.yb)(this)/2,d=(0,D.Qb)(b.x+c/2,b.y),!(0,D.Rb)(this,(0,D.Qb)(b.x-c/2,b.y))||!(0,D.Rb)(this,d))b=D.n;if(b){c=new D.Ia(this.I.e,this.Bz,b.x,b.y,D.n);c.Wf((0,D.yb)(this));
(0,D.Yb)(this,c);c.lf();c.Ge();c.ia(D.p);for(var d=D.Pa.sf(c),f=e=b.x,g=b.y-d.j/2,h=b.y+d.j/2;this.contains(e,g)&&this.contains(e,h);)e--;for(;this.contains(f,g)&&this.contains(f,h);)f++;e+=3;f-=3;b=2*window.Math.min(b.x-e,f-b.x);b<d.g&&(c.ea((e+f)/2),b=f-e);a=D.Pa.Vb(c,b,d.j,a)?c:D.n}else a=D.i}return a};
D.rb.prototype.Xw=function(){if(!this.Jc){var a;a=this.H;if(!a||!(0,D.Bb)(this))a=D.n;else{var b;if(this.Dg){b=this.I.e;var c=this.I.yh,d=new D.Xa(b,c.collapseUp,0,0,16,16),e=new D.Xa(b,c.collapseOver,0,0,16,16),c=new D.Xa(b,c.collapseDown,0,0,16,16)}else b=this.I.e,c=this.I.yh,d=new D.Xa(b,c.expandUp,0,0,16,16),e=new D.Xa(b,c.expandOver,0,0,16,16),c=new D.Xa(b,c.expandDown,0,0,16,16);(0,D.La)(d);(0,D.La)(e);(0,D.La)(c);b=new D.Na(b,d,e,c);b.U(D.Cb,this.x5,D.p,this);d=(0,D.Mb)(this.Sh,this.bd+this.ld/
2);(0,D.G)(b,d.x-8,d.y-8);a.k(b);a=this.Dg?this.I.yh.collapse:this.I.yh.expand;this.I.Ua().ka(b,new D.Zb(this,this.getId(),a));a=b}this.Jc=a}D.rb.o.Xw.call(this)};D.rb.prototype.Uq=function(){this.Jc&&this.H&&(this.H.removeChild(this.Jc),this.Jc=D.n);D.rb.o.Uq.call(this)};
D.Pb=function(a,b){if(a.H){var c=(0,D.Sb)(a);a.H.Ek(c);if(a.Bf||!(0==a.pi&&a.ld==D.vb))a.Ya&&a.H.removeChild(a.Ya),a.Ya=a.tK(a.H),a.dp&&(a.H.removeChild(a.dp),a.dp=D.n);a.H.J(a.mE());if(b)for(var c=a.ub(),d=0;d<c.length;d++)(0,D.Pb)(c[d],D.k)}};
D.rb.prototype.x5=function(){this.Dg=!this.Dg;var a=this.I,b=this.Dg,c=this.getId();a.CL=c;if(b)a.Wa(new D.sb("sunburstExpand",this.getId()));else{var b=a.WX,c=this.getId(),c=b.indexOf('\x3cn id\x3d"'+c),d=b.indexOf("\x3e",c),e=b.substring(c,d),e=-1<e.indexOf("di\x3d")?e.replace('di\x3d"t"','di\x3d"f"'):e+'di\x3d"f"';a.L(b.substring(0,c)+e+b.substring(d),a.pb,a.Cb);a.Wa(new D.sb("sunburstCollapse",this.getId()))}this.$j()};D.rb.prototype.Za=(0,D.w)("Dg");
D.kb=function(a){return a.mk!=D.n?(0,window.Number)(a.mk):a.Bf?1:a.VE?0.25:a.xM?1:0.5};D.rb.prototype.vc=function(){var a=[];this.$b()&&a.push((0,D.ob)(this.jd,this.Ma()?"STATE_SELECTED":"STATE_UNSELECTED"));(0,D.Bb)(this)&&a.push((0,D.ob)(this.jd,this.Za()?"STATE_EXPANDED":"STATE_COLLAPSED"));return(0,D.$b)(this.Ey,a,this.jd)};D.rb.prototype.$j=function(){!(0,D.ac)()&&this.H&&(0,D.Oa)(this.H,"label",this.vc())};
D.jb={};D.y.l(D.jb,D.y,"DvtSunburstLayout");D.jb.io=function(a,b,c,d,e){var f=D.jb.Nca(b);D.jb.cg(a/f,b,c,d,e,0)};D.jb.cg=function(a,b,c,d,e,f){var g=f+(0,D.kb)(b)*a;b.mO(f,g,c,d);f=b.ub();if(f!=D.n&&b.Za()){"on"==e&&(f=f.slice(0),f.sort(function(a,b){return b.yc()-a.yc()}));(0,D.C)(b.I.e)&&(f=f.slice(0).reverse());var h=0;for(b=0;b<f.length;b++)h+=0<f[b].yc()?f[b].yc():0;for(b=0;b<f.length;b++){var j=f[b];if(!(0>=j.yc())){var l=j.yc()/h*d;D.jb.cg(a,j,c,l,e,g);c+=l}}}};
D.jb.Nca=function(a){var b=0,c=a.ub();if(c&&0<c.length){for(var d=0;d<c.length;d++)var e=D.jb.Nca(c[d]),b=window.Math.max(b,e);return b+(0,D.kb)(a)}return(0,D.kb)(a)};
D.sb=function(a,b){this.Init(a);this.Oa=b?b:D.n};D.y.l(D.sb,D.tb,"DvtSunburstExpandCollapseEvent");D.sb.prototype.getId=(0,D.w)("Oa");
D.fc=function(a,b,c,d){D.ec.call(this,a,b,c,d)};D.y.l(D.fc,D.ec,"DvtSunburstEventManager");D.x=D.fc.prototype;D.x.xl=function(a){var b=this.ma(a.target);b&&b.getId&&"_rotationShape"==b.getId()&&!this.rQ?(this.rQ=D.k,a=(0,D.gc)(this.e,a.pageX,a.pageY),b=this.I,(0,D.hc)(b,(0,D.ic)(b,a.x,a.y))):D.fc.o.xl.call(this,a)};D.x.Lp=function(a){if(this.rQ){a=(0,D.gc)(this.e,a.pageX,a.pageY);var b=this.I;(0,D.jc)(b,(0,D.ic)(b,a.x,a.y))}else D.fc.o.Lp.call(this,a)};
D.x.un=function(a){this.rQ?(this.rQ=D.p,(0,D.lc)(this.I)):D.fc.o.un.call(this,a)};D.x.rm=function(a){var b=D.k,c=a.keyCode,d=this.Ie(),e=this.I;(0,D.Bb)(d)&&((0,D.mc)(a)&&!d.Za()||(0,D.nc)(a)&&d.Za()||a.ctrlKey&&13==c)?(d.x5(),a.preventDefault()):e&&"on"==e.Cia&&(37==c||39==c)&&!a.ctrlKey&&a.altKey&&a.shiftKey?(c=37==c?-5*(window.Math.PI/180):5*(window.Math.PI/180),(0,D.hc)(e,0),(0,D.jc)(e,c),(0,D.lc)(e),a.preventDefault()):b=D.fc.o.rm.call(this,a);return b};
D.x.qE=function(a){var b=this.ma(a.target);b&&(b.getId&&"_rotationShape"==b.getId())&&(0,D.oc)(a,this.Dqa,this)};D.x.dP=function(a){(0,D.pc)(this.Qb,a,"rotateKey")};D.x.cP=function(a){(0,D.qc)(this.Qb,a,"rotateKey")};D.x.Dqa=function(a,b){if(1>=(0,D.rc)(this.Qb,"rotateKey").length){(0,D.sc)(this.Qb,b.identifier,"rotateKey","rotateKey","rotateKey",this.Cqa,this.Bqa,this);(0,D.tc)(this.Qb,b.identifier,D.p);var c=(0,D.gc)(this.e,b.pageX,b.pageY),d=this.I;(0,D.hc)(d,(0,D.ic)(d,c.x,c.y));a.Hz()}};
D.x.Cqa=function(a,b){var c=(0,D.gc)(this.e,b.pageX,b.pageY),d=this.I;(0,D.jc)(d,(0,D.ic)(d,c.x,c.y));a.preventDefault()};D.x.Bqa=function(){(0,D.lc)(this.I)};
D.nb=(0,D.s)();D.y.l(D.nb,D.wa,"DvtSunburstBundle");D.nb._defaults={COLOR:"Color",SIZE:"Size"};D.nb.prototype.ej=function(a){var b=D.nb.o.ej.call(this,a);return b?b:D.nb._defaults[a]};D.nb.prototype.kr=(0,D.ca)("DvtSunburstBundle");
D.cc=function(){this.Init({skyros:D.bc,alta:{}})};D.y.l(D.cc,D.dc,"DvtSunburstDefaults");D.bc={rotation:"on"};
D.lb=(0,D.s)();D.y.l(D.lb,D.mb,"DvtSunburstJsonUtils");D.x=D.lb.prototype;D.x.VO=(0,D.ca)("sunburst");D.x.wJ=function(a){var b=D.lb.o.wJ.call(this,a),b=b+this.Ea("r",a.rotation),b=b+this.Ea("sa",(a.startAngle+360)%360);a=a.animationOnDisplay;return b="auto"==a?b+this.Ea("adi","fan"):b+this.Ea("adi",a)};
D.x.xJ=function(a,b){var c=D.lb.o.xJ.call(this,a,b),c=c+this.Ea("ld",b.labelDisplay?b.labelDisplay:a.nodeDefaults.labelDisplay),d=b.labelHalign?b.labelHalign:a.nodeDefaults.labelHalign;"inner"==d?c+=this.Ea("ha","s"):"outer"==d&&(c+=this.Ea("ha","e"));d=b.radius;d!=D.n&&!(0,window.isNaN)(d)&&(c+=this.Ea("r",d));return c};
D.x.cZ=function(a){var b,c=new D.nb;b="\x3cresources"+this.Ea("legendSize",(0,D.ob)(c,"SIZE"));b+=this.Ea("legendColor",(0,D.ob)(c,"COLOR"));b+=this.Ea("cursorRotate",a._resources.rotateCursor);b+=this.Ea("alta","true");return b+"/\x3e\n"};
D.x.yJ=function(a){var b=D.lb.o.yJ.call(this,a),c=a.animationUpdateColor;c&&(b+=this.Ea("top","-tr-animation-update-color: "+c));(c=a.nodeDefaults.borderColor)&&(b+=this.Ea("node","border-color: "+c));(c=a.nodeDefaults.hoverColor)&&(b+=this.Ea("node-hover","border-color: "+c));(a=a.nodeDefaults.selectedColor)&&(b+=this.Ea("node-selected","border-color: "+a));return b+"/\x3e\n"};
});