"use strict";
define(['./DvtToolkit', './DvtPanZoomCanvas', './DvtSubcomponent'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.lC=function(a,b,c){this.Init(a,b,c)};(0,D.ra)("DvtAmxThematicMap",D.lC);D.y.l(D.lC,D.I,"DvtAmxThematicMap");D.lC.Vx=10;D.lC.prototype.Init=function(a,b,c){D.lC.o.Init.call(this,a);this.fa=new D.Ud(a,b,c);this.OT=new D.I(a);this.OT.k(this.fa);this.k(this.OT);this.vf=new D.ee};D.lC.newInstance=function(a,b,c){return new D.lC(a,b,c)};D.lC.newInstance=D.lC.newInstance;D.lC.prototype.L=function(a,b,c){this.M=this.vf.ah(a);this.T=b;this.Y=c;b=new D.N(0,0,b,c);this.dM(this,b);this.fa.L(a,b.g,b.j)};
D.lC.prototype.render=D.lC.prototype.L;
D.lC.prototype.dM=function(a,b){this.Ba&&(a.removeChild(this.Ba),this.Ba=D.n);var c=new D.N(D.lC.Vx,D.lC.Vx,b.g-2*D.lC.Vx,b.j-2*D.lC.Vx),d=this.M,e=d.legend.rendered,f=d.legend.scrolling,g=D.Sa.clone(d.legend);this.BZ(this.M,g);if(e&&!(g.XGa&&0==g.XGa.length)){e=d.legend.position;delete g.position;g.layout.gapRatio=(0,D.mC)(this);g.hideAndShowBehavior="none";g.rolloverBehavior="none";g.scrolling=d.legend.scrolling;var h=(0,D.ib)(this.fa.e,D.n,D.n);this.fa.getId()!=D.n&&h.setId(this.fa.getId()+"legend");
a.k(h);"auto"==e&&"asNeeded"!==f?e="bottom":"auto"==e&&"asNeeded"==f&&(e="end");f=(0,D.C)(a.e);"start"==e?e=f?"right":"left":"end"==e&&(e=f?"left":"right");g.orientation="left"==e||"right"==e?"vertical":"horizontal";f="top"==e||"bottom"==e;f=h.Sw(g,f?c.g:d.layout.legendMaxSize*c.g,f?d.layout.legendMaxSize*c.j:c.j);if(0<f.g&&0<f.j)switch(h.L(g,f.g,f.j),this.Ba=h,d=window.Math.ceil(d.layout.legendGap*(0,D.mC)(this)),(0,D.yi)(c,e,h,f.g,f.j,d),e){case "top":this.OT.O(f.j+D.lC.Vx);case "bottom":b.j-=f.j+
D.lC.Vx;break;case "left":this.OT.F(f.g+D.lC.Vx);case "right":b.g-=f.g+D.lC.Vx}}};D.mC=function(a){if(a.M.layout.gapRatio!==D.n&&!(0,window.isNaN)(a.M.layout.gapRatio))return a.M.layout.gapRatio;var b=window.Math.min(a.T/400,1);a=window.Math.min(a.Y/300,1);return window.Math.min(b,a)};
D.lC.prototype.BZ=function(a,b){b.title=a.legend?a.legend.title:D.n;b.sections=[];if(a&&a.legend&&a.legend.sections)for(var c=0;c<a.legend.sections.length;c++){var d=a.legend.sections[c];d&&b.sections.push({title:d.title,items:d.items,sections:d.sections})}return b};
D.Ud=function(a,b,c){this.Init(a,b,c)};(0,D.ra)("DvtThematicMap",D.Ud);D.y.l(D.Ud,D.Rt,"DvtThematicMap");
D.Ud.prototype.Init=function(a,b,c){D.Ud.o.Init.call(this,a,b,c);(0,D.aC)(this);this.Af=[];this.Cv=[];this.xxa=this.Lt=this.oc=this.Ba=D.n;this.RZ=D.p;this.LK=[];this.bL={};this.eT=D.p;this.rR={};this.I_={};this.Fm=[];this.MZ=new D.I(this.e);this.vK=new D.I(this.e);this.yv=new D.I(this.e);this.Kt=new D.I(this.e);this.sG=this.QC=this.q1=D.p;this.g2=6;this.Vv=D.k;this.MG={};this.YZ=D.p;this.Rc=D.n;this.Ll=16777215;this.vf=new D.ee;this.Ca.ka(this,this);this.Zf=D.p};
D.Ud.newInstance=function(a,b,c){return new D.Ud(a,b,c)};D.Ud.prototype.ge=function(a){D.Ud.o.ge.call(this,a);(0,D.yp)()||(this.M.animationOnDisplay="none",this.M.animationOnMapChange="none",this.M.animationOnDrill="none");(new D.sd(this)).parse(this.M)};D.bC=function(a,b){for(var c=0;c<a.Af.length;c++)if(a.Af[c].mg==b)return a.Af[c]};D.x=D.Ud.prototype;D.x.Ds=function(a){this.ht=(0,window.parseFloat)(a)};D.x.Qa=(0,D.w)("ht");
D.x.nW=function(a){a=(0,window.parseInt)(a);var b=this.Ll;if(1==a||3==a||5==a||7==a)b&=-17,this.sG=D.p;if(2==a||3==a||6==a||7==a)b&=-4098,this.QC=D.p;if(4==a||5==a||6==a||7==a)b&=-257;this.Ll=b};D.x.p8=function(a){this.Wk=a;this.Ca.p8(a)};
D.x.pJ=function(){D.Ud.o.pJ.call(this);!this.Qy&&this.Hya&&(this.Af=[],this.LK=[],this.bL={},this.rR={},this.I_={},this.Fm=[],this.removeChild(this.oc),this.xxa=this.Lt=this.Ba=this.oc=D.n,this.Ll=16777215,this.sG=this.QC=D.k,this.kG=this.Rb,this.MZ=new D.I(this.e),this.vK=new D.I(this.e),this.yv=new D.I(this.e),this.Kt=new D.I(this.e),this.Rc=D.n,this.Ca.Bs(this),(0,D.aC)(this),this.Ca.zc(),this.Ca.ka(this,this))};
D.aC=function(a){a.Ca=new D.Ic(a.e,a.Wa,a);a.Ca.Df(a);(0,D.Qa)()?a.C1=D.n:(a.C1=new D.Vd(a,a.Ca),(0,D.gk)(a.Ca,a.C1))};D.x=D.Ud.prototype;D.x.Apa=function(a){(0,D.C)(this.e)||(a=this.T-5-a.getWidth(),this.oc.F(a))};
D.x.dM=function(){if(this.Lt){this.oc&&(this.oc.S(),this.removeChild(this.oc));var a="true"==this.Lt.disclosed,b="fixed"==this.Lt.display||(0,D.Dy)();if(!b||a){var c=this.Lt.maxWidth,d=c.indexOf("%"),c=-1!=d?(0,window.parseFloat)(c.substring(0,d))/100*this.T:(0,window.parseFloat)(c),d=this.Y-10;if("alta"==this.Kb)this.oc=new D.Sc(this.e,D.n,this,"pd"),this.oc.U("dvtPanelDrawerEvent",this.l$,D.p,this),this.oc.mm(c),this.oc.TD(d),this.oc.Tv=b,(0,D.C)(this.e)?(this.oc.Jr="right",this.oc.F(0)):this.oc.F(this.T);
else{var e=(0,D.C)(this.e)?"col_northwest":"col_northeast";this.oc=new D.Qc(this.e,c,d,e,(0,D.qe)(this),this.ts(),a,b);this.oc.U("dvtCollapsiblePanelEvent",this.l$,D.p,this);this.oc.U("dvtResizeEvent",this.Apa,D.p,this);c=this.oc;d=this.Lt.collapseTooltip;c.EB=this.Lt.expandTooltip;c.qB=d}this.Ba=new D.DvtCommonLegend(this.e,this.oc.l6(),this.oc.k6(),(0,D.qe)(this),this.Kb);this.Ba.oW(this.Lt);this.k(this.oc);this.k(this.Ba);this.Ba.L();var f;if("alta"==this.Kb){c=this.Ba.C();(0,D.ku)(this.oc,c.j);
this.removeChild(this.Ba);var c=new D.Xa(this.e,(0,D.qe)(this).legendEna,0,0,24,24),d=new D.Xa(this.e,(0,D.qe)(this).legendOvr,0,0,24,24),e=new D.Xa(this.e,(0,D.qe)(this).legendDwn,0,0,24,24),g=(0,D.ob)(this.jc(),"LEGEND");(0,D.Of)(this.oc,this.Ba,c,d,e,g,"legend");this.oc.jn();a&&this.oc.Pe(D.k,D.k)}else f=this.oc,a=this.Ba,f.ad.k(a),a.U("dvtResizeEvent",f.IX,D.p,f),c=f.ad.C(),a=c.g+10,c=c.j+10,f.Y=c,f.T=a,f.$a?(f.$a.Ek((0,D.cC)(f,a,c)),a="col_northwest"==f.Li||"col_southwest"==f.Li,f.Ag&&a&&f.Ag.F(f.T)):
(a=new D.Tb(f.e,(0,D.cC)(f,a,c)),c=f.D.borderAlpha,a.qa(f.pv,f.ek),a.La(f.Tp,c),f.$a=a,f.Ha(f.$a,0),f.Tv||(f.Ag=D.Bt.g5(f.e,25,f.D,D.p),f.Ag.B(f.D.borderAlpha),f.k(f.Ag),f.gk=f.isCollapsed()?D.R.pU(f.e,f.Il,25,f.D,D.p):D.R.nU(f.e,f.Il,25,f.D,D.p),f.Ag.k(f.gk),"col_northwest"==f.Li||"col_southwest"==f.Li||(f.Ag.O(25),f.Ag.Tj(-window.Math.PI)),(0,D.C)(f.e)&&f.Ag.F(f.T),(0,D.Qa)()?f.gk.U(D.Wv.Ce,f.vE,D.p,f):(f.gk.U(D.Cb,f.vE,D.p,f),f.gk.U(D.Yq,f.gY,D.p,f),f.gk.U(D.Zq,f.fY,D.p,f)))),f.IQ&&(0,D.dC)(f,
D.p),f=this.oc.C(),a=(0,D.C)(this.e)?5:this.T-5-f.g-f.x,(0,D.G)(this.oc,a,5),f.g+=5;if(this.xfa=b)f||(f=this.oc.C()),this.N1=f.g,this.Rb.dj(this.T-this.N1,this.Y,D.k)}}};
D.x.Fi=function(){D.Ud.o.Fi.call(this);var a=new D.I(this.e),b=new D.I(this.e);this.Rb=this.ba;this.Rb.k(a);this.Rb.X.k(b);this.Th(a,b);if(this.Aj){(this.Ic=this.Rb.Ic)&&this.Rb.k(this.Ic);(0,D.eC)(this);var c=new D.N(0,0,this.T,this.Y);if(!this.Zf&&!this.kG)D.cg.isSupported(this.dca)&&(this.yb=D.cg.KH(this.e,this.dca,this.Rb,c,this.ht));else{var d=D.n;if(this.RZ&&!this.Qy)d=this.Lta;else if(this.Aj&&this.Aj.mg!=this.dya&&(d=this.Aj.os(),!d)){var e=this.Aj.ci,f;for(f in e)if(e[f].os()){d=e[f].os();
break}}d&&D.cg.isSupported(d)?(this.yb=D.cg.EH(this.e,d,this.kG,this.Rb,c,this.ht))&&this.k(this.kG):(this.Rb.X.removeChild(this.hF),this.Kp())}this.yb&&(this.Ic&&this.k(this.Ic),this.Ca.zc(),this.Ca.Bs(this),this.YZ=D.k,this.yb.Md(this.Kp,this),this.yb.play(D.k));this.Hya=a;this.hF=b;this.Aj&&(this.dya=this.Aj.mg);this.Zf=D.k}};
D.x.Th=function(a,b){this.dM();b.k(this.MZ);b.k(this.vK);this.Vv?a.k(this.yv):b.k(this.yv);a.k(this.Kt);var c=this.Rb.X.na();this.y4=D.p;for(var d=0;d<this.Af.length;d++){var e=this.Af[d];if(!this.y4&&e instanceof D.uc||!(e instanceof D.uc))e.L(c),!this.y4&&e instanceof D.uc&&(this.y4=D.k,this.Aj=e)}this.Aj&&(c=(0,D.Zd)(this),0==c.length&&(c=(0,D.rd)(this)),this.C1&&(c=c[0])&&D.Ic.o.Fs.call(this.Ca,c),this.Rb.Is(D.n),this.Rb.Lu(D.n),this.Rb.Sp=D.k,this.Rb.ji=D.k,!this.RZ&&!this.Qy&&this.pfa!=D.n?
((0,D.ds)(this.Rb,this.pfa),(0,D.wu)(this.Rb,this.axa,this.bxa)):this.Rb.oo(D.n,this.Aj.bD()),(0,D.ae)(this),c=this.Rb.jp,d=this.Aj.bD(),e=this.Rb.yc(),c=window.Math.min((e.g-2*c)/d.g,(e.j-2*c)/d.j),this.Rb.Is(c),this.Rb.Lu(c*(this.QC?this.g2:1)),this.Rb.Sp=this.QC,this.Rb.ji=this.sG)};D.x.u8=(0,D.v)("EG");D.fC=function(a,b){var c=new D.jd;c.translate(b.Bb,b.xb);a.Vv&&a.yv.sa(c);a.Kt.sa(c)};D.Ud.prototype.l$=function(a){var b=new D.sf;(0,D.Lc)(b,D.DvtCommonLegend.T$,"show"==a.Wi());this.Wa(b)};
D.gC=function(a,b,c){if(b=b.R){var d=a.Rb.X,e=(0,D.pq)(b,d,d.na);c&&(a.xda=d.na(),(0,D.T)(b,"typeMatrix",a,a.Rva,a.Jza,e));c=new D.jd(1,0,0,1,e.Bb,e.xb);a.Vv&&(0,D.T)(b,"typeMatrix",a.yv,a.yv.na,a.yv.sa,c);(0,D.T)(b,"typeMatrix",a.Kt,a.Kt.na,a.Kt.sa,c)}};
D.Ud.prototype.Rg=function(a){switch(a.Wi()){case "adjustPanConstraints":if(this.sG){var b=a.cz;a=this.Rb.jp;var c=this.Rb.yc();a=new D.N(a,a,c.g-2*a,c.j-2*a);var d=this.Aj.bD(),e=d.x*b,c=d.y*b,f=d.g*b,b=d.j*b,d=0;f>a.g?(this.xfa&&(0,D.C)(this.e)&&(d=this.N1),this.Rb.pq=a.x+a.g+d-(e+f),this.Rb.nq=a.x-e+d):(this.xfa&&(0,D.C)(this.e)&&(d=2*this.N1),e=(a.x+a.g+d)/2-(e+f/2),this.Rb.pq=e,this.Rb.nq=e);b>a.j?(this.Rb.qq=a.y+a.j-(c+b),this.Rb.oq=a.y-c):(a=(a.y+a.j)/2-(c+b/2),this.Rb.qq=a,this.Rb.oq=a)}break;
case "zooming":case "elasticAnimBegin":(0,D.gC)(this,a,D.k);break;case "zoomed":if(a.cz!=D.n){c=this.Rb.X.na();(0,D.Lc)(a,"panX",c.Bb);(0,D.Lc)(a,"panY",c.xb);a.R=D.n;this.Wa(a);(0,D.fC)(this,c);for(b=0;b<this.Af.length;b++)this.Af[b].Rg(a,c)}break;case "zoomAndCenter":(0,D.Vc)(this);break;case "zoomToFitEnd":this.Wa(new D.jB)}};
D.Ud.prototype.Us=function(a){var b=a.Wi();if("elasticAnimBegin"==b)(0,D.gC)(this,a,D.p);else if("panned"==b&&a.Sga!=D.n){var c=this.Rb.X.na();(0,D.Lc)(a,"zoom",this.Rb.Fc());(0,D.Lc)(a,"panX",c.Bb);(0,D.Lc)(a,"panY",c.xb);a.R=D.n;this.Wa(a);(0,D.fC)(this,c);for(a=0;a<this.Af.length;a++)this.Af[a].Us(c)}this.oc&&("alta"==this.Kb?"dragPanBegin"===b?this.oc.ia(D.p):"dragPanEnd"===b&&this.oc.ia(D.k):(c=this.ts(),a=this.oc.$a.rc().clone(),"dragPanBegin"===b?(this.Ba.B(c.backgroundDragAlpha),a.B(c.borderDragAlpha),
this.oc.$a.W(a),this.oc.Ag&&this.oc.Ag.B(c.borderDragAlpha),this.oc.ia(D.p)):"dragPanEnd"===b&&(this.Ba.B(1),a.B(c.borderAlpha),this.oc.$a.W(a),this.oc.Ag&&this.oc.Ag.B(c.borderAlpha),this.oc.ia(D.k))))};D.Ud.prototype.Ex=function(){return"none"==this.Wk&&!this.QC&&(!this.sG||"alta"==this.Kb)?"hidden":D.Ud.o.Ex.call(this)};D.Ud.prototype.WO=function(){var a=this.Ex();return"hidden"!=a?new D.le(this.e,this,"initCollapsed"==a?1:2):D.n};
D.ae=function(a){a.eT=D.k;for(var b=0;b<a.Af.length;b++){var c=a.Af[b].mg;c in a.bL&&(a.MG[c]=a.bL[c][1],a.fk=c,a.tv=a.bL[c][0],a.uU())}a.eT=D.p};
D.Ud.prototype.d8=function(){(0,D.eC)(this);for(var a=[],b=[],c=this.Af.length-1;-1<c;c--)this.Af[c].mg==this.Aj.mg?this.Af[c].reset(b):this.Af[c].reset(a);for(c=0;c<a.length;c++)if(a[c]){var d=a[c].getParent();d&&d.removeChild(a[c])}for(c=0;c<b.length;c++)b[c]&&b[c].B(1);this.LK=[];a=new D.fm(this.e,0.3);this.Rb.oo(a);a.play(D.k);this.Fm=[];this.Ic&&"none"!=this.Wk&&((0,D.re)(this.Ic,D.p),(0,D.se)(this.Ic,D.p))};
D.be=function(a){var b=a.vK.C(),c=a.yv.C();if(a.Vv){var d=a.Rb.X.na();c.g/=d.Qd;c.j/=d.Qe;c.x/=d.Qd;c.y/=d.Qe}b=(0,D.Ac)(b,c);(0,D.eC)(a);(0,D.yp)()&&(a.yb=new D.fm(a.e,0.3));0<b.g&&0<b.j?a.Rb.oo(a.yb,b):a.Rb.oo(a.yb,a.Aj.bD());a.yb&&a.yb.play(D.k)};D.Ud.prototype.mH=function(a){var b=new D.fm(this.e,0.3);this.Rb.oo(b,a);b.play(D.k)};
D.Vc=function(a){if(a.tv){var b=(0,D.bC)(a,a.fk).jl(a.tv);if(b&&(b=b.Mb)){for(var b=b.getSelection(),c=0;c<b.length;c++)b[c]=b[c].ra();if(0<b.length){for(var d=b[0].C(),c=1;c<b.length;c++)d=(0,D.Ac)(d,b[c].C());a.mH(d)}}}};D.hC=function(a,b){var c=D.zc.HDa(a.qi,b);return(0,D.bC)(a,c)};D.Gc=function(a,b){var c=D.zc.Nka(a.qi,b);return(0,D.bC)(a,c)};D.Zd=function(a){var b=[];if(a.Aj)for(var c=0;c<a.Af.length;c++){var d=a.Af[c].ci,e;for(e in d)b=a.Aj.mg==a.Af[c].mg?b.concat((0,D.cd)(d[e])):b.concat((0,D.dd)(d[e]))}return b};
D.rd=function(a){var b=[];if(a.Aj)for(var c=0;c<a.Af.length;c++){var d=a.Af[c].ci;if(a.Aj.mg==a.Af[c].mg||!(a.Af[c]instanceof D.uc))for(var e in d)b=b.concat(d[e].li)}return b};D.Ud.prototype.Jza=function(a){this.xda=a;if(this.Vv){for(var b=(0,D.rd)(this),c=0;c<b.length;c++)b[c].Rg(a);b=this.Kt.ua();for(c=0;c<b;c++)for(var d=this.Kt.aa(c),e=d.ua(),f=0;f<e;f++){var g=d.aa(f);g instanceof D.Cc&&g.update(a)}}};D.Ud.prototype.Rva=(0,D.w)("xda");
D.Ud.prototype.uU=function(){(0,D.eC)(this);var a=(0,D.Gc)(this,this.fk),b=(0,D.bC)(this,this.fk),c=[];if(a){this.rR[this.fk]=this.tv;var d=this.MG[this.fk];!this.eT&&"single"==this.Wk&&(this.Fm.pop(),b.reset(c,d),a.reset(this.Cv));for(var e=[],f=0;f<d.length;f++){var g=d[f],h=(0,D.yc)(b,g);e.push(h[0]);for(var j=0;j<h.length;j++)this.I_[h[j]]=d[f];a.r5(h,c);if(h=b.jl(this.tv)){for(var j=g,l=this.Cv,m=0;m<h.mc.length;m++)if(h.mc[m].tl==j){h.mc[m].uI(D.k);h.Fm.push(j);l.push(h.mc[m].ra());if(m=h.mc[m].Of())l.push(m),
(m=m.jk)&&l.push(m);break}for(m=0;m<h.li.length;m++)if(h.li[m].tl==j){l.push(h.li[m].ra());break}}this.Fm.push(g)}(0,D.iC)(this,this.Cv,c,D.p);(0,D.jC)(this,a.mg);this.fk=a.mg;this.MG[this.fk]=e}};
D.Ud.prototype.s5=function(){(0,D.eC)(this);for(var a=(0,D.bC)(this,this.fk),b=(0,D.hC)(this,this.fk),c=[],d=[],e=this.MG[this.fk],f=0;f<e.length;f++){var g=this.I_[e[f]];d.push(g);if(-1!=D.Hc.Fa(this.Fm,g)){a.AO((0,D.yc)(b,g),this.Cv);for(var h=b.jl(this.rR[b.mg]),j=g,l=c,m=0;m<h.mc.length;m++)if(h.mc[m].tl==j){h.Fm.splice(D.Hc.Fa(h.Fm,j),1);h.mc[m].uI(D.p);var o=h.mc[m].ra();h.Dn.k(o);l.push(o);if(m=h.mc[m].Of())m.update(h.yG),l.push(m),l.push(m.jk);break}for(m=0;m<h.li.length;m++)if(h.li[m].tl==
j){o=h.li[m].ra();h.st.k(o);l.push(o);break}g=D.Hc.Fa(this.Fm,g);-1!=g&&this.Fm.splice(g,1)}}(0,D.iC)(this,this.Cv,c,D.k);this.fk=b.mg;this.tv=this.rR[this.fk];this.MG[this.fk]=d;(0,D.jC)(this,this.fk)};D.eC=function(a){a.yb&&(a.yb.stop(D.k),a.yb=D.n)};
D.iC=function(a,b,c,d){a.Rb.X.na();if("zoomToFit"==a.JZ&&!a.eT){var e=new D.fm(a.e,0.3);(0,D.yp)()||(e=D.n);d?a.Rb.oo(e):(0,D.Vc)(a);e&&e.play(D.k)}(0,D.eC)(a);(0,D.yp)()&&"alphaFade"==a.JZ&&(a.yb=D.cg.EH(a.e,a.JZ,b,c,D.n,0.5));a.yb?(a.Ca.zc(),a.Ca.Bs(a),a.yb.Md(a.rqa,a),a.yb.play(D.k)):(0,D.kC)(a)};
D.Ud.prototype.Wa=function(a){var b=a.Ga();if("selection"==b)if(this.tv){this.M3=a.getSelection();for(var b=this.MG,c=this.fk,d=this.M3,e=[],f=(0,D.bC)(this,this.fk).jl(this.tv).mc,g=0;g<d.length;g++)for(var h=0;h<f.length;h++)if(f[h].getId()==d[g]){e.push(f[h].tl);break}b[c]=e;(0,D.jC)(this,this.fk);(0,D.Lc)(a,"clientId",this.tv);this.HQ&&!(this.HQ instanceof D.Ed)&&(this.Hja=this.HQ)}else(0,D.jC)(this,D.n),this.Hja=D.n;else b==D.Pc.Saa?((0,D.Lc)(a,"clientId",this.wF),this.LK="multiple"==this.Wk?
this.LK.concat(this.M3):this.M3,b=a.Bva,b==D.Pc.Roa&&this.s5(),b==D.Pc.dX?this.uU():b==D.Pc.yqa&&this.d8(),a.Pe(this.LK)):("showPopup"==b||"hidePopup"==b)&&(0,D.Lc)(a,"clientId",this.wF);D.Ud.o.Wa.call(this,a)};D.jC=function(a,b){if(a.Ic&&a.Wk&&"none"!=a.Wk){var c=(0,D.Gc)(a,b),d=(0,D.hC)(a,b);c?(0,D.re)(a.Ic,D.k):(0,D.re)(a.Ic,D.p);d?(0,D.se)(a.Ic,D.k):(0,D.se)(a.Ic,D.p)}};D.Ud.prototype.S=function(){D.Ud.o.S.call(this);this.Ca&&(this.Ca.S(),this.Ca=D.n)};D.Ud.prototype.destroy=D.Ud.prototype.S;
D.Ud.prototype.Kp=function(){this.Ic&&this.Rb.k(this.Ic);this.kG&&(this.removeChild(this.kG),this.kG=D.n);this.yb=D.n;this.q1&&(0,D.be)(this);this.YZ&&(this.Ca.Df(this),this.YZ=D.p)};D.Ud.prototype.rqa=function(){(0,D.kC)(this);this.yb=D.n;this.Ca.Df(this)};D.kC=function(a){if(0<a.Cv.length){for(var b=0;b<a.Cv.length;b++){var c=a.Cv[b];if(c)if(c instanceof D.Cc)c.reset();else if(c.uu&&c.uu())c.B(0);else{var d=c.getParent();d&&d.removeChild(c)}}a.Cv=[]}};D.x=D.Ud.prototype;
D.x.qT=function(a){this.zR("mouseover"==a.Nga?"categoryRollOver":"categoryRollOut",a.b6())};D.x.zR=function(a,b){var c=new D.Wk(a,b),d=[],e;for(e in this.rh)for(var f in this.rh[e])d.push(this.rh[e][f]);for(e in this.$v)for(f in this.$v[e])d.push(this.$v[e][f]);e=this.Ba.c1;for(var g in e)f=new D.ue(e[g].je(),g),d.push(f);(0,D.Uh)(c,d,0.1)};D.x.zd=(0,D.w)("Rc");D.x.uA=(0,D.v)("Rc");D.x.Vh=function(){this.hr||(this.hr=new D.ve(this));return this.hr};D.Ud.prototype.getAutomation=D.Ud.prototype.Vh;
D.ee=function(){this.Init({fusion:D.ce,alta:D.de})};D.y.l(D.ee,D.Aa,"DvtThematicMapDefaults");
D.ce={animationDuration:500,animationOnDisplay:"none",animationOnDrill:"none",animationOnMapChange:"none",controlPanelBehavior:"hidden",drilling:"none",initialZooming:"none",markerZoomBehavior:"fixed",panning:"none",tooltipDisplay:"auto",visualEffects:"none",zooming:"none",styleDefaults:{skin:"alta",areaStyle:"background-color:#B8CDEC;border-color:#FFFFFF;",dataAreaDefaults:{borderColor:"#FFFFFF",drilledInnerColor:"#FFFFFF",drilledOuterColor:"#000000",hoverColor:"#FFFFFF",opacity:1,selectedInnerColor:"#FFFFFF",
selectedOuterColor:"#000000"},dataMarkerDefaults:{borderColor:"#FFFFFF",borderStyle:"solid",borderWidth:"0.5px",color:"#000000",height:8,labelStyle:"font-family:Tahoma;font-size:13pt;color:#000000",opacity:0.4,scaleX:1,scaleY:1,shape:"circle",width:8},labelStyle:"font-family:Tahoma;font-size:11pt;"},legend:{position:"auto",rendered:D.k,layout:{gapRatio:1}},layout:{gapRatio:D.n,legendMaxSize:0.3,legendGap:10},resources:{images:{},translations:{}}};
D.de={styleDefaults:{areaStyle:"background-color:#DDDDDD;border-color:#FFFFFF;",dataAreaDefaults:{drilledOuterColor:"#0572CE"},dataMarkerDefaults:{color:"rgb(51,51,51)",labelStyle:'font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;font-size:12px;color:#333333',opacity:1},labelStyle:'font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;font-size:12px;'}};D.ud={animationOnLayerChange:"none",labelDisplay:"auto",labelType:"short"};D.zd={animationOnDataChange:"none",selection:"none"};
D.Td=function(a){for(var b=0;b<a.Af.length;b++){var c=a.Af[b].ci,d;for(d in c){var e=c[d].Vk;if(e&&e.BB)return e}}return D.n};D.Ud.prototype.Oj=function(a,b,c){this.tva=D.p;return(a=(0,D.Td)(this))?a.Oj(c):D.p};D.Ud.prototype.kl=function(a,b){var c=(0,D.Td)(this);return c?c.kl(a,b):D.n};

D.wc=function(a,b){this.tIa=a;this.HIa=b};D.y.l(D.wc,D.$d,"DvtThematicMapDropTarget");
D.ve=(0,D.v)("fa");(0,D.ra)("DvtThematicMapAutomation",D.ve);D.y.l(D.ve,D.we,"DvtThematicMapAutomation");
D.ve.prototype.Fp=function(a){a=this.fa.Ca.ma(a);var b;if(a&&(a instanceof D.Bd||a instanceof D.md))a:{for(var c=this.fa.Af,d=0;d<c.length;d++){var e=c[d].ci;for(b in e)if(a instanceof D.Bd)for(var f=e[b].mc,g=0;g<f.length;g++){if(f[g]===a){b=(0,D.xe)(b)+":area["+a.getId()+"]";break a}}else if(a instanceof D.md){f=e[b].li;for(g=0;g<f.length;g++)if(f[g]===a){b=(0,D.xe)(b)+":marker["+a.getId()+"]";break a}}}b=D.n}else b=D.n;return b};
D.ve.prototype.Ij=function(a){var b=a.indexOf(":"),c=a.indexOf("[");a=0<b&&0<c?(a=(0,D.ye)(this,a.substring(0,b),a.substring(b+1,c),a.substring(c+1,a.length-1)))?a.ra().pa():D.n:D.n;return a};D.ve.prototype.getDomElementForSubId=D.ve.prototype.Ij;D.ve.prototype.getData=function(a,b,c){return(a=(0,D.ye)(this,a,b,c))?(b={},b.color=a.tk(),b.tooltip=a.Oe(),c=a.Of(),b.label=c?c.Ze():D.n,b.isSelected=a.Ma(),b):D.n};D.ve.prototype.getData=D.ve.prototype.getData;
D.ye=function(a,b,c,d){a=a.fa.Af;for(var e=0;e<a.length;e++){var f=a[e].ci,g;for(g in f)if((0,D.xe)(g)==b)if("area"==c)for(var h=f[g].mc,j=0;j<h.length;j++){if(h[j].getId()===d)return h[j]}else if("marker"==c){h=f[g].li;for(j=0;j<h.length;j++)if(h[j].getId()===d)return h[j]}}return D.n};D.xe=function(a){var b=a.lastIndexOf(":");return 0<b?a.substring(b+1):a};
D.Wc=function(a,b){this.Init(a,b)};D.y.l(D.Wc,D.Tb,"DvtDrillablePath");D.x=D.Wc.prototype;D.x.Init=function(a,b){D.Wc.o.Init.call(this,a);this.Gy=this.Fy=this.kR=this.jR=D.n;this.cS=D.p;this.Zoom=1;this.yf=b};D.x.uu=(0,D.w)("cS");
D.x.uI=function(a){this.cS!=a&&(this.cS=a,this.uu()?(this.Fy=this.Qi(),this.Fy.J(D.n),this.Fy.ia(D.p),this.Gy=this.Qi(),this.Gy.J(D.n),this.Gy.ia(D.p),a=this.getParent(),a.k(this.Gy),a.k(this.Fy),this.Fy.W((0,D.Xc)(this,this.jR,2)),this.Gy.W((0,D.Xc)(this,this.kR,4)),this.ia(D.p),this.Xs=D.p):(this.bi()&&(this.Ii(),this.Sg.W((0,D.Xc)(this,this.mr,1),2)),this.Gy.getParent().removeChild(this.Gy),this.Fy.getParent().removeChild(this.Fy),this.ia(D.k),this.B(1)))};
D.x.Pb=function(a){this.Hp!=a&&(a&&(this.bi()?(this.OI(),this.yl=(0,D.Xc)(this,this.yl,2),this.Lk=(0,D.Xc)(this,this.Lk,6)):(this.pr=(0,D.Xc)(this,this.pr,1),this.Bo=(0,D.Xc)(this,this.Bo,4))),D.Wc.o.Pb.call(this,a))};D.x.Oc=function(){this.Ma()?(this.OI(),this.yl=(0,D.Xc)(this,this.yl,2),this.Lk=(0,D.Xc)(this,this.Lk,6)):this.mr=(0,D.Xc)(this,this.mr,2);D.Wc.o.Oc.call(this)};
D.x.OI=function(){this.yl||(this.yl=this.mr.clone(),this.yl.ha(2),this.yf&&(this.yl.rd=D.k));this.Lk||(this.Lk=this.Bo.clone(),this.Lk.ha(6),this.yf&&(this.Lk.rd=D.k))};D.x.sc=function(){this.Ma()&&(this.pr=(0,D.Xc)(this,this.pr,1),this.Bo=(0,D.Xc)(this,this.Bo,4));D.Wc.o.sc.call(this)};D.x.Gs=function(a,b){D.Wc.o.Gs.call(this,a,b);this.yf&&(this.mr&&(this.mr.rd=D.k),this.mP&&(this.mP.rd=D.k));return this};
D.x.Ls=function(a,b){D.Wc.o.Ls.call(this,a,b);this.yf&&(this.pr&&(this.pr.rd=D.k),this.Bo&&(this.Bo.rd=D.k));return this};D.x.Mu=function(a,b){D.Wc.o.Mu.call(this,a,b);this.yf&&(this.yl&&(this.yl.rd=D.k),this.Lk&&(this.Lk.rd=D.k));return this};D.Yc=function(a,b,c){if(!a.yf){var d=b.rc();d&&(d=d.clone(),d.ha(c/a.Zoom),b.W(d))}};D.Xc=function(a,b,c){a.yf||(b=b.clone(),b.ha(c/a.Zoom));return b};
D.Zc=function(a,b){a.Zoom=b.Qd;a.uu()?((0,D.Yc)(a,a.Fy,2),(0,D.Yc)(a,a.Gy,4)):a.Ma()?a.bi()?((0,D.Yc)(a,a.Sg,2),(0,D.Yc)(a,a,6)):((0,D.Yc)(a,a.Sg,1),(0,D.Yc)(a,a,4)):a.bi()?(0,D.Yc)(a,a.Sg,2):(0,D.Yc)(a,a,1)};
D.Sd=this?this:window;D.Sd.DvtBaseMapManager?D.zc=D.Sd.DvtBaseMapManager:(D.zc={},D.Sd.DvtBaseMapManager=D.zc);D.y.l(D.zc,D.y,"DvtBaseMapManager");D.zc.DE=0;D.zc.uJ=1;D.zc.UY=2;D.zc.TY=3;D.zc.CP=4;D.zc.ct="__index";D.zc.ph={};D.zc.Ika=function(a,b){D.zc.$o();var c=D.zc.ph[a][b];return c&&(c=c[D.zc.CP])?new D.N(c[0],c[1],c[2],c[3]):D.n};D.zc.eCa=function(a,b){D.zc.$o();var c=D.zc.ph[a][b];return c?c[D.zc.TY]:D.n};D.zc.fCa=function(a,b){D.zc.$o();var c=D.zc.ph[a][b];return c?c[D.zc.DE]:D.n};
D.zc.mDa=function(a,b,c){D.zc.$o();a=D.zc.ph[a][b];var d;a&&(d=a[D.zc.DE]);return d&&d[c]?d[c][1]:D.n};D.zc.wCa=function(a,b){D.zc.$o();var c=D.zc.ph[a];if(c&&(c=c.cities))if(c=c[D.zc.uJ][b])return new D.L(c[0],c[1]);return D.n};D.zc.xCa=function(a,b){D.zc.$o();var c=D.zc.ph[a];if(c&&(c=c.cities))if(c=c[D.zc.DE][b])return c[1];return D.n};
D.zc.cCa=function(a,b,c){D.zc.$o();var d=D.zc.ph[a];if(d&&(d=d[b])){if((d=d[D.zc.TY])&&d[c])return(0,D.Pd)(d[c][0]).de();a=D.zc.ph[a][b][D.zc.uJ][c];if(!a)return D.n;a=D.P.qU(a);return D.P.C(a).de()}return D.n};D.zc.Nka=function(a,b){D.zc.$o();var c=D.zc.ph[a][b];return c?D.zc.ph[a][D.zc.ct][c.__index+1]:D.n};D.zc.HDa=function(a,b){D.zc.$o();return D.zc.ph[a][b]?D.zc.ph[a][D.zc.ct][D.zc.ph[a][b].__index-1]:D.n};D.zc.Eka=function(a,b){D.zc.$o();return D.zc.ph[a][b][D.zc.uJ]};
D.zc.IDa=function(a,b,c){D.zc.$o();return D.zc.ph[a][b][D.zc.uJ][c]};D.zc.vCa=function(a,b){D.zc.$o();var c=D.zc.Nka(a,b);return c&&(c=D.zc.ph[a][c][D.zc.UY])?c:[]};D.zc.mKa=function(a,b){D.zc.$o();return D.zc.ph[a][D.zc.ct][b]};D.zc.W7=function(a,b,c,d,e,f,g,h){var j=D.zc.ph[a];j||(j={},j[D.zc.ct]=[],D.zc.ph[a]=j);a=j[b];a||(a={},j[b]=a,g!=D.n&&(j[D.zc.ct][g]=b));a[D.zc.DE]=c;a[D.zc.uJ]=d;a[D.zc.UY]=e;a[D.zc.TY]=f;a[D.zc.CP]=h;a[D.zc.ct]=g};(0,D.ra)("DvtBaseMapManager.registerBaseMapLayer",D.zc.W7);
D.zc.rna=function(a,b,c){var d=D.zc.ph[a];d||(d={},D.zc.ph[a]=d);a=d[b];a||(a={},d[b]=a);(a=d[b])&&(a[D.zc.DE]=c)};(0,D.ra)("DvtBaseMapManager.registerResourceBundle",D.zc.rna);D.zc.Vna=function(a,b,c){if(a=D.zc.ph[a])if(b=a[b])for(var d in c)b[D.zc.DE][d]=c[d]};(0,D.ra)("DvtBaseMapManager.updateResourceBundle",D.zc.Vna);
D.zc.$o=function(){var a,b,c=D.zc._UNPROCESSED_MAPS;if(c){for(a=0;a<c[0].length;a++)b=c[0][a],D.zc.W7(b[0],b[1],b[2],b[3],b[4],b[5],b[6],b[7]);for(a=0;a<c[1].length;a++)b=c[1][a],D.zc.rna(b[0],b[1],b[2]);for(a=0;a<c[2].length;a++)b=c[2][a],D.zc.Vna(b[0],b[1],b[2]);D.zc._UNPROCESSED_MAPS=D.n}if(c=D.zc._UNPROCESSED_PARENT_UPDATES){for(a=0;a<c[0].length;a++){b=c[0][a];var d=b[1],e=b[2],f=D.zc.ph[b[0]],g;if(f){if(d=f[d]){d[D.zc.UY]=b[3];g=d[D.zc.CP];a=d[D.zc.ct];d=f[D.zc.ct];d.splice(a,0,e);f[e][D.zc.ct]=
a;for(a+=1;a<d.length;a++)(e=f[d[a]])&&e[D.zc.ct]++}(d=f[b[2]])&&(d[D.zc.CP]=g)}}D.zc._UNPROCESSED_PARENT_UPDATES=D.n}};D.zc.oHa=function(a,b,c,d,e,f){if(0<f){b=1/(window.Math.min(d/b,e/c)*f);if(1>=b)return a;c=[];if(a)for(var g in a)d=a[g],(0,window.isNaN)(d)&&(d=D.P.qU(a[g])),c[g]=D.P.pHa(d,b);return c}return a};
D.ue=function(a,b){this.Init(a,b)};D.y.l(D.ue,D.y,"DvtThematicMapCategoryWrapper");D.ue.prototype.Init=function(a,b){this.yB=a;this.An=b};D.ue.prototype.Wh=(0,D.w)("An");D.ue.prototype.ze=function(){return[this.yB]};
D.Pc=function(a){this.Init(D.Pc.Saa);this.Bva=a};D.y.l(D.Pc,D.tb,"DvtMapDrillEvent");D.Pc.Saa="drill";D.Pc.Roa=0;D.Pc.dX=1;D.Pc.yqa=2;D.Pc.prototype.Pe=(0,D.v)("Dg");
D.Oc=function(a,b,c){this.Init("action");this.Oh=a;this.kM=b;this.Al=c};(0,D.ra)("DvtMapActionEvent",D.Oc);D.y.l(D.Oc,D.tb,"DvtMapActionEvent");D.Oc.TYPE="action";D.Oc.prototype.WC=(0,D.w)("Oh");D.Oc.prototype.getClientId=D.Oc.prototype.WC;D.Oc.prototype.w6=(0,D.w)("kM");D.Oc.prototype.getRowKey=D.Oc.prototype.w6;D.Oc.prototype.Fj=(0,D.w)("Al");D.Oc.prototype.getAction=D.Oc.prototype.Fj;
D.Cc=function(a,b,c,d,e,f){this.Init(a,b,c,d,e,f)};D.y.l(D.Cc,D.Ia,"DvtMapLabel");D.x=D.Cc.prototype;D.x.Init=function(a,b,c,d,e,f){D.Cc.o.Init.call(this,a,b,0,0);this.yf=f;this.nt=[];this.ia(D.p);this.lf();this.Ge();this.pt=D.n;this.Po=d;this.AC=e;if(c&&(this.nt.push((0,D.Pd)(c[0])),1<c.length)){this.L1=[];for(b=1;b<c.length;b++)d=c[b],this.nt.push((0,D.Pd)(d[0])),d=new D.Qd(a,d[1]),(0,D.Rd)(d),e=new D.db("#000000"),this.yf&&(e.rd=D.k),d.W(e),this.L1.push(d)}};
D.x.update=function(a){a=a.Qd;for(var b=-1,c=D.Pa.sf(this),d=D.p,e=0;e<this.nt.length;e++){var f=this.nt[e].g*a;if(c.j<=this.nt[e].j*a)if(c.g<=f){b=e;break}else if(this.getParent()||(d=D.k,this.AC.k(this)),this.C().g<=f){b=e;break}}-1==b&&"on"==this.Po&&(b=this.nt.length-1);this.c0!=b?(-1==b?this.reset():(this.getParent()||this.AC.k(this),c=this.nt[b].de(),this.vp(c),this.L1&&(this.AC.removeChild(this.jk),this.jk=D.n,0<b?(this.jk=this.L1[b-1],this.AC.k(this.jk),d=this.Xc(),d.V("color","#000000"),
this.Ia(d),d=this.nt[b],e=this.jk.Hb(),f=e.length,d.x>e[f-2]?(this.am(),this.Ge(),this.vp(new D.L(d.x,c.y))):d.y>e[f-1]?(this.lp(),this.lf(),this.vp(new D.L(c.x,d.y))):d.x+d.g<e[f-2]?(this.Dj(),this.Ge(),this.vp(new D.L(d.x+d.g,c.y))):d.y+d.j<e[f-1]&&(this.Bw(),this.lf(),this.vp(new D.L(c.x,d.y+d.j)))):(this.lf(),this.Ge(),d=this.Xc(),d.V("color",this.Lfa),this.Ia(d)))),this.c0=b):-1==b&&d&&this.AC.removeChild(this);-1!=this.c0&&(b=new D.jd,b.translate(a*this.pt.x-this.pt.x,a*this.pt.y-this.pt.y),
this.sa(b),this.jk&&(this.jk.sa(new D.jd(a,0,0,a)),this.yf||(b=this.jk.rc().clone(),b.ha(1/a),this.jk.W(b))))};D.x.vp=function(a){this.pt=a;this.ea(a.x);this.va(a.y)};D.x.de=(0,D.w)("pt");D.x.Ia=function(a){D.Cc.o.Ia.call(this,a);this.Lfa||(this.Lfa=a.v("color"))};D.x.reset=function(){this.AC.removeChild(this);this.c0=-1;this.jk&&(this.AC.removeChild(this.jk),this.jk=D.n)};
D.Mc=function(a,b,c,d,e){this.Init(a,b,c,d,e)};D.y.l(D.Mc,D.I,"DvtMapDataObject");D.x=D.Mc.prototype;D.x.Init=function(a,b,c,d,e){D.Mc.o.Init.call(this,a,D.n,d);this.Vp=[];this.Ib=D.n;this.Oa=c;this.Oh=d;this.tl=e;this.FJa=D.n;this.wK="#000000";this.Zoom=1;this.Z0=D.p;this.fR=b;this.jd=b.fa.jc()};D.x.getId=(0,D.w)("Oa");D.x.WC=(0,D.w)("Oh");D.x.Yd=function(a){(this.Ib=a)&&this.Ib.Hf("img")};D.x.vp=(0,D.v)("Gk");D.x.de=(0,D.w)("Gk");D.x.ra=(0,D.w)("Ib");D.x.yp=(0,D.v)("wo");D.x.Of=(0,D.w)("wo");
D.x.Yc=(0,D.v)("X$");D.x.Fj=(0,D.w)("Al");D.x.eb=function(a){D.Mc.o.eb.call(this,a);this.wo&&this.wo.eb(a)};D.x.ze=function(){return[this.Ib]};D.x.Wh=(0,D.w)("Vp");D.x.Oe=(0,D.w)("Ey");D.x.tk=(0,D.w)("wK");D.x.Cna=function(a){this.wK=a;this.Ib&&this.Ib.wp&&this.Ib.wp(a)};D.x.Bna=function(a){this.Ey=a;this.$j()};D.x.vc=function(){var a=[];this.$b()&&a.push((0,D.ob)(this.jd,this.Ma()?"STATE_SELECTED":"STATE_UNSELECTED"));return(0,D.$b)(this.Oe(),a,this.jd)};
D.x.$j=function(){!(0,D.ac)()&&this.Ib&&(0,D.Oa)(this.Ib,"label",this.vc())};D.x.$b=function(){return this.Ib.$b()};D.x.Ma=function(){return this.Ib.Ma()};D.x.Oc=(0,D.s)();D.x.sc=function(){this.Zd||this.UX()};D.x.UX=(0,D.s)();D.x.uA=(0,D.v)("Rc");D.x.zd=(0,D.w)("Rc");D.x.Oj=function(a){for(var b=this.fR.Oh,c=0;c<a.length&&a[c]!=b;c++);return b};D.x.jl=(0,D.w)("fR");D.x.kl=function(){return this.fR.ay(this)};D.x.$C=function(){return this.fR.$x()};
D.x.Rf=function(a){return a.type==D.Cb?this:32==a.keyCode&&a.ctrlKey?this:(0,D.Gb)(this,a,this.xX())};D.x.xX=(0,D.ca)(D.n);D.x.of=function(a){return this.Ib&&this.Ib.getParent()?this.Ib.C(a):new D.N(0,0,0,0)};D.x.$m=function(){return this.Ib?this.Ib.pa():D.n};D.x.Xf=function(){this.Zd=D.k;this.Oc()};D.x.Mc=function(){this.Zd&&(this.Zd=D.p,this.sc())};D.x.vg=(0,D.w)("Zd");D.x.Rg=function(a){this.Ib.getParent()&&(this.Zoom=a.Qd,this.bO())};D.x.Mp=(0,D.s)();D.x.bO=(0,D.s)();D.x.yc=(0,D.ca)(0);
D.Bd=function(a,b,c,d,e){this.Init(a,b,c,d,e)};D.y.l(D.Bd,D.Mc,"DvtMapDataArea");D.x=D.Bd.prototype;D.x.Init=function(a,b,c,d,e){D.Bd.o.Init.call(this,a,b,c,d,e);this.s1=D.p};D.x.Yd=function(a){D.Bd.o.Yd.call(this,a)};D.x.Pb=function(a){a&&!this.s1&&this.Dn.k(this.Ib);this.Ib.Pb(a);this.$j()};D.x.Oc=function(){this.Dn.k(this.Ib);this.Ib.Oc();this.s1=D.k};D.x.UX=function(){this.Ma()?this.Dn.k(this.Ib):this.Dn.Ha(this.Ib,0);this.Ib.sc();this.s1=D.p};D.x.uu=function(){return this.Ib.uu()};
D.x.uI=function(a){(this.cS=a)?this.Dn.k(this.Ib):this.Dn.Ha(this.Ib,0);this.Ib.uI(a)};D.x.Rg=function(a){this.Ib.getParent()&&(D.Bd.o.Rg.call(this,a),(0,D.Zc)(this.Ib,a),this.uu()||this.Mp(a))};D.x.Mp=function(a){this.wo&&this.wo.update(a)};D.x.xX=function(){return(0,D.Zd)(this.jl().fa)};
D.md=function(a,b,c,d,e){this.Init(a,b,c,d,e)};D.y.l(D.md,D.Mc,"DvtMapDataMarker");D.x=D.md.prototype;D.x.Init=function(a,b,c,d,e){D.md.o.Init.call(this,a,b,c,d,e);this.KHa=1;this.ok=0};D.x.Pb=function(a){this.Ib.Pb(a);this.$j()};D.x.Oc=function(){this.Ib.Oc()};D.x.UX=function(){this.Ib.sc()};
D.x.Mp=function(){if(this.wo){this.wo.lf();var a=(this.Ib.da()+(0,D.nd)(this.Ib)/2)*this.Zoom,b=this.Ib.ga()*this.Zoom,c=(0,D.pd)(this.Ib),d=this.Ib.Ga();"top"==this.X$?(b-=4,this.wo.Bw()):"bottom"==this.X$?(b+=c,this.wo.lp()):(b="triangleUp"==d?b+2*c/3:"triangleDown"==d?b+c/3:b+c/2,this.wo.Ge());this.wo.ea(a);this.wo.va(b)}};
D.x.bO=function(){var a=this.Ib.getParent(),b=(0,D.pd)(this.Ib);(0,D.nd)(this.Ib)!=D.n&&(b!=D.n&&a)&&(b=this.Ib.hD(),this.wo&&this.Ib.hD()?((0,D.G)(a,this.Gk.x*this.Zoom-this.Gk.x,this.Gk.y*this.Zoom-this.Gk.y),(0,D.qd)(a)):((0,D.G)(this.Ib,this.Gk.x*this.Zoom-(this.Gk.x*window.Math.cos(b)-this.Gk.y*window.Math.sin(b)),this.Gk.y*this.Zoom-(this.Gk.x*window.Math.sin(b)+this.Gk.y*window.Math.cos(b))),(0,D.qd)(this.Ib)))};D.x.xX=function(){return(0,D.rd)(this.jl().fa)};D.x.dj=(0,D.v)("ok");D.x.yc=(0,D.w)("ok");
D.Fd=function(a,b,c,d,e){this.Init(a,b,c,d,e)};D.y.l(D.Fd,D.Mc,"DvtMapDataImage");D.x=D.Fd.prototype;D.x.Init=function(a,b,c,d,e){D.Fd.o.Init.call(this,a,b,c,d,e)};D.x.VV=function(a){a&&(a.width&&a.height)&&(this.Ib.getWidth()||this.Ib.ha(a.width),this.Ib.getHeight()||this.Ib.xa(a.height),this.dj(a.width*a.height),this.Ib.ea(this.Gk.x-a.width/2),this.Ib.va(this.Gk.y-a.height/2),this.bO())};D.x.Ma=(0,D.ca)(D.p);D.x.$b=(0,D.ca)(D.p);
D.x.bO=function(){var a=this.Ib.getWidth(),b=this.Ib.getHeight();a!=D.n&&(b!=D.n&&this.Ib.getParent())&&(a=this.Ib.da()+a/2,b=this.Ib.ga()+b/2,(0,D.G)(this.Ib,a*this.Zoom-this.Gk.x,b*this.Zoom-this.Gk.y))};D.x.dj=(0,D.v)("ok");D.x.yc=(0,D.w)("ok");
D.hd=function(a,b,c,d,e){this.Init(a,b,c,d,e)};D.y.l(D.hd,D.Mc,"DvtMapDataComponent");D.x=D.hd.prototype;D.x.Init=function(a,b,c,d,e){D.hd.o.Init.call(this,a,b,c,d,e)};D.x.ha=(0,D.v)("T");D.x.getWidth=(0,D.w)("T");D.x.xa=(0,D.v)("Y");D.x.getHeight=(0,D.w)("Y");D.x.ea=(0,D.v)("Ta");D.x.va=(0,D.v)("lb");D.x.bO=function(){if(this.Ib.getParent()){var a=this.lb+this.Y/2;this.Ib.F(this.Ta+(this.Ta+this.T/2)*this.Zoom-this.Gk.x);this.Ib.O(this.lb+a*this.Zoom-this.Gk.y)}};
D.x.yc=function(){return this.T*this.Y};D.x.Ma=(0,D.ca)(D.p);D.x.$b=(0,D.ca)(D.p);
D.Bc=function(a,b,c,d){this.Init(a,b,c,d)};D.y.l(D.Bc,D.I,"DvtMapArea");D.x=D.Bc.prototype;D.x.Init=function(a,b,c,d){D.Bc.o.Init.call(this,a);this.hS=this.tQ=D.p;this.uIa=c;this.H=b;this.k(this.H);this.yf=d;if(a=b.rc())this.hca=a.getWidth();this.H&&this.H.Hf("img")};D.x.te=(0,D.w)("kf");D.x.vx=(0,D.v)("kf");D.x.rc=function(){return this.H instanceof D.ld?this.H.rc():D.n};D.x.W=function(a){this.H instanceof D.ld&&this.H.W(a)};D.x.J=function(a){this.H instanceof D.ld&&this.H.J(a)};
D.x.Ec=function(){return this.H instanceof D.ld?this.H.Ec():D.n};D.x.XC=function(){return this.H instanceof D.Tb?this.H.XC():D.n};D.x.Ek=function(a){this.H instanceof D.Tb&&this.H.Ek(a)};D.x.XD=function(a){this.H instanceof D.Xa&&this.H.XD(a)};D.x.contains=function(a,b){var c=this.C();return a>=c.x&&a<=c.x+c.g&&b>=c.y&&b<=c.y+c.j};D.x.Rg=function(a){if(!this.yf&&this.H&&this.hca){var b=this.H.rc().clone();b.ha(this.hca/a.Qd);this.H.W(b)}};
D.vc=function(a,b,c){this.Init(a,b,c)};D.y.l(D.vc,D.y,"DvtMapLayer");D.x=D.vc.prototype;D.x.Init=function(a,b,c){this.fa=a;this.mg=b;this.UO=c;this.ci={};this.qJ=new D.jd};D.x.paa=(0,D.s)();D.x.jl=function(a){return this.ci?this.ci[a]:D.n};D.x.L=function(a){this.qJ=a;for(var b in this.ci)this.ci[b].L(a)};D.x.reset=function(a,b){for(var c in this.ci)this.ci[c].reset(a,b)};D.x.Rg=function(a,b){this.qJ=b;for(var c in this.ci)this.ci[c].Rg(a,b)};D.x.Us=function(a){this.qJ=a;for(var b in this.ci)this.ci[b].Us(a)};
D.x.Kp=function(a){if(this.t2)for(var b=[this.t2.Dn,this.t2.st,this.t2.eR],c=0;c<b.length;c++){var d=b[c].getParent();d&&d.removeChild(b[c])}b=[a.eR];a.fa.Vv&&b.push(a.st);for(c=0;c<b.length;c++)b[c].up(b[c].ua()-1);a=[a.Dn];for(c=0;c<a.length;c++)a[c].up(a[c].ua()-1);this.paa();c=this.fa;c.Aj.z1&&c.Rb.oo(D.n,c.Aj.bD());(0,D.ae)(c);c.q1&&(0,D.be)(c);this.yb=D.n;this.UO.Df(this.ja)};
D.uc=function(a,b,c,d,e){this.Init(a,b,c,d,e)};D.y.l(D.uc,D.vc,"DvtMapAreaLayer");D.x=D.uc.prototype;D.x.Init=function(a,b,c,d,e){D.uc.o.Init.call(this,a,b,e);this.Po=c;this.Ofa=d;this.NJ={};this.Cp={};this.gr={};this.VF=this.fr=D.n;this.Dg=[];this.vz={};this.Xt={};this.mT={};this.DO=new D.I(this.fa.e);this.cJ=new D.I(this.fa.e);this.fa.MZ.Ha(this.DO,0);this.fa.Kt.Ha(this.cJ,0);this.w0=new D.wc(this,this.fa.qi)};D.x.fW=(0,D.v)("HZ");D.x.os=(0,D.w)("HZ");D.x.Ds=(0,D.v)("GZ");D.x.Qa=(0,D.w)("GZ");
D.xc=function(a,b){a.fr=b;for(var c in a.fr)a.vz[c]=D.k,a.Xt[c]=D.k};D.uc.prototype.fla=function(a){return!this.VF?D.n:this.VF[a]};D.yc=function(a,b){return a.ve[b]?a.ve[b].split(","):[]};D.uc.prototype.SU=(0,D.w)("Po");
D.uc.prototype.bD=function(){if(!this.XF)if(this.z1)this.XF=D.P.C(D.P.qU(D.zc.IDa(this.fa.qi,this.mg,this.z1)));else if("world"!=this.fa.qi&&"worldRegions"!=this.fa.qi&&(this.XF=D.zc.Ika(this.fa.qi,this.mg)),!this.XF){var a=(0,D.Ac)(this.DO.C(),this.fa.vK.C());0<a.g&&0<a.j&&(this.XF=a)}return this.XF};
D.Dc=function(a,b,c){var d=a.gr[b];if(d&&((c||!a.Cp[b])&&a.Una(b),a.Cp[b]||(c=new D.Bc(a.fa.e,d,b,a.fa.yf),a.Cp[b]=c,a.UO.ka(d,c),c.vx(a.fr&&a.fr[b]?a.fr[b][1]:D.n)),a.Xt[b]&&(c=a.NJ[b],!c&&("off"!=a.Po&&a.fr)&&(c="short"==a.Ofa?a.fr[b][0]:a.fr[b][1]))))a.VF&&a.VF[b]?c=new D.Cc(a.fa.e,c,a.VF[b],a.Po,a.cJ,a.fa.yf):(d=(0,D.Ka)(a.fa.e,d),c=new D.Cc(a.fa.e,c,[[d.x,d.y,d.g,d.j]],a.Po,a.cJ,a.fa.yf)),a.NJ[b]=c,a.J1&&c.Ia(a.J1)};
D.Fc=function(a,b,c){if(a.gr[b]){a.DO.k(a.Cp[b]);var d=a.NJ[b];d&&(a.Xt[b]?d.update(a.qJ):d.reset(),a.mT[b]=a.Xt[b]);c&&(c.push(a.Cp[b]),d&&(c.push(d),c.push(d.jk)))}};D.x=D.uc.prototype;
D.x.Una=function(a){if(!this.Qha||this.wca){this.wca=D.p;var b;this.Qha=(b="world"==this.fa.qi||"worldRegions"==this.fa.qi?D.zc.Ika(this.fa.qi,this.mg):this.bD())?D.zc.oHa(D.zc.Eka(this.fa.qi,this.mg),b.g,b.j,this.fa.T,this.fa.Y,this.fa.QC?this.fa.g2:1):D.zc.Eka(this.fa.qi,this.mg)}b=this.Qha[a];this.gr[a]&&b?this.gr[a].Ek(b):delete this.gr[a]};D.x.L=function(a){this.wca=D.k;for(var b in this.gr)(0,D.Dc)(this,b,D.k),this.vz[b]&&(0,D.Fc)(this,b);D.uc.o.L.call(this,a)};
D.x.paa=function(){for(var a in this.vz)if(!this.vz[a]){this.DO.removeChild(this.Cp[a]);var b=this.NJ[a];b&&(this.mT[a]=D.p,this.cJ.removeChild(b),(b=b.jk)&&this.cJ.removeChild(b))}};D.x.r5=function(a,b){for(var c=0;c<a.length;c++)(0,D.Dc)(this,a[c],D.p),this.vz[a[c]]&&(0,D.Fc)(this,a[c],b);for(var d in this.ci)this.ci[d].r5(a,b,this.qJ);this.Dg=this.Dg.concat(a)};
D.x.AO=function(a,b){for(var c in this.ci)this.ci[c].AO(a,b);c=(0,D.Gc)(this.fa,this.mg);for(var d=0;d<a.length;d++){var e=a[d];if(this.Cp[e]){var f=D.Hc.Fa(this.Dg,e);-1!==f&&(this.Dg.splice(f,1),b.push(this.Cp[e]))}c&&c.AO((0,D.yc)(this,e),b)}};D.x.reset=function(a,b){D.uc.o.reset.call(this,a,b);"none"!=this.fa.Wk&&(this.AO(this.Dg,a),this.Dg=[])};
D.x.Rg=function(a,b){D.uc.o.Rg.call(this,a,b);if(!this.fa.yf)for(var c in this.Cp)this.Cp[c].Rg(b);for(c in this.mT)if(this.mT[c]){var d=this.NJ[c];d&&d.update(b)}};
D.wd=function(a,b,c,d,e){this.Init(a,b,c,d,e)};D.y.l(D.wd,D.uc,"DvtMapCustomAreaLayer");D.wd.prototype.Init=function(a,b,c,d,e){D.wd.o.Init.call(this,a,b,c,d,e)};D.wd.prototype.Una=(0,D.s)();D.wd.prototype.bD=function(){return new D.N(0,0,this.sxa,this.rxa)};D.xd=function(a){var b=a.fa.T,c=a.fa.Y;a=a.Rta;for(var d=0;d<a.length;d++){var e=a[d],f=e.source,g=e.width,e=e.height;if(f&&-1<f.search(".svg")||g>=b&&e>=c||d==a.length-1)return f}};
D.wd.prototype.Rg=function(a,b){D.wd.o.Rg.call(this,a,b);if(this.Cp.image){var c=(0,D.xd)(this);c!=this.UR&&(this.UR=c,this.Cp.image.XD(this.UR))}};
D.$c=function(a,b,c,d){this.Init(a,b,c,d)};D.y.l(D.$c,D.y,"DvtMapDataLayer");D.$c.prototype.Init=function(a,b,c,d){this.fa=a;this.Oh=c;this.mc=[];this.li=[];this.Ca=d;this.Vk=new D.ad(a.e);(0,D.bd)(this.Ca,this.Vk);this.Dn=new D.I(this.fa.e);this.st=new D.I(this.fa.e);this.eR=new D.I(this.fa.e);this.fa.vK.Ha(this.Dn,0);this.fa.yv.Ha(this.st,0);this.fa.Kt.Ha(this.eR,0);this.Nha=b;this.Dg=[];this.Fm=[]};D.cd=function(a){for(var b=[],c=0;c<a.mc.length;c++)a.mc[c].uu()||b.push(a.mc[c]);return b};
D.dd=function(a){for(var b=[],c=0;c<a.mc.length;c++)for(var d=0;d<a.Dg.length;d++)a.mc[c].tl==a.Dg[d]&&(a.mc[c].uu()||b.push(a.mc[c]));return b};D.ed=function(a,b){a.li.push(b);a.Ca.ka(b.ra(),b)};D.x=D.$c.prototype;D.x.WC=(0,D.w)("Oh");D.x.fW=(0,D.v)("HZ");D.x.os=(0,D.w)("HZ");D.x.Ds=(0,D.v)("GZ");D.x.Qa=(0,D.w)("GZ");D.x.tx=function(a){if(this.cs=a)this.Mb=new D.fd(this.cs),this.Ca.tA(this.Oh,this.Mb)};D.x.$b=function(){return this.cs!=D.n};
D.gd=function(a,b){var c;c=a.mc[b];var d=c.ra(),e=a.Nha.gr[c.tl];e?(d.Ek(e.XC()),c=D.k):(c=a.mc.indexOf(c),-1!==c&&a.mc.splice(c,1),c=D.p);if(c){d=a.mc[b].ra();a.Dn.k(d);if(c=a.mc[b].Of())0<c.nt.length||(d=d.C(),c.nt.push(d)),c.update(a.yG);return D.k}return D.p};D.x=D.$c.prototype;
D.x.L=function(a){this.pca=D.k;this.yG=a;var b={};this.li.sort(function(a,b){return a.yc()<b.yc()?1:a.yc()>b.yc()?-1:0});for(var c=0;c<this.li.length;c++){var d=this.li[c],e=d.ra(),f=d.Of();if(f){if(e.hD()){var g=new D.I(e.e);this.st.k(g);g.k(e);g.k(f)}else this.st.k(e),e.k(f);d.Mp(a)}else this.st.k(e);if(d instanceof D.hd)if(f=d.pxa)e.L(f,d.getWidth(),d.getHeight());else continue;(d=d.tl)&&(b[d]=D.k)}for(c=0;c<this.mc.length;c++)b[this.mc[c].tl]&&this.mc[c].yp(D.n),(0,D.gd)(this,c)||c--;this.o1&&
this.wG()};D.x.r5=function(a,b,c){this.yG=c;for(var d=[],e=0;e<a.length;e++)for(var f=0;f<this.mc.length;f++)if(this.mc[f].tl==a[e]){d.push(this.mc[f].tl);(0,D.gd)(this,f);var g=this.mc[f].ra();b.push(g);(0,D.Zc)(g,c);if(f=this.mc[f].Of())b.push(f),(f=f.jk)&&b.push(f);break}for(f=0;f<this.li.length;f++)for(e=0;e<a.length;e++)c=this.li[f].tl,g=this.li[f].ra(),c!=D.n?c==a[e]&&(this.st.k(g),b.push(g)):(this.st.k(g),b.push(g));this.Dg=this.Dg.concat(d)};
D.x.AO=function(a,b){for(var c=0;c<a.length;c++)for(var d=0;d<this.mc.length;d++)if(this.mc[d].tl==a[c]){this.mc[d].uu()&&this.mc[d].uI(D.p);this.mc[d].Ma()&&this.Mb.dO(this.mc[d]);var e=D.Hc.Fa(this.Dg,a[c]);if(-1<e&&(this.Dg.splice(e,1),b.push(this.mc[d].ra()),d=this.mc[d].Of()))b.push(d),b.push(d.jk);break}};
D.x.reset=function(a,b){if(this.Mb)for(var c=this.Mb.getSelection(),d=0;d<c.length;d++)(!b||b&&-1==D.Hc.Fa(b,c[d].tl))&&this.Mb.dO(c[d]);if("none"!=this.fa.Wk)for(c=0;c<this.Fm.length;c++){for(d=0;d<this.mc.length;d++)if(this.mc[d].tl==this.Fm[c]){this.mc[d].uI(D.p);var e=this.mc[d].ra();this.Dn.k(e);a.push(e);if(d=this.mc[d].Of())d.update(this.yG),a.push(d),a.push(d.jk);break}for(d=0;d<this.li.length;d++)if(this.li[d].tl==this.Fm[c]){e=this.li[d].ra();this.st.k(e);a.push(e);break}}this.Fm=[]};
D.x.Rg=function(a,b){this.yG=b;var c=b.Qd,d=a.Wi();if(this.pca&&"zoomed"==d){this.pca=D.p;for(d=0;d<this.mc.length;d++){var e=this.mc[d].ra(),f=e.Gya;if(f){var g=new D.id;f.Ld(g);g.sa(new D.jd(1/c,D.n,D.n,1/c));e.J(g)}}}d=this.mc;for(c=0;c<d.length;c++)d[c].Rg(b);if(this.fa.Vv){d=this.li;for(c=0;c<d.length;c++)d[c].Rg(b)}};D.x.Us=(0,D.v)("yG");D.x.wG=function(){this.Mb&&((0,D.kd)(this.Mb,this.o1,this.li.concat(this.mc)),this.o1=D.n)};
D.x.ay=function(a){if(this.Mb){a.Ma()||(this.Mb.cj(a,D.p),this.Ca.Hq(a));a=[];for(var b=this.Mb.getSelection(),c=0;c<b.length;c++)a.push(b[c].getId());return a}return D.n};D.x.$x=function(){for(var a=[],b=this.Mb.getSelection(),c=0;c<b.length;c++)a.push(b[c].ra());return a};
D.Vd=function(a,b){this.Init(a,b)};D.y.l(D.Vd,D.Yd,"DvtThematicMapKeyboardHandler");D.x=D.Vd.prototype;D.x.Init=function(a,b){D.Vd.o.Init(a,b);this.fa=a};D.x.cI=function(a){return this.Yi(a)&&!a.ctrlKey};
D.x.lo=function(a){var b=a.keyCode;if(221==b){var b=this.ta.Ie(),c=(0,D.rd)(this.fa);b instanceof D.Bd&&0<c.length&&(b=(0,D.Gb)(b,a,c));(0,D.Jc)(this.ta,b)}else 219==b?(b=this.ta.Ie(),c=(0,D.Zd)(this.fa),!(b instanceof D.Bd)&&0<c.length&&(b=(0,D.Gb)(b,a,c)),(0,D.Jc)(this.ta,b)):(b=D.Vd.o.lo.call(this,a),this.Yi(a)&&!a.ctrlKey&&(0,D.Jc)(this.ta,b));return b};D.x.tD=function(a){return 32==a.keyCode&&a.ctrlKey};
D.x.Yi=function(a){var b=D.Vd.o.Yi.call(this,a);if(!b&&(a=a.keyCode,219==a||221==a))b=D.k;return b};
D.Ic=function(a,b,c){this.Init(a,b,c)};D.y.l(D.Ic,D.ta,"DvtThematicMapEventManager");D.x=D.Ic.prototype;D.x.Init=function(a,b,c){D.Ic.o.Init.call(this,a,b,c);this.rw={};this.fa=c;this.kt=D.p};D.x.Ef=function(a){if(a&&a.jl)return this.rw[a.jl().Oh]};D.x.tA=function(a,b){this.rw[a]=b};D.x.p8=(0,D.v)("Wk");D.x.dO=function(a,b){var c=this.rw[a];c&&c.dO(b)};D.x.uH=function(a){(a=this.rw[a])&&a.uH()};
D.x.zo=function(a){var b=this.ma(a.target);b&&(b.zd&&b.jl)&&(this.fa.wF=b.jl().Oh);D.Ic.o.zo.call(this,a)};D.x.fj=function(a){this.fa.wF=D.n;D.Ic.o.fj.call(this,a)};D.x.xl=function(a){this.kt=D.p;D.Ic.o.xl.call(this,a)};D.x.Lp=function(a){this.kt=D.k;D.Ic.o.Lp.call(this,a)};
D.x.mh=function(a){if(!this.kt){var b=this.ma(a.target);(0,D.Jc)(this,b);if(!b||!b.$b||!b.$b())for(var c in this.rw)if(this.rw[c].cj(D.n,a.ctrlKey)){var d=new D.Kc([]);(0,D.Lc)(d,"clientId",c);this.fb.call(this.ja,d)}D.Ic.o.mh.call(this,a);this.Ft(b,a.pageX,a.pageY)}};D.x.Ft=function(a,b,c){a instanceof D.Mc&&(a.Z0?(0,D.Nc)(this,a,b,c):a.zd()&&(this.fa.wF=a.jl().Oh))};
D.Nc=function(a,b,c,d){var e=new D.Oc(b.Oh,b.getId(),b.Fj());(0,D.Lc)(e,"clientId",b.jl().Oh);c!=D.n&&d!=D.n&&(b=(0,D.gc)(a.fa.e,c,d),(0,D.Lc)(e,"pointXY",{x:b.x,y:b.y}));a.zc();a.fb.call(a.ja,e)};D.Jc=function(a,b){var c=D.n,d=D.n,e=D.n;b&&(b instanceof D.Mc?e=b.ra():b instanceof D.Bc&&(e=b),b.jl&&(d=b.jl(),c=d.Oh,d=d.Nha.mg));var f=a.fa;f.fk=d;f.tv=c;f.HQ=e};D.x=D.Ic.prototype;
D.x.yo=function(a){D.Ic.o.yo.call(this,a);a=this.ma(a.target);this.Ef(a)&&(this.Wk&&"none"!=this.Wk)&&(a=new D.Pc(D.Pc.dX),this.fb.call(this.ja,a))};
D.x.rm=function(a){var b=D.k,c=a.keyCode;if((48==c||96==c)&&a.ctrlKey&&a.shiftKey)this.fa.d8(),a.preventDefault();else if(220==c)(c=this.fa.oc)&&(c instanceof D.Qc?(0,D.Rc)(c,!c.isCollapsed()):c instanceof D.Sc&&c.Pe(!c.Za())),a.preventDefault();else if(13==c)c=this.Ie(),c instanceof D.Mc&&c.Z0?(0,D.Nc)(this,c):(a.shiftKey?this.fa.s5():this.fa.uU(),a.preventDefault());else if(32==c&&a.ctrlKey)c=this.Ie(),(0,D.Jc)(this,c),(0,D.Uc)(this,c,D.k),a.preventDefault();else if((48==c||96==c)&&a.ctrlKey){var d=
this.Ie();a.altKey?(c=this.fa,d=d.ra(),d||(d=c.Hja),d||(d=c.HQ),c.mH(d.C())):(0,D.Vc)(this.fa);a.preventDefault()}else b=D.Ic.o.rm.call(this,a);return b};D.x.$s=function(a){var b=this.ma(a.target);(0,D.Jc)(this,b);if(!b||b.CKa)for(var c in this.rw)if(this.rw[c].cj(D.n,a.ctrlKey)){for(var d=this.rw[c].getSelection(),e=[],f=0;f<d.length;f++)e.push(d[f].getId());d=new D.Kc(e);this.fb.call(this.ja,d)}D.Ic.o.$s.call(this,a);this.Ft(b,a.cr.pageX,a.cr.pageY)};
D.x.lP=function(a){if((a=this.ma(a.target))&&a.zd&&a.jl)this.fa.wF=a.jl().Oh};D.x.ZI=function(a){this.fa.wF=D.n;D.Ic.o.ZI.call(this,a)};D.x.HA=function(a){var b=this.ma(a.target);b&&(this.Ef(b)&&this.Wk&&"none"!=this.Wk)&&((0,D.Uc)(this,b,a.ctrlKey),a=new D.Pc(D.Pc.dX),this.fb.call(this.ja,a))};
D.sd=function(a){this.Init(a)};D.y.l(D.sd,D.y,"DvtThematicMapJsonParser");D.sd.prototype.Init=function(a){this.fa=a;this.cL=D.p;this.aB=D.n;this.gxa=(0,D.Qa)();this.zda={};this.Bda={}};
D.sd.prototype.parse=function(a){this.fa.Ds(a.animationDuration/1E3);this.fa.dca="auto"==a.animationOnDisplay?"alphaFade":a.animationOnDisplay;this.fa.Lta="auto"==a.animationOnMapChange?"alphaFade":a.animationOnMapChange;this.cL=a.source!=D.n;var b=this.fa,c=this.cL?"$"+a.basemap:a.basemap;b.RZ=b.qi&&b.qi!=c;b.qi=c;this.fa.nW(a.featuresOff);this.fa.WQ=a.controlPanelBehavior;b=a.tooltipDisplay;"shortDesc"==b?b="shortDescOnly":"labelAndShortDesc"==b&&(b="auto");this.fa.sva=b;(b=a.popups)&&this.fa.uA(this.Mv(b));
this.fa.p8(a.drilling);this.fa.JZ=a.animationOnDrill;this.fa.q1="auto"==a.initialZooming;this.fa.Vv="fixed"==a.markerZoomBehavior;this.fa.sG="auto"==a.panning;this.fa.QC="auto"==a.zooming;this.fa.axa=a.panX;this.fa.bxa=a.panY;this.fa.pfa=a.zoom;(0,window.isNaN)(a.maxZoom)||(this.fa.g2=a.maxZoom);a._legend&&(this.fa.Lt=a._legend);this.c3(a.styleDefaults);if(this.cL&&a.sourceXml)for(var b=(new D.td).parse(a.sourceXml).ub(),d,e,c=0;c<b.length;c++)if(d=b[c],e=d.getName(),"layer"==e){e=d;d=e.ub();e=e.q("id");
for(var f=D.i,g=D.i,h=[],j=0;j<d.length;j++)if(f=d[j],g=f.getName(),"image"==g){g={};g.source=f.q("source");g.width=f.q("width");g.height=f.q("height");var l=f.q("bidi"),f=f.q("dir");g.dir="true"==l||"rtl"==f?"rtl":"ltr";h.push(g)}this.zda[e]=h}else if("points"==e){d=d.ub();h=e=D.i;j={};f={};for(g=0;g<d.length;g++)e=d[g],h=e.getName(),"point"==h&&(j[e.q("name")]=[e.q("x"),e.q("y")],f[e.q("name")]=[D.n,e.q("longLabel")]);D.zc.W7(this.fa.qi,"cities",f,j,D.n,D.n,1)}b=a.areaLayers;c=this.fa.qi;for(d=
0;d<b.length;d++)if(e=D.Sa.Ob(b[d],D.ud),j=e.layer){e.areaStyle&&(0,D.vd)(this.aB,e.areaStyle);e.labelStyle&&(0,D.vd)(this.aB,e.labelStyle);if(this.cL){f=h=new D.wd(this.fa,j,e.labelDisplay,e.labelType,this.fa.Ca);j=this.zda[j];l=D.n;g=(0,D.C)(f.fa.e);if(j&&0<j.length){var l=j[0].width,m=j[0].height;f.sxa=l;f.rxa=m;for(var o=[],q=0;q<j.length;q++)g&&"rtl"==j[q].dir?o.push(j[q]):!g&&"ltr"==j[q].dir&&o.push(j[q]);f.Rta=0<o.length?o:j;f.UR=(0,D.xd)(f);l=new D.Xa(f.fa.e,f.UR,0,0,l,m)}l&&((0,D.xc)(f,{image:[D.n,
D.n]}),f.gr={image:l})}else{h=new D.uc(this.fa,j,e.labelDisplay,e.labelType,this.fa.Ca);f=D.zc.fCa(c,j);g=h;q=f;l={};m=this.fa.e;o=D.i;for(o in q){l[o]=new D.Tb(m);if((q=this.aB.v("border-color"))&&"transparent"!=q)q=new D.db(q),this.fa.yf&&(q.rd=D.k),l[o].W(q);q=this.aB.v("background-color");"transparent"!=q?l[o].qa(q):l[o].J(D.n)}g.gr=l;(0,D.xc)(h,f);f=D.zc.eCa(c,j);h.VF=f;j=D.zc.vCa(this.fa.qi,j);h.ve=j}h.J1=this.aB;h.VIa=this.Qta;h.fW("auto"==e.animationOnLayerChange?"alphaFade":e.animationOnLayerChange);
h.Ds(this.fa.Qa());this.fa.Af.push(h);e.areaDataLayer&&(0,D.yd)(this,[e.areaDataLayer],h,D.k);e.pointDataLayers&&(0,D.yd)(this,e.pointDataLayers,h,D.p)}(0,D.yd)(this,a.pointDataLayers,D.n,D.p)};
D.yd=function(a,b,c,d){if(b)for(var e=0;e<b.length;e++){var f=D.Sa.Ob(b[e],D.zd);if(f.markerDefs){var g=f.markerDefs,h;for(h in g)if(!a.Bda[h]){var j=(new D.td).parse(g[h]);a.Bda[h]=D.Ad.cka(a.fa.e,j)}}f.legend&&(a.fa.Lt=f.legend);if(c){if(c instanceof D.uc&&d)for(g in d=c,g=D.i,d.fr)d.vz[g]=D.k,d.Xt[g]=D.k}else c=new D.vc(a.fa,f.id,a.fa.Ca),a.fa.Af.push(c);g=new D.$c(a.fa,c,f.id,a.fa.Ca);d=f.selection;"single"==d?g.tx("s"):"multiple"==d&&g.tx("m");g.fW("auto"==f.animationOnDataChange?"alphaFade":
f.animationOnDataChange);g.Ds(a.fa.Qa());var l=D.n;c instanceof D.uc&&(l=f.isolatedItem);var m=f.disclosedItems,j=[],o;d=c instanceof D.uc;var q;f.popups&&(q=a.Mv(f.popups));var r=f.areas;if(r)for(var t=0;t<r.length;t++){var u=r[t].location;if(l)if(l!=r[t].id)continue;else o=u;m&&-1!=m.indexOf(r[t].id)&&j.push(u);var u=a,z=c,A=g,F=r[t],H=F.location;if(z.gr[H]&&F.color){z.vz[H]=D.p;var E=u.fa.e,M=new D.Wc(E,u.fa.yf),F=D.Sa.Ob(F,u.fa.js.dataAreaDefaults);F.labelStyle||(F.labelStyle=u.fa.js.labelStyle);
var S=new D.db(F.hoverColor,1,2),J=new D.db(F.selectedInnerColor,1,1),aa=new D.db(F.selectedOuterColor,1,4);M.Gs(S,D.n).Ls(J,aa);S=new D.db(F.drilledInnerColor,1,2);aa=new D.db(F.drilledOuterColor,1,4);J=M;J.jR=S;J.jR&&J.yf&&(J.jR.rd=D.k);J.kR=aa;J.kR&&J.yf&&(J.kR.rd=D.k);H=new D.Bd(E,A,F.id,F.clientId,H);H.Yd(M);(0,D.Cd)(u,z,A,F,M,H,D.k);u=H}else u=D.n;q&&u.uA(q);u&&(g.$b()&&(z=u.ra(),z.ih(D.k)),z=g,z.mc.push(u),z.Ca.ka(u.ra(),u),u.Dn=z.Dn)}if(r=f.markers)for(t=0;t<r.length;t++){u=r[t].location;
if(l)if(l!=r[t].id)continue;else o=u;u=a;z=c;A=g;F=r[t];M=d;if(E=(0,D.Dd)(u,z.mg,F)){S=u.fa.e;H=new D.md(S,A,F.id,F.clientId,F.location);H.vp(E);J=u.fa.js.dataMarkerDefaults;aa=new D.B(J.labelStyle);(0,D.vd)(aa,F.labelStyle);F=D.Sa.Ob(F,J);F.labelStyle=aa.toString();var oa=D.i;(J=F.source)?oa=[J,F.sourceSelected,F.sourceHover,F.sourceHoverSelected]:(oa=F.shape)||(oa="c");J=F.scaleX;(0,window.isNaN)(J)&&(J=1);aa=F.scaleY;(0,window.isNaN)(aa)&&(aa=1);var ka=F.width,gb=F.height;if(!ka||(0,window.isNaN)(ka))ka=
8;if(!gb||(0,window.isNaN)(gb))gb=8;S=new D.Ed(S,oa,"alta",E.x-ka*J/2,E.y-gb*aa/2,ka,gb,D.n,J,aa);H.Yd(S);H.dj(ka*J*gb*aa);H.Yc(F.labelPosition);if(E=F.rotation)J=E*window.Math.PI/180,S.Tj(J),E=H.de(),(0,D.G)(S,E.x-(E.x*window.Math.cos(J)-E.y*window.Math.sin(J)),E.y-(E.x*window.Math.sin(J)+E.y*window.Math.cos(J)));(0,D.Cd)(u,z,A,F,S,H,M);u=H}else u=D.n;q&&u.uA(q);u&&(g.$b()&&(z=u.ra(),z.ih(D.k)),(0,D.ed)(g,u))}if(r=f.images)for(t=0;t<r.length;t++){u=r[t].location;if(l)if(l!=r[t].id)continue;else o=
u;u=a;z=c;A=g;F=r[t];M=d;(H=(0,D.Dd)(u,z.mg,F))?(E=u.fa.e,S=new D.Fd(E,A,F.id,F.clientId,F.location),S.vp(H),J=new D.Xa(E,F.url),S.Yd(J),aa=F.width,ka=F.height,J.ha(aa),J.xa(ka),aa!=D.n&&ka!=D.n&&(J.ea(H.x-aa/2),J.va(H.y-ka/2),S.dj(aa*ka)),(!aa||!ka)&&D.Gd.Pj(E,F.url,D.y.Ej(S,S.VV)),(0,D.Cd)(u,z,A,F,J,S,M),u=S):u=D.n;q&&u.uA(q);u&&(0,D.ed)(g,u)}if(r=f.components){a.Gxa=new D.Id(a.fa.Wa,a.fa);for(t=0;t<r.length;t++){u=r[t].location;if(l)if(l!=r[t].id)continue;else o=u;m&&-1!=m.indexOf(r[t].id)&&j.push(u);
F=a;A=g;u=r[t];(z=(0,D.Dd)(F,c.mg,u))?(A=new D.hd(F.fa.e,A,u.id,u.clientId,u.location),A.vp(z),A.Yd(F.Gxa.Si(F.fa.e,u)),F=u._width,M=u._height,A.ha(F),A.xa(M),F!=D.n&&M!=D.n&&(A.ea(z.x-F/2),A.va(z.y-M/2)),A.pxa=u,u=A):u=D.n;q&&u.uA(q);u&&(g.$b()&&(z=u.ra(),z.ih(D.k)),(0,D.ed)(g,u))}}if(o)for(t in g.gJa=l,l=c,m=o,l.z1=m,l.XF=D.n,t=D.i,l.gr)t!=m&&(l.vz[t]=D.p);if((f=f.selectedItems)&&0<f.length)g.o1=f;j&&0<j.length&&(a.fa.bL[c.mg]=[g.Oh,j]);c.ci[g.Oh]=g}};
D.sd.prototype.c3=function(a){(0,D.Jd)(this.fa,a);this.aB=new D.B(a.areaStyle);(0,D.vd)(this.aB,a.labelStyle);this.Qta=new D.B(a.dropTargetStyle);this.fa.js=a};
D.Cd=function(a,b,c,d,e,f,g){g&&(b.Xt[d.location]=D.p);d.action&&(f.Z0=D.k,f.Al=d.action);var h=d.destination;if(h){var j=[];j.destination=h;j.targetFrame="_blank";j.focusable=D.k;(0,D.Kd)(e,j)}j=a.fa.sva;if("none"!=j){h=d.shortDesc;if("auto"==j){var l;(j=d.location)&&(l=!g||a.cL?D.zc.xCa(a.fa.qi,j):D.zc.mDa(a.fa.qi,b.mg,j));l&&(h=h?l+": "+h:l)}h&&f.Bna(h)}l=d.pattern;h=d.color;j=a.gxa||"alta"==a.fa.Kb?"none":d.visualEffects;f&&f.Cna(h);if(e instanceof D.Ed&&(0,D.Ld)(e.Ga())){if("none"!=d.borderStyle){var m=
new D.db(d.borderColor,1,d.borderWidth);a.fa.Vv||(m.rd=D.k);m.Uj((0,D.Md)(d.borderStyle));e.W(m)}var o=d.opacity;"none"!=j?e.J(new D.Nd.dka(h,e,o)):l?e.J(new D.id(l,h,"#FFFFFF")):h&&e.qa(h,o)}else if(e instanceof D.Tb){if(j=d.borderColor)m=new D.db(j),a.fa.yf&&(m.rd=D.k),e.W(m);l?(o=new D.id(l,h,"#FFFFFF"),e.Gya=o):e.qa(h,o)}e=d.location;l=(o=d.label)?"on":"off";g&&(l=b.SU());if(!o&&g&&(f instanceof D.Bd&&"off"!=l||!(f instanceof D.Bd)&&"on"==l))o="long"==b.Ofa?b.fr[e][1]:b.fr[e][0];if(o){var q=a.fa.e,
q=f instanceof D.md?new D.Ia(q,o,0,0):new D.Cc(q,o,b.fla?b.fla(e):D.n,l,c.eR,a.fa.yf);a=new D.B;f instanceof D.Bd&&a.Ob(b.J1);d.labelStyle&&(0,D.vd)(a,d.labelStyle);q instanceof D.Cc&&(a.v("color")||a.V("color",D.O.bm(f.tk())));q.Ia(a)}f.yp(q)};D.Dd=function(a,b,c){var d=a.fa.qi,e=c.location;return e?((a=D.zc.cCa(d,b,e))||(a=D.zc.wCa(d,e)),a):D.Q.FGa(c.x,c.y,a.fa.qi)};D.sd.prototype.Mv=function(a){for(var b=[],c=0;c<a.length;c++)b.push(new D.Od(a[c].popupId,a[c].triggerType,D.n,a[c].align));return b};
D.Q={};D.y.l(D.Q,D.y,"DvtThematicMapProjections");D.Q.$u=new D.N(0,0,800,500);D.Q.KP=6378206.4;D.Q.mZ=new D.N(500,200,200,200);D.Q.lZ=new D.N(163,-49,17,17);D.Q.eba=new D.N(-17.379205428479874,-37.201510854305546,68.66391442808313,77.50071544582713);D.Q.hba=new D.N(-0.8436866097568272,-0.7626456732012923,1.8336308036296942,1.5748427214611724);D.Q.iba=new D.N(113.29667079927977,-52.89550592498755,65.25257389065216,42.123114617504626);
D.Q.tba=new D.N(-0.47944476148667076,-0.0014669405958800579,0.7364925893845453,0.6293972741802124);D.Q.Cba=new D.N(-0.6154469465354344,-0.24589767758847714,1.2448236795108683,1.2631535127174947);D.Q.Jba=new D.N(-80.60817722658722,-60.796273249672765,46.608687602908056,66.96595767361796);D.Q.gba=new D.N(68.20516856593524,-52.89892708045518,111.65739821771903,116.55460214469134);D.Q.rba=new D.N(-24.543831069368586,-37.202500659225905,204.54283106936856,164.9634493690208);
D.Q.Bba=new D.N(-117.12451221229134,-54.95921623126266,82.33223251442891,87.67786623127876);D.Q.Nba=new D.N(-0.6154656300926513,0.0507209798775865,1.0153104799231851,0.966537441082997);D.Q.Oba=new D.N(-171.9,-62.6,349.8,150.8);D.Q.cra=new D.N(172,51,8,3);D.Q.dra=new D.N(-180,51,51,21);D.Q.Qra=new D.N(-178.5,18.9,35,11);D.Q.Qsa=new D.N(-124.8,24.4,58,25.5);D.Q.fba=new D.N(-187.5517578125,59.82610321044922,57.562225341796875,43.83738708496094);
D.Q.xba=new D.N(-160.23606872558594,18.91549301147461,5.4374847412109375,3.3189010620117188);D.Q.Mba=new D.N(-2386803.25,-1183550.5,4514111,2908402);D.Q.jZ=new D.N(165,400,100,100);D.Q.fZ=new D.N(-75,350,240,150);D.Q.zl=[[1,0],[0.9986,0.0314],[0.9954,0.0629],[0.99,0.0943],[0.9822,0.1258],[0.973,0.1572],[0.96,0.1887],[0.9427,0.2201],[0.9216,0.2515],[0.8962,0.2826],[0.8679,0.3132],[0.835,0.3433],[0.7986,0.3726],[0.7597,0.4008],[0.6732,0.4532],[0.6213,0.4765],[0.5722,0.4951],[0.5322,0.5072]];
D.Q.FGa=function(a,b,c){var d;switch(c){case "africa":d=D.Q.Jv(D.Q.eba,D.Q.TK(a,b));break;case "asia":d=D.Q.Jv(D.Q.hba,D.Q.CR(40,95,20,60,a,b),D.Q.kh(5));break;case "australia":d=D.Q.Pva(a,b);break;case "europe":d=D.Q.Jv(D.Q.tba,D.Q.CR(35,25,40,65,a,b),D.Q.kh(10));break;case "northAmerica":d=D.Q.Jv(D.Q.Cba,D.Q.CR(23,-96,20,60,a,b));break;case "southAmerica":d=D.Q.Jv(D.Q.Jba,new D.L(a,b),D.Q.kh(5));break;case "apac":d=D.Q.Jv(D.Q.gba,D.Q.TK(a,b));break;case "emea":d=D.Q.Jv(D.Q.rba,D.Q.TK(a,b));break;
case "latinAmerica":d=D.Q.Jv(D.Q.Bba,new D.L(a,b));break;case "usaAndCanada":d=D.Q.Jv(D.Q.Nba,D.Q.CR(23,-96,20,60,a,b));break;case "worldRegions":d=D.Q.Rea(a,b);break;case "usa":d=D.Q.vwa(a,b);break;case "world":d=D.Q.Rea(a,b)}return d?new D.L(10*d.x,10*d.y):new D.L(a,b)};
D.Q.vwa=function(a,b){var c;return(0,D.ze)(D.Q.cra,a,b)||(0,D.ze)(D.Q.dra,a,b)?(c=D.Q.Hn(D.Q.fba,D.Q.fZ),D.Q.IJ(c,D.Q.TK(a,b))):(0,D.ze)(D.Q.Qra,a,b)?(c=D.Q.Hn(D.Q.xba,D.Q.jZ),D.Q.IJ(c,new D.L(a,b))):(0,D.ze)(D.Q.Qsa,a,b)?(c=D.Q.Hn(D.Q.Mba,D.Q.$u),D.Q.IJ(c,D.Q.mwa(new D.L(-95,36),a,b))):new D.L(a,b)};D.Q.Rea=function(a,b){var c=D.Q.Hn(D.Q.Oba,D.Q.$u);return D.Q.IJ(c,D.Q.pwa(a,b))};
D.Q.Pva=function(a,b){var c;c=(0,D.ze)(D.Q.lZ,a,b)?D.Q.Hn(D.Q.lZ,D.Q.mZ):D.Q.Hn(D.Q.iba,D.Q.$u);return D.Q.IJ(c,D.Q.TK(a,b))};D.Q.Jv=function(a,b,c){a=D.Q.Hn(a,D.Q.$u);if(c){var d=new D.jd;d.rotate(c);a=D.Q.eda(a,d)}return(0,D.Ae)(a,b)};
D.Q.CR=function(a,b,c,d,e,f){b=D.Q.kh(b);a=D.Q.kh(a);c=D.Q.kh(c);d=D.Q.kh(d);d=0.5*(window.Math.sin(c)+window.Math.sin(d));c=window.Math.pow(window.Math.cos(c),2)+2*d*window.Math.sin(c);a=c-2*d*window.Math.sin(a);a=window.Math.sqrt(a)/d;e=d*(D.Q.kh(e)-b);f=c-2*d*window.Math.sin(D.Q.kh(f));f=window.Math.sqrt(f)/d;return new D.L(f*window.Math.sin(e),a-f*window.Math.cos(e))};D.Q.TK=function(a,b){var c=window.Math.log(window.Math.tan(0.25*window.Math.PI+0.5*D.Q.kh(b)));return new D.L(a,D.Q.DI(c))};
D.Q.mwa=function(a,b,c){b=D.Q.kh(b);c=D.Q.kh(c);var d=D.Q.kh(a.x);a=D.Q.kh(a.y);return new D.L(window.Math.cos(c)*window.Math.sin(b-d)*D.Q.KP,(window.Math.cos(a)*window.Math.sin(c)-window.Math.sin(a)*window.Math.cos(c)*window.Math.cos(b-d))*D.Q.KP)};
D.Q.pwa=function(a,b){var c=window.Math.floor(window.Math.abs(b)/5);c>=D.Q.zl.length-1&&(c=D.Q.zl.length-2);var d=(window.Math.abs(b)-5*c)/5,e=a*(D.Q.zl[c][0]+d*(D.Q.zl[c+1][0]-D.Q.zl[c][0])),c=D.Q.zl[c][1]+d*(D.Q.zl[c+1][1]-D.Q.zl[c][1]);0>b&&(c*=-1);return new D.L(e,180*c)};D.Q.IJ=function(a,b){return new D.L(b.x*a.Qd+a.Bb,b.y*a.Qe+a.xb)};D.Q.eda=function(a,b){var c=a.Qd,d=a.Qe;return new D.jd(b.Qd*c,b.ng*c,b.Lf*d,b.Qe*d,a.Bb+b.Bb*c,a.xb+b.xb*d)};
D.Q.Hn=function(a,b){var c=b.x,d=b.y,e=a.g,f=a.j,g=0,g=b.g/e,h=b.j/f,g=g<=h?g:h,c=c-a.x*g,d=d+a.y*g,c=c+(b.g-e*g)/2,d=d+(b.j-(b.j-f*g)/2);return new D.jd(g,0,0,-g,c,d)};D.Q.kh=function(a){return a*(window.Math.PI/180)};D.Q.DI=function(a){return a*(180/window.Math.PI)};
D.Q.BKa=function(a,b,c){var d;a/=10;b/=10;switch(c){case "africa":d=D.Q.Kv(D.Q.eba,new D.L(a,b));d=D.Q.SK(d.x,d.y);break;case "asia":d=D.Q.Kv(D.Q.hba,new D.L(a,b),D.Q.kh(5));d=D.Q.FR(40,95,20,60,d.x,d.y);break;case "australia":d=D.Q.bwa(a,b);break;case "europe":d=D.Q.Kv(D.Q.tba,new D.L(a,b),D.Q.kh(10));d=D.Q.FR(35,25,40,65,d.x,d.y);break;case "northAmerica":d=D.Q.Kv(D.Q.Cba,new D.L(a,b));d=D.Q.FR(23,-96,20,60,d.x,d.y);break;case "southAmerica":d=D.Q.Kv(D.Q.Jba,new D.L(a,b),D.Q.kh(5));break;case "apac":d=
D.Q.Kv(D.Q.gba,new D.L(a,b));d=D.Q.SK(d.x,d.y);break;case "emea":d=D.Q.Kv(D.Q.rba,new D.L(a,b));d=D.Q.SK(d.x,d.y);break;case "latinAmerica":d=D.Q.Kv(D.Q.Bba,new D.L(a,b));break;case "usaAndCanada":d=D.Q.Kv(D.Q.Nba,new D.L(a,b));d=D.Q.FR(23,-96,20,60,d.x,d.y);break;case "worldRegions":d=D.Q.Cea(a,b);break;case "usa":d=D.Q.ewa(a,b);break;case "world":d=D.Q.Cea(a,b)}return d?d:new D.L(a,b)};
D.Q.ewa=function(a,b){var c;return(0,D.ze)(D.Q.fZ,a,b)?(c=D.Q.Hn(D.Q.fba,D.Q.fZ),c.su(),c=(0,D.Ae)(c,new D.L(a,b)),D.Q.SK(c.x,c.y)):(0,D.ze)(D.Q.jZ,a,b)?(c=D.Q.Hn(D.Q.xba,D.Q.jZ),c.su(),(0,D.Ae)(c,new D.L(a,b))):(0,D.ze)(D.Q.$u,a,b)?(c=D.Q.Hn(D.Q.Mba,D.Q.$u),c.su(),c=(0,D.Ae)(c,new D.L(a,b)),D.Q.cwa(new D.L(-95,36),c.x,c.y)):new D.L(a,b)};D.Q.Cea=function(a,b){var c=D.Q.Hn(D.Q.Oba,D.Q.$u);c.su();c=(0,D.Ae)(c,new D.L(a,b));return D.Q.dwa(c.x,c.y)};
D.Q.bwa=function(a,b){var c;c=(0,D.ze)(D.Q.mZ,a,b)?D.Q.Hn(D.Q.lZ,D.Q.mZ):D.Q.Hn(D.Q.iba,D.Q.$u);c.su();c=(0,D.Ae)(c,new D.L(a,b));return D.Q.SK(c.x,c.y)};D.Q.Kv=function(a,b,c){a=D.Q.Hn(a,D.Q.$u);if(c){var d=new D.jd;d.rotate(c);a=D.Q.eda(a,d)}a.su();return(0,D.Ae)(a,b)};
D.Q.FR=function(a,b,c,d,e,f){b=D.Q.kh(b);a=D.Q.kh(a);c=D.Q.kh(c);d=D.Q.kh(d);d=0.5*(window.Math.sin(c)+window.Math.sin(d));c=window.Math.pow(window.Math.cos(c),2)+2*d*window.Math.sin(c);a=c-2*d*window.Math.sin(a);a=window.Math.sqrt(a)/d;var g=window.Math.sqrt(e*e+(a-f)*(a-f));return new D.L(D.Q.DI(b+window.Math.atan(e/(a-f))/d),D.Q.DI(window.Math.asin((c-g*g*d*d)/(2*d))))};D.Q.SK=function(a,b){return new D.L(a,D.Q.DI(2*window.Math.atan(window.Math.exp(D.Q.kh(b)))-0.5*window.Math.PI))};
D.Q.cwa=function(a,b,c){b/=D.Q.KP;c/=D.Q.KP;var d=D.Q.kh(a.y),e=window.Math.sqrt(b*b+c*c),f=window.Math.asin(e);return new D.L(D.Q.DI(D.Q.kh(a.x)+window.Math.atan(b*window.Math.sin(f)/(e*window.Math.cos(d)*window.Math.cos(f)-c*window.Math.sin(d)*window.Math.sin(f)))),D.Q.DI(window.Math.asin(window.Math.cos(f)*window.Math.sin(d)+c*window.Math.sin(f)*window.Math.cos(d)/e)))};
D.Q.dwa=function(a,b){var c=window.Math.floor(window.Math.abs(b)/5);c>=D.Q.zl.length-1&&(c=D.Q.zl.length-2);var d=(window.Math.abs(b/180)-D.Q.zl[c][1])/(D.Q.zl[c+1][1]-D.Q.zl[c][1]),e=5*d+5*c,c=a/(D.Q.zl[c][0]+d*(D.Q.zl[c+1][0]-D.Q.zl[c][0]));0>b&&(e*=-1);return new D.L(c,e)};
D.fe=function(a,b,c,d,e,f,g){this.Init(a,b,c,d,e,f,g)};D.y.l(D.fe,D.ge,"DvtMapControlButton");
D.fe.prototype.Init=function(a,b,c,d,e,f,g){D.fe.o.Init.call(this,a,d,f);this.s_=e;this.sb=b;this.ta=g;(0,D.he)(this.sb,this.Bpa,this);this.sb.setCursor("pointer");a=new D.ie(this,D.n,D.n,D.n,D.n,D.n,0==this.s_?(0,D.ob)(this.jd,"CONTROL_PANEL_DRILLUP"):1==this.s_?(0,D.ob)(this.jd,"CONTROL_PANEL_DRILLDOWN"):2==this.s_?(0,D.ob)(this.jd,"CONTROL_PANEL_RESET"):D.n);this.ta.ka(this.sb,a);this.k(this.sb);this.wga=c;this.vfa=D.k};
D.fe.prototype.gh=function(a){this.B(a?1:0.4);this.sb.setCursor(a?"pointer":D.n);this.vfa=a;this.sb.gh(a);(0,D.je)(this.sb)};D.fe.prototype.Bpa=function(a){(0,D.ke)(a);this.vfa&&this.wga&&this.wga()};
D.le=function(a,b,c){this.Init(a,b,c)};D.y.l(D.le,D.me,"DvtThematicMapControlPanel");D.le.prototype.Init=function(a,b,c){D.le.o.Init.call(this,a,b,c);this.Wk=b.Wk;this.Il=(0,D.qe)(b);this.Cva=D.y.Ej(b,b.s5);this.Ava=D.y.Ej(b,b.uU);this.tza=D.y.Ej(b,b.d8);this.oF=this.pF=this.xia=D.n;this.Qda=this.Pda=D.p;this.D=b.ts()};D.re=function(a,b){a.Pda=b;a.oF&&a.oF.gh(b)};D.se=function(a,b){a.Qda=b;a.pF&&a.pF.gh(b)};
D.le.prototype.mJ=function(a){if(this.Wk&&"none"!=this.Wk){var b=(0,D.te)(this.D,"buttonWidth",0);this.xia=D.R.pBa(this.e,this.tza,this.ba,this.jd,this.Il,this.ta,this.D);a.k(this.xia);this.oF=D.R.dBa(this.e,this.Ava,this.ba,this.jd,this.Il,this.ta,this.D);this.oF.F(b);this.oF.gh(this.Pda);a.k(this.oF);this.pF=D.R.eBa(this.e,this.Cva,this.ba,this.jd,this.Il,this.ta,this.D);this.pF.F(2*b);this.pF.gh(this.Qda);a.k(this.pF)}};
});