"use strict";
/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojcollapsible"],function(a,f){(function(){a.Oa("oj.ojAccordion",f.oj.baseComponent,{widgetEventPrefix:"oj",options:{multiple:!1,expanded:null,beforeExpand:null,expand:null,beforeCollapse:null,collapse:null},_ComponentCreate:function(){this._super();this.element.addClass("oj-accordion oj-component").attr("role","group");this.Wb()},_OpenContextMenu:function(a,b){a.open(b,{launcher:this.element.find(".oj-collapsible-header-icon").first(),initialFocus:"menu"})},
_destroy:function(){this.element.removeClass("oj-accordion oj-component").removeAttr("role");this.element.children().removeClass("oj-accordion-collapsible");this.element.children(".oj-accordion-created").removeClass("oj-accordion-created").ojCollapsible("destroy")},_setOption:function(a,b,d){if("multiple"===a)!1==b&&!0==this.options.multiple&&this.element.children(".oj-expanded").first().siblings(".oj-collapsible").ojCollapsible("collapse",!1);else if("expanded"===a){this.XT(b);return}this._super(a,
b,d)},refresh:function(){this._super();this.Wb()},Wb:function(){this.aS();this._setOption("disabled",this.options.disabled);this._setOption("expanded",this.options.expanded);this.Nj()},aS:function(){this.element.children(":oj-collapsible").each(function(){f(this).ojCollapsible("option","expandArea","header")});this.Ch=this.element.children().not(":oj-ojCollapsible").ojCollapsible({expandArea:"header"}).addClass("oj-accordion-created").end().addClass("oj-accordion-collapsible")},Nj:function(){var a=
{keydown:this.Fj,ojbeforeexpand:this.aN,ojexpand:this.RO,ojbeforecollapse:this.ZM,ojcollapse:this.CN};this._off(this.Ch);this._on(this.Ch,a)},Fj:function(a){if(!a.altKey&&!a.ctrlKey&&(f(a.target).hasClass("oj-collapsible-header")||f(a.target).hasClass("oj-collapsible-header-icon"))){var b=f.ui.keyCode,d=this.Ch.not(".oj-disabled"),e=d.length,g=f(a.target).closest(".oj-collapsible"),h=d.index(g),k=!1;if(0<=h)switch(a.keyCode){case b.RIGHT:case b.DOWN:k=d[(h+1)%e];break;case b.LEFT:case b.UP:k=d[(h-
1+e)%e];break;case b.HOME:k=d[0];break;case b.END:k=d[e-1]}k&&(g&&f(g).trigger("ojfocusout"),f(k).trigger("ojfocus"),a.preventDefault())}},lC:function(a){return!this.options.multiple&&(a=f(a.target).closest(".oj-collapsible"),a.parent().is(":oj-ojAccordion"))?a.siblings(".oj-collapsible.oj-expanded").map(function(){return f(this).data("oj-ojCollapsible")}):f()},aN:function(a){if(!this.dr(a))return!0;var b,d=this,e;this.lC(a).each(function(){var g=this.element;e=d.Vk(g,f(a.target));g={header:g.find(".oj-collapsible-header"),
content:g.find(".oj-collapsible-content")};return b=this._trigger("beforeCollapse",a,g)});e||(e=d.Vk(null,f(a.target)));this.options.multiple||this._trigger("beforeExpand",a,e);return b},RO:function(a,b){if(this.dr(a)){var d,e=this;this.lC(a).each(function(){this.collapse(!1,a,b);d=e.Vk(this.element,f(a.target))});d||(d=e.Vk(null,f(a.target)));this.options.multiple||this._trigger("expand",a,d);this.ix()}},ZM:function(a,b){return this.dr(a)&&!this.options.multiple?this._trigger("beforeCollapse",a,
this.yD(a,b)):!0},CN:function(a,b){if(this.dr(a)){var d=this.yD(a,b);this.options.multiple||this._trigger("collapse",a,d);this.ix()}},Vk:function(a,b){return{fromCollapsible:a,toCollapsible:b}},yD:function(a,b){var d;if(b.toCollapsible)d=b;else{if(a.originalEvent&&a.originalEvent.target){var e=f(a.originalEvent.target);e.hasClass("oj-collapsible")&&(d=this.Vk(f(a.target),e))}d||(d=this.Vk(f(a.target),null))}return d},dr:function(a){return f(a.target).is(this.Ch)},ix:function(){var a,b=[];this.Ch.each(function(d){f(this).ojCollapsible("option",
"expanded")&&(a=f(this).attr("id"),b.push(a?a:d))});this.options.expanded=b},XT:function(a){var b={};this.Ch.each(function(a){var c=f(this).attr("id");c&&(b[c]=a)});var d=[];if(Array.isArray(a))for(var e,g=0;g<a.length;g++)e=a[g],"string"===typeof e?void 0!==b[e]&&(d[b[e]]=!0):"number"===typeof e&&(d[e]=!0);for(g=0;g<d.length;g++)f(this.Ch[g]).ojCollapsible("option","expanded",!!d[g]);this.ix()},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;var b=a.subId;a=a.index;
if("number"!==typeof a||0>a||a>=this.Ch.length)return null;a=this.Ch[a];switch(b){case "oj-accordion-content":b="oj-collapsible-content";break;case "oj-accordion-header":b="oj-collapsible-header";break;case "oj-accordion-header-icon":b="oj-collapsible-header-icon";break;case "oj-accordion-collapsible":return a;default:return null}return f(a).ojCollapsible("getNodeBySubId",{subId:b})}})})()});
//# sourceMappingURL=oj-modular.map