/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(a,f){(function(){function c(a,b){var c=a.name,d=a.form;c?(c=c.replace(/'/g,"\\'"),c=":radio[name\x3d'"+c+"']:oj-button",d=b?b.filter(c):d?f(d).find(c):f(c,a.ownerDocument).filter(function(){return!this.form})):d=(b?b.filter(a):f(a)).filter(":oj-button");return d}a.Oa("oj.ojButton",f.oj.baseComponent,{defaultElement:"\x3cbutton\x3e",widgetEventPrefix:"oj",options:{disabled:null,display:"all",label:null,icons:{start:void 0,end:void 0},menu:null},
_create:function(){this.element.closest("form").unbind("reset"+e).bind("reset"+e,function(){var a=f(this);setTimeout(function(){a.find(":oj-button").each(function(){f(this).data("oj-ojButton").Pp(!1)}).length||a.unbind("reset"+e)},1)});"boolean"!==typeof this.options.disabled&&(this.options.disabled=!!this.element.prop("disabled"));this.Nl=this.eventNamespace+"menu";this.eR();this.Vx=!!this.pb.attr("title");var a=this,c=this.options,h=this.er,k=h?"":"oj-active";this.pb.addClass(g);this.tc.bind("mouseenter"+
this.eventNamespace,function(){a.ed()||(this===b&&a.pb.addClass("oj-active"),a.pb.addClass("oj-hover").removeClass("oj-default oj-focus-only"))}).bind("mouseleave"+this.eventNamespace,function(){a.pb.removeClass("oj-hover");a.ed()||(a.pb.removeClass(k),a.Lf())}).bind("click"+this.eventNamespace,function(b){var c=a.ed();c&&b.preventDefault();c&&b.stopImmediatePropagation()});this.element.attr("role","button").bind("focus"+this.eventNamespace,function(){a.pb.addClass("oj-focus");a.Lf()}).bind("blur"+
this.eventNamespace,function(){a.pb.removeClass("oj-focus");a.Lf()});h&&(this.element.bind("change"+this.eventNamespace,function(b){a.Pp(!0);var c=f(this).closest(":oj-buttonset").data("oj-ojButtonset"),d=c&&c.Ru(c.Wc);c&&void 0!==d&&(c.DE=b,c._setOption("checked",d))}),this.tc.bind("mousedown"+this.eventNamespace,function(){a.ed()||(d=this,a.document.one("mouseup",function(){d=null}))}).bind("mouseup"+this.eventNamespace,function(){a.ed()||this!==d||a.element.focus()}));"checkbox"===this.type?(this.tc.bind("click"+
this.eventNamespace,function(){if(a.ed())return!1}),this.element.bind("keyup"+this.eventNamespace,function(b){b.keyCode===f.ui.keyCode.ENTER&&(a.ed()||a.element.click())})):"radio"===this.type?(this.tc.bind("click"+this.eventNamespace,function(){if(a.ed())return!1}),this.element.bind("keyup"+this.eventNamespace,function(b){b.keyCode!==f.ui.keyCode.ENTER||a.element[0].checked||a.ed()||(a.element[0].checked=!0,a.element.change(),a.element.click())})):(this.tc.bind("mousedown"+this.eventNamespace,function(c){if(a.ed())return!1;
1===c.which&&(f(this).addClass("oj-active").removeClass("oj-default oj-focus-only"),b=this,a.document.one("mouseup",function(){b=null}))}).bind("mouseup"+this.eventNamespace,function(){if(a.ed())return!1;f(this).removeClass("oj-active");a.Lf()}).bind("keydown"+this.eventNamespace,function(b){if(a.ed())return!1;var c=b.keyCode===f.ui.keyCode.SPACE;"anchor"===a.type&&c&&b.preventDefault();(c||b.keyCode===f.ui.keyCode.ENTER)&&f(this).addClass("oj-active").removeClass("oj-default oj-focus-only")}).bind("keyup"+
this.eventNamespace+" blur"+this.eventNamespace,function(){f(this).removeClass("oj-active");a.Lf()}),"anchor"===this.type&&(h=this.tc.attr("tabindex"),("undefined"===h||null===h||isNaN(h))&&this.tc.attr("tabindex","0"),this.tc.bind("keyup"+this.eventNamespace,function(a){a.keyCode===f.ui.keyCode.SPACE&&f(this).click()})));this._setOption("disabled",c.disabled);this.JQ();this.$B();this.Lf();this._super()},eR:function(){var a;if(this.element.is("input[type\x3dcheckbox]"))this.type="checkbox",this.er=
!0;else if(this.element.is("input[type\x3dradio]"))this.type="radio",this.er=!0;else if(this.element.is("input[type\x3dbutton],input[type\x3dsubmit],input[type\x3dreset]"))this.type="inputPush";else if(this.element.is("button"))this.type="button";else if(this.element.is("a"))this.type="anchor";else throw Error("JET Button not supported on this element type");this.er?(a="label[for\x3d'"+this.element.attr("id")+"']",this.tc=this.element.siblings().filter(a).addClass("oj-button-label"),this.element.addClass("oj-helper-hidden-accessible").add(this.tc).wrapAll("\x3cspan\x3e\x3c/span\x3e"),
this.pb=this.element.parent(),(a=this.element[0].checked)&&this.pb.addClass("oj-selected").removeClass("oj-default oj-focus-only"),this.element.attr("aria-pressed",a)):this.pb=this.tc=this.element},widget:function(){return this.pb},_destroy:function(){this.vF();this.element.removeClass("oj-helper-hidden-accessible").removeAttr("role").removeAttr("aria-pressed");var a=this.er;a||this.pb.removeClass(g+" "+h+" "+k);this.tc.html(this.tc.find(".oj-button-text").html());if(a){this.tc.removeClass("oj-button-label");
var b=this;setTimeout(function(){b.pb.parent().length&&b.element.unwrap()},0)}else this.Vx||this.pb.removeAttr("title");d===this.tc[0]&&(d=null)},bA:function(){this.pb.removeClass("oj-active oj-hover oj-focus");this.Lf()},Dm:function(a){this._super(a);this.QG()},QG:function(){var a=this.ed();this.pb.toggleClass("oj-disabled",a);this.pb.toggleClass("oj-enabled",!a);"anchor"!==this.type?(this.element.prop("disabled",a),this.pb.removeAttr("aria-disabled")):this.pb.attr("aria-disabled",a);a?(this.widget().removeClass("oj-active oj-default oj-focus-only oj-hover oj-focus"),
b=null,this.Au()):this.Lf()},_setOption:function(a,b,c){this._super(a,b,c);switch(a){case "disabled":this.QG();break;case "label":this.bU();break;case "display":"inputPush"!==this.type&&this.Cr();break;case "icons":this.ZT(!0);break;case "menu":this.$B()}},refresh:function(){this._super();this.OA&&!f(this).closest(":oj-buttonset").length&&this.Dm(!1)},Pp:function(a){"radio"===this.type?(a?c(this.element[0]):this.element).each(function(){var a=f(this).data("oj-ojButton");this.checked?(a.pb.addClass("oj-selected").removeClass("oj-default oj-focus-only"),
a.element.attr("aria-pressed","true")):(a.pb.removeClass("oj-selected"),a.Lf(),a.element.attr("aria-pressed","false"))}):"checkbox"===this.type&&(this.element[0].checked?(this.pb.addClass("oj-selected").removeClass("oj-default oj-focus-only"),this.element.attr("aria-pressed","true")):(this.pb.removeClass("oj-selected"),this.Lf(),this.element.attr("aria-pressed","false")))},JQ:function(){var a=!1;null===this.options.label&&(a=!0,this.options.label="inputPush"===this.type?this.tc.val():this.tc.html());
if("inputPush"===this.type)this.bG();else{a=this.aU(a);void 0===this.options.icons.end&&(this.options.icons.end=this.options.menu?"oj-component-icon oj-button-menu-dropdown-icon":null);var b=this.Dr(!0),c=this.Dr(!1);this.Cr(a,b,c)}},aU:function(a){var b=this.tc,c=f("\x3cspan class\x3d'oj-button-text'\x3e\x3c/span\x3e",this.document[0]);a?c.append(b.contents()):(b.empty(),c.text(this.options.label));b.append(c);return c},bU:function(){if("inputPush"===this.type)this.bG();else{var a=this.tc.find(".oj-button-text");
a.text(this.options.label);this.Cr(a)}},bG:function(){this.options.label&&this.element.val(this.options.label)},ZT:function(){if("inputPush"!==this.type){var a=this.Dr(!0),b=this.Dr(!1);this.Cr(void 0,a,b)}},Dr:function(a){if(a){var b=".oj-button-icon.oj-start";a="oj-button-icon oj-start";var c=this.options.icons.start,d="_lastStartIcon",e="prependTo"}else b=".oj-button-icon.oj-end",a="oj-button-icon oj-end",c=this.options.icons.end,d="_lastEndIcon",e="appendTo";b=this.tc.find(b);c?(b.length?b.removeClass(this[d]):
b=f("\x3cspan\x3e\x3c/span\x3e").addClass(a)[e](this.tc),b.addClass(c)):b.remove();this[d]=c;return!!c},Cr:function(a,b,c){void 0===a&&(a=this.tc.find(".oj-button-text"));void 0===b&&(b=!!this.options.icons.start);void 0===c&&(c=!!this.options.icons.end);var d=b&&c;c=b||c;var e="icons"===this.options.display;c&&e?(a.addClass("oj-helper-hidden-accessible"),this.Vx||(a=a.text(),this.pb.attr("title",f.trim(a)))):(a.removeClass("oj-helper-hidden-accessible"),this.Vx||this.pb.removeAttr("title"));b=c?
e?d?"oj-button-icons-only":"oj-button-icon-only":d?"oj-button-text-icons":b?"oj-button-text-icon-start":"oj-button-text-icon-end":"oj-button-text-only";this.pb.removeClass(k).addClass(b)},$B:function(){if(this.options.menu&&this.element.is("input"))throw Error("Menu Button functionality is not supported on input elements.");this.vF();if(this.options.menu){var a=this;this.element.attr("aria-haspopup",!0).on("keydown"+this.Nl,function(b){if(b.which===f.ui.keyCode.DOWN)a.oG(b,"firstItem"),b.preventDefault();
else if(b.which===f.ui.keyCode.ESCAPE)return a.Au(b),!1;return!0}).on("click"+this.Nl,function(b){var c=a.OC();c.Ip||a.oG(b,"firstItem");c.Ip=!1;b.preventDefault();return!0})}},FO:function(a){this.Za=a;var b=this;a.widget().on("oj__dismiss"+this.Nl,function(a){b.mE(a)}).on("ojbeforeopen"+this.Nl,function(a){b.$D||b.mE(a);b.$D=!1})},vF:function(){this.element.removeAttr("aria-haspopup").off(this.Nl);this.Au();this.Za&&this.Za.widget().off(this.Nl);this.Za=void 0},OC:function(){var b=this.Za;b||((b=
f(this.options.menu).data("oj-ojMenu"))?this.FO(b):this.options.menu&&a.D.warn('JET Button: "menu" option specified, but does not reference a valid JET Menu.'));return b},oG:function(a,b){if(!this.ed()){var c=this.OC();c&&(this.pb.addClass("oj-selected").removeClass("oj-default oj-focus-only"),this.$D=!0,c.open(a,{launcher:this.element,initialFocus:b}),this.nE=!0)}},Au:function(a){this.nE&&(this.Za.Ct(a,!0),this.Za.Hp(a))},mE:function(){if("button"===this.type||"anchor"===this.type)this.pb.removeClass("oj-selected"),
this.Lf();this.nE=!1},Lf:function(){var a,b;this.pb.is(".oj-hover, .oj-active, .oj-selected, .oj-disabled")?b=a=!1:(b=this.pb.is(".oj-focus"),a=!b);this.pb.toggleClass("oj-default",a);this.pb.toggleClass("oj-focus-only",b)}});a.Oa("oj.ojButtonset",f.oj.baseComponent,{OR:"button, input[type\x3dbutton], input[type\x3dsubmit], input[type\x3dreset], input[type\x3dcheckbox], input[type\x3dradio], a",widgetEventPrefix:"oj",options:{checked:void 0,focusManagement:"oneTabstop",optionChange:null},UF:function(a,
b){var c=f.type(a);if("string"===c||"null"===c)return(c=((c=b[0].name)||1>=b.length)&&b.filter("input[type\x3dradio][name\x3d"+c+"]").length===b.length&&(null===a||b.filter("[value\x3d"+a+"]").length))&&b.each(function(){this.checked=this.value===a}),c;if("array"===c){var c=b.filter("input[type\x3dcheckbox]").length===b.length,d;(c=c&&a.concat().sort().every(function(a){var c=a!==d&&b.filter("[value\x3d"+a+"]").length;d=a;return c}))&&b.each(function(){this.checked=-1<a.indexOf(this.value)});return c}return!1},
Ru:function(a){var b=void 0,c=null,d=null;a.each(function(){if("input"!==this.tagName.toLowerCase())return b=void 0,!1;var a=this.type.toLowerCase(),e;if("radio"===a)a=!0,e=this.name.toLowerCase();else if("checkbox"===a)a=!1,e=null;else return b=void 0,!1;if(void 0!==b&&(a!==c||e!==d||c&&!d))return b=void 0,!1;void 0===b?(b=a?this.checked?this.value:null:this.checked?[this.value]:[],c=a,d=e):this.checked&&(c?b=this.value:b.push(this.value))});return b},rN:function(a,b){return a===b?!0:"array"===f.type(a)&&
"array"===f.type(b)&&!f(a).not(b).length&&!f(b).not(a).length},_create:function(){this.element.addClass("oj-buttonset oj-component");"oneTabstop"===this.options.focusManagement&&this.element.attr("role","toolbar");this.sb(!0);this._super()},_OpenContextMenu:function(a,b){a.open(b,{launcher:this.element.find(":oj-button[tabindex\x3d0]"),initialFocus:"menu"})},XE:function(a){a=!!a;this.Wc.each(function(){f(this).data("oj-ojButton").Dm(a)})},_setOption:function(a,b){var c=!1,d=this.DE;this.DE=null;"disabled"===
a&&this.XE(b);"checked"!==a||d||null===b&&void 0===this.Ru(this.Wc)||(this.UF(b,this.Wc)?this.Wc.each(function(){f(this).data("oj-ojButton").Pp(!1)}):c=!0);c||(c=this.options[a],this._superApply(arguments),"checked"===a&&this.Oc(a,c,b,this.rN,d))},Oc:function(a,b,c,d,e){d.call(this,b,c)||this._trigger("optionChange",e,{option:a,previousValue:b,value:c,optionMetadata:{writeback:e?"shouldWrite":"shouldNotWrite"}})},refresh:function(){this._super();this.sb(!1)},sb:function(a){var b=this;this.Eg="rtl"===
this.Ec();this.Wc=this.element.find(this.OR);if(a&&!this.UF(this.options.checked,this.Wc)){var c=this.Ru(this.Wc);this.options.checked=void 0===c?null:c}this.Wc.filter(":oj-button").ojButton("refresh").each(function(){f(this).data("oj-ojButton").Pp(!1)}).end().not(":oj-button").ojButton().end().map(function(){return f(this).ojButton("widget")[0]}).removeClass("oj-buttonset-first oj-buttonset-last").filter(":first").addClass("oj-buttonset-first").end().filter(":last").addClass("oj-buttonset-last").end().end();
this.XE(this.options.disabled);"oneTabstop"===this.options.focusManagement&&(this.Wc.unbind("keydown"+this.eventNamespace).bind("keydown"+this.eventNamespace,function(a){b.Jv(a,f(this))}).unbind("click"+this.eventNamespace).bind("click"+this.eventNamespace,function(){f(this).data("oj-ojButton").ed()||b.Mj(f(this))}).unbind("focus"+this.eventNamespace).bind("focus"+this.eventNamespace,function(){b.Mj(f(this))}),this.Qg=this.Wc.filter(function(){return!f(this).data("oj-ojButton").ed()}),this.Tv(a))},
Tv:function(a){var b=f(this.Gj);this.Gj=void 0;this.Wc.attr("tabindex","-1");a=a||!b.is(this.Qg)?this.Qg.first():b;this.Mj(a)},gw:function(a){var b=this.Qg;return a.map(function(a,d){if("radio"!=d.type||d.checked||""==d.name)return d;var e=c(d,b).filter(":checked");return e.length?e[0]:d})},Mj:function(a){a=this.gw(a);var b=a[0],c=this.Gj;b!==c&&(f(c).attr("tabindex","-1"),a.attr("tabindex","0"),this.Gj=b)},Jv:function(a,b){switch(a.which){case f.ui.keyCode.LEFT:case f.ui.keyCode.RIGHT:a.preventDefault();
var c=this.Qg,d=c.length;if(2>d)break;var e=c.index(b);c.eq((e+(a.which==f.ui.keyCode.RIGHT^this.Eg?1:-1)+d)%d).focus();break;case f.ui.keyCode.UP:case f.ui.keyCode.DOWN:"radio"==b.attr("type")&&a.preventDefault()}},_destroy:function(){this.element.removeClass("oj-buttonset oj-component").removeAttr("role");"oneTabstop"===this.options.focusManagement&&this.Wc.attr("tabindex","0");this.Wc.map(function(){return f(this).ojButton("widget")[0]}).removeClass("oj-buttonset-first oj-buttonset-last").end().ojButton("destroy")}});
var b,d,e=".ojButton",g="oj-button oj-component oj-enabled oj-default",h="oj-hover oj-active oj-selected",k="oj-button-icons-only oj-button-icon-only oj-button-text-icons oj-button-text-icon-start oj-button-text-icon-end oj-button-text-only"})()});
//# sourceMappingURL=oj-modular.map