"use strict";
/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojdvt-base","ojs/internal-deps/dvt/DvtChart"],function(a,f){a.Oh=function(a){this.f=a};o_("ChartAxis",a.Oh,a);a.Oh.prototype.getTitle=function(){return this.f?this.f.title:null};a.b.g("ChartAxis.prototype.getTitle",{getTitle:a.Oh.prototype.getTitle});a.Oh.prototype.Ei=function(){return this.f?this.f.bounds:null};a.b.g("ChartAxis.prototype.getBounds",{Ei:a.Oh.prototype.Ei});a.bf=function(a){this.f=a};o_("SparkChartDataItem",a.bf,a);a.bf.prototype.qo=
function(){return this.f?this.f.borderColor:null};a.b.g("SparkChartDataItem.prototype.getBorderColor",{qo:a.bf.prototype.qo});a.bf.prototype.od=function(){return this.f?this.f.color:null};a.b.g("SparkChartDataItem.prototype.getColor",{od:a.bf.prototype.od});a.bf.prototype.getDate=function(){return this.f?this.f.date:null};a.b.g("SparkChartDataItem.prototype.getDate",{getDate:a.bf.prototype.getDate});a.bf.prototype.getFloatValue=function(){return this.f?this.f.floatValue:null};a.b.g("SparkChartDataItem.prototype.getFloatValue",
{getFloatValue:a.bf.prototype.getFloatValue});a.bf.prototype.Bg=function(){return this.f?this.f.value:null};a.b.g("SparkChartDataItem.prototype.getValue",{Bg:a.bf.prototype.Bg});a.Oa("oj.ojChart",f.oj.dvtBaseComponent,{version:"1.0.0",widgetEventPrefix:"oj",options:{categoryFilter:null,categoryHighlight:null,optionChange:null,select:null,selectInput:null,viewportChange:null,viewportChangeInput:null},Cf:function(a,b,d){return DvtChart.newInstance(a,b,d)},pA:function(){this._super();this.options.styleDefaults||
(this.options.styleDefaults={});if(!this.options.styleDefaults.colors){var c=new a.Rg;this.options.styleDefaults.colors=c.Jl()}},ef:function(){var a=this._super();a.push("oj-chart");return a},aj:function(){var a=this._super();a["oj-chart-footnote"]={path:"footnote/style",property:"CSS_TEXT_PROPERTIES"};a["oj-chart-slice-label"]={path:"styleDefaults/sliceLabelStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-chart-subtitle"]={path:"subtitle/style",property:"CSS_TEXT_PROPERTIES"};a["oj-chart-title"]={path:"title/style",
property:"CSS_TEXT_PROPERTIES"};a["oj-chart-xaxis-tick-label"]={path:"xAxis/tickLabel/style",property:"CSS_TEXT_PROPERTIES"};a["oj-chart-xaxis-title"]={path:"xAxis/titleStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-chart-yaxis-tick-label"]={path:"yAxis/tickLabel/style",property:"CSS_TEXT_PROPERTIES"};a["oj-chart-yaxis-title"]={path:"yAxis/titleStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-chart-y2axis-tick-label"]={path:"y2Axis/tickLabel/style",property:"CSS_TEXT_PROPERTIES"};a["oj-chart-y2axis-title"]=
{path:"y2Axis/titleStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-legend"]={path:"legend/textStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-legend-title"]={path:"legend/titleStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-chart-pan-icon"]={path:"_resources/panUp",property:"CSS_URL"};a["oj-chart-pan-icon oj-active"]={path:"_resources/panDown",property:"CSS_URL"};a["oj-chart-select-icon"]={path:"_resources/selectUp",property:"CSS_URL"};a["oj-chart-select-icon oj-active"]={path:"_resources/selectDown",property:"CSS_URL"};
a["oj-chart-zoom-icon"]={path:"_resources/zoomUp",property:"CSS_URL"};a["oj-chart-zoom-icon oj-active"]={path:"_resources/zoomDown",property:"CSS_URL"};return a},bj:function(){return"categoryFilter categoryHighlight optionChange select selectInput viewportChange viewportChangeInput".split(" ")},wm:function(){var a=this._super();a["DvtChartBundle.DEFAULT_GROUP_NAME"]=this.pc("labelDefaultGroupName",["groupName"]);a["DvtChartBundle.EMPTY_TEXT"]=this.pc("msgNoData");a["DvtChartBundle.INVALID_DATA"]=
this.pc("msgInvalidData");a["DvtChartBundle.LABEL_SERIES"]=this.pc("labelSeries",["seriesName"]);a["DvtChartBundle.LABEL_GROUP"]=this.pc("labelGroup",["groupName"]);a["DvtChartBundle.LABEL_VALUE"]=this.pc("labelValue",["value"]);a["DvtChartBundle.LABEL_TARGET_VALUE"]=this.pc("labelTargetValue",["targetValue"]);a["DvtChartBundle.LABEL_X"]=this.pc("labelX",["x"]);a["DvtChartBundle.LABEL_Y"]=this.pc("labelY",["y"]);a["DvtChartBundle.LABEL_Z"]=this.pc("labelZ",["z"]);a["DvtChartBundle.LABEL_LOW"]=this.pc("labelLow",
["low"]);a["DvtChartBundle.LABEL_HIGH"]=this.pc("labelHigh",["high"]);a["DvtChartBundle.LABEL_OTHER"]=this.pc("labelOther");a["DvtChartBundle.PAN"]=this.pc("tooltipPan");a["DvtChartBundle.MARQUEE_SELECT"]=this.pc("tooltipSelect");a["DvtChartBundle.MARQUEE_ZOOM"]=this.pc("tooltipZoom");return a},cj:function(a){var b=a&&a.getType?a.getType():null;if(b===DvtSelectionEvent.TYPE||b===DvtSelectionEvent.TYPE_INPUT){var d=a.getSelection();if(d){for(var e=[],f=0;f<d.length;f++){var h={id:d[f].getId(),series:d[f].getSeries(),
group:d[f].getGroup()};e.push(h)}b===DvtSelectionEvent.TYPE&&this.$g("selectedItems",e);a={items:e,endGroup:a.getEndGroup(),startGroup:a.getStartGroup(),xMax:a.getXMax(),xMin:a.getXMin(),yMax:a.getYMax(),yMin:a.getYMin()};this._trigger(b===DvtSelectionEvent.TYPE?"select":"selectInput",null,a)}}else if(b===DvtCategoryHideShowEvent.TYPE_HIDE||b===DvtCategoryHideShowEvent.TYPE_SHOW){d=b===DvtCategoryHideShowEvent.TYPE_HIDE?"out":"in";e=this.options.series;for(f=0;f<e.length;f++)e[f].name==a.getCategory()&&
(e[f].visibility=b===DvtCategoryHideShowEvent.TYPE_HIDE?"hidden":"visible");this._trigger("categoryFilter",null,{category:a.getCategory(),type:d})}else b===DvtCategoryRolloverEvent.TYPE_OVER||b===DvtCategoryRolloverEvent.TYPE_OUT?(b=b===DvtCategoryRolloverEvent.TYPE_OVER?"on":"off",this._trigger("categoryHighlight",null,{categories:[a.getCategory()],type:b})):b===DvtChartViewportChangeEvent.TYPE||b===DvtChartViewportChangeEvent.TYPE_INPUT?(a={endGroup:a.getEndGroup(),startGroup:a.getStartGroup(),
xMax:a.getXMax(),xMin:a.getXMin(),yMax:a.getYMax(),yMin:a.getYMin()},this._trigger(b===DvtChartViewportChangeEvent.TYPE?"viewportChange":"viewportChangeInput",null,a)):this._super(a)},kt:function(){null==this.options._resources&&(this.options._resources={});var c=this.options._resources;c.overviewGrippy=a.ia.jb("resources/internal-deps/dvt/chart/drag_horizontal.png");c.panCursorDown=a.ia.jb("resources/internal-deps/dvt/chart/hand-closed.cur");c.panCursorUp=a.ia.jb("resources/internal-deps/dvt/chart/hand-open.cur")},
xk:function(a){return"selectedItems"==a},getNodeBySubId:function(a){return this._super(a)},getSubIdByNode:function(a){return this._super(a)},getTitle:function(){return this.Va.getAutomation().getTitle()},getGroup:function(a){return this.Va.getAutomation().getGroup(a)},getSeries:function(a){return this.Va.getAutomation().getSeries(a)},getGroupCount:function(){return this.Va.getAutomation().getGroupCount()},getSeriesCount:function(){return this.Va.getAutomation().getSeriesCount()},getDataItem:function(c,
b){var d=this.Va.getAutomation();return new a.Lb(d.getDataItem(c,b))},getLegend:function(){var c=this.Va.getAutomation();return new a.jk(c.getLegend())},getPlotArea:function(){var c=this.Va.getAutomation();return new a.fp(c.getPlotArea())},getXAxis:function(){var c=this.Va.getAutomation();return new a.Oh(c.getXAxis())},getYAxis:function(){var c=this.Va.getAutomation();return new a.Oh(c.getYAxis())},getY2Axis:function(){var c=this.Va.getAutomation();return new a.Oh(c.getY2Axis())}});a.fp=function(a){this.f=
a};o_("ChartPlotArea",a.fp,a);a.fp.prototype.Ei=function(){return this.f?this.f.bounds:null};a.b.g("ChartPlotArea.prototype.getBounds",{Ei:a.fp.prototype.Ei});a.jk=function(a){this.f=a};o_("ChartLegend",a.jk,a);a.jk.prototype.getTitle=function(){return this.f?this.f.title:null};a.b.g("ChartLegend.prototype.getTitle",{getTitle:a.jk.prototype.getTitle});a.jk.prototype.Ei=function(){return this.f?this.f.bounds:null};a.b.g("ChartLegend.prototype.getBounds",{Ei:a.jk.prototype.Ei});a.Oa("oj.ojSparkChart",
f.oj.dvtBaseComponent,{version:"1.0.0",widgetEventPrefix:"oj",Cf:function(a,b,d){return DvtSparkChart.newInstance(a,b,d)},ef:function(){var a=this._super();a.push("oj-sparkchart");return a},hg:function(){this.element.attr("title")?(this.options.shortDesc=this.element.attr("title"),this.element.data(this.element,"title",this.element.attr("title")),this.element.removeAttr("title")):this.element.data("title")&&(this.options.shortDesc=this.element.data("title"));this._super()},getNodeBySubId:function(a){return this._super(a)},
getSubIdByNode:function(a){return this._super(a)},getDataItem:function(c){var b=this.Va.getAutomation();return new a.bf(b.getDataItem(c))}});a.Lb=function(a){this.f=a};o_("ChartDataItem",a.Lb,a);a.Lb.prototype.getGroup=function(){return this.f?this.f.group:null};a.b.g("ChartDataItem.prototype.getGroup",{getGroup:a.Lb.prototype.getGroup});a.Lb.prototype.getSeries=function(){return this.f?this.f.series:null};a.b.g("ChartDataItem.prototype.getSeries",{getSeries:a.Lb.prototype.getSeries});a.Lb.prototype.qo=
function(){return this.f?this.f.borderColor:null};a.b.g("ChartDataItem.prototype.getBorderColor",{qo:a.Lb.prototype.qo});a.Lb.prototype.od=function(){return this.f?this.f.color:null};a.b.g("ChartDataItem.prototype.getColor",{od:a.Lb.prototype.od});a.Lb.prototype.pe=function(){return this.f?this.f.label:null};a.b.g("ChartDataItem.prototype.getLabel",{pe:a.Lb.prototype.pe});a.Lb.prototype.Bg=function(){return this.f?this.f.value:null};a.b.g("ChartDataItem.prototype.getValue",{Bg:a.Lb.prototype.Bg});
a.Lb.prototype.jI=function(){return this.f?this.f.targetValue:null};a.b.g("ChartDataItem.prototype.getTargetValue",{jI:a.Lb.prototype.jI});a.Lb.prototype.te=function(){return this.f?this.f.tooltip:null};a.b.g("ChartDataItem.prototype.getTooltip",{te:a.Lb.prototype.te});a.Lb.prototype.lI=function(){return this.f?this.f.x:null};a.b.g("ChartDataItem.prototype.getX",{lI:a.Lb.prototype.lI});a.Lb.prototype.mI=function(){return this.f?this.f.y:null};a.b.g("ChartDataItem.prototype.getY",{mI:a.Lb.prototype.mI});
a.Lb.prototype.nI=function(){return this.f?this.f.z:null};a.b.g("ChartDataItem.prototype.getZ",{nI:a.Lb.prototype.nI});a.Lb.prototype.isSelected=function(){return this.f?this.f.selected:!1};a.b.g("ChartDataItem.prototype.isSelected",{isSelected:a.Lb.prototype.isSelected})});
//# sourceMappingURL=oj-modular.map