var o_a=this;function o_(a,f,c){a=a.split(".");c=c||o_a;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var b;a.length&&(b=a.shift());)a.length||void 0===f?c=c[b]?c[b]:c[b]={}:c[b]=f};define(["require","ojL10n!ojtranslations/nls/ojtranslations"],function(a,f){var c={};"undefined"!==typeof window?c=window:"undefined"!==typeof self&&(c=self);var b=c.oj,d=c.oj={version:"1.0",build:"3157",revision:"10321",noConflict:function(){c.oj=b}};d.D={};o_("Logger",d.D,d);d.D.RJ=0;o_("Logger.LEVEL_NONE",d.D.RJ,d);d.D.Rs=1;o_("Logger.LEVEL_ERROR",d.D.Rs,d);d.D.Qh=2;o_("Logger.LEVEL_WARN",d.D.Qh,d);d.D.cz=3;o_("Logger.LEVEL_INFO",d.D.cz,d);d.D.dz=4;o_("Logger.LEVEL_LOG",
d.D.dz,d);d.D.iL="error";d.D.lL="warn";d.D.jL="info";d.D.kL="log";d.D.MB={level:d.D.Rs,writer:null};d.D.Wa=d.D.MB;d.D.error=function(a){d.D.fo(d.D.Rs,d.D.iL,arguments)};o_("Logger.error",d.D.error,d);d.D.info=function(a){d.D.fo(d.D.cz,d.D.jL,arguments)};o_("Logger.info",d.D.info,d);d.D.warn=function(a){d.D.fo(d.D.Qh,d.D.lL,arguments)};o_("Logger.warn",d.D.warn,d);d.D.log=function(a){d.D.fo(d.D.dz,d.D.kL,arguments)};o_("Logger.log",d.D.log,d);d.D.option=function(a,c){var b={},f;if(0==arguments.length){for(f in d.D.Wa)d.D.Wa.hasOwnProperty(f)&&
(b[f]=d.D.Wa[f]);return b}if("string"===typeof a&&void 0===c)return void 0===d.D.Wa[a]?null:d.D.Wa[a];if("string"===typeof a)d.D.Wa[a]=c;else for(f in a)a.hasOwnProperty(f)&&d.D.option(f,a[f])};o_("Logger.option",d.D.option,d);d.D.fo=function(a,c,b){if(!(d.D.option("level")<a)){var f=d.D.kQ();null!=f&&(1==b.length&&b[0]instanceof Function&&(b=[b[0]()]),f[c]&&f[c].apply?f[c].apply(f,b):f[c]&&(f[c]=Function.prototype.bind.call(f[c],f),d.D.fo(a,c,b)))}};d.D.kQ=function(){var a=null;d.D.option("writer")?
a=d.D.option("writer"):void 0!==window&&void 0!==window.console&&(a=window.console);return a};d.D.HY=function(a){return void 0!==d.D.MB[a]};d.b=function(){this.Init()};o_("Object",d.b,d);d.b.t=null;d.b.cx="oj.Object";d.b.HK=/function\s+([\w\$][\w\$\d]*)\s*\(/;d.b.prototype={};d.b.prototype.constructor=d.b;d.b.g=function(a,c){var b=null,f=null,l;for(l in c)if(c.hasOwnProperty(l)){b=l;f=c[l];break}var m=a.split(".");l=d[m[0]];m=m[2];if(b!=m&&null!=b){var n=l.zw;n||(n={},l.zw=n);n[b]=m;l.prototype[m]=
f}};d.b.sa=function(a,c,b){d.i.xi(a);d.i.hH(c);d.i.jH(b);void 0===c&&(c=d.b);d.i.assert(a!==c,"Class can't extend itself");var f=d.b.BU;f.prototype=c.prototype;a.prototype=new f;a.prototype.constructor=a;a.t=a.superclass=c.prototype;b&&(a.cx=b)};o_("Object.createSubclass",d.b.sa,d);d.b.DV=function(a,c){var b;d.i.xi(a);d.i.assert(null!=c,"source object cannot be null");for(b in c)c.hasOwnProperty(b)&&(a.prototype[b]=c[b])};o_("Object.copyPropertiesForClass",d.b.DV,d);d.b.BU=function(){};d.b.prototype.PH=
function(a){if(void 0===a)a=this;else if(null===a)return null;return a.constructor};d.b.g("Object.prototype.getClass",{PH:d.b.prototype.PH});d.b.prototype.clone=function(){var a=new this.constructor;d.ec.Ne(a,this);return a};d.b.g("Object.prototype.clone",{clone:d.b.prototype.clone});d.b.prototype.toString=function(){return this.Ly()};d.b.g("Object.prototype.toString",{toString:d.b.prototype.toString});d.b.prototype.Ly=function(){return this.getTypeName()+" Object"};d.b.g("Object.prototype.toDebugString",
{Ly:d.b.prototype.Ly});d.b.getTypeName=function(a){d.i.xi(a);var c=a.cx;null==c&&(c=a.toString(),c=(c=d.b.HK.exec(c))?c[1]:"anonymous",a.cx=c);return c};o_("Object.getTypeName",d.b.getTypeName,d);d.b.prototype.getTypeName=function(){return d.b.getTypeName(this.constructor)};d.b.g("Object.prototype.getTypeName",{getTypeName:d.b.prototype.getTypeName});d.b.prototype.Init=function(){d.i.Gb&&d.i.assert(this.getTypeName,"Not an oj.Object");var a=this.constructor;a.uh||d.b.Rv(a)};d.b.g("Object.prototype.Init",
{Init:d.b.prototype.Init});d.b.VV=function(a){d.i.xi(a);a.uh||d.b.Rv(a)};o_("Object.ensureClassInitialization",d.b.VV,d);d.b.prototype.Ci=function(a){return this===a};d.b.g("Object.prototype.equals",{Ci:d.b.prototype.Ci});d.b.fs=function(a,c){d.i.xi(c);return c.bind(a)};o_("Object.createCallback",d.b.fs,d);d.b.RA=function(a,c){var b=d.i.Os,f=d.i.Qy,l,m;for(l in a)a.hasOwnProperty(l)&&(m=a[l],"function"!==typeof m||m.hasOwnProperty(b)||(m[b]=l,m[f]=c))};d.b.Rv=function(a){d.i.Gb&&(d.i.xi(a),d.i.assert(!a.uh));
a.uh=!0;var c=a.t,b;c&&((c=c.constructor)&&!c.uh&&d.b.Rv(c),d.b.QM(a));c=d.b.getTypeName(a);try{(b=a.InitClass||null)||(b=a.InitClass),b&&b.call(a)}finally{d.i.Gb&&(d.b.RA(a.prototype,c),d.b.RA(a,"static "+c))}};d.b.xg=function(a,c){if(a===c)return!0;if(typeof a!==typeof c||null===a||null===c)return!1;if(a.constructor===c.constructor){if(Array.isArray(a))return d.b.EN(a,c);if(a.constructor===Object)return d.b.ej(a,c);if(a.valueOf&&"function"===typeof a.valueOf)return a.valueOf()===c.valueOf()}return!1};
o_("Object.compareValues",d.b.xg,d);d.b.EN=function(a,c){if(a.length!==c.length)return!1;for(var b=0,f=a.length;b<f;b++)if(!d.b.xg(a[b],c[b]))return!1;return!0};d.b.ej=function(a,c){var b,f=!1;if(a===c)return!0;if(!(a instanceof Object&&c instanceof Object)||a.constructor!==c.constructor)return!1;for(b in a)if(f||(f=!0),a.hasOwnProperty(b)&&(!c.hasOwnProperty(b)||a[b]!==c[b]&&("object"!==typeof a[b]||!d.b.ej(a[b],c[b]))))return!1;for(b in c)if(f||(f=!0),c.hasOwnProperty(b)&&!a.hasOwnProperty(b))return!1;
return f?!0:JSON.stringify(a)===JSON.stringify(c)};d.b.isEmpty=function(a){var c;if(void 0===a||null===a)return!0;for(c in a)if(a.hasOwnProperty(c))return!1;return!0};d.b.QM=function(a){d.b.zw&&d.b.SA(a,a.t)};d.b.SA=function(a,c){if(c){var b=c.constructor;d.b.SA(a,b.t);var b=b.zw,f;if(b)for(f in b)if(b.hasOwnProperty(f)){var l=b[f];if(f!=l){var m=a.prototype;!m.hasOwnProperty(f)&&m.hasOwnProperty(l)?m[f]=m[l]:!m.hasOwnProperty(l)&&m.hasOwnProperty(f)&&(m[l]=m[f])}}}};d.b.ha=function(a){Promise.prototype.done||
(Promise.prototype.done=Promise.prototype.then);return new Promise(a)};d.Cm=function(){return"function"===typeof define&&define.amd};d.i={};o_("Assert",d.i,d);d.i.ZV=function(){d.i.Gb=d.i.DEBUG=!0};o_("Assert.forceDebug",d.i.ZV,d);d.i.Os="_funcName";d.i.Qy="_className";d.i.hL=20;d.i.assert=function(a,c){if(d.i.Gb&&!a){var b=c||"",f;if(2<arguments.length){b+="(";for(f=2;f<arguments.length;f+=1)b+=arguments[f];b+=")"}d.i.Ac(b,1)}};o_("Assert.assert",d.i.assert,d);d.i.fa=function(){d.i.Gb&&d.i.Ac("Abstract function called",
1)};o_("Assert.failedInAbstractFunction",d.i.fa,d);d.i.mb=function(a,c,b){var f;d.i.Gb&&(null!==a?(d.i.Le(c,"function",null,1,!1),f=c.prototype,f.isPrototypeOf(a)||d.i.Ac("object '"+a+"' doesn't match prototype "+f,1,b)):d.i.Ac("null object doesn't match prototype "+f,1,b))};o_("Assert.assertPrototype",d.i.mb,d);d.i.sV=function(a,c,b){var f;d.i.Gb&&null!==a&&(null!==a?(d.i.Le(c,"function",null,1,!1),f=c.prototype,f.isPrototypeOf(a)||d.i.Ac("object '"+a+"' doesn't match prototype "+f,1,b)):d.i.Ac("null object doesn't match prototype "+
f,1,b))};o_("Assert.assertPrototypeOrNull",d.i.sV,d);d.i.tV=function(a,c,b,f){d.i.Gb&&(c=c.prototype,b=b.prototype,c.isPrototypeOf(a)||b.isPrototypeOf(a)||d.i.Ac("object '"+a+"' doesn't match prototype "+c+" or "+b,1,f))};o_("Assert.assertPrototypes",d.i.tV,d);d.i.mV=function(a,c){d.i.Gb&&a&&void 0===a.nodeType&&d.i.Ac(a+" is not a DOM Node",c+1)};o_("Assert.assertDomNodeOrNull",d.i.mV,d);d.i.rx=function(a,c){d.i.Gb&&(a&&void 0!==a.nodeType||d.i.Ac(a+" is not a DOM Node",c+1))};o_("Assert.assertDomNode",
d.i.rx,d);d.i.kf=function(a,c){d.i.Gb&&(d.i.rx(a,1),1!==a.nodeType?d.i.Ac(a+" is not a DOM Element",1):c&&a.nodeName!==c&&d.i.Ac(a+" is not a "+c+" Element",1))};o_("Assert.assertDomElement",d.i.kf,d);d.i.lV=function(a,c){d.i.Gb&&null!==a&&(d.i.rx(a,1),1!==a.nodeType?d.i.Ac(a+" is not a DOM Element",1):c&&a.nodeName!==c&&d.i.Ac(a+" is not a "+c+" Element",1))};o_("Assert.assertDomElementOrNull",d.i.lV,d);d.i.Le=function(a,c,b,f,l){!d.i.Gb||null===a&&l||typeof a===c||(a=a+" is not of type "+c,b&&(a=
b+a),f||(f=0),d.i.Ac(a,f+1))};o_("Assert.assertType",d.i.Le,d);d.i.oe=function(a,c){d.i.Gb&&d.i.Le(a,"object",c,1,!1)};o_("Assert.assertObject",d.i.oe,d);d.i.rV=function(a,c){d.i.Gb&&d.i.Le(a,"object",c,1,!0)};o_("Assert.assertObjectOrNull",d.i.rV,d);d.i.iH=function(a,c){d.i.Gb&&(d.i.Le(a,"string",c,1,!1),d.i.assert(0<a.length,"empty string"))};o_("Assert.assertNonEmptyString",d.i.iH,d);d.i.Zr=function(a,c){d.i.Gb&&d.i.Le(a,"string",c,1,!1)};o_("Assert.assertString",d.i.Zr,d);d.i.jH=function(a,c){d.i.Gb&&
d.i.Le(a,"string",c,1,!0)};o_("Assert.assertStringOrNull",d.i.jH,d);d.i.xi=function(a,c){d.i.Gb&&d.i.Le(a,"function",c,1,!1)};o_("Assert.assertFunction",d.i.xi,d);d.i.hH=function(a,c){d.i.Gb&&d.i.Le(a,"function",c,1,!0)};o_("Assert.assertFunctionOrNull",d.i.hH,d);d.i.gH=function(a,c){d.i.Gb&&d.i.Le(a,"boolean",c,1,!1)};o_("Assert.assertBoolean",d.i.gH,d);d.i.fc=function(a,c){d.i.Gb&&d.i.Le(a,"number",c,1,!1)};o_("Assert.assertNumber",d.i.fc,d);d.i.pV=function(a,c){d.i.Gb&&d.i.Le(a,"number",c,1,!0)};
o_("Assert.assertNumberOrNull",d.i.pV,d);d.i.Yr=function(a,c){d.i.Gb&&!Array.isArray(a)&&(void 0===c&&(c=a+" is not an array"),d.i.Ac(c,1))};o_("Assert.assertArray",d.i.Yr,d);d.i.io=function(a,c){d.i.Gb&&null!==a&&!Array.isArray(a)&&(void 0===c&&(c=a+" is not an array"),d.i.Ac(c,1))};o_("Assert.assertArrayOrNull",d.i.io,d);d.i.oV=function(a,c){d.i.Gb&&!isNaN(a)&&(void 0===c&&(c=a+" is convertible to a number"),d.i.Ac(c,1))};o_("Assert.assertNonNumeric",d.i.oV,d);d.i.qV=function(a,c){d.i.Gb&&isNaN(a)&&
(void 0===c&&(c=a+" is not convertible to a number"),d.i.Ac(c,1))};o_("Assert.assertNumeric",d.i.qV,d);d.i.nV=function(a,c,b){var f;if(null===a||void 0===c[a.toString()]){if(void 0===b){b=" is not in set: {";for(f in c)c.hasOwnProperty(f)&&(b+=f,b+=",");b=a+(b+"}")}d.i.Ac(b,1)}};o_("Assert.assertInSet",d.i.nV,d);d.i.Ac=function(a,c,b){c||(c=0);var f="Assertion";b&&(f+=" ("+b+")");f+=" failed: ";void 0!==a&&(f+=a);a=d.i.zv(c+1);a=d.i.bD(a);f+="\nStackTrace:\n"+a;a=Error(f);window.alert(f);throw a;
};o_("Assert.assertionFailed",d.i.Ac,d);d.i.getFunctionName=function(a){var c=a[d.i.Os],b,f;void 0===c&&(c=a.toString(),b=c.indexOf("("),f=c.lastIndexOf(" ",b),c=c.substring(f+1,b),c.length||(c=null),a[d.i.Os]=c);return c};o_("Assert.getFunctionName",d.i.getFunctionName,d);d.i.pW=function(){return d.i.bD(d.i.zv(1))};o_("Assert.getStackString",d.i.pW,d);d.i.zv=function(a){void 0===a&&(a=0);d.i.assert(0<=a);var c=[],b;try{for(b=d.i.zv.caller;b&&c.length<d.i.hL;)a?a-=1:c.push(b),b=b.caller}catch(f){}return c};
d.i.HC=function(a){var c=a[d.i.oA],b,f;void 0===c&&(c=a.toString(),b=c.indexOf("("),f=c.indexOf(")",b+1),c=c.substring(b,f+1),c=c.replace(/\s+/g,""),c.length||(c=null),a[d.i.oA]=c);return c};d.i.bD=function(a){if(!a)return"";var c=a.length,b=[],f,l,m,n,q,r,t,p,u;for(f=0;f<c;f+=1){l=a[f];(m=d.i.getFunctionName(l))||(m="anonymous");(n=l[d.i.Qy])&&(m=n+"."+m);n=d.i.HC(l);q=l.arguments;r=q.length;l=null;if(r)for(l=[],t=0;t<r;t+=1)p=q[t],"function"===typeof p&&((u=d.i.getFunctionName(p))||(u="anonymous"),
p=d.i.HC(p),p="function "+u+p),l[t]=p;q=[];q[0]=m;q[1]=n;l&&(q[2]="\n",q[3]="[",q[4]=d.i.MT(l),q[5]="]");b[f]=q.join("")}return b.join("\n")};d.i.MT=function(a){var c=a.length,b="",d,l;for(d=0;d<c;d+=1)l=(l=a[d])?l.toString?l.toString():"Unknown":"(empty)",b+=l,d<c-1&&(b+=",");return b};d.i.oA="_funcParams";d.ia={};o_("Config",d.ia,d);d.ia.qe=function(){var a;if(d.Cm())return d.i.assert(void 0!==f,"ojtranslations module must be defined"),a=f._ojLocale_,"root"==a?"en":a;a=d.ia.Zk;null==a&&((a=document.documentElement.lang)||
(a=void 0===navigator?"en":(navigator.language||navigator.userLanguage||"en").toLowerCase()),d.ia.Zk=a=a.toLowerCase());return a};o_("Config.getLocale",d.ia.qe,d);d.ia.mX=function(c,b){if(d.Cm()){var h=["ojL10n!ojtranslations/nls/"+c+"/ojtranslations"];d.Ga&&h.push("ojL10n!ojtranslations/nls/"+c+"/localeElements");a(h,function(a,c){f=a;c&&d.Ga.sM(c);b&&b()})}else d.ia.Zk=c,b&&b()};o_("Config.setLocale",d.ia.mX,d);d.ia.jb=function(c){var b=/^\/|:/;return null==c||b.test(c)?c:(b=d.ia.GT)?b+("/"==b.charAt(b.length-
1)?"":"/")+c:d.Cm()?(b=a.toUrl("ojs/_foo_"),b.replace(/[^\/]*$/,"../"+c)):c};o_("Config.getResourceUrl",d.ia.jb,d);d.ia.nX=function(a){d.ia.GT=a};o_("Config.setResourceBaseUrl",d.ia.nX,d);d.ia.lX=function(a){d.ia.UM=a};o_("Config.setAutomationMode",d.ia.lX,d);d.ia.NH=function(){return d.ia.UM};o_("Config.getAutomationMode",d.ia.NH,d);d.fb={};o_("StringUtils",d.fb,d);d.fb.rM=/^\s*|\s*$/g;d.fb.isEmpty=function(a){return null===a?!0:0===d.fb.trim(a).length};o_("StringUtils.isEmpty",d.fb.isEmpty,d);d.fb.yI=
function(a){return void 0===a||d.fb.isEmpty(a)?!0:!1};o_("StringUtils.isEmptyOrUndefined",d.fb.yI,d);d.fb.pd=function(a){return null!==a&&("string"===typeof a||a instanceof String)};o_("StringUtils.isString",d.fb.pd,d);d.fb.trim=function(a){return d.fb.pd(a)?a.replace(d.fb.rM,""):a};o_("StringUtils.trim",d.fb.trim,d);d.ec={};o_("CollectionUtils",d.ec,d);d.ec.Ne=function(a,c,b,f,l){return d.ec.yB(a,c,b,f,l,0)};o_("CollectionUtils.copyInto",d.ec.Ne,d);d.ec.isPlainObject=function(a){if("object"===typeof a)try{if(a.constructor&&
a.constructor.prototype.hasOwnProperty("isPrototypeOf"))return!0}catch(c){}return!1};o_("CollectionUtils.isPlainObject",d.ec.isPlainObject,d);d.ec.yB=function(a,c,b,f,l,m){var n,q,r;if(a&&c&&a!==c){r=Object.keys(c);for(var t=0;t<r.length;t++){n=r[t];q=b?b(n):n;n=c[n];var p=!1;if(f&&m<l){var u=a[q];d.ec.isPlainObject(u)&&d.ec.isPlainObject(n)&&(p=!0,d.ec.yB(u,n,b,!0,l,m+1))}p||(a[q]=n)}}return a};d.ea={};o_("Translations",d.ea,d);d.ea.By=function(a){d.ea.Ot=a};o_("Translations.setBundle",d.ea.By,d);
d.ea.Gc=function(a){return d.ea.YC(a)};o_("Translations.getResource",d.ea.Gc,d);d.ea.ub=function(a,c){return null==a?null:d.ea.eP(a,c)};o_("Translations.applyParameters",d.ea.ub,d);d.ea.O=function(a,c){var b=d.ea.YC(a);if(null==b)return a;var f={};2<arguments.length?f=Array.prototype.slice.call(arguments,1):2==arguments.length&&(f=arguments[1],"object"===typeof f||f instanceof Array||(f=[f]));return d.ea.ub(b,f)};o_("Translations.getTranslatedString",d.ea.O,d);d.ea.ms=function(a){a=d.ea.uC()[a];var c,
b;if(null==a)return{};c={};for(b in a)a.hasOwnProperty(b)&&(c[b]=a[b]);return c};o_("Translations.getComponentTranslations",d.ea.ms,d);d.ea.YC=function(a){a=a?a.split("."):[];var c=d.ea.uC(),b=a.length,f=0,l=a[f];for(d.i.oe(c);0<--b&&c;)c=c[l],f++,l=a[f];return c?c[l]||null:null};d.ea.eP=function(a,c){var b=a.length,d=[],l=null,f=!1,n=!1,q=!1,r=!1,t,p;for(p=0;p<b;p++){var u=a.charAt(p),s=!1;if(f)s=!0,f=!1;else switch(u){case "$":f=!0;break;case "{":r||(n||(t=!1,l=[]),n=!0);break;case "}":n&&0<l.length&&
(n=c[l.join("")],d.push(void 0===n?"null":n));n=!1;break;case "[":n||(q?r=!0:q=!0);break;case "]":r?r=!1:q=!1;break;default:s=!0}s&&(n?","==u||" "==u?t=!0:t||l.push(u):r||d.push(u))}return d.join("")};d.ea.uC=function(){var a=d.ea.Ot;return a?a:d.Cm()?(d.i.assert(void 0!==f,"ojtranslations module must be defined"),f):{}};return d});
//# sourceMappingURL=oj-modular.map