"use strict";
/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(a,f){(function(){var c=0;a.Oa("oj.ojCollapsible",f.oj.baseComponent,{widgetEventPrefix:"oj",options:{expanded:!1,expandOn:"click",expandArea:"disclosureIcon",beforeExpand:null,expand:null,beforeCollapse:null,collapse:null,optionChange:null},_ComponentCreate:function(){this._super();this.element.addClass("oj-collapsible oj-component");this.SE();this.Wb()},_init:function(){this.Yq=!0;this.$F(this.options.expanded);this.Yq=void 0},_OpenContextMenu:function(a,
c){a.open(c,{launcher:this.element.find(".oj-collapsible-header-icon").first(),initialFocus:"menu"})},PN:function(){var a=this.options.expanded?"oj-collapsible-open-icon":"oj-collapsible-close-icon";f("\x3ca href\x3d'#'\x3e").addClass("oj-component-icon oj-clickable-icon oj-collapsible-header-icon "+a).attr("aria-labelledby",this.header.attr("id")).prependTo(this.header)},SB:function(){this.header.children(".oj-collapsible-header-icon").remove()},_destroy:function(){this.pB();this.element.removeClass("oj-collapsible oj-component oj-expanded oj-collapsed oj-disabled");
this.header.removeClass("oj-collapsible-header").each(function(){/^oj-collapsible/.test(this.id)&&this.removeAttribute("id")});this.Xm().removeAttr("role").removeAttr("aria-controls").removeAttr("aria-expanded").removeAttr("aria-disabled");this.SB();this.Ku(this.content).removeAttr("tabIndex");this.content.css("display","").removeAttr("aria-hidden").removeAttr("tabIndex").removeClass("oj-component-content oj-collapsible-content").each(function(){/^oj-collapsible/.test(this.id)&&this.removeAttribute("id")})},
pB:function(){this.ol();this.content&&(this.content.unwrap(),this.Pg=null)},wY:function(){return!1},EC:function(){return"header"==this.options.expandArea?"\x3e .oj-collapsible-header":"\x3e .oj-collapsible-header \x3e .oj-collapsible-header-icon"},_setOption:function(a,c,e){"expanded"===a?c!==this.options.expanded&&this.$F(c):"expandOn"===a||"expandArea"===a?(this.ol(),this._super(a,c,e),this.Nj()):this._super(a,c,e)},Fj:function(a){if(!a.altKey&&!a.ctrlKey){var c=f.ui.keyCode;switch(a.keyCode){case c.SPACE:case c.ENTER:this.IG(a)}}},
refresh:function(){this._super();this.pB();this.SE();this.SB();this.Wb()},SE:function(){this.header=this.element.children(":first-child").addClass("oj-collapsible-header");this.content=this.header.next().addClass("oj-collapsible-content oj-component-content");this.content.wrap("\x3cdiv\x3e\x3c/div\x3e");this.Pg=this.content.parent().addClass("oj-collapsible-wrapper")},Wb:function(){var a=this.header,d=this.content,e=this.options,f="oj-collapsible-"+(this.element.attr("id")||++c),h=a.attr("id"),k=
d.attr("id");h||a.attr("id",f+"-header");k||(k=f+"-content",d.attr("id",k));this.PN();this.Xm().attr("role","button").attr("aria-controls",k).attr("aria-expanded",e.expanded);this.XF(e.expanded?"0":"-1");e.expanded?d.attr("aria-hidden","false"):(this.Pg.css({"max-height":0,"overflow-y":"hidden",display:"none"}),this.Pg.css("max-height",0),d.attr("aria-hidden","true"));this.Nj()},$F:function(a){a?this.expand(!0):this.collapse(!0)},Nj:function(){var a={keydown:this.Fj},c=this.options.expandOn;if(c){var e=
this;f.each(c.split(" "),function(c,d){/^[a-zA-Z]+$/.test(d)&&(a[d]=e.IG)})}c=this.element.find(this.EC());this._on(c,a);this._on(this.Pg,{transitionend:this.Qr,webkitTransitionEnd:this.Qr,otransitionend:this.Qr,oTransitionEnd:this.Qr});this._on(this.element,{ojexpand:this.Iu,ojcollapse:this.Iu,ojfocus:this.qC,ojfocusout:this.qC});this._hoverable(c);this._focusable(c);this.Lp(c)},ol:function(){this._off(this.element.find(this.EC()));this.Pg&&this._off(this.Pg);this._off(this.element.add(this.content))},
IG:function(a){this.options.expanded?this.collapse(!0,a):this.expand(!0,a);a.preventDefault();a.stopPropagation();this.header.find(".oj-collapsible-header-icon").focus()},Iu:function(a){if(a.target===this.element[0]&&(this.Yq||!a.isDefaultPrevented())){var c=this.element,e=this.options,f=this.content,h=this.Pg,k="ojcollapse"===a.type;a.preventDefault();e.expanded=!k;this.Yq?k?(c.removeClass("oj-expanded"),c.addClass("oj-collapsed"),h.css("max-height",0),h.hide()):(c.removeClass("oj-collapsed"),c.addClass("oj-expanded")):
(h.es=h.outerHeight(),k?(h.removeClass("oj-collapsible-transition"),h.css({"max-height":h.es,"overflow-y":"hidden"}),setTimeout(function(){h.addClass("oj-collapsible-transition").css({"max-height":0});c.removeClass("oj-expanded");c.addClass("oj-collapsed")},10)):(h.show(),setTimeout(function(){h.es+=f.outerHeight();h.addClass("oj-collapsible-transition").css({"max-height":h.es});c.removeClass("oj-collapsed");c.addClass("oj-expanded")},1)));this.header.find(".oj-collapsible-header-icon").toggleClass("oj-collapsible-open-icon",
!k).toggleClass("oj-collapsible-close-icon",k||!1).end();this.content.attr("aria-hidden",k);this.Xm().attr("aria-expanded",!k);this.XF(k?"-1":"0")}},qC:function(a){"ojfocusout"==a.type?(this.Xm().attr("tabIndex",-1),a.preventDefault(),a.stopPropagation()):"ojfocus"==a.type&&(this.Xm().attr("tabIndex",0).focus(),a.preventDefault(),a.stopPropagation())},Xm:function(){return this.Ku(this.header).first()},XF:function(a){return this.Ku(this.content).attr("tabIndex",a)},Ku:function(a){return a.find("a,:input")},
expand:function(a,c){var e={header:this.header,content:this.content};a&&!1===this._trigger("beforeExpand",c,e)||(this._trigger("expand",c,e),this.Oc("expanded",!1,!0,c?!0:!1))},collapse:function(a,c){if(this.Yq){var e=this.element[0];this.Iu({type:"ojcollapse",target:e,currentTarget:e,preventDefault:f.noop})}else e={header:this.header,content:this.content},a&&!1===this._trigger("beforeCollapse",c,e)||(this._trigger("collapse",c,e),this.Oc("expanded",!0,!1,c?!0:!1))},Qr:function(a){"max-height"==(a.originalEvent?
a.originalEvent.propertyName:null)&&(a.preventDefault(),a.stopPropagation());this.options.expanded?this.Pg.css({"max-height":9999,"overflow-y":""}):this.Pg.hide();this.Pg.removeClass("oj-collapsible-transition")},Oc:function(a,c,e,f){this._trigger("optionChange",f,{option:a,previousValue:c,value:e,optionMetadata:{writeback:f?"shouldWrite":"shouldNotWrite"}})},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;a=a.subId;switch(a){case "oj-collapsible-content":return this.content;
case "oj-collapsible-header":return this.header;case "oj-collapsible-header-icon":return this.header.find("."+a)[0]}return null}})})()});
//# sourceMappingURL=oj-modular.map