/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojdatacollection-common","ojs/ojmodel"],function(a){a.wc=function(f,c,b,d,e){a.i.fc(f,null);a.i.fc(c,null);a.i.fc(b,null);a.i.fc(d,null);a.i.io(e);this.uf=f;this.Zj=c;this.Gg=b;this.Yj=d;this.Ic=e};o_("CollectionCellSet",a.wc,a);a.wc.prototype.fJ=function(f){a.i.Yr(f);null!=f&&f.length===this.Z("row")&&(this.ak=f)};a.wc.prototype.getData=function(a){var c;c=this.Vb(a);return null==c?null:c.get(this.Ic[a.column])};a.b.g("CollectionCellSet.prototype.getData",{getData:a.wc.prototype.getData});
a.wc.prototype.getMetadata=function(f){var c;c=this.Vb(f);return null==c?null:{keys:{row:a.Ph.uj(c),column:this.Ic[f.column]}}};a.b.g("CollectionCellSet.prototype.getMetadata",{getMetadata:a.wc.prototype.getMetadata});a.wc.prototype.Vb=function(f){var c;if(null==this.ak)return null;a.i.oe(f);c=f.row;f=f.column;a.i.assert(c>=this.uf&&c<=this.Zj&&f>=this.Gg&&f<=this.Yj);return this.ak[c-this.uf]};a.wc.prototype.Z=function(a){return"row"===a?Math.max(0,this.Zj-this.uf):"column"===a?Math.max(0,this.Yj-
this.Gg):0};a.b.g("CollectionCellSet.prototype.getCount",{Z:a.wc.prototype.Z});a.wc.prototype.getStartRow=function(){return this.uf};a.b.g("CollectionCellSet.prototype.getStartRow",{getStartRow:a.wc.prototype.getStartRow});a.wc.prototype.UH=function(){return this.Zj};a.b.g("CollectionCellSet.prototype.getEndRow",{UH:a.wc.prototype.UH});a.wc.prototype.getStartColumn=function(){return this.Gg};a.b.g("CollectionCellSet.prototype.getStartColumn",{getStartColumn:a.wc.prototype.getStartColumn});a.wc.prototype.TH=
function(){return this.Yj};a.b.g("CollectionCellSet.prototype.getEndColumn",{TH:a.wc.prototype.TH});a.wc.prototype.Fi=function(){return this.Ic};a.b.g("CollectionCellSet.prototype.getColumns",{Fi:a.wc.prototype.Fi});a.Ph=function(){};a.Ph.uj=function(a){var c;c=a.ye();null==c&&(c=a.mk());return c};a.Kc=function(f,c,b,d){a.i.fc(f,null);a.i.fc(c,null);a.i.io(b);this.vc=f;this.Qf=c;this.ys=b;this.tf=d};o_("CollectionHeaderSet",a.Kc,a);a.Kc.prototype.fJ=function(f){a.i.Yr(f);null!=f&&f.length===this.Z()&&
(this.ak=f)};a.Kc.prototype.getData=function(f){a.i.assert(f<=this.Qf&&f>=this.vc);if(null!=this.tf){if(null==this.ak)return null;f=this.ak[f-this.vc];return f.get(this.tf)}return this.ys[f]};a.b.g("CollectionHeaderSet.prototype.getData",{getData:a.Kc.prototype.getData});a.Kc.prototype.getMetadata=function(f){if(null!=this.tf){if(null==this.ak)return null;f=this.ak[f-this.vc];return{key:a.Ph.uj(f)}}return{key:this.getData(f)}};a.b.g("CollectionHeaderSet.prototype.getMetadata",{getMetadata:a.Kc.prototype.getMetadata});
a.Kc.prototype.Z=function(){return Math.max(0,this.Qf-this.vc)};a.b.g("CollectionHeaderSet.prototype.getCount",{Z:a.Kc.prototype.Z});a.Kc.prototype.Ka=function(){return this.vc};a.b.g("CollectionHeaderSet.prototype.getStart",{Ka:a.Kc.prototype.Ka});a.Kc.prototype.SH=function(){return this.Qf};a.b.g("CollectionHeaderSet.prototype.getEnd",{SH:a.Kc.prototype.SH});a.Kc.prototype.ZH=function(){return this.ys};a.b.g("CollectionHeaderSet.prototype.getHeaders",{ZH:a.Kc.prototype.ZH});a.Kc.prototype.to=function(){return this.tf};
a.b.g("CollectionHeaderSet.prototype.getRowHeader",{to:a.Kc.prototype.to});a.ja=function(f,c){this.pa=f;null!=c&&(this.Ui=c.rowHeader,this.columns=c.columns);this.C=0;this.na=-1;a.ja.t.constructor.call(this)};o_("CollectionDataGridDataSource",a.ja,a);a.b.sa(a.ja,a.Eb,"oj.CollectionDataGridDataSource");a.ja.prototype.Init=function(){a.ja.t.Init.call(this);this.Ql={};this.Yv()||(null==this.columns&&0<this.pa.length?(this.columns=this.pa.first().keys(),-1!=this.columns.indexOf(this.Ui)&&this.columns.splice(this.columns.indexOf(this.Ui),
1)):this.columns=[]);this.hT()};a.b.g("CollectionDataGridDataSource.prototype.Init",{Init:a.ja.prototype.Init});a.ja.prototype.hT=function(){this.pa.on("add",this.KQ.bind(this));this.pa.on("remove",this.pD.bind(this));this.pa.on("change",this.LQ.bind(this));this.pa.on("refresh",this.oQ.bind(this))};a.ja.prototype.Yv=function(){return null!=this.pa.url||null!=this.pa.customURL};a.ja.prototype.zR=function(){return this.Yv()?null!=this.data:!0};a.ja.prototype.OD=function(a){if(this.Yv()){if("column"===
a)return null!=this.columns;if("row"===a&&null!=this.Ui)return null!=this.data}return!0};a.ja.prototype.Z=function(a){if(!this.OD(a))return this.precision="estimate",-1;this.precision="exact";return"row"==a?this.size():"column"==a?this.columns.length:0};a.b.g("CollectionDataGridDataSource.prototype.getCount",{Z:a.ja.prototype.Z});a.ja.prototype.pf=function(a){null==this.precision&&this.Z(a);return this.precision};a.b.g("CollectionDataGridDataSource.prototype.getCountPrecision",{pf:a.ja.prototype.pf});
a.ja.prototype.Xd=function(a,c,b){var d,e;d=a.axis;this.OD(d)?this.oD(a,c,b):null!=c&&(e={},e.uW=a,e.callbacks=c,e.tx=b,this.Ql[d]=e)};a.b.g("CollectionDataGridDataSource.prototype.fetchHeaders",{Xd:a.ja.prototype.Xd});a.ja.prototype.oD=function(f,c,b,d){var e,g,h,k;e=f.axis;g=f.start;h=f.count;a.i.assert("row"===e||"column"===e);a.i.assert(0<h);if("column"===e)null!=this.columns?(d=Math.min(this.columns.length,g+h),k=new a.Kc(g,d,this.columns)):k=new a.de(g,g,e,null);else if("row"===e){if(null!=
this.Ui){null!=d&&(h=d.count);d=Math.min(this.size(),g+h);0<this.na&&(d=Math.min(d,this.totalSize()-this.C));k=new a.Kc(g,d,this.columns,this.Ui);this.HF(g,d,k,f,c,b);return}k=new a.de(g,g,e,null)}null!=c&&c.success&&c.success.call(b.success,k,f)};a.ja.prototype.UC=function(f){var c,b,d,e,g,h;for(c=0;c<f.length;c+=1)b=f[c],a.i.assert("row"===b.axis||"column"===b.axis),a.i.assert(0<b.count),"row"===b.axis?(d=b.start,e=b.count):"column"===b.axis&&(g=b.start,h=b.count);return{rowStart:d,rowCount:e,colStart:g,
colCount:h}};a.ja.prototype.mD=function(f,c,b,d){var e,g,h;e=this.UC(f);g=e.rowStart;d=null!=d?Math.min(this.size(),g+d.count):Math.min(this.size(),g+e.rowCount);h=e.colStart;e=Math.min(this.columns.length,h+e.colCount);0<this.na&&(d=Math.min(d,this.totalSize()-this.C));e=new a.wc(g,d,h,e,this.columns);this.HF(g,d,e,f,c,b)};a.ja.prototype.HF=function(a,c,b,d,e,g){var h;for(h=[];a<c;a++)h.push(this.pa.at(a+this.C,{deferred:!0}));Promise.all(h).then(function(a){b.fJ(a);e.success.call(g.success,b,d)})};
a.ja.prototype.Vd=function(a,c,b){this.zR()?this.mD(a,c,b):(null!=c&&(this.Lg={},this.Lg.wV=a,this.Lg.callbacks=c,this.Lg.tx=b),this.TO(a))};a.b.g("CollectionDataGridDataSource.prototype.fetchCells",{Vd:a.ja.prototype.Vd});a.ja.prototype.TE=function(a){var c,b,d,e,g;c=this.Ql[a];null!=c&&(b=c.uW,d=c.callbacks,e=c.tx,"row"===a&&(g=c.qx),this.oD(b,d,e,g),this.Ql[a]=null)};a.ja.prototype.PS=function(){this.mD(this.Lg.wV,this.Lg.callbacks,this.Lg.tx,this.Lg.qx)};a.ja.prototype.TO=function(a){var c;a=
this.UC(a);c=a.rowStart;0<this.na&&(c+=this.C);this.pa.Js(c,a.rowCount).then(function(a){var d=this.pa.at(c,{deferred:!0});this.UT(a.start,a.count);null!=d&&void 0===this.columns?d.then(function(a){this.Pw(a);this.iC()}.bind(this)):this.iC()}.bind(this))};a.ja.prototype.iC=function(){null!=this.Ql&&(this.TE("column"),this.TE("row"));null!=this.Lg&&this.PS();0<this.na&&a.Eb.t.handleEvent.call(this,"sync",!0)};a.ja.prototype.UT=function(a,c){var b={start:a,count:c};null!=this.Ql.row&&(this.Ql.row.qx=
b);null!=this.Lg&&(this.Lg.qx=b)};a.ja.prototype.Pw=function(a){this.columns=a.keys();-1!=this.columns.indexOf(this.Ui)&&this.columns.splice(this.columns.indexOf(this.Ui),1)};a.ja.prototype.keys=function(f){var c,b,d,e,g,h;c=f.row+this.C;b=f.column;h=this;return a.b.ha(function(f){g=h.pa.at(c,{deferred:!0});null!=g?g.then(function(c){d=a.Ph.uj(c);null==h.columns&&h.Pw(c);e=h.columns[b];f({row:null==d?null:d,column:null==e?null:e})}.bind(h)):f({row:null,column:null})})};a.b.g("CollectionDataGridDataSource.prototype.keys",
{keys:a.ja.prototype.keys});a.ja.prototype.$d=function(f){var c,b,d,e;c=f.row;b=f.column;e=this;return a.b.ha(function(a){e.pa.indexOf(c,{deferred:!0}).then(function(c){-1!=c&&(c-=this.C);null==e.columns?e.pa.first(1,{deferred:!0}).then(function(f){e.Pw(f);d=e.columns.indexOf(b);a({row:c,column:d})}.bind(e)):(d=e.columns.indexOf(b),a({row:c,column:d}))}.bind(e))})};a.b.g("CollectionDataGridDataSource.prototype.indexes",{$d:a.ja.prototype.$d});a.ja.prototype.getCapability=function(a){return"sort"===
a?"column":"move"===a?"row":null};a.b.g("CollectionDataGridDataSource.prototype.getCapability",{getCapability:a.ja.prototype.getCapability});a.ja.prototype.sort=function(a,c,b){var d,e=a.direction,g=a.key;a=a.axis;null==b&&(b={});"column"===a?(-1<this.pa.Gx&&this.pa.hasMore?(this.pa.comparator=g,this.pa.sortDirection="ascending"===e?1:-1):("ascending"===e&&(d=function(a,b){var c,d;a=a.get(g);b=b.get(g);c=isNaN(a);d=isNaN(b);a instanceof Date&&(a=a.toISOString(),c=!0);b instanceof Date&&(b=b.toISOString(),
d=!0);return c&&d?a<b?-1:a===b?0:1:c?1:d?-1:a-b}),"descending"===e&&(d=function(a,b){var c,d;a=a.get(g);b=b.get(g);c=isNaN(a);d=isNaN(b);a instanceof Date&&(a=a.toISOString());b instanceof Date&&(b=b.toISOString());return c&&d?a>b?-1:a===b?0:1:c?-1:d?1:b-a}),this.pa.comparator=d),this.pa.sort(),null!=c&&null!=c.success&&c.success.call(b.success)):null!=c&&null!=c.error&&c.error.call(b.error,"Axis value not supported")};a.b.g("CollectionDataGridDataSource.prototype.sort",{sort:a.ja.prototype.sort});
a.ja.prototype.move=function(a,c){var b;this.pa.get(a,{deferred:!0}).then(function(d){null==c?(this.pa.remove(d),this.pa.add(d)):(a===c?(b=this.pa.indexOf(c,{deferred:!0}),this.pa.remove(d)):(this.pa.remove(d),b=this.pa.indexOf(c,{deferred:!0})),b.then(function(a){this.pa.add(d,{at:a,PY:!0})}.bind(this)))}.bind(this))};a.b.g("CollectionDataGridDataSource.prototype.move",{move:a.ja.prototype.move});a.ja.prototype.gf=function(a,c,b,d,e){var g={source:this};g.operation=a;g.keys={row:c,column:b};g.indexes=
{row:d,column:e};return g};a.ja.prototype.KQ=function(f){var c,b;this.pa.indexOf(f,{deferred:!0}).then(function(d){b=a.Ph.uj(f);c=this.gf("insert",b,null,0<d-this.C?d-this.C:0,-1);this.handleEvent("change",c);d<this.na+this.C&&(d=this.pa.at(this.C+this.na,{deferred:!0}),null!=d&&d.then(function(a){null!=f&&this.pD(a,0,{index:this.C+this.na-1})}.bind(this)))}.bind(this))};a.ja.prototype.pD=function(f,c,b){var d,e,g;g=b.index;0<this.na&&g<this.C?(g<this.C&&(g=0),f=this.pa.at(this.C-1,{deferred:!0}),
null!=f&&f.then(function(b){null!=b&&(e=a.Ph.uj(b),d=this.gf("delete",e,null,g,-1),this.handleEvent("change",d))}.bind(this))):(0<this.na&&(g-=this.C),e=a.Ph.uj(f),d=this.gf("delete",e,null,g,-1),this.handleEvent("change",d))};a.ja.prototype.LQ=function(f){var c,b;this.pa.indexOf(f,{deferred:!0}).then(function(d){b=a.Ph.uj(f);d=0<d-this.C?d-this.C:-1;c=this.gf("update",b,null,d,-1);this.handleEvent("change",c)}.bind(this))};a.ja.prototype.oQ=function(){this.handleEvent("change",this.gf("refresh",
null,null))};a.ja.prototype.setPageSize=function(a){this.na=a};a.b.g("CollectionDataGridDataSource.prototype.setPageSize",{setPageSize:a.ja.prototype.setPageSize});a.ja.prototype.size=function(){return null!=this.na&&0<this.na&&this.pa.size()>this.na?this.na:this.pa.size()};a.b.g("CollectionDataGridDataSource.prototype.size",{size:a.ja.prototype.size});a.ja.prototype.totalSize=function(){return null!=this.pa?this.pa.totalResults:-1};a.b.g("CollectionDataGridDataSource.prototype.totalSize",{totalSize:a.ja.prototype.totalSize});
a.ja.prototype.hasMore=function(){return null!=this.pa?this.pa.hasMore:!1};a.b.g("CollectionDataGridDataSource.prototype.hasMore",{hasMore:a.ja.prototype.hasMore});a.ja.prototype.fetch=function(a){this.C=null!=a?null!=a.startIndex?a.startIndex:0:0;this.handleEvent("change",{operation:"sync",pageSize:this.na})};a.ja.prototype.getCollection=function(){return this.pa};a.b.g("CollectionDataGridDataSource.prototype.getCollection",{getCollection:a.ja.prototype.getCollection});a.ja.prototype.Fi=function(){return this.columns};
a.b.g("CollectionDataGridDataSource.prototype.getColumns",{Fi:a.ja.prototype.Fi});a.ja.prototype.to=function(){return this.Ui};a.b.g("CollectionDataGridDataSource.prototype.getRowHeader",{to:a.ja.prototype.to});a.ja.prototype.dI=function(){return this.C};a.b.g("CollectionDataGridDataSource.prototype.getStartIndex",{dI:a.ja.prototype.dI});a.ja.prototype.$H=function(){return this.na};a.b.g("CollectionDataGridDataSource.prototype.getPageSize",{$H:a.ja.prototype.$H});a.ja.prototype.getData=function(){return this.data};
a.b.g("CollectionDataGridDataSource.prototype.getData",{getData:a.ja.prototype.getData})});
//# sourceMappingURL=oj-modular.map