/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define("ojs/ojcore jquery ojs/ojeditablevalue ojs/ojinputtext ojs/ojvalidation ojs/ojpopup ojs/ojbutton".split(" "),function(a,f){function c(a,b){var c=a.filter("span");b?c.addClass("oj-disabled").removeClass("oj-enabled oj-default"):c.removeClass("oj-disabled").addClass("oj-enabled oj-default")}function b(a,b){b.setHours(a.getHours());b.setMinutes(a.getMinutes());b.setSeconds(a.getSeconds());b.setMilliseconds(a.getMilliseconds());return b}function d(a){return a.delegate(".oj-datepicker-prev-icon, .oj-datepicker-prev-icon .oj-clickable-icon.oj-component-icon, .oj-datepicker-next-icon, .oj-datepicker-next-icon .oj-clickable-icon.oj-component-icon, .oj-datepicker-calendar td a",
"mouseout",function(){f(this).removeClass("oj-hover")}).delegate(".oj-datepicker-prev-icon, .oj-datepicker-prev-icon .oj-clickable-icon.oj-component-icon, .oj-datepicker-next-icon, .oj-datepicker-next-icon .oj-clickable-icon.oj-component-icon, .oj-datepicker-calendar td a","mouseover",function(){f(this).addClass("oj-hover")}).delegate(".oj-datepicker-prev-icon, .oj-datepicker-prev-icon .oj-clickable-icon.oj-component-icon, .oj-datepicker-next-icon, .oj-datepicker-next-icon .oj-clickable-icon.oj-component-icon, .oj-datepicker-calendar td a",
"focus",function(){f(this).addClass("oj-focus")}).delegate(".oj-datepicker-prev-icon, .oj-datepicker-prev-icon .oj-clickable-icon.oj-component-icon, .oj-datepicker-next-icon, .oj-datepicker-next-icon .oj-clickable-icon.oj-component-icon, .oj-datepicker-calendar td a","blur",function(){f(this).removeClass("oj-focus")})}var e=a.ca.yi(a.Zf.CONVERTER_TYPE_DATETIME).createConverter({year:"numeric"});a.Oa("oj.ojInputDate",f.oj.inputBase,{version:"1.0.0",widgetEventPrefix:"oj",_CLASS_NAMES:"oj-inputdatetime-input",
_WIDGET_CLASS_NAMES:"oj-inputdatetime-date-only oj-component oj-inputdatetime",_INPUT_HELPER_KEY:"inputHelp",_ATTR_CHECK:[{attr:"type",setMandatory:"text"}],yt:"oj-inputdatetime-input-trigger",pM:"oj-inputdatetime-calendar-icon",Dz:"oj-datepicker-current-day",Gz:"oj-datepicker-days-cell-over",BA:"oj-datepicker-unselectable",Fz:"oj-datepicker-desc",$s:"oj-datepicker-calendar",gL:"oj-datepicker-div",NK:"oj-datepicker-inline",PK:" oj-inputdatetime-input-container",options:{datePicker:{footerLayout:"",
changeMonth:"select",changeYear:"select",currentMonthPos:0,daysOutsideMonth:"hidden",numberOfMonths:1,showOn:"image",stepMonths:"numberOfMonths",stepBigMonths:12,weekDisplay:"none",yearRange:"c-10:c+10"},converter:a.ca.yi(a.Zf.CONVERTER_TYPE_DATETIME).createConverter({day:"2-digit",month:"2-digit",year:"2-digit"}),max:void 0,min:void 0,dayFormatter:null},_InitOptions:function(b,c){this._super(b,c);a.td.Ki([{attribute:"disabled",defaultOptionValue:!1,validateOption:!0},{attribute:"title",defaultOptionValue:""},
{attribute:"placeholder",defaultOptionValue:""},{attribute:"value",defaultOptionValue:null},{attribute:"required",defaultOptionValue:!1,coerceDomValue:!0,validateOption:!0},{attribute:"min",defaultOptionValue:null},{attribute:"max",defaultOptionValue:null}],c,this)},sp:function(){this.Gd=null;this.Pv=!1;this.Cn=4;this.Zh=this.lg=this.kh=this.Hf=this.kg=0;this.Vm={};var a=this.element[0].nodeName.toLowerCase();this.Sd="div"===a||"span"===a;this.yc=d(f("\x3cdiv id\x3d'"+this.Sh(this.gL)+"' role\x3d'region' aria-describedby\x3d'"+
this.Sh(this.Fz)+"' class\x3d'oj-datepicker-content'\x3e\x3c/div\x3e"));f("body").append(this.yc);if(this.Sd)this._CLASS_NAMES="";else{this._WIDGET_CLASS_NAMES+=this.PK;var b=this;this.rr=this.yc.ojPopup({initialFocus:"none",rootAttributes:{"class":"datetimepicker-dropdown"},open:function(){b.yc.find(".oj-datepicker-calendar").focus()}})}},_ComponentCreate:function(){this.sp();var a=this._super();this.Br(this.bn());this.Sd?(this.element.append(this.yc),this.element.addClass(this.NK),this.yc.css("display",
"block")):this.Ht();return a},Rh:function(){var a=this._superApply(arguments);this.XB(this.options.disabled);return a},_setOption:function(b,c,d){var e=null,f={},f={};if("value"===b)return c||(c=null),e=this._super(b,c,d),this.Br(c),this.ih()&&this.ti(),e;e=this._super(b,c,d);"disabled"===b?this.XB(c):"max"===b||"min"===b?(f={min:this.options.min,max:this.options.max,converter:this.nc()},this.Vm[a.Tb.VALIDATOR_TYPE_DATETIMERANGE]=a.ca.Xf(a.Tb.VALIDATOR_TYPE_DATETIMERANGE).createValidator(f),this.pk()):
"readOnly"===b&&c?this.hide():"dayFormatter"===b&&(f={dayFormatter:this.options.dayFormatter,converter:this.nc()},this.Vm[a.Tb.VALIDATOR_TYPE_DATERESTRICTION]=a.ca.Xf(a.Tb.VALIDATOR_TYPE_DATERESTRICTION).createValidator(f),this.pk());"datePicker"===b&&"currentMonthPos"===d.subkey&&this.Br(this.options.value);c={max:!0,min:!0,dayFormatter:!0,datePicker:!0,translations:!0,dayMetaData:!0};this.ih()&&b in c&&this.ti();return e},Xs:function(){return this.Gd},_destroy:function(){var a=this._super();this.element.off("focus");
this.Gd&&this.Gd.remove();this.Sd&&(this.element.removeProp("disabled"),this.element.removeProp("readonly"));this.yc.remove();return a},ih:function(){return this.Sd||this.rr.ojPopup("isOpen")},Ht:function(){var a=this.options.datePicker.showOn,b=f("\x3cspan\x3e").addClass(this.yt);if("focus"===a)this.element.on("focus",f.proxy(this.show,this));a=f("\x3cspan/\x3e").addClass(this.pM+" oj-clickable-icon oj-component-icon");b.append(a);var c=this;a.on("click",function(){c.ih()?c.hide():c.show();return!1}).on("mouseenter",
function(){f(this).addClass("oj-hover")}).on("mousedown",function(){f(this).addClass("oj-active")}).on("mouseleave",function(){f(this).removeClass("oj-hover oj-active")});this.Gd=b;this.element.after(b)},DO:function(a){var b;b=!1;var c=f.ui.keyCode,d=this.tp();if(this.ih())switch(a.keyCode){case 84:a.altKey&&a.ctrlKey&&(this.yc.find(".oj-datepicker-current").focus(),b=!0);break;case c.TAB:this.hide();break;case c.ENTER:return b=f("td."+this.Gz+":not(."+this.Dz+")",this.yc),b[0]&&this.QF(this.Hf,this.lg,
b[0],a),a.preventDefault(),a.stopPropagation(),!1;case c.ESCAPE:this.hide();this.element.focus();b=!0;break;case c.PAGE_UP:a.ctrlKey&&a.altKey?this.zd(-this.options.datePicker.stepBigMonths,"M",!0):a.altKey?this.zd(-1,"Y",!0):this.zd(-this.mn(),"M",!0);b=!0;break;case c.PAGE_DOWN:a.ctrlKey&&a.altKey?this.zd(+this.options.datePicker.stepBigMonths,"M",!0):a.altKey?this.zd(1,"Y",!0):this.zd(+this.mn(),"M",!0);b=!0;break;case c.END:this.kg=this.Eq(this.lg,this.Hf);this.ti(!0);b=!0;break;case c.HOME:this.kg=
1;this.ti(!0);b=!0;break;case c.LEFT:this.zd(d?1:-1,"D",!0);a.originalEvent.altKey&&this.zd(a.ctrlKey?-this.options.datePicker.stepBigMonths:-this.mn(),"M",!0);b=!0;break;case c.UP:this.zd(-7,"D",!0);b=!0;break;case c.RIGHT:this.zd(d?-1:1,"D",!0);a.originalEvent.altKey&&this.zd(a.ctrlKey?+this.options.datePicker.stepBigMonths:+this.mn(),"M",!0);b=!0;break;case c.DOWN:this.zd(7,"D",!0),b=!0}else a.keyCode===c.HOME&&a.ctrlKey&&(this.show(),b=!0);b&&(a.preventDefault(),a.stopPropagation())},ti:function(a){this.Cn=
4;var b=this.gP();this.yc.empty().append(b.html);var c=f("button",this.yc);0<c.length&&(1===c.length&&f(c[0]).addClass("oj-datepicker-single-button"),f.each(c,function(a,b){f(b).ojButton()}));this.SM();b.AH&&this.yc.find(".oj-datepicker-calendar").attr("aria-activedescendant",b.AH);b=this.lv();c=b[1];this.yc.removeClass("oj-datepicker-multi-2 oj-datepicker-multi-3 oj-datepicker-multi-4").width("");1<c&&this.yc.addClass("oj-datepicker-multi-"+c).css("width",17*c+"em");this.yc[(1!==b[0]||1!==b[1]?"add":
"remove")+"Class"]("oj-datepicker-multi");this.ih()&&this.element.is(":visible")&&!this.element.is(":disabled")&&(a||this.Sd?(a=this.yc.find(".oj-datepicker-calendar"),a[0]!==document.activeElement&&a.focus()):this.element[0]!==document.activeElement&&this.element.focus())},zd:function(a,b,c){this.options.disabled||(this.MA(a+("M"===b?this.options.datePicker.currentMonthPos:0),b),this.ti(c))},lQ:function(){var a=new Date;this.kg=a.getDate();this.kh=this.Hf=a.getMonth();this.Zh=this.lg=a.getFullYear();
this.zd()},RF:function(a,b){var c=parseInt(a.options[a.selectedIndex].value,10);"M"===b?this.Hf=this.kh=c:this.lg=this.Zh=c;f("#"+this.Sh(this.$s)).html(this.options.monthWide[this.kh]+" "+e.format((new Date(this.Zh,this.kh,1)).toISOString()));this.zd()},QF:function(c,d,e,l){f(e).hasClass(this.BA)||this.options.disabled||(this.kg=f("a",e).html(),this.Hf=c,this.lg=d,(c=this.options.value?a.IntlConverterUtils.isoToLocalDate(this.options.value):null)?(d=new Date(this.lg,this.Hf,this.kg),b(c,d),c=d):
c=new Date(this.lg,this.Hf,this.kg),c=c.toISOString(),d=this.nc().format(c),this.ig(d),this.ie(c,l),this.hide())},zu:function(b,c){return b?"string"===typeof b?a.IntlConverterUtils.isoToLocalDate(b):new Date(b.getTime()):c},Br:function(a){a=this.zu(a,this.iD());this.kg=a.getDate();this.kh=this.Hf=a.getMonth();this.Zh=this.lg=a.getFullYear();this.MA()},mn:function(){var a=this.options.datePicker.stepMonths;return f.isNumeric(a)?a:this.options.datePicker.numberOfMonths},SM:function(){var a=this.mn(),
b=this;this.yc.find("[data-handler]").map(function(){f(this).bind(this.getAttribute("data-event"),{prev:function(c){b.zd(-a,"M",!0);c.preventDefault()},next:function(c){b.zd(+a,"M",!0);c.preventDefault()},today:function(a){if("keyup"===a.type&&13===a.keyCode||"click"===a.type)b.lQ(),a.preventDefault(),a.stopPropagation()},selectDay:function(a){b.QF(+this.getAttribute("data-month"),+this.getAttribute("data-year"),this,a);return!1},selectMonth:function(){b.RF(this,"M");return!1},selectYear:function(){b.RF(this,
"Y");return!1},calendarKey:function(a){b.DO(a)}}[this.getAttribute("data-handler")])})},gP:function(){var a,b,c,d,e,f,q=this.options.dayWide,r=this.options.dayNarrow,t=this.options.monthWide,p=this.options.monthAbbreviated,u=this.options.firstDayOfWeek,s,v,z,w,y,H,x,O="",B,A,D,C,I,P,F,G,N=new Date,N=new Date(N.getFullYear(),N.getMonth(),N.getDate()),J=this.tp();f=this.options.datePicker.footerLayout;var K=this.lv(),E=this.options.datePicker.currentMonthPos,S=this.options.dayFormatter;G=null;var Y=
1!==K[0]||1!==K[1],W=this.Iq("min"),T=this.Iq("max"),E=this.kh-E,Q=this.Zh,da=new Date(this.lg,this.Hf,this.kg),R=new Date(this.bn()),L=R.getDate(),aa=R.getMonth(),ea=R.getFullYear(),U=this.options.disabled,ba=this.O("weekText");R.setHours(0);R.setMinutes(0);R.setSeconds(0);R.setMilliseconds(0);0>E&&(E+=12,Q--);if(T)for(a=new Date(T.getFullYear(),T.getMonth()-K[0]*K[1]+1,T.getDate()),a=W&&a<W?W:a;new Date(Q,E,1)>a;)E--,0>E&&(E=11,Q--);this.kh=E;this.Zh=Q;a=this.O("prevText");a=this.kB(-1,Q,E)&&!U?
"\x3ca href\x3d'#' class\x3d'oj-datepicker-prev-icon oj-enabled oj-default oj-component-icon oj-clickable-icon' data-handler\x3d'prev' data-event\x3d'click' title\x3d'"+a+"'\x3e\x3c/a\x3e":"\x3ca class\x3d'oj-datepicker-prev-icon oj-disabled oj-component-icon oj-clickable-icon' title\x3d'"+a+"'\x3e\x3c/a\x3e";b=this.O("nextText");b=this.kB(1,Q,E)&&!U?"\x3ca href\x3d'#' class\x3d'oj-datepicker-next-icon oj-enabled oj-default oj-component-icon oj-clickable-icon' data-handler\x3d'next' data-event\x3d'click' title\x3d'"+
b+"'\x3e\x3c/a\x3e":"\x3ca class\x3d'oj-datepicker-next-icon oj-disabled oj-component-icon oj-clickable-icon' title\x3d'"+b+"'\x3e\x3c/a\x3e";c=this.O("currentText");e="";d="\x3cbutton type\x3d'button' class\x3d'oj-datepicker-current oj-priority-secondary' data-handler\x3d'today' data-event\x3d'click keyup'\x3e"+c+"\x3c/button\x3e";if(1<f.length){c=0;f=[{index:f.indexOf("today"),content:this.QD(N)?d:""}];for(f.sort(function(a,b){return a.index-b.index});c<f.length&&0>f[c].index;)c++;for(;c<f.length;)e+=
f[c++].content;0<e.length&&(e="\x3cdiv class\x3d'oj-datepicker-buttonpane'\x3e"+e+"\x3c/div\x3e")}f=this.options.datePicker.weekDisplay;c=this.options.datePicker.daysOutsideMonth;d="";s="all";for(v=0;v<K[0];v++){z="";this.Cn=4;for(w=0;w<K[1];w++){s="all";B="";if(Y){B+="\x3cdiv class\x3d'oj-datepicker-group";if(1<K[1])switch(w){case 0:B+=" oj-datepicker-group-first";s=J?"right":"left";break;case K[1]-1:B+=" oj-datepicker-group-last";s=J?"left":"right";break;default:B+=" oj-datepicker-group-middle",
s=""}B+="'\x3e"}B+="\x3cdiv class\x3d'oj-datepicker-header"+(U?" oj-disabled ":" oj-enabled oj-default ")+"'\x3e"+(/all|left/.test(s)&&0===v?J?b:a:"")+(/all|right/.test(s)&&0===v?J?a:b:"")+this.hP(E,Q,W,T,0<v||0<w,t,p)+"\x3c/div\x3e\x3ctable class\x3d'oj-datepicker-calendar"+(U?" oj-disabled ":" oj-enabled oj-default ")+"' tabindex\x3d-1 data-handler\x3d'calendarKey' data-event\x3d'keydown' aria-readonly\x3d'true' role\x3d'grid' aria-labelledby\x3d'"+this.Sh(this.$s)+"'\x3e\x3cthead role\x3d'presentation'\x3e\x3ctr role\x3d'row'\x3e";
A="number"===f?"\x3cth class\x3d'oj-datepicker-week-col'\x3e"+this.O("weekHeader")+"\x3c/th\x3e":"";for(s=0;7>s;s++)D=(s+parseInt(u,10))%7,A+="\x3cth role\x3d'columnheader' aria-label\x3d'"+q[D]+"'"+(5<=(s+u+6)%7?" class\x3d'oj-datepicker-week-end'":"")+"\x3e\x3cspan title\x3d'"+q[D]+"'\x3e"+r[D]+"\x3c/span\x3e\x3c/th\x3e";B+=A+"\x3c/tr\x3e\x3c/thead\x3e\x3ctbody role\x3d'presentation'\x3e";A=this.Eq(Q,E);Q===ea&&E===aa&&(L=Math.min(L,A));s=(this.zP(Q,E)-u+7)%7;A=Math.ceil((s+A)/7);this.Cn=A=Y?this.Cn>
A?this.Cn:A:A;D=new Date(Q,E,1-s);for(C=0;C<A;C++){B+="\x3ctr role\x3d'row'\x3e";s=this.nc().jo(D.toISOString());I="none"===f?"":"\x3ctd class\x3d'oj-datepicker-week-col' role\x3d'rowheader' aria-label\x3d'"+ba+" "+s+"'\x3e"+s+"\x3c/td\x3e";for(s=0;7>s;s++){F=D.getMonth()!==E;y=D.getTime()===R.getTime();H="oj-dp-"+C+"-"+s;(x=D.getTime()===da.getTime()&&E===this.Hf)&&(O=H);P=[!0,""];G=D.getFullYear();var X=D.getMonth(),ca=D.getDate();S&&(G=S({fullYear:G,month:X+1,date:ca}))&&(P=[!G.disabled,G.className||
""],G.tooltip&&P.push(G.tooltip));X=D.getTime()===R.getTime();G=F&&"selectable"!==c||!P[0]||W&&D<W||T&&D>T;I+="\x3ctd role\x3d'gridcell' aria-disabled\x3d'"+!!G+"' aria-selected\x3d'"+y+"' id\x3d'"+H+"' class\x3d'"+(5<=(s+u+6)%7?" oj-datepicker-week-end":"")+(F?" oj-datepicker-other-month":"")+(x?" "+this.Gz:"")+(G||U?" "+this.BA+" oj-disabled":" oj-enabled ")+(F&&"hidden"===c?"":" "+P[1]+(y?" "+this.Dz:"")+(D.getTime()===N.getTime()?" oj-datepicker-today":""))+"'"+(F&&"hidden"===c||!P[2]?"":" title\x3d'"+
P[2].replace(/'/g,"\x26#39;")+"'")+(G?"":" data-handler\x3d'selectDay' data-event\x3d'click' data-month\x3d'"+D.getMonth()+"' data-year\x3d'"+D.getFullYear()+"'")+"\x3e"+(F&&"hidden"===c?"\x26#xa0;":G||U?"\x3cspan class\x3d'oj-disabled'\x3e"+D.getDate()+"\x3c/span\x3e":"\x3ca class\x3d'oj-enabled"+(X?" oj-selected":"")+(F?" oj-priority-secondary":"")+"' "+(X||x?"":"tabindex\x3d'-1' ")+" href\x3d'#'\x3e"+D.getDate()+"\x3c/a\x3e")+"\x3c/td\x3e";D.setDate(D.getDate()+1)}B+=I+"\x3c/tr\x3e"}E++;11<E&&
(E=0,Q++);B+="\x3c/tbody\x3e\x3c/table\x3e"+(Y?"\x3c/div\x3e"+(0<K[0]&&w===K[1]-1?"\x3cdiv class\x3d'oj-datepicker-row-break'\x3e\x3c/div\x3e":""):"");z+=B}d+=z}return{html:d+e,AH:O}},hP:function(b,c,d,f,m,n,q){var r,t,p,u,s=this.options.datePicker.changeMonth,v=this.options.datePicker.changeYear,z=a.Ga.BI()?"before":"after",w="\x3cdiv class\x3d'oj-datepicker-title' role\x3d'header'\x3e",y="",H=this.options.disabled;if(m||"none"===s)y+="\x3cspan class\x3d'oj-datepicker-month'\x3e"+n[b]+"\x3c/span\x3e";
else{r=d&&d.getFullYear()===c;t=f&&f.getFullYear()===c;y+="\x3cselect tabindex\x3d'-1' class\x3d'oj-datepicker-month "+(H?"oj-disabled' disabled":"oj-enabled'")+" data-handler\x3d'selectMonth' data-event\x3d'change' role\x3d'listbox'\x3e";for(p=0;12>p;p++)(!r||p>=d.getMonth())&&(!t||p<=f.getMonth())&&(y+="\x3coption role\x3d'option' value\x3d'"+p+"' aria-selected\x3d'"+(p===b?"true' selected\x3d'selected'":"false'")+"\x3e"+q[p]+"\x3c/option\x3e");y+="\x3c/select\x3e"}"before"===z&&(w+=y+(m||"select"!==
s||"select"!==v?"\x26#xa0;":""));if(!this.Nh)if(this.Nh="",m||"none"===v)w+="\x3cspan class\x3d'oj-datepicker-year'\x3e"+e.format((new Date(c,b,1)).toISOString())+"\x3c/span\x3e";else{r=this.options.datePicker.yearRange.split(":");u=(new Date).getFullYear();t=function(a){a=a.match(/c[+\-].*/)?c+parseInt(a.substring(1),10):a.match(/[+\-].*/)?u+parseInt(a,10):parseInt(a,10);return isNaN(a)?u:a};q=t(r[0]);r=Math.max(q,t(r[1]||""));q=d?Math.max(q,d.getFullYear()):q;r=f?Math.min(r,f.getFullYear()):r;for(this.Nh+=
"\x3cselect tabindex\x3d'-1' class\x3d'oj-datepicker-year "+(H?"oj-disabled' disabled":"oj-enabled'")+" data-handler\x3d'selectYear' data-event\x3d'change' role\x3d'listbox'\x3e";q<=r;q++)this.Nh+="\x3coption role\x3d'option' value\x3d'"+q+"' aria-selected\x3d'"+(q===c?"true' selected\x3d'selected'":"false'")+"\x3e"+e.format((new Date(q,b,1)).toISOString())+"\x3c/option\x3e";this.Nh+="\x3c/select\x3e";w+=this.Nh;this.Nh=null}"after"===z&&(w+=(m||"select"!==s||"select"!==v?"\x26#xa0;":"")+y);w+="\x3cspan class\x3d'oj-helper-hidden-accessible' id\x3d'"+
this.Sh(this.$s)+"'\x3e"+n[b]+" "+e.format((new Date(c,b,1)).toISOString())+"\x3c/span\x3e";w+="\x3cspan class\x3d'oj-helper-hidden-accessible' id\x3d'"+this.Sh(this.Fz)+"'\x3e"+this.O("datePicker")+"\x3c/span\x3e";return w+"\x3c/div\x3e"},MA:function(a,b){var c=this.Zh+("Y"===b?a:0),d=this.kh+("M"===b?a:0),e=Math.min(this.kg,this.Eq(c,d))+("D"===b?a:0),c=new Date(c,d,e);this.kg=c.getDate();this.kh=this.Hf=c.getMonth();this.Zh=this.lg=c.getFullYear()},lv:function(){var a=this.options.datePicker.numberOfMonths,
a="string"===typeof a?parseInt(a,10):a;return null==a?[1,1]:"number"===typeof a?[1,a]:a},Iq:function(a){return this.zu(this.options[a],null)},Eq:function(a,b){return 32-(new Date(a,b,32)).getDate()},zP:function(a,b){return(new Date(a,b,1)).getDay()},kB:function(a,b,c){var d=this.lv();b=new Date(b,c+(0>a?a:d[0]*d[1]),1);0>a&&b.setDate(this.Eq(b.getFullYear(),b.getMonth()));return this.QD(b)},QD:function(a){var b,c,d=this.Iq("min"),e=this.Iq("max"),f=null,q=null;if(b=this.options.datePicker.yearRange)b=
b.split(":"),c=(new Date).getFullYear(),f=parseInt(b[0],10),q=parseInt(b[1],10),b[0].match(/[+\-].*/)&&(f+=c),b[1].match(/[+\-].*/)&&(q+=c);return(!d||a.getTime()>=d.getTime())&&(!e||a.getTime()<=e.getTime())&&(!f||a.getFullYear()>=f)&&(!q||a.getFullYear()<=q)},XB:function(a){this.Gd&&c(this.Gd.children(),a);a&&this.hide();this.Sd&&this.ti()},Ws:function(){this.Sd||this._superApply(arguments)},pw:function(a){this.Sd||this._superApply(arguments)},or:function(a){if(!this.Sd){this._superApply(arguments);
var b=f.ui.keyCode,c=!1;if(this.ih())switch(a.keyCode){case b.TAB:this.hide();break;case b.ESCAPE:this.hide();c=!0;break;case b.UP:case b.DOWN:this.yc.find(".oj-datepicker-calendar").focus(),c=!0}else switch(a.keyCode){case b.UP:case b.DOWN:this.show(),c=!0}if(c)return a.preventDefault(),a.stopPropagation(),!1}},ig:function(a){this.Sd||this._superApply(arguments);this.Br(this.bn());this.ih()&&this.ti()},nc:function(){return this.options.converter?this._superApply(arguments):f.oj.ojInputDate.prototype.options.converter},
sk:function(){return this.options.value||""},_GetDefaultStyleClass:function(){return"oj-inputdate"},vm:function(){var b=this._superApply(arguments),c=this.options.max,d={},d={};if(null!=this.options.min||null!=c)d={min:this.options.min,max:this.options.max,converter:this.nc()},this.Vm[a.Tb.VALIDATOR_TYPE_DATETIMERANGE]=a.ca.Xf(a.Tb.VALIDATOR_TYPE_DATETIMERANGE).createValidator(d);null!=this.options.dayFormatter&&(d={dayFormatter:this.options.dayFormatter,converter:this.nc()},this.Vm[a.Tb.VALIDATOR_TYPE_DATERESTRICTION]=
a.ca.Xf(a.Tb.VALIDATOR_TYPE_DATERESTRICTION).createValidator(d));return f.extend(this.Vm,b)},iD:function(){var a=new Date;a.setHours(0);a.setMinutes(0);a.setSeconds(0);a.setMilliseconds(0);return a},bn:function(){return this.zu(this.options.value,this.iD())},getNodeBySubId:function(a){var b=null,c=a&&a.subId,d=this.yc;if(c)switch(c){case "oj-datepicker-content":b=d[0];break;case "oj-inputdatetime-calendar-icon":b=f(".oj-inputdatetime-calendar-icon",this.Gd)[0];break;case "oj-datepicker-prev-icon":b=
f(".oj-datepicker-prev-icon",d)[0];break;case "oj-datepicker-next-icon":b=f(".oj-datepicker-next-icon",d)[0];break;case "oj-datepicker-month":b=f(".oj-datepicker-month",d)[0];break;case "oj-datepicker-year":b=f(".oj-datepicker-year",d)[0];break;case "oj-datepicker-current":b=f(".oj-datepicker-current",d)[0];break;default:b=null}return b||this._superApply(arguments)},getSubIdByNode:function(a){var b=this.yc,c=null,d=[{selector:".oj-inputdatetime-calendar-icon",ele:this.Gd},{selector:".oj-datepicker-prev-icon",
ele:b},{selector:".oj-datepicker-next-icon",ele:b},{selector:".oj-datepicker-month",ele:b},{selector:".oj-datepicker-year",ele:b},{selector:".oj-datepicker-current",ele:b}];if(a===b[0])return"oj-datepicker-content";for(var b=0,e=d.length;b<e;b++){var n=d[b],q=f(n.selector,n.ele);if(1===q.length&&q[0]===a){c=n.selector.substr(1);break}}return c||this._superApply(arguments)},hide:function(){this.ih()&&!this.Sd&&(this.rr.ojPopup("close"),"focus"===this.options.datePicker.showOn&&(this.Pv=!0),this.element.focus());
return this},refresh:function(){return this._superApply(arguments)||this},show:function(){if(!(this.ih()||this.options.disabled||this.options.readOnly))if(this.Pv)this.Pv=!1;else{var b=this.tp();this.yc.empty();this.ti();var c=this.widget(),c=c.is("[id]")?c.attr("id"):c.uniqueId().attr("id");this.rr.ojPopup("widget").attr(a.ba.dg,c);this.rr.ojPopup("open",this.element,{my:b?"right top":"left top",at:b?"right bottom":"left bottom",collision:"fit"});return this}}});a.Components.Cy({ojInputDate:{firstDayOfWeek:a.Components.Uj(function(){return a.Ga.WH()}),
dayWide:a.Components.Uj(function(){return a.Ga.Kx("wide")}),dayNarrow:a.Components.Uj(function(){return a.Ga.Kx("narrow")}),monthWide:a.Components.Uj(function(){return a.Ga.os("wide")}),monthAbbreviated:a.Components.Uj(function(){return a.Ga.os("abbreviated")})}});a.Oa("oj.ojInputTime",f.oj.inputBase,{version:"1.0.0",widgetEventPrefix:"oj",_CLASS_NAMES:"oj-inputdatetime-input",_WIDGET_CLASS_NAMES:"oj-inputdatetime-time-only oj-component oj-inputdatetime oj-inputdatetime-input-container",_INPUT_HELPER_KEY:"inputHelp",
_ATTR_CHECK:[{attr:"type",setMandatory:"text"}],eM:"ojInputTime",yt:"oj-inputdatetime-input-trigger",qM:"oj-inputdatetime-time-icon",options:{converter:a.ca.yi(a.Zf.CONVERTER_TYPE_DATETIME).createConverter({hour:"2-digit",hour12:!0,minute:"2-digit"}),max:void 0,min:void 0,datePickerComp:null,timePicker:{timeIncrement:"00:30:00:00"}},_InitOptions:function(b,c){this._super(b,c);a.td.Ki([{attribute:"disabled",defaultOptionValue:!1,validateOption:!0},{attribute:"title",defaultOptionValue:""},{attribute:"placeholder",
defaultOptionValue:""},{attribute:"value",defaultOptionValue:null},{attribute:"required",defaultOptionValue:!1,coerceDomValue:!0,validateOption:!0},{attribute:"min",defaultOptionValue:null},{attribute:"max",defaultOptionValue:null}],c,this)},sp:function(){this.Zw={};this.Um=this.options.datePickerComp;this.Fd=f("\x3cdiv id\x3d'"+this.Sh(this.eM)+"' class\x3d'oj-listbox-drop' style\x3d'display:none'\x3e\x3c/div\x3e");f("body").append(this.Fd);var a=this;this.sr=this.Fd.ojPopup({initialFocus:"none",
rootAttributes:{"class":"datetimepicker-dropdown"},open:function(){var b=f("[aria-selected]",a.Fd);1===b.length&&f(b);f("ul",a.Fd).focus()}})},ao:function(){return this.sr.ojPopup("isOpen")},_ComponentCreate:function(){this.sp();var a=this._superApply(arguments);this.$q()&&!this.LD()&&(this._CLASS_NAMES="");this.Ht();return a},Rh:function(){var a=this._superApply(arguments);c(this.Gd.children(),this.options.disabled);return a},_setOption:function(b,d,e){var f=null,m={};if("value"===b)return d||(d=
null),f=this._super(b,d,e),this.yq(),f;f=this._superApply(arguments);"disabled"===b?(d&&this.hide(),c(this.Gd.children(),d)):"max"!==b&&"min"!==b||!this.vh()?"readOnly"===b&&d&&this.hide():(m={min:this.options.min,max:this.options.max,converter:this.nc()},this.Zw[a.Tb.VALIDATOR_TYPE_DATETIMERANGE]=a.ca.Xf(a.Tb.VALIDATOR_TYPE_DATETIMERANGE).createValidator(m),this.pk());b in{max:!0,min:!0,converter:!0,timePicker:!0}&&this.yq();return f},_destroy:function(){var a=this._super();this.Gd&&this.Gd.remove();
this.Fd.remove();return a},Ws:function(){this.vh()&&this._superApply(arguments)},Xs:function(){return this.Gd},or:function(a){if(this.vh()){this._superApply(arguments);var b=f.ui.keyCode,c=!1;if(this.ao())switch(a.keyCode){case b.TAB:this.hide();break;case b.ESCAPE:this.hide();c=!0;break;case b.UP:case b.DOWN:f("ul",this.Fd).focus(),c=!0}else switch(a.keyCode){case b.UP:case b.DOWN:this.show(),c=!0}if(c||a.keyCode===b.ENTER)return a.preventDefault(),a.stopPropagation(),!1}},Ht:function(){var a=this.vh(),
b=a?f(f("\x3cspan\x3e").addClass(this.yt)):f("+ span",this.element),c=f("\x3cspan/\x3e").addClass(this.qM+" oj-clickable-icon oj-component-icon");b.append(c);var d=this;c.on("click",function(){d.ao()?d.hide():d.show()}).on("mouseenter",function(){f(this).addClass("oj-hover")}).on("mousedown",function(){f(this).addClass("oj-active")}).on("mouseleave",function(){f(this).removeClass("oj-hover oj-active")});this.Gd=b;a&&this.element.after(b)},dR:function(b){var c=this.options.min?a.IntlConverterUtils.isoToLocalDate(this.options.min):
null,d=this.options.max?a.IntlConverterUtils.isoToLocalDate(this.options.max):null;return null!==c&&b<c||null!==d&&b>d},yq:function(){var b=this.options.value?a.IntlConverterUtils.isoToLocalDate(this.options.value):new Date,c=f("\x3cul class\x3d'oj-listbox-results' tabindex\x3d'-1' role\x3d'listbox'\x3e\x3c/ul\x3e"),d=this.AP(),e=[],m;b.setHours(0);b.setMinutes(0);b.setSeconds(0);b.setMilliseconds(0);e=this.hQ(b);d=d||e[0].value;this.Fd.empty();b=0;for(m=e.length;b<m;b++){var n=e[b].value,q=e[b].minMaxRange,
r=f("\x3cli class\x3d'oj-listbox-result "+(q?"oj-disabled":"")+"' role\x3d'presentation'\x3e"),t=this.uuid+"_sel"+b,q=f("\x3cdiv class\x3d'oj-listbox-result-label' "+(q?"aria-disabled ":"")+"data-value\x3d'"+n+"' role\x3d'option' id\x3d'"+t+"'\x3e"+e[b].label+"\x3c/li\x3e");d===n&&(q.attr("aria-selected","true"),r.addClass("oj-hover"),c.attr("aria-activedescendant",t));r.append(q);c.append(r)}this.Fd.append(c);f(".oj-listbox-result",c).on("mousemove",function(){var a=f(this);a.hasClass("oj-disabled")||
(f(".oj-hover",c).removeClass("oj-hover"),a.addClass("oj-hover"),c.attr("aria-activedescendant",a.children()[0].id))});var p=this;c.on("click",function(a){var b=f(a.target);b.hasClass("oj-disabled")||void 0!==b.attr("aria-disabled")||(p.hide(),p.VE(a))}).on("keydown",function(a){p.DU(a)})},hQ:function(a){var b=[],c=this.nc();if(a){var d=this.options.timePicker.timeIncrement.split(":");if(4===d.length){var e=parseInt(d[0].substring(0),10),f=parseInt(d[1],10),q=parseInt(d[2],10),d=parseInt(d[3],10),
r=new Date(a),t="";do t=c.format(r.toISOString()),b.push({label:t,value:t,minMaxRange:this.dR(r)}),r.setHours(r.getHours()+e),r.setMinutes(r.getMinutes()+f),r.setSeconds(r.getSeconds()+q),r.setMilliseconds(r.getMilliseconds()+d);while(r.getDate()===a.getDate())}else throw Error("timeIncrement value should be in the format of hh:mm:ss:SS");}return b},DU:function(a){if(this.ao()){var b=f.ui.keyCode,c=!1;switch(a.keyCode){case b.TAB:this.hide();break;case b.ESCAPE:this.hide();this.element.focus();c=
!0;break;case b.UP:this.RE(a,"prev");c=!0;break;case b.DOWN:this.RE(a,"next");c=!0;break;case b.ENTER:this.VE(a),c=!0}if(c)return a.preventDefault(),a.stopPropagation(),!1}},RE:function(a,b){var c=f(".oj-hover",this.Fd),d=f("ul",this.Fd);if(1===c.length){var e=c[b]();1===e.length&&(c.removeClass("oj-hover"),e.addClass("oj-hover"),d.attr("aria-activedescendant",e.children()[0].id))}},VE:function(a){var b=this.Fd,c=f("[aria-selected]",b),d=f("ul",b),b=f(".oj-hover div",b);1===b.length&&(1===c.length&&
(c.removeAttr("aria-selected"),c.parent().removeClass("oj-hover")),b.attr("aria-selected","true"),b.parent().addClass("oj-hover"),this.ig(b.attr("data-value")),this.ie(b.attr("data-value"),a),d.attr("aria-activedescendant",b[0].id),this.hide(),this.element.focus(),this.$q()&&this.Um.widget.hide())},pw:function(a){this.vh()&&this._superApply(arguments)},show:function(){if(!this.options.disabled&&!this.options.readOnly){this.$q()&&this.Um.widget.hide();0===this.Fd.children().length&&this.yq();this.Fd.width(this.element.parent().width());
this.Fd.css({position:"relative"});var b=this.tp(),c=this.widget(),c=c.is("[id]")?c.attr("id"):c.uniqueId().attr("id");this.sr.ojPopup("widget").attr(a.ba.dg,c);this.sr.ojPopup("open",this.element,{my:b?"right top":"left top",at:b?"right bottom":"left bottom",collision:"fit"})}},hide:function(){this.ao()&&(this.sr.ojPopup("close"),this.element.focus())},refresh:function(){return this._superApply(arguments)||this},ig:function(a){this.vh()&&this._superApply(arguments);this.ao()&&this.yq()},um:function(){return this.vh()},
vh:function(){return!this.$q()||this.LD()},_GetDefaultStyleClass:function(){return"oj-inputtime"},sk:function(){return this.options.value||""},vm:function(){var b=this._superApply(arguments),c=this.options.min,d=this.options.max,e={};null==c&&null==d||!this.vh()||(e={min:c,max:d,converter:this.nc()},this.Zw[a.Tb.VALIDATOR_TYPE_DATETIMERANGE]=a.ca.Xf(a.Tb.VALIDATOR_TYPE_DATETIMERANGE).createValidator(e));return f.extend(this.Zw,b)},nc:function(){return this.options.converter?this._superApply(arguments):
f.oj.ojInputTime.prototype.options.converter},XX:function(){},AP:function(){var a=this.nc(),b=this.options.value;return b?a.format(b):""},$q:function(){return null!==this.Um},LD:function(){return this.Um.inline},getNodeBySubId:function(a){var b=null,c=a&&a.subId;c&&("oj-listbox-drop"===c?b=this.Fd[0]:"oj-inputdatetime-time-icon"===c&&(b=f(".oj-inputdatetime-time-icon",this.Gd)[0]));return b||this._superApply(arguments)},getSubIdByNode:function(a){var b=f(".oj-inputdatetime-time-icon",this.Gd),c=null;
a===this.Fd[0]?c="oj-listbox-drop":a===b[0]&&(c="oj-inputdatetime-time-icon");return c||this._superApply(arguments)},widget:function(){return this.vh()?this._super():this.Um.widget.widget()}});a.Oa("oj.ojInputDateTime",f.oj.ojInputDate,{version:"1.0.0",widgetEventPrefix:"oj",_WIDGET_CLASS_NAMES:"oj-inputdatetime-date-time oj-component oj-inputdatetime",_INPUT_HELPER_KEY:"inputHelpBoth",options:{converter:a.ca.yi(a.Zf.CONVERTER_TYPE_DATETIME).createConverter({day:"2-digit",month:"2-digit",year:"2-digit",
hour:"2-digit",hour12:!0,minute:"2-digit"}),timePicker:{timeIncrement:"00:30:00:00"}},sp:function(){this._super();this.Or=this.element;this.Nr=this.Td=null},_ComponentCreate:function(){var a=this._super(),b=this.hD(this.nc());if(null===b)throw Error("Plase use ojInputDate if you do not have time portion");if(this.Sd){var c=f("\x3cinput type\x3d'text'\x3e");c.insertAfter(this.element);this.Or=c}this.Td=this.Or.ojInputTime({converter:b,min:this.options.min,max:this.options.max,value:this.bn().toISOString(),
optionChange:f.proxy(this.EU,this),timePicker:this.options.timePicker,datePickerComp:{widget:this,inline:this.Sd}});this.Td.ojInputTime("option","disabled",this.options.disabled);return a},_setOption:function(a,b,c){var d=this._superApply(arguments);this.Td&&(a in{disabled:!0,min:!0,max:!0}?this.Td.ojInputTime("option",a,b):"timePicker"===a&&"timeIncrement"===c.subkey?this.Td.ojInputTime("option","timePicker.timeIncrement",b.timeIncrement):"converter"===a&&(this.Nr=null,this.Td.ojInputTime("option",
a,this.hD(this.nc()))));return d},_destroy:function(){var a=this._super();this.Td.ojInputTime("destroy");this.Sd&&this.Or.remove();return a},hD:function(b){if(null!==this.Nr)return this.Nr;b=b.resolvedOptions();var c={},d="hour hour12 minute second millisecond timeFormat".split(" "),e,m;e=0;for(m=d.length;e<m;e++)d[e]in b&&("timeFormat"===d[e]&&(c.formatType="time"),c[d[e]]=b[d[e]]);return f.isEmptyObject(c)?null:this.Nr=b=a.ca.yi(a.Zf.CONVERTER_TYPE_DATETIME).createConverter(c)},EU:function(c,d){"value"===
d.option&&d.value&&this.ie(b(d.value?a.IntlConverterUtils.isoToLocalDate(d.value):new Date,this.bn()).toISOString(),c)},or:function(a){var b=f.ui.keyCode,c=!1;switch(a.keyCode){case b.UP:case b.DOWN:a.shiftKey&&(this.Td.ojInputTime("show"),c=!0)}return c?(a.preventDefault(),a.stopPropagation(),!1):this._superApply(arguments)},show:function(){this.Td.ojInputTime("hide");return this._super()},showTimePicker:function(){this.hide();return this.Td.ojInputTime("show")},hideTimePicker:function(){return this.Td.ojInputTime("hide")},
refresh:function(){return this._superApply(arguments)||this},ig:function(a){this._superApply(arguments);this.Td&&this.Td.ojInputTime("option","value",this.options.value)},getNodeBySubId:function(a){var b=a&&a.subId;return!b||"oj-listbox-drop"!==b&&"oj-inputdatetime-time-icon"!==b?this._superApply(arguments):this.Td.ojInputTime("getNodeBySubId",a)},getSubIdByNode:function(a){return this.Td.ojInputTime("getSubIdByNode",a)||this._superApply(arguments)},nc:function(){return this.options.converter?this._superApply(arguments):
f.oj.ojInputDateTime.prototype.options.converter},_GetMessagingLauncherElement:function(){return this.Sd?this.Or:this._super()},_GetDefaultStyleClass:function(){return"oj-inputdatetime"},Kz:function(){return"oj-ojInputDate"}})});
//# sourceMappingURL=oj-modular.map