/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define("ojs/ojcore jquery ojs/internal-deps/datagrid/DvtDataGrid ojs/ojcomponentcore ojs/ojdatacollection-common ojs/ojinputnumber ojs/ojmenu ojs/ojdialog ojs/ojpagingcontrol".split(" "),function(a,f,c){a.Ea=function(b,c){if(!(b instanceof Array)&&"function"!=typeof b&&"function"!=typeof b.wX)throw Error("_ERR_DATA_INVALID_TYPE_SUMMARY\n_ERR_DATA_INVALID_TYPE_DETAIL");null!=c&&(this.ek=c.rowHeader);this.C=0;this.na=-1;a.Ea.t.constructor.call(this,b)};o_("ArrayDataGridDataSource",a.Ea,a);a.b.sa(a.Ea,
a.Eb,"oj.ArrayDataGridDataSource");a.Ea.prototype.Init=function(){this.columns=this.pP(this.Pe());this.uR();"function"==typeof this.data&&this.data.subscribe(this.xU.bind(this),null,"arrayChange");a.Ea.t.Init.call(this)};a.b.g("ArrayDataGridDataSource.prototype.Init",{Init:a.Ea.prototype.Init});a.Ea.prototype.uR=function(){var a;a=this.Pe();for(this.Xj=0;this.Xj<a.length;this.Xj+=1)a[this.Xj].ojKey=this.Xj.toString()};a.Ea.prototype.pP=function(a){var c,e;if("number"!==typeof a.length||0===a.length)return[];
e=[];for(c in a[0])a[0].hasOwnProperty(c)&&(void 0!=this.ek&&c==this.ek||e.push(c));return e};a.Ea.prototype.Z=function(a){return"row"===a?this.size():"column"===a?this.columns.length:0};a.b.g("ArrayDataGridDataSource.prototype.getCount",{Z:a.Ea.prototype.Z});a.Ea.prototype.YH=function(a,c){var e;if("row"===a)return e=this.Pe(),c+=this.C,void 0!=this.ek?e[c][this.ek]:0<e.length&&e[0]instanceof Array?void 0===this.qh(c)?c.toString():this.qh(c):null;if("column"===a)return this.columns[c]};a.Ea.prototype.iW=
function(a,c){return"row"===a&&void 0!=this.ek?{key:this.qh(c+this.C)}:{key:this.YH(a,c)}};a.Ea.prototype.Xd=function(b,c,e){var g,f,k,l;g=b.axis;f=b.start;k=b.count;a.i.assert("row"===g||"column"===g);a.i.assert(f<this.Z(g));a.i.assert(0<k);f=Math.max(0,f);"column"===g?k=Math.min(this.columns.length,f+k):(l=this.Pe(),void 0!==this.ek||0<l.length&&l[0]instanceof Array?(k=Math.min(l.length,f+k),0<this.na&&(k=Math.min(k,this.totalSize()-this.C))):k=f);g=new a.de(f,k,g,this);null!=c&&null!=c.success&&
(null==e&&(e={}),c.success.call(e.success,g,b))};a.b.g("ArrayDataGridDataSource.prototype.fetchHeaders",{Xd:a.Ea.prototype.Xd});a.Ea.prototype.cW=function(a,c){var e=this.columns[c];return this.Pe()[a+this.C][e]};a.Ea.prototype.dW=function(a,c){return{keys:{row:this.qh(a+this.C),column:this.columns[c]}}};a.Ea.prototype.Vd=function(b,c,e){var g,f,k,l,m,n;for(g=0;g<b.length;g+=1)f=b[g],a.i.assert("row"===f.axis||"column"===f.axis),a.i.assert(f.start<this.Z(f.axis)),a.i.assert(0<f.count),"row"===f.axis?
(k=f.start,l=Math.min(this.size(),k+f.count),0<this.na&&(l=Math.min(l,this.totalSize()-this.C))):"column"===f.axis&&(m=f.start,n=Math.min(this.columns.length,m+f.count));void 0===l||void 0===n?null!=c&&null!=c.error&&(null==e&&(e={}),c.error.call(e.error)):(g=new a.Md(k,l,m,n,this),null!=c&&null!=c.success&&(null==e&&(e={}),c.success.call(e.success,g,b)),0<this.na&&a.Eb.t.handleEvent.call(this,"sync",!0))};a.b.g("ArrayDataGridDataSource.prototype.fetchCells",{Vd:a.Ea.prototype.Vd});a.Ea.prototype.keys=
function(b){var c=b.row,e=b.column;return a.b.ha(function(a){a({row:this.qh(c+this.C),column:this.columns[e]})}.bind(this))};a.b.g("ArrayDataGridDataSource.prototype.keys",{keys:a.Ea.prototype.keys});a.Ea.prototype.$d=function(b){var c=b.row,e=b.column;return a.b.ha(function(a){a({row:this.Mq(c)-this.C,column:this.columns.indexOf(e)})}.bind(this))};a.b.g("ArrayDataGridDataSource.prototype.indexes",{$d:a.Ea.prototype.$d});a.Ea.prototype.sort=function(a,c,e){var g=[],f=[],k,l;k=a.axis;l=a.key;a=a.direction;
null!=c&&null==e&&(e={});if("column"===k)this.Pe().sort(this.vE(a,l)),null!=c&&null!=c.success&&c.success.call(e.success);else if("row"===k){l=this.Mq(l);for(k=0;k<this.columns.length;k+=1)g[k]=this.Pe()[l][this.columns[k]];g.sort(this.vE(a));for(k=0;k<this.columns.length;k+=1)f[k]=this.columns[g.indexOf(this.Pe()[l][this.columns[k]])];this.columns=f;null!=c&&null!=c.success&&c.success.call(e.success)}else null!==c&&null!=c.error&&c.error.call(e.error,"Invalid axis value")};a.b.g("ArrayDataGridDataSource.prototype.sort",
{sort:a.Ea.prototype.sort});a.Ea.prototype.getCapability=function(a){return"sort"===a?"column":"move"===a?"row":null};a.b.g("ArrayDataGridDataSource.prototype.getCapability",{getCapability:a.Ea.prototype.getCapability});a.Ea.prototype.vE=function(a,c){if("ascending"===a)return function(a,b){var f,k;void 0!=c&&(a instanceof Array?(a=a[parseInt(c,10)],b=b[parseInt(c,10)]):(a=a[c],b=b[c]));f=isNaN(a);k=isNaN(b);a instanceof Date&&(a=a.toISOString(),f=!0);b instanceof Date&&(b=b.toISOString(),k=!0);return f&&
k?a<b?-1:a===b?0:1:f?1:k?-1:a-b};if("descending"===a)return function(a,b){var f,k;void 0!=c&&(a instanceof Array?(a=a[parseInt(c,10)],b=b[parseInt(c,10)]):(a=a[c],b=b[c]));f=isNaN(a);k=isNaN(b);a instanceof Date&&(a=a.toISOString(),f=!0);b instanceof Date&&(b=b.toISOString(),k=!0);return f&&k?a>b?-1:a===b?0:1:f?-1:k?1:b-a}};a.Ea.prototype.move=function(a,c){var e,f,h;e=this.Mq(a);f=this.data.splice(e,1)[0];this.data instanceof Array&&(e=this.gf("delete",a,null,e,-1),this.handleEvent("change",e));
null===c?this.data.push(f):(h=this.Mq(c),this.data.splice(h,0,f));this.data instanceof Array&&(e=this.gf("insert",a,null,h,-1),this.handleEvent("change",e))};a.b.g("ArrayDataGridDataSource.prototype.move",{move:a.Ea.prototype.move});a.Ea.prototype.Pe=function(){return"function"===typeof this.data?this.data():this.data};a.Ea.prototype.Mq=function(a){var c,e=this.Pe();for(c=0;c<e.length;c++)if(e[c].ojKey===a)return c;return-1};a.Ea.prototype.qh=function(a){var c=this.Pe();return c[a]?c[a].ojKey:null};
a.Ea.prototype.gf=function(a,c,e,f,h,k){var l={source:this};l.operation=a;l.keys={row:c,column:e};l.indexes={row:f,column:h};l.silent=k;return l};a.Ea.prototype.xU=function(a){var c,e,f,h,k=!1;e=!1;var l=[],m=[],n,q=0;for(c=0;c<a.length;c++){n=a[c];if(void 0!==n.moved){e=!0;n=this.gf("refresh",null,null);this.handleEvent("change",n);break}"added"===n.status&&(k=!0);0<this.na&&"deleted"===n.status&&n.index<this.C&&q++}if(!e){for(c=0;c<a.length;c++)n=a[c],"deleted"===n.status&&(e=n.value,h=n.index,
0<this.na?h<this.C?(h=0,f=this.qh(this.C-q),q--):h<this.C+this.na&&(h-=this.C,f=e.ojKey):f=e.ojKey,l.push({row:f,column:-1}),m.push({row:h,column:-1}));0<l.length&&(n={source:this,operation:"delete",keys:l,indexes:m,silent:k},this.handleEvent("change",n));for(c=0;c<a.length;c++)n=a[c],"added"===n.status&&(e=n.value,h=n.index,null==e.ojKey&&(e.ojKey=this.Xj.toString(),this.Xj++),0<this.na&&h<this.C+this.na?(h<this.C?(h=0,f=this.qh(this.C)):(h=n.index-this.C,f=this.qh(h)),n=this.gf("insert",f,null,
h,-1),this.handleEvent("change",n),n=this.gf("delete",this.qh(this.C+this.na),null,this.na,-1,!0)):(f=e.ojKey,n=this.gf("insert",f,null,h,-1)),this.handleEvent("change",n))}};a.Ea.prototype.fetch=function(a){this.C=null!=a?null!=a.startIndex?a.startIndex:0:0;this.handleEvent("change",{operation:"sync",pageSize:this.na})};a.Ea.prototype.setPageSize=function(a){var c=this.na;this.na=a;0>c&&this.fetch({startIndex:this.C})};a.b.g("ArrayDataGridDataSource.prototype.setPageSize",{setPageSize:a.Ea.prototype.setPageSize});
a.Ea.prototype.size=function(){return null!=this.na&&0<this.na&&this.Pe().length>this.na?this.na:this.Pe().length};a.b.g("ArrayDataGridDataSource.prototype.size",{size:a.Ea.prototype.size});a.Ea.prototype.totalSize=function(){return this.Pe().length};a.b.g("ArrayDataGridDataSource.prototype.totalSize",{totalSize:a.Ea.prototype.totalSize});a.Ea.prototype.hasMore=function(){return!1};a.b.g("ArrayDataGridDataSource.prototype.hasMore",{hasMore:a.Ea.prototype.hasMore});a.Ea.prototype.aI=function(){return this.ek};
a.b.g("ArrayDataGridDataSource.prototype.getRowHeaderKey",{aI:a.Ea.prototype.aI});a.Ea.prototype.Fi=function(){return this.columns};a.b.g("ArrayDataGridDataSource.prototype.getColumns",{Fi:a.Ea.prototype.Fi});a.Ea.prototype.getData=function(){return this.data};a.b.g("ArrayDataGridDataSource.prototype.getData",{getData:a.Ea.prototype.getData});a.Xe=function(b,c){this.iX=b;this.DX=c;this.Fa={};this.Fa.datagrid="oj-datagrid";this.Fa.cell="oj-datagrid-cell";this.Fa.cellcontent="oj-datagrid-cell-content";
this.Fa.celltext="oj-datagrid-cell-text";this.Fa.banded="oj-datagrid-banded";this.Fa.row="oj-datagrid-row";this.Fa.databody="oj-datagrid-databody";this.Fa.topcorner="oj-datagrid-top-corner";this.Fa.bottomcorner="oj-datagrid-bottom-corner";this.Fa.rowheaderspacer="oj-datagrid-row-header-spacer";this.Fa.colheaderspacer="oj-datagrid-column-header-spacer";this.Fa.status="oj-datagrid-status";this.Fa.emptytext="oj-datagrid-empty-text";this.Fa.header="oj-datagrid-header";this.Fa.headercell="oj-datagrid-header-cell";
this.Fa.headercelltext="oj-datagrid-header-cell-text";this.Fa.headercellcontent="oj-datagrid-header-cell-content";this.Fa.rowheader="oj-datagrid-row-header";this.Fa.colheader="oj-datagrid-column-header";this.Fa.colheadercell="oj-datagrid-column-header-cell";this.Fa.rowheadercell="oj-datagrid-row-header-cell";this.Fa["scroller-mobile"]="oj-datagrid-scroller-touch";this.Fa.scroller="oj-datagrid-scroller";this.Fa.scrollers="oj-datagrid-scrollers";this.Fa.focus="oj-focus";this.Fa.hover="oj-hover";this.Fa.active=
"oj-active";this.Fa.selected="oj-selected";this.Fa.disabled="oj-disabled";this.Fa.enabled="oj-enabled";this.Fa["default"]="oj-default";this.Fa.sortcontainer="oj-datagrid-sort-icon-container";this.Fa.sortascending="oj-datagrid-sort-ascending-icon";this.Fa.sortdescending="oj-datagrid-sort-descending-icon";this.Fa.icon="oj-component-icon";this.Fa.clickableicon="oj-clickable-icon-nocontext";this.Fa.info="oj-helper-hidden-accessible";this.Fa.rowexpander="oj-rowexpander";this.Fa.cut="oj-datagrid-cut";this.Fa.selectaffordancetop=
"oj-datagrid-touch-selection-affordance-top";this.Fa.selectaffordancebottom="oj-datagrid-touch-selection-affordance-bottom";this.Fa.toucharea="oj-datagrid-touch-area";this.Fa.draggable="oj-draggable";this.Fa.drag="oj-drag";this.Fa.drop="oj-drop";this.Fa.activedrop="oj-active-drop";this.Fa.validdrop="oj-valid-drop";this.Fa.invaliddrop="oj-invalid-drop";this.Me={};this.Me.sortCol="oj-datagrid-sortCol";this.Me.sortColAsc="oj-datagrid-sortColAsc";this.Me.sortColDsc="oj-datagrid-sortColDsc";this.Me.sortRow=
"oj-datagrid-sortRow";this.Me.sortRowAsc="oj-datagrid-sortRowAsc";this.Me.sortRowDsc="oj-datagrid-sortRowDsc";this.Me.resize="oj-datagrid-resize";this.Me.resizeWidth="oj-datagrid-resizeWidth";this.Me.resizeHeight="oj-datagrid-resizeHeight";this.Me.cut="oj-datagrid-cut";this.Me.paste="oj-datagrid-paste";this.attributes={};this.attributes.key="data-oj-key";this.attributes.resizable="data-oj-resizable";this.attributes.sortable="data-oj-sortable";this.attributes.sortDir="data-oj-sortdir";this.attributes.expander=
"data-oj-expander";this.attributes.expanderIndex="data-oj-expander-index";this.attributes.container=a.Components.Bp};o_("DataGridResources",a.Xe,a);a.Xe.prototype.CI=function(){return"rtl"===this.iX?!0:!1};a.b.g("DataGridResources.prototype.isRTLMode",{CI:a.Xe.prototype.CI});a.Xe.prototype.kI=function(a,c){return this.DX(a,c)};a.b.g("DataGridResources.prototype.getTranslatedText",{kI:a.Xe.prototype.kI});a.Xe.prototype.Ox=function(a){return null!=a?this.Fa[a]:null};a.b.g("DataGridResources.prototype.getMappedStyle",
{Ox:a.Xe.prototype.Ox});a.Xe.prototype.ns=function(a){return null!=a?this.Me[a]:null};a.b.g("DataGridResources.prototype.getMappedCommand",{ns:a.Xe.prototype.ns});a.Xe.prototype.Nx=function(a){return null!=a?this.attributes[a]:null};a.b.g("DataGridResources.prototype.getMappedAttribute",{Nx:a.Xe.prototype.Nx});a.Oa("oj.ojDataGrid",f.oj.baseComponent,{widgetEventPrefix:"oj",options:{bandingInterval:{row:0,column:0},data:null,emptyText:null,gridlines:{horizontal:"visible",vertical:"visible"},scrollPosition:null,
selectionMode:null,dnd:{Ul:{row:"disable"}},scrollPolicy:"auto",selection:[],header:{row:{className:null,renderer:null,resizable:{width:"disable",height:"disable"},sortable:"auto",style:null},column:{className:null,renderer:null,resizable:{width:"disable",height:"disable"},sortable:"auto",style:null}},cell:{className:null,renderer:null,style:null},resize:null,sort:null,optionChange:null},_ComponentCreate:function(){this._super();this.root=this.element[0];this.We=this.root.getAttribute("id");this.grid=
new c;this.ty={data:"all",header:["className","renderer","style","template"]}},Rh:function(){var b=this;this.dx(this.root);f(this.root).empty();this._super();this.dk=new a.Xe(this.Ec(),this.jD.bind(b));this.ZF();this.Fr();this.uM();null!=this.hc&&this.grid.SetDataSource(this.hc);this.grid.SetOptions(this.options);this.grid.SetResources(this.dk);this.grid.SetCreateContextCallback(this.iS.bind(b));this.grid.addListener("resize",function(a){b._trigger("resize",a.event,a.ui)});this.grid.addListener("select",
function(a){b.Oc("selection",a.ui.previousSelection,a.ui.selection,a.event)});this.grid.addListener("sort",function(a){b._trigger("sort",a.event,a.ui)});this.grid.addListener("keydown",function(a){b._trigger("keydown",a.event,a.ui)});this.grid.addListener("active",function(a){b._trigger("active",a.event,a.ui)});this.grid.render(this.root);null!=this.hc&&this.gl(this.root)},refresh:function(){this._super();this.dx(this.root);f(this.root).empty();this.ZF();null!=this.hc&&this.grid.SetDataSource(this.hc);
this.grid.SetOptions(this.options);this.grid.SetResources(this.dk);this.grid.refresh(this.root);null!=this.hc&&this.gl(this.root)},_destroy:function(){this.grid.destroy();this.dx(this.root);f(this.root).empty()},Oc:function(a,c,e,f){this._trigger("optionChange",f,{option:a,previousValue:c,value:e,optionMetadata:{writeback:f?"shouldWrite":"shouldNotWrite"}})},_setOptions:function(a,c){var e;this.hc?(e=this.pU(a),this._super(a,c),e?this.refresh():this.grid.UpdateOptions(a)):(this._super(a,c),null!=
a.data&&this.refresh())},pU:function(b){var c,e,f,h,k,l;f=!1;for(e in b)if(e in this.ty)if("data"===e){f=!0;break}else if("header"==e)for(h in b.header){if("column"==h||"row"==h||"cell"==h)for(k in b.header[h]){for(c=0;c<this.ty.header.length;c++)if(k==this.ty.header[c])for(l in this.options.header[h])if(l==k&&b.header[h][k]!=this.options.header[h][k]){f=!0;break}if(f)break}if(f)break}else for(l in this.options)if(l==e&&!a.b.xg(b[e],this.options[l])){f=!0;break}return f},Yk:function(a,c){return"disable"!==
this.options.header[a].resizable[c]},WD:function(a){return"disable"!==this.options.header[a].sortable},uM:function(){var a,c,e=null,g=null,h=null,k;a=this;if(null==this.options.contextMenu){if(null!=this.hc){c=f("\x3cul\x3e");c.css("display","none").attr("id",this.We+"contextmenu");f(this.root).append(c);if(this.Yk("column","width")||this.Yk("column","height")||this.Yk("row","width")||this.Yk("row","height"))e=this.dh("resize");k=this.hc.getCapability("sort");!this.WD("column")||"column"!==k&&"full"!==
k||(g=this.dh("sortCol"));!this.WD("row")||"row"!==k&&"full"!==k||(g=null!=g?g.add(this.dh("sortRow")):this.dh("sortRow"));if("enable"===this.options.dnd.reorder)switch(this.hc.getCapability("move")){case "none":break;default:h=f(this.je("cut")).add(f(this.je("paste")))}c.append(e).append(g).append(h);c.ojMenu();this._setOption("contextMenu","#"+c.attr("id"));c.on("ojbeforeopen",this.sh.bind(this));c.on("ojselect",this.th.bind(this))}}else c=f(this.options.contextMenu),e=c.find("[data-oj-command]"),
e.each(function(){var c;0===f(this).children("a").length&&(c=f(this).attr("data-oj-command").split("-"),f(this).replaceWith(a.dh(c[c.length-1])))}),c.ojMenu("refresh"),c.on("ojbeforeopen",this.sh.bind(this)),c.on("ojselect",this.th.bind(this))},dh:function(a){if("resize"===a)return f(this.je("resize")).append(f("\x3cul\x3e\x3c/ul\x3e").append(f(this.je("resizeWidth"))).append(f(this.je("resizeHeight"))));if("sortCol"===a)return f(this.je("sortCol")).append(f("\x3cul\x3e\x3c/ul\x3e").append(f(this.je("sortColAsc"))).append(f(this.je("sortColDsc"))));
if("sortRow"===a)return f(this.je("sortRow")).append(f("\x3cul\x3e\x3c/ul\x3e").append(f(this.je("sortRowAsc"))).append(f(this.je("sortRowDsc"))));if(-1!=Object.keys(this.dk.Me).indexOf(a))return f(this.je(a))},je:function(a){return"\x3cli data-oj-command\x3d"+this.mh(a)+"\x3e"+this.Mt(a)+"\x3c/li\x3e"},Mt:function(a){a="label"+a.charAt(0).toUpperCase()+a.slice(1);return'\x3ca href\x3d"#"\x3e'+this.jD(a)+"\x3c/a\x3e"},Su:function(){return f(this.options.contextMenu).get(0)},jD:function(a,c){return this.O(a,
c)},QQ:function(){var a=f("#"+this.We+"spinner").ojInputNumber("option","value");f("#"+this.We+"dialog").remove();this.grid.handleContextMenuReturn(this.yg,this.Hg,a);this.yg.target.focus()},gN:function(a,c){var e,g,h,k,l;e=f("#"+this.We+"dialog");h=f("#"+this.We+"spinner");if(0===e.length||0===h.length)e=f("\x3cdiv\x3e"),e.attr("id",this.We+"dialog"),e.attr("title",a),g=f('\x3cdiv class\x3d"oj-dialog-body"\x3e\x3c/div\x3e'),k=f('\x3cdiv class\x3d"oj-dialog-footer"\x3e\x3c/div\x3e'),e.append(g).append(k),
h=f('\x3cinput id\x3d"'+this.We+'spinner"/\x3e'),l=f("\x3cbutton\x3e"),g.append(h),k.append(l),f(this.root).append(e),l.ojButton({va:"ojButton",label:"OK"}),l.on("click",this.QQ.bind(this));h.ojInputNumber({va:"ojInputNumber",max:1E3,min:20,step:1,value:c});e.ojDialog({initialVisibility:"show",position:{my:"center center",at:"center center",collision:"none",of:f(this.root)}})},th:function(a,c){var e;this.Hg=c.item.attr("data-oj-command");if(this.Hg===this.mh("sortColAsc")||this.Hg===this.mh("sortColDsc")||
this.Hg===this.mh("cut")||this.Hg===this.mh("paste"))this.grid.handleContextMenuReturn(this.yg,this.Hg,null);else if(this.Hg===this.mh("resizeWidth")||this.Hg===this.mh("resizeHeight"))e=this.Ju(f(this.yg.target),"oj-datagrid-headercell"),e=null!=e?this.Hg===this.mh("resizeWidth")?e.outerWidth():e.outerHeight():this.Hg===this.mh("resizeWidth")?f(this.yg.target).outerWidth():f(this.yg.target).outerHeight(),this.gN(c.item.text(),e)},sh:function(a,c){var e;f(this.Su());this.yg=a.originalEvent.originalEvent;
c.openOptions.position="keydown"===this.yg.type?{my:"start top",at:"start bottom",of:this.yg.target}:{my:"start top",at:"start bottom"};e=this.Ju(f(this.yg.target).eq(0),this.tj("cell"));null!=e?e=this.kP(e):(e=this.Ju(f(this.yg.target).eq(0),this.tj("headercell")),e=this.CP(e));this.bS(e)},vM:function(a){var c;c=f(this.Su());c.find("[data-oj-command\x3d"+a+"]").hasClass("oj-disabled")||c.find("[data-oj-command\x3d"+a+"]").addClass("oj-disabled")},oT:function(a){f(this.Su()).find("[data-oj-command\x3d"+
a+"]").removeClass("oj-disabled")},bS:function(a){var c,e;for(c in a)a.hasOwnProperty(c)&&(e=this.dk.ns(c),"disable"===a[c]?this.vM(e):this.oT(e))},Ju:function(a,c){var e;if(a.hasClass(c))return a;e=a.parents("."+c);return 0!=e.length?e.eq(0):null},ZO:function(a){var c;c=a.parent();a=c.children().index(a);return{rowIndex:c.parent().children().index(c)-1,columnIndex:a}},$O:function(a){var c;c=this.$P().children().eq(0).children().eq(a.rowIndex+1);a=this.oP().children().eq(0).children().eq(a.columnIndex);
return{rowHeader:c,columnHeader:a}},cY:function(){return f(this.root)},oP:function(){return f("#"+this.We+"\\:columnHeader")},$P:function(){return f("#"+this.We+"\\:rowHeader")},bY:function(){return f("#"+this.We+"\\:databody")},sP:function(){return f("#"+this.We+"\\:databody ."+this.tj("row"))},kP:function(a){var c,e;a=this.ZO(a);c=this.$O(a);a={eX:"disable",dX:"disable",sX:"disable",rX:"disable"};e=c.rowHeader;c=c.columnHeader;0!==c.length&&("true"===c.attr(this.ci("resizable"))&&(a.resizeWidth=
"enable"),"true"===c.attr(this.ci("sortable"))&&(a.sortCol="enable"));0!==e.length&&("true"===e.attr(this.ci("resizable"))&&(a.resizeHeight="enable"),"true"===e.attr(this.ci("sortable"))&&(a.sortRow="enable"));return a},CP:function(a){var c;c={eX:"disable",dX:"disable",sX:"disable",rX:"disable"};null!==a&&(a.hasClass(this.tj("colheadercell"))?("true"===a.attr(this.ci("resizable"))&&(c.resizeWidth="enable"),c.resizeHeight=this.Yk("column","height")?"enable":"disable","true"===a.attr(this.ci("sortable"))&&
(c.sortCol="enable")):("true"===a.attr(this.ci("resizable"))&&(c.resizeHeight="enable"),c.resizeWidth=this.Yk("row","width")?"enable":"disable","true"===a.attr(this.ci("sortable"))&&(c.sortRow="enable")));return c},ZF:function(){this.hc=null!=this.options.data?this.options.data:null},Fr:function(){var a=this.options.selection;null!=a&&this.grid.SetSelection(a)},iS:function(a){a.component=this},Ar:function(a){this.grid.SetAccessibleContext(a)},dx:function(b){b&&this.me&&a.ba.Ti(b,this.me)},gl:function(b){b&&
(null==this.me&&(this.me=this.He.bind(this)),a.ba.ug(b,this.me))},He:function(a,c){0<a&&0<c&&this.grid.HandleResize(a,c)},getNodeBySubId:function(a){var c,e,g;if(null==a)return this.element?this.element[0]:null;c=a.subId;return"oj-datagrid-cell"===c?(c=a.rowIndex-this.grid.getStartRow(),a=a.columnIndex-this.grid.getStartColumn(),this.sP().eq(c).children().eq(a).get(0)):"oj-datagrid-sort-icon"===c||"oj-datagrid-header"===c?(g=a.axis,a=a.index,"column"===g?e=f("#"+this.We+"\\:columnHeader ."+this.tj("headercell")).eq(a-
this.grid.getStartColumnHeader()):"row"===g&&(e=f("#"+this.We+"\\:rowHeader ."+this.tj("headercell")).eq(a-this.grid.getStartRowHeader())),"oj-datagrid-sort-icon"===c?e.children("."+this.tj("sortcontainer")).children().get(0):e.get(0)):null},tj:function(a){return this.dk.Ox(a)},ci:function(a){return this.dk.Nx(a)},mh:function(a){return this.dk.ns(a)}});a.Ye=function(b,c,e,f,h,k){a.i.fc(b,null);a.i.fc(c,null);a.i.fc(e,null);a.i.fc(f,null);a.i.io(k);this.uf=b;this.Zj=c;this.Gg=e;this.Yj=f;this.kb=h;
this.Ic=k};o_("FlattenedTreeCellSet",a.Ye,a);a.Ye.prototype.getData=function(b){var c;c=this.VC(b);if(null==c)return null;b=c[0];c=c[1];a.i.assert(b<this.kb.Ka()+this.kb.Z()&&c<this.Ic.length);c=this.Ic[c];b=this.kb.getData(b);return null!=b?b.get?b.get(c):b[c]:null};a.b.g("FlattenedTreeCellSet.prototype.getData",{getData:a.Ye.prototype.getData});a.Ye.prototype.getMetadata=function(b){var c;c=this.VC(b);if(null==c)return null;b=c[0];c=c[1];a.i.assert(b<this.kb.Ka()+this.kb.Z()&&c<this.Ic.length);
c=this.Ic[c];b=this.kb.getMetadata(b);b.keys={row:b.key,column:c};return b};a.b.g("FlattenedTreeCellSet.prototype.getMetadata",{getMetadata:a.Ye.prototype.getMetadata});a.Ye.prototype.VC=function(b){var c;a.i.oe(b);if(null==this.kb||0==this.kb.length)return null;c=b.row-this.uf+this.kb.Ka();b=b.column;a.i.fc(c,null);a.i.fc(b,null);a.i.assert(0<=c&&0<=b);return[c,b]};a.Ye.prototype.Ka=function(a){return"row"===a?this.uf:"column"===a?this.Gg:0};a.b.g("FlattenedTreeCellSet.prototype.getStart",{Ka:a.Ye.prototype.Ka});
a.Ye.prototype.Z=function(a){return"row"===a?Math.min(this.Zj-this.uf,this.kb.Z()):"column"===a?this.Yj-this.Gg:0};a.b.g("FlattenedTreeCellSet.prototype.getCount",{Z:a.Ye.prototype.Z});a.Tg=function(b,c,e,f,h){a.i.fc(b,null);a.i.fc(c,null);a.i.io(e);this.vc=b;this.Qf=c;this.ys=e;this.kb=f;this.tf=h};o_("FlattenedTreeHeaderSet",a.Tg,a);a.Tg.prototype.getData=function(b){a.i.assert(b<=this.Qf&&b>=this.vc);return null!=this.tf&&null!=this.kb?(b=this.kb.getData(b),null!=b?b.get(this.tf):null):this.ys[b]};
a.b.g("FlattenedTreeHeaderSet.prototype.getData",{getData:a.Tg.prototype.getData});a.Tg.prototype.getMetadata=function(a){return null!=this.tf&&null!=this.kb?this.kb.getMetadata(a):{key:this.getData(a)}};a.b.g("FlattenedTreeHeaderSet.prototype.getMetadata",{getMetadata:a.Tg.prototype.getMetadata});a.Tg.prototype.Z=function(){return null!=this.tf&&null!=this.kb?Math.min(this.kb.Z(),this.Qf-this.vc):Math.max(0,this.Qf-this.vc)};a.b.g("FlattenedTreeHeaderSet.prototype.getCount",{Z:a.Tg.prototype.Z});
a.Md=function(b,c,e,f,h){a.i.fc(b,null);a.i.fc(c,null);a.i.fc(e,null);a.i.fc(f,null);this.uf=b;this.Zj=c;this.Gg=e;this.Yj=f;this.Pf=h};o_("ArrayCellSet",a.Md,a);a.Md.prototype.getData=function(a){return this.Pf.cW(a.row,a.column)};a.b.g("ArrayCellSet.prototype.getData",{getData:a.Md.prototype.getData});a.Md.prototype.getMetadata=function(a){return this.Pf.dW(a.row,a.column)};a.b.g("ArrayCellSet.prototype.getMetadata",{getMetadata:a.Md.prototype.getMetadata});a.Md.prototype.Ka=function(a){return"row"==
a?this.uf:"column"==a?this.Gg:-1};a.b.g("ArrayCellSet.prototype.getStart",{Ka:a.Md.prototype.Ka});a.Md.prototype.Z=function(a){return"row"===a?Math.max(0,this.Zj-this.uf):"column"===a?Math.max(0,this.Yj-this.Gg):0};a.b.g("ArrayCellSet.prototype.getCount",{Z:a.Md.prototype.Z});a.Md.prototype.getStartRow=function(){return this.uf};a.b.g("ArrayCellSet.prototype.getStartRow",{getStartRow:a.Md.prototype.getStartRow});a.Md.prototype.getStartColumn=function(){return this.Gg};a.b.g("ArrayCellSet.prototype.getStartColumn",
{getStartColumn:a.Md.prototype.getStartColumn});a.Pa=function(b,c){a.Pa.t.constructor.call(this,b,c)};o_("FlattenedTreeDataGridDataSource",a.Pa,a);a.b.sa(a.Pa,a.ga,"oj.FlattenedTreeDataGridDataSource");a.Pa.prototype.Init=function(){a.Pa.t.Init.call(this);this.Ic=a.Pa.t.so.call(this,"columns");this.tf=a.Pa.t.so.call(this,"rowHeader")};a.b.g("FlattenedTreeDataGridDataSource.prototype.Init",{Init:a.Pa.prototype.Init});a.Pa.prototype.pf=function(a){return"row"===a?"estimate":"actual"};a.b.g("FlattenedTreeDataGridDataSource.prototype.getCountPrecision",
{pf:a.Pa.prototype.pf});a.Pa.prototype.Z=function(a){return"row"===a?-1:"column"===a?this.Ic.length:0};a.b.g("FlattenedTreeDataGridDataSource.prototype.getCount",{Z:a.Pa.prototype.Z});a.Pa.prototype.Xd=function(b,c,e){var f,h;f=b.axis;if("column"===f)h=new a.Tg(b.start,b.start+b.count,this.Ic);else if("row"===f){if(null!=this.tf){this.Fg={range:b,callbacks:c,callbackObjects:e};return}h=new a.de(b.start,b.start,f,null)}null!=h&&null!=c&&null!=c.success&&(null==e&&(e={}),c.success.call(e.success,h,
b))};a.b.g("FlattenedTreeDataGridDataSource.prototype.fetchHeaders",{Xd:a.Pa.prototype.Xd});a.Pa.prototype.Vd=function(b,c,e){var f,h,k,l;for(f=0;f<b.length;f++)if(h=b[f],"row"==h.axis){k=h.start;l=h.count;break}a.Pa.t.DH.call(this,{start:k,count:l},{success:function(a){this.Iv(a,b,c,e,0)}.bind(this),error:function(a){this.xQ(a,{start:k,count:l},c,e)}.bind(this)})};a.b.g("FlattenedTreeDataGridDataSource.prototype.fetchCells",{Vd:a.Pa.prototype.Vd});a.Pa.prototype.keys=function(b){var c;c=b.row;b=
b.column;return c>a.Pa.t.hW.call(this).end||b>this.Ic.length?null:{row:a.Pa.t.getKey.call(this,c),column:this.Ic[b]}};a.b.g("FlattenedTreeDataGridDataSource.prototype.keys",{keys:a.Pa.prototype.keys});a.Pa.prototype.$d=function(b){var c,e,f;c=b.row;b=b.column;c=a.Pa.t.Cl.call(this,c);for(f=0;f<this.Ic.length;f++)if(this.Ic[f]===b){e=f;break}return 0<=c&&0<=e?{row:c,column:e}:null};a.b.g("FlattenedTreeDataGridDataSource.prototype.indexes",{$d:a.Pa.prototype.$d});a.Pa.prototype.sort=function(b,c,e){return a.Pa.t.getWrappedDataSource.call(this).sort(b,
{success:function(){this.TQ(c,e)}.bind(this),error:c.error})};a.b.g("FlattenedTreeDataGridDataSource.prototype.sort",{sort:a.Pa.prototype.sort});a.Pa.prototype.TQ=function(a,c){this.refresh();a.success&&(null==c&&(c={}),a.success.call(c.success))};a.Pa.prototype.move=function(b,c,e,f){a.Pa.t.getWrappedDataSource.call(this).move(b,c,e,f)};a.b.g("FlattenedTreeDataGridDataSource.prototype.move",{move:a.Pa.prototype.move});a.Pa.prototype.getCapability=function(b){return"default"===a.Pa.t.getWrappedDataSource.call(this).getCapability(b)?
"column":"none"};a.b.g("FlattenedTreeDataGridDataSource.prototype.getCapability",{getCapability:a.Pa.prototype.getCapability});a.Pa.prototype.Bo=function(b,c){a.Pa.t.Bo.call(this,b,c)};a.Pa.prototype.Iv=function(b,c,e,f){var h,k,l,m,n,q;for(h=0;h<c.length;h++)k=c[h],"row"==k.axis?(l=k.start,m=k.count):"column"==k.axis&&(n=k.start,q=k.count);this.Fg&&(h=this.Fg.range,h.start==l&&h.count==m&&this.RQ(b,h,this.Fg.callbacks,this.Fg.callbackObjects),this.Fg=null);b=new a.Ye(l,l+m,n,n+q,b,this.Ic);e.success&&
(null==f&&(f={}),e.success.call(f.success,b,c))};a.Pa.prototype.xQ=function(a,c,e,f){var h;this.Fg&&(h=this.Fg.range,h.start==c.start&&h.count==c.count&&(c=this.Fg.callbacks,h=this.Fg.callbackObjects,c.error&&(null==h&&(h={}),c.error.call(h.error,a))),this.Fg=null);e.error&&(null==f&&(f={}),e.success.call(f.error,a))};a.Pa.prototype.RQ=function(b,c,e,f){b=new a.Tg(c.start,c.start+c.count,this.Ic,b,this.tf);e.success&&(null==f&&(f={}),e.success.call(f.success,b,c))};a.Pa.prototype.us=function(b,c,
e){b=new a.Ye(b,b+e.Z(),0,this.Ic.length,e,this.Ic);e={source:this,operation:"insert"};e.result=b;e.keys={row:c};a.Pa.t.handleEvent.call(this,"change",e)};a.Pa.prototype.Hs=function(b){var c,e;c=[];for(e=0;e<b.length;e++)c.push({row:b[e].key});b={source:this,operation:"delete"};b.keys=c;a.Pa.t.handleEvent.call(this,"change",b)};a.Pa.prototype.Tx=function(b,c){c.success.call(null,new a.Xc(null,b.start))};a.Ua=function(b){if(!(b instanceof a.Eb))throw new a.U("Not a datagridatasource","Not a datagridatasource",
a.U.Mb.ERROR);this.Ra=b;this.C=0;this.Init()};o_("PagingDataGridDataSource",a.Ua,a);a.b.sa(a.Ua,a.lb,"oj.PagingDataGridDataSource");a.Ua.prototype.Init=function(){a.Ua.t.Init.call(this)};a.b.g("PagingDataGridDataSource.prototype.Init",{Init:a.Ua.prototype.Init});a.Ua.prototype.fetch=function(b){this.uh=!0;this.C=b.startIndex;this.Ra.setPageSize(this.fd);var c=this;return a.b.ha(function(a){c.Ra.fetch(b);a()})};a.b.g("PagingDataGridDataSource.prototype.fetch",{fetch:a.Ua.prototype.fetch});a.Ua.prototype.hasMore=
function(){return this.Ra.hasMore()};a.b.g("PagingDataGridDataSource.prototype.hasMore",{hasMore:a.Ua.prototype.hasMore});a.Ua.prototype.next=function(){return this.Ra.totalSize()>this.C?(this.fd+=this.na,this.Ra.setPageSize(this.fd),this.fetch({startIndex:this.C})):a.b.ha(function(a,c){c()})};a.b.g("PagingDataGridDataSource.prototype.next",{next:a.Ua.prototype.next});a.Ua.prototype.previous=function(){return 0!=this.C||-1!=this.C?(this.C-=this.na,this.C=0>this.C?0:this.C,this.fd+=this.na,this.Ra.setPageSize(this.fd),
this.fetch({startIndex:this.C})):a.b.ha(function(a,c){c()})};a.b.g("PagingDataGridDataSource.prototype.previous",{previous:a.Ua.prototype.previous});a.Ua.prototype.setPageSize=function(a){this.na=a;this.fd=this.C+a;this.Ra.setPageSize(this.fd)};a.Ua.prototype.startIndex=function(){return this.C};a.b.g("PagingDataGridDataSource.prototype.startIndex",{startIndex:a.Ua.prototype.startIndex});a.Ua.prototype.Z=function(a){return this.Ra.Z(a)};a.b.g("PagingDataGridDataSource.prototype.getCount",{Z:a.Ua.prototype.Z});
a.Ua.prototype.pf=function(a){return this.Ra.pf(a)};a.b.g("PagingDataGridDataSource.prototype.getCountPrecision",{pf:a.Ua.prototype.pf});a.Ua.prototype.Xd=function(b,c,e){var f;null==this.uh?(f=new a.de(0,0,b.axis,null),null!=c&&c.success&&c.success.call(e.success,f,b)):this.Ra.Xd(b,c,e)};a.b.g("PagingDataGridDataSource.prototype.fetchHeaders",{Xd:a.Ua.prototype.Xd});a.Ua.prototype.Vd=function(b,c,e){var f;null==this.uh?(f=new a.Md(0,0,0,0,null),null!=c&&c.success&&c.success.call(e.success,f,b)):
this.Ra.Vd(b,c,e)};a.b.g("PagingDataGridDataSource.prototype.fetchCells",{Vd:a.Ua.prototype.Vd});a.Ua.prototype.keys=function(a){return this.Ra.keys(a)};a.b.g("PagingDataGridDataSource.prototype.keys",{keys:a.Ua.prototype.keys});a.Ua.prototype.$d=function(a){return this.Ra.$d(a)};a.b.g("PagingDataGridDataSource.prototype.indexes",{$d:a.Ua.prototype.$d});a.Ua.prototype.on=function(a,c){this.Ra.on(a,c)};a.b.g("PagingDataGridDataSource.prototype.on",{on:a.Ua.prototype.on});a.Ua.prototype.off=function(a,
c){this.Ra.off(a,c)};a.b.g("PagingDataGridDataSource.prototype.off",{off:a.Ua.prototype.off});a.Ua.prototype.getCapability=function(a){return this.Ra.getCapability(a)};a.b.g("PagingDataGridDataSource.prototype.getCapability",{getCapability:a.Ua.prototype.getCapability});a.Ua.prototype.size=function(){return null==this.uh?-1:this.Ra.size()};a.b.g("PagingDataGridDataSource.prototype.size",{size:a.Ua.prototype.size});a.Ua.prototype.sort=function(a,c,e){this.Ra.sort(a,c,e)};a.b.g("PagingDataGridDataSource.prototype.sort",
{sort:a.Ua.prototype.sort});a.Ua.prototype.totalSize=function(){return null==this.uh?-1:this.Ra.totalSize()};a.b.g("PagingDataGridDataSource.prototype.totalSize",{totalSize:a.Ua.prototype.totalSize});a.Ua.prototype.move=function(a,c){this.Ra.move(a,c)};a.b.g("PagingDataGridDataSource.prototype.move",{move:a.Ua.prototype.move});a.de=function(b,c,e,f){a.i.fc(b,null);a.i.fc(c,null);this.vc=b;this.Qf=c;this.GI=e;this.Pf=f};o_("ArrayHeaderSet",a.de,a);a.de.prototype.getData=function(b){if(null==this.Pf)return null;
a.i.assert(b<=this.Qf&&b>=this.vc);return this.Pf.YH(this.GI,b)};a.b.g("ArrayHeaderSet.prototype.getData",{getData:a.de.prototype.getData});a.de.prototype.getMetadata=function(b){if(null==this.Pf)return null;a.i.assert(b<=this.Qf&&b>=this.vc);return this.Pf.iW(this.GI,b)};a.b.g("ArrayHeaderSet.prototype.getMetadata",{getMetadata:a.de.prototype.getMetadata});a.de.prototype.Z=function(){return null==this.Pf?0:Math.max(0,this.Qf-this.vc)};a.b.g("ArrayHeaderSet.prototype.getCount",{Z:a.de.prototype.Z});
a.de.prototype.Ka=function(){return this.vc};a.b.g("ArrayHeaderSet.prototype.getStart",{Ka:a.de.prototype.Ka})});
//# sourceMappingURL=oj-modular.map