/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(a,f){(function(){var c=!1;f(document).mouseup(function(){c=!1});a.Oa("oj.ojResizable",f.oj.baseComponent,{version:"1.0.0",widgetEventPrefix:"oj",options:{cancel:"input,textarea,button,select,option",distance:1,delay:0,maxHeight:null,maxWidth:null,minHeight:10,minWidth:10,alsoResize:!1,animate:!1,animateDuration:"slow",animateEasing:"swing",containment:!1,ghost:!1,grid:!1,handles:"e,s,se",helper:!1,resize:null,start:null,stop:null},mS:function(){var a=
this;this.element.bind("mousedown."+this.widgetName,function(c){return a.lS(c)}).bind("click."+this.widgetName,function(c){if(!0===f.data(c.target,a.widgetName+".preventClickEvent"))return f.removeData(c.target,a.widgetName+".preventClickEvent"),c.stopImmediatePropagation(),!1})},kS:function(){this.element.unbind("."+this.widgetName);this.jr&&this.document.unbind("mousemove."+this.widgetName,this.jr).unbind("mouseup."+this.widgetName,this.jw)},lS:function(a){if(!c){this.ji&&this.kr(a);this.ir=a;var d=
this,e=1===a.which,g="string"===typeof this.options.cancel&&a.target.nodeName?f(a.target).closest(this.options.cancel).length:!1;if(!e||g||!this.jS(a))return!0;(this.So=!this.options.delay)||setTimeout(function(){d.So=!0},this.options.delay);if(this.rE(a)&&this.So&&(this.ji=!1!==this.tE(a),!this.ji))return a.preventDefault(),!0;!0===f.data(a.target,this.widgetName+".preventClickEvent")&&f.removeData(a.target,this.widgetName+".preventClickEvent");this.jr=function(a){return d.nS(a)};this.jw=function(a){return d.kr(a)};
this.document.bind("mousemove."+this.widgetName,this.jr).bind("mouseup."+this.widgetName,this.jw);a.preventDefault();return c=!0}},nS:function(a){if(f.ui.SY&&(!document.documentMode||9>document.documentMode)&&!a.button||!a.which)return this.kr(a);if(this.ji)return this.sE(a),a.preventDefault();this.rE(a)&&this.So&&((this.ji=!1!==this.tE(this.ir,a))?this.sE(a):this.kr(a));return!this.ji},kr:function(a){this.document.unbind("mousemove."+this.widgetName,this.jr).unbind("mouseup."+this.widgetName,this.jw);
this.ji&&(this.ji=!1,a.target===this.ir.target&&f.data(a.target,this.widgetName+".preventClickEvent",!0),this.oS(a));return c=!1},rE:function(a){return Math.max(Math.abs(this.ir.pageX-a.pageX),Math.abs(this.ir.pageY-a.pageY))>=this.options.distance},EY:function(){return this.So},mw:function(a){return parseInt(a,10)||0},Bd:function(a){return!isNaN(parseInt(a,10))},tD:function(a,c){if("hidden"===f(a).css("overflow"))return!1;var e=c&&"left"===c?"scrollLeft":"scrollTop",g=!1;if(0<a[e])return!0;a[e]=
1;g=0<a[e];a[e]=0;return g},_ComponentCreate:function(){this._super();var a,c,e,g,h,k=this;a=this.options;this.element.addClass("oj-resizable");f.extend(this,{Cs:this.element,tr:[],ng:null});this.handles=a.handles||(f(".oj-resizable-handle",this.element).length?{WY:".oj-resizable-n",MY:".oj-resizable-e",dZ:".oj-resizable-s",Vc:".oj-resizable-w",fZ:".oj-resizable-se",hZ:".oj-resizable-sw",XY:".oj-resizable-ne",$Y:".oj-resizable-nw"}:"e,s,se");if(this.handles.constructor===String)for("all"===this.handles&&
(this.handles="n,e,s,w,se,sw,ne,nw"),a=this.handles.split(","),this.handles={},c=0;c<a.length;c++)e=f.trim(a[c]),h="oj-resizable-"+e,g=f("\x3cdiv class\x3d'oj-resizable-handle "+h+"'\x3e\x3c/div\x3e"),this.handles[e]=".oj-resizable-"+e,this.element.append(g);this.xT=function(){for(var a in this.handles)this.handles[a].constructor===String&&(this.handles[a]=this.element.children(this.handles[a]).first().show())};this.xT();this.ZQ=f(".oj-resizable-handle",this.element);this.ZQ.mouseover(function(){k.$I||
(this.className&&(g=this.className.match(/oj-resizable-(se|sw|ne|nw|n|e|s|w)/i)),k.axis=g&&g[1]?g[1]:"se")});this.mS()},_destroy:function(){this.kS();f(this.Cs).removeClass("oj-resizable oj-resizable-disabled oj-resizable-resizing").removeData("resizable").removeData("oj-resizable").unbind(".resizable").find(".oj-resizable-handle").remove();return this},jS:function(a){var c,e,g=!1;for(c in this.handles)if(e=f(this.handles[c])[0],e===a.target||f.contains(e,a.target))g=!0;return!this.options.disabled&&
g},tE:function(a){var c,e,g;g=this.options;c=this.element.position();var h=this.element;this.$I=!0;/absolute/.test(h.css("position"))?h.css({position:"absolute",top:h.css("top"),left:h.css("left")}):h.is(".ui-draggable")&&h.css({position:"absolute",top:c.top,left:c.left});this.yT();c=this.mw(this.helper.css("left"));e=this.mw(this.helper.css("top"));g.containment&&(c+=f(g.containment).scrollLeft()||0,e+=f(g.containment).scrollTop()||0);this.offset=this.helper.offset();this.position={left:c,top:e};
this.size={width:h.width(),height:h.height()};this.Sf={width:h.width(),height:h.height()};this.Ri={left:c,top:e};this.Ks={width:h.outerWidth()-h.width(),height:h.outerHeight()-h.height()};this.UW={left:a.pageX,top:a.pageY};this.vg=this.Sf.width/this.Sf.height||1;g=f(".oj-resizable-"+this.axis).css("cursor");f("body").css("cursor","auto"===g?this.axis+"-resize":g);h.addClass("oj-resizable-resizing");this.xw("start",a);this.IM(a);this.IN(a);return!0},sE:function(a){var c,e=this.helper,g={},h=this.UW;
c=a.pageX-h.left||0;var h=a.pageY-h.top||0,k=this.eh[this.axis];this.Rl={top:this.position.top,left:this.position.left};this.Sl={width:this.size.width,height:this.size.height};if(!k)return!1;c=k.apply(this,[a,c,h]);this.YU(a.shiftKey);a.shiftKey&&(c=this.VU(c,a));c=this.HT(c,a);this.RU(c);this.xw("resize",a);this.HM(a,this.ui());this.HN(a,this.ui());this.position.top!==this.Rl.top&&(g.top=this.position.top+"px");this.position.left!==this.Rl.left&&(g.left=this.position.left+"px");this.size.width!==
this.Sl.width&&(g.width=this.size.width+"px");this.size.height!==this.Sl.height&&(g.height=this.size.height+"px");e.css(g);!this.ng&&this.tr.length&&this.US();f.isEmptyObject(g)||this._trigger("resize",a,this.ui());return!1},oS:function(a){this.$I=!1;f("body").css("cursor","auto");this.element.removeClass("oj-resizable-resizing");this.xw("stop",a);this.JM(a);this.JN(a);return!1},YU:function(a){var c,e,f,h;h=this.options;h={minWidth:this.Bd(h.minWidth)?h.minWidth:0,maxWidth:this.Bd(h.maxWidth)?h.maxWidth:
Infinity,minHeight:this.Bd(h.minHeight)?h.minHeight:0,maxHeight:this.Bd(h.maxHeight)?h.maxHeight:Infinity};a&&(a=h.minHeight*this.vg,e=h.minWidth/this.vg,c=h.maxHeight*this.vg,f=h.maxWidth/this.vg,a>h.minWidth&&(h.minWidth=a),e>h.minHeight&&(h.minHeight=e),c<h.maxWidth&&(h.maxWidth=c),f<h.maxHeight&&(h.maxHeight=f));this.aV=h},RU:function(a){this.offset=this.helper.offset();this.Bd(a.left)&&(this.position.left=a.left);this.Bd(a.top)&&(this.position.top=a.top);this.Bd(a.height)&&(this.size.height=
a.height);this.Bd(a.width)&&(this.size.width=a.width)},VU:function(a){var c=this.position,e=this.size,f=this.axis;this.Bd(a.height)?a.width=a.height*this.vg:this.Bd(a.width)&&(a.height=a.width/this.vg);"sw"===f&&(a.left=c.left+(e.width-a.width),a.top=null);"nw"===f&&(a.top=c.top+(e.height-a.height),a.left=c.left+(e.width-a.width));return a},HT:function(a){var c=this.aV,e=this.axis,f=this.Bd(a.width)&&c.maxWidth&&c.maxWidth<a.width,h=this.Bd(a.height)&&c.maxHeight&&c.maxHeight<a.height,k=this.Bd(a.width)&&
c.minWidth&&c.minWidth>a.width,l=this.Bd(a.height)&&c.minHeight&&c.minHeight>a.height,m=this.Ri.left+this.Sf.width,n=this.position.top+this.size.height,q=/sw|nw|w/.test(e),e=/nw|ne|n/.test(e);k&&(a.width=c.minWidth);l&&(a.height=c.minHeight);f&&(a.width=c.maxWidth);h&&(a.height=c.maxHeight);k&&q&&(a.left=m-c.minWidth);f&&q&&(a.left=m-c.maxWidth);l&&e&&(a.top=n-c.minHeight);h&&e&&(a.top=n-c.maxHeight);a.width||a.height||a.left||!a.top?a.width||a.height||a.top||!a.left||(a.left=null):a.top=null;return a},
US:function(){if(this.tr.length){var a,c,e,f,h,k=this.helper||this.element;for(a=0;a<this.tr.length;a++){h=this.tr[a];if(!this.ul)for(this.ul=[],e=[h.css("borderTopWidth"),h.css("borderRightWidth"),h.css("borderBottomWidth"),h.css("borderLeftWidth")],f=[h.css("paddingTop"),h.css("paddingRight"),h.css("paddingBottom"),h.css("paddingLeft")],c=0;c<e.length;c++)this.ul[c]=(parseInt(e[c],10)||0)+(parseInt(f[c],10)||0);h.css({height:k.height()-this.ul[0]-this.ul[2]||0,width:k.width()-this.ul[1]-this.ul[3]||
0})}}},yT:function(){this.element.offset();this.helper=this.element},eh:{e:function(a,c){return{width:this.Sf.width+c}},w:function(a,c){return{left:this.Ri.left+c,width:this.Sf.width-c}},n:function(a,c,e){return{top:this.Ri.top+e,height:this.Sf.height-e}},s:function(a,c,e){return{height:this.Sf.height+e}},se:function(a,c,e){return f.extend(this.eh.s.apply(this,arguments),this.eh.e.apply(this,[a,c,e]))},sw:function(a,c,e){return f.extend(this.eh.s.apply(this,arguments),this.eh.w.apply(this,[a,c,e]))},
ne:function(a,c,e){return f.extend(this.eh.n.apply(this,arguments),this.eh.e.apply(this,[a,c,e]))},nw:function(a,c,e){return f.extend(this.eh.n.apply(this,arguments),this.eh.w.apply(this,[a,c,e]))}},xw:function(a,c){"resize"!==a&&this._trigger(a,c,this.ui())},IM:function(){function a(b){f(b).each(function(){var a=f(this);a.data("oj-resizable-alsoresize",{width:parseInt(a.width(),10),height:parseInt(a.height(),10),left:parseInt(a.css("left"),10),top:parseInt(a.css("top"),10)})})}var c=this.options;
"object"!==typeof c.alsoResize||c.alsoResize.parentNode?a(c.alsoResize):c.alsoResize.length?(c.alsoResize=c.alsoResize[0],a(c.alsoResize)):f.each(c.alsoResize,function(c){a(c)})},HM:function(a,c){function e(a,b){f(a).each(function(){var a=f(this),e=f(this).data("oj-resizable-alsoresize"),g={};f.each(b&&b.length?b:a.parents(c.Cs[0]).length?["width","height"]:["width","height","top","left"],function(a,b){var c=(e[b]||0)+(l[b]||0);c&&0<=c&&(g[b]=c||null)});a.css(g)})}var g=this.options,h=this.Sf,k=this.Ri,
l={height:this.size.height-h.height||0,width:this.size.width-h.width||0,top:this.position.top-k.top||0,left:this.position.left-k.left||0};"object"!==typeof g.alsoResize||g.alsoResize.nodeType?e(g.alsoResize,null):f.each(g.alsoResize,function(a,b){e(a,b)})},JM:function(){f(this).removeData("oj-resizable-alsoresize")},IN:function(){var a,c,e,g,h,k=this,l=k.element;e=k.options.containment;if(l=e instanceof f?e.get(0):/parent/.test(e)?l.parent().get(0):e)k.cs=f(l),/document/.test(e)||e===document?(k.ds=
{left:0,top:0},k.qH={left:0,top:0},k.Si={element:f(document),left:0,top:0,width:f(document).width(),height:f(document).height()||document.body.parentNode.scrollHeight}):(a=f(l),c=[],f(["Top","Right","Left","Bottom"]).each(function(e,f){c[e]=k.mw(a.css("padding"+f))}),k.ds=a.offset(),k.qH=a.position(),k.rH={height:a.innerHeight()-c[3],width:a.innerWidth()-c[1]},e=k.ds,g=k.rH.height,h=k.rH.width,h=k.tD(l,"left")?l.scrollWidth:h,g=k.tD(l)?l.scrollHeight:g,k.Si={element:l,left:e.left,top:e.top,width:h,
height:g})},HN:function(a,c){var e,f,h,k;e=this.options;f=this.ds;k=this.position;var l=a.shiftKey;h={top:0,left:0};var m=this.cs,n=!0;m[0]!==document&&/static/.test(m.css("position"))&&(h=f);k.left<(this.ng?f.left:0)&&(this.size.width+=this.ng?this.position.left-f.left:this.position.left-h.left,l&&(this.size.height=this.size.width/this.vg,n=!1),this.position.left=e.helper?f.left:0);k.top<(this.ng?f.top:0)&&(this.size.height+=this.ng?this.position.top-f.top:this.position.top,l&&(this.size.width=this.size.height*
this.vg,n=!1),this.position.top=this.ng?f.top:0);this.offset.left=this.Si.left+this.position.left;this.offset.top=this.Si.top+this.position.top;e=Math.abs((this.ng?this.offset.left-h.left:this.offset.left-f.left)+this.Ks.width);f=Math.abs((this.ng?this.offset.top-h.top:this.offset.top-f.top)+this.Ks.height);h=this.cs.get(0)===this.element.parent().get(0);k=/relative|absolute/.test(this.cs.css("position"));h&&k&&(e-=Math.abs(this.Si.left));e+this.size.width>=this.Si.width&&(this.size.width=this.Si.width-
e,l&&(this.size.height=this.size.width/this.vg,n=!1));f+this.size.height>=this.Si.height&&(this.size.height=this.Si.height-f,l&&(this.size.width=this.size.height*this.vg,n=!1));n||(this.position.left=c.Rl.left,this.position.top=c.Rl.top,this.size.width=c.Sl.width,this.size.height=c.Sl.height)},JN:function(){var a=this.options,c=this.ds,e=this.qH,g=this.cs,h=f(this.helper),k=h.offset(),l=h.outerWidth()-this.Ks.width,h=h.outerHeight()-this.Ks.height;this.ng&&!a.animate&&/relative/.test(g.css("position"))&&
f(this).css({left:k.left-e.left-c.left,width:l,height:h});this.ng&&!a.animate&&/static/.test(g.css("position"))&&f(this).css({left:k.left-e.left-c.left,width:l,height:h})},ui:function(){return{Cs:this.Cs,element:this.element,helper:this.helper,position:this.position,size:this.size,Sf:this.Sf,Ri:this.Ri,Sl:this.Sl,Rl:this.Rl}}})})();(function(){a.Oa("oj.ojDialog",f.oj.baseComponent,{version:"1.0.0",widgetEventPrefix:"oj",options:{cancelBehavior:"icon",dragAffordance:"title-bar",initialVisibility:"hide",
modality:"modal",position:{my:"center",at:"center",of:window,collision:"fit",mZ:function(a){var b=f(this).css(a).offset().top;0>b&&f(this).css("top",a.top-b)}},resizeBehavior:"resizable",role:"dialog",title:null,beforeClose:null,beforeOpen:null,close:null,focus:null,open:null,resize:null,resizeStart:null,resizeStop:null},_ComponentCreate:function(){this._super();this.TW={display:this.element[0].style.display,width:this.element[0].style.width,height:this.element[0].style.height};this.Ri={parent:this.element.parent(),
index:this.element.parent().children().index(this.element)};this.oy=this.element.attr("title");this.options.title=this.options.title||this.oy;this.hO();this.element.show().removeAttr("title").addClass("oj-dialog-content oj-dialog-default-content").appendTo(this.Ja);this.Zl=!1;if(this.element.find(".oj-dialog").length){var c=this;this.element.find(".oj-dialog-header").each(function(a,d){var e=f(d);if(!e.closest(".oj-dialog-body").length)return c.Bh=e,c.Zl=!0,!1})}else this.Bh=this.element.find(".oj-dialog-header"),
this.Bh.length&&(this.Zl=!0);this.Zl?(this.eO(this.Bh),this.Bh.prependTo(this.Ja),"icon"===this.options.cancelBehavior&&(this.fq(this.Bh),this.co=this.Bh.find(".oj-dialog-title"),this.co.length&&this.co.insertAfter(this.hk))):this.gO();this.Wf=this.element.find(".oj-dialog-footer");this.dO(this.Wf);this.Wf&&(this.Wf.addClass("oj-helper-clearfix"),this.Wf.appendTo(this.Ja));"title-bar"===this.options.dragAffordance&&f.fn.draggable&&this.hE();this.PB=this.DT.bind(this);this.wu=window.setTimeout(this.PB,
50);this.rD=this.He.bind(this);a.ba.ug(this.Ja[0],this.rD);this.pn=!0;this._isOpen=!1;this.KU();this._super()},_init:function(){"show"===this.options.initialVisibility&&this.open()},NM:function(){return this.document.find("body").eq(0)},_destroy:function(){this._isOpen&&this.close();this.pn&&(a.ba.Ti(this.Ja[0],this.rD),this.pn=!1);this.Kj&&(this.Kj("destroy"),this.Kj=null);this.Wf&&(this.Wf.removeClass("oj-helper-clearfix"),f("#"+this.KE).replaceWith(this.Wf));this.RB();if(this.Zl){var c=this.Ja.find(".oj-dialog-header");
c&&f("#"+this.LE).replaceWith(c)}this.uJ&&(this.uJ.remove(),this.uJ=null);this.element.removeUniqueId().removeClass("oj-dialog-content oj-dialog-default-content").css(this.TW);this.Ja.stop(!0,!0);this.element.unwrap();this.oy&&this.element.attr("title",this.oy);this._super()},He:function(){null==this.wu&&(this.wu=window.setTimeout(this.PB,50))},refresh:function(){this._super()},widget:function(){return this.Ja},disable:f.noop,enable:f.noop,close:function(c){var b=this;this._isOpen&&!1!==this._trigger("beforeClose",
c)&&(a.Components.Iy(this.Ja[0]),this._isOpen=!1,this.sC=null,this.TB(),this.PG(),this.opener.filter(":focusable").focus().length||f(this.document[0].activeElement).blur(),this._hide(this.Ja,null,function(){b._trigger("close",c)}),f("#"+this.ME).replaceWith(f("#"+this.px)))},isOpen:function(){return this._isOpen},kw:function(a,b){var d=!!this.Ja.nextAll(":visible").insertBefore(this.Ja).length;d&&!b&&this._trigger("focus",a);return d},open:function(c){if(!1!==this._trigger("beforeOpen",c)){var b=
this;this._isOpen?this.kw()&&this.$m():(this._isOpen=!0,this.opener=f(this.document[0].activeElement),this.uU(),"resizable"===this.options.resizeBehavior&&this.kE(),this.kT(),this.zB(),this.NE(),this.kw(null,!0),this._show(this.Ja,null,function(){b.$m();b._trigger("focus")}),a.Components.Jy(this.Ja[0]),this.iE(),this._trigger("open"))}},$m:function(){var a=this.sC;a||(a=this.element.find("[autofocus]"));a.length||(a=this.element.find(":tabbable"));a.length||this.Wf&&(a=this.Wf.find(":tabbable"));
a.length||this.Ny&&(a=this.Ny.filter(":tabbable"));a.length||(a=this.Ja);a.eq(0).focus()},_keepFocus:function(a){a.preventDefault();a=this.document[0].activeElement;this.Ja[0]===a||f.contains(this.Ja[0],a)||this.$m()},KU:function(){this._on(this.widget(),{focusin:function(a){this.iE();this.sC=f(a.target)}})},iE:function(){this.PG();this.bx().unshift(this)},PG:function(){var a=this.bx(),b=f.inArray(this,a);-1!==b&&a.splice(b,1)},bx:function(){var a=this.document.data("ui-dialog-instances");a||(a=[],
this.document.data("ui-dialog-instances",a));return a},Bd:function(a){return!isNaN(parseInt(a,10))},hO:function(){this.element.uniqueId();this.pq=this.element.attr("id");this.px="ojDialogWrapper-"+this.pq;this.Ja=f("\x3cdiv\x3e").addClass("oj-dialog oj-component oj-dialog-front ").hide().attr({tabIndex:-1,role:this.options.role,id:this.px});this.Ja.insertBefore(this.element);this._on(this.Ja,{keyup:function(a){if("none"!=this.options.cancelBehavior&&!a.isDefaultPrevented()&&a.keyCode&&a.keyCode===
f.ui.keyCode.ESCAPE)a.preventDefault(),a.stopImmediatePropagation(),this.close(a);else if(a.keyCode===f.ui.keyCode.TAB){var b=this.Ja.find(":tabbable"),d=b.filter(":first"),b=b.filter(":last");a.target!==b[0]&&a.target!==this.Ja[0]||a.shiftKey?a.target!==d[0]&&a.target!==this.Ja[0]||!a.shiftKey||(b.focus(1),a.preventDefault()):(d.focus(1),a.preventDefault())}},mousedown:function(a){this.kw(a)&&this.$m()}});this.element.find("[aria-describedby]").length||this.Ja.attr({"aria-describedby":this.element.uniqueId().attr("id")})},
RB:function(){this.hk&&(this.hk.remove(),this.Ny=this.hk=null)},fq:function(a){this.hk=f("\x3cdiv\x3e").addClass("oj-dialog-header-close-wrapper").attr("tabindex","1").attr("aria-label","close").attr("role","button").appendTo(a);this.Ny=f("\x3cspan\x3e").addClass("oj-component-icon oj-clickable-icon oj-dialog-close-icon").attr("alt","close icon").prependTo(this.hk);this._on(this.hk,{click:function(a){a.preventDefault();a.stopImmediatePropagation();this.close(a)},mousedown:function(a){f(a.currentTarget).addClass("oj-active")},
mouseup:function(a){f(a.currentTarget).removeClass("oj-active")},mouseenter:function(a){f(a.currentTarget).addClass("oj-hover")},mouseleave:function(a){a=a.currentTarget;f(a).removeClass("oj-hover");f(a).removeClass("oj-active")},keyup:function(a){if(a.keyCode&&a.keyCode===f.ui.keyCode.SPACE||a.keyCode===f.ui.keyCode.ENTER)a.preventDefault(),a.stopImmediatePropagation(),this.close(a)}})},gO:function(){var a;this.Yl=f("\x3cdiv\x3e").addClass("oj-dialog-header oj-helper-clearfix").prependTo(this.Ja);
this._on(this.Yl,{mousedown:function(a){f(a.target).closest(".oj-dialog-close-icon")||this.Ja.focus()}});"icon"===this.options.cancelBehavior&&this.fq(this.Yl);a=f("\x3cspan\x3e").uniqueId().addClass("oj-dialog-title").appendTo(this.Yl);this.FG(a);this.Ja.attr({"aria-labelledby":a.attr("id")})},FG:function(a){this.options.title||a.html("\x26#160;");a.text(this.options.title)},hE:function(){function a(b){return{position:b.position,offset:b.offset}}var b=this,d=this.options;this.Ja.draggable({cancel:".oj-dialog-content, .oj-dialog-header-close",
handle:".oj-dialog-header",containment:"document",start:function(d,g){f(this).addClass("oj-dialog-dragging");b.ZA();b._trigger("dragStart",d,a(g))},drag:function(d,f){b._trigger("drag",d,a(f))},stop:function(e,g){d.position=[g.position.left-b.document.scrollLeft(),g.position.top-b.document.scrollTop()];f(this).removeClass("oj-dialog-dragging");b.NG();b._trigger("dragStop",e,a(g))}})},kE:function(){function a(b){return{originalPosition:b.Ri,originalSize:b.Sf,position:b.position,size:b.size}}var b=
this,d=this.Ja.css("position");this.Kj=this.Ja.ojResizable.bind(this.Ja);this.Kj({cancel:".oj-dialog-content",containment:"document",handles:"n,e,s,w,se,sw,ne,nw",start:function(d,g){f(this).addClass("oj-dialog-resizing");b.ZA();b._trigger("resizeStart",d,a(g))},resize:function(d,f){b._trigger("resize",d,a(f))},stop:function(d,g){f(this).removeClass("oj-dialog-resizing");b.NG();b._trigger("resizeStop",d,a(g))}}).css("position",d)},NE:function(){var c=this.Ja.is(":visible");c||this.Ja.show();var b=
this.options.position,d="rtl"===this.Ec();this.Ja.position(a.he.Jg(b,d));c||this.Ja.hide()},_setOption:function(a,b,d){var e;e=this.Ja;if("disabled"!==a)switch(this._super(a,b,d),a){case "dragAffordance":(a=e.is(":data(ui-draggable)"))&&"none"===b&&e.draggable("destroy");a||"title-bar"!==b||this.hE();break;case "position":this.NE();break;case "resizeBehavior":e=!1;this.Kj&&(e=!0);e&&"resizable"!=b&&(this.Kj("destroy"),this.Kj=null);e||"resizable"!==b||this.kE();break;case "title":this.FG(this.Yl.find(".oj-dialog-title"));
break;case "role":e.attr("role",b);break;case "modality":"modal"===b?this.zB():"modeless"===b&&this.TB();break;case "cancelBehavior":"none"===b||"escape"===b?this.RB():"icon"===b&&(this.Zl?(this.fq(this.Bh),this.co=this.Bh.find(".oj-dialog-title"),this.co.length&&this.co.insertAfter(this.hk)):this.fq(this.Yl))}},DT:function(){var a=this.jP();this.element.css({height:a})},jP:function(){this.wu=null;var a=(this.Zl?this.Bh:this.Yl).outerHeight(),b=0;this.Wf&&(b=this.Wf.outerHeight());return this.Ja.height()-
a-b},dS:function(){var a=f("\x3cdiv\x3e\x3c/div\x3e");this.JB=this.Ja.css("height");"auto"!=this.JB?(a.height(this.JB),this.Qm=a.height(),this.Bd(this.Qm)&&(this.Qm=Math.ceil(this.Qm))):this.Qm="auto";a.remove()},uU:function(){this.dS();var a=this.Ja[0].style.height,b=this.Ja[0].style.width,d=this.Ja[0].style.minHeight,e=this.Ja[0].style.maxHeight;this.element.css({width:"auto",minHeight:0,maxHeight:"none",height:0});var f;f=this.Ja.css({minHeight:0,maxHeight:"none",height:"auto"}).outerHeight();
this.element.css({width:"",minHeight:"",maxHeight:"",height:""});this.Ja.css({width:b});this.Ja.css({height:a});this.Ja.css({minHeight:d});this.Ja.css({maxHeight:e});"auto"!=a&&this.element.height(Math.max(0,this.Qm+2-f))},ZA:function(){this.Wx=this.document.find("iframe").map(function(){var a=f(this),b=a.offset();return f("\x3cdiv\x3e").css({position:"absolute",width:a.outerWidth(),height:a.outerHeight()}).appendTo(a.parent()).offset(b)[0]})},NG:function(){this.Wx&&(this.Wx.remove(),delete this.Wx)},
GM:function(a){return f(a.target).closest(".oj-dialog").length?!0:!!f(a.target).closest(".oj-datepicker").length},kT:function(){this.ME="ojDialogPlaceHolder-"+this.pq;this.JE=f("\x3cdiv\x3e").hide().attr({id:this.ME});this.JE.insertBefore(f("#"+this.px));this.Ja.attr(a.ba.dg,this.JE.attr("id"));this.Ja.appendTo(this.NM())},dO:function(a){this.KE="ojDialogPlaceHolderFooter-"+this.pq;this.CS=f("\x3cdiv\x3e").hide().attr({id:this.KE});this.CS.insertBefore(a)},eO:function(a){this.LE="ojDialogPlaceHolderHeader-"+
this.pq;this.DS=f("\x3cdiv\x3e").hide().attr({id:this.LE});this.DS.insertBefore(a)},ZX:function(){this.TI&&(this.TI.remove(),this.TI=null)},zB:function(){if("modeless"!==this.options.modality&&!this.Ol){var a=!0;this._delay(function(){a=!1});this.document.data("oj-dialog-overlays")||this._on(this.document,{focusin:function(b){a||this.GM(b)||(b.preventDefault(),this.bx()[0].$m())}});this.Ol=f("\x3cdiv\x3e").addClass("oj-component-overlay oj-dialog-front");var b=this.document.find("body").eq(0);this.Ol.insertBefore(b.find(".oj-dialog").eq(-0));
this._on(this.Ol,{mousedown:"_keepFocus"});this.document.data("oj-dialog-overlays",(this.document.data("oj-dialog-overlays")||0)+1)}},TB:function(){if(this.Ol){var a=this.document.data("oj-dialog-overlays")-1;a?this.document.data("oj-dialog-overlays",a):this.document.unbind("focusin").removeData("oj-dialog-overlays");this.Ol.remove();this.Ol=null}},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;a=a.subId;switch(a){case "oj-dialog":case "oj-dialog-header":case "oj-dialog-body":case "oj-dialog-footer":case "oj-dialog-content":case "oj-dialog-header-close-wrapper":case "oj-dialog-header-close-icon":case "oj-resizable-n":case "oj-resizable-e":case "oj-resizable-s":case "oj-resizable-w":case "oj-resizable-se":case "oj-resizable-sw":case "oj-resizable-ne":case "oj-resizable-nw":return a=
"."+a,this.widget().find(a)[0]}return null}})})()});
//# sourceMappingURL=oj-modular.map