"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojvalidation"],function(a,f){function c(a,b){this.AS=b;this.JT=a;this.sO="/"}a.ee=function(a){this.Init(a)};o_("AttributeGroupHandler",a.ee,a);a.b.sa(a.ee,a.b,"oj.AttributeGroupHandler");a.ee.prototype.Init=function(b){a.ee.t.Init.call(this);this.Bn=b?b:{};this.Jm={};this.Wr=0;this.mp=this.Jl();for(var c in this.Bn)b=this.mp.indexOf(this.Bn[c]),-1!==b&&this.mp.splice(b,1)};a.ee.prototype.Jl=function(){return[]};a.b.g("AttributeGroupHandler.prototype.getValueRamp",
{Jl:a.ee.prototype.Jl});a.ee.prototype.Bg=function(a){if(this.Bn[a])return this.Bn[a];this.Jm[a]||(this.Jm[a]=this.mp[this.Wr],this.Wr==this.mp.length-1?this.Wr=0:this.Wr++);return this.Jm[a]};a.b.g("AttributeGroupHandler.prototype.getValue",{Bg:a.ee.prototype.Bg});a.ee.prototype.OH=function(){var a=[],b;for(b in this.Jm)a.push({category:b,value:this.Jm[b]});return a};a.b.g("AttributeGroupHandler.prototype.getCategoryAssignments",{OH:a.ee.prototype.OH});a.ee.prototype.eH=function(a,b){this.Bn[a]=
b};a.b.g("AttributeGroupHandler.prototype.addMatchRule",{eH:a.ee.prototype.eH});var b={CSS_TEXT_PROPERTIES:function(a,c){var f={};a&&(a.hasClass("oj-gaugeMetricLabel")&&a.hasClass(a.parentNode,"oj-ledGauge")&&(f["font-size"]=!0,f.color=!0),a.hasClass(a,"oj-chartSliceLabel")&&(f.color=!0));return b.pE(a,c,!1,f)},CSS_BACKGROUND_PROPERTIES:function(a,c){return b.pE(a,c,!0,{})},CSS_URL:function(a){return b.zS(a)},Nz:"rgb(254, 0, 254)",Oz:"Times",MK:"1px",Qz:"1",Pz:"normal",GK:4,RV:function(a,b){return a.css(b)},
zS:function(a){return(a=a.css("background-image"))&&-1!==a.indexOf("url(")?a.slice(a.indexOf("url(")+4,a.length-1).replace(/"/g,""):a},cN:function(a){var b="";a.css("border-top-color")&&(b+="border-color: "+a.css("border-top-color")+";");a.css("border-width")&&a.css("border-style")&&"none"!=a.css("border-style")&&(b+="border-width: "+a.css("border-width")+";");a.css("background-color")&&(b+="background-color: "+a.css("background-color")+";");return b},hN:function(a,c){var f="",h=a.css("font-family");
h&&h!==b.Oz&&(f+="font-family: "+h.replace(/"/g,"'")+";");h=a.css("font-size");!h||-1<h.indexOf("px")&&parseFloat(h)<b.GK||c["font-size"]||(f+="font-size: "+h+";");(h=a.css("font-weight"))&&h!==b.Qz&&(f+="font-weight: "+h+";");(h=a.css("color"))&&h!==b.Nz&&!c.color&&(f+="color: "+h+";");(h=a.css("font-style"))&&h!==b.Pz&&(f+="font-style: "+h+";");return f},pE:function(a,b,c,f){f||(f={});if(!a)return b;var k;b&&((k=a.attr("style"))?a.attr("style",k+b):a.attr("style",b));b="";!0!==c&&(b+=this.hN(a,
f));!1!==c&&(b+=this.cN(a));k&&a.attr("style",k);return b},YW:function(a,c,g,h){var k=f(document.createElement("div"));k.attr("style","display:none;");a.append(k);a="";for(var l=0;l<g.length;l++)a=a+g[l]+" ";k.attr("class",a);g=f(document.createElement("div"));k.append(g);g.css("font-family",b.Oz);g.css("font-size",b.MK);g.css("color",b.Nz);g.css("font-weight",b.Qz);g.css("font-style",b.Pz);for(var m in h)k=f(document.createElement("div")),k.addClass(m),g.append(k),b.QS(c,k,h[m])},QS:function(a,c,
f){if(f instanceof Array)for(var h=0;h<f.length;h++)b.JF(a,c,f[h]);else b.JF(a,c,f)},JF:function(a,e,f){a=new c(a,f.path);var h;f.property&&(h=(h=b[f.property])?h(e,a.Bg()):b.RV(e,f.property));null==h||"string"==typeof h&&""==h.replace(/^\s+/g,"")||a.pX(h)}};a.Oa("oj.dvtBaseComponent",f.oj.baseComponent,{_ComponentCreate:function(){this._super();this.Aw=f(document.createElement("div"));this.Aw.attr("style","visibility:hidden;");this.element.append(this.Aw);this.kj=new DvtContext(this.element[0],null,
this.Aw[0]);this.kj.setReadingDirection(this.Ec());this.kj.setTooltipStyleClass("oj-dvt-tooltip");this.kj.setDatatipStyleClass("oj-dvt-datatip");f(document.body).hasClass("oj-hicontrast")&&DvtAgent.setHighContrast(!0);this.element.attr("tabIndex",0);this.Va=this.Cf(this.kj,this.cj,this);this.kj.getStage().addChild(this.Va);this.pA();this.WE();this.kt();this.hg();a.ba.ug(this.element[0],f.proxy(this.He,this))},refresh:function(){this._super();this.kj.setReadingDirection(this.Ec());this.WE();this.hg()},
getNodeBySubId:function(a){var b;this.Va&&this.Va.getAutomation&&(b=this.Va.getAutomation());return b?b.getDomElementForSubId(a.subId):null},getSubIdByNode:function(a){var b;this.Va&&this.Va.getAutomation&&(b=this.Va.getAutomation());return b?b.getSubIdForDomElement(a):null},pA:function(){for(var a=this.ef(),c=0;c<a.length;c++)this.element.addClass(a[c]);b.YW(this.element,this.options,this.ef(),this.aj())},ef:function(){return["oj-dvtbase"]},aj:function(){return{}},bj:function(){return[]},wm:function(){var b=
{"DvtUtilBundle.CLEAR_SELECTION":this.Gc("labelClearSelection"),"DvtUtilBundle.STATE_SELECTED":this.Gc("stateSelected"),"DvtUtilBundle.STATE_UNSELECTED":this.Gc("stateUnselected"),"DvtUtilBundle.STATE_MAXIMIZED":this.Gc("stateMaximized"),"DvtUtilBundle.STATE_MINIMIZED":this.Gc("stateMinimized"),"DvtUtilBundle.STATE_EXPANDED":this.Gc("stateExpanded"),"DvtUtilBundle.STATE_COLLAPSED":this.Gc("stateCollapsed"),"DvtUtilBundle.STATE_ISOLATED":this.Gc("stateIsolated"),"DvtUtilBundle.STATE_HIDDEN":this.Gc("stateHidden"),
"DvtUtilBundle.STATE_VISIBLE":this.Gc("stateVisible"),"DvtUtilBundle.SCALING_SUFFIX_THOUSAND":this.Gc("labelScalingSuffixThousand"),"DvtUtilBundle.SCALING_SUFFIX_MILLION":this.Gc("labelScalingSuffixMillion"),"DvtUtilBundle.SCALING_SUFFIX_BILLION":this.Gc("labelScalingSuffixBillion"),"DvtUtilBundle.SCALING_SUFFIX_TRILLION":this.Gc("labelScalingSuffixTrillion"),"DvtUtilBundle.SCALING_SUFFIX_QUADRILLION":this.Gc("labelScalingSuffixQuadrillion")},c=a.Ga.os("abbreviated");b["DvtUtilBundle.MONTH_SHORT_JANUARY"]=
c[0];b["DvtUtilBundle.MONTH_SHORT_FEBRUARY"]=c[1];b["DvtUtilBundle.MONTH_SHORT_MARCH"]=c[2];b["DvtUtilBundle.MONTH_SHORT_APRIL"]=c[3];b["DvtUtilBundle.MONTH_SHORT_MAY"]=c[4];b["DvtUtilBundle.MONTH_SHORT_JUNE"]=c[5];b["DvtUtilBundle.MONTH_SHORT_JULY"]=c[6];b["DvtUtilBundle.MONTH_SHORT_AUGUST"]=c[7];b["DvtUtilBundle.MONTH_SHORT_SEPTEMBER"]=c[8];b["DvtUtilBundle.MONTH_SHORT_OCTOBER"]=c[9];b["DvtUtilBundle.MONTH_SHORT_NOVEMBER"]=c[10];b["DvtUtilBundle.MONTH_SHORT_DECEMBER"]=c[11];return b},pc:function(b,
c){var f=this.Gc(b);if(c){for(var h={},k=0;k<c.length;k++)h[c[k]]="{"+k+"}";f=a.ea.ub(f,h)}return f},WE:function(){var a=this.wm();DvtBundle.addLocalizedStrings(a)},_destroy:function(){this.Va.destroy&&this.Va.destroy();a.ba.Ti(this.element[0],f.proxy(this.He,this));this.element.children().remove();this.element.removeAttr("role").removeAttr("tabIndex");for(var b=this.ef(),c=0;c<b.length;c++)this.element.removeClass(b[c]);this._super()},_setOptions:function(a){this._superApply(arguments);if(!this.Jt){var b=
!1,c=this.bj();f.each(a,function(a){if(0>c.indexOf(a))return b=!0,!1});b&&this.hg()}},_setOption:function(b,c){var f=this.xk(b),h=this.options[b],k=this._superApply(arguments);f&&(f=this.options[b],a.b.ej(h,f)||this._trigger("optionChange",null,{option:b,previousValue:h,value:f,optionMetadata:{writeback:this.Jt?"shouldWrite":"shouldNotWrite"}}));return k},Cf:function(){return null},cj:function(){},He:function(){var a=this.element.width(),b=this.element.height();5<=Math.abs(a-this.nx)+Math.abs(b-this.Mv)&&
(this.Va.render(null,a,b),this.nx=a,this.Mv=b)},kt:function(){},hg:function(){this.kj.isReadyToRender()?(this.nx=this.element.width(),this.Mv=this.element.height(),this.Va.render(this.options,this.nx,this.Mv)):a.D.error(this.Gc("notReadyToRender").summary)},xk:function(){return!1},$g:function(a,b){this.Jt=!0;this.option(a,b);this.Jt=!1}});a.lm=function(a){this.Init(a)};o_("ShapeAttributeGroupHandler",a.lm,a);a.b.sa(a.lm,a.ee,"oj.ShapeAttributeGroupHandler");a.lm.Km="square circle diamond plus triangleDown triangleUp human".split(" ");
a.lm.prototype.Jl=function(){return a.lm.Km.slice()};a.Rg=function(b){this.Km=[];if(f(document.body).hasClass("oj-hicontrast"))this.Km=a.Rg.qO.slice();else{var c=f(document.createElement("div"));c.attr("style","display:none;");c.attr("id","attrGps");f(document.body).append(c);for(var g=0;g<a.Rg.zG.length;g++){var h=f(document.createElement("div"));h.addClass(a.Rg.zG[g]);c.append(h);this.Km.push(h.css("color"))}c.remove()}this.Init(b)};o_("ColorAttributeGroupHandler",a.Rg,a);a.b.sa(a.Rg,a.ee,"oj.ColorAttributeGroupHandler");
a.Rg.zG="oj-dvt-category1 oj-dvt-category2 oj-dvt-category3 oj-dvt-category4 oj-dvt-category5 oj-dvt-category6 oj-dvt-category7 oj-dvt-category8 oj-dvt-category9 oj-dvt-category10 oj-dvt-category11 oj-dvt-category12".split(" ");a.Rg.qO="#267db3 #68c182 #fad55c #ed6647 #8561c8 #6ddbdb #ffb54d #e371b2 #47bdef #a2bf39 #a75dba #f7f37b".split(" ");a.Rg.prototype.Jl=function(){return this.Km.slice()};c.prototype.FT=function(a,b,c,f){for(var k={};a&&-1<b.indexOf(c);){var l=b.substring(0,b.indexOf(c));f&&
void 0===a[l]&&(a[l]={});a=a[l];b=b.substring(b.indexOf(c)+1,b.length)}a&&(k.object=a,k.parameter=b);return k};c.prototype.IF=function(a){void 0===this.zn&&(a=this.FT(this.JT,this.AS,this.sO,a),this.zn=a.object,this.rw=a.parameter)};c.prototype.Bg=function(){this.IF(!1);return void 0===this.zn?void 0:this.zn[this.rw]};c.prototype.pX=function(a){this.IF(!0);this.zn[this.rw]!==a&&(this.zn[this.rw]=a)}});
//# sourceMappingURL=oj-modular.map