"use strict";
/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojvalidation","ojs/ojpopup"],function(a,f){a.la=function(a){this.Init(a)};a.Xa.uy(a.Xa.bd.jp,a.la);a.b.sa(a.la,a.Sb,"oj.PopupMessagingStrategy");a.la.$i={ojRadioset:{position:"launcher",Di:{open:"focusin mouseover",close:"mouseout"}},ojCheckboxset:{position:"launcher",Di:{open:"focusin mouseover",close:"mouseout"}},"default":{Di:{open:"focusin"}}};a.la.vK="oj-component-icon oj-message-status-icon ";a.la.SL="oj-message";a.la.YL="oj-message-summary";
a.la.WL="oj-message-detail";a.la.VL="oj-message-content";a.la.NL="oj-form-control-hint";a.la.PL="oj-form-control-hint-converter";a.la.RL="oj-form-control-hint-validator";a.la.QL="oj-form-control-hint-title";a.la.rA="oj-message-error-icon";a.la.ZL="oj-message-warning-icon";a.la.XL="oj-message-info-icon";a.la.TL="oj-message-confirmation-icon";a.la.prototype.wi=function(b){a.la.t.wi.call(this,b);this.mR()};a.la.prototype.Wo=function(b){a.la.t.Wo.call(this,b);this.VG()};a.la.prototype.update=function(){a.la.t.update.call(this);
this.VG()};a.la.prototype.zg=function(){var b=a.la.$i[this.Ze().widgetName],b=b?b.Di:a.la.$i["default"].Di;b.open&&(this.fe().off(b.open,this.CE),this.fe().off(b.open,this.ox));b.close&&this.fe().off(b.close,this.vB);this.yO();a.la.t.zg.call(this)};a.la.prototype.vB=function(a){a=a.data&&a.data.strategy;a.Ld.ojPopup("close",a.fe())};a.la.prototype.mR=function(){var b=this.fe(),c=a.la.$i[this.Ze().widgetName],c=c?c.Di:a.la.$i["default"].Di;if(!this.wn())b.on(c.open,{strategy:this},this.ox)};a.la.prototype.CE=
function(a){(a.data&&a.data.strategy).Du()};a.la.prototype.Du=function(){var b,c;this.pN()&&(c=this.aB(),this.wn()&&c&&(b=this.Ld[0],b.innerHTML="",b.innerHTML=c,b=this.fe(),c=b.is("[id]")?b.attr("id"):b.uniqueId().attr("id"),this.Ld.ojPopup("widget").attr(a.ba.dg,c),this.Ld.ojPopup("open",b)))};a.la.prototype.pN=function(){var a=this.Ze().options,b=a.readOnly||!1;return!(a.disabled||b)};a.la.prototype.VG=function(){var a;a=!1;var b,c;this.wn()&&(a=this.Ld.ojPopup("isOpen"),b=this.aB(),c=document.activeElement===
this.fe()[0]?!0:!1,a?b?(a=this.Ld[0],a.innerHTML="",a.innerHTML=b,this.Ld.ojPopup("refresh")):this.Ld.ojPopup("close",this.fe()):c&&b&&this.Du())};a.la.prototype.ox=function(b){b=b.data&&b.data.strategy;if(!b.wn()){var c=b.fe(),d=b.WP(),e=a.la.$i[b.Ze().widgetName],e=e?e.Di:a.la.$i["default"].Di;b.Ze().widget();b.Ld=f("\x3cdiv class\x3d'oj-messaging-popup-container'\x3e\x3c/div\x3e");f("body").append(b.Ld);b.Ld.ojPopup({rootAttributes:{"class":"oj-messaging-popup"},initialFocus:"none",tail:"simple",
autoDismiss:"focusLoss",position:{my:"start bottom",at:"end top",collision:"flip",of:d}});d={strategy:b};if(e.open)c.on(e.open,d,b.CE);if(e.close)c.on(e.close,d,b.vB);b.fe().off(e.open,b.ox);b.Du()}};a.la.prototype.WP=function(){var b=a.la.$i[this.Ze().widgetName];return b&&b.position&&"launcher"===b.position?this.fe():this.Ze().widget()};a.la.prototype.yO=function(){this.wn()&&this.Ld&&(this.Ld.ojPopup("destroy"),this.Ld.remove())};a.la.prototype.aB=function(){var a="",b=this.Ze().document[0],c=
[],d=!1,e=this;this.fK()&&c.push(this.fN(b));(this.Vs()||this.kz()||this.jz())&&c.push(this.dN(b));f.each(c,function(c,g){g&&(d?a=a.concat(e.cQ(b)):d=!0,a=a.concat(g))});return a};a.la.prototype.fN=function(b){var c,d="",e,g,f,h,k;g=this.Zy();var s={};c=[];if(this.az()){c=this.$y();for(e=0;e<c.length;e++)k=c[e],k=k instanceof a.U?k:new a.U(k.summary,k.detail,k.severity),h=a.U.Gl(k.severity),s[h]||(s[h]=[]),s[h].push(k);for(e=g;e>=a.U.Mb.CONFIRMATION;e--)for(c=s[e]||[],g=0;g<c.length;g++)k=c[g],a.i.mb(k,
a.U),h=a.U.Gl(k.severity),f=this.aD(h),f=k.summary||f,k=k.detail||"",d=d.concat(this.eN(b,f,k,h))}return d};a.la.prototype.eN=function(b,c,d,e){var g,h,p=this.aD(e);g=f(b.createElement("div"));g.addClass(a.la.SL);h=f(b.createElement("span"));h.addClass(this.dQ(e)).attr("title",p).attr("role","img");g.append(h);e=f(b.createElement("span"));e.addClass(a.la.VL);h=f(b.createElement("div"));h.addClass(a.la.YL).text(c);e.append(h);d&&(d=this.gD(b,d,!0),b=f(b.createElement("div")),b.addClass(a.la.WL).append(d),
e.append(b));g.append(e);return g?g.get(0).outerHTML:""};a.la.prototype.dN=function(b){var c=[],d,e="";this.Vs()&&(c=this.Yy(),c=c.length?c[0]:"",e+=this.Nt(b,a.la.PL,c));if(this.kz())for(c=this.PJ(),d=0;d<c.length;d++)e+=this.Nt(b,a.la.RL,c[d]);this.jz()&&(e+=this.Nt(b,a.la.QL,this.OJ(),!0));return e?"\x3cdiv class\x3d'oj-form-control-hints'\x3e"+e+"\x3c/div\x3e":""};a.la.prototype.Nt=function(b,c,d,e){var g,h=a.la.NL;d&&(g=f(b.createElement("div")),g.addClass(h+(" "+c)),g.append(this.gD(b,d,e)));
return g?g.get(0).outerHTML:""};a.la.prototype.gD=function(b,c,d){var e=null;d&&a.ba.HW(c)?e=a.ba.AV(c.substring(6,c.length-7)):a.fb.pd(c)&&(e=b.createElement("span"),e.textContent=c);return e};a.la.prototype.cQ=function(a){return(a=f(a.createElement("hr")))?a.get(0).outerHTML:""};a.la.prototype.aD=function(b){var c;switch(b){case a.U.Mb.FATAL:c=a.ea.O("oj-message.fatal");break;case a.U.Mb.ERROR:c=a.ea.O("oj-message.error");break;case a.U.Mb.WARNING:c=a.ea.O("oj-message.warning");break;case a.U.Mb.INFO:c=
a.ea.O("oj-message.info");break;case a.U.Mb.CONFIRMATION:c=a.ea.O("oj-message.confirmation")}return c};a.la.prototype.dQ=function(b){var c;switch(b){case a.U.Mb.FATAL:c=a.la.rA;break;case a.U.Mb.ERROR:c=a.la.rA;break;case a.U.Mb.WARNING:c=a.la.ZL;break;case a.U.Mb.INFO:c=a.la.XL;break;case a.U.Mb.CONFIRMATION:c=a.la.TL}return a.la.vK+c};a.la.prototype.wn=function(){return this.Ld?this.Ld.is(":oj-popup"):!1};var c={EJ:1,Sy:2,Uy:3,ez:4,fz:5,gz:6,aK:7,hK:8,nz:9,oz:10,jK:11},b={Bl:!0,zf:c.Sy},d={Bl:!0,
zf:c.Uy},e={Bl:!0,zf:c.gz},g={Bl:!0,zf:c.ez},h={Bl:!0,zf:c.fz},k={Bl:!0,zf:c.oz};a.Oa("oj.editableValue",f.oj.baseComponent,{widgetEventPrefix:"oj",options:{disabled:!1,displayOptions:void 0,help:{definition:void 0,source:void 0},messagesCustom:void 0,messagesHidden:void 0,messagesShown:void 0,required:void 0,title:void 0,validators:void 0,value:void 0,optionChange:void 0},getNodeBySubId:function(a){return this._super(a)},isValid:function(){return void 0===this.kx?!0:this.kx},refresh:function(){this._super();
this.aC(!0)},reset:function(){this.Zp();this.Vn(this.Gf.aK);this.Dw(this.options.value,!0)},showMessages:function(){var b=this.options.messagesHidden,c,d=!1,e,g=[];for(e=0;e<b.length;e++)d=!0,c=b[e],c instanceof a.Rb&&c.dP(),g.push(c.clone());d&&(this.iu(),this.jx(g))},validate:function(){return this.ie(this.Yg(),null,this.At)},Bm:{Wy:1,iK:2,hz:3},Gf:c,At:{oo:!1,zf:c.nz},_InitOptions:function(a,b){this._super(a,b);this.qr=[]},_ComponentCreate:function(){var a=this.element,b=this.gt(a);this._super();
this.options.messagesCustom=this.options.messagesCustom||[];this.options.messagesHidden=[];this.options.messagesShown=0<this.options.messagesCustom.length?this.BN(this.options.messagesCustom):[];"boolean"===typeof this.options.disabled&&a.prop("disabled",this.options.disabled);this.Mz()&&(this._SetPlaceholder(this.options.placeholder),this.uu=!0);f.each(["required","title"],function(c,d){d in b&&a.removeAttr(d)})},Rh:function(){this._super();this.TN();this.aC(!1);this.Wq();this.OM();this.KT();this.widget().addClass("oj-form-control")},
sz:function(a,b,c){switch(a){case "disabled":this.tz(a,d);break;case "converter":this.kK(a);break;case "displayOptions":this.Wq();break;case "help":this.Ff(a,this.options[a]);break;case "messagesCustom":this.fS(b,c);break;case "placeholder":this.ES(c);break;case "readOnly":this.tz(a,g);break;case "required":this.lK(a);break;case "title":this.FU();break;case "translations":this.refresh();break;case "value":this.mK(a,b,c);break;case "validators":this.pk(a)}},kK:function(a){var c=!1;this.JL();this.Tq()&&
(c=!0);c?(this.$p(),this.Vr(b)):this.Ff(a,this.options[a],!0)},tz:function(a,b){var c=!this.options[a];this.Ff(a,this.options[a]);c&&this.MF(b)},lK:function(a){this.Ff(a,this.options[a]);this.MF(e)},mK:function(a,b,c){var d=!1,e;this.bV(b,c);c&&(d=c._oj_originalEvent?!0:!1,e=c._oj_doNotClearMessages||!1);d||(e||this.Zp(null),this.Vn(this.Gf.jK));this.Ff(a,this.options[a],!0)},pk:function(){var a=!1;this.ut();this.Tq()&&(a=!0);a&&(this.$p(),this.Vr(k))},ct:function(){var a=this.options.readOnly||!1;
return this.options.disabled||a?!1:!0},_destroy:function(){this.widget();this.Zp(null,!0);this.Lk().zg();this.Qb&&this.Qb._ojLabel("destroy");this.vk();return this._super()},Focus:function(){this.Ae().focus();return!0},_setOption:function(b,c,d){var e,g;e=!1;if("string"===typeof b&&void 0!==c)switch(b){case "messagesCustom":g=this.options.messagesCustom||[];break;case "messagesHidden":e=!0;break;case "messagesShown":e=!0;break;case "value":g=this.options.value}if(e)return a.D.error(b+" option cannot be set"),
this;e=this._superApply(arguments);this.sz(b,g,d);return e},Ae:function(){return this.element},IK:function(){var a=this.tC(this.element);if(null!==a&&0!==a.length)return a;a=this.element.prop("id");if(void 0!==a&&(a=f("label[for\x3d'"+a+"']"),0!==a.length))return a;a=this.element.closest("[aria-labelledby]");return 0!==a.length&&(a=this.tC(a),null!==a&&0!==a.length)?a:null},sk:function(){return this.element.val()},_GetMessagingLauncherElement:function(){return this.Ae()},nc:function(){this.Ub||(this.Ub=
a.IntlConverterUtils.getConverterInstance(this.options.converter));return this.Ub||null},vm:function(){this.xD||(this.xD={});return this.xD},Yg:function(){return this.Ae().val()},Jz:function(){if(!this.Hm){var b=[],c=this.options.validators,d,e=!0,g=this.vm(),f=[],h,k;k=Object.keys(g);if(0<k.length){for(h in k)d=k[h],f.push(g[d]);b=b.concat(f)}if(c){f=[];for(k=0;k<c.length;k++)d=c[k],"object"===typeof d?(d.validate&&"function"===typeof d.validate||(e=!1),e||(h=d.type)&&"string"===typeof h&&((g=a.ca.Xf(h))?
(d=a.ec.Ne({},d.options)||{},d.converter=d.converter||this.nc(),d.label=d.label||this.ev(),d=g.createValidator(d)):a.D.error("Unable to locate a validatorFactory for the requested type: "+h)),f.push(d)):a.D.error("Unable to parse the validator provided:"+d);b=b.concat(f)}this.Hm=b}return this.Hm||[]},ut:function(){this.Hm&&(this.Hm.length=0);this.Hm=null;this.Lk().update(this.ff(this.Be.pz))},JL:function(){this.Ub=null;this.Lk().update(this.ff(this.Be.Ry))},ht:function(a,b){this.qr.push({option:a,
previousValue:b})},xm:function(){return this.options.required},rp:function(a){var b=this.Yg();this.ie(b,a)},Ff:function(a,b,c){switch(a){case "converter":b=this.options.value;this.Dw(b,c);break;case "disabled":this.mF("disabled",this.options.disabled);break;case "help":a=this.options.help.definition;b=this.options.help.source;c=this.WA(b);this.Qb&&(this.Qb._ojLabel("option","describedById",c),this.Qb._ojLabel("option","help",{definition:a,source:b}));break;case "required":this.mF("required",this.xm());
this.tt(b);this.Qb&&this.Qb._ojLabel("option","required",b);break;case "value":this.Dw(b,c)}},tt:function(a){var b=this.Ae();a&&b?b.attr("aria-required",a):b.removeAttr("aria-required")},qA:function(){this.Ub=this.Qv=null;this.ut()},ig:function(a){this.Ae().val(a)},_SetPlaceholder:function(a){this.Ae().attr("placeholder",a)},tA:function(a){this.options.placeholder=a},Mz:function(){return this.options.placeholder},Ez:function(){this.tA("");this._SetPlaceholder("")},ie:function(b,c,d){var e=d&&"boolean"===
typeof d.oo?d.oo:!0;if(void 0===b)return a.D.warn("Attempt to set a value of undefined"),!1;if(e&&b===this.xE)a.D.Po>a.D.Qh&&a.D.info("Validation skipped and value option not updated as submitted value '"+b.toString?b.toString():b+" same as previous.");else if(b=this.CA(b,c,d),void 0!==b&&this.isValid())return this.XG(b,c,d&&d.zf),!0;return!1},CA:function(b,c,d){var e=d&&d.GX?d.GX:this.Bm.Wy,g=d&&d.zf?d.zf:this.Gf.hK;d=d&&d.Bl||!1;if(void 0===b)a.D.warn("Attempt to set a value of undefined");else if(this.ct()){d||
this.Zp(c);this.cG(b);try{return this.LT(b,e,g,c)}catch(f){}}else a.D.Po>a.D.Qh&&a.D.info("Validation skipped and value option not set as component state does not  allow setting value. For example if the component is readonly or disabled.")},zt:function(b,c,d,e){a.i.iH(b,"");d=d?{writeback:"shouldWrite"}:{writeback:"shouldNotWrite"};c={option:b,component:a.Components.rs(this.element),previousValue:c,value:this.options[b],optionMetadata:d};switch(b){case "messagesShown":case "messagesHidden":case "messagesCustom":this._trigger("optionChange",
e||null,c);break;case "value":this._trigger("optionChange",e||null,c)}},DA:function(b,c){return a.b.xg(b,c)},_GetDefaultStyleClass:function(){a.i.fa();return""},Be:{dm:1,qz:2,Ry:3,pz:4,mz:5},Th:{disabled:"oj-disabled",required:"oj-required"},OM:function(){var a,b;for(a=0;a<this.qr.length;a++)b=this.qr[a],this.zt(b.option,b.previousValue,!0);this.qr=null},Zp:function(a,b){b?(this.options.messagesHidden=[],this.options.messagesShown=[],this.options.messagesCustom=[]):(this.iu(a),this.xN(a),this.wN(a))},
$p:function(){var b=this.options.messagesShown,c=b.length,d,e={};this.iu();for(var g=c-1;0<=g;g--)d=b[g],d instanceof a.Rb&&b.splice(g,1);e.changed=this.options.messagesShown.length!==c?!0:!1;this.Fn("messagesShown",this.options.messagesShown,e)},iu:function(a){var b={};b.changed=0<this.options.messagesHidden.length?!0:!1;a&&(b._oj_originalEvent=a);this.options.messagesHidden=[];this.qE(this.options.messagesHidden,b)},xN:function(a){var b={};b.changed=0<this.options.messagesShown.length?!0:!1;a&&
(b._oj_originalEvent=a);this.options.messagesShown=[];this.iw(this.options.messagesShown,b)},wN:function(a){var b={},c={};c.changed=0<this.options.messagesCustom.length?!0:!1;b.messagesCustom=[];a&&(c._oj_originalEvent=a);this.option(b,c)},BN:function(b){var c,d=[],e;if(b&&0<b.length)for(e=0;e<b.length;e++)c=b[e],c instanceof a.U?d.push(c.clone()):(c=new a.U(c.summary,c.detail,c.severity),c=Object.freeze?Object.freeze(c):c,d.push(c));return d},TN:function(){if(this.Qb=this.IK()){var a=this.options.help.definition,
b=this.options.help.source,c=this.WA(b);this.Qb._ojLabel({rootAttributes:{"class":this._GetDefaultStyleClass()+"-label"},describedById:c,required:this.options.required,help:{definition:a,source:b}})}},aC:function(a){var b=!1;a?(this.Qb&&this.Qb._ojLabel("refresh"),this.qA(),this.Wq(),this.Tq()&&(b=!0),this.$p(),b?this.Vr(h):(this.xm()&&this.Vn(h.zf),this.Ff("value",this.options.value,!0))):(this.Ff("value",this.options.value),this.Ff("required",this.options.required));this.Ff("disabled",this.options.disabled)},
hY:function(){return this.yE},gY:function(){return this.xE},tC:function(a){a=a.attr("aria-labelledby");return void 0!==a?f("label[id\x3d'"+a+"']"):null},WA:function(a){this.element.uniqueId();var b=this.element.prop("id")+"Icons";a&&this.Ae().each(function(){var a=f(this).attr("aria-describedby");a?f(this).attr("aria-describedby",a+" "+b):f(this).attr("aria-describedby",b)});return b},Hq:function(){return this.options.messagesShown.concat(this.options.messagesHidden)},ev:function(){if(this.Qb)return this.Qb.text()},
lD:function(){this.aH||(this.aH=new a.Bf(this.isValid(),this.Hq()));return this.aH},Sq:function(){return!a.U.isValid(this.Hq())},Tq:function(){return!this.isValid()&&0<this.options.messagesShown.length},aR:function(){for(var b=this.options.messagesShown,c,d,e=0;e<b.length;e++)c=b[e],c instanceof a.Rb&&c.TD()&&(d=d||[],d.push(c));return void 0===d?!1:!a.U.isValid(d)},Wq:function(){var a=this.Lk(),b=this._GetMessagingLauncherElement(),c=this.ff(this.Be.dm);this.uu||this.Ez();a.wi(b,c)},qE:function(a,
b){this.Fn("messagesHidden",a,b)},iw:function(a,b){this.Fn("messagesShown",a,b)},fS:function(b,c){var d=this.options.messagesCustom,e=this.options.messagesShown,g,f=[],h;for(h=0;h<e.length;h++)g=e[h],g instanceof a.Rb&&g.TD()&&f.push(g);this.options.messagesShown=f;for(h=0;h<d.length;h++)this.options.messagesShown.push(d[h]);this.Fn("messagesCustom",b,c);this.Fn("messagesShown",e,c)},Fn:function(a,b,c){var d=!1,e=this.options[a],g;c&&(d=c.changed||!1,g=c._oj_originalEvent||null);this.XU();this.Lk().update(this.ff());
!d&&this.gS(b,e)||this.zt(a,b,!1,g)},ES:function(a){a=a&&a._oj_messaging_update?!1:!0;this._SetPlaceholder(this.options.placeholder);a?(this.uu=!0,this.Wq()):this.uu=!1},dU:function(a){this.yE=a},cG:function(a){this.xE=a},FU:function(){this.Lk().update(this.ff(this.Be.mz))},UU:function(b,c){var d={},e,g;a.i.mb(b,a.U);if("object"===typeof b&&Array.isArray(b))for(d.changed=!0,e=b.length,g=0;g<e;g++)this.options.messagesHidden.push(b[g]);c&&(d._oj_originalEvent=c);this.qE(this.options.messagesHidden,
d)},jx:function(b,c){var d={},e,g;a.i.mb(b,a.U);if("object"===typeof b&&Array.isArray(b))for(d.changed=!0,e=b.length,g=0;g<e;g++)this.options.messagesShown.push(b[g]);c&&(d._oj_originalEvent=c);this.iw(this.options.messagesShown,d)},XG:function(a,b,c){var d={},e={},g=!1;d.value=a;b&&(e._oj_originalEvent=b);switch(c){case this.Gf.Sy:case this.Gf.Uy:case this.Gf.ez:case this.Gf.fz:case this.Gf.gz:case this.Gf.nz:case this.Gf.oz:g=!0,e._oj_doNotClearMessages=!0}e.shouldWriteback=g;this.option(d,e)},
XU:function(){var a=this.Hq(),a=a&&0!==a.length;this.kx=!0;a&&(this.kx=!this.Sq())},bV:function(a,b){var c=this.options.value,d=!1,e=!1,g;b&&(d=b.changed||!1,g=b._oj_originalEvent||null,e=b.shouldWriteback||g?!0:!1);!d&&this.DA(a,c)||this.zt("value",a,e,g)},fP:function(b){var c=b,d=this.nc();d&&"object"===typeof d&&(d.format&&"function"===typeof d.format?c=d.format(b):a.D.Po>a.D.Qh&&a.D.info("converter does not support the format method."));return c},Lk:function(){this.jj||(this.jj=new a.Xa(this));
return this.jj},DP:function(a){var b,c=[];b="";var d;this.xm()&&(b=this.IC(),b.getHint&&"function"===typeof b.getHint&&(b=b.getHint())&&c.push(b));for(d=0;d<a.length;d++)b=a[d],"object"===typeof b&&b.getHint&&"function"===typeof b.getHint&&(b=b.getHint())&&c.push(b);return c},IC:function(){var b;b={};var c;null==this.Qv&&(b=this.options.translations?this.options.translations.required||{}:{},c={hint:b.hint||null,label:this.ev(),messageSummary:b.messageSummary||null,messageDetail:b.messageDetail||null},
this.Qv=(b=a.ca.Xf(a.Tb.VALIDATOR_TYPE_REQUIRED))?b.createValidator(c):null);return this.Qv},ff:function(a){var b={},c=this.nc(),d=[];a=a||this.Be.qz;if(a===this.Be.dm||a===this.Be.qz)d=this.Hq(),this.lD().update(this.isValid(),d),b.validityState=this.lD();(a===this.Be.dm||a===this.Be.Ry)&&c&&"object"===typeof c&&c.getHint&&"function"===typeof c.getHint&&(c=c.getHint()||"",b.converterHint=c);if(a===this.Be.dm||a===this.Be.pz)c=this.Jz(),d=this.DP(c)||[],b.validatorHint=d;if(a===this.Be.dm||a===this.Be.mz)b.title=
this.options.title||"";return b},gS:function(b,c){var d=-1,e,g=!0,h=f.extend([],b),p=f.extend([],c);if(h===p)return!0;if(null==h||null==p||h.length!==p.length)return!1;f.each(h,function(b,c){c instanceof a.U?e=c:(e=new a.U(c.summary,c.detail,c.severity),e=Object.freeze?Object.freeze(e):e);d=-1;f.each(p,function(a,b){e.Ci(b)&&(d=a)});-1<d?p.splice(d,1):g=!1});return g},IE:function(b){var c=this.nc(),d=b;c&&"object"===typeof c&&(c.parse&&"function"===typeof c.parse?d=c.parse(b):a.D.Po>a.D.Qh&&a.D.info("converter does not support the parse method."));
return d},Et:function(b,c){var d,e,g;b instanceof a.rd||b instanceof a.ze?(d=b.Fl(),a.i.mb(d,a.U),g=d.severity,e=d.summary,d=d.detail):(g=a.U.Mb.ERROR,e=a.ea.O("oj-message.error"),d=b.message||a.ea.O("oj-converter.detail"));c.push({summary:e,detail:d,severity:g})},ww:function(b,c,d){var e={},g=[],f=b.En||[];e.context=c||0;e.display=d||a.Rb.lk.Ss;0===f.length&&this.Et(b,f);for(c=0;c<f.length;c++)b=f[c],g.push(this.ON(b.summary,b.detail,b.severity,e));return g||null},ON:function(b,c,d,e){b=new a.Rb(b,
c,d,e);return b=Object.seal?Object.seal(b):b},Dw:function(a,b){var c=a||this.options.value,d;d=this.yE;(b||c!==d)&&this.SU(c)},mF:function(a,b){-1!=Object.keys(this.Th).indexOf(a)&&this.widget().toggleClass(this.Th[a],!!b)},Vn:function(b){if(this.ct())try{this.$G(this.options.value,this.Bm.hz)}catch(c){(b=this.ww(c,b,a.Rb.lk.Qs))&&this.UU(b)}else a.D.Po>a.D.Qh&&a.D.info("Deferred validation skipped as component is readonly or disabled.")},KT:function(){this.Vn(this.Gf.EJ);0<this.options.messagesShown.length&&
this.iw([],{changed:!0})},LT:function(a,b,c,d){var e=a;try{b===this.Bm.Wy&&(e=this.IE(a)),this.$G(e,b===this.Bm.hz)}catch(g){throw a=this.ww(g,c),this.jx(a,d),g;}return e},MF:function(a){var b=!0;this.Tq()&&(b=!1);this.$p();b?this.xm()&&this.Vn(a.zf):this.Vr(a)},SU:function(a,b){var c,d;this.dU(a);c=a;try{c=this.fP(a)}catch(e){d=this.ww(e),this.jx(d,b)}this.ig(c);this.cG(this.Yg())},Vr:function(a){var b;b=this.CA(this.Yg(),null,a);void 0===b||!this.isValid()&&this.aR()||this.XG(b,null,a.zf)},$G:function(b,
c){var d=this.Jz(),e,g,f=[];if(this.xm()){e=this.IC();try{e.validate(a.fb.trim(b))}catch(h){this.Et(h,f)}}if(!c)for(g=0;g<d.length;g++)if(e=d[g],"object"===typeof e)if(e.validate&&"function"===typeof e.validate)try{e.validate(b)}catch(k){this.Et(k,f)}else a.D.Po>a.D.Qh&&a.D.info("validator does not support the validate method.");if(0<f.length)throw d=Error(),d.En=f,d;}});a.Components.Cy({editableValue:{displayOptions:a.Components.Uj(function(){return{messages:["notewindow"],converterHint:["placeholder",
"notewindow"],validatorHint:["notewindow"],title:["notewindow"]}})}});a.Oa("oj._ojLabel",f.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3clabel\x3e",widgetEventPrefix:"oj",options:{describedById:null,help:{definition:void 0,source:void 0},required:null,rootAttributes:void 0},cb:{mM:"tooltipHelp",oM:"tooltipRequired"},widget:function(){return this.Og},refresh:function(){this._super();this.fF();this.cF()},_InitOptions:function(a,b){this._super(a,b);this.bu()},_ComponentCreate:function(){this._super();
this.JO()},JO:function(){var a=this.options.help.source||this.options.required,b=null;this.Og=this.element.wrap(this.NU()).closest(".oj-component");this.pS();a&&(b=this.pu());if(this.options.help.definition||this.options.help.source)this.HD(b),this.HA();this.options.required&&b.append(this.CF())},bu:function(){if((this.options.help.source||this.options.required)&&null==this.options.describedById)throw Error("ojLabel's describedById option must be set if required or help source is set.");},pS:function(){var a=
this.element.attr("class"),b;if(a&&(a=a.split(/\s+/),null!=a)){b=a.length;for(var c=0;c<b;c++){var d=a[c];0<d.indexOf("-label")&&(this.Og.addClass(d),this.element.removeClass(d))}}},pu:function(){var a=this.Og.find(".oj-label-group"),b=f("\x3cspan\x3e\x3c/span\x3e",this.document[0]);b.attr("id",this.options.describedById);return a.prepend(b).children().first()},NU:function(){var a;this.options.rootAttributes&&(a=this.options.rootAttributes["class"]);return null!==a?"\x3cdiv class\x3d'oj-label oj-component "+
a+"'\x3e\x3cdiv class\x3d'oj-label-group'\x3e\x3c/div\x3e\x3c/div\x3e":"\x3cdiv class\x3d'oj-label oj-component'\x3e\x3cdiv class\x3d'oj-label-group'\x3e\x3c/div\x3e\x3c/div\x3e"},CF:function(){return"\x3cspan class\x3d'oj-label-required-icon oj-component-icon' title\x3d'"+this.O(this.cb.oM)+"' role\x3d'img'\x3e\x3c/span\x3e"},bR:function(a,b){var c,d;b&&(c=f("\x3ca target\x3d'_blank' class\x3d'oj-label-help-icon-anchor'\x3e\x3c/a\x3e",this.document[0]),c.attr("href",b),d=f("\x3cspan class\x3d'oj-label-help-icon oj-component-icon oj-clickable-icon' role\x3d'img'\x3e\x3c/span\x3e",
this.document[0]),a?d.attr("title",a):d.attr("title",this.O(this.cb.mM)),c.append(d));return c},HA:function(){var a=this.options.help.definition,b;a&&(this.element.addClass("oj-label-help-def"),(b=this.element.attr("title"))?this.element.attr("title",b+" "+a):this.element.attr("title",a))},uT:function(){this.element.removeClass("oj-label-help-def");this.element.attr("title","")},HD:function(a){var b=this.options.help.source,c;b&&(c=this.options.help.definition,a.prepend(this.bR(c,b)))},cF:function(){var a,
b;this.bu();a="#"+this.options.describedById;this.uT();b=this.Og.find(".oj-label-help-icon");1===b.length&&b.parent().remove();b=this.options.help.source;a=this.Og.find(a);null!=b&&0===a.length?a=this.pu():null==b&&0<a.length&&0===a.children().size()&&a.remove();this.HD(a);this.HA()},fF:function(){var a;a="#"+this.options.describedById;this.options.required?(this.bu(),0===this.Og.find(".oj-label-required-icon").length&&(a=this.Og.find(a),0===a.length&&(a=this.pu()),a.append(this.CF()))):(this.Og.find(".oj-label-required-icon").remove(),
a=this.Og.find(a),0<a.length&&0===a.children().size()&&a.remove())},_setOption:function(a,b){this._superApply(arguments);"required"===a&&this.fF();"help"===a&&this.cF()},getNodeBySubId:function(a){var b;b=this._super(a);b||(a=a.subId,"oj-label-help-icon"===a&&(b=this.widget().find(".oj-label-help-icon")[0]),"oj-label-help-icon-anchor"===a&&(b=this.widget().find(".oj-label-help-icon").parent()[0]),"oj-label-required-icon"===a&&(b=this.widget().find(".oj-label-required-icon")[0]));return b||null},_destroy:function(){this.Og.replaceWith(this.element);
this.vk();return this._super()}});a.td={};o_("EditableValueUtils",a.td,a);a.td.$V=function(a,b){var c,d,e={};if(a&&b)switch(b){case "disabled":c=void 0!==a.attr("disabled")?!!a.prop("disabled"):void 0;break;case "pattern":c=a.prop("pattern")||void 0;break;case "placeholder":c=a.prop("placeholder")||void 0;break;case "readonly":c=void 0!==a.attr("readonly")?!!a.prop("readonly"):void 0;break;case "required":c=a.attr("required");d=a.prop("required");c=void 0!==c?void 0!==d?!!d:!!c:void 0;break;case "title":c=
a.prop("title");break;case "value":c=a.val()||void 0;break;default:c=a.attr(b)||void 0}void 0!==c?(e.KH=!0,e.value=c):e.KH=!1;return e};a.td.Ki=function(b,c,d){for(var e=0;e<b.length;e++){var g,f;g=b[e];f=g.attribute;var h=g.option||f,k=g.coerceDomValue,s=g.validateOption,v=d.element,z=d.options[h];void 0===c[h]&&(z=d.options[h],f=a.td.$V(v,f),f.KH?(g=f.value,k&&("boolean"===typeof k?g=a.td.CV(h,g):"function"===typeof k&&(g=k.call(d,g))),d.options[h]=g,d.ht(h,z)):void 0===z&&(d.options[h]=g.defaultOptionValue));
s&&("boolean"===typeof s?a.td.FX(h,d.options[h]):"function"===typeof s&&s.call(d))}};a.td.FX=function(a,b){var c=!1;switch(a){case "required":null!==b&&"boolean"!==typeof b&&(c=!0);break;case "readOnly":case "disabled":null!==b&&"boolean"!==typeof b&&(c=!0)}if(c)throw"Option '"+a+" 'has invalid value set: "+b;};a.td.CV=function(a,b){var c=b;switch(a){case "required":c=b?!0:!1}return c}});
//# sourceMappingURL=oj-modular.map