/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojeditablevalue"],function(a,f){a.Oa("oj.inputBase",f.oj.editableValue,{version:"1.0.0",widgetEventPrefix:"oj",_ATTR_CHECK:[],_CLASS_NAMES:"",_WIDGET_CLASS_NAMES:"",_INPUT_HELPER_KEY:"",uz:"blur",Yz:"keydown",Hz:"drop",options:{converter:void 0,placeholder:void 0,readOnly:void 0},sA:function(a){var b=this._superApply(arguments);this.NS();return b},_InitOptions:function(c,b){this._super(c,b);a.td.Ki([{attribute:"disabled",defaultOptionValue:!1,validateOption:!0},
{attribute:"pattern",defaultOptionValue:""},{attribute:"placeholder",defaultOptionValue:""},{attribute:"value",defaultOptionValue:null},{attribute:"readonly",option:"readOnly",defaultOptionValue:!1,validateOption:!0},{attribute:"required",defaultOptionValue:!1,coerceDomValue:!0,validateOption:!0},{attribute:"title",defaultOptionValue:""}],b,this)},_ComponentCreate:function(){var a=this.element,b=this._superApply(arguments),d=this.gt(a);"boolean"===typeof this.options.readOnly&&this.element.prop("readonly",
this.options.readOnly);this.um()&&this.cV();"pattern"in d&&a.removeAttr("pattern");this.Gp={};this.ib=null;return b},Rh:function(){var a=this._superApply(arguments),b=this;this._CLASS_NAMES&&this.element.addClass(this._CLASS_NAMES);this.XA();this.Ws();f.each(["disabled","readOnly"],function(a,c){b.options[c]&&b.PE(c,b.options[c])});return a},PE:function(a,b){"disabled"===a&&this.element.prop("disabled",b);"readOnly"===a&&(this.element.prop("readonly",b),this.ur("readOnly",b));"disabled"!==a&&"readOnly"!==
a||this.XA()},_setOption:function(a,b){var d=this._superApply(arguments);"disabled"!==a&&"readOnly"!==a||this.PE(a,b);"pattern"===a&&(this.Gp.pattern=b,this.ut(),this.pk());return d},_destroy:function(){var a=this._superApply(arguments);this.element.off("blur drop keydown");this.Uv&&this.Uv.remove();this.um()&&this.element.unwrap();this.vk();return a},XA:function(){if(!this.options.readOnly&&!this.options.disabled){this.ib={};var a=f.proxy(this.pw,this),b=f.proxy(this.or,this),d=function(){this.focus()};
this.element.on("blur",a);this.element.on("keydown",b);this.element.on("drop",d);this.ib[this.uz]=a;this.ib[this.Yz]=b;this.ib[this.Hz]=d}else if(this.ib)for(a=[this.uz,this.Yz,this.Hz],b=0,d=a.length;b<d;b++)this.ib[a[b]]&&(this.element.off(a[b],this.ib[a[b]]),delete this.ib[a[b]])},Th:{readOnly:"oj-read-only"},NS:function(){for(var a=this._ATTR_CHECK,b=0,d=a.length;b<d;b++){var e=a[b].attr;"setMandatory"in a[b]&&this.element.attr(e,a[b].setMandatory)}},pw:function(a){this.ie(this.Yg(),a)},or:function(a){a.keyCode===
f.ui.keyCode.ENTER&&this.ie(this.Yg(),a)},um:function(){return this._WIDGET_CLASS_NAMES},cV:function(){f(this.element).wrap(f("\x3cdiv\x3e").addClass(this._WIDGET_CLASS_NAMES));this.tl=this.element.parent()},Ws:function(){if(this._INPUT_HELPER_KEY&&this.um()){var a=this.element.attr("aria-describedby")||"",b=this.Sh(this._INPUT_HELPER_KEY);this.element.attr("aria-describedby",a+(" "+b));this.Uv=f("\x3cdiv class\x3d'oj-helper-hidden-accessible' id\x3d'"+b+"'\x3e"+this.O(this._INPUT_HELPER_KEY)+"\x3c/div\x3e");
this.Xs().append(this.Uv)}},Xs:function(){return this.widget()},qA:function(){this.Gp={};this._super()},vm:function(){var c=this._superApply(arguments),b={};return this.options.pattern?(b[a.Tb.VALIDATOR_TYPE_REGEXP]=this.tP(),a.ec.Ne(b,c)):c},ur:function(a,b){-1!=Object.keys(this.Th).indexOf(a)&&this.widget().toggleClass(this.Th[a],!!b)},tP:function(){var c;this.Gp={pattern:this.options.pattern,label:this.ev()};return(c=a.ca.Xf(a.Tb.VALIDATOR_TYPE_REGEXP))?c.createValidator(this.Gp):null},Sh:function(a){return this.uuid+
"_"+a},tp:function(){return"rtl"===this.Ec()},getNodeBySubId:function(a){return this._super(a)},widget:function(){return this.um()?this.tl:this.element}});a.Oa("oj.ojInputText",f.oj.inputBase,{version:"1.0.0",defaultElement:"\x3cinput\x3e",widgetEventPrefix:"oj",_ATTR_CHECK:[{attr:"type",setMandatory:"text"}],_CLASS_NAMES:"oj-inputtext-input",_WIDGET_CLASS_NAMES:"oj-inputtext oj-form-control oj-component",options:{pattern:void 0},getNodeBySubId:function(a){var b=this._superApply(arguments),d;b||(d=
a.subId,"oj-inputtext-input"===d&&(b=this.element?this.element[0]:null));return b||null},_GetDefaultStyleClass:function(){return"oj-inputtext"}});a.Oa("oj.ojTextArea",f.oj.inputBase,{version:"1.0.0",defaultElement:"\x3ctextarea\x3e",widgetEventPrefix:"oj",_ATTR_CHECK:[],_CLASS_NAMES:"oj-textarea-input",_WIDGET_CLASS_NAMES:"oj-textarea oj-form-control oj-component",options:{pattern:void 0},getNodeBySubId:function(a){var b=this._superApply(arguments),d;b||(d=a.subId,"oj-textarea-input"===d&&(b=this.element?
this.element[0]:null));return b||null},_GetDefaultStyleClass:function(){return"oj-textarea"}});a.Oa("oj.ojInputPassword",f.oj.inputBase,{version:"1.0.0",defaultElement:"\x3cinput\x3e",widgetEventPrefix:"oj",_ATTR_CHECK:[{attr:"type",setMandatory:"password"}],_CLASS_NAMES:"oj-inputpassword-input",_WIDGET_CLASS_NAMES:"oj-inputpassword oj-form-control oj-component",options:{pattern:void 0},getNodeBySubId:function(a){var b=this._superApply(arguments),d;b||(d=a.subId,"oj-inputpassword-input"===d&&(b=this.element?
this.element[0]:null));return b||null},_GetDefaultStyleClass:function(){return"oj-inputpassword"}})});
//# sourceMappingURL=oj-modular.map