"use strict";
/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojeditablevalue","ojs/ojbutton"],function(a,f){a.Oa("oj.ojInputNumber",f.oj.editableValue,{version:"1.0.0",defaultElement:"\x3cinput\x3e",widgetEventPrefix:"oj",options:{converter:a.ca.yi(a.Zf.CONVERTER_TYPE_NUMBER).createConverter(),max:void 0,min:void 0,placeholder:void 0,readOnly:void 0,step:void 0,value:void 0},getNodeBySubId:function(a){var b=this._superApply(arguments),d;b||(d=a.subId,"oj-inputnumber-up"===d&&(b=this.widget().find(".oj-inputnumber-up")[0]),
"oj-inputnumber-down"===d&&(b=this.widget().find(".oj-inputnumber-down")[0]),"oj-inputnumber-input"===d&&(b=this.widget().find(".oj-inputnumber-input")[0]));return b||null},refresh:function(){this._super();this.sb()},stepDown:function(a){this.wG(a,!1)},stepUp:function(a){this.wG(a,!0)},widget:function(){return this.ik},_InitOptions:function(c,b){this._superApply(arguments);a.td.Ki([{attribute:"disabled",defaultOptionValue:!1,validateOption:!0},{attribute:"pattern",defaultOptionValue:""},{attribute:"placeholder",
defaultOptionValue:""},{attribute:"value",defaultOptionValue:null},{attribute:"readonly",option:"readOnly",defaultOptionValue:!1,validateOption:!0},{attribute:"required",defaultOptionValue:!1,coerceDomValue:!0,validateOption:!0},{attribute:"title",defaultOptionValue:""},{attribute:"min",defaultOptionValue:null},{attribute:"max",defaultOptionValue:null},{attribute:"step",defaultOptionValue:1}],b,this);this.options.value=this.Jn("value",this.options.value);null!=this.options.step&&(this.options.step=
this.HE(this.options.step));null!=this.options.min&&(this.options.min=this.Jn("min",this.options.min));null!=this.options.max&&(this.options.max=this.Jn("max",this.options.max));if(null!=this.options.min&&null!=this.options.max&&this.options.max<this.options.min)throw Error("ojInputNumber's max must not be less than min");},_ComponentCreate:function(){var a=this.element;this._super();this.Wm();this._on(this.Jf);this._on(this.window,{beforeunload:function(){a.removeAttr("autocomplete")}});a.removeAttr("pattern");
this.GD={}},Rh:function(){this._super();this.sb()},sz:function(a,b,d){this._superApply(arguments);switch(a){case "min":case "max":this.Ff(a,this.options[a])}},_setOption:function(a,b,d){var e;e="value"===a||"max"===a||"min"===a?this.Jn(a,b):"step"===a?this.HE(b):b;this._super(a,e,d);if("max"===a||"min"===a)this.DB(),this.pk();"disabled"===a&&this.element.prop("disabled",!!b);"readOnly"===a&&(this.element.prop("readonly",!!b),this.ur("readOnly",this.options.readOnly),this.gF("readOnly",this.options.readOnly))},
_destroy:function(){this._off(this.element,"keydown keyup focus blur mousedown mouseup mouseenter mouseleave");this.ik.replaceWith(this.element);clearTimeout(this.xf);return this._super()},Ff:function(a,b,d){this._superApply(arguments);var e="value"===a||"max"===a||"min"===a;e&&this.Cw();(e||"disabled"===a)&&this.gx()},ct:function(){return!this._superApply(arguments)||this.options.readOnly?!1:!0},nc:function(){return this.options.converter?this._superApply(arguments):f.oj.ojInputNumber.prototype.options.converter},
vm:function(){var a=this._superApply(arguments);null==this.options.min&&null==this.options.max||this.DB();return f.extend(this.GD,a)},_GetDefaultStyleClass:function(){return"oj-inputnumber"},Jf:{keydown:function(a){a.keyCode===f.ui.keyCode.ENTER?(this.$A(a),a.preventDefault()):this.ml()&&this.Fj(a)&&a.preventDefault()},keyup:function(a){this.Yn(a)},focus:function(){this.previous=this.element.val()},blur:function(a){this.ux?delete this.ux:this.$A(a)},"mousedown .oj-inputnumber-button":function(a){function b(){this.element[0]!==
this.document[0].activeElement&&(this.element.focus(),this.previous=d,this._delay(function(){this.previous=d}))}var d;d=this.element[0]===this.document[0].activeElement?this.previous:this.element.val();a.preventDefault();b.call(this);this.ux=!0;this._delay(function(){delete this.ux;b.call(this)});this.ml();this.Sn(null,f(a.currentTarget).hasClass("oj-inputnumber-up")?1:-1,a)},"mouseup .oj-inputnumber-button":function(a){this.Yn(a)},"mouseenter .oj-inputnumber-button":function(a){f(a.currentTarget).hasClass("oj-active")&&
(this.ml(),this.Sn(null,f(a.currentTarget).hasClass("oj-inputnumber-up")?1:-1,a))},"mouseleave .oj-inputnumber-button":function(a){this.Yn(a)}},cb:{lM:"tooltipDecrement",nM:"tooltipIncrement"},Th:{readOnly:"oj-read-only"},sb:function(){var a=this.O(this.cb.nM),b=this.O(this.cb.lM);this.ik.find(".oj-inputnumber-up").ojButton({display:"icons",icons:{start:"oj-component-icon oj-inputnumber-up-icon"},label:a});this.ik.find(".oj-inputnumber-down").ojButton({display:"icons",icons:{start:"oj-component-icon oj-inputnumber-down-icon"},
label:b});this.Cw();this.gx();"boolean"===typeof this.options.readOnly&&this.element.prop("readonly",this.options.readOnly);this.ur("readOnly",this.options.readOnly);this.gF("readOnly",this.options.readOnly)},Wm:function(){var a=this.ik=this.element.addClass("oj-inputnumber-input").attr("autocomplete","off").wrap("\x3cspan class\x3d'oj-inputnumber oj-component'\x3e\x3c/span\x3e").parent().append("\x3ca class\x3d'oj-inputnumber-button oj-inputnumber-down'\x3e\x3c/a\x3e\x3ca class\x3d'oj-inputnumber-button oj-inputnumber-up'\x3e\x3c/a\x3e");
this.saveType=this.element.prop("type");this.element.attr("type","text");this.buttons=a.find(".oj-inputnumber-button").attr("tabIndex","-1").attr("aria-hidden",!0)},Fj:function(a){var b=f.ui.keyCode;switch(a.keyCode){case b.UP:return this.Sn(null,1,a),!0;case b.DOWN:return this.Sn(null,-1,a),!0}return!1},GY:function(){return"\x3cspan class\x3d'oj-inputnumber oj-component'\x3e\x3c/span\x3e"},WX:function(){return"\x3ca class\x3d'oj-inputnumber-button oj-inputnumber-down'\x3e\x3c/a\x3e\x3ca class\x3d'oj-inputnumber-button oj-inputnumber-up'\x3e\x3c/a\x3e"},
ml:function(){return this.kJ=!0},Sn:function(a,b,d){a=a||500;clearTimeout(this.xf);this.xf=this._delay(function(){this.Sn(40,b,d)},a);this.Uw(b*this.options.step,d)},Uw:function(a,b){var d=this.Tu(),d=this.CM(d,a);this.ie(d,b,this.Bm.iK)},HS:function(){var a=this.OE(this.options.step);null!=this.options.min&&(a=Math.max(a,this.OE(this.options.min)));return a},OE:function(a){a=a.toString();var b=a.indexOf(".");return-1===b?0:a.length-b-1},CM:function(a,b){var d,e,f=this.options,h=this.HS();e=null!=
f.min?f.min:0;d=a-e;var k=Math.round(d/f.step)*f.step,k=parseFloat(k.toFixed(h));k!==d?(d=0>b?Math.ceil(d/f.step)*f.step:Math.floor(d/f.step)*f.step,d=e+d+b):d=a+b;d=parseFloat(d.toFixed(h));return null!=f.min&&d<f.min?f.min:null!=f.max&&d>f.max?(e=Math.floor((f.max-e)/f.step)*f.step+e,e=parseFloat(e.toFixed(h))):d},Yn:function(){this.kJ&&(clearTimeout(this.xf),this.kJ=!1)},gx:function(){var a=this.Tu(),b=this.options.min,d=this.options.max;if(this.ik){var e=this.ik.find(".oj-inputnumber-down").ojButton(),
f=this.ik.find(".oj-inputnumber-up").ojButton();this.options.disabled||void 0===a?(e.ojButton("disable"),f.ojButton("disable")):null!=d&&a>=d?(e.ojButton("enable"),f.ojButton("disable")):(null!=b&&a<=b?e.ojButton("disable"):e.ojButton("enable"),f.ojButton("enable"))}},Tu:function(){var a,b;try{b=this.Yg()||0,a=this.IE(b)}catch(d){a=void 0}return a},$A:function(a){this.Yn();this.previous!==this.element.val()&&(this.Cw(),this.gx(),this.ie(this.element.val(),a))},DB:function(){var c=null!=this.options.min?
this.options.min:void 0,b=null!=this.options.max?this.options.max:void 0,d=this.options.translations?this.options.translations.numberRange||{}:{},e,f,h,k,l,m,n,q=d.hint||{},r=d.messageDetail||{},d=d.messageSummary||{};null!==q&&(e=q.min||null,f=q.max||null,h=q.inRange||null);null!==r&&(k=r.rangeOverflow||null,l=r.rangeUnderflow||null);null!==d&&(m=d.rangeOverflow||null,n=d.rangeUnderflow||null);c={min:c,max:b,hint:{min:e||null,max:f||null,inRange:h||null},messageDetail:{rangeOverflow:k||null,rangeUnderflow:l||
null},messageSummary:{rangeOverflow:m||null,rangeUnderflow:n||null},converter:this.nc()};this.GD[a.Tb.VALIDATOR_TYPE_NUMBERRANGE]=a.ca.Xf(a.Tb.VALIDATOR_TYPE_NUMBERRANGE).createValidator(c)},Jn:function(a,b){var d;d=null!==b?+b:b;if(isNaN(d))throw Error("ojInputNumber's "+a+" option is not a number");return d},HE:function(a){if(null===a)return 1;a=this.Jn("step",a);if(0>=a)throw Error("Invalid step for ojInputNumber; step must be \x3e 0");if(null===a||0>=a)a=1;return a},ur:function(a,b){-1!=Object.keys(this.Th).indexOf(a)&&
this.widget().toggleClass(this.Th[a],!!b)},gF:function(a,b){b?this.widget().removeAttr("role"):this.widget().attr("role","spinbutton")},Cw:function(){var a=this.Tu(),b=this.element.val();this.element.attr({"aria-valuemin":this.options.min,"aria-valuemax":this.options.max,"aria-valuenow":a});this.DA(""+a,b)||this.element.attr({"aria-valuetext":b})},wG:function(a,b){this.ml();b?this.Uw((a||1)*this.options.step):this.Uw((a||1)*-this.options.step);this.Yn()}})});
//# sourceMappingURL=oj-modular.map