/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","knockout"],function(a,f,c){function b(a,b,c,d){"dayMetaData"===a&&d({dayFormatter:b?function(a){return q(b,0,[a.fullYear,a.month,a.date])}:null})}function d(a,b){var c={};c.value=b.value;return c}function e(a,b){var c={},d=b.optionMetadata;d&&"shouldWrite"===d.writeback&&(c[b.option]=b.value);return c}function g(){this.Init()}function h(a,b,c){this.Init(a,b,c)}function k(a,b){return function(d){var e,g;e=d.parentElement;g=a.createChildContext(d.data,null,function(a){a.$key=
d.key;a.$metadata=d.metadata;a.$headerContext=d});c.renderTemplate(b,g,null,e);return null}}function l(a,b){return function(d){var e,g;e=d.parentElement;g=a.createChildContext(d.data,null,function(a){a.$keys=d.keys;a.$metadata=d.metadata;a.$cellContext=d});c.renderTemplate(b,g,null,e);return null}}function m(a,b,d){var e={};(function(b,d){e=function(e){var g=null,f=null;"header"==d?(g=a.extend({$column:e.column,$headerContext:e.headerContext}),f=e.headerContext.parentElement):"cell"==d&&(g=a.createChildContext(e.row,
null,function(a){a.$column=e.column;a.$cellContext=e.cellContext}),f=e.cellContext.parentElement);"footer"==d&&(g=a.extend({$column:e.column,$footerContext:e.footerContext}),f=e.footerContext.parentElement);c.renderTemplate(b,g,null,f,"replaceNode")}})(d,b);return e}function n(a,b){return function(d){var e=a.createChildContext(d.row,null,function(a){a.$rowContext=d.rowContext});c.renderTemplate(b,e,null,d.rowContext.parentElement,"replaceNode")}}function q(a,b,c){if(!a||b===c.length)return a;var d=
b+1;return q(a[c[b]],d,c)||q(a["*"],d,c)}a.ka=function(a,b){this.Init(a,b)};o_("ComponentBinding",a.ka,a);a.b.sa(a.ka,a.b,"oj.ComponentBinding");a.ka.create=function(b,d){if(null==b)throw"Binding name is required!";var e=new a.ka(b,d),g=c.bindingHandlers,f,h=Array.isArray(b)?b:[b];for(f=0;f<h.length;f++)g[h[f]]=e;return e};o_("ComponentBinding.create",a.ka.create,a);a.ka.Eh=function(){return a.ka.QK};o_("ComponentBinding.getDefaultInstance",a.ka.Eh,a);a.ka.prototype.Mh=function(a){var b=a["for"],
b=null==b?"@global":b,c=this.fr[b]||[];c.push(a);this.fr[b]=c};a.b.g("ComponentBinding.prototype.setupManagedAttributes",{Mh:a.ka.prototype.Mh});a.ka.Dx=function(){a.ka.lB.Dx()};o_("ComponentBinding.deliverChanges",a.ka.Dx,a);a.ka.prototype.Init=function(b,c){a.ka.t.Init.call(this);"string"===typeof c&&(c={componentName:c});this.Kt=c||{};this.bN=Array.isArray(b)?b:[b];this.init=a.b.fs(this,this._init);this.update=a.b.fs(this,this.si);this.fr={}};a.ka.lt="_ojNeedsJUIBInit";a.ka.prototype._init=function(b,
d,e,g,h){c.applyBindingsToDescendants(h,b);f(b).data(a.ka.lt,!0);return{controlsDescendantBindings:!0}};a.ka.prototype.si=function(b,c,d,e,g){e=f(b);e.data(a.ka.lt)&&(e.data(a.ka.lt,null),this.zD(b,e,c,d,g))};a.ka.prototype.zD=function(b,g,f,l,k){var m=f(),n=null,q=!1,y=[],H=null,x=null,O=a.ka.iP(this.bN,b,k),B=0,A={},D=this.Kt.componentName;if(null==D){n="component";if(!O[n]&&(n="role",!O[n])){a.D.error("component attribute is required for the ojComponent binding");return}var C=m[n];if(null==C){a.D.error("non-null component attribute is required for the ojComponent binding");
return}c.computed(function(){a.ka.qq(O[n],n,A,k,!1);if(0==B)D=c.utils.unwrapObservable(C);else{q=!0;O=null;a.ka.PU(g);if(x){H.BH();H=null;var d=this.Kt.beforeDestroy;d&&d(b,x,f,l,k);x("destroy");x=null;for(d=0;d<y.length;d++)y[d].BH();y=null}this.zD(b,g,f,l,k)}return null},this,{disposeWhenNodeIsRemoved:b})}if(null!=D)if(x=g[D],"function"===typeof x){var x=x.bind(g),I=a.ka.GF(this.fr,O,D),P={},F=a.ka.Eh();this!==F&&(F=F.JP(O,D),a.ec.Ne(F,I),I=F);for(var G={},H=new h(x,b,a.ka.lB),F={"^slider$":[{event:"slidechange",
getter:d}],"^oj*":[{event:"ojoptionchange",getter:e}]},N=function(){var c=this.TS,d=O[c];if(!d)throw"Binding expression for property "+c+" is not found";d=a.ka.qq(d,c,A,k,0!==B&&!q);if(0===B){var d=a.ka.HG(m[c]),e=I[c];null!=e?(P[c]=e,e=e.xW,null!=e&&(c=e(c,d,b,x,f,l,k)||{},a.ec.Ne(G,c))):G[c]=d}else if(!q)if(d=a.ka.HG(d),null!=I[c]){if(e=I[c].update,null!=e)for(c=e(c,d,b,x,f,l,k)||{},d=Object.keys(c),e=0;e<d.length;e++){var g=d[e];H.dH(g,c[g])}}else H.dH(c,d);return null},J,K=Object.keys(m),E=0;E<
K.length;E++)J=K[E],J!==n&&y.push(c.computed(N,{TS:J},{disposeWhenNodeIsRemoved:b}));a.ka.jT(g,D,F,O,H,k,A);F=a.ka.fC(G);x(G);for(var S in F)x("option",S,F[S]);(S=this.Kt.afterCreate)&&S(b,x,f,l,k);a.ka.tO(P,b,x,f,l,k);G=null}else a.D.error("Component %s is not found",D);B=1};a.ka.iP=function(a,b,d){var e={},g=null,g=c.bindingProvider.instance,f;f=null;var h,g=g.aW?g.aW(b,d):b.getAttribute("data-bind");if(!g)return e;b=c.jsonExpressionRewriting.parseObjectLiteral(g);d=/^(\s|\u00A0)+|(\s|\u00A0)+$/g;
for(g=0;g<b.length;g+=1){h=b[g];var l=h.key.replace(d,"");if(0<=a.indexOf(l)){f=h.value;break}}if(!f)return e;b=c.jsonExpressionRewriting.parseObjectLiteral(f);for(a=0;a<b.length;a+=1)f=b[a],e[f.key.replace(d,"")]=f.value.replace(d,"");return e};a.ka.qq=function(a,b,c,d,e){var g=c[b],f=void 0===g;if(f||null===g.Fx&&g.hJ&&e){"string"!==typeof a&&(a=a());var g=null,h=!1;if(null!==a){if(f){if(f=a.charAt(0),"'"===f||'"'===f||0>=a.indexOf("("))h=!0}else h=!0;if(!h||e)g=new Function("$context","with($context){with($data||{}){return "+
a+";}}")}g={Fx:g,hJ:h};c[b]=g}return!g.Fx||!e&&g.hJ?null:g.Fx(d)};a.ka.prototype.JP=function(b,c){return a.ka.GF(this.fr,b,c)};a.ka.GF=function(a,b,c){function d(b,c){var e=a[b];if(null!=e)for(var f=e.length-1;0<=f;f--){var h=e[f];null!=h.attributes&&g.push(h);if(c&&(h=h.use,null!=h))for(var h=Array.isArray(h)?h:[h],p=0;p<h.length;p++)d(h[p],!0)}}var e={},g=[];d(c,!0);c=f.oj[c];if(null!=c)for(c=Object.getPrototypeOf(c.prototype);null!=c&&"oj"===c.namespace;)d(c.widgetName,!0),c=Object.getPrototypeOf(c);
d("@global",!1);if(0<g.length)for(b=Object.keys(b),c=0;c<b.length;c++)for(var h=b[c],l=0;l<g.length;l++){var k=g[l];if(0<=k.attributes.indexOf(h)){e[h]={xW:k.init,update:k.update,iV:k.afterCreate};break}}return e};a.ka.Lz=".ojWriteback";a.ka.PU=function(b){b&&b.off(a.ka.Lz)};a.ka.jT=function(b,c,d,e,g,f,h){var l={},k;for(k in d)if(c.match(k)){c=d[k];for(d=0;d<c.length;d++)k=c[d],b.on(k.event+a.ka.Lz,{tW:k.getter},function(b,c){b.stopPropagation();var d=b.data.tW(b,c);g.zX();try{for(var p in d)if(e[p]){var k=
a.ka.qq(e[p],p,h,f,!0);a.ka.dV(p,k,d[p],e[p],f,l)}}finally{g.fX()}});break}};a.ka.XP=function(a){var b=["true","false","null","undefined"];if(null==a||0<=b.indexOf(a))return null;b=a.match(/^(?:[$_a-z][$\w]*|(.+)(\.\s*[$_a-z][$\w]*|\[.+\]))$/i);return null===b?null:"function(v){"+(b[1]?"Object("+b[1]+")"+b[2]:a)+"\x3dv;}"};a.ka.dV=function(b,d,e,g,f,h){null!=d&&c.isObservable(d)?c.isWriteableObservable(d)&&d(e):(b=a.ka.qq(function(){return a.ka.XP(g)},b,h,f,!0))&&b(e)};a.ka.HG=function(b){b=c.utils.unwrapObservable(b);
(Array.isArray(b)||a.ec.isPlainObject(b))&&b.ojConvertToJS&&(b=c.toJS(b));return b};a.ka.fC=function(a){var b={},c;for(c in a)0<=c.indexOf(".")&&(b[c]=a[c]);for(var d in b)delete a[d];return b};a.ka.tO=function(a,b,c,d,e,g){for(var f=Object.keys(a),h=0;h<f.length;h++){var l=f[h],k=a[l].iV;k&&k(l,b,c,d,e,g)}};a.b.sa(g,a.b,"ComponentBinding.GlobalChangeQueue");g.prototype.Init=function(){g.t.Init.call(this);this.ql=[];this.cl=[]};g.prototype.bX=function(b){-1===this.ql.indexOf(b)&&(this.ql.push(b),
this.lq||(this.lq=setTimeout(a.b.fs(this,this.QB),1)))};g.prototype.cX=function(a){a=this.ql.indexOf(a);0<=a&&this.ql.splice(a,1)};g.prototype.Dx=function(){this.lq&&clearTimeout(this.lq);this.QB()};g.prototype.QB=function(){var a;this.lq=null;var b=this.ql;this.ql=[];for(a=0;a<b.length;a++){var c=b[a];this.cl.push({My:c,ko:c.YV()})}for(;0<this.cl.length;)a=this.cl.shift(),a.My.kV(a.ko)};a.b.sa(h,a.b,"ComponentBinding.ComponentChangeTracker");h.prototype.Init=function(a,b,c){h.t.Init.call(this);this.Va=
a;this.LO=b;this.cl=c;this.au={};this.nl=0};h.prototype.dH=function(a,b){this.GR()||this.AO||(this.au[a]=b,this.cl.bX(this))};h.prototype.BH=function(){this.cl.cX(this);this.AO=!0};h.prototype.fX=function(){a.i.assert(0<this.nl,"ComponentChangeTracker._suspendCount underflow");this.nl-=1};h.prototype.zX=function(){this.nl+=1};h.prototype.kV=function(b){if(null!=a.Components.rs(this.LO)){var c=a.ka.fC(b),d={changed:!0};this.Va("option",b,d);for(var e in c)this.Va("option",e,c[e],d)}};h.prototype.YV=
function(){var a=this.au;this.au={};return a};h.prototype.GR=function(){return 1<=this.nl};a.ka.lB=new g;a.ka.QK=a.ka.create(["ojComponent","jqueryUI"]);a.ey={};o_("koStringTemplateEngine",a.ey,a);a.ey.DW=function(){function a(c){this.pl=c;this.text=function(a){if(!a)return b[this.pl];b[this.pl]=a};this.data=function(a,b){d[this.pl]||(d[this.pl]={});if(1===arguments.length)return d[this.pl][a];d[this.pl][a]=b}}var b={},d={},e=new c.nativeTemplateEngine;e.makeTemplateSource=function(b,d){if("string"==
typeof b){d=d||document;var e=d.getElementById(b);return e?new c.templateSources.domElement(e):new a(b)}if(b&&1==b.nodeType||8==b.nodeType)return new c.templateSources.anonymousTemplate(b)};c.templates=b;c.setTemplateEngine(e)};o_("koStringTemplateEngine.install",a.ey.DW,a);a.ka.Eh().Mh({attributes:["header","cell"],init:function(a,b,c,d,e,g,f){"header"===a?(a=b.row,null!=a&&(c=a.template,null!=c&&(a.renderer=k(f,c))),a=b.column,null!=a&&(c=a.template,null!=c&&(a.renderer=k(f,c))),d({header:b})):
"cell"===a&&(a=b.template,null!=a&&(b.renderer=l(f,a)),d({cell:b}))},update:function(a,b,c,d,e,g,f){return"header"===a?(a=b.row,null!=a&&(c=a.template,null!=c&&(a.renderer=k(f,c))),a=b.column,null!=a&&(c=a.template,null!=c&&(a.renderer=k(f,c))),{header:b}):"cell"===a?(a=b.template,null!=a&&(b.renderer=l(f,a)),{cell:b}):null},"for":"ojDataGrid"});c.bindingHandlers.ojContextMenu={update:function(a,b){f(a).off(".ojContextMenu");var d=c.utils.unwrapObservable(b());"string"!==f.type(d)&&(d=a.getAttribute("contextmenu"))&&
(d="#"+d);d&&(d=f(d).data("oj-ojMenu"));if(d){var e=f(a);e.on("keydown.ojContextMenu contextmenu.ojContextMenu",function(a){return"contextmenu"===a.type||121==a.which&&a.shiftKey?(d.open(a,{launcher:e,initialFocus:"menu"}),!1):!0})}}};a.ka.Eh().Mh({attributes:["columns","columnsDefault","rowTemplate"],init:function(a,b,c,d,e,g,f){if("columns"==a||"columnsDefault"==a){var h;for(c=0;c<b.length;c++){var l=b[c];e=l.template;g=l.footerTemplate;h=l.headerTemplate;null!=e&&(l.renderer=m(f,"cell",e));null!=
g&&(l.footerRenderer=m(f,"footer",g));null!=h&&(l.headerRenderer=m(f,"header",h))}"columns"==a?d({columns:b}):d({columnsDefault:b})}else"rowTemplate"==a&&d({rowRenderer:n(f,b)})},update:function(a,b,c,d,e,g,f){if("columns"==a||"columnsDefault"==a){var h;for(c=0;c<b.length;c++){var l=b[c];e=l.template;g=l.footerTemplate;h=l.headerTemplate;null!=e&&(l.renderer=m(f,"cell",e));null!=g&&(l.footerRenderer=m(f,"footer",g));null!=h&&(l.headerRenderer=m(f,"header",h))}"columns"==a?d({columns:b}):d({columnsDefault:b})}else if("rowTemplate"==
a)return{rowRenderer:n(f,b)};return null},"for":"ojTable"});a.ka.Eh().Mh({"for":"ojDayMetaData",attributes:["dayMetaData"],init:b,update:b});a.ka.Eh().Mh({"for":"ojInputDateTime",use:"ojDayMetaData"});a.ka.Eh().Mh({"for":"ojInputDate",use:"ojDayMetaData"});a.ka.Eh().Mh({"for":"ojInputTime",use:"ojDayMetaData"})});
//# sourceMappingURL=oj-modular.map