"use strict";
/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","promise"],function(a,f){a.X=window.oj.Events={on:function(a,b,d){return this.Wg(a,b,d,!1,!1)},off:function(a,b,d){return this.ow(a,b,d,!1)},trigger:function(c){var b=Array.prototype.slice.call(arguments);b.unshift(!1);return a.X.Hb.apply(this,b)},once:function(a,b,d){return this.AE(a,b,d,!1)},listenTo:function(c,b,d){var e,g,h,f,l={};b.constructor===String?l[b]=d:l=b;for(f in l)if(l.hasOwnProperty(f))for(b=a.X.rj(f),d=0;d<b.length;d+=1)e=b[d].event,g=b[d].Ob,h={event:e,
Ob:g,object:c,gc:l[f]},this.cu(this.Yb,h,a.X.aE),e=g?e+":"+g:e,void 0===this.Yb&&(this.Yb=[]),this.Yb.push(h),c.Wg(e,l[f],null,!0,!1);return this},listenToOnce:function(c,b,d){var e,g,h,f,l={};b.constructor===String?l[b]=d:l=b;for(f in l)if(l.hasOwnProperty(f))for(b=a.X.rj(f),d=0;d<b.length;d+=1)e=b[d].event,g=b[d].Ob,h={event:e,Ob:g,object:c,gc:l[f]},this.cu(this.Yb,h,a.X.aE),e=g?e+":"+g:e,void 0===this.Yb&&(this.Yb=[]),this.Yb.push(h),c.AE(e,l[f],null,!0);return this},stopListening:function(c,b,
d){var e,g={},h,f,l,m,n,q,r,t,p;if(null==arguments||0==arguments.length){n=this.Yb?this.Yb.length:0;for(t=0;t<n;t++)q=this.Yb[t].object.ow,q.apply(this.Yb[t].object,[this.Yb[t].event,this.Yb[t].gc,this.Yb[t].context,!0]);this.Yb=[];return this}e=b;c&&c.constructor===String&&(e=c);e.constructor===String?g[e]=d:g=e;for(p in g)if(g.hasOwnProperty(p))for(e=a.X.rj(p),h=0;h<e.length;h+=1)for(f=e[h].event,l=e[h].Ob,n=this.Yb?this.Yb.length:0,t=n-1;0<=t;t-=1)m=this.Yb[t],n=c?c===m.object:!0,q=f?f===m.event:
!0,r=d?g[p]===m.gc:!0,m=l?l===m.Ob:!0,n&&q&&r&&m&&(q=this.Yb[t].object.ow,q.apply(this.Yb[t].object,[this.Yb[t].event,this.Yb[t].gc,this.Yb[t].context,!0]),this.Yb.splice(t,1));return this}};a.X.bind=a.X.on;a.X.unbind=a.X.off;a.X.v={ADD:"add",REMOVE:"remove",RESET:"reset",REFRESH:"refresh",SORT:"sort",CHANGE:"change",DESTROY:"destroy",ALLREMOVED:"allremoved",REQUEST:"request",SYNC:"sync",ERROR:"error",INVALID:"invalid",ALL:"all"};o_("Events.EventType",a.X.v,a);a.X.ip=function(a,b){var d,e=b||this;
for(d in e)"function"===typeof e[d]&&(a[d]=e[d]);a.ic={};a.Yb=[]};a.X.AE=function(a,b,d,e){var g,h,f,l;f=this.Yu(a,b);for(l in f)if(f.hasOwnProperty(l))for(a=this.rj(l),b=0;b<a.length;b+=1)g=a[b].event,h=a[b].Ob,void 0===this.ic&&(this.ic=[]),void 0===this.ic[g]&&(this.ic[g]=[]),this.ic[g].push({gc:f[l],context:d,Ob:h,Jh:!0,fired:!1,Li:e});return this};a.X.lG=function(a){return a.Jh?a.fired?!1:a.fired=!0:!0};a.X.Hb=function(c,b){var d=this.rj(b),e,g,h,f,l,m;f=[];for(e=0;e<d.length;e+=1)g=d[e].event,
h=d[e].Ob,f.push({event:g,Ob:h});for(e=0;e<f.length;e+=1){l=this.Gq(this.ic,a.X.v.ALL);d=a.X.Gq(this.ic,f[e].event,!1);for(g=0;g<(d?d.length:0);g+=1)d[g].Ob===f[e].Ob&&d[g].gc&&(h=Array.prototype.slice.call(arguments),d&&d[g]&&d[g].Jh&&this.uF(a.X.Gq(this.ic,f[e].event,!0),d[g]),d&&d[g]&&this.lG(d[g])&&(m=d[g].gc,c&&!d[g].tI||m.apply(d[g].context||this,h.slice(2))));for(g=0;g<(l?l.length:0);g+=1)h=Array.prototype.slice.call(arguments),0<h.length&&(h[1]=f[e].Ob?f[e].event+":"+f[e].Ob:f[e].event),l&&
l[g]&&l[g].gc&&this.lG(l[g])&&(m=l[g].gc,c&&!l[g].tI||m.apply(l[g].context||this,h.slice(1))),l&&l[g]&&l[g].Jh&&this.uF(this.Gq(this.ic,a.X.v.ALL,!0),l[g])}return this};a.X.Wg=function(c,b,d,e,g){var h,f,l,m;c=this.Yu(c,b);for(h in c)if(c.hasOwnProperty(h))for(b=this.rj(h),f=0;f<b.length;f+=1)l=b[f].event,m=b[f].Ob,void 0===this.ic&&(this.ic=[]),void 0===this.ic[l]&&(this.ic[l]=[]),m={gc:c[h],context:d,Ob:m,Li:e,tI:g},-1===this.cu(this.ic[l],m,a.X.YQ)&&this.ic[l].push(m);return this};a.X.ow=function(a,
b,d,e){var g,h;if(null==arguments||0==arguments.length)return this.ic={},this;if(null==a)return this.tF(a,b,d,e),this;g=this.Yu(a,b);for(h in g)g.hasOwnProperty(h)&&this.tF(h,g[h],d,e);return this};a.X.Yu=function(a,b){var d={};a.constructor===String?d[a]=b:d=a;return d};a.X.tF=function(c,b,d,e){var g=[],h,f,l,m,n,q,r,t;if(c)g=a.X.rj(c);else if(void 0!==this.ic)for(f in this.ic)this.ic.hasOwnProperty(f)&&g.push({event:f});for(c=0;c<g.length;c+=1)if(f=g[c].event,l=g[c].Ob,void 0!==this.ic&&this.ic[f]instanceof
Array){m=this.ic[f];for(h=m.length-1;0<=h;h-=1)n=void 0===b||null===b||m[h].gc==b,q=void 0===d||null===d||m[h].context==d,r=void 0===l||null===l||m[h].Ob==l,t=void 0===e||null===e||m[h].Li==e,n&&q&&r&&t&&m.splice(h,1);0===m.length&&delete this.ic[f]}};a.X.uF=function(a,b){var d,e,g,h,f,l;for(d=a.length-1;0<=d;d-=1)e=void 0===b.gc||null===b.gc||a[d].gc==b.gc,g=void 0===b.context||null===b.context||a[d].context==b.context,h=void 0===b.Ob||null===b.Ob||a[d].Ob==b.Ob,f=void 0===b.Li||null===b.Li||a[d].Li==
b.Li,l=void 0===b.Jh||null===b.Jh||a[d].Jh==b.Jh,e&&g&&h&&f&&l&&a.splice(d,1)};a.X.rj=function(a){a=a?a.split(" "):[];var b=[],d,e,g;for(d=0;d<a.length;d+=1)e=a[d].split(":"),g=e[0],e=1<e.length?e[1]:null,b.push({event:g,Ob:e});return b};a.X.YQ=function(a,b){return a.gc===b.gc&&a.Ob===b.Ob&&a.context===b.context&&a.Li===b.Li&&a.Jh===b.Jh};a.X.aE=function(a,b){return a.event===b.event&&a.Ob===b.Ob&&a.context===b.context&&a.object===b.object};a.X.cu=function(a,b,d){var e;if(void 0===a)return-1;for(e=
0;e<a.length;e+=1)if(d(a[e],b))return e;return-1};a.X.Gq=function(a,b,d){if(a&&a[b]instanceof Array){if(d)return a[b];d=[];var e;for(e=0;e<a[b].length;e++)d.push(a[b][e]);return d}return null};a.q=function(c,b){a.q._init(this,c,b,null)};o_("Model",a.q,a);a.b.sa(a.q,a.b,"Model.Model");a.q.prototype.Init=function(){a.q.t.Init.call(this)};a.q.prototype.attributes={};a.b.g("Model.prototype.attributes",{attributes:a.q.prototype.attributes});a.q.prototype.uc={};a.b.g("Model.prototype.defaults",{uc:a.q.prototype.uc});
a.q.prototype.id=null;a.b.g("Model.prototype.id",{id:a.q.prototype.id});a.q.prototype.Se=null;a.b.g("Model.prototype.idAttribute",{Se:a.q.prototype.Se});a.q.prototype.zJ=null;a.b.g("Model.prototype.urlRoot",{zJ:a.q.prototype.zJ});a.q.prototype.Of=null;a.b.g("Model.prototype.customURL",{Of:a.q.prototype.Of});a.q.Ov=0;a.q._init=function(c,b,d,e){var g=null,h;if(!a.q.yn){c.Init();a.X.ip(c);c.Dk();c.qy={};c.Bs=!1;c.index=-1;d=d||{};c.attributes={};c.defaults&&(c.attributes=a.q.fh(a.q.Zc(c.defaults)?c.defaults():
c.defaults,null));for(g in e)e.hasOwnProperty(g)&&(c[g]=e[g]);if(b)if(e=d.parse,a.q.Zc(e)&&(c.parse=e),h=a.q.fh(b,c.attributes),h=e?c.parse(h):h,null==h||void 0===h)c.attributes={};else for(g in h)h.hasOwnProperty(g)&&c.kl(g,h[g],!1,!1,d);c.kp();c.km(d.collection);d.customURL&&(c.customURL=d.customURL);d.url&&(c.url=d.url);d.urlRoot&&(c.urlRoot=d.urlRoot);c.initialize&&c.initialize(b,d);c.Xg()}};a.q.extend=function(c,b){a.q.yn=!0;var d,e;d=new a.q;a.q.yn=!1;a.X.ip(d,this.prototype);c=c||{};for(e in c)c.hasOwnProperty(e)&&
(d[e]=c[e]);var g;g=c&&c.constructor&&c.hasOwnProperty("constructor")?c.constructor:function(b,d){a.q._init(this,b,d,c)};g.prototype=d;g.extend=a.q.extend;g.prototype.constructor=g;a.X.ip(g,this);if(b)for(e in b)b.hasOwnProperty(e)&&(g[e]=b[e]);return g};o_("Model.extend",a.q.extend,a);a.q.prototype.Hb=function(){};a.q.prototype.kp=function(){this.mk()||(this.cid="id"+a.q.Ov,a.q.Ov+=1)};a.q.prototype.mk=function(){return this.cid};a.q.prototype.Ts=function(a){this.index=a};a.q.prototype.Us=function(a){this.RW=
a};a.q.prototype.lp=function(a){var b=this.ry;this.ry=a;return b};a.q.prototype.TJ=function(c,b,d){var e,g=!1,h=a.fb.pd(b),f,l=!1;for(e in c.attributes)c.attributes.hasOwnProperty(e)&&(f=this.attributes[e]!=c.attributes[e],h?e===b&&f&&(g=!0):f&&(g=!0),f&&(l=!0,this.attributes[e]=c.attributes[e],this.Dt(e,c.attributes[e]),this.vq(e,this.attributes[e],null,d)));this.Xg();l&&this.wq(null,d);return g};a.q.xj=function(a){var b;if(a&&a instanceof Object)for(b in a)if(a.hasOwnProperty(b))return!0;return!1};
a.q.prototype.km=function(a){null==a?delete this.collection:this.collection=a};a.q.prototype.hp=function(){return this.collection};a.q.prototype.vq=function(c,b,d,e){null!=c&&this.Hb(e,a.X.v.CHANGE+":"+c,this,b,d)};a.q.prototype.wq=function(c,b){this.Hb(b,a.X.v.CHANGE,this,c,null)};a.q.prototype.Xg=function(){var a=this.dv();this.id=null!=this.attributes?this.attributes[a]:null};a.q.prototype.Nw=function(c,b,d){var e=a.b.ej(this.attributes[c],b);return d||!e?(this.attributes[c]=b,this.Xg(),!e):!1};
a.q.prototype.Dk=function(){this.changed={}};a.q.prototype.Dt=function(a,b){this.changed[a]=b};a.q.prototype.kl=function(c,b,d,e,g){if(null==c)return!0;var h={},f,l=this.Bs;g=a.q.dq(g);if(e)for(f in c)c.hasOwnProperty(f)&&(h[f]=c[f]);else h[c]=b;g=g||{};if(!this.Mm(h,{validate:g.validate},!1))return!1;l||(this.Dk(),this.ko=[]);this.Bs||(this.qy=a.q.fh(this.attributes,null));this.Bs=!0;for(f in h)h.hasOwnProperty(f)&&(this.Nw(f,h[f],d)?(this.Dt(f,h[f]),this.ko.push(f)):delete h[f]);c=g.silent;for(f in h)h.hasOwnProperty(f)&&
(!c&&(0<this.ko.length||l&&-1===this.ko.indexOf(f))&&(this.RI=!0),this.vq(f,h[f],g,c));if(l)return!0;if(!c&&!l)for(;this.RI;)this.RI=!1,this.wq(g,c);this.Bs=!1;return!0};a.q.prototype.clear=function(c){var b,d={silent:!0},e;c=c||{};e=c.silent;d.validate=c.validate;this.Dk();for(b in this.attributes)if(this.attributes.hasOwnProperty(b)){if(!this.Rr(b,d,!0))return!1;this.Hb(e,a.X.v.CHANGE+":"+b,this,void 0,null)}this.attributes={};this.Xg();this.vq(null,null,null,e);this.wq(null,e);return this};a.b.g("Model.prototype.clear",
{clear:a.q.prototype.clear});a.q.fh=function(c,b){var d;if(null===c)return null;b=b||{};var e=!1;for(d in c)if(e=!0,c.hasOwnProperty(d))if("object"!==typeof c[d])b.hasOwnProperty(d)?void 0!==c[d]&&(b[d]=c[d]):b[d]=c[d];else if(a.q.fm(c[d]))if(null===c[d])b[d]=null;else if(b[d]=[],0===c[d].length)b[d]=c[d];else for(var g=0;g<c[d].length;g++)b[d].push(a.q.fh(c[d][g],null));else b[d]=a.q.fh(c[d],null);return e||"object"===typeof c?b:c};a.q.prototype.clone=function(){var c=new this.constructor,b;for(b in this)this.hasOwnProperty(b)&&
this[b]!==this.attributes&&(c[b]=this[b]);c.attributes=a.q.fh(this.attributes,null);delete c.cid;c.kp();c.Xg();return c};a.b.g("Model.prototype.clone",{clone:a.q.prototype.clone});a.q.prototype.nk=function(a,b){var d=this.ye();if(void 0!==d&&d==a)return!0;d=this.cid;return void 0!==d&&d==b?!0:!1};a.q.prototype.set=function(c,b,d){var e={},g=!1,h,f=!0;if(arguments&&0<arguments.length)if(1<arguments.length&&arguments[arguments.length-1]&&(g=!0,e=arguments[arguments.length-1]||{}),a.q.xj(c))if(e.unset)for(h in c)c.hasOwnProperty(h)&&
this.Rr(h,null,!1);else this.kl(c,null,!0,!0,e)||(f=!1);else for(h=0;h<arguments.length;h+=2)if(void 0!==arguments[h]||h<arguments.length-1||!g&&h===arguments.length-1)e.unset?this.Rr(arguments[h],null,!1):this.kl(arguments[h],arguments[h+1],!1,!1,e)||(f=!1);return f?this:!1};a.b.g("Model.prototype.set",{set:a.q.prototype.set});a.q.prototype.xJ=function(a,b){return this.Rr(a,b,!1)};a.b.g("Model.prototype.unset",{xJ:a.q.prototype.xJ});a.q.prototype.Rr=function(a,b,d){b=b||{};var e=b.silent,g={};if(this.has(a)){if(!this.Mm(g,
b,!1))return!1;d||this.Dk();delete this.attributes[a];this.Dt(a,void 0);this.vq(a,null,null,e);this.wq(null,e)}this.Xg();return!0};a.q.prototype.get=function(a){return this.attributes[a]};a.b.g("Model.prototype.get",{get:a.q.prototype.get});a.q.prototype.has=function(a){return void 0!==this.attributes[a]&&null!==this.attributes[a]};a.b.g("Model.prototype.has",{has:a.q.prototype.has});a.q.prototype.fetch=function(c){c=c||{};var b=c.success,d=c.error,e=this,g;g=a.q.dq(c);g.error=function(b,g,l){e.Hb(!1,
a.X.v.ERROR,e,b,c);d&&d.call(e,arguments)};g.success=function(d){a.q.xq(e,d,g);a.q.Zc(this.parse)&&this.set(this.parse(d),g);b&&b.call(e,this,d,c)};a.q.vn("read",this,g)};a.b.g("Model.prototype.fetch",{fetch:a.q.prototype.fetch});a.q.prototype.parse=function(a){return a};a.q.prototype.url=function(){var c=this.kD(),b=this.ye();if(c)return b?c+"/"+encodeURIComponent(b):c;if(c=this.collection)return c=a.q.Zc(c.url)?c.url():c.url,b&&c?(b="/"==a.q.FP(c)?"":"/",c+b+encodeURIComponent(this.ye())):c;throw"No URL defined";
};a.b.g("Model.prototype.url",{url:a.q.prototype.url});a.q.prototype.keys=function(){var a,b=[];for(a in this.attributes)this.attributes.hasOwnProperty(a)&&b.push(a);return b};a.b.g("Model.prototype.keys",{keys:a.q.prototype.keys});a.q.prototype.values=function(){var a,b=[];for(a in this.attributes)this.attributes.hasOwnProperty(a)&&b.push(this.get(a));return b};a.b.g("Model.prototype.values",{values:a.q.prototype.values});a.q.prototype.pairs=function(){var a,b=[],d;for(a in this.attributes)this.attributes.hasOwnProperty(a)&&
(d=[],d.push(a),d.push(this.get(a)),b.push(d));return b};a.b.g("Model.prototype.pairs",{pairs:a.q.prototype.pairs});a.q.prototype.QI=function(a){var b=[],d,e,g={};if(a instanceof Array)b=a;else for(d=0;d<arguments.length;d++)b.push(arguments[d]);for(e in this.attributes)this.attributes.hasOwnProperty(e)&&-1==b.indexOf(e)&&(g[e]=this.get(e));return g};a.b.g("Model.prototype.omit",{QI:a.q.prototype.QI});a.q.prototype.SI=function(a){var b=[],d,e={};if(a instanceof Array)b=a;else for(d=0;d<arguments.length;d++)b.push(arguments[d]);
for(d=0;d<b.length;d++)this.attributes.hasOwnProperty(b[d])&&(e[b[d]]=this.get(b[d]));return e};a.b.g("Model.prototype.pick",{SI:a.q.prototype.SI});a.q.prototype.wI=function(){var a,b={},d;for(a in this.attributes)this.attributes.hasOwnProperty(a)&&(d=this.get(a),b[d]=a);return b};a.b.g("Model.prototype.invert",{wI:a.q.prototype.wI});a.q.FP=function(a){return a.charAt(a.length-1)};a.q.prototype.OT=function(){var a=this.kD();return a?a:this.hp()?this.hp().url:null};a.q.prototype.kD=function(){return a.q.Zc(this.urlRoot)?
this.urlRoot():this.urlRoot};a.q.prototype.parseSave=function(a){return a};a.q.prototype.isValid=function(){var a={};a.validate=this.validate;return this.Mm(this.attributes,a,!1)};a.b.g("Model.prototype.isValid",{isValid:a.q.prototype.isValid});a.q.KR=function(a,b){a=a||{};return void 0!==a.validate&&null!==a.validate?a.validate:b};a.q.prototype.Mm=function(c,b,d){b=b||{};var e=this.validate;return e&&a.q.KR(b,d)&&(this.validationError=e.call(this,c,b))?(this.Hb(!1,a.X.v.INVALID,this,this.validationError,
b),!1):!0};a.q.MS=function(c){var b=!1,d={},e,g={};if(c&&0<c.length){1<c.length&&c[c.length-1]&&a.q.xj(c[c.length-1])&&(b=!0,d=c[c.length-1]||{});if(null==c[0])return{attributes:null,options:d};if(a.q.xj(c[0]))for(e in c[0])c[0].hasOwnProperty(e)&&(g[e]=c[0][e]);else for(e=0;e<c.length;e+=2)if(void 0!==c[e]||e<c.length-1||!b&&e===c.length-1)g[c[e]]=c[e+1]}return{attributes:g,options:d}};a.q.dq=function(a){var b={},d;a=a||{};for(d in a)a.hasOwnProperty(d)&&(b[d]=a[d]);return b};a.q.prototype.save=
function(c,b){var d,e,g,h,f,l;d=a.q.MS(arguments);var m,n,q;q=void 0===c?void 0:d.attributes;m=a.q.dq(d.options);m.wait||this.set(q);if(!this.Mm(this.attributes,m,!0))return!1;d=void 0===m.forceNew?!1:m.forceNew;h=this;f=m.error;l=m.patch;m.error=function(c,d,e){h.Hb(!1,a.X.v.ERROR,h,c,b);f&&f.call(h,arguments)};m.saveAttrs=m.wait?this.TM(q):this.attributes;n=this.attributes;this.attributes=m.saveAttrs;m.saveAttrs=this.toJSON();this.attributes=n;if(!d&&!this.vs())return e=m.success,m.success=function(c){var d;
c&&(d=a.q.Zc(this.parse)?this.parse(c):c,h.attributes=d,h.Xg());a.q.xq(h,c,m);e&&e.call(a.q.ag(m,h),h,c,b);h.Dk()},m.attrs=void 0===q?void 0:l?q:m.saveAttrs,a.q.vn(l?"patch":"update",this,m);g=a.q.cD(m);m.success=function(c){var d;if(c){d=a.q.Zc(h.parse)?h.parse(c):c;if(!h.Mm(d,m,!0))return;h.attributes=d;h.Xg()}m.wait&&h.set(q);a.q.xq(h,c,m);g&&g.call(a.q.ag(m,h),h,c,b);h.Dk()};m.attrs=m.saveAttrs;m.parse=!0;return a.q.vn("create",this,m)};a.b.g("Model.prototype.save",{save:a.q.prototype.save});
a.q.prototype.TM=function(a){var b={},d;for(d in this.attributes)this.attributes.hasOwnProperty(d)&&(b[d]=this.attributes[d]);for(d in a)a.hasOwnProperty(d)&&(b[d]=a[d]);return b};a.q.fm=function(a){return null!=a&&a.constructor===Array};a.q.Zc=function(a){return a instanceof Function};a.q.bz=function(a){return a&&a.hasOwnProperty("value")&&a.hasOwnProperty("comparator")};a.q.prototype.$Q=function(c){for(var b in c)if(c.hasOwnProperty(b)){if(!this.attributes.hasOwnProperty(b))return!1;for(var d=a.q.fm(c[b])?
c[b]:[c[b]],e=0;e<d.length;e++)if(a.q.bz(d[e])){var g=d[e].comparator,h=d[e].value;if(a.fb.pd(g))throw Error("String comparator invalid for local where/findWhere");if(!g(this,b,h))return!1}else if(c[b]!==this.attributes[b])return!1}return!0};a.q.prototype.HJ=function(a){a=a.constructor===Array?a:[a];var b;for(b=0;b<a.length;b++)if(this.$Q(a[b]))return!0;return!1};a.q.cD=function(a){return null!=a&&a.success?a.success:null};a.q.ag=function(a,b){return void 0!==a&&void 0!==a.context?a.context:b};a.q.prototype.vs=
function(){return void 0==this.ye()};a.b.g("Model.prototype.isNew",{vs:a.q.prototype.vs});a.q.prototype.dv=function(){return this.idAttribute||"id"};a.q.prototype.ye=function(){return this.id};a.q.prototype.vx=function(c){if(c){var b={},d;for(d in c)c.hasOwnProperty(d)&&(a.b.ej(c[d],this.attributes[d])||(b[d]=c[d]));return a.b.isEmpty(b)?!1:b}return a.b.isEmpty(this.changed)?!1:this.changed};a.b.g("Model.prototype.changedAttributes",{vx:a.q.prototype.vx});a.q.prototype.Ux=function(c){return void 0!==
c?a.q.xj(this.changed)&&this.changed.hasOwnProperty(c):a.q.xj(this.changed)};a.b.g("Model.prototype.hasChanged",{Ux:a.q.prototype.Ux});a.q.prototype.destroy=function(c){c=c||{};var b=c.wait,d,e=c.error,g=this,h,f;f=a.q.dq(c);d=a.q.cD(f);f.success=function(e){b&&g.Lu();a.q.xq(g,e,f);d&&d.call(a.q.ag(f,g),g,e,c)};f.error=function(c,b,d){g.Hb(!1,a.X.v.ERROR,g,c,f);e&&e.call(g,arguments)};if(!this.vs())return h=a.q.vn("delete",this,f),b||this.Lu(),h;b||this.Lu();d&&d.call(a.q.ag(f,g),g,null,c);return!1};
a.b.g("Model.prototype.destroy",{destroy:a.q.prototype.destroy});a.q.prototype.nC=function(c,b,d,e){this.Hb(e,a.X.v.REQUEST,c,b,d)};a.q.prototype.Lu=function(){this.Hb(!1,a.X.v.DESTROY,this,this.collection,null)};a.q.xq=function(c,b,d){c.Hb(!1,a.X.v.SYNC,c,b,d)};a.q.prototype.toJSON=function(){var a={},b;for(b in this.attributes)this.attributes.hasOwnProperty(b)&&(Array.isArray(this.attributes[b])?a[b]=this.attributes[b].slice(0):a[b]=this.attributes[b]);return a};a.b.g("Model.prototype.toJSON",{toJSON:a.q.prototype.toJSON});
a.q.prototype.previous=function(a){return this.qy[a]};a.b.g("Model.prototype.previous",{previous:a.q.prototype.previous});a.q.prototype.XI=function(){return this.qy};a.b.g("Model.prototype.previousAttributes",{XI:a.q.prototype.XI});a.q.prototype.sync=function(a,b,d){return window.oj.sync(a,b,d)};a.q.vn=function(a,b,d){d=d||{};b.oauth&&(d.oauthHeader=b.oauth.getHeader());!d.dataType&&b.dataType&&(d.dataType=b.dataType);!d.jsonpCallback&&b.jsonpCallback&&(d.jsonpCallback=b.jsonpCallback);if("create"===
a||"patch"===a||"update"===a)d.py=b.parseSave.call(b,"patch"===a?b.changed:d.saveAttrs);return b.sync(a,b,d)};a.AX=function(c,b,d){function e(a){b.nC(b,a,d,d.silent);return a}d=d||{};var g,h=d.success,f=d.error;g=b.customURL;if("create"===c.valueOf())return g=new a.Fb(b.OT(),g),e(g.hV(d.py,f,d,b));if("read"===c.valueOf()){if(b instanceof a.q)return g=new a.Fb(b.url(),g),e(g.kW(h,f,b.ye(),d,a.q.ag(d,b)));g=new a.Fb(b.NJ(d),g);return e(g.lW(h,f,d,b))}g=new a.Fb(b.url(),g);var l=null;b instanceof a.q&&
(l=b.ye());return"update"===c.valueOf()?e(g.yJ(h,l,d.py,f,d,b,!1)):"patch"===c.valueOf()?e(g.yJ(h,l,d.py,f,d,b,!0)):"delete"===c.valueOf()?e(g.SV(l,f,d,b)):null};o_("sync",a.AX,a);a.q.ZU=function(a){if(!a.url)throw Error("The url property or function must be specified");};a.ajax=function(){arguments&&0<arguments.length&&a.q.ZU(arguments[0]);return f.ajax.apply(window.oj,arguments)};a.l=function(c,b){a.l.yn||a.l._init(this,c,b,null)};o_("Collection",a.l,a);a.l.prototype.Ro=null;a.b.g("Collection.prototype.model",
{Ro:a.l.prototype.Ro});a.l.prototype.length=0;a.b.g("Collection.prototype.length",{length:a.l.prototype.length});a.l.prototype.KI=[];a.b.g("Collection.prototype.models",{KI:a.l.prototype.KI});a.l.prototype.url=null;a.b.g("Collection.prototype.url",{url:a.l.prototype.url});a.l.prototype.Of=function(){return null};a.b.g("Collection.prototype.customURL",{Of:a.l.prototype.Of});a.l.prototype.yH=function(){return null};a.b.g("Collection.prototype.customPagingOptions",{yH:a.l.prototype.yH});a.l.prototype.FI=
0;a.b.g("Collection.prototype.lastFetchSize",{FI:a.l.prototype.FI});a.l.prototype.hasMore=!1;a.b.g("Collection.prototype.hasMore",{hasMore:a.l.prototype.hasMore});a.l.prototype.rJ=0;a.b.g("Collection.prototype.totalResults",{rJ:a.l.prototype.rJ});a.l.prototype.EI=0;a.b.g("Collection.prototype.lastFetchCount",{EI:a.l.prototype.EI});a.l.prototype.JI=-1;a.b.g("Collection.prototype.modelLimit",{JI:a.l.prototype.JI});a.l.prototype.offset=0;a.b.g("Collection.prototype.offset",{offset:a.l.prototype.offset});
a.l.prototype.Gx=-1;a.b.g("Collection.prototype.fetchSize",{Gx:a.l.prototype.Gx});a.l.prototype.Wl=1;a.b.g("Collection.prototype.sortDirection",{Wl:a.l.prototype.Wl});a.l.prototype.lf=null;a.b.g("Collection.prototype.comparator",{lf:a.l.prototype.lf});a.l.prototype.Tf=!0;a.b.g("Collection.prototype.sortSupported",{Tf:a.l.prototype.Tf});a.b.sa(a.l,a.b,"Collection.Collection");a.l.prototype.Init=function(){a.l.t.Init.call(this)};a.l.extend=function(c){a.l.yn=!0;var b=new a.l;a.l.yn=!1;var d;d=c&&c.constructor&&
c.hasOwnProperty("constructor")?c.constructor:function(b,d){a.l._init(this,b,d,c)};d.prototype=b;return d.prototype.constructor=d};o_("Collection.extend",a.l.extend,a);a.l._init=function(c,b,d,e){var g,h;c.Init();a.X.ip(c);if(e)for(g in e)e.hasOwnProperty(g)&&(c[g]=e[g]);d=d||{};h=["url","comparator","model",a.l.cd,"modelLimit","customURL"];for(g=0;g<h.length;g++)d.hasOwnProperty(h[g])&&void 0!==d[h[g]]&&(c[h[g]]=d[h[g]]);void 0===c.cn(null)&&c.Is(-1);void 0===c.modelLimit&&c.Dy(-1);c.hasMore=!1;
c.sf=0;c.Lj([]);d.parse&&(b=c.parse(b));if(null!=b&&void 0!==b)for(h=b instanceof Array?b:[b],g=0;g<h.length;g+=1)c.add(h[g],d);c.oi();e&&e.initialize&&e.initialize.call(c,b,d)};a.l.prototype.on=function(){};a.l.prototype.Wg=function(){};a.l.prototype.Hb=function(){};a.l.prototype.nC=function(c,b,d,e){this.Hb(e,a.X.v.REQUEST,c,b,d)};a.l.prototype.Lj=function(a){this.models=a};a.l.prototype.Cb=function(){return this.models};a.l.prototype.gd=function(){return this.Cb().length};a.l.prototype.xS=function(a){return a<
this.gd()||this.ab()&&(!this.Tk()||0===this.gd())?!1:!0};a.l.prototype.Tk=function(){return void 0!==this.totalResults&&null!=this.totalResults};a.l.prototype.VS=function(a){this.fw(a);this.Cb().push(a);this.sf++;a.Ts(this.gd()-1)};a.l.prototype.aF=function(a){if(a)for(var b=0;b<a.length;b++)a[b]&&this.sf--};a.l.prototype.vG=function(a,b,d){for(var e=a;e<a+b;e++)this.wF(this.Cb()[e]);void 0===d?this.aF(this.Cb().splice(a,b)):(this.aF(this.Cb().splice(a,b,d)),this.fw(d));0>this.sf&&(this.sf=0);this.$E(a)};
a.l.prototype.Vb=function(a){return this.Cb()[a]};a.l.prototype.$E=function(a){this.Cb().forEach(function(b,d){d>=a&&b&&b.Ts(d)})};a.l.prototype.wF=function(a){if(a){var b=a.ry;a=a.RW;b?b.Us(a):this.head=a;a?a.lp(b):this.tail=b}};a.l.prototype.fw=function(a){a.Us(this.head);this.head?this.head.lp(a):this.tail=a;a.lp(null);this.head=a};a.l.prototype.gU=function(a,b){var d=this.Cb()[a];this.wF(d);d||this.sf++;this.Cb()[a]=b;b.Ts(a);this.fw(b)};a.l.prototype.yN=function(a){var b=this.tail,d,e,g=0;for(this.tail=
null;b&&g<a;)d=b.index,(e=this.Cb()[d])&&e.Ux()?(this.tail||(this.tail=b),b=b.ry):(this.sf--,-1<d&&(this.Cb()[d]=void 0),b.Us(null),b=b.lp(null),g++);this.tail||(this.tail=b);0>this.sf&&(this.sf=0);0===this.sf&&(this.tail=this.head=null)};a.l.prototype.Tn=function(){this.sf=0;this.tail=this.head=null};a.l.prototype.ii=function(a){if(this.ab()){var b=this.PC();-1<b&&this.sf+a>b&&this.yN(this.sf+a-b)}};a.l.prototype.clone=function(){return this.uB(!0)};a.b.g("Collection.prototype.clone",{clone:a.l.prototype.clone});
a.l.prototype.uB=function(a){var b=new this.constructor,d;this.ab()&&(b=this.MN(b),b.DF());if(a)for(a=0;a<this.Qc();a+=1)(d=this.Vh(a,null,!0,!1))&&b.bh(d.clone(),{at:a},!0,!1);return b};a.l.prototype.MN=function(c){var b=["totalResults","hasMore",a.l.cd],d,e;for(e=0;e<b.length;e++)d=b[e],c[d]=this[d];return c};a.l.prototype.Qc=function(){return this.length};a.l.prototype.oi=function(){var a=this.gd();this.length=a;this.ab()||(this.totalResults=a)};a.l.prototype.In=function(c,b,d){var e=null;d=d||
{};d.YY=!b;e=c instanceof a.q?c:this.model?a.q.Zc(this.model)?new this.model(c,d):new this.model.constructor(c,d):new a.q(c,d);return d.validate&&e.validate&&(c=e.validate(e.attributes))?(d.validationError=c,this.Hb(!1,a.X.v.INVALID,e,c,d),null):e};a.l.prototype.add=function(a,b){this.ii(1);return this.bh(a,b,!1,(b||{}).deferred)};a.b.g("Collection.prototype.add",{add:a.l.prototype.add});a.l.prototype.bh=function(c,b,d,e){function g(c,e,g,h,f){var k,q=null;!n&&p&&g?(s=g.TJ(e,c.comparator,m),q=g):
(n||(k=c.MC(h))&&d&&l!==k.index&&a.D.warn("Duplicate ID fetched or added without merging, the id \x3d "+k.ye()),void 0===k?(void 0===l?(c.VS(h),r=c.gd()-1,c.Vb(r).kp()):(r=l,c.ab()&&d?c.gU(r,h):c.vG(r,0,h),c.Vb(r).kp(),l+=1),void 0===h.hp()&&h.km(c),c.oi(),c.RR(h),v=!0,q=h):q=k);d&&(b=b||{},b.fillIn=!0);s&&void 0===k&&!u&&void 0===l&&1<c.Qc()&&(-1<r&&(t=c.Vb(r).cid),e={},a.ec.Ne(e,b),e.add=!0,c.sort(e),-1<r&&(r=c.indexOf(c.Ix(t),f)));v&&(h?h.Hb(m,a.X.v.ADD,h,c,b):g.Hb(m,a.X.v.ADD,g,c,b));return q}
function h(c,e,l){var h=c.In(e,!0,b),f=null,m=null;if(null!=h){r=-1;h.Xg();f=e instanceof a.q?e:h;if(l)return n?a.b.ha(function(a){g(c,f,void 0,h,l);a()}):c.sj(f,null,l,!0).then(function(a){m=a.m;a=g(c,f,m,h,l);z.push(a)});!n&&p&&(m=d?c.MC(f):c.get(f));(e=g(c,f,m,h,l))&&z.push(e)}}b=b||{};var f=[],l=b.at,m=b.silent,n=b.force,q,r,t,p=b.merge||!1,u=b.sort,s=!0,v=!1,z=[];c instanceof Array?f=c:f.push(c);if(!d&&(this.ab()||e)){var w=this;return a.b.ha(function(c){function b(a){return d(a+1)}function d(c){return a.b.ha(function(a){h(w,
f[c],!0).then(function(){a(c)})})}var e=d(0);for(q=1;q<f.length;q++)e=e.then(b);e.then(function(){c(a.l.LF(z))})})}for(q=0;q<f.length;q++)h(this,f[q],!1);return a.l.LF(z)};a.l.LF=function(a){return 1===a.length?a[0]:a};a.l.prototype.Lv=function(){var a=this.comparator;return void 0!==a&&null!==a};a.l.prototype.sort=function(c){c=c||{};var b=c.silent,d=this.comparator,e;if(this.Lv()){if(this.ab()){var g=this.totalResults;void 0!==g?this.Lj(Array(g)):(this.Lj([]),this.Tn(),this.oi())}else e=this,this.Cb().sort(function(c,
b){return a.l.lz(c,b,d,e,e)}),this.$E(0);c=c.add?{add:!0}:null;this.Hb(b,a.X.v.SORT,this,c,null)}};a.b.g("Collection.prototype.sort",{sort:a.l.prototype.sort});a.l.en=function(c,b){return c instanceof a.q?c.get(b):a.q.Zc(c[b])?c[b]():c[b]};a.l.lz=function(c,b,d,e,g){var h,f,l;if(a.q.Zc(d)){if(1===d.length){h=d.call(g,c);f=d.call(g,b);h=a.fb.pd(h)?h.split(","):[h];var m=a.fb.pd(f)?f.split(","):[f];for(l=0;l<h.length;l++)if(f=a.l.gh(h[l],m[l],e.sortDirection),0!==f)return f}return d.call(g,c,b)}if(a.fb.pd(d))for(d=
d.split(","),l=0;l<d.length;l++)if(h=a.l.en(c,d[l]),f=a.l.en(b,d[l]),f=a.l.gh(h,f,e.sortDirection),0!==f)return f;return 0};a.l.prototype.jJ=function(c,b){var d=b?b:this.comparator,e;if(!d)return-1;this.Ke("sortedIndex");e=this;return a.l.YO(this.Cb(),c,function(c,b){var f,l;if(a.q.Zc(d)){if(1===d.length){f=d.call(e,c);l=d.call(e,b);f=a.fb.pd(f)?f.split(","):[f];l=a.fb.pd(l)?l.split(","):[l];var m,n;for(n=0;n<f.length;n++)if(m=a.l.gh(f[n],l[n],e.sortDirection),0!==m)return m}return d.call(e,c,b)}return a.fb.pd(d)?
(f=c.get(d),l=b.get(d),a.l.gh(f,l,e.sortDirection)):0})};a.b.g("Collection.prototype.sortedIndex",{jJ:a.l.prototype.jJ});a.l.YO=function(a,b,d){function e(g,f){var k,l;if(g>f)return-1;k=b.mk();l=b.ye();if(a[g].nk(l,k))return g;if(a[f].nk(l,k))return f;k=Math.floor((f+g)/2);return-1===d(a[k],b)?e(g+1,k):1===d(a[k],b)?e(k,f-1):k}return e(0,a.length-1)};a.l.gh=function(a,b,d){if(-1===d){if(a<b)return 1;if(b<a)return-1}else{if(a>b)return 1;if(b>a)return-1}return 0};a.l.prototype.unshift=function(c,b){var d=
{};a.ec.Ne(d,b||{});d.at||(d.at=0);this.ii(1);return this.bh(c,d,!1,d.deferred)};a.b.g("Collection.prototype.unshift",{unshift:a.l.prototype.unshift});a.l.prototype.shift=function(a){var b=this.Rd(a);if(this.ab()||b){var d=this;return this.at(0,a).then(function(b){return d.mi(b,0,a)})}return this.mi(this.at(0),0,a)};a.b.g("Collection.prototype.shift",{shift:a.l.prototype.shift});a.l.prototype.uI=function(a){void 0===a&&(a=1);var b=[],d;for(d=0;d<this.Qc()-a;d+=1)b.push(this.at(d));return b};a.b.g("Collection.prototype.initial",
{uI:a.l.prototype.uI});a.l.prototype.Rd=function(a){return(a||{}).deferred};a.l.prototype.last=function(a,b){var d=this.Rd(b);void 0===a&&(a=1);if(1===a){var e=this.gd();0===e&&(e=a);return 0<e?this.at(e-1,d):null}var g=[],e=this.Qc();if(d||this.ab())return g=e-a,0>g&&(g=0),0===e&&(e=a),this.gm(g,e);for(d=e-a;d<e;d+=1)g.push(this.at(d));return g};a.b.g("Collection.prototype.last",{last:a.l.prototype.last});a.l.prototype.gm=function(c,b){var d=[],e,g=this;return a.b.ha(function(f){function k(a){return l(a+
1)}function l(b){return a.b.ha(function(a){g.vu(b,null).then(function(c){d.push(c);a(b)})})}var m=l(c);for(e=c+1;e<b;e++)m=m.then(k);m.then(function(){f(d)})})};a.l.prototype.DC=function(c){return void 0===c||null===c?this[a.l.cd]:c};a.l.prototype.mN=function(){var c=this.lastFetchCount;if(void 0===c||null===c)c=this[a.l.cd];return void 0===this.offset||null===this.offset?c:this.offset+c};a.l.prototype.next=function(c,b){b=b||{};b[a.l.cd]=this.DC(c);var d=this.mN(),e=this.Qc();if(0===e&&0<b[a.l.cd])d=
0;else if(d>=e)return b.success&&b.success.call(a.q.ag(b,this),this,null,b),null;b.startIndex=d;return this.fetch(b)};a.b.g("Collection.prototype.next",{next:a.l.prototype.next});a.l.prototype.nN=function(a){return void 0===this.offset||null===this.offset?0:this.offset-a};a.l.prototype.previous=function(c,b){b=b||{};if(0===this.offset)return b.success&&this.lastFetchCount&&b.success.call(a.q.ag(b,this),this,null,b),null;b[a.l.cd]=this.DC(c);var d=this.nN(b[a.l.cd]);0>d&&(b[a.l.cd]=this.offset,d=0);
b.startIndex=d;return this.fetch(b)};a.b.g("Collection.prototype.previous",{previous:a.l.prototype.previous});a.l.prototype.Dy=function(a){this.modelLimit=a;this.ii(0)};a.b.g("Collection.prototype.setModelLimit",{Dy:a.l.prototype.Dy});a.l.prototype.PC=function(){return this.modelLimit};a.l.prototype.Is=function(c){this[a.l.cd]=c};a.b.g("Collection.prototype.setFetchSize",{Is:a.l.prototype.Is});a.l.prototype.aJ=function(a,b){var d=this.Rd(b);void 0===a&&(a=1);var e=[];if(this.ab()||d)return this.gm(a,
this.Qc());for(d=a;d<this.Qc();d+=1)e.push(this.at(d));return e};a.b.g("Collection.prototype.rest",{aJ:a.l.prototype.aJ});a.l.prototype.remove=function(c,b){b=b||{};var d=[],e;c instanceof Array?d=c:d.push(c);for(e=d.length-1;0<=e;e-=1)this.mi(d[e],-1,b);this.Hb(b.silent,a.X.v.ALLREMOVED,this,d,b)};a.b.g("Collection.prototype.remove",{remove:a.l.prototype.remove});a.l.prototype.mi=function(c,b,d){d=d||{};c=-1==b?this.sj(c):a.l.nh(b,c);var e=d.silent;b=c.index;if(-1<b){var g=c.m;void 0!==g&&g.hp()===
this&&g.km(null);this.vG(b,1);this.oi();var f={};a.ec.Ne(f,d);f.index=b;void 0!==g&&g.Hb(e,a.X.v.REMOVE,g,this,f);this.OG(g)}return c.m};a.l.prototype.OG=function(a){void 0!==a&&a.off(null,null,this)};a.l.prototype.RR=function(c){c.Wg(a.X.v.ALL,this.hS,this,!1,!0)};a.l.prototype.hS=function(c,b,d,e){c===a.X.v.DESTROY&&this.remove(b);void 0!==d&&d instanceof a.l&&d!==this||(Array.prototype.slice.call(arguments),this.Hb(e&&e.silent,c,b,d,e))};a.l.prototype.refresh=function(c){c=c||{};var b=this;return a.b.ha(function(d,
e){if(b.ab()){var g=b.totalResults;void 0!==g&&(b.Lj(Array(g)),b.Tn());b.Hb(void 0!==c.silent&&c.silent,a.X.v.REFRESH,b,c,null);d()}else b.reset(null,{silent:!0}),b.fetch({success:function(c,e,g){b.Hb(void 0!==g.silent&&g.silent,a.X.v.REFRESH,b,g,null);d({collection:c,response:e,options:g})},error:function(a,c,d){e({collection:b,xhr:a,status:c,error:d})}})})};a.b.g("Collection.prototype.refresh",{refresh:a.l.prototype.refresh});a.l.prototype.reset=function(c,b){b=b||{};b.previousModels=this.Cb();
this.Cb().forEach(function(a){a&&(this.OG(a),a.km(null))},this);this.Lj([]);this.Tn();if(c)if(b.parse&&(c=this.parse(c)),c instanceof Array){this.ii(c.length);for(var d=0;d<c.length;d+=1)this.bh(c[d],b,!0,!1)}else this.ii(1),this.bh(c,b,!0,!1);this.oi();this.Hb(void 0!==b.silent&&b.silent,a.X.v.RESET,this,b,null)};a.b.g("Collection.prototype.reset",{reset:a.l.prototype.reset});a.l.prototype.at=function(a,b){return this.Vh(a,b,!1,this.Rd(b))};a.b.g("Collection.prototype.at",{at:a.l.prototype.at});
a.l.prototype.Vh=function(a,b,d,e){return 0>a||this.xS(a)?null:d||!this.ab()&&!e?this.Vb(a):this.vu(a,b)};a.l.prototype.vu=function(c,b){var d=this,e=d.Vb(c);return void 0===e?a.b.ha(function(e,f){var k={};a.ec.Ne(k,b||{});k.context=d;k.startIndex=c;k.error=function(a,b){f(b)};d.rq(k,-1,!1).then(function(){e(d.Vb(c))},function(a){f(a)})}):a.b.ha(function(a){a(e)})};a.l.prototype.Ix=function(a){var b=null;this.Cb().some(function(d){return void 0!==d&&a===d.cid?(b=d,!0):!1});if(b)return b;if(this.ab())throw Error("Not found locally and not supported by server for virtual collections");
return null};a.b.g("Collection.prototype.getByCid",{Ix:a.l.prototype.Ix});a.l.prototype.get=function(c,b){var d=this.sj(c,b,this.Rd(b));if(d){if(f.isFunction(d.then))return a.b.ha(function(a){d.then(function(b){a(b.m)})});if(this.ab())return a.b.ha(function(a){a(d.m)});if(d.hasOwnProperty("m"))return d.m}return null};a.b.g("Collection.prototype.get",{get:a.l.prototype.get});a.l.prototype.MC=function(a){return(a=this.NC(a))?a.m:null};a.l.prototype.NC=function(c){var b=c;c instanceof a.q?(b=c.mk(),
c=c.ye()):void 0!==c&&null!=c&&void 0!==c.id&&(c=c.id);var d=null;this.Cb().some(function(e,g){return void 0!==e&&e.nk(c,b)?(d=a.l.nh(g,e),!0):!1});return d?d:a.l.nh(-1,void 0)};a.l.prototype.sj=function(c,b,d,e){var g=c;void 0===e&&(e=!1);c instanceof a.q?(g=c.mk(),c=c.ye()):void 0!==c&&null!=c&&void 0!==c.id&&(c=c.id);var f=null;this.Cb().some(function(b,d){return void 0!==b&&b.nk(c,g)?(f=a.l.nh(d,b),!0):!1});if(f)return d?a.b.ha(function(a){a(f)}):f;if(this.ab()){if(void 0===c&&void 0!==g)return a.b.ha(function(b){b(a.l.nh(-1,
void 0))});var k=this;return a.b.ha(function(d,l){var f={};a.ec.Ne(f,b||{});f.context=k;f.startID=c;f.error=function(a,b){l(b)};k.rq(f,-1,e).then(function(b){if(null!=b){b=k.mv();var e=k.Vb(b);void 0!==e&&e.nk(c,g)?d(a.l.nh(b,e)):d(a.l.nh(-1,void 0))}else d(a.l.nh(-1,void 0))},function(a){l(a)})})}var l=a.l.nh(-1,void 0);return d?a.b.ha(function(a){a(l)}):l};a.l.nh=function(a,b){return{index:a,m:b}};a.l.prototype.parse=function(a){var b;if(a instanceof Array||!a)return a;for(b in a)if(a.hasOwnProperty(b)&&
a[b]instanceof Array)return a[b];return a};a.l.prototype.Js=function(c,b){var d=this.gv(c,b);if(d.start===c&&d.count===b)return a.b.ha(function(a){a(d)});var e=this.PC();-1<e&&e<b&&(this.modelLimit=b);var g=this;return a.b.ha(function(a,d){g.hG(c,b,-1,{start:c,count:b},a,d,!0)})};a.b.g("Collection.prototype.setRangeLocal",{Js:a.l.prototype.Js});a.l.prototype.hG=function(c,b,d,e,g,f,k){var l=this,m=this.iv(c,b);this[a.l.cd]&&this[a.l.cd]>m-c&&(m=this[a.l.cd]+c);!this.Tk()&&m<c+b&&(m=c+b);var n=this.GC(c,
m);n>c&&(c=n,m=this.iv(n,b));m=this.ab()?{context:this,startIndex:c,fetchSize:m-c}:{context:this};m.error=function(a,b){f(b)};this.rq(m,d,-1<d).then(function(){var a=l.gv(e.start,e.count);if(k&&l.Tk()&&a.count<e.count){var d=a.start+a.count,m=c+b;m<l.totalResults?l.hG(m,b,d,e,g,f,k):g(a)}else g(a)},function(a){f(a)})};a.l.prototype.iv=function(a,b){var d=this.gd();return 0===d?a+b:a+b>d?d:a+b};a.l.prototype.ay=function(a,b){var d=this.gv(a,b);return a===d.start&&b===d.count};a.b.g("Collection.prototype.isRangeLocal",
{ay:a.l.prototype.ay});a.l.prototype.gv=function(a,b){if(!this.ab())return 0<this.gd()?{start:a,count:b}:{start:a,count:0};var d=this.iv(a,b);if(!this.Tk()&&d<a+b||0===d)return{start:a,count:0};d=this.GC(a,d);return-1<d?{start:a,count:d-a}:{start:a,count:b}};a.l.prototype.GC=function(a,b){for(var d=a;d<b;d++)if(void 0===this.Vb(d))return d;return-1};a.l.prototype.fetch=function(a){return this.rq(a,-1,!1)};a.b.g("Collection.prototype.fetch",{fetch:a.l.prototype.fetch});a.l.prototype.rq=function(c,
b,d){function e(a,b,c){a.ab()?c||a.DF():b.add||b.Oy||a.reset()}var g=c||{},f=g.success,k;g.set&&(g.Oy=g.set?!0:!1);void 0===g.parse&&(g.parse=!0);k=this;g.success=function(l){k.hU(l,c);var m=k.parse(l,c),n=null;if(g.add||k.model){e(k,g,d);try{r=!1,-1===b&&(r=!0,b=k.mv()),n=k.XO(m,b,r,g)}catch(q){g.error&&g.error.call(a.q.ag(c,k),k,q,c);return}}else if(!d)if(k.ab()){e(k,g,d);var r=!1;-1===b&&(r=!0,b=k.mv());n=k.WS(m,b,r)}else g.Oy?k.Lw(m,!1,g,!1):k.reset(m);k.ab()&&n&&(k.lastFetchCount=n.length);k.Hb(!1,
a.X.v.SYNC,k,l,g);f&&f.call(a.q.ag(c,k),k,l,g)};return this.hC(g)};a.l.prototype.WS=function(a,b,d){var e;if(a){e=a instanceof Array?a:[a];a={};d&&this.ii(e.length);d=this.ab();for(var g=null,f=0;f<e.length;f+=1)d&&(a={at:b},g=this.Vh(b,null,!0,!1)),a.silent=!0,this.bh(e[f],a,!0,!1),this.Vh(b,null,!0,!1)!==g&&b++}return e};a.l.prototype.XO=function(c,b,d,e){e=e||{};var g=e.parse,f=a.l.CB(this);if(c){var k=c instanceof Array?c:[c];c={};d&&this.ii(k.length);d=this.ab();if(e.Oy&&!d){for(var l=0;l<k.length;l+=
1)b=f&&g?f.parse(k[l]):k[l],k[l]=b;this.Lw(k,!1,e,!1)}else{e=null;for(var m=b,l=0;l<k.length;l+=1)b=f&&g?f.parse(k[l]):k[l],d&&(c={at:m},e=this.Vh(m,c,!0,!1)),c.silent=!0,this.bh(b,c,!0,!1),this.Vh(m,null,!0,!1)!==e&&m++}}return k};a.l.prototype.UO=function(c){var b=c||{},d=b.success,e,g;void 0===b.parse&&(b.parse=!0);g=this;b.success=function(f){var k,l;k=g.parse(f,c);var m=null,n=[];if(b.add||g.model)if(l=a.l.CB(g),k)for(m=k instanceof Array?k:[k],k=0;k<m.length;k+=1)e=l&&b.parse?l.parse(m[k]):
m[k],n.push(g.In(e));g.Hb(!1,a.X.v.SYNC,g,f,b);d&&d.call(a.q.ag(c,g),g,n,b)};this.hC(b)};a.l.CB=function(c){if(c.model)return a.q.Zc(c.model)?new c.model:new c.model.constructor};a.l.prototype.hC=function(c){try{return a.q.vn("read",this,c)}catch(b){throw this.Hb(!1,a.X.v.ERROR,this,null,c),b;}};a.l.prototype.DF=function(){var a=this.totalResults;void 0!==a&&this.gd()!==a&&(this.Lj(Array(a)),this.Tn(),this.oi())};a.l.prototype.cn=function(c){c=c||{};return c[a.l.cd]||this[a.l.cd]};a.l.prototype.ab=
function(){return-1<this.cn(null)};a.l.prototype.Lq=function(c,b,d,e,g){c=parseInt(a.l.qv(c,b,d),10);return void 0===c||null===c||isNaN(c)?e?e:g:c};a.l.prototype.hU=function(c,b){var d={};this.customPagingOptions&&((d=this.customPagingOptions.call(this,c))||(d={}));b=b||{};this.lastFetchSize=this.Lq(d,c,"limit",b.fetchSize,this.fetchSize);this.offset=this.Lq(d,c,"offset",b.startIndex,0);this.lastFetchCount=this.Lq(d,c,"count",this.lastFetchCount,this.lastFetchCount);this.totalResults=this.Lq(d,c,
"totalResults",this.totalResults,this.totalResults);this.hasMore=this.BP(a.l.qv(d,c,"hasMore"),this.offset,this.lastFetchSize,this.totalResults);!this.ab()&&this.totalResults&&this.totalResults!==this.lastFetchCount&&this.lastFetchSize&&this.Is(this.lastFetchSize)};a.l.prototype.BP=function(a,b,d,e){return a&&void 0!==a?a:b+d>e?!1:!0};a.l.qv=function(a,b,d){return a.hasOwnProperty(d)?a[d]:b?b[d]:void 0};a.l.prototype.mv=function(){return void 0!==this.offset?this.offset:0};a.l.prototype.create=function(c,
b){function d(b,d){b.save(c instanceof a.q?null:c,d);return b}var e=this.Rd(b);b=b||{};var g=this.In(c,!0,b),f=b.success,k=b.context;b.context=this;b.success=function(a,b,c){f&&f.call(null!=k?k:this,a,b,c)};if(null==g)return!1;b.forceNew=null!=g.ye();g.km(this);var l=this;if(e||this.ab())return a.b.ha(function(a){l.add(g,{merge:!0,deferred:!0}).then(function(){b.success=function(b,c,d){f&&f.call(null!=k?k:l,b,c,d);a(b)};var c=d(g,b);c||a(c)})});this.add(g,{merge:!0});return d(g,b)};a.b.g("Collection.prototype.create",
{create:a.l.prototype.create});a.l.prototype.UI=function(a){var b=[],d;this.Ke("pluck");for(d=0;d<this.Qc();d+=1)b.push(this.at(d).get(a));return b};a.b.g("Collection.prototype.pluck",{UI:a.l.prototype.UI});a.l.prototype.$l=function(c,b){b=b||{};var d=this.Rd(b),e=this;if(this.ab())return a.b.ha(function(a,b){e.UO({query:c,all:!0,success:function(b,c){a(c)},error:function(a,c,d){b({collection:a,xhr:c,error:d})}})});var g=[],f,k;for(f=0;f<this.Qc();f+=1)k=this.at(f),k.HJ(c)&&g.push(k);return d?a.b.ha(function(a){a(g)}):
g};a.b.g("Collection.prototype.where",{$l:a.l.prototype.$l});a.l.prototype.AJ=function(c,b){b=b||{};var d=this.Rd(b),e=this;if(this.ab()||d)return a.b.ha(function(a){return e.$l(c,b).then(function(b){b=e.jE(b);a(b)})});d=this.$l(c,b);d=this.jE(d);d[a.l.cd]=-1;d.oi();return d};a.b.g("Collection.prototype.whereToCollection",{AJ:a.l.prototype.AJ});a.l.prototype.jE=function(a){var b=this.uB(!1);b.Lj(a);b.Tn();b.oi();return b};a.l.prototype.Ke=function(a){if(this.ab())throw Error(a+" not valid on a virtual Collection");
};a.l.prototype.map=function(a,b){var d=[],e;this.Ke("map");this.Cb().forEach(function(g){e=a.call(b||this,g);d.push(e)});return d};a.b.g("Collection.prototype.map",{map:a.l.prototype.map});a.l.prototype.each=function(a,b){this.Ke("each");this.Cb().forEach(a,b)};a.b.g("Collection.prototype.each",{each:a.l.prototype.each});a.l.prototype.size=function(){return this.Qc()};a.b.g("Collection.prototype.size",{size:a.l.prototype.size});a.l.prototype.iJ=function(c,b){var d=[],e;this.Ke("sortBy");this.Cb().forEach(function(a){d.push(a)});
e=this;d.sort(function(d,f){var k,l;if(a.q.Zc(c))return k=c.call(b||e,d),l=c.call(b||e,f),a.l.gh(k,l,e.sortDirection);k=d.get(c);l=f.get(c);return a.l.gh(k,l,e.sortDirection)});return d};a.b.g("Collection.prototype.sortBy",{iJ:a.l.prototype.iJ});a.l.prototype.oI=function(c,b){var d={},e;this.Ke("groupBy");this.Cb().forEach(function(g){e=a.q.Zc(c)?c.call(b||this,g):g.get(c);void 0===d[e]&&(d[e]=[]);d[e].push(g)},this);return d};a.b.g("Collection.prototype.groupBy",{oI:a.l.prototype.oI});a.l.prototype.min=
function(a,b){var d={},e,g;this.Ke("min");if(0==this.gd())return null;d=this.Vb(0);e=a.call(b||this,this.Vb(0));this.Cb().forEach(function(f,k){1<=k&&(g=a.call(b||this,f),g<e&&(d=f,e=g))},this);return d};a.b.g("Collection.prototype.min",{min:a.l.prototype.min});a.l.prototype.max=function(a,b){var d={},e,g;this.Ke("max");if(0==this.gd())return null;d=this.Vb(0);e=a.call(b,this.Vb(0));this.Cb().forEach(function(f,k){1<=k&&(g=a.call(b||this,f),g>e&&(d=f,e=g))},this);return d};a.b.g("Collection.prototype.max",
{max:a.l.prototype.max});a.l.prototype.filter=function(a,b){var d=[];this.Ke("filter");this.Cb().forEach(function(e){a.call(b||this,e)&&d.push(e)});return d};a.b.g("Collection.prototype.filter",{filter:a.l.prototype.filter});a.l.prototype.BJ=function(a){var b=[],d,e,g,f;this.Ke("without");for(var k,l=0;l<this.Cb().length;l++){f=!0;k=this.Cb()[l];for(d=0;d<arguments.length;d+=1)if(g=arguments[d].mk(),e=arguments[d].ye(),k.nk(e,g)){f=!1;break}f&&b.push(k)}return b};a.b.g("Collection.prototype.without",
{BJ:a.l.prototype.BJ});a.l.prototype.isEmpty=function(){return 0===this.Qc()};a.b.g("Collection.prototype.isEmpty",{isEmpty:a.l.prototype.isEmpty});a.l.prototype.fH=function(a,b){this.Ke("any");for(var d,e=0;e<this.gd();e+=1)if(d=this.Vb(e),a.call(b||this,d))return!0;return!1};a.b.g("Collection.prototype.any",{fH:a.l.prototype.fH});a.l.prototype.EH=function(c,b){var d=this.Rd(b),e=this;if(this.ab()||d)return a.b.ha(function(a){e.$l(c,b).then(function(b){b&&0<b.length&&a(b[0]);a(null)})});d=this.$l(c);
return 0<d.length?d[0]:null};a.b.g("Collection.prototype.findWhere",{EH:a.l.prototype.EH});a.l.prototype.slice=function(a,b,d){var e=this.Rd(d);d=[];if(void 0===b){if(this.BY&&!this.Tk())throw Error("End must be set for virtual collections with no totalResults");b=this.gd()}if(e||this.ab())return this.gm(a,b);for(;a<b;a+=1)d.push(this.Vb(a));return d};a.b.g("Collection.prototype.slice",{slice:a.l.prototype.slice});a.l.prototype.set=function(a,b){return this.Lw(a,!0,b,this.Rd(b)||this.ab())};a.b.g("Collection.prototype.set",
{set:a.l.prototype.set});a.l.rF=function(a,b,d,e){if(b)for(b=a.gd()-1;0<=b;b-=1)-1==d.indexOf(b)&&a.mi(a.Vb(b),b,e)};a.l.prototype.Lw=function(c,b,d,e){d=d||{};var g=void 0===d.add?!0:d.add,f=void 0===d.remove?!0:d.remove,k=void 0===d.merge?!0:d.merge,l=[],m=null,n;b&&(c=this.parse(c));n=a.q.fm(c)?c:[c];if(e)return this.rO(n,d,f,g,k,b);for(c=0;c<n.length;c+=1)m=this.UG(this.In(n[c],b,d),g,k,e),-1!==m&&l.push(m);a.l.rF(this,f,l,d)};a.l.prototype.rO=function(c,b,d,e,g,f){var k=[],l,m=this;return a.b.ha(function(n){function q(a){return r(a+
1)}function r(d){return a.b.ha(function(a){m.UG(m.In(c[d],f,b),e,g,!0).then(function(b){-1!==b&&k.push(b);a(d)})})}var t=r(0);for(l=1;l<c.length;l+=1)t=t.then(q);t.then(function(){a.l.rF(m,d,k,b);n()})})};a.l.prototype.UG=function(c,b,d,e){function g(e,g,f){var h=g?g.index:-1;if(g&&g.m){if(d){var k={merge:d};if(f)return a.b.ha(function(a){e.bh(c,k,!1,!0).then(function(){a(h)})});e.add(c,k)}}else if(b){if(f)return a.b.ha(function(a){e.add(c,{deferred:!0}).then(function(){a(e.Qc()-1)})});e.add(c);h=
e.Qc()-1}return h}if(e||this.ab()){var f=this;return a.b.ha(function(a){f.sj(c,null,e).then(function(b){g(f,b,!0).then(function(b){a(b)})})})}var k=this.sj(c);return g(this,k,!1)};a.l.prototype.toJSON=function(){var a=[];this.Ke("toJSON");this.Cb().forEach(function(b){a.push(b.toJSON())});return a};a.b.g("Collection.prototype.toJSON",{toJSON:a.l.prototype.toJSON});a.l.prototype.first=function(a,b){var d=this.Rd(b),e=this.Qc(),g=[];a?e=a:a=1;d=this.ab()||d;if(1===a)return d?this.vu(0,null):0<this.gd()?
this.Vb(0):null;e>this.gd()&&(!this.ab()||this.Tk())&&(e=this.gd());if(d)return this.gm(0,e);for(d=0;d<e;d+=1)g.push(this.Vb(d));return g};a.b.g("Collection.prototype.first",{first:a.l.prototype.first});a.l.prototype.indexOf=function(a,b){var d=this.Rd(b);return this.ab()||d?this.sj(a,null,!0).then(function(a){return a.index}):this.sj(a).index};a.b.g("Collection.prototype.indexOf",{indexOf:a.l.prototype.indexOf});a.l.prototype.$R=function(a){a=this.NC(a);return void 0!==a?a.index:-1};a.l.prototype.pop=
function(a){var b=this.Rd(a);if(this.ab()||b){var d=this;return this.at(this.Qc()-1,{deferred:b}).then(function(b){d.remove(b,a);return b})}b=this.at(this.Qc()-1);this.remove(b,a);return b};a.b.g("Collection.prototype.pop",{pop:a.l.prototype.pop});a.l.prototype.push=function(a,b){var d=this.Rd(b);this.ii(1);return this.bh(a,b,!1,d)};a.b.g("Collection.prototype.push",{push:a.l.prototype.push});a.l.prototype.lastIndexOf=function(c,b){var d;this.Ke("lastIndexOf");void 0===b&&(b=0);for(d=this.Qc()-1;d>=
b;d-=1)if(a.b.ej(c,this.at(d)))return d;return-1};a.b.g("Collection.prototype.lastIndexOf",{lastIndexOf:a.l.prototype.lastIndexOf});a.l.prototype.xv=function(a){return void 0===a?[]:a.split(",")};a.l.YP=function(c){c=a.q.fm(c)?c:[c];var b="",d,e,g,f;for(g=0;g<c.length;g++){d=c[g];for(f in d)if(d.hasOwnProperty(f))for(var k=a.q.fm(d[f])?d[f]:[d[f]],l=0;l<k.length;l++){if(a.q.bz(k[l])){e=k[l].value;var m=null,m=k[l].comparator,m=a.q.Zc(m)?m(null,f,e):m;e=f+m+e}else e=f+"\x3d"+d[f];b+=e+"+"}b=b.substring(0,
b.length-1)+","}return","===b.substring(b.length-1)?b.substring(0,b.length-1):b};a.l.prototype.XJ=function(c){var b={},d;for(d in c)c.hasOwnProperty(d)&&(b[d]=c[d]);if((c=this.comparator)&&a.fb.pd(c)){c=this.xv(c);for(d=0;d<c.length;d++)b.sort=0===d?c[d]:b.sort+(","+c[d]);b.sortDir=this.yv()}this.ab()&&(b[a.l.cd]=this.cn(b));return b};a.l.prototype.NJ=function(c){var b=a.q.Zc(this.url)?this.url():this.url;if(this.ab()){var d=c.all,e=null;e=d?(e=this.totalResults)?e:this.cn(c):this.cn(c);b+="?limit\x3d"+
e;d||(c.startIndex&&(b+="\x26offset\x3d"+c.startIndex),c.startID&&(b+="\x26fromID\x3d"+c.startID),c.since&&(b+="\x26since\x3d"+c.since),c.until&&(b+="\x26until\x3d"+c.until));c.query&&(c=a.l.YP(c.query))&&0<c.length&&(b+="\x26q\x3d"+c);if(c=this.comparator)for(c=this.xv(c),d=this.yv(),e=0;e<c.length;e++)b=0===e?b+("\x26orderBy\x3d"+c[e]+":"+d):b+(","+c[e]+":"+d);b+="\x26totalResults\x3dtrue"}return b};a.l.prototype.yv=function(){return-1===this.sortDirection?"desc":"asc"};a.l.prototype.sync=function(a,
b,d){return window.oj.sync(a,b,d)};a.l.cd="fetchSize";a.Fb=function(a,b){this.Yo=a;this.Of=b;f.support.cors=!0};a.Fb.tk="headers";a.Fb.ho=function(c,b,d){var e;c=f.extend(!0,c,d);for(e in b)b.hasOwnProperty(e)&&"oauthHeader"!==e&&(c.hasOwnProperty(e)||(c[e]=b[e]),e===a.Fb.tk&&(c[e]=f.extend(!0,c[e],b[e])));if(b.oauthHeader)for(e in c[a.Fb.tk]||(c[a.Fb.tk]={}),b.oauthHeader)b.oauthHeader.hasOwnProperty(e)&&(c[a.Fb.tk].hasOwnProperty(e)||(c[a.Fb.tk][e]=b.oauthHeader[e]));return c};a.Fb.prototype.lW=
function(c,b,d,e){d=d||{};var g="jsonp"===d.dataType,f=this.nn("read",this.Yo,this.Of,null,e,d);c={crossDomain:d.crossDomain||!g,dataType:d.dataType||"json",jsonpCallback:d.jsonpCallback,context:null!==e?e:this,success:c,error:b};c=this.Np(c);c=a.Fb.ho(c,d,f);d.xhr=this.ajax(c);return d.xhr};a.Fb.prototype.Np=function(c){c[a.Fb.tk]={"Accept-Language":this.qe()};return c};a.Fb.prototype.kW=function(c,b,d,e,g){e=e||{};var f="jsonp"===e.dataType;d=this.nn("read",this.Yo,this.Of,d,g,e);c={crossDomain:e.crossDomain||
!f,dataType:e.dataType||"json",jsonpCallback:e.jsonpCallback,context:null!==g?g:this,success:c,error:b};c=this.Np(c);c=a.Fb.ho(c,e,d);e.xhr=this.ajax(c);return e.xhr};a.Fb.prototype.yJ=function(c,b,d,e,g,f,k){g=g||{};var l="jsonp"===g.dataType;b=this.nn(k?"patch":"update",this.Yo,this.Of,b,f,g);c={crossDomain:g.crossDomain||!l,contentType:g.contentType||"application/json",dataType:g.dataType||"json",jsonpCallback:g.jsonpCallback,data:JSON.stringify(d),success:c,error:e,context:null!==f?f:this};c=
this.Np(c);c=a.Fb.ho(c,g,b);g.xhr=this.ajax(c);return g.xhr};a.Fb.prototype.av=function(a,b){return b.type?b.type:"create"===a?"POST":"delete"===a?"DELETE":"patch"===a?"PATCH":"update"===a?"PUT":"GET"};a.Fb.prototype.WT=function(c,b,d){b=b instanceof a.l?b.XJ(d):{};c&&(b.recordID=c);return b};a.Fb.prototype.nn=function(c,b,d,e,g,f){if(a.q.Zc(d)){d=d.call(this,c,g,this.WT(e,g,f));if(a.fb.pd(d))return{url:d,type:this.av(c,f)};if(d)return d.url=d.hasOwnProperty("url")?d.url:b,d.type=d.hasOwnProperty("type")?
d.type:this.av(c,f),d}return{url:b,type:this.av(c,f)}};a.Fb.prototype.SV=function(c,b,d,e){d=d||{};var g="jsonp"===d.dataType;c=this.nn("delete",this.Yo,this.Of,c,e,d);b={crossDomain:d.crossDomain||!g,success:d.success,error:b,context:null!==e?e:this};b=a.Fb.ho(b,d,c);d.xhr=this.ajax(b);return d.xhr};a.Fb.prototype.hV=function(c,b,d,e){d=d||{};var g=JSON.stringify(c),f="jsonp"===d.dataType;c=this.nn("create",this.Yo,this.Of,null,e,d);b={crossDomain:d.crossDomain||!f,contentType:d.contentType||"application/json",
dataType:d.dataType||"json",jsonpCallback:d.jsonpCallback,data:g,success:d.success,error:b,context:null!==e?e:this};b=this.Np(b);b=a.Fb.ho(b,d,c);d.xhr=this.ajax(b);return d.xhr};a.Fb.prototype.qe=function(){return a.ia.qe()};a.Fb.prototype.ajax=function(a){return window.oj.ajax(a)};a.eb=function(c,b){b=b||{};a.eb._init(this,b,c||"Authorization")};o_("OAuth",a.eb,a);a.b.sa(a.eb,a.b,"OAuth.OAuth");a.eb.prototype.Init=function(){a.eb.t.Init.call(this)};a.eb.prototype.XH=function(){var a={};this.vi.access_token||
this.xx();a[this.tg.lH]="Bearer "+this.vi.access_token;return a};a.b.g("OAuth.prototype.getHeader",{XH:a.eb.prototype.XH});a.eb.prototype.AI=function(){return this.vi.IY?!0:!1};a.b.g("OAuth.prototype.isInitialized",{AI:a.eb.prototype.AI});a.eb.prototype.xx=function(){var c={},b=this;c[b.tg.lH]="Basic "+a.eb.YM(b.tg.client_id+":"+b.tg.client_secret);f.ajax({type:"POST",async:!1,url:this.tg.bearer_url,data:"grant_type\x3dclient_credentials",headers:c,success:function(c){a.eb.tn(b.vi,c)},error:function(a){throw Error(a.responseText);
}})};a.b.g("OAuth.prototype.clientCredentialGrant",{xx:a.eb.prototype.xx});a.eb.prototype.eJ=function(c){a.eb.tn(this.vi,c)};a.b.g("OAuth.prototype.setAccessTokenResponse",{eJ:a.eb.prototype.eJ});a.eb.prototype.MH=function(){return this.vi};a.b.g("OAuth.prototype.getAccessTokenResponse",{MH:a.eb.prototype.MH});a.eb.prototype.pH=function(){a.eb.nB(this.vi)};a.b.g("OAuth.prototype.cleanAccessTokenResponse",{pH:a.eb.prototype.pH});a.eb.prototype.dJ=function(c){a.eb.tn(this.tg,c)};a.b.g("OAuth.prototype.setAccessTokenRequest",
{dJ:a.eb.prototype.dJ});a.eb.prototype.LH=function(){return this.tg};a.b.g("OAuth.prototype.getAccessTokenRequest",{LH:a.eb.prototype.LH});a.eb.prototype.oH=function(){a.eb.nB(this.tg)};a.b.g("OAuth.prototype.cleanAccessTokenRequest",{oH:a.eb.prototype.oH});a.eb._init=function(c,b,d){c.Init();c.tg={};c.vi={};b.access_token?a.eb.tn(c.vi,b):b.client_id&&b.client_secret&&b.bearer_url&&a.eb.tn(c.tg,b);c.tg.lH=d};a.eb.tn=function(a,b){var d;b=b||{};for(d in b)a[d]=b[d]};a.eb.nB=function(a){for(var b in a)a.hasOwnProperty(b)&&
"auth_header"!==b&&(a[b]=null,delete a[b])};a.eb.YM=function(a){var b,d,e,g,f=0,k=0,l=[];do b=a.charCodeAt(f++),d=a.charCodeAt(f++),e=a.charCodeAt(f++),g=b<<16|d<<8|e,b=g>>18&63,d=g>>12&63,e=g>>6&63,g&=63,l[k++]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".charAt(b)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".charAt(d)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".charAt(e)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".charAt(g);
while(f<a.length);l=l.join("");b=a.length%3;return(b?l.slice(0,b-3):l)+"\x3d\x3d\x3d".slice(b||3)}});
//# sourceMappingURL=oj-modular.map