/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojdatacollection-common","ojs/ojinputtext"],function(a,f){a.lb=function(a){this.Ra=a;this.Init()};o_("PagingDataSource",a.lb,a);a.b.sa(a.lb,a.Nc,"oj.PagingDataSource");a.lb.prototype.Init=function(){a.lb.t.Init.call(this)};a.b.g("PagingDataSource.prototype.Init",{Init:a.lb.prototype.Init});a.lb.prototype.fetch=function(){a.i.fa();return a.b.ha(function(a,b){b()})};a.b.g("PagingDataSource.prototype.fetch",{fetch:a.lb.prototype.fetch});a.lb.prototype.hasMore=
function(){a.i.fa();return!1};a.b.g("PagingDataSource.prototype.hasMore",{hasMore:a.lb.prototype.hasMore});a.lb.prototype.next=function(){a.i.fa();return a.b.ha(function(a,b){b()})};a.b.g("PagingDataSource.prototype.next",{next:a.lb.prototype.next});a.lb.prototype.previous=function(){a.i.fa();return a.b.ha(function(a,b){b()})};a.b.g("PagingDataSource.prototype.previous",{previous:a.lb.prototype.previous});a.lb.prototype.setPageSize=function(){a.i.fa()};a.lb.prototype.startIndex=function(){a.i.fa();
return 0};a.b.g("PagingDataSource.prototype.startIndex",{startIndex:a.lb.prototype.startIndex});a.lb.prototype.size=function(){a.i.fa();return 0};a.b.g("PagingDataSource.prototype.size",{size:a.lb.prototype.size});a.lb.prototype.totalSize=function(){a.i.fa();return 0};a.b.g("PagingDataSource.prototype.totalSize",{totalSize:a.lb.prototype.totalSize});a.lb.v={ADD:"add",REMOVE:"remove",RESET:"reset",SYNC:"sync",REFRESH:"refresh",SORT:"sort"};o_("PagingDataSource.EventType",a.lb.v,a);(function(){a.Oa("oj.ojPagingControl",
f.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{data:null,overflow:"fit",pageSize:25,pageOptions:{layout:["auto"],maxPageLinks:6},loadMoreOptions:{maxCount:500},mode:"page",translations:{}},cb:{ZK:"labelAccPaging",UK:"labelAccNavFirstPage",VK:"labelAccNavLastPage",WK:"labelAccNavNextPage",YK:"labelAccNavPreviousPage",XK:"labelAccNavPage",$K:"labelLoadMore",aL:"labelNavInputPage",bL:"labelNavInputPageMax",cL:"labelNavInputPageSummary",$z:"msgItemRange",
nL:"msgItemRangeUnknown",gM:"tipNavInputPage",jM:"tipNavPageLink",iM:"tipNavNextPage",kM:"tipNavPreviousPage",fM:"tipNavFirstPage",hM:"tipNavLastPage",BK:"pageInvalid.summary",AK:"pageInvalid.detail",ft:"dataInvalidType.summary",et:"dataInvalidType.detail",zK:"maxPageLinksInvalid.summary",yK:"maxPageLinksInvalid.detail"},Na:{Bt:"oj-component",Od:"oj-active",Zi:"oj-clickable-icon",Bb:"oj-disabled",xd:"oj-enabled",Df:"oj-focus",qp:"oj-hover",qc:"oj-selected"},qa:{uL:"oj-pagingcontrol",dA:"oj-pagingcontrol-acc-label",
eA:"oj-pagingcontrol-content",fA:"oj-pagingcontrol-loadmore",gA:"oj-pagingcontrol-loadmore-link",hA:"oj-pagingcontrol-loadmore-range",jA:"oj-pagingcontrol-nav",Cp:"oj-pagingcontrol-nav-arrow",iA:"oj-pagingcontrol-nav-arrow-section",EL:"oj-pagingcontrol-nav-page",DL:"oj-pagingcontrol-nav-page-acc-label",xL:"oj-pagingcontrol-nav-label",mA:"oj-pagingcontrol-nav-input-section",kA:"oj-pagingcontrol-nav-input",lA:"oj-pagingcontrol-nav-input-max",pt:"oj-pagingcontrol-nav-input-summary",CL:"oj-pagingcontrol-nav-pages-section",
nA:"oj-pagingcontrol-nav-pages-links",ot:"oj-pagingcontrol-nav-first",vL:"oj-pagingcontrol-nav-first-acc-label",st:"oj-pagingcontrol-nav-previous",FL:"oj-pagingcontrol-nav-previous-acc-label",rt:"oj-pagingcontrol-nav-next",AL:"oj-pagingcontrol-nav-next-acc-label",qt:"oj-pagingcontrol-nav-last",yL:"oj-pagingcontrol-nav-last-acc-label",wL:"oj-pagingcontrol-nav-first-icon",GL:"oj-pagingcontrol-nav-previous-icon",BL:"oj-pagingcontrol-nav-next-icon",zL:"oj-pagingcontrol-nav-last-icon",dj:"oj-component-icon",
Ef:"oj-helper-hidden-accessible"},sK:"data-oj-pagenum",Pd:"enabled",ym:"disabled",zp:{jt:"loadMore",sL:"page"},yd:{ok:"auto",om:"all",OK:"input",HL:"rangeText",tL:"pages",aA:"nav"},firstPage:function(){var c=this.za();return null!=c?(this.C=0,c.fetch({startIndex:0})):a.b.ha(function(a,c){c()})},previousPage:function(){var c=this.za();if(null!=c){var b=this.Ee();if(1<b)return this.C=this.Qk(b-1),0>this.C&&(this.C=0),c.fetch({startIndex:this.C})}return a.b.ha(function(a,b){b()})},nextPage:function(){var c=
this.za();if(null!=c){var b=this.Ee();if(b+1<=this.hd()||0>this.hd())return this.C=this.Qk(b+1),c.fetch({startIndex:this.C})}return a.b.ha(function(a,b){b()})},lastPage:function(){var c=this.za();return null!=c&&0<this.hd()?(this.C=this.Qk(this.hd()),c.fetch({startIndex:this.C})):a.b.ha(function(a,c){c()})},page:function(c){var b=this.za();return null!=b&&0<this.hd()?(this.C=this.Qk(c),b.fetch({startIndex:this.C})):a.b.ha(function(a,b){b()})},loadNext:function(){var c=this.za();return null!=c?c.next():
a.b.ha(function(a,c){c()})},refresh:function(){this._super();if(null!=this.bi){this.bi=null;var a=this.za();null!=a&&(a.setPageSize(this.options.pageSize),a.fetch({startIndex:this.C}))}this.Wb(!0)},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;var b=a.subId;return"oj-pagingcontrol-nav-input"===b?this.QP():"oj-pagingcontrol-nav-input-max"===b?this.hf().find("."+this.qa.lA):"oj-pagingcontrol-nav-input-summary"===b?this.hf().find("."+this.qa.pt):"oj-pagingcontrol-nav-first"===
b?this.hf().find("."+this.qa.ot):"oj-pagingcontrol-nav-next"===b?this.hf().find("."+this.qa.rt):"oj-pagingcontrol-nav-previous"===b?this.hf().find("."+this.qa.st):"oj-pagingcontrol-nav-last"===b?this.hf().find("."+this.qa.qt):"oj-pagingcontrol-nav-page"===b?(a=a.index,this.hf().find("["+this.sK+"\x3d"+a+"]")):null},_ComponentCreate:function(){this._super();this.Rn();this.Wm();this.gl(this.hf());this._on(this.Jf);var a=this;setInterval(function(){null!=a.nF&&(a.dF(),a.nF=null)},50);setInterval(function(){if(null!=
a.bi){var b=a.za();null!=b&&(b.setPageSize(a.options.pageSize),b.fetch({startIndex:a.C}),a.bi=null)}},100)},_destroy:function(){this.Pj()},Wm:function(){var a=this.options;this.element.addClass(this.qa.uL);this.element.addClass(this.Na.Bt);this.C=0;this.UN();this.$N();a.mode==this.zp.jt?(this.aO(),this.bO(),this.AB()):this.BB()},Jf:{"click .oj-pagingcontrol-loadmore-link":function(a){this.loadNext();a.preventDefault()},"click .oj-pagingcontrol-nav-page":function(a){var b=f(a.target).attr("data-oj-pagenum");
this.page(b);a.preventDefault()},"click .oj-pagingcontrol-nav-first":function(a){this.firstPage();a.preventDefault()},"click .oj-pagingcontrol-nav-previous":function(a){this.previousPage();a.preventDefault()},"click .oj-pagingcontrol-nav-next":function(a){this.nextPage();a.preventDefault()},"click .oj-pagingcontrol-nav-last":function(a){this.lastPage();a.preventDefault()},"keypress .oj-pagingcontrol-nav-input":function(a){13==a.which&&a.preventDefault()},"mousedown .oj-pagingcontrol-nav-first":function(a){f(a.target).addClass(this.Na.Od);
a.preventDefault()},"mousedown .oj-pagingcontrol-nav-previous":function(a){f(a.target).addClass(this.Na.Od);a.preventDefault()},"mousedown .oj-pagingcontrol-nav-next":function(a){f(a.target).addClass(this.Na.Od);a.preventDefault()},"mousedown .oj-pagingcontrol-nav-last":function(a){f(a.target).addClass(this.Na.Od);a.preventDefault()},"mouseup .oj-pagingcontrol-nav-first":function(a){f(a.target).removeClass(this.Na.Od);a.preventDefault()},"mouseup .oj-pagingcontrol-nav-previous":function(a){f(a.target).removeClass(this.Na.Od);
a.preventDefault()},"mouseup .oj-pagingcontrol-nav-next":function(a){f(a.target).removeClass(this.Na.Od);a.preventDefault()},"mouseup .oj-pagingcontrol-nav-last":function(a){f(a.target).removeClass(this.Na.Od);a.preventDefault()},"mouseleave .oj-pagingcontrol-nav-first":function(a){f(a.target).removeClass(this.Na.Od);a.preventDefault()},"mouseleave .oj-pagingcontrol-nav-previous":function(a){f(a.target).removeClass(this.Na.Od);a.preventDefault()},"mouseleave .oj-pagingcontrol-nav-next":function(a){f(a.target).removeClass(this.Na.Od);
a.preventDefault()},"mouseleave .oj-pagingcontrol-nav-last":function(a){f(a.target).removeClass(this.Na.Od);a.preventDefault()}},Wb:function(a){a?this.dF():this.nF=!0},dF:function(){this.f!=this.options.data&&(this.fu(),this.bi=!0);if(this.options.mode==this.zp.jt){var a=this.za(),b=this.hn();null!=a&&a.size()==a.totalSize()?b.css("display","none"):(b.css("display",""),this.ZS())}else this.$S()},_setOption:function(a,b){this._superApply(arguments);this.bi=!0;this.Wb(!0)},fu:function(){null!=this.f&&
this.Pj();this.f=null;this.C=0},tN:function(){this.Pt=null},uN:function(){this.St=this.Rt=this.Qt=null},Ee:function(){return 0==this.C?1:Math.ceil((this.C+1)/this.options.pageSize)},za:function(){if(!this.f&&null!=this.options.data){var c=this.options.data;if(c instanceof a.lb)this.f=c;else{var c=this.O(this.cb.ft),b=this.O(this.cb.et);throw Error(c+"\n"+b);}this.f.setPageSize(this.options.pageSize);this.Rn();var d=this;setTimeout(function(){d.Sv()},0)}return this.f},JC:function(){var a=this.za(),
b=this.C,d=this.O(this.cb.$z,{pageFrom:b,pageTo:0,pageTotal:0});null!=a&&(d=parseInt(this.C,10)+parseInt(a.size(),10),b=0<d?b+1:0,-1!=a.totalSize()?(d=d>a.totalSize()?a.totalSize():d,d=this.O(this.cb.$z,{pageFrom:b,pageTo:d,pageTotal:a.totalSize()})):d=this.O(this.cb.nL,{pageFrom:b,pageTo:d}));return d},KP:function(){return this.options.pageOptions.maxPageLinks},Qk:function(c){var b=(c-1)*this.options.pageSize,d=this.hd();0>b?a.D.error("Value must be greater than 0"):0<d&&c>d&&a.D.error("Value cannot be greater than the total number of pages");
return b},hd:function(){var a=this.za(),b=0;null!=a&&(b=a.totalSize());return-1==b?-1:Math.ceil(b/this.options.pageSize)},Fv:function(){this.Wb()},Pq:function(){this.C=0;this.za().setPageSize(this.options.pageSize);this.Wb(!0);this.za().fetch({startIndex:this.C,reset:!0})},nD:function(){this.Wb();this.za().fetch({startIndex:this.C})},Qq:function(a){this.options.mode==this.zp.jt?this.Pq(a):this.nD(a)},Gv:function(a){if(this.options.mode==this.zp.sL){var b=this.za(),d=0;null!=b&&(d=b.totalSize());b=
this.options.pageSize;a=a.index;var e=this.Qk(this.Ee());if(e!=this.C||a>=e&&a<e+b&&d>b)this.C=e,this.bi=!0}this.Wb()},Hv:function(){0>=this.hd()?this.C=0:this.Ee()>this.hd()&&(this.C=this.Qk(this.hd()),this.bi=!0);1<this.hd()&&(this.bi=!0);this.Wb()},OQ:function(c,b){try{b.value!=this.Ee()&&!isNaN(b.value)&&0<b.value&&this.page(b.value)}catch(d){var e=this.O(this.cb.BK),g=this.O(this.cb.AK);a.D.error(e+"\n"+g)}},Sv:function(){null!=this.za()&&this.za().size()<this.options.pageSize&&(0>this.za().totalSize()||
this.za().totalSize()>=this.za().size())&&(this.za().setPageSize(this.options.pageSize),this.za().fetch({startIndex:this.C,fetchType:"init"}))},ZS:function(){var a=this.PP();a[0].parentNode.removeChild(a[0]);this.AB();this.tN()},$S:function(){var a=this.options.overflow;this.gn().empty();this.uN();this.BB();this.aT();if("fit"==a){var a=this.element.width(),b=this.RC(),d=this.RP(),e=this.TP(),g=this.SP(),f=null!=b?b[0].offsetWidth:0,k=null!=d?d[0].offsetWidth:0,d=null!=e?e.width():0,l=null!=g?g.width():
0,f=f+k;f>a?f-d<=a?e.css("display","none"):f-d-l<=a?(null!=e&&e.css("display","none"),null!=g&&g.css("display","none")):(null!=e&&e.css("display","none"),null!=g&&g.css("display","none"),null!=b&&b.css("display","none")):0<f&&(null!=e&&e.css("display",""),null!=g&&g.css("display",""),null!=b&&b.css("display",""))}},aT:function(){var a=this.RC(),b=a.children("."+this.qa.ot);b&&0<b.length&&(b=f(b[0]),1==this.Ee()?(b.addClass(this.Na.Bb),b.removeClass(this.Na.xd),b.attr("tabindex","-1")):(b.addClass(this.Na.xd),
b.removeClass(this.Na.Bb),b.attr("tabindex","0")));(b=a.children("."+this.qa.st))&&0<b.length&&(b=f(b[0]),1==this.Ee()?(b.addClass(this.Na.Bb),b.removeClass(this.Na.xd),b.attr("tabindex","-1")):(b.addClass(this.Na.xd),b.removeClass(this.Na.Bb),b.attr("tabindex","0")));(b=a.children("."+this.qa.qt))&&0<b.length&&(b=f(b[0]),this.Ee()==this.hd()||0===this.hd()?(b.addClass(this.Na.Bb),b.removeClass(this.Na.xd),b.attr("tabindex","-1")):(b.addClass(this.Na.xd),b.removeClass(this.Na.Bb),b.attr("tabindex",
"0")));(a=a.children("."+this.qa.rt))&&0<a.length&&(a=f(a[0]),this.Ee()==this.hd()||0===this.hd()?(a.addClass(this.Na.Bb),a.removeClass(this.Na.xd),a.attr("tabindex","-1")):(a.addClass(this.Na.xd),a.removeClass(this.Na.Bb),a.attr("tabindex","0")))},Rn:function(){var c=this.za();if(null!=c){this.Pj();this.rb=[];this.rb.push({eventType:a.lb.v.ADD,eventHandler:this.Gv.bind(this)});this.rb.push({eventType:a.lb.v.REMOVE,eventHandler:this.Hv.bind(this)});this.rb.push({eventType:a.lb.v.RESET,eventHandler:this.Pq.bind(this)});
this.rb.push({eventType:a.lb.v.REFRESH,eventHandler:this.nD.bind(this)});this.rb.push({eventType:a.lb.v.SYNC,eventHandler:this.Fv.bind(this)});this.rb.push({eventType:a.lb.v.SORT,eventHandler:this.Qq.bind(this)});var b,d;for(b=0;b<this.rb.length;b++)(d=c.on(this.rb[b].eventType,this.rb[b].eventHandler))&&(this.rb[b].eventHandler=d)}},gl:function(c){if(!this.Zv){var b=this;a.ba.ug(c[0],function(){b.Wb()});this.Zv=!0}},Pj:function(){var a=this.za();if(null!=this.rb&&null!=a){var b;for(b=0;b<this.rb.length;b++)a.off(this.rb[b].eventType,
this.rb[b].eventHandler)}},Gk:function(a,b){var d=f(document.createElement("span"));d.addClass(b);d.addClass(this.qa.Ef);d.append(a);return d},UN:function(){var a=this.hf(),b=this.O(this.cb.ZK),b=this.Gk(b,this.qa.dA),d=this.element.attr("id")+"_oj_pgCtrl_acc_label";b.attr("id",d);a.append(b);return b},YN:function(){var a=this.O(this.cb.XK);return this.Gk(a,this.qa.DL)},VN:function(){var a=this.O(this.cb.UK);return this.Gk(a,this.qa.vL)},WN:function(){var a=this.O(this.cb.VK);return this.Gk(a,this.qa.yL)},
XN:function(){var a=this.O(this.cb.WK);return this.Gk(a,this.qa.AL)},ZN:function(){var a=this.O(this.cb.YK);return this.Gk(a,this.qa.FL)},$N:function(){var a=this.hf(),b=f(document.createElement("div"));b.addClass(this.qa.eA);var d=this.OP().attr("id");b.attr("role","navigation");b.attr("aria-labelledby",d);a.append(b);return b},aO:function(){var a=this.gn(),b=f(document.createElement("div"));b.addClass(this.qa.fA);a.append(b);return b},bO:function(){var a=this.hn(),b=f(document.createElement("a"));
b.addClass(this.qa.gA);var d=this.O(this.cb.$K);b.append(d);b.attr("tabindex","0");b.attr("href","#");a.append(b);return b},AB:function(){this.za();var a=this.hn(),b=f(document.createElement("span"));b.addClass(this.qa.hA);var d=this.JC();b.append(d);a.append(b);return b},BB:function(){var a=this.options.pageOptions.layout;null==a&&(a=[this.yd.ok]);var b=this.gn(),d=f(document.createElement("div"));d.addClass(this.qa.jA);b.append(d);if(-1!=f.inArray(this.yd.ok,a)||-1!=f.inArray(this.yd.om,a)||-1!=
f.inArray(this.yd.OK,a)){b=f(document.createElement("div"));b.addClass(this.qa.mA);d.append(b);var e=f(document.createElement("label"));e.addClass(this.qa.xL);var g=this.O(this.cb.aL);e.append(g);b.append(e);g=f(document.createElement("input"));g.addClass(this.qa.kA);var h=this.O(this.cb.gM);this._focusable(this.element);g.attr("title",h);g.attr("tabindex","0");g.val(this.Ee());e.append(g);e=0;if(0<this.hd()){e=this.hd();h=f(document.createElement("span"));h.addClass(this.qa.lA);var k=this.O(this.cb.bL,
{pageMax:e});h.append(k);b.append(h)}else e=this.Ee()+1;g.ojInputText({rootAttributes:{style:"width: auto; min-width: 0;"},optionChange:this.OQ.bind(this),validators:[{type:"numberRange",options:{min:1,max:e}}]});if(-1!=f.inArray(this.yd.ok,a)||-1!=f.inArray(this.yd.om,a)||-1!=f.inArray(this.yd.HL,a))g=f(document.createElement("span")),g.addClass(this.qa.pt),e=this.JC(),e=this.O(this.cb.cL,{pageSummary:e}),g.append(e),b.append(g)}b=f(document.createElement("div"));b.addClass(this.qa.iA);d.append(b);
if(-1!=f.inArray(this.yd.ok,a)||-1!=f.inArray(this.yd.om,a)||-1!=f.inArray(this.yd.aA,a))g=f(document.createElement("a")),g.addClass(this.qa.Cp),g.addClass(this.qa.ot),g.addClass(this.qa.wL),g.addClass(this.qa.dj),g.addClass(this.Na.Zi),g.addClass(this.Na.Bb),e=this.O(this.cb.fM),this._hoverable(g),this._focusable(g),g.attr("title",e),g.attr("tabindex","0"),g.attr("href","#"),e=this.VN(),g.append(e),b.append(g),g=f(document.createElement("a")),g.addClass(this.qa.Cp),g.addClass(this.qa.st),g.addClass(this.qa.GL),
g.addClass(this.qa.dj),g.addClass(this.Na.Zi),g.addClass(this.Na.Bb),e=this.O(this.cb.kM),this._hoverable(g),this._focusable(g),g.attr("title",e),g.attr("tabindex","0"),g.attr("href","#"),e=this.ZN(),g.append(e),b.append(g);if(-1!=f.inArray(this.yd.ok,a)||-1!=f.inArray(this.yd.om,a)||-1!=f.inArray(this.yd.tL,a))g=f(document.createElement("div")),g.addClass(this.qa.CL),b.append(g),this.cO(g,this.KP());if(-1!=f.inArray(this.yd.ok,a)||-1!=f.inArray(this.yd.om,a)||-1!=f.inArray(this.yd.aA,a))a=f(document.createElement("a")),
a.addClass(this.qa.Cp),a.addClass(this.qa.rt),a.addClass(this.qa.BL),a.addClass(this.qa.dj),a.addClass(this.Na.Zi),a.addClass(this.Na.Bb),g=this.O(this.cb.iM),this._hoverable(a),this._focusable(a),a.attr("title",g),a.attr("tabindex","0"),a.attr("href","#"),g=this.XN(),a.append(g),b.append(a),a=f(document.createElement("a")),a.addClass(this.qa.Cp),a.addClass(this.qa.qt),a.addClass(this.qa.zL),a.addClass(this.qa.dj),a.addClass(this.Na.Zi),a.addClass(this.Na.Bb),g=this.O(this.cb.hM),this._hoverable(a),
this._focusable(a),a.attr("title",g),a.attr("tabindex","0"),a.attr("href","#"),g=this.WN(),a.append(g),b.append(a);return d},cO:function(a,b){if(5>b){var d=this.O(this.cb.zK),e=this.O(this.cb.yK);throw Error(d+"\n"+e);}d=f(document.createElement("div"));d.addClass(this.qa.nA);a.append(d);var e=this.hd(),g=this.Ee(),h=b,k=[];if(1<=g){if(-1!=e&&e<=h)for(h=k[0]=1;h<e;h++)k[h]=h+1;else{k.push(1);1!=g&&k.push(g);g!=e&&-1!=e&&k.push(e);var h=h-k.length,l=g-1,m=1;if(g==e||g==e-1)m=0;for(;h>m&&1<l;)k.push(l),
l--,h--;g+=1;for(-1==e&&(h=1);0<h&&(g<=e||-1==e);)k.push(g),g++,h--}k.sort(function(a,b){return a-b});for(h=0;h<k.length;h++)g=k[h],this.qu(d,g),h!=k.length-1&&g!=k[h+1]-1&&this.qu(d,-1);-1==e&&this.qu(d,-1)}return d},qu:function(a,b){var d=this.Ee(),e=null;-1==b?(e=f(document.createElement("span")),e.append("...")):(d==b?(e=f(document.createElement("div")),e.addClass(this.Na.qc),e.addClass(this.Na.Od),e.addClass(this.Na.Bb),e.removeClass(this.Na.xd)):(e=f(document.createElement("a")),e.removeClass(this.Na.qc),
e.removeClass(this.Na.Od),e.removeClass(this.Na.Bb),e.addClass(this.Na.xd)),e.attr("data-oj-pagenum",b),e.addClass(this.qa.EL),d=this.O(this.cb.jM,{pageNum:b.toString()}),this._hoverable(e),this._focusable(e),e.attr("title",d),e.attr("tabindex","0"),e.attr("href","#"),d=this.YN(),e.append(d),e.append(b.toString()),this._hoverable(e));a.append(e);return e},OP:function(){var a=this.hf(),b=null;a&&(b=a.find("."+this.qa.dA))&&0<b.length&&(b=f(b.get(0)));return b},hf:function(){return f(this.element)},
gn:function(){if(!this.bB){var a=this.hf(),b=null;a&&(b=a.find("."+this.qa.eA))&&0<b.length&&(this.bB=f(b.get(0)))}return this.bB},hn:function(){if(!this.cB){var a=this.gn(),b=null;a&&(b=a.children("."+this.qa.fA))&&0<b.length&&(this.cB=f(b.get(0)))}return this.cB},jY:function(){if(!this.dB){var a=this.hn(),b=null;a&&(b=a.children("."+this.qa.gA))&&0<b.length&&(this.dB=f(b.get(0)))}return this.dB},PP:function(){if(!this.Pt){var a=this.hn(),b=null;a&&(b=a.children("."+this.qa.hA))&&0<b.length&&(this.Pt=
f(b.get(0)))}return this.Pt},jn:function(){if(!this.Qt){var a=this.gn(),b=null;a&&(b=a.children("."+this.qa.jA))&&0<b.length&&(this.Qt=f(b.get(0)))}return this.Qt},QP:function(){if(!this.Rt){var a=this.jn(),b=null;a&&(b=a.find("."+this.qa.kA))&&0<b.length&&(this.Rt=f(b.get(0)))}return this.Rt},SP:function(){if(!this.St){var a=this.jn(),b=null;a&&(b=a.find("."+this.qa.pt))&&0<b.length&&(this.St=f(b.get(0)))}return this.St},TP:function(){var a=this.jn(),b=null;a&&(b=a.find("."+this.qa.nA))&&0<b.length&&
(b=f(b.get(0)));return b},RC:function(){var a=this.jn(),b=null;if(a)if((b=a.find("."+this.qa.iA))&&0<b.length)b=f(b.get(0));else return null;return b},RP:function(){var a=this.jn(),b=null;if(a)if((b=a.find("."+this.qa.mA))&&0<b.length)b=f(b.get(0));else return null;return b}})})()});
//# sourceMappingURL=oj-modular.map