/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","knockout","ojs/ojpagingcontrol","ojs/ojknockout-model"],function(a,f,c){a.wb=function(a){this.pa=a;this.current=0;this.Init();this.nf=[];this.setPageSize(10)};o_("CollectionPagingDataSource",a.wb,a);a.b.sa(a.wb,a.lb,"oj.CollectionPagingDataSource");a.wb.prototype.Init=function(){a.wb.t.Init.call(this)};a.b.g("CollectionPagingDataSource.prototype.Init",{Init:a.wb.prototype.Init});a.wb.prototype.wv=function(){return this.hasMore()?this.pageSize:this.totalSize()-this.startIndex()};
a.wb.prototype.xh=function(){this.nf=Array(this.wv());var a=this;return this.pa.gm(this.startIndex(),this.startIndex()+this.nf.length).then(function(c){for(var e=0;e<c.length;e++)a.nf[e]=c[e];a.Pn()})};a.wb.prototype.Pn=function(){if(void 0!==this.Rf){this.Rf.removeAll();for(var b=0;b<this.nf.length;b++)this.Rf.push(a.Ma.map(this.nf[b]))}};a.wb.prototype.Wj=function(){return this.nf};a.b.g("CollectionPagingDataSource.prototype.getWindow",{Wj:a.wb.prototype.Wj});a.wb.prototype.zo=function(){void 0===
this.Rf&&(this.Rf=c.observableArray(),this.Pn());return this.Rf};a.b.g("CollectionPagingDataSource.prototype.getWindowObservable",{zo:a.wb.prototype.zo});a.wb.prototype.fetch=function(a){var c=a||{};void 0!==c.startIndex&&(this.current=c.startIndex);void 0!==c.pageSize&&(this.pageSize=c.pageSize);var e=this;try{this.pa.fetch({success:function(){e.xh().then(function(){e.Nn(c)})}})}catch(f){e.xh().then(function(){e.Nn(c)})}};a.b.g("CollectionPagingDataSource.prototype.fetch",{fetch:a.wb.prototype.fetch});
a.wb.prototype.Nn=function(a){a=a||{};this.handleEvent("sync",null);a.success&&a.success()};a.wb.prototype.handleEvent=function(b,c){a.wb.t.handleEvent.call(this,b,c)};a.wb.prototype.hasMore=function(){return this.startIndex()+this.pageSize<this.totalSize()};a.b.g("CollectionPagingDataSource.prototype.hasMore",{hasMore:a.wb.prototype.hasMore});a.wb.prototype.next=function(){if(this.hasMore()){this.current+=this.pageSize;var a=this;return this.xh().then(function(){a.Nn(null)})}this.Nn(null)};a.b.g("CollectionPagingDataSource.prototype.next",
{next:a.wb.prototype.next});a.wb.prototype.previous=function(){0>this.startIndex()-this.pageSize?this.current=0:this.current-=this.pageSize;var a=this;return this.xh().then(function(){a.Nn(null)})};a.b.g("CollectionPagingDataSource.prototype.previous",{previous:a.wb.prototype.previous});a.wb.prototype.setPageSize=function(a){this.pageSize=a};a.wb.prototype.startIndex=function(){return this.current};a.b.g("CollectionPagingDataSource.prototype.startIndex",{startIndex:a.wb.prototype.startIndex});a.wb.prototype.size=
function(){var a=this.Wj();return a?a.length:0};a.b.g("CollectionPagingDataSource.prototype.size",{size:a.wb.prototype.size});a.wb.prototype.totalSize=function(){return this.pa.length};a.b.g("CollectionPagingDataSource.prototype.totalSize",{totalSize:a.wb.prototype.totalSize});a.Ab=function(a){this.data=a;this.current=0;this.Init();this.setPageSize(10)};o_("ArrayPagingDataSource",a.Ab,a);a.b.sa(a.Ab,a.lb,"oj.ArrayPagingDataSource");a.Ab.prototype.Init=function(){a.Ab.t.Init.call(this)};a.b.g("ArrayPagingDataSource.prototype.Init",
{Init:a.Ab.prototype.Init});a.Ab.prototype.wv=function(){return this.hasMore()?this.pageSize:this.totalSize()-this.startIndex()};a.Ab.prototype.xh=function(){this.nf=Array(this.wv());for(var a=0;a<this.nf.length;a++)this.nf[a]=this.data[this.startIndex()+a];this.Pn();this.handleEvent("sync",null)};a.Ab.prototype.Pn=function(){if(void 0!==this.Rf){this.Rf.removeAll();for(var a=0;a<this.nf.length;a++)this.Rf.push(this.nf[a])}};a.Ab.prototype.handleEvent=function(b,c){a.Ab.t.handleEvent.call(this,b,
c)};a.Ab.prototype.Wj=function(){return this.nf};a.b.g("ArrayPagingDataSource.prototype.getWindow",{Wj:a.Ab.prototype.Wj});a.Ab.prototype.zo=function(){void 0===this.Rf&&(this.Rf=c.observableArray(),this.Pn());return this.Rf};a.b.g("ArrayPagingDataSource.prototype.getWindowObservable",{zo:a.Ab.prototype.zo});a.Ab.prototype.fetch=function(a){a=a||{};void 0!==a.startIndex&&(this.current=a.startIndex);void 0!==a.pageSize&&(this.pageSize=a.pageSize);this.xh()};a.b.g("ArrayPagingDataSource.prototype.fetch",
{fetch:a.Ab.prototype.fetch});a.Ab.prototype.hasMore=function(){return this.startIndex()+this.pageSize<this.totalSize()};a.b.g("ArrayPagingDataSource.prototype.hasMore",{hasMore:a.Ab.prototype.hasMore});a.Ab.prototype.next=function(){this.hasMore()&&(this.current+=this.pageSize,this.xh())};a.b.g("ArrayPagingDataSource.prototype.next",{next:a.Ab.prototype.next});a.Ab.prototype.previous=function(){0>this.startIndex()-this.pageSize?this.current=0:this.current-=this.pageSize;this.xh()};a.b.g("ArrayPagingDataSource.prototype.previous",
{previous:a.Ab.prototype.previous});a.Ab.prototype.setPageSize=function(a){this.pageSize=a;this.xh()};a.Ab.prototype.startIndex=function(){return this.current};a.b.g("ArrayPagingDataSource.prototype.startIndex",{startIndex:a.Ab.prototype.startIndex});a.Ab.prototype.size=function(){return this.Wj().length};a.b.g("ArrayPagingDataSource.prototype.size",{size:a.Ab.prototype.size});a.Ab.prototype.totalSize=function(){return this.data.length};a.b.g("ArrayPagingDataSource.prototype.totalSize",{totalSize:a.Ab.prototype.totalSize})});
//# sourceMappingURL=oj-modular.map