define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(a,f){(function(){var c="oj-left oj-center oj-right oj-top oj-middle oj-bottom".split(" "),b={"right-top":"oj-right oj-top","right-middle":"oj-right oj-middle","right-bottom":"oj-right oj-bottom","left-top":"oj-left oj-top","left-middle":"oj-left oj-middle","left-bottom":"oj-left oj-bottom","center-top":"oj-center oj-top","center-middle":"oj-left oj-middle","center-bottom":"oj-center oj-bottom"};a.Oa("oj.ojPopup",f.oj.baseComponent,{widgetEventPrefix:"oj",
options:{autoDismiss:"focusLoss",chrome:"default",initialFocus:"none",position:{my:"start top",at:"start bottom",of:"",collision:"flip"},tail:"none",beforeOpen:null,open:null,beforeClose:null,close:null,focus:null},_ComponentCreate:function(){this._super();var a=f("\x3cdiv\x3e");this.md=a.hide().addClass("oj-popup").attr("aria-hidden","true");a.addClass("oj-helper-reset-inheritable oj-component");var b=f("\x3cdiv\x3e").addClass("oj-popup-content");b.appendTo(a);this.element.after(a);this.element.appendTo(b);
this.element.show();this.FB();this.VF();this.RN();this.ZG=f.proxy(this.$U,this)},_destroy:function(){this._super();this.isOpen()&&this.close();this.VB();this.xO();delete this.ZG;this.md.replaceWith(this.element);this.element.hide()},widget:function(){return this.md},open:function(b,c){if(this.isOpen()&&(this.close(),this.isOpen()))return;this.fU(b);var g=this.md;b=this.Nb;a.i.mb(g,jQuery);a.i.mb(b,jQuery);a.fb.yI(g.attr("id"))&&g.uniqueId();if(!1!==this._trigger("beforeOpen")){this.gG(c);var h=this.options;
this.Jw(h.autoDismiss);this._on(!0,f(window),{resize:this.me,scroll:this.me});this._on(!0,g,{keydown:this.ZD});this._on(!0,b,{keydown:this.ZD});this.xM();g.removeAttr("aria-hidden");g.attr("role","tooltip");c=h.position;g.show();var k="rtl"===this.Ec();g.position(a.he.Jg(c,k));this._trigger("open");this.JD();g=this.O("none"===h.initialFocus?"ariaLiveRegionInitialFocusNone":"ariaLiveRegionInitialFocusFirstFocusable");this.PA(g)}},close:function(){if(this.isOpen()&&!1!==this._trigger("beforeClose")){this.IT();
var b=this.Nb,c=this.md;a.i.mb(c,jQuery);a.i.mb(b,jQuery);c.hide();c.attr("aria-hidden","true");this.pT();this.Jw();var g=f(window);this._off(g,"resize");this._off(g,"scroll");this._off(c,"keydown");this._off(b,"keydown");delete this.Nb;b=this.options.position;b._ofo&&(delete b._ofo,delete b.of);this.PA(null);this._trigger("close")}},isOpen:function(){return this.md.is(":visible")},refresh:function(){this._super();this.isOpen()&&this.me()},_setOption:function(a,b){var c=this.options;switch(a){case "tail":b!==
c.tail&&this.kU(b);break;case "chrome":b!==c.chrome&&this.VF(b);break;case "position":this.gG(b);this.isOpen()&&this.me();return;case "autoDismiss":this.isOpen()&&b!==c.autoDismiss&&this.Jw(b)}this._superApply(arguments)},kY:function(){return"oj-popup"},kU:function(a){this.VB();this.FB(a);this.me()},FB:function(b){b=b?b:this.options.tail;if("none"!==b){b=["oj-popup-tail",b].join("-");var c=f("\x3cdiv\x3e").hide().addClass("oj-popup-tail").addClass(b);this.CG="#"+c.uniqueId().attr("id");var g=this.md;
a.i.mb(g,jQuery);c.appendTo(g);g.addClass(b)}},fD:function(){var a=this.CG;return a?f(a):null},VB:function(){var b=this.fD();b&&b.remove();delete this.CG;var b=["oj-popup-tail",this.options.tail].join("-"),c=this.md;a.i.mb(c,jQuery);c.removeClass(b)},VF:function(b){b=b?b:this.options.chrome;var c=this.md;a.i.mb(c,jQuery);"default"===b&&c.hasClass("oj-popup-no-chrome")?c.removeClass("oj-popup-no-chrome"):"none"!==b||c.hasClass("oj-popup-no-chrome")||c.addClass("oj-popup-no-chrome")},fU:function(b){b?
"string"===f.type(b)?b=f(b):1===b.nodeType&&(b=f(b)):b=f(document.activeElement);if(b instanceof jQuery&&1<b.length){var c=this.md;a.i.mb(c,jQuery);for(var g=0;g<b.length;g++){var h=b[0];if(!a.ba.Co(c[0],h)){b=f(h);break}}}else if(!(b instanceof jQuery)||b instanceof jQuery&&0===b.length)b=f(document.activeElement);a.i.mb(b,jQuery);this.Nb=b},gG:function(b){var c=this.options;b&&(c.position=f.extend(c[b],b));b=c.position;c=this.ZG;a.i.xi(c);f.isFunction(b.using)&&b.using!==c&&(b.origUsing=b.using);
b.using=c;c=this.Nb;a.i.mb(c,jQuery);b.of||(b.of=c,b._ofo=!0)},$U:function(d,e){var f=e.element.element;a.i.mb(f,jQuery);var h=this.fD();if(h){h.hide();for(var k=0;k<c.length;k++)h.removeClass(c[k]),f.removeClass(c[k]);h.removeAttr("style");k=b[[e.horizontal,e.vertical].join("-")];a.i.Zr(k);h.addClass(k);f.addClass(k);h.show();"left"===e.horizontal||"right"===e.horizontal?(k=(h.outerWidth()-1)*("left"===e.horizontal?1:-1),d.left+=k):"center"===e.horizontal&&(k=(h.outerHeight()-1)*("top"===e.vertical?
1:-1),d.top+=k);f.css(d);"middle"===e.vertical?(f=f.height(),f=Math.round((f/2-h.outerHeight()/2)/f*100),h.css({top:f+"%"})):"center"===e.horizontal&&(f=f.width(),f=Math.round((f/2-h.outerWidth()/2)/f*100),h.css({left:f+"%"}));(h=this.options.position.origUsing)&&h(d,e)}else f.css(d)},me:function(){var b=this.md;a.i.mb(b,jQuery);var c=this.options.position;a.i.oe(c);var f="rtl"===this.Ec();b.position(a.he.Jg(c,f))},JD:function(b){var c=this.options;if(b||"none"!==c.initialFocus)if(b||"firstFocusable"===
c.initialFocus)b=this.element.find(":focusable"),0<b.length?(b=b[0],a.i.kf(b),f(b).focus()):(b=this.md,a.i.mb(b,jQuery),b.attr("tabindex","-1"),b.focus()),this._trigger("focus")},Wv:function(b){b||(b=document.activeElement);a.i.kf(b);if(!b)return!1;var c=this.md;a.i.mb(c,jQuery);return a.ba.Co(c[0],b)},CR:function(b){b||(b=document.activeElement);a.i.kf(b);var c=this.Nb;a.i.mb(c,jQuery);return a.ba.Co(c[0],b)},IT:function(){if(this.Wv()){var b=this.Nb;a.i.mb(b,jQuery);b.focus()}},ZD:function(b){if(!b.isDefaultPrevented()){var c=
b.target;a.i.kf(c);if(27===b.keyCode)b.preventDefault(),this.close();else if(117===b.keyCode)this.Wv(c)?(b.preventDefault(),b=this.Nb,a.i.mb(b,jQuery),b.focus()):this.CR(c)&&(b.preventDefault(),this.JD(!0));else if(9===b.keyCode&&this.Wv(c)){var g=this.element.find(":tabbable");if(0<g.length){var h=g[0];a.i.kf(h);g=g[g.length-1];a.i.kf(g);h===c&&b.shiftKey?(b.preventDefault(),f(g).focus()):g!==c||b.shiftKey||(b.preventDefault(),f(h).focus())}else b.preventDefault(),b=this.Nb,a.i.mb(b,jQuery),b.focus()}}},
Jw:function(a){var b=document.documentElement,c=this.rC;c&&(b.removeEventListener("mousedown",c,!0),b.removeEventListener("focus",c,!0),delete this.rC);"focusLoss"===a&&(c=this.rC=f.proxy(this.zO,this),b.addEventListener("mousedown",c,!0),b.addEventListener("focus",c,!0))},zO:function(b){var c=this.Nb,f=this.md;a.i.mb(c,jQuery);a.i.mb(f,jQuery);b=b.target;a.i.kf(b);a.ba.Co(c[0],b)||a.ba.Co(f[0],b)||this.close()},xM:function(){var b=this.Nb,c=this.md;a.i.mb(b,jQuery);a.i.mb(c,jQuery);var c=c.attr("id"),
g=b.attr("aria-describedby"),g=g?g.split(/\s+/):[];g.push(c);g=f.trim(g.join(" "));b.attr("aria-describedby",g)},pT:function(){var b=this.Nb,c=this.md;a.i.mb(b,jQuery);a.i.mb(c,jQuery);var c=c.attr("id"),g=b.attr("aria-describedby"),g=g?g.split(/\s+/):[],c=f.inArray(c,g);-1!==c&&g.splice(c,1);(g=f.trim(g.join(" ")))?b.attr("aria-describedby",g):b.removeAttr("aria-describedby")},RN:function(){var b=this.md;a.i.mb(b,jQuery);var c=this.fQ("ariaLive"),g=this.bw=f("\x3cdiv\x3e");g.attr({id:c,role:"log",
"aria-live":"polite","aria-relevant":"additions"});g.addClass("oj-helper-hidden-accessible");g.appendTo(document.body);b.data("oj-aria-controls",c)},PA:function(b){var c=this.bw;a.i.mb(c,jQuery);c.children().remove();a.fb.isEmpty(b)||f("\x3cdiv\x3e").text(b).appendTo(c)},xO:function(){var b=this.bw;a.i.mb(b,jQuery);b.remove();delete this.bw;b=this.md;a.i.mb(b,jQuery);b.removeData("oj-aria-controls")},fQ:function(a){return this.uuid+"_"+a}})})()});
//# sourceMappingURL=oj-modular.map