"use strict";
/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojeditablevalue"],function(a,f){a.Oa("oj._ojRadioCheckbox",f.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3cinput\x3e",widgetEventPrefix:"oj",options:{disabled:null,checked:null,type:null},label:function(){void 0===this.Qb&&(this.Qb=this.fv());return this.Qb},refresh:function(){this._super();this.sb()},widget:function(){return this.vJ},_InitOptions:function(a,b){this._super(a,b);if(null===this.options.checked)this.options.checked=void 0!==this.element.attr("checked")?
!!this.element.prop("checked"):!1;else if("boolean"!==typeof this.options.checked)throw Error("checked option must be a boolean");if(null===this.options.disabled)this.options.disabled=void 0!==this.element.attr("disabled")?!!this.element.prop("disabled"):!1;else if("boolean"!==typeof this.options.disabled)throw Error("disabled option must be a boolean");this.options.type=this.element.prop("type")},_ComponentCreate:function(){this._super();var a=this.options.type;"checkbox"==a?(this.vJ=this.element.addClass("oj-checkbox oj-component"),
this.Qb=this.fv(),this.Qb.addClass("oj-checkbox-label")):"radio"==a&&(this.vJ=this.element.addClass("oj-radio oj-component"),this.Qb=this.fv(),this.Qb.addClass("oj-radio-label"));var b=this;this._hoverable(this.element);this._focusable(this.element);this.Lp(this.element);f.each(b.Qb,function(){b._hoverable(this);b._focusable(this);b.Lp(this)});this._on(this.Jf)},Rh:function(){this._super();this.sb()},sb:function(){this.BF();this.options.checked?this._setOption("checked",!0):this._setOption("checked",
!1)},BF:function(){this.ed()?(this.element.prop("disabled",!0).removeAttr("aria-disabled").removeClass("oj-enabled").addClass("oj-disabled"),this.Qb.removeClass("oj-enabled").addClass("oj-disabled")):(this.element.prop("disabled",!1).removeAttr("aria-disabled").removeClass("oj-disabled").addClass("oj-enabled"),this.Qb.addClass("oj-enabled").removeClass("oj-disabled"))},Jf:{},_setOption:function(a,b){this._superApply(arguments);"disabled"===a&&(b=!!b,this.BF(b));"checked"===a&&(b?this.element.prop("checked",
!0):this.element.prop("checked",!1),this.element.toggleClass("oj-selected",b))},fv:function(){var a=this.element.closest("label"),b="label[for\x3d'"+this.element.prop("id")+"']";return a.add(f(b))},getNodeBySubId:function(a){var b=this._super(a);b||(a=a.subId,"oj-radiocheckbox-input"===a&&(b=this.element[0]),"oj-radiocheckbox-label"===a&&(b=this.label()[0]));return b||null},_destroy:function(){var a=this.options.type;"checkbox"==a?this.Qb.removeClass("oj-enabled oj-disabled oj-checkbox-label"):"radio"==
a&&this.Qb.removeClass("oj-enabled oj-disabled oj-radio-label");this.vk();return this._super()}})});
//# sourceMappingURL=oj-modular.map