"use strict";
/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojeditablevalue","ojs/ojradiocheckbox"],function(a,f){a.Oa("oj.ojRadioset",f.oj.editableValue,{version:"1.0.0",defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{disabled:null,value:void 0},refresh:function(){this._super();this.Af.each(function(){var a=void 0!==f(this).attr("disabled")?!!f(this).prop("disabled"):!1;f(this)._ojRadioCheckbox("option","disabled",a)});this.Af=this.uq().filter(".oj-radio")._ojRadioCheckbox("refresh").end().not(".oj-radio")._ojRadioCheckbox().end();
this.sb()},widget:function(){return this.wJ},_InitOptions:function(c,b){var d,e;this._super(c,b);a.td.Ki([{attribute:"disabled",defaultOptionValue:!1,validateOption:!0},{attribute:"placeholder",defaultOptionValue:""},{attribute:"required",defaultOptionValue:!1,coerceDomValue:!0,validateOption:!0},{attribute:"title",defaultOptionValue:""}],b,this);void 0===b.value&&(d=this.uq(),d=d.filter(":checked"),d=0===d.length?void 0:d.val(),void 0!==d&&(e=this.options.value,this.options.value=d,this.ht("value",
e)),void 0===this.options.value&&(this.options.value=null))},_ComponentCreate:function(){this._super();if(this.element.is("fieldset"))throw Error("ojRadioset cannot be bound to a fieldset. Use a div instead.");this.Af=this.uq()._ojRadioCheckbox();this.wJ=this.element.addClass("oj-radioset oj-component").attr("role","radiogroup");this._on(this.Jf);this.sb()},Focus:function(){this.Ae().first().focus();return!0},uq:function(){var c=this.element.find("input[type\x3dradio]:first");0===c.length&&a.D.warn("Could not find any input type\x3dradio within this element");
c=c.attr("name");return void 0===c?(c=this.element.find("input[type\x3dradio]"),c.not("[name]")):this.element.find("input[type\x3dradio][name\x3d"+c+"]")},_OpenContextMenu:function(a,b){var d=this.element.find("input[type\x3dradio]"),e=d.filter(":checked"),d=e.length?e:d.filter(":enabled").first();a.open(b,{launcher:d,initialFocus:"menu"})},sb:function(){!0===this.options.disabled?this.disable():!1===this.options.disabled&&this.enable()},Jf:{change:function(a){this.rp(a)}},rp:function(a){this._super(a)},
Yg:function(){return this.sk()},ig:function(a){null!=a&&(a="[value\x3d'"+a+"']",void 0!==a&&void 0!==this.Af&&(a=this.Af.filter(a),void 0!==a&&0<a.length?a.prop("checked")||a._ojRadioCheckbox("option","checked",!0):this.Af._ojRadioCheckbox("option","checked",!1)))},sk:function(){var a=this.Af.filter(":checked");return 0===a.length?null:a.val()},_GetDefaultStyleClass:function(){return"oj-radioset"},Ae:function(){return this.uq()},tt:function(a){var b=this.wJ;a&&b?b.attr("aria-required",a):b.removeAttr("aria-required")},
_setOption:function(a,b){this._superApply(arguments);"disabled"===a&&(this.Af.each(function(){f(this).data("oj-_ojRadioCheckbox").Dm(b)}),this.Af._ojRadioCheckbox("refresh"))},getNodeBySubId:function(a){var b=this._super(a);b||(a=a.subId,"oj-radioset-inputs"===a&&(b=this.Af));return b||null},_destroy:function(){this.Af&&this.Af._ojRadioCheckbox("destroy");this.vk();return this._super()}})});
//# sourceMappingURL=oj-modular.map