/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojmodel","ojs/ojdatacollection-common"],function(a,f){a.Oa("oj.ojRowExpander",f.oj.baseComponent,{version:"1.0.0",widgetEventPrefix:"oj",options:{context:null,expand:null,collapse:null},wg:{root:"oj-rowexpander",icon:"oj-component-icon",clickable:"oj-clickable-icon-nocontext",expand:"oj-rowexpander-expand-icon",collapse:"oj-rowexpander-collapse-icon",leaf:"oj-rowexpander-leaf-icon",lazyload:"oj-rowexpander-lazyload-icon",toucharea:"oj-rowexpander-touch-area",
indent:"oj-rowexpander-indent",iconspacer:"oj-rowexpander-icon-spacer",depth0:"oj-rowexpander-depth-0",depth1:"oj-rowexpander-depth-1",depth2:"oj-rowexpander-depth-2",depth3:"oj-rowexpander-depth-3",depth4:"oj-rowexpander-depth-4",depth5:"oj-rowexpander-depth-5",depth6:"oj-rowexpander-depth-6",depth7:"oj-rowexpander-depth-7"},xl:{im:7,YJ:53},_ComponentCreate:function(){this._super();this.element.addClass(this.wg.root);this.BD()},BD:function(){var a=this,b;b=this.options.context;this.va=b.component;
this.hc=b.datasource;this.depth=b.depth;this.Cg=b.state;this.Vi=b.key;this.index=b.index;this.Ds=b.parentKey;this.zM();this.yM();this.Er();if("expanded"===this.Cg||"collapsed"===this.Cg)f(this.sJ).on("click",function(b){b.preventDefault();a.mC()}),f(this.element).on("keypress",function(b){if((b.keyCode||b.which)===f.ui.keyCode.ENTER||f.ui.keyCode.SPACE)a.mC(),b.preventDefault(),b.target.focus()}),null!=this.va&&(this.sI=this.AQ.bind(this),f(this.va.element).on("ojkeydown",this.sI)),null!=this.hc&&
(this.rI=this.vQ.bind(this),this.qI=this.nQ.bind(this),this.hc.on("expand",this.rI,this),this.hc.on("collapse",this.qI,this));null!=this.va&&(this.pI=this.mQ.bind(this),f(this.va.element).on("ojactive",this.pI))},refresh:function(){this.element.empty();this.BD()},_destroy:function(){null!=this.va&&(f(this.va.element).off("ojkeydown",this.sI),f(this.va.element).off("ojactive",this.pI));null!=this.hc&&(this.hc.off("expand",this.rI,this),this.hc.off("collapse",this.qI,this));this.removeClass(this.wg.root);
this.element.empty()},_setOption:function(a,b,d){this._super(a,b,d);"context"==a&&this.refresh()},zM:function(){var a,b;b=this.depth-1;if(b<this.xl.im)this.Gt(b);else{for(a=1;a<=b/this.xl.im;a++)this.Gt(this.xl.im);a=b%this.xl.im;a<this.xl.im&&this.Gt(a)}},Gt:function(a){a=f(document.createElement("span")).addClass(this.wg.indent).addClass(this.wg["depth"+a]);this.element.append(a)},yM:function(){var a=f(document.createElement("div")).addClass(this.wg.iconspacer);this.sJ=f(document.createElement("div")).addClass(this.wg.toucharea);
this.icon=f(document.createElement("a")).attr("href","#").addClass(this.wg.icon).addClass(this.wg.clickable);this.element.append(a.append(this.sJ.append(this.icon)))},gj:function(a){this.icon.addClass(this.wg[a])},Jj:function(a){this.icon.removeClass(this.wg[a])},Er:function(){switch(this.Cg){case "leaf":this.Jj("icon");this.Jj("clickable");this.gj("leaf");break;case "collapsed":this.gj("expand");this.Qp(!1);break;case "expanded":this.gj("collapse");this.Qp(!0);break;case "loading":this.Jj("clickable"),
this.gj("lazyload")}},Gw:function(){switch(this.Cg){case "leaf":this.Jj("leaf");this.gj("icon");this.gj("clickable");break;case "collapsed":this.Jj("expand");break;case "expanded":this.Jj("collapse");break;case "loading":this.Jj("lazyload"),this.gj("clickable")}},mQ:function(a,b){var d,e;null!=b.activeKey&&(d=b.activeKey.rowKey,this.Vi!==d||null!=b.previousActiveKey&&b.previousActiveKey.row==b.activeKey.row||!this.va.Ar||(d=this.O("accessibleRowDescription",{level:this.depth,num:this.index+1,total:this.hc.getWrappedDataSource().Yd(this.Ds)}),
e="collapsed"===this.Cg?this.O("accessibleStateCollapsed"):"expanded"===this.Cg?this.O("accessibleStateExpanded"):"",this.va.Ar({context:d,state:e})))},AQ:function(c,b){var d;this.Vi===b.rowKey&&(d=c.keyCode||c.which,a.ba.Ho(c)&&(d==f.ui.keyCode.RIGHT?(this.dw(),this.hc.expand(this.Vi)):d==f.ui.keyCode.LEFT?(this.dw(),this.hc.collapse(this.Vi)):c.altKey&&d==this.xl.YJ&&this.va.Ar&&(d=this.O("accessibleRowDescription",{level:this.depth,num:this.index+1,total:this.hc.getWrappedDataSource().Yd(this.Ds)}),
this.va.Ar({context:d,state:""}))))},dw:function(){this.Gw();this.Cg="loading";this.Er()},vQ:function(a){a=a.rowKey;a===this.Vi&&(this.Gw(),this.Cg="expanded",this.Er(),this.Qp(!0),this._trigger("expand",null,{rowKey:a}))},nQ:function(a){a=a.rowKey;a===this.Vi&&(this.Gw(),this.Cg="collapsed",this.Er(),this.Qp(!1),this._trigger("collapse",null,{rowKey:a}))},mC:function(){var a=this.Cg;this.dw();"collapsed"===a?this.hc.expand(this.Vi):"expanded"===a&&this.hc.collapse(this.Vi)},Qp:function(a){this.icon.attr("aria-expanded",
a)},getNodeBySubId:function(a){return null==a?this.element?this.element[0]:null:"oj-rowexpander-icon"===a.subId?this.icon:null}})});
//# sourceMappingURL=oj-modular.map