"use strict";
/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2012 Igor Vaynberg

 This software is licensed under the Apache License, Version 2.0 (the "Apache License") or the GNU
 General Public License version 2 (the "GPL License"). You may choose either license to govern your
 use of this software only upon the condition that you accept all of the terms of either the Apache
 License or the GPL License.

 You may obtain a copy of the Apache License and the GPL License at:

 http://www.apache.org/licenses/LICENSE-2.0
 http://www.gnu.org/licenses/gpl-2.0.html

 Unless required by applicable law or agreed to in writing, software distributed under the
 Apache License or the GPL Licesnse is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 CONDITIONS OF ANY KIND, either express or implied. See the Apache License and the GPL License for
 the specific language governing permissions and limitations under the Apache License and the GPL License.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2012 Igor Vaynberg

 This software is licensed under the Apache License, Version 2.0 (the "Apache License") or the GNU
 General Public License version 2 (the "GPL License"). You may choose either license to govern your
 use of this software only upon the condition that you accept all of the terms of either the Apache
 License or the GPL License.

 You may obtain a copy of the Apache License and the GPL License at:

 http://www.apache.org/licenses/LICENSE-2.0
 http://www.gnu.org/licenses/gpl-2.0.html

 Unless required by applicable law or agreed to in writing, software distributed under the
 Apache License or the GPL Licesnse is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 CONDITIONS OF ANY KIND, either express or implied. See the Apache License and the GPL License for
 the specific language governing permissions and limitations under the Apache License and the GPL License.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2012 Igor Vaynberg

 This software is licensed under the Apache License, Version 2.0 (the "Apache License") or the GNU
 General Public License version 2 (the "GPL License"). You may choose either license to govern your
 use of this software only upon the condition that you accept all of the terms of either the Apache
 License or the GPL License.

 You may obtain a copy of the Apache License and the GPL License at:

 http://www.apache.org/licenses/LICENSE-2.0
 http://www.gnu.org/licenses/gpl-2.0.html

 Unless required by applicable law or agreed to in writing, software distributed under the
 Apache License or the GPL Licesnse is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 CONDITIONS OF ANY KIND, either express or implied. See the Apache License and the GPL License for
 the specific language governing permissions and limitations under the Apache License and the GPL License.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2012 Igor Vaynberg

 This software is licensed under the Apache License, Version 2.0 (the "Apache License") or the GNU
 General Public License version 2 (the "GPL License"). You may choose either license to govern your
 use of this software only upon the condition that you accept all of the terms of either the Apache
 License or the GPL License.

 You may obtain a copy of the Apache License and the GPL License at:

 http://www.apache.org/licenses/LICENSE-2.0
 http://www.gnu.org/licenses/gpl-2.0.html

 Unless required by applicable law or agreed to in writing, software distributed under the
 Apache License or the GPL Licesnse is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 CONDITIONS OF ANY KIND, either express or implied. See the Apache License and the GPL License for
 the specific language governing permissions and limitations under the Apache License and the GPL License.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2012 Igor Vaynberg

 This software is licensed under the Apache License, Version 2.0 (the "Apache License") or the GNU
 General Public License version 2 (the "GPL License"). You may choose either license to govern your
 use of this software only upon the condition that you accept all of the terms of either the Apache
 License or the GPL License.

 You may obtain a copy of the Apache License and the GPL License at:

 http://www.apache.org/licenses/LICENSE-2.0
 http://www.gnu.org/licenses/gpl-2.0.html

 Unless required by applicable law or agreed to in writing, software distributed under the
 Apache License or the GPL Licesnse is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 CONDITIONS OF ANY KIND, either express or implied. See the Apache License and the GPL License for
 the specific language governing permissions and limitations under the Apache License and the GPL License.
*/
define(["ojs/ojcore","jquery","ojs/ojeditablevalue"],function(a,f){var c={Qa:{TAB:9,ENTER:13,Ns:27,SPACE:32,LEFT:37,UP:38,RIGHT:39,DOWN:40,dK:16,FJ:17,CJ:18,PAGE_UP:33,PAGE_DOWN:34,HOME:36,END:35,ep:8,Ty:46,xI:function(a){switch(a.which){case c.Qa.dK:case c.Qa.FJ:case c.Qa.CJ:return!0}return a.metaKey?!0:!1},zI:function(a){a=a.which?a.which:a;return 112<=a&&123>=a}},fy:{x:0,y:0},To:function(){var a=1;return function(){return a++}}(),bJ:null,Bi:function(a,b){for(var c=f(a[0]),d=-1,e=a.length;++d<e&&
(c.context=c[0]=a[d])&&!1!==b.call(c[0],d,c););return a},PW:function(){var a=f("\x3cdiv class\x3d'oj-listbox-measure-scrollbar'\x3e\x3c/div\x3e");a.appendTo("body");var b={width:a.width()-a[0].clientWidth,height:a.height()-a[0].clientHeight};a.remove();return b},gk:function(a,b){var c,d,e;if(null===a||1>a.length)return[];c=a.split(b);d=0;for(e=c.length;d<e;d+=1)c[d]=f.trim(c[d]);return c},cI:function(a){return a.outerWidth(!1)-a.width()},FW:function(a){a.on("keydown",function(){void 0===f.data(a,
"keyup-change-value")&&f.data(a,"keyup-change-value",a.val())});a.on("keyup",function(b){b.which===c.Qa.ENTER?b.stopPropagation():(b=f.data(a,"keyup-change-value"),void 0!==b&&a.val()!==b&&(f.removeData(a,"keyup-change-value"),a.trigger("keyup-change")))})},EW:function(a){a.on("mousemove",function(a){var b=c.fy;if(void 0===b||b.x!==a.pageX||b.y!==a.pageY)f(a.target).trigger("mousemove-filtered",a),c.fy.x=a.pageX,c.fy.y=a.pageY})},CX:function(a){var b=!1,c;return function(){!1===b&&(c=a(),b=!0);return c}},
Qd:function(a){a[0]!==document.activeElement&&window.setTimeout(function(){var b=a[0],c=a.val().length;a.focus();a.is(":visible")&&b===document.activeElement&&(b.setSelectionRange?b.setSelectionRange(c,c):b.createTextRange&&(b=b.createTextRange(),b.collapse(!1),b.select()))},0)},eW:function(a){a=f(a)[0];var b=0,c=0;"selectionStart"in a?(b=a.selectionStart,c=a.selectionEnd-b):"selection"in document&&(a.focus(),b=document.selection.createRange(),c=document.selection.createRange().text.length,b.moveStart("character",
-a.value.length),b=b.text.length-c);return{offset:b,length:c}},Sc:function(a){a.preventDefault();a.stopPropagation()},JW:function(a){a.preventDefault();a.stopImmediatePropagation()},QV:function(a){var b={"\\":"\x26#92;","\x26":"\x26amp;","\x3c":"\x26lt;","\x3e":"\x26gt;",'"':"\x26quot;","'":"\x26#39;"};return String(a).replace(/[&<>"'\\]/g,function(a){return b[a]})},MW:function(a,b){function d(a){return""+a.label}var e=a,g,h;f.isArray(e)&&(h=e,e={kc:h});!1===f.isFunction(e)&&(h=e,e=function(){return h});
var p=e();p&&p.text&&(d=p.text,f.isFunction(d)||(g=p.text,d=function(a){return a[g]}));return function(a){var g=a.Ls,p={kc:[]},h;""===g?a.gc(e()):(h=function(b,e,p){var l,k;b=b[0];!b.label&&p&&p.label&&(b.label=b[p.label],delete b[p.label]);!b.value&&p&&p.value&&(b.value=b[p.value],delete b[p.value]);!b.children&&p&&p.children&&(b.children=b[p.children],delete b[p.children]);if(b.children){l={};for(k in b)b.hasOwnProperty(k)&&(l[k]=b[k]);l.children=[];c.Bi(f(b.children),function(a,b){h(b,l.children,
p&&p.childKeys?p.childKeys:null)});(l.children.length||a.bk(g,d(l),b))&&e.push(l)}else a.bk(g,d(b),b)&&e.push(b)},e()&&c.Bi(f(e().kc),function(a,c){h(c,p.kc,b)}),a.gc(p))}},yV:function(a,b,c){if(f.isFunction(b))return!0;if(!b)return!1;throw Error(c+" must be a function or a false value");},lo:function(b,c){function d(){}a.b.sa(d,b,"");d.prototype=f.extend(d.prototype,c);return d}},b=c.lo(Object,{rc:function(a){var b=this;return function(){a.apply(b,arguments)}},_init:function(b){var d,e=this.Ha,g=
this.sc;this.ae=b.ae;this.da=b=this.Mn(b);this.id=b.id;void 0!==b.element.data(g)&&null!==b.element.data(g)&&b.element.data(g)._destroy();this.ua=this.ou();var h=this.da.rootAttributes;this.Rj=h&&h.id?h.id:"ojChoiceId_"+(b.element.attr("id")||"autogen"+c.To());this.Rj.replace(/([;&,\.\+\*\~':"\!\^#$%@\[\]\(\)=>\|])/g,"\\$1");this.ua.attr("id",this.Rj);this.body=c.CX(function(){return b.element.closest("body")});this.ua.attr("style",b.element.attr("style"));this.Ex=this.da.element.attr("tabindex");
this.da.element.data(g,this).attr("tabindex","-1").before(this.ua);this.ua.data(g,this);this.Cc=this.ua.find(".oj-listbox-drop");this.Cc.data("ojlistbox",this);this.Cc.on("click",c.Sc);this.Cc.attr(a.ba.dg,this.Rj);this.kc=this.ua.find(".oj-listbox-results");this.search=d="oj-select"==e?this.ua.find("input.oj-listbox-input"):this.ua.find("input."+e+"-input");this.zy=this.ZI=0;this.context=null;this.Xq();this.ua.on("click",c.Sc);c.EW(this.kc);this.Cc.on("mousemove-filtered touchstart touchmove touchend",
".oj-listbox-results",this.rc(this.wD));f(this.ua).on("change","."+e+"-input",function(a){a.stopPropagation()});f(this.Cc).on("change","."+e+"-input",function(a){a.stopPropagation()});c.FW(d);d.on("keyup-change input paste",this.rc(this.Ur));d.on("focus",function(){d.addClass(e+"-focused")});d.on("blur",function(){d.removeClass(e+"-focused")});this.Cc.on("mouseup",".oj-listbox-results",this.rc(function(a){0<f(a.target).closest(".oj-listbox-result-selectable").length&&(this.wD(a),this.zr(null,a))}));
this.Cc.on("click mouseup mousedown",function(a){a.stopPropagation()});f.isFunction(this.da.Ji)&&this.Wk();h=b.element.prop("disabled");void 0===h&&(h=!1);this.ai(!h);h=b.element.prop("readonly");void 0===h&&(h=!1);this.dl(h);c.bJ=c.bJ||c.PW();this.autofocus=b.element.prop("autofocus");b.element.prop("autofocus",!1);this.autofocus&&this.Qd();(h=f(document).data("ojChoiceClickAwayHandler-"+g))?h.no.push(this):(h=function(a){var b=f("#oj-listbox-drop");!f(a.target).closest(b).length&&0<b.length&&(b=
b.data("ojlistbox"),b.da.kX&&b.zr({OI:!0},a),b.close(a))},document.addEventListener("mousedown",h,!0),h={KW:h,no:[]},h.no.push(this),f(document).data("ojChoiceClickAwayHandler-"+g,h))},_destroy:function(){var a=this.da.element,b=a.data(this.sc);this.close();this.YI&&(delete this.YI,this.YI=null);void 0!==b&&(b.ua.remove(),b.Cc.remove(),a.removeAttr("aria-hidden").removeData(this.sc).off("."+this.Ha).prop("autofocus",this.autofocus||!1),this.Ex?a.attr({jZ:this.Ex}):a.removeAttr("tabindex"),a.show());
a=f(document).data("ojChoiceClickAwayHandler-"+this.sc);b=a.no.indexOf(this);-1<b&&(a.no.splice(b,1),a.no.length||(document.removeEventListener("mousedown",a.KW,!0),f(document).removeData("ojChoiceClickAwayHandler-"+this.sc)))},al:function(a){if(a.is("option"))return{value:a.prop("value"),label:a.text(),element:a.get(),css:a.attr("class"),disabled:a.prop("disabled"),locked:"locked"===a.attr("locked")||!0===a.data("locked")};if(a.is("optgroup"))return{label:a.attr("label"),children:[],element:a.get(),
css:a.attr("class")}},Mn:function(a){var b,e,g=this;b=a.element;var h=b.get(0).tagName.toLowerCase();"input"===h&&b.attr("list")?this.Ai=e=f("#"+b.attr("list")):"select"===h&&0<b.children().length&&(this.Ai=e=b);a=f.extend({},{WW:function(b,d,e,h){var k,m=this.da.id;k=function(b,d,h,p){var s,n,r,t,C;s=g.wj();p&&null!==s&&!e.Ls&&(n={value:"",label:s},C=f("\x3cli\x3e\x3c/li\x3e"),C.addClass("oj-listbox-placeholder oj-listbox-results-depth-0 oj-listbox-result oj-listbox-result-selectable"),C.attr("role",
"presentation"),r=f(document.createElement("div")),r.addClass("oj-listbox-result-label"),r.attr("id","oj-listbox-result-label-"+c.To()),r.attr("role","option"),t=a.JH(n),void 0!==t&&r.text(t),C.append(r),C.data(g.sc,n),d.append(C));p=0;for(s=b.length;p<s;p+=1)n=b[p],t=!0===n.disabled,r=!t&&void 0!==m(n),C=f("\x3cli\x3e\x3c/li\x3e"),C.addClass("oj-listbox-results-depth-"+h),C.addClass("oj-listbox-result"),C.addClass(r?"oj-listbox-result-selectable":"oj-listbox-result-unselectable"),t&&C.addClass("oj-disabled"),
n.children&&C.addClass("oj-listbox-result-with-children"),C.attr("role","presentation"),r=f(document.createElement("div")),r.addClass("oj-listbox-result-label"),r.attr("id","oj-listbox-result-label-"+c.To()),r.attr("role","option"),t&&r.attr("aria-disabled","true"),t=a.JH(n),void 0!==t&&r.text(t),C.append(r),n.children&&0<n.children.length&&(t=f("\x3cul\x3e\x3c/ul\x3e"),t.addClass("oj-listbox-result-sub"),k(n.children,t,h+1,!1),C.append(t)),C.data(g.sc,n),d.append(C)};k(d,b,0,h)}},d,a);a.id=function(a){return a.value};
a.JH=function(b){var c=[];c.push(a.hs(b.label));return c.join("")};a.Hx=function(a,b,c){return a&&a.label?c(a.label):void 0};"select"!==h&&null!==a.manageNewEntry&&(a.manageNewEntry=function(a){var b={};b.value=b.label=f.trim(a);return b});e?a.Gs=this.rc(function(a){var b={kc:[],VY:!1},d=a.Ls,f,h;h=function(b,e){var f;b.is("option")?a.bk(d,b.text(),b)&&e.push(g.al(b)):b.is("optgroup")&&(f=g.al(b),c.Bi(b.children(),function(a,b){h(b,f.children)}),0<f.children.length&&e.push(f))};f=e.children();void 0!==
this.wj()&&0<f.length&&""==f.first().attr("value")&&(f=f.slice(1));c.Bi(f,function(a,c){h(c,b.kc)});a.gc(b)}):"options"in a&&(a.Gs=c.MW(a.options,a.optionsKeys?a.optionsKeys:null));return a},LG:function(a){a=f.Event(this.sc+"-selecting",{val:this.id(a),object:a});this.da.element.trigger(a);return!a.isDefaultPrevented()},og:function(){return!0===this.CH},Ik:function(){var a=this.Jk&&!this.dl;if(a===this.CH)return!1;this.ua.toggleClass("oj-disabled",!a);this.close();this.CH=a;return!0},ai:function(a){void 0===
a&&(a=!0);this.Jk!==a&&(this.Jk=a,this.da.element.prop("disabled",!a),this.Ik())},WB:function(){this.ai(!1)},dl:function(a){void 0===a&&(a=!1);if(this.dl===a)return!1;this.dl=a;this.da.element.prop("readonly",a);this.Ik();return!0},ld:function(){return this.ua.hasClass("oj-listbox-dropdown-open")},Kn:function(){var a=this.Cc,b=this.ua.offset(),c=this.ua.outerHeight(!1),d=this.ua.outerWidth(!1),e=a.outerHeight(!1),g=f(window),h=g.width(),k=g.height(),s=g.scrollLeft()+h,v=g.scrollTop()+k,c=b.top+c,
z=b.left,v=c+e<=v,w=b.top-e>=this.body().scrollTop(),y=a.outerWidth(!1),s=z+y<=s,H;a.hasClass("oj-listbox-drop-above")?(e=!0,!w&&v&&(H=!0,e=!1)):(e=!1,!v&&w&&(e=H=!0));H?(a.hide(),b=this.ua.offset(),c=this.ua.outerHeight(!1),d=this.ua.outerWidth(!1),a.outerHeight(!1),s=g.scrollLeft()+h,g.scrollTop(),c=b.top+c,!e&&this.yj()&&(c-=1),z=b.left,y=a.outerWidth(!1),s=z+y<=s,a.show()):!e&&this.yj()&&(c-=1);"static"!==this.body().css("position")&&(g=this.body().offset(),c-=g.top,z-=g.left);s||(z=b.left+d-
y);d={left:z,width:d};e?(d.bottom=k-b.top,d.top="auto",this.ua.addClass("oj-listbox-drop-above"),a.addClass("oj-listbox-drop-above")):(d.top=c,d.bottom="auto",this.ua.removeClass("oj-listbox-drop-above"),a.removeClass("oj-listbox-drop-above"));a.css(d)},mG:function(){var a;if(this.ld()||!1===this.Jk||!0===this.dl)return!1;a=f.Event(this.sc+"-opening");this.da.element.trigger(a);return!a.isDefaultPrevented()},rB:function(){this.ua.removeClass("oj-listbox-drop-above");this.Cc.removeClass("oj-listbox-drop-above")},
open:function(a){if(!this.mG(a))return!1;this.Ij();return!0},Ij:function(){var a=this.Rj,b="scroll."+a,c="resize."+a,d="orientationchange."+a;this.ua.addClass("oj-listbox-dropdown-open");this.rB();this.Cc[0]!==this.body().children().last()[0]&&this.Cc.detach().appendTo(this.body());this.Cc.appendTo(this.body());f("#oj-listbox-drop").removeAttr("id");this.Cc.attr("id","oj-listbox-drop");this.Kn();this.Cc.show();this.Kn();this.zq().attr("aria-expanded",!0);var e=this;this.ua.parents().add(window).each(function(){f(this).on(c+
" "+b+" "+d,function(){e.Kn()})})},close:function(){if(this.ld()){var a=this.Rj,b="scroll."+a,c="resize."+a,d="orientationchange."+a;this.ua.parents().add(window).each(function(){f(this).off(b).off(c).off(d)});this.rB();this.Cc.removeAttr("id");this.Cc.hide();this.ua.removeClass("oj-listbox-dropdown-open");this.kc.empty();this.zq().attr("aria-expanded",!1)}},Xh:function(){},NO:function(){var a=this.kc,b,c,d,e;c=this.Bj();0>c||(0==c?a.scrollTop(0):(b=this.Ym().find(".oj-listbox-result-label"),d=f(b[c]),
e=d.offset().top+d.outerHeight(!0),c===b.length-1&&(b=a.find("li.oj-listbox-more-results"),0<b.length&&(e=b.offset().top+b.outerHeight(!0))),b=a.offset().top+a.outerHeight(!0),e>b&&a.scrollTop(a.scrollTop()+(e-b)),e=d.offset().top-a.offset().top,0>e&&"none"!=d.css("display")&&a.scrollTop(a.scrollTop()+e)))},Ym:function(){return this.kc.find(".oj-listbox-result-selectable:not(.oj-disabled, .oj-selected)")},uE:function(a){for(var b=this.Ym(),c=this.Bj();-1<=c&&c<b.length;){var c=c+a,d=f(b[c]);if(d.hasClass("oj-listbox-result-selectable")&&
!d.hasClass("oj-disabled")&&!d.hasClass("oj-selected")){this.Bj(c);break}}},Bj:function(a){var b=this.Ym();if(0===arguments.length)return b.get().indexOf(b.filter(".oj-hover")[0]);a>=b.length&&(a=b.length-1);0>a&&(a=0);this.Fw();b=f(b[a]);b.addClass("oj-hover");this.zq().attr("aria-activedescendant",b.find(".oj-listbox-result-label").attr("id"));this.NO()},Fw:function(){this.kc.find(".oj-hover").removeClass("oj-hover")},wD:function(a){a=f(a.target).closest(".oj-listbox-result-selectable");if(0<a.length&&
!a.is(".oj-hover")){var b=this.Ym();this.Bj(b.index(a))}else 0==a.length&&this.Fw()},Ur:function(a){var b=this.search,d=this.kc,e=this.da,g=this,h;h=b.val();var p=f.data(this.ua,this.Ha+"-last-term"),k;!0!==a&&p&&h===p||(f.data(this.ua,this.Ha+"-last-term",h),k=++this.ZI,this.Fw(),h=this.search.val(),this.zy=1,e.Gs({element:e.element,Ls:void 0!==h&&null!=h&&!0!==a?h:"",page:this.zy,context:null,bk:e.bk,gc:this.rc(function(f){k==this.ZI&&this.ld()&&(this.context=f&&void 0!==f.context?f.context:null,
f&&0!==f.kc.length||!c.yV(g.ae,e.IH,"formatNoMatches")?(d.empty(),g.da.WW.call(this,d,f.kc,{Ls:b.val(),page:this.zy,context:null},this.pG()),this.Ln(f,a),g.Kn()):"oj-select"==this.Ha?(f="\x3cli class\x3d'oj-listbox-no-results'\x3e"+e.IH(g.ae,b.val())+"\x3c/li\x3e",d.html(f),g.Kn()):this.close())})}))},$t:function(a){this.close(a)},Zm:function(){c.Qd(this.search)},zr:function(a,b){var c=this.Bj(),d=this.kc.find(".oj-hover").closest(".oj-listbox-result").data(this.sc);d?(this.Bj(c),this.pr(d,a,b)):
a&&a.OI&&this.close(b)},wj:function(){return this.da.element.attr("placeholder")||this.da.element.attr("data-placeholder")||this.da.element.data("placeholder")||this.da.placeholder},pi:function(){var a=this.wj();a&&(this.search.attr("placeholder",a),this.ua.removeClass(this.Ha+"-allowclear"))},AD:function(){var a;a:{var b,c,d;a=this.da.element.attr("style");if(void 0!==a)for(a=a.split(";"),c=0,d=a.length;c<d;c+=1)if(b=a[c].replace(/\s/g,""),b=b.match(/^width:(([-+]?([0-9]*\.)?[0-9]+)(px|em|ex|%|in|cm|mm|pt|pc))/i),
null!==b&&1<=b.length){a=b[1];break a}a=void 0}null!==a&&this.ua.css("width",a)},vb:function(){return this.ae.option("value")},Xi:function(a,b){"string"===typeof a?this.ae.ie([a],b,{oo:!1}):this.ae.ie(a,b,{oo:!1});this.da.element.val(a)},pG:function(){return!1},zq:function(){return this.search},yj:function(){return void 0!==this.da.minimumResultsForSearch&&void 0!==this.ua.yj}}),d={yx:!0,SW:!0,IH:function(){return"No matches found"},id:function(a){return a.id},bk:function(a,b){return 0<=(""+b).toUpperCase().indexOf((""+
a).toUpperCase())},separator:",",hs:c.QV,JY:!1,kX:!1},e=c.lo(b,{Ik:function(){e.t.Ik.apply(this,arguments)&&this.search.prop("disabled",!this.og())},Qd:function(){this.ld()&&this.close()},_destroy:function(){f("label[for\x3d'"+this.search.attr("id")+"']").attr("for",this.da.element.attr("id"));e.t._destroy.apply(this,arguments)},eu:function(b){this.selection.data(this.sc)&&(b||a.D.warn("Event should not be null when user modified the value in UI"),this.Xi([],b),this.search.val(""),this.selection.removeData(this.sc));
this.pi()},Wk:function(){this.da.Ji.call(null,this.Ai?this.Ai:this.da.element,this.rc(this.WG))},cq:function(a){if(this.og())if(a.which===c.Qa.PAGE_UP||a.which===c.Qa.PAGE_DOWN)c.Sc(a);else{switch(a.which){case c.Qa.UP:case c.Qa.DOWN:this.ld()?this.uE(a.which===c.Qa.UP?-1:1):this.open(a);c.Sc(a);return;case c.Qa.ENTER:this.zr(null,a);c.Sc(a);return;case c.Qa.TAB:this.close(a);return;case c.Qa.Ns:this.$t(a);c.Sc(a);return}this.YG=!0;this.ld()||this.open(a)}},GN:function(a){this.og()&&!this.ld()&&this.open(a)},
Xq:function(){var a;a=this.ua;var b=c.To(),d;this.selection=a=a.find("."+this.Ha+"-choice");a.attr("id",this.Ha+"-choice-"+b);d=f("label[for\x3d'"+this.da.element.attr("id")+"']");d.attr("id")||d.attr("id",this.Ha+"-label-"+b);a.find("."+this.Ha+"-input").attr("id",this.Ha+"-input-"+b);this.kc.attr("id","oj-listbox-results-"+b);this.search.attr("aria-owns","oj-listbox-results-"+b);this.search.attr("aria-labelledby",d.attr("id"));a.on("keydown",this.rc(this.cq));a.on("mousedown","abbr",this.rc(function(a){this.og()&&
(this.eu(a),c.JW(a),this.close(a),this.selection.focus())}));a.on("mousedown",this.rc(function(a){this.da.element.prop("disabled")&&c.Sc(a);this.ld()?this.close(a):this.og()&&this.open(a);this.search.focus()}));a.on("focus",this.rc(function(a){c.Sc(a)}));this.search.on("blur",this.rc(function(a){if(void 0!==this.search.val()&&0>=this.kc.children().length)if(this.da.manageNewEntry){if(!this.selection.data("ojcombobox")&&""!==this.search.val()||this.selection.data("ojcombobox")&&this.selection.data("ojcombobox").label!==
this.search.val()){var b=this.da.manageNewEntry(this.search.val());this.pr(b,null,a)}}else null==this.da.manageNewEntry&&(b=this.selection.data(this.sc),""==this.search.val()?this.eu(a):b||""===this.search.val()?(a=this.da.Hx(b,0,this.da.hs),void 0!==a&&this.search.val(a)):this.Xh());this.search.removeClass(this.Ha+"-focused")}));this.AD();this.da.element.hide().attr("aria-hidden",!0);this.pi()},Mn:function(){var a=e.t.Mn.apply(this,arguments),b=this,c=a.element.get(0).tagName.toLowerCase();if("input"===
c&&a.element.attr("list")||"select"===c&&0<a.element.children().length)a.Ji=function(a,c){var d,e=b.vb();Array.isArray(e)&&(e=e[0]);d=void 0!==e&&null!==e?b.al(a.find("option").filter(function(){return this.value===e})):b.al(a.find("option").filter(function(){return this.selected}));c(d)};else if("options"in a||this.vb()&&0<this.vb().length)a.Ji=a.Ji||function(d,e){var g="";b.vb()&&b.vb().length&&(g=b.vb()[0]);var h=null,k=null;a.Gs({bk:function(b,c,d){(b=g===a.id(d))&&(k=d);h||(h=d);return b},gc:f.isFunction(e)?
function(){k||"select"!==c||(k=h);e(k)}:f.noop})};return a},Ln:function(a,b,d){var e=-1,f=this;a=this.Ym();c.Bi(a,function(a,b){if(f.vb()&&f.vb()[0]===f.id(b.data(f.sc)))return e=a,!1});!1!==d&&!0===b&&0<=e&&this.Bj(e)},pr:function(a,b,c){this.LG(a)&&(this.vb()&&this.vb(),this.Ah(a),this.close(c),this.Xi(0===this.id(a).length?[]:this.id(a),c))},mG:function(a){return this.ld()||!1===this.Jk||!0===this.dl?!1:this.ae._trigger("beforeExpand",a,{component:this.da.element})},Xh:function(){this.search.val("")}}),
g=c.lo(e,{sc:"ojcombobox",Ha:"oj-combobox",ou:function(){return f(document.createElement("div")).attr({"class":"oj-combobox oj-component"}).html("\x3cdiv class\x3d'oj-combobox-choice' tabindex\x3d'-1' role\x3d'presentation'\x3e   \x3cinput type\x3d'text' autocomplete\x3d'off' autocorrect\x3d'off' autocapitalize\x3d'off'       spellcheck\x3d'false' class\x3d'oj-combobox-input' role\x3d'combobox' aria-expanded\x3d'false' aria-autocomplete\x3d'list' /\x3e   \x3cabbr class\x3d'oj-combobox-clear-entry' role\x3d'presentation'\x3e\x3c/abbr\x3e   \x3ca class\x3d'oj-combobox-arrow' role\x3d'presentation'\x3e\x3cb class\x3d'oj-combobox-icon oj-component-icon oj-clickable-icon oj-combobox-open-icon' role\x3d'presentation'\x3e\x3c/b\x3e\x3c/a\x3e\x3c/div\x3e\x3cdiv class\x3d'oj-listbox-drop' style\x3d'display:none' role\x3d'presentation'\x3e   \x3cul class\x3d'oj-listbox-results' role\x3d'listbox'\x3e   \x3c/ul\x3e\x3c/div\x3e")},
ai:function(a){g.t.ai.apply(this,arguments);this.Jk?this.ua.find(".oj-combobox-arrow").removeClass("oj-disabled"):this.ua.find(".oj-combobox-arrow").addClass("oj-disabled")},close:function(a){this.ld()&&g.t.close.apply(this,arguments)},Ij:function(a){var b,c;g.t.Ij.apply(this,arguments);b=this.search.get(0);b.createTextRange?(b=b.createTextRange(),b.collapse(!1),b.select()):b.setSelectionRange&&(c=this.search.val().length,b.setSelectionRange(c,c));this.Ur(!0)},Ah:function(a){this.selection.data(this.sc,
a);null!==a?(a=this.da.Hx(a,0,this.da.hs),void 0!==a&&this.search.val(a),this.search.removeClass(this.Ha+"-default")):this.pi();this.da.jV&&this.ua.addClass(this.Ha+"-allowclear")},WG:function(a){if(void 0===a||null===a)a=(a=this.vb())?Array.isArray(a)?Array.isArray(a)&&a.length?{label:a[0]}:null:{label:a}:null;this.Ah(a)}}),h=c.lo(e,{sc:"ojselect",Ha:"oj-select",YG:!1,ou:function(){return f(document.createElement("div")).attr({"class":"oj-select oj-component"}).html("\x3cdiv class\x3d'oj-select-choice' tabindex\x3d'0' role\x3d'combobox'      aria-autocomplete\x3d'none' aria-expanded\x3d'false' aria-ready\x3d'true'\x3e  \x3cspan class\x3d'oj-select-chosen'\x3e\x3c/span\x3e  \x3cabbr class\x3d'oj-select-search-choice-close' role\x3d'presentation'\x3e\x3c/abbr\x3e  \x3ca class\x3d'oj-select-arrow' role\x3d'presentation'\x3e    \x3cb class\x3d'oj-component-icon oj-clickable-icon oj-select-open-icon' role\x3d'presentation'\x3e\x3c/b\x3e\x3c/a\x3e\x3c/div\x3e\x3cdiv class\x3d'oj-listbox-drop' style\x3d'display:none' role\x3d'presentation'\x3e  \x3cdiv class\x3d'oj-listbox-search-wrapper'\x3e  \x3cdiv class\x3d'oj-listbox-search'\x3e    \x3cinput type\x3d'text' autocomplete\x3d'off' autocorrect\x3d'off' autocapitalize\x3d'off'           spellcheck\x3d'false' class\x3d'oj-listbox-input' title\x3d'Search field'            role\x3d'combobox' aria-expanded\x3d'false' aria-autocomplete\x3d'list' /\x3e    \x3cspan class\x3d'oj-listbox-spyglass-box'\x3e      \x3cspan class\x3d'oj-component-icon oj-clickable-icon oj-listbox-search-icon' role\x3d'presentation'\x3e       \x3cb role\x3d'presentation'\x3e\x3c/b\x3e\x3c/span\x3e    \x3c/span\x3e  \x3c/div\x3e  \x3c/div\x3e   \x3cul class\x3d'oj-listbox-results' role\x3d'listbox'\x3e   \x3c/ul\x3e\x3c/div\x3e")},
ai:function(a){h.t.ai.apply(this,arguments);this.Jk?(this.ua.find(".oj-select-choice").attr("tabindex","0"),this.ua.find(".oj-select-arrow").removeClass("oj-disabled")):(this.ua.find(".oj-select-choice").attr("tabindex","-1"),this.ua.find(".oj-select-arrow").addClass("oj-disabled"))},close:function(a){this.ld()&&(h.t.close.apply(this,arguments),this.Yw(a)||this.Xh(),c.Qd(this.selection),this.ua.find(".oj-listbox-spyglass-box").off("mouseup click"))},Ij:function(a){var b,c;h.t.Ij.apply(this,arguments);
this.tU();this.yj()&&(b=this.search.get(0),b.createTextRange?(b=b.createTextRange(),b.collapse(!1),b.select()):b.setSelectionRange&&(c=this.search.val().length,b.setSelectionRange(c,c)));this.Ur(!0)},Xq:function(){var a=this.Rj+"_selected";this.text=this.ua.find(".oj-select-chosen").attr("id",a);h.t.Xq.apply(this,arguments);this.ua.find(".oj-select-choice").attr({"aria-owns":this.search.attr("aria-owns"),"aria-labelledby":this.search.attr("aria-labelledby"),"aria-describedby":a});this.search.on("keydown",
this.rc(this.cq));this.search.on("keyup-change input",this.rc(this.GN));var b=this;this.selection.on("blur",function(a){b.Yw(a)})},Wk:function(){this.VD()?(this.Ah(null),this.close(),this.pi()):h.t.Wk.apply(this,arguments)},WG:function(a){if(void 0!==a&&null!==a){var b,c=this.vb(),c=Array.isArray(c)?c[0]:c;b=this.da.id(a);c!==b&&(void 0===c||null===c?this.ae.options.value=Array.isArray(b)?b:[b]:this.Xi(Array.isArray(b)?b:[b]));this.Ah(a);this.close()}},Ah:function(a){this.selection.data(this.sc,a);
null!==a&&this.text.text(a.label);a&&""!=a.id&&this.text.removeClass(this.Ha+"-default");this.da.jV&&this.ua.addClass(this.Ha+"-allowclear")},zq:function(){return this.search.attr("aria-expanded")&&this.yj()?this.search:this.selection},VD:function(){if(null===this.wj())return!1;var a=this.vb(),a=Array.isArray(a)?a[0]:a;return""===a||void 0===a||null===a},wj:function(){return this.da.placeholder},pG:function(){return!0},pi:function(){var a=this.wj();this.VD()&&void 0!==a&&(void 0===a&&(a=""),this.text.text(a).addClass(this.Ha+
"-default"),this.ua.removeClass(this.Ha+"-allowclear"))},Xi:function(a,b){h.t.Xi.call(this,a,b);this.selection.data("selectVal",a)},cq:function(a){if(!c.Qa.xI(a)&&!c.Qa.zI(a)){switch(a.which){case c.Qa.TAB:this.close(a);this.selection.focus();this.Yw(a);return;case c.Qa.ENTER:if(a.target===this.selection[0]&&!this.ld()){this.open(a);c.Sc(a);return}}h.t.cq.apply(this,arguments)}},Yw:function(a){return""==this.text.text()?(this.eu(a),!0):!1},tU:function(){var a=!1,b=this.Cc.find(".oj-listbox-search");
b&&(this.yj()?(this.Cc.find(".oj-listbox-search-wrapper").removeClass("oj-helper-hidden-accessible"),f(b).removeAttr("aria-hidden"),a=!0):(this.Cc.find(".oj-listbox-search-wrapper").addClass("oj-helper-hidden-accessible"),f(b).attr({"aria-hidden":"true"})));c.Qd(a?this.search:this.selection);if(a){var d=this;b.find(".oj-listbox-spyglass-box").on("mouseup click",function(a){d.search.focus();a.stopPropagation()})}},yj:function(){return(this.Ai?this.Ai[0].length:this.da.options?this.da.options.length:
0)>this.da.minimumResultsForSearch||this.YG}});a.Oa("oj.ojCombobox",f.oj.editableValue,{defaultElement:"\x3cinput\x3e",widgetEventPrefix:"oj",options:{converter:void 0,placeholder:void 0,multiple:!1,options:null,optionsKeys:null,beforeExpand:null},widget:function(){return this.nd.ua},_ComponentCreate:function(){this._super();this.sb()},_InitOptions:function(b,d){this._super(b,d);a.td.Ki([{attribute:"disabled",defaultOptionValue:null,validateOption:!0},{attribute:"placeholder",defaultOptionValue:""},
{attribute:"required",defaultOptionValue:!1,coerceDomValue:!0,validateOption:!0},{attribute:"title",defaultOptionValue:""}],d,this);if(void 0===this.options.value)this.options.value=void 0!==this.element.attr("value")?c.gk(this.element.val(),","):null;else{var e=this.options.value;Array.isArray(e)?e=e.slice(0):"string"===typeof e&&(e=c.gk(e,","));this.options.value=e}},sb:function(){var a,b=this.options.multiple;a={};a.element=this.element;a.ae=this;a=f.extend(this.options,a);this.nd=b?new k:new g;
this.nd._init(a)},_destroy:function(){this.nd._destroy()},refresh:function(){this._super();this.nd._destroy();this.sb()},_setOption:function(a,b,d){"value"===a&&(Array.isArray(b)?b=b.slice(0):"string"===typeof b&&(b=c.gk(b,",")));this._super(a,b,d);"options"===a&&this.refresh();"disabled"===a&&(b?this.nd.WB():this.nd.ai())},ig:function(){this.nd.Wk()},_SetPlaceholder:function(a){this.nd&&(this.nd.da.placeholder=a,this.nd.pi&&this.nd.pi())},validate:function(){if(this.nd)return this.ie(this.nd.vb(),
null,this.At)},_GetMessagingLauncherElement:function(){return this.nd.search},Ae:function(){return this.nd.search},_GetDefaultStyleClass:function(){return"oj-combobox"},getNodeBySubId:function(a){var b=null;if(null==a)return this.nd.ua?this.nd.ua[0]:null;b=this._super(a);if(!b)switch(a=a.subId,"oj-combobox-drop"===a&&(a="oj-listbox-drop"),"oj-combobox-results"===a&&(a="oj-listbox-results"),"oj-combobox-selection"===a&&(a="oj-combobox-selected-choice"),a){case "oj-combobox-input":case "oj-combobox-arrow":case "oj-listbox-drop":case "oj-listbox-results":b=
this.widget().find("."+a)[0];break;case "oj-combobox-selected-choice":b=this.widget().find("."+a)}return b||null}});a.Oa("oj.ojSelect",f.oj.editableValue,{defaultElement:"\x3cselect\x3e",widgetEventPrefix:"oj",options:{minimumResultsForSearch:10,placeholder:void 0,options:null,optionsKeys:null,beforeExpand:null},widget:function(){return this.select.ua},_ComponentCreate:function(){this._super();this.sb()},sb:function(){var a={};a.element=this.element;a.ae=this;a=f.extend(this.options,a);this.select=
new h;this.select._init(a)},refresh:function(){this._super();this.select._destroy();this.sb()},_destroy:function(){this.select._destroy()},_SetPlaceholder:function(){},Mz:function(){return"string"===typeof this.options.placeholder},Ez:function(){this.tA(null);this._SetPlaceholder(null)},_InitOptions:function(b,d){this._super(b,d);a.td.Ki([{attribute:"disabled",defaultOptionValue:null,validateOption:!0},{attribute:"placeholder",defaultOptionValue:null},{attribute:"required",defaultOptionValue:!1,coerceDomValue:!0,
validateOption:!0},{attribute:"title",defaultOptionValue:""}],d,this);if(void 0===this.options.value)this.options.value=void 0!==this.element.attr("value")?c.gk(this.element.val(),","):null;else{var e=this.options.value;Array.isArray(e)&&(e=e.slice(0));this.options.value=e}},validate:function(){return this.ie(this.select.vb(),null,this.At)},ig:function(){this.select.Wk()},_setOption:function(a,b,c){"value"===a?Array.isArray(b)&&(b=b.slice(0)):"placeholder"===a?(this.select.da.placeholder=b,this.select.pi()):
"minimumResultsForSearch"===a&&(this.select.da.minimumResultsForSearch=b);this._super(a,b,c);"disabled"===a?b?this.select.WB():this.select.ai():"options"===a&&this.sb()},Wu:function(){if(this.select&&this.select.ld()){var b=f(".oj-listbox-drop");if("oj-listbox-drop"==b.attr("id")&&b.attr(a.ba.dg)==this.select.Rj)return b}return null},getNodeBySubId:function(a){var b=null,c;if(null==a)return this.select.ua?this.select.ua[0]:null;b=this._super(a);if(!b)switch(c=a.subId,"oj-select-drop"===c&&(c="oj-listbox-drop"),
"oj-select-results"===c&&(c="oj-listbox-results"),"oj-select-search"===c&&(c="oj-listbox-search"),c){case "oj-select-choice":case "oj-select-chosen":b=this.widget().find("."+c)[0];break;case "oj-listbox-drop":var d=this.Wu();d&&(b=d[0]);break;case "oj-listbox-input":case "oj-listbox-search":case "oj-listbox-results":(d=this.Wu())&&(b=d.find("."+c)[0]);break;case "oj-listbox-result-label":this.Wu()&&(d=f("#"+this.select.kc.attr("id")).children(),a=a.index,d.length&&a<d.length&&(b=d.eq(a).find("."+
c)[0]))}return b||null},_GetDefaultStyleClass:function(){return"oj-select"},_GetMessagingLauncherElement:function(){return this.select.selection},Ae:function(){return this.select.selection}});var k=c.lo(b,{sc:"ojcombobox",Ha:"oj-combobox",ou:function(){return f(document.createElement("div")).attr({"class":"oj-combobox oj-combobox-multi oj-component"}).html("\x3cul class\x3d'oj-combobox-choices'\x3e  \x3cli class\x3d'oj-combobox-search-field'\x3e    \x3cinput type\x3d'text' role\x3d'combobox' aria-expanded\x3d'false' aria-autocomplete\x3d'list' autocomplete\x3d'off' autocorrect\x3d'off' autocapitalize\x3d'off' spellcheck\x3d'false' class\x3d'oj-combobox-input'\x3e  \x3c/li\x3e\x3c/ul\x3e\x3cdiv class\x3d'oj-combobox-description oj-helper-hidden-accessible'/\x3e\x3cdiv class\x3d'oj-listbox-drop oj-listbox-drop-multi' style\x3d'display:none'\x3e   \x3cul class\x3d'oj-listbox-results' role\x3d'listbox'\x3e   \x3c/ul\x3e\x3c/div\x3e")},
Mn:function(){var a=k.t.Mn.apply(this,arguments),b=this;"input"===a.element.get(0).tagName.toLowerCase()&&a.element.attr("list")?a.Ji=function(a,d){var e=[];if(b.vb()&&b.vb().length)for(var f,g=b.vb(),h=0;h<g.length;h++){var k=g[h];(f=a.find("option").filter(function(){return this.value===k}))&&f.length?e.push(b.al(f)):e.push({value:k,label:k})}else f=a.find("option").filter(function(){return this.selected}),c.Bi(f,function(a,c){e.push(b.al(c))});d(e)}:"options"in a&&(a.Ji=a.Ji||function(c,d){var e=
b.vb(),g=[];a.Gs({bk:function(b,c,d){(b=f.grep(e,function(b){return b===a.id(d)}).length)&&g.push(d);return b},gc:f.isFunction(d)?function(){for(var b=[],c=0;c<e.length;c++){for(var f=e[c],h=!1,k=0;k<g.length;k++){var m=g[k];if(f===a.id(m)){b.push(m);g.splice(k,1);h=!0;break}}h||b.push({value:f,label:f})}d(b)}:f.noop})});return a},il:function(a){var b=this.ua.find("."+this.Ha+"-selected-choice.oj-focus");b.length&&a&&a[0]==b[0]||(b.length&&this.da.element.trigger("choice-deselected",b),b.removeClass("oj-focus"),
a&&a.length&&(this.close(),a.addClass("oj-focus"),this.ua.find(".oj-combobox-description").text(a.attr("valueText")+". Press back space to delete.").attr("aria-live","assertive"),this.da.element.trigger("choice-selected",a)))},_destroy:function(){f("label[for\x3d'"+this.search.attr("id")+"']").attr("for",this.da.element.attr("id"));k.t._destroy.apply(this,arguments)},Xq:function(){var a="."+this.Ha+"-choices",b,d=c.To(),e;this.jX=this.ua.find("."+this.Ha+"-search-field");this.selection=b=this.ua.find(a);
var g=this;this.selection.on("click","."+this.Ha+"-selected-choice:not(."+this.Ha+"-locked)",function(){g.search[0].focus();g.il(f(this))});e=f("label[for\x3d'"+this.da.element.attr("id")+"']");e.attr("id")||e.attr("id",this.Ha+"-label-"+d);b.find("."+this.Ha+"-input").attr("id",this.Ha+"-input-"+d);this.kc.attr("id","oj-listbox-results-"+d);this.search.attr("aria-owns","oj-listbox-results-"+d);this.search.attr("aria-labelledby",e.attr("id"));this.search.on("input paste",this.rc(function(){this.og()&&
!this.ld()&&this.open()}));this.search.attr("tabindex",this.Ex);this.dy=0;this.search.on("keydown",this.rc(function(a){if(this.og()){++this.dy;var d=b.find("."+this.Ha+"-selected-choice.oj-focus"),e=d.prev("."+this.Ha+"-selected-choice:not(."+this.Ha+"-locked)"),f=d.next("."+this.Ha+"-selected-choice:not(."+this.Ha+"-locked)"),g=c.eW(this.search);if(!d.length||a.which!=c.Qa.LEFT&&a.which!=c.Qa.RIGHT&&a.which!=c.Qa.ep&&a.which!=c.Qa.Ty&&a.which!=c.Qa.ENTER)if((a.which!==c.Qa.ep||1!=this.dy)&&a.which!=
c.Qa.LEFT||0!=g.offset||g.length){this.il(null);if(this.ld())switch(a.which){case c.Qa.UP:case c.Qa.DOWN:this.uE(a.which===c.Qa.UP?-1:1);c.Sc(a);return;case c.Qa.ENTER:this.zr(null,a);c.Sc(a);return;case c.Qa.TAB:this.close(a);return;case c.Qa.Ns:this.$t(a);c.Sc(a);return}a.which===c.Qa.TAB||c.Qa.xI(a)||c.Qa.zI(a)||a.which===c.Qa.ep||a.which===c.Qa.Ns||a.which===c.Qa.ENTER&&(!1===this.da.SW||a.altKey||a.ctrlKey||a.shiftKey||a.metaKey)||(this.open(),a.which!==c.Qa.PAGE_UP&&a.which!==c.Qa.PAGE_DOWN||
c.Sc(a),a.which===c.Qa.ENTER&&c.Sc(a))}else this.il(b.find("."+this.Ha+"-selected-choice:not(."+this.Ha+"-locked)").last()),c.Sc(a);else g=d,a.which==c.Qa.LEFT&&e.length?g=e:a.which==c.Qa.RIGHT?g=f.length?f:null:a.which===c.Qa.ep?(this.ex(d.first(),a),this.search.width(10),g=e.length?e:f):a.which==c.Qa.Ty?(this.ex(d.first(),a),this.search.width(10),g=f.length?f:null):a.which==c.Qa.ENTER&&(g=null),this.il(g),c.Sc(a),g&&g.length||this.open()}}));this.search.on("keyup",this.rc(function(){this.dy=0}));
this.search.on("blur",this.rc(function(a){if(this.da.manageNewEntry&&this.search.val()&&0>=this.kc.children().length){var b=this.da.manageNewEntry(this.search.val());this.pr(b,null,a)}this.search.removeClass(this.Ha+"-focused");this.il(null);this.ld()||this.Xh();a.stopImmediatePropagation()}));this.ua.on("click",a,this.rc(function(a){!this.og()||0<f(a.target).closest("."+this.Ha+"-selected-choice").length||(this.il(null),this.open(),this.Zm(),a.preventDefault())}));this.ua.on("focus",a,this.rc(function(){}));
this.AD();this.da.element.hide().attr("aria-hidden",!0);this.Xh()},Ik:function(){k.t.Ik.apply(this,arguments)&&this.search.prop("disabled",!this.og())},Wk:function(){null!==this.vb()&&0!==this.vb().length||""!==this.da.element.text()||(this.Ah([]),this.close(),this.Xh());if(this.Ai||null!==this.vb()&&this.vb().length){var a=this;this.da.Ji.call(null,this.Ai?this.Ai:this.da.element,function(b){void 0!==b&&null!==b&&(a.Ah(b),a.close(),a.Xh())})}},Xh:function(){var a=this.wj(),b=this.LP();void 0===a||
this.vb()&&0!==this.vb().length?(this.search.attr("placeholder",""),this.search.val("").width(10)):(this.search.attr("placeholder",a),this.search.width(0<b?b:this.ua.css("width")))},Ij:function(a){this.ae._trigger("beforeExpand",a)&&(this.ET(),k.t.Ij.apply(this,arguments),this.Zm(),this.Ur(!0),this.search.focus())},close:function(a){this.ld()&&k.t.close.apply(this,arguments)},Qd:function(){this.close();this.search.focus()},Ah:function(a){var b=[],c=[],d=this;f(a).each(function(){0>b.indexOf(d.id(this))&&
(b.push(d.id(this)),c.push(this))});a=c;this.selection.find("."+this.Ha+"-selected-choice").remove();f(a).each(function(){d.JA(this)});d.Ln()},pr:function(a,b,d){if(this.LG(a)){this.JA(a);var e=this.id(a),g=this.vb()?this.vb().slice(0):[];this.ae.isValid()||(g=c.gk(this.da.element.val(),this.da.separator));f(a).each(function(){0>g.indexOf(e)&&g.push(e)});this.Xi(g,d);!this.select&&this.da.yx||this.Ln(a,!1,!0===this.da.yx);this.da.yx&&(this.close(d),this.search.width(10));b&&b.OI||this.Zm()}},$t:function(a){this.close(a);
this.Zm()},JA:function(a){var b=!a.locked,d=f("\x3cli class\x3d'"+this.Ha+"-selected-choice'\x3e    \x3cdiv\x3e\x3c/div\x3e    \x3ca href\x3d'#' onclick\x3d'return false;' class\x3d'"+this.Ha+"-clear-entry' tabindex\x3d'-1'\x3e    \x3cspan class\x3d'oj-component-icon oj-clickable-icon oj-combobox-clear-entry-icon' role\x3d'presentation'\x3e\x3c/a\x3e\x3c/li\x3e"),e=f("\x3cli class\x3d'"+this.Ha+"-selected-choice "+this.Ha+"-locked'\x3e\x3cdiv\x3e\x3c/div\x3e\x3c/li\x3e"),d=b?d:e;this.id(a);e=this.da.Hx(a,
d.find("div"),this.da.hs);void 0!==e&&(d.find("div").replaceWith("\x3cdiv class\x3d'"+this.Ha+"-selected-choice-label'\x3e"+e+"\x3c/div\x3e"),d.attr("valueText",e));if(b)d.find("."+this.Ha+"-clear-entry").on("mousedown",c.Sc).on("click dblclick",this.rc(function(a){this.og()&&(f(a.target).closest("."+this.Ha+"-selected-choice").fadeOut("fast",this.rc(function(){this.ex(f(a.target),a);this.selection.find("."+this.Ha+"-selected-choice.oj-focus").removeClass("oj-focus");this.close(a);this.Zm()})).dequeue(),
c.Sc(a))}));d.data(this.sc,a);d.insertBefore(this.jX)},ex:function(a,b){var d=this.vb()?this.vb().slice(0):[],e,f;a=a.closest("."+this.Ha+"-selected-choice");if(0===a.length)throw"Invalid argument: "+a+". Must be ."+this.Ha+"-selected-choice";if(e=a.data(this.sc)){for(this.ae.isValid()||(d=c.gk(this.da.element.val(),this.da.separator));0<=(f=d.indexOf(this.id(e)));)d.splice(f,1),this.Xi(d,b),this.select&&this.Ln();a.remove()}},Ln:function(){var a=this.vb()&&(this.da.element.val()||this.ae.isValid())?
this.vb():[],b=this.kc.find(".oj-listbox-result"),d=this.kc.find(".oj-listbox-result-with-children"),e=this;c.Bi(b,function(b,c){var d=e.id(c.data(e.sc));a&&0<=a.indexOf(d)&&(c.addClass("oj-selected"),c.find(".oj-listbox-result-selectable").addClass("oj-selected"))});c.Bi(d,function(a,b){b.is(".oj-listbox-result-selectable")||0!==b.find(".oj-listbox-result-selectable:not(.oj-selected)").length||b.addClass("oj-selected")});0< !b.filter(".oj-listbox-result:not(.oj-selected)").length&&this.close()},
LP:function(){return this.selection.width()-c.cI(this.search)},CU:function(a){a='\x3cspan style\x3d"display:none"\x3e'+a+"\x3c/span\x3e";f("body").append(a);a=f("body").find("span:last").width();f("body").find("span:last").remove();return a},ET:function(){var a,b,d,e,f=c.cI(this.search);a=this.CU(this.search.val())+10;b=this.search.offset().left;d=this.selection.width();e=this.selection.offset().left;b=d-(b-e)-f;b<a&&(b=d-f);40>b&&(b=d-f);0>=b&&(b=a);this.search.width(Math.floor(b))},Xi:function(a,
b){var d;d=[];"string"===typeof a&&(a=c.gk(a,this.da.separator));for(var e=0;e<a.length;e++)0>d.indexOf(a[e])&&d.push(a[e]);this.ae.ie(d,b,{oo:!1});this.da.element.val(0===d.length?"":d.join(this.da.separator));this.search.attr("aria-activedescendant",this.da.element.attr("id"))}})});
//# sourceMappingURL=oj-modular.map