"use strict";
/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojdvt-base","ojs/internal-deps/dvt/DvtSunburst"],function(a,f){a.cf=function(a){this.f=a};o_("SunburstNode",a.cf,a);a.cf.prototype.od=function(){return this.f?this.f.color:null};a.b.g("SunburstNode.prototype.getColor",{od:a.cf.prototype.od});a.cf.prototype.pe=function(){return this.f?this.f.label:null};a.b.g("SunburstNode.prototype.getLabel",{pe:a.cf.prototype.pe});a.cf.prototype.vo=function(){return this.f?this.f.size:null};a.b.g("SunburstNode.prototype.getSize",
{vo:a.cf.prototype.vo});a.cf.prototype.te=function(){return this.f?this.f.tooltip:null};a.b.g("SunburstNode.prototype.getTooltip",{te:a.cf.prototype.te});a.cf.prototype.isSelected=function(){return this.f?this.f.selected:!1};a.b.g("SunburstNode.prototype.isSelected",{isSelected:a.cf.prototype.isSelected});a.Oa("oj.ojSunburst",f.oj.dvtBaseComponent,{version:"1.0.0",widgetEventPrefix:"oj",options:{optionChange:null,rotate:null,rotateInput:null,select:null},Cf:function(a,b,d){return DvtSunburst.newInstance(a,
b,d)},ef:function(){var a=this._super();a.push("oj-sunburst");return a},aj:function(){var a=this._super();a["oj-sunburst-attribute-type-text"]={path:"styleDefaults/_attributeTypeTextStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-sunburst-attribute-value-text"]={path:"styleDefaults/_attributeValueTextStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-sunburst-node"]={path:"nodeDefaults/labelStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-sunburst-node oj-hover"]={path:"nodeDefaults/hoverColor",property:"border-top-color"};
a["oj-sunburst-node oj-selected"]=[{path:"nodeDefaults/selectedOuterColor",property:"border-top-color"},{path:"nodeDefaults/selectedInnerColor",property:"border-bottom-color"}];return a},bj:function(){return["optionChange","rotate","rotateInput","select"]},wm:function(){var a=this._super();a["DvtSunburstBundle.COLOR"]=this.pc("labelColor");a["DvtSunburstBundle.SIZE"]=this.pc("labelSize");return a},cj:function(a){var b=a&&a.getType?a.getType():null,d,e;if(b===DvtSelectionEvent.TYPE){b=[];a=a.getSelection();
for(e=0;e<a.length;e++)d={id:a[e]},b.push(d);this.$g("selectedNodes",a);this._trigger("select",null,{items:b})}else b===DvtSunburstRotationEvent.TYPE?(this.$g("startAngle",a.getStartAngle()),this._trigger("rotate",null,{value:a.getStartAngle()})):b===DvtSunburstRotationEvent.TYPE_INPUT?this._trigger("rotateInput",null,{value:a.getStartAngle()}):this._super(a)},kt:function(){null==this.options._resources&&(this.options._resources={});this.options._resources.rotateCursor=a.ia.jb("resources/internal-deps/dvt/sunburst/rotate.cur")},
xk:function(a){return"selectedNodes"==a||"startAngle"==a},getNodeBySubId:function(a){return this._super(a)},getSubIdByNode:function(a){return this._super(a)},getNode:function(c){var b=this.Va.getAutomation();return new a.cf(b.getNode(c))}})});
//# sourceMappingURL=oj-modular.map