/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define("ojs/ojcore jquery ojs/ojcomponentcore promise ojs/ojmenu ojs/ojdatacollection-common ojs/ojpagingcontrol".split(" "),function(a,f){a.ta=function(c,b){a.ta._init(this,c,b)};o_("FlattenedTreeRowSet",a.ta,a);a.b.sa(a.ta,a.Q,"oj.FlattenedTreeRowSet");a.ta.prototype.Init=function(){a.ta.t.Init.call(this)};a.b.g("FlattenedTreeRowSet.prototype.Init",{Init:a.ta.prototype.Init});a.ta._init=function(c,b){c.ib=[];c.C=0;c.Init();c.f=b;null==c.f.so("fetchSize")&&(c.f.Lx=function(){return-1});c.f.us=function(b,
e,f){var h,k;for(e=0;e<f.Z();e++)k=b+e,h=new a.Ta(f.getData(e),{context:f.getMetadata(e)}),h.index=k,h.hx=function(a){return function(){this.context=f.getMetadata(a)}}(e),c.Ia.splice(k,0,h),a.ta.t.ac.call(c,a.Q.v.ADD,h);a.ta.el(0,c.Ia);c.na&&setTimeout(function(){c.fetch({pageSize:c.na})},0)};c.f.Hs=function(b){var e,f,h;for(e=0;e<b.length;e++)h=b[e].index-e,f=new a.Ta({},null),f.index=h,c.Ia.splice(h,1),a.ta.t.ac.call(c,a.Q.v.REMOVE,f);a.ta.el(0,c.Ia);c.na&&setTimeout(function(){c.fetch({pageSize:c.na})},
0)}};a.ta.prototype.add=function(){a.i.fa();return null};a.b.g("FlattenedTreeRowSet.prototype.add",{add:a.ta.prototype.add});a.ta.prototype.at=function(a){return this.Ia[a]};a.b.g("FlattenedTreeRowSet.prototype.at",{at:a.ta.prototype.at});a.ta.prototype.clone=function(){a.i.fa();return null};a.b.g("FlattenedTreeRowSet.prototype.clone",{clone:a.ta.prototype.clone});a.ta.prototype.collapse=function(a){this.f.collapse(a)};a.b.g("FlattenedTreeRowSet.prototype.collapse",{collapse:a.ta.prototype.collapse});
a.ta.prototype.expand=function(a){this.f.expand(a)};a.b.g("FlattenedTreeRowSet.prototype.expand",{expand:a.ta.prototype.expand});a.ta.prototype.fetch=function(a){a=a||{};null!=a.startIndex&&(this.C=a.startIndex);var b=Number.MAX_VALUE;null!=a.pageSize&&(this.na=b=a.pageSize);var d=this.C;if(null!=this.Ia&&null!=a.pageSize){var e=this.Ia.length-1;if(this.C+a.pageSize-1<=e){for(b=0;b<this.Ia.length;b++)this.Ia[b].hx&&this.Ia[b].hx();a.refresh=!0;this.If(a,null);return}this.C<=e&&(d=e+1)}var f=this;
this.f.DH({start:d,count:b},{success:function(b){f.Iv(b);a.refresh=!0;f.If(a,null)}.bind(this),error:function(b){f.If(a,b)}.bind(this)})};a.b.g("FlattenedTreeRowSet.prototype.fetch",{fetch:a.ta.prototype.fetch});a.ta.prototype.get=function(){a.i.fa();return null};a.b.g("FlattenedTreeRowSet.prototype.get",{get:a.ta.prototype.get});a.ta.prototype.hasMore=function(){a.i.fa();return!1};a.b.g("FlattenedTreeRowSet.prototype.hasMore",{hasMore:a.ta.prototype.hasMore});a.ta.prototype.indexOf=function(){a.i.fa();
return 0};a.b.g("FlattenedTreeRowSet.prototype.indexOf",{indexOf:a.ta.prototype.indexOf});a.ta.prototype.isEmpty=function(){a.i.fa();return!0};a.b.g("FlattenedTreeRowSet.prototype.isEmpty",{isEmpty:a.ta.prototype.isEmpty});a.ta.prototype.on=function(c,b){if("expand"==c||"collapse"==c)this.f.on(c,b);else a.ta.t.on.call(this,c,b)};a.b.g("FlattenedTreeRowSet.prototype.on",{on:a.ta.prototype.on});a.ta.prototype.off=function(c,b){"expand"==c||"collapse"==c?this.f.off(c,b):a.ta.t.off.call(this,c,b)};a.b.g("FlattenedTreeRowSet.prototype.off",
{off:a.ta.prototype.off});a.ta.prototype.remove=function(){a.i.fa()};a.b.g("FlattenedTreeRowSet.prototype.remove",{remove:a.ta.prototype.remove});a.ta.prototype.reset=function(){a.i.fa()};a.b.g("FlattenedTreeRowSet.prototype.reset",{reset:a.ta.prototype.reset});a.ta.prototype.size=function(){return this.Ia?this.na&&this.Ia.length>this.C+this.na?this.C+this.na:this.Ia.length:0};a.b.g("FlattenedTreeRowSet.prototype.size",{size:a.ta.prototype.size});a.ta.prototype.sort=function(a){var b=this;return this.f.getWrappedDataSource().sort(a,
{success:function(){b.f.refresh();b.fetch({startIndex:b.C,pageSize:b.na})}.bind(this),error:function(){}.bind(this)})};a.b.g("FlattenedTreeRowSet.prototype.sort",{sort:a.ta.prototype.sort});a.ta.prototype.startIndex=function(){return 0};a.b.g("FlattenedTreeRowSet.prototype.startIndex",{startIndex:a.ta.prototype.startIndex});a.ta.prototype.totalSize=function(){return-1};a.b.g("FlattenedTreeRowSet.prototype.totalSize",{totalSize:a.ta.prototype.totalSize});a.ta.prototype.Iv=function(c){this.nO=c;this.Ia||
(this.Ia=[]);a.ta.rv(this.nO,this,this.Ia)};a.ta.prototype.If=function(c,b){c=c||{};var d=c.success,e=c.error;null!=b?(a.ta.t.ac.call(this,a.Q.v.ERROR,b),e&&e.call(this,c,b)):(a.ta.t.ac.call(this,a.Q.v.SYNC,c),d&&d.call(this,c))};a.ta.rv=function(c,b,d){var e=c.Z()-1,f;for(f=c.Ka();f<=e;f++){var h=new a.Ta(c.getData(f),{context:c.getMetadata(f)});h.hx=function(a){return function(){this.context=c.getMetadata(a)}}(f);h.index=f;d[f]=h;h.rowSet=b}};a.ta.el=function(a,b){for(var d,e=a;e<b.length;e++)(d=
b[e])&&(d.index=e)};a.N=function(c,b){if(this.constructor==a.N)throw Error(a.N.xc.PX+"\n"+a.N.xc.OX);this.data=c;this.options=b;this.Rc=!1;this.C=0;this.Init()};o_("TableDataSource",a.N,a);a.b.sa(a.N,a.Nc,"oj.TableDataSource");a.N.prototype.Init=function(){a.N.t.Init.call(this)};a.b.g("TableDataSource.prototype.Init",{Init:a.N.prototype.Init});a.N.prototype.at=function(){a.i.fa();return null};a.b.g("TableDataSource.prototype.at",{at:a.N.prototype.at});a.N.prototype.fetch=function(){a.i.fa();return a.b.ha(function(a,
b){b()})};a.b.g("TableDataSource.prototype.fetch",{fetch:a.N.prototype.fetch});a.N.prototype.get=function(){a.i.fa();return null};a.b.g("TableDataSource.prototype.get",{get:a.N.prototype.get});a.N.prototype.getCapability=function(){return null};a.b.g("TableDataSource.prototype.getCapability",{getCapability:a.N.prototype.getCapability});a.N.prototype.hasMore=function(){a.i.fa();return!1};a.b.g("TableDataSource.prototype.hasMore",{hasMore:a.N.prototype.hasMore});a.N.prototype.indexOf=function(){a.i.fa();
return 0};a.b.g("TableDataSource.prototype.indexOf",{indexOf:a.N.prototype.indexOf});a.N.prototype.size=function(){a.i.fa();return 0};a.b.g("TableDataSource.prototype.size",{size:a.N.prototype.size});a.N.prototype.sort=function(){a.i.fa();return a.b.ha(function(a,b){b()})};a.b.g("TableDataSource.prototype.sort",{sort:a.N.prototype.sort});a.N.prototype.startIndex=function(a){null!=a&&(this.C=a);return this.C};a.b.g("TableDataSource.prototype.startIndex",{startIndex:a.N.prototype.startIndex});a.N.prototype.totalSize=
function(){a.i.fa();return 0};a.b.g("TableDataSource.prototype.totalSize",{totalSize:a.N.prototype.totalSize});a.N.v={ADD:"add",REMOVE:"remove",RESET:"reset",REFRESH:"refresh",SORT:"sort",CHANGE:"change",REQUEST:"request",SYNC:"sync",ERROR:"error"};o_("TableDataSource.EventType",a.N.v,a);a.N.xc={_ERR_TABLE_DATASOURCE_INSTANTIATED_SUMMARY:"oj.TableDataSource constructor called.",_ERR_TABLE_DATASOURCE_INSTANTIATED_DETAIL:"Please do not instantiate oj.TableDataSource. Please use one of the subclasses instead such as oj.ArrayTableDataSource or oj.CollectionTableDataSource.",
_ERR_DATA_INVALID_TYPE_SUMMARY:"Invalid data type.",_ERR_DATA_INVALID_TYPE_DETAIL:"Please specify the appropriate data type."};o_("TableDataSource._LOGGER_MSG",a.N.xc,a);a.Ya=function(c){if(!(c instanceof a.N))throw Error(a.N.xc._ERR_DATA_INVALID_TYPE_SUMMARY+"\n"+a.N.xc._ERR_DATA_INVALID_TYPE_DETAIL);this.Ra=c;this.C=0;this.Init()};o_("PagingTableDataSource",a.Ya,a);a.b.sa(a.Ya,a.lb,"oj.PagingTableDataSource");a.Ya.prototype.Init=function(){a.Ya.t.Init.call(this)};a.b.g("PagingTableDataSource.prototype.Init",
{Init:a.Ya.prototype.Init});a.Ya.prototype.getWrappedDataSource=function(){return this.Ra};a.b.g("PagingTableDataSource.prototype.getWrappedDataSource",{getWrappedDataSource:a.Ya.prototype.getWrappedDataSource});a.Ya.prototype.fetch=function(c){null!=c&&(this.C=c.startIndex,c.reset&&(this.Rm=void 0));c.pageSize=null!=c.pageSize?c.pageSize:this.na;c.startIndex=this.C;var b=this;return a.b.ha(function(a,e){c.success=function(){a();b.sq=c.fetchType};c.error=function(){e()};b.Ra.fetch(c)})};a.b.g("PagingTableDataSource.prototype.fetch",
{fetch:a.Ya.prototype.fetch});a.Ya.prototype.next=function(){if(-1==this.Ra.totalSize()||this.Ra.totalSize()>this.C){this.Rm=this.Rm?this.Rm+this.na:this.C+this.na;this.fd+=this.na;var c=this;return this.Ra.fetch({startIndex:this.Rm,pageSize:this.na,fetchType:"next",success:function(){c.sq="next"}})}return a.b.ha(function(a,c){c()})};a.b.g("PagingTableDataSource.prototype.next",{next:a.Ya.prototype.next});a.Ya.prototype.previous=function(){if(0!=this.C||-1!=this.C){this.C-=this.na;this.C=0>this.C?
0:this.C;this.fd-=this.na;var c=this;return this.Ra.fetch({startIndex:this.Rm,pageSize:this.na,fetchType:"previous",success:function(){c.sq="previous"}})}return a.b.ha(function(a,c){c()})};a.b.g("PagingTableDataSource.prototype.previous",{previous:a.Ya.prototype.previous});a.Ya.prototype.setPageSize=function(a){this.na=a;this.fd=this.C+a};a.b.g("PagingTableDataSource.prototype.setPageSize",{setPageSize:a.Ya.prototype.setPageSize});a.Ya.prototype.startIndex=function(){return this.C};a.b.g("PagingTableDataSource.prototype.startIndex",
{startIndex:a.Ya.prototype.startIndex});a.Ya.prototype.at=function(a){return this.Ra.at(a)};a.b.g("PagingTableDataSource.prototype.at",{at:a.Ya.prototype.at});a.Ya.prototype.get=function(a){return this.Ra.get(a)};a.b.g("PagingTableDataSource.prototype.get",{get:a.Ya.prototype.get});a.Ya.prototype.getCapability=function(a){return this.Ra.getCapability(a)};a.b.g("PagingTableDataSource.prototype.getCapability",{getCapability:a.Ya.prototype.getCapability});a.Ya.prototype.hasMore=function(){return this.Ra.hasMore()};
a.b.g("PagingTableDataSource.prototype.hasMore",{hasMore:a.Ya.prototype.hasMore});a.Ya.prototype.indexOf=function(a){return this.Ra.indexOf(a)};a.b.g("PagingTableDataSource.prototype.indexOf",{indexOf:a.Ya.prototype.indexOf});a.Ya.prototype.on=function(c,b){var d=this,e=this.Ra;if(c==a.N.v.SYNC){var f=function(a){d.UQ(a,b)};e.on(c,f);return f}e.on(c,b);return b};a.b.g("PagingTableDataSource.prototype.on",{on:a.Ya.prototype.on});a.Ya.prototype.off=function(a,b){return this.Ra.off(a,b)};a.b.g("PagingTableDataSource.prototype.off",
{off:a.Ya.prototype.off});a.Ya.prototype.size=function(){return null!=this.fd&&0<this.fd&&this.Ra.size()>this.fd?this.fd:this.Ra.size()};a.b.g("PagingTableDataSource.prototype.size",{size:a.Ya.prototype.size});a.Ya.prototype.sort=function(a){return this.Ra.sort(a)};a.b.g("PagingTableDataSource.prototype.sort",{sort:a.Ya.prototype.sort});a.Ya.prototype.totalSize=function(){return this.Ra.totalSize()};a.b.g("PagingTableDataSource.prototype.totalSize",{totalSize:a.Ya.prototype.totalSize});a.Ya.prototype.UQ=
function(c,b){var d=this;setTimeout(function(){if("next"==d.sq||"next"==c.fetchType){var e=d.Ra,f=c.startIndex,h=c.pageSize;d.C=0;d.sq=null;var k;f+h>e.size()&&e.size();for(k=f;k<f+h;k++)e.handleEvent(a.Q.v.ADD,d.Ra.at(k))}b(c)},0)};a.ob=function(c,b){this.data={};if(!(c instanceof Array)&&"function"!=typeof c&&"function"!=typeof c.wX)throw Error(a.N.xc._ERR_DATA_INVALID_TYPE_SUMMARY+"\n"+a.N.xc._ERR_DATA_INVALID_TYPE_DETAIL);a.ob.t.constructor.call(this,c,b);this.aa=new a.$(c,this.options);this.Gm();
if(null!=b&&("enabled"==b.startFetch||null==b.startFetch)||null==b)this.Xn=!0};o_("ArrayTableDataSource",a.ob,a);a.b.sa(a.ob,a.N,"oj.ArrayTableDataSource");a.ob.prototype.Init=function(){a.ob.t.Init.call(this)};a.b.g("ArrayTableDataSource.prototype.Init",{Init:a.ob.prototype.Init});a.ob.prototype.add=function(a,b){this.aa.add(a,b)};a.b.g("ArrayTableDataSource.prototype.add",{add:a.ob.prototype.add});a.ob.prototype.at=function(a){return this.aa.at(a)};a.b.g("ArrayTableDataSource.prototype.at",{at:a.ob.prototype.at});
a.ob.prototype.fetch=function(c){c=c||{};var b=this,d=c.success,e=c.error,f=null==c.context?this:c.context;if("init"==c.fetchType&&!this.Xn)return a.b.ha(function(a){a()});null!=c.startIndex&&a.ob.t.startIndex.call(this,c.startIndex);return a.b.ha(function(a,k){c.success=function(){null!=d&&d.call(f,b,c);a()};c.error=function(a,c){null!=e&&e.call(f,b,a,c);k()};"enabled"==c.startFetch?(b.aa.isEmpty()||"undefined"===typeof b.aa.size())&&b.aa.fetch(c):b.aa.fetch(c)})};a.b.g("ArrayTableDataSource.prototype.fetch",
{fetch:a.ob.prototype.fetch});a.ob.prototype.get=function(a){return this.aa.get(a)};a.b.g("ArrayTableDataSource.prototype.get",{get:a.ob.prototype.get});a.ob.prototype.getCapability=function(){return"full"};a.b.g("ArrayTableDataSource.prototype.getCapability",{getCapability:a.ob.prototype.getCapability});a.ob.prototype.hasMore=function(){return null!=this.aa?this.aa.hasMore():!1};a.b.g("ArrayTableDataSource.prototype.hasMore",{hasMore:a.ob.prototype.hasMore});a.ob.prototype.indexOf=function(a){return this.aa.indexOf(a)};
a.b.g("ArrayTableDataSource.prototype.indexOf",{indexOf:a.ob.prototype.indexOf});a.ob.prototype.remove=function(a,b){this.aa.remove(a,b)};a.b.g("ArrayTableDataSource.prototype.remove",{remove:a.ob.prototype.remove});a.ob.prototype.reset=function(a,b){this.aa.reset(a,b)};a.b.g("ArrayTableDataSource.prototype.reset",{reset:a.ob.prototype.reset});a.ob.prototype.size=function(){return this.aa.size()};a.b.g("ArrayTableDataSource.prototype.size",{size:a.ob.prototype.size});a.ob.prototype.sort=function(c){if(null==
c)return this.aa.comparator=null,a.b.ha(function(a){a()});var b=c.key;c=c.direction;var d=null;"ascending"==c?d=function(a){return f.isFunction(a.get)?a.get(b):a[b]()}:"descending"==c&&(d=function(a,c){var d,e;f.isFunction(a.get)?(d=a.get(b),e=c.get(b)):(d=a[b](),e=c[b]());return d===e?0:d>e?-1:1});this.aa.comparator=d;var e=this;return a.b.ha(function(a){e.aa.sort();a()})};a.b.g("ArrayTableDataSource.prototype.sort",{sort:a.ob.prototype.sort});a.ob.prototype.totalSize=function(){return this.aa.totalSize()};
a.b.g("ArrayTableDataSource.prototype.totalSize",{totalSize:a.ob.prototype.totalSize});a.ob.prototype.Gm=function(){var c=this;this.aa.on(a.Q.v.ADD,function(b){c.Rc=!1;a.N.t.handleEvent.call(c,a.N.v.ADD,b)});this.aa.on(a.Q.v.REMOVE,function(b){c.Rc=!1;a.N.t.handleEvent.call(c,a.N.v.REMOVE,b)});this.aa.on(a.Q.v.REQUEST,function(b){c.Rc=!0;a.N.t.handleEvent.call(c,a.N.v.REQUEST,b)});this.aa.on(a.Q.v.RESET,function(b){c.Rc=!1;a.N.t.handleEvent.call(c,a.N.v.RESET,b)});this.aa.on(a.Q.v.SORT,function(b){c.Rc=
!1;a.N.t.handleEvent.call(c,a.N.v.SORT,b)});this.aa.on(a.Q.v.CHANGE,function(b){c.Rc=!1;a.N.t.handleEvent.call(c,a.N.v.CHANGE,b)});this.aa.on(a.Q.v.SYNC,function(b){c.Rc=!1;a.N.t.handleEvent.call(c,a.N.v.SYNC,b)});this.aa.on(a.Q.v.ERROR,function(b){c.Rc=!1;a.N.t.handleEvent.call(c,a.N.v.ERROR,b)})};(function(){a.Oa("oj.ojTable",f.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3ctable\x3e",widgetEventPrefix:"oj",options:{accessibility:null,currentRow:null,data:null,emptyText:null,horizontalGridVisible:"enabled",
rowRenderer:null,selection:[],selectionMode:null,verticalGridVisible:"enabled",columns:[{renderer:null,className:null,field:null,footerClassName:null,footerRenderer:null,footerStyle:null,headerClassName:null,headerRenderer:null,headerStyle:null,headerText:null,id:null,sortable:"auto",sortProperty:null,style:null}],columnsDefault:{renderer:null,className:null,field:null,footerClassName:null,footerRenderer:null,footerStyle:null,headerClassName:null,headerRenderer:null,headerStyle:null,headerText:null,
sortable:"auto",sortProperty:null,style:null},beforeCurrentRow:null,select:null,translations:{}},cb:{mL:"msgFetchingData",oL:"msgNoData",dL:"labelSelectColumn",Zz:"labelSelectRow"},xc:{DK:"Did not change current row due to error.",CK:"Error detail: {error}.",xK:"Did not change current row due to unavailable row index.",wK:"Unavailable row index: {rowIdx}.",FK:"Invalid row index value.",EK:"Row index: {rowIdx}.",ft:"Invalid data type.",et:"Please specify the appropriate data type."},LX:"_headerColumn",
MX:"_headerColumnText",JX:"_headerColumnAsc",KX:"_headerColumnDsc",rK:"_hdrCol",qL:"auto",Pd:"enabled",ym:"disabled",rL:"none",Zg:{wk:"single",Ap:"multiple"},gg:{qm:"ascending",tm:"descending"},yb:{Wz:16,Xz:32,RK:13,wp:38,vp:40,Uz:37,Vz:39,Tz:36,Sz:35,TK:9,SK:27,xp:"shiftKey"},columnMetaData:function(a){var b=this.zc();return null===a||0==arguments.length?b:b[a]},getNodeBySubId:function(c){if(null==c)return this.element?this.element[0]:null;var b=c.subId;if("oj-table-cell"===b)return b=c.rowIndex,
c=c.columnIndex,this.u().xo(b,c)[0];if("oj-table-header"===b||"oj-table-sort-ascending"===b||"oj-table-sort-descending"===b){if(c=c.index,c=this.u().Hc(c),null!=c){if("oj-table-header"===b)return c[0];b="oj-table-sort-ascending"===b?c.find("."+a.j.J.qk):c.find("."+a.j.J.sm);if(0<b.length)return b[0]}}else if("oj-table-footer"===b&&(c=c.index,b=this.u().hI(c),null!=b))return b[0];return null},refresh:function(){this._super();this.Wb(!0)},refreshRow:function(c){var b=this.za();if(!b)return!1;if(isNaN(c)||
0>c||c>b.size()-1)throw b=this.xc.FK,c=a.ea.ub(this.xc.EK,{rowIdx:c.toString()}),new RangeError(b+"\n"+c);b=b.at(c);if(null==b)return!1;try{b instanceof a.bb?this.Qn(c,b):this.Rp(b)}catch(d){a.D.error(d)}return!0},_ComponentCreate:function(){this._super();this.Wm();this.fT();this._on(this.Jf);this.gT();this.Rn();var a=this;setInterval(function(){null!=a.SF&&(a.Fr(),a.SF=null)},100)},_destroy:function(){this.za();this.Pj();this.u().re().removeAttr(a.Components.Bp);this.element.children().remove("."+
a.j.J.wt);this.element.children().remove("."+a.j.J.vt);this.element.children().remove("."+a.j.J.xt);var c=this.u().Id();null!=c&&(c[0].parentNode.appendChild(this.element),c[0].parentNode.removeChild(c[0]));this.element.removeClass(a.j.J.uA)},Wm:function(){this.element.addClass(a.j.J.cM);this.u().GV(this.$v(),this.XD(),this.sh.bind(this),this.th.bind(this));this.u().tX();this.kF();this.jF();this.u().Mg(!0);this.options.disabled&&this.disable();this.gl(this.u().Id())},Jf:{blur:function(a){var b=this.u().bc();
0<b.has(a.relatedTarget).length||null!=a.originalEvent&&a.originalEvent.explicitOriginalTarget==b[0]||(this.vN(),this.sB(),this.hu(),this.Gr(!1))},focus:function(){var a=this.Nk(),b=this.lh();null==a&&null==b&&this.yh(0,!0,!1,null)},"click .oj-table-checkbox-acc-select-column":function(a){var b=this.u().qf(f(a.currentTarget)),d=f(a.currentTarget).is(":checked");d&&this.yh(b,!0,!0,null);this.rg(b,d,a.currentTarget,a);a.stopPropagation()},"click .oj-table-checkbox-acc-select-row":function(a){var b=
this.u().ro(f(a.currentTarget)),d=f(a.currentTarget).is(":checked");d&&this.qi(b,!0,null,a);this.sg(b,d,a.currentTarget,a);a.stopPropagation()},keydown:function(a){if(!(null!=this.u().Hi()&&0<this.u().Hi().has(a.target).length)&&(this.AM(a.keyCode),1==this.Ge().length||2==this.Ge().length)){if(this.Ad(this.yb.wp)||this.Ad(this.yb.vp)||this.Ad(this.yb.Xz)||this.Ad(this.yb.Tz)||this.Ad(this.yb.Sz))a.preventDefault(),a.stopPropagation();this.Ad(this.yb.wp)||this.Ad(this.yb.vp)?this.DQ(a):this.Ad(this.yb.Uz)||
this.Ad(this.yb.Vz)?this.BQ(a):this.Ad(this.yb.TK)&&this.CQ(a)}},keyup:function(a){if(!(null!=this.u().Hi()&&0<this.u().Hi().has(a.target).length)){if(1==this.Ge().length){var b=this.Ge()[0];b==this.yb.Xz?this.IQ(a):b==this.yb.RK?this.FQ(a):b==this.yb.Tz?this.HQ(a):b==this.yb.Sz?this.EQ(a):b==this.yb.SK&&this.GQ(a);this.Hw(b)}this.Hw(a.keyCode)}},"mouseenter .oj-table-column-header-cell":function(a){a=this.u().qf(f(a.currentTarget));this.qG(a)},"mouseleave .oj-table-column-header-cell":function(a){a=
this.u().qf(f(a.currentTarget));this.Aj(a,!0);this.Aj(a,!1)},"mouseenter .oj-table-data-cell":function(a){a=this.u().ro(f(a.currentTarget));this.sl(a,{hover:!0})},"mouseleave .oj-table-data-cell":function(a){a=this.u().ro(f(a.currentTarget));this.sl(a,{hover:!1})},"click .oj-table-column-header-asc-link":function(a){this.Ck();var b=this.u().qf(f(a.target)),d=this.u().Hc(b);d&&(d.data("sorted")==this.gg.qm?this.mg(b,!1):this.mg(b,!0),a.preventDefault(),a.stopPropagation())},"click .oj-table-column-header-acc-asc-link":function(a){this.Ck();
var b=this.u().qf(f(a.target));this.mg(b,!0);a.preventDefault();a.stopPropagation()},"click .oj-table-column-header-dsc-link":function(a){this.Ck();var b=this.u().qf(f(a.target)),d=this.u().Hc(b);d&&(d.data("sorted")==this.gg.tm?this.mg(b,!0):this.mg(b,!1),a.preventDefault(),a.stopPropagation())},"click .oj-table-column-header-acc-dsc-link":function(a){this.Ck();var b=this.u().qf(f(a.target));this.mg(b,!1);a.preventDefault();a.stopPropagation()},"click .oj-table-data-cell":function(c){this.Ck();var b=
this.u().ro(f(c.currentTarget));this.qi(b,!0,c.currentTarget,c);if(1==this.Ge().length){if(this.Ge()[0]==this.yb.Wz){var d=this.HP();if(null!=d)if(b<d){var e;for(e=b;e<=d;e++)this.sg(e,!0,c.currentTarget,c)}else for(e=d;e<=b;e++)this.sg(e,!0,c.currentTarget,c)}}else a.ba.Ho(c)?this.sg(b,!this.ln(b),c.currentTarget,c):0==this.Ge().length&&(this.Ek(),this.sg(b,!this.ln(b),c.currentTarget,c))},"click .oj-table-column-header-cell":function(c){this.Ck();var b=this.u().qf(f(c.currentTarget));this.yh(b,
!0,!0,c.currentTarget);if(1==this.Ge().length){if(this.Ge()[0]==this.yb.Wz){var d=this.GP();if(null!=d)if(b<d){var e;for(e=b;e<=d;e++)this.rg(e,!0,c.currentTarget,c)}else for(e=d;e<=b;e++)this.rg(e,!0,c.currentTarget,c)}}else a.ba.Ho(c)?this.rg(b,!this.dn(b),c.currentTarget,c):0==this.Ge().length&&(this.ju(),this.rg(b,!this.dn(b),c.currentTarget,c));c.preventDefault()}},Wb:function(a){this.qB();this.f!=this.options.data&&this.fu();this.KN!=this.u().QH()&&this.u().sH(this.sh.bind(this),this.th.bind(this));
this.u().BV();var b=this;setTimeout(function(){b.Bw(a)},0)},_setOption:function(a,b){var d=this.JR(a,b);this._superApply(arguments);d&&this.Wb(!0);"selection"==a&&this.Fr()},AM:function(a){var b=!1,d;for(d in this.yb)this.yb.hasOwnProperty(d)&&this.yb[d]==a&&(b=!0);if(b){b=this.Ge();d=!1;var e;for(e=0;e<b.length;e++)if(b[e]==a){d=!0;break}d||b.push(a)}},KA:function(c,b,d){var e=this.u().tH(c);this.u().Hy(e);this.u().vI(c,e,d);b instanceof a.bb?this.Qn(c,b,e,d):this.Rp(b)},Rp:function(a){var b=this;
a.then(function(a){setTimeout(function(){var c=a.index-b.za().startIndex();b.Qn(c,a);b.u().Mg()},0)})},Ck:function(){this.ND()||this.u().bc().focus()},qB:function(){this.Fk=null;this.Gr(!1)},fu:function(){null!=this.f&&this.Pj();this.f=null},vN:function(){this.aw=[]},sB:function(){var a=this.lh();null!=a&&this.yh(a,!1,!1,null);this.GA=-1},hu:function(){var a=this.Nk();null!=a&&this.qi(a,!1,null,null)},ju:function(){var a=this.$C(),b;for(b=0;b<a.length;b++)this.rg(a[b],!1,null)},Ek:function(){var a=
this.uv(),b;for(b=0;b<a.length;b++)this.sg(a[b],!1,null)},zN:function(c){var b=this.eQ();if(null!=b){var d=this.u().Hc(b),e=d.data("sorted");d.data("sorted",null);b!=c?e==this.gg.qm?this.Aj(b,!0):this.Aj(b,!1):(d.find("."+a.j.J.qk).removeClass(a.j.xa.qc),d.find("."+a.j.J.sm).removeClass(a.j.xa.qc))}},Gu:function(){if(null!=this.Cd){var c=this.Cd[this.Cd.length-1];null!=c&&(c=c.js,c==a.N.v.ADD?this.OO(this.Cd):c==a.N.v.REMOVE?this.QO(this.Cd):c==a.N.v.CHANGE&&this.PO(this.Cd),this.Cd=[])}},OO:function(a){var b=
!1;if(1<a.length){var d,e=!0;for(d=0;d<a.length;d++)if(0!=d&&a[d-1].vf!=a[d].vf-1){e=!1;break}if(e){b=this.u().re();e=f(document.createDocumentFragment());for(d=0;d<a.length;d++)this.KA(a[d].vf,a[d].row,e);0==a[0].vf?b.prepend(e):(d=this.u().Ag(a[0].vf),null!=d?b[0].insertBefore(e[0],d[0]):b[0].insertBefore(e[0],null));for(d=0;d<a.length;d++)for(this.u().wy(a[d].vf),e=this.zc(),b=0;b<e.length;b++)this.u().vy(a[d].vf,b);this.u().as();this.u().$r();b=!0}}if(!b)for(d=0;d<a.length;d++)this.KA(a[d].vf,
a[d].row);this.u().mo();this.u().Mg()},PO:function(c){var b;for(b=0;b<c.length;b++)c[b].row instanceof a.bb?this.Qn(c[b].vf,c[b].row):this.Rp(c[b].row);this.u().Mg()},QO:function(a){var b;for(b=0;b<a.length;b++)this.yF(a[b].vf);this.u().Mg()},Oc:function(a,b,d,e){this._trigger("optionChange",e,{option:a,previousValue:b,value:d,optionMetadata:{writeback:e?"shouldWrite":"shouldNotWrite"}})},zc:function(){this.Fk||(this.Fk=this.zC());return this.Fk},zC:function(){var a=this.options.columns,b=this.options.columnsDefault;
if((0==a.length||1==a.length&&null==a[0].id&&null==a[0].headerText&&null==a[0].field)&&null==b.headerText&&null==b.field)return[];var d=[],e;for(e=0;e<a.length;e++)d[e]=f.extend({},b,a[e]);a=[];for(e=0;e<d.length;e++)a.push(d[e]);e=this.za();b=!1;null!=e&&"full"==e.getCapability("sort")&&(b=!0);for(e=0;e<d.length;e++)null==a[e].id&&(a[e].id=this.rK+e),null!=a[e].sortable&&a[e].sortable!=this.qL||!b||(a[e].sortable=this.Pd);return a},xC:function(c){var b=this.zc();if(null!=b){var d,e;for(d=0;d<b.length;d++)if(e=
b[d],a.b.xg(e.id,c))return d}return null},yC:function(a){a=this.u().bc().find(a);var b=[];if(a&&0<a.length){var d,e,g,h;for(d=0;d<a.length;d++){h=this.u().qf(f(a.get(d)));g=!1;for(e=0;e<b.length;e++)b[e]==h&&(g=!0);g||b.push(h)}}return b},Bq:function(a){var b=this.zc();return null!=b&&a<b.length?b[a].id:null},Cq:function(a,b){var d=this.zc()[a];return"cell"==b?d.renderer:"footer"==b?d.footerRenderer:"header"==b?d.headerRenderer:null},rP:function(){return this.za()?this.Hk:null},za:function(){if(!this.f&&
null!=this.options.data){var c=this.options.data;if(c instanceof a.N||c instanceof a.Ya)this.f=c;else throw Error(this.xc.ft+"\n"+this.xc.et);this.Rn();if(c instanceof a.N){var b=this;setTimeout(function(){0==b.f.size()&&b.za().fetch({fetchType:"init"})},0)}}return this.f},lh:function(){return this.yC("."+a.j.J.rk+"."+a.j.xa.Df)[0]},Nk:function(){return this.ZC("."+a.j.J.Uh+"."+a.j.xa.Df)[0]},dY:function(a){return this.bv(a).Oe},dn:function(a){return this.bv(a).selected},Dq:function(){return null==
this.options.selectionMode?null:this.options.selectionMode.column},bv:function(c){c=this.u().Hc(c);return{Oe:c.hasClass(a.j.xa.Df),selected:c.hasClass(a.j.xa.qc)}},Ge:function(){this.aw||(this.aw=[]);return this.aw.reverse()},GP:function(){return null!=this.gi&&0<this.gi.length?this.gi[0]:null},HP:function(){return null!=this.hi&&0<this.hi.length?this.hi[0]:null},fY:function(a,b){var d;for(d=0;d<f(a).length;d++)if(f(f(a)[d]).is(b))return f(a)[d];return null},lY:function(c){return this.u().Ag(c).hasClass(a.j.xa.Df)},
mY:function(c){return this.u().Ag(c).hasClass(a.j.xa.qp)},sv:function(c){var b=this.za();if(null!=b){var d=b.startIndex(),e=d+b.size(),f,h,k;for(f=d;f<e;f++)if(k=f-d,h=b.at(f),null!=h&&h instanceof a.bb&&a.b.xg(h.id,c))return k}return null},ZC:function(a){a=this.u().bc().find(a);var b=[];if(a&&0<a.length){var d,e,g,h;for(d=0;d<a.length;d++){g=this.u().ro(f(a.get(d)));h=!1;for(e=0;e<b.length;e++)b[e]==g&&(h=!0);h||b.push(g)}}return b},Ok:function(c){var b=this.za();return null!=b&&(c=b.at(c),null!=
c&&c instanceof a.bb)?c.id:null},aQ:function(){return this.options.rowRenderer},ln:function(c){return this.u().Ag(c).hasClass(a.j.xa.qc)},tv:function(){return null==this.options.selectionMode?null:this.options.selectionMode.row},$C:function(){return this.yC("."+a.j.J.rk+"."+a.j.xa.qc)},uv:function(){return this.ZC("."+a.j.J.Uh+"."+a.j.xa.qc)},vv:function(){var a=this.za(),a=null!=a?a.startIndex():0,b=this.uv(),d=this.$C(),e=null,f=!0;if(null!=b&&0<b.length)e=b;else if(null!=d&&0<d.length)e=d,f=!1;
else return null;var b=[],d=0,h=null,k,l,m,n;for(n=0;n<e.length;n++)l=e[n]+a,0==n?(k=[],k.startIndex=[],k.endIndex=[],k.startKey=[],k.endKey=[],f?(k.startIndex.row=l,k.endIndex.row=l,m=this.Ok(l),k.startKey.row=m,k.endKey.row=m):(k.startIndex.column=l,k.endIndex.column=l,m=this.Bq(l),k.startKey.column=m,k.endKey.column=m),b[0]=k):(k=b[d],f?(k.endIndex.row=l,m=this.Ok(l),k.endKey.row=m):(k.endIndex.column=l,m=this.Bq(l),k.endKey.column=m),l!=h+1&&(f?(k.endIndex.row=h,m=this.Ok(h),k.endKey.row=m,k=
[],k.startIndex=[],k.endIndex=[],k.startKey=[],k.endKey=[],k.startIndex.row=l,k.endIndex.row=l,m=this.Ok(l),k.startKey.row=m,k.endKey.row=m):(k.endIndex.column=h,m=this.Bq(h),k.endKey.column=m,k=[],k.startIndex=[],k.endIndex=[],k.startKey=[],k.endKey=[],k.startIndex.column=l,k.endIndex.column=l,m=this.Bq(l),k.startKey.column=m,k.endKey.column=m),d++,b[d]=k)),h=l;return b},eQ:function(){var a=this.u().Rx(),b,d;for(b=0;b<a.length;b++)if(d=f(a[b]).data("sorted"),null!=d)return b;return null},Oq:function(a){a=
a.find(":tabbable");return null!=a&&0<a.length?a:null},u:function(){this.AG||(this.AG=new a.j(this));return this.AG},nY:function(){var a=this.u().Hl();return null!=a?a.length:0},sh:function(a,b){this.u();this.lj=a.originalEvent.originalEvent;if(this.ER(f(this.lj.target)))return!1;b.openOptions.position="keydown"===this.lj.type?{my:"start top",at:"start bottom",of:this.lj.target}:{my:"start top",at:"start bottom"};var d=this.u().Gi(f(this.lj.target),"oj-table-column-header-cell"),d=null==d?this.u().Hc(this.GA):
d,e=this.u().Gi(f(this.lj.target),"oj-table-data-cell");null!=e&&(d=this.u().qf(e),d=this.u().Hc(d));if(d.attr("data-oj-sortable")==this.Pd)this.u().gr.find("[data-oj-command\x3doj-table-sortAsc]").removeClass("oj-disabled"),this.u().gr.find("[data-oj-command\x3doj-table-sortDsc]").removeClass("oj-disabled");else return this.u().gr.find("[data-oj-command\x3doj-table-sortAsc]").addClass("oj-disabled"),this.u().gr.find("[data-oj-command\x3doj-table-sortDsc]").addClass("oj-disabled"),!1},th:function(a,
b){var d=b.item.attr("data-oj-command"),e=this.u().Gi(f(this.lj.target),"oj-table-column-header-cell"),g=this.u().Gi(f(this.lj.target),"oj-table-data-cell"),h=null;null!=e&&(h=this.u().qf(e));null!=g&&(h=this.u().qf(g));"oj-table-sortAsc"==d?this.mg(h,!0):"oj-table-sortDsc"==d&&this.mg(h,!1)},pQ:function(c){this.zj();a.D.error(c)},qQ:function(){this.Sw();this.kq=!0},Fv:function(a){try{this.kq&&this.KB?(this.KB=this.kq=!1,this.Qq()):a.refresh&&this.Bw(!0),this.zj()}catch(b){throw b;}finally{this.KB=
this.kq=!1}},Pq:function(){this.zj();this.Bw();this.Kw(null,null)},Gv:function(c){if(c&&void 0!==c.index){var b=c.index,d=this.za();this.zj();var e=d.startIndex(),d=e+d.size()-1;null!=b&&(b<e||b>d)||(0<=b&&(b-=e),this.yw(a.N.v.ADD,b,c))}},rQ:function(c){var b=c.index,d=this.za();this.zj();var e=d.startIndex(),d=e+d.size()-1;null!=b&&(b<e||b>d)||(0<=b&&(b-=e),this.yw(a.N.v.CHANGE,b,c))},Hv:function(c){var b=c.index,d=this.za();this.zj();d=d.startIndex();this.yw(a.N.v.REMOVE,b-d,c)},Qq:function(){this.kq||
(this.zj(),this.hF(),this.u().Mg(!0),this.Ek(),this.options.selection=null,this.Kw(this.Hk,null))},BQ:function(a){var b=this.lh(),d=this.zc();if(null!=b){var e=b;this.Ad(this.yb.Uz)?e=0<b?b-1:b:this.Ad(this.yb.Vz)&&(e=b<d.length-1?b+1:b);e!=b&&(this.yh(e,!0,!1,null),a[this.yb.xp]&&(d=this.dn(e),this.rg(e,!d,null,a),d&&this.dn(b)&&this.rg(b,!1,null,a)))}},CQ:function(a){var b=!1,d=this.Nk();if(null!=d&&this.BG){var e=this.u().re(),e=this.Oq(e);if(null!=e){var b=!0,g=document.activeElement,h=!1,k;for(k=
0;k<e.length;k++)if(g==e[k]){h=!0;break}if(h)return;a[this.yb.xp]||(d=this.u().Ag(d),d=this.Oq(d),null!=d?f(d[0]).focus():f(e[0]).focus(),a.preventDefault(),a.stopPropagation())}}b||(e=this.u().bc(),b=this.Oq(f(document)),e=this.Oq(e),e=null!=e?e.length:0,d=b.index(this.u().bc()),a[this.yb.xp]?f(b[d-1]).focus():f(b[d+e+1]).focus(),a.preventDefault(),a.stopPropagation());this.Hw(a.keyCode)},DQ:function(a){var b=this.Nk(),d=this.lh();if(null!=b){var e=this.za(),d=b;this.Ad(this.yb.wp)?d=0<b?b-1:b:this.Ad(this.yb.vp)&&
(d=b<e.size()-1?b+1:b);d!=b?(this.qi(d,!0,null,a),a[this.yb.xp]&&(e=this.ln(d),this.sg(d,!e,null,a),e&&this.ln(b)&&this.sg(b,!1,null,a))):d==b&&0==b&&this.Ad(this.yb.wp)&&this.yh(0,!0,!1,null)}else null!=d&&this.Ad(this.yb.vp)&&this.qi(0,!0,null,a)},EQ:function(){var a=this.lh();null!=a&&a!=this.zc().length-1&&this.yh(this.zc().length-1,!0,!1,null)},FQ:function(){var a=this.lh();if(null!=a&&this.zc()[a].sortable==this.Pd){var b=this.u().Hc(a).data("sorted");null==b||b==this.gg.tm?this.mg(a,!0):this.mg(a,
!1)}},GQ:function(a){a.preventDefault();a.stopPropagation();this.u().bc().focus();this.Gr(!1)},HQ:function(){var a=this.lh();null!=a&&0!=a&&this.yh(0,!0,!1,null)},IQ:function(a){var b=this.Nk();null!=b?this.sg(b,!this.ln(b),null,a):(b=this.lh(),null!=b&&(this.Ek(),this.rg(b,!this.dn(b),null,a)))},mg:function(c,b){this.zN(c);var d=this.zc()[c],e=null==d.sortProperty?d.field:d.sortProperty,f=this.u().Hc(c);this.wR(e,b,null);this.rG=d;b?(f.data("sorted",this.gg.qm),d=f.find("."+a.j.J.qk),d.addClass(a.j.xa.xd),
d.removeClass(a.j.xa.Bb),d=f.find("."+a.j.J.rm),d.removeClass(a.j.xa.Bb),d=f.find("."+a.j.J.op)):(f.data("sorted",this.gg.tm),d=f.find("."+a.j.J.sm),d.addClass(a.j.xa.xd),d.removeClass(a.j.xa.Bb),d=f.find("."+a.j.J.op),d.removeClass(a.j.xa.Bb),d=f.find("."+a.j.J.rm));d.addClass(a.j.xa.Bb);this.Aj(c,!b)},vD:function(){this.u().yo().css("display","none")},zj:function(){this.u().qs().css("display","none")},Aj:function(c,b){if(this.zc()[c].sortable==this.Pd){var d=this.u().Hc(c),e=d.data("sorted");!b||
null!=e&&e!=this.gg.tm?b||null!=e&&e!=this.gg.qm||(d=d.find("."+a.j.J.sm),d.addClass(a.j.xa.Bb),d.removeClass(a.j.xa.xd),d.removeClass(a.j.xa.qc)):(d=d.find("."+a.j.J.qk),d.addClass(a.j.xa.Bb),d.removeClass(a.j.xa.xd),d.removeClass(a.j.xa.qc))}},wR:function(a,b){var d=this.za();if(!d)return null;this.Sw();var e={};e.key=a;e.direction=b?this.gg.qm:this.gg.tm;d.sort(e)},xR:function(){if(null!=this.Fk){var a=this.zC();if(this.Fk.length!=a.length)return!0;var b,d;for(b=0;b<a.length;b++)for(d in a[b])if(a[b].hasOwnProperty(d)&&
a[b][d]!=this.Fk[b][d])return!0;return!1}return!0},ND:function(){var a=f(document.activeElement),b=this.u().bc();return b[0]!=a[0]&&0==b.has(a).length?!1:!0},Ad:function(a){var b=this.Ge(),d;for(d=0;d<b.length;d++)if(b[d]==a)return!0;return!1},ER:function(a){for(var b,d=this.u().bc();null!=a&&a[0]!=d[0]&&"TD"!=(b=a.prop("nodeName"))&&"TH"!=b;)if(3==a[0].nodeType)a=a[0].parentNode;else{var e=a.attr("tabIndex");if(null!=e&&0<=e||b.match(/^INPUT|SELECT|OPTION|BUTTON|^A\b|TEXTAREA/)&&-1!=e)return!0;a=
a.parentNode}return!1},XD:function(){var a=this.zc(),b,d;for(b=0;b<a.length;b++)if(d=this.Cq(b,"footer"),null!=d)return!1;return!0},$v:function(){var a=this.zc(),b;for(b=0;b<a.length;b++)if(null!=a[b].headerText||null!=a[b].headerStyle||null!=a[b].sortable&&a[b].sortable!=this.rL||null!=a[b].sortProperty||null!=a[b].headerRenderer)return!1;return!0},IR:function(){return!0==this.zT},AY:function(){return this.BG},JR:function(c,b){var d=this.options;return"selection"==c||a.b.xg(b,d[c])?!1:!0},yw:function(a,
b,d){var e=this;this.Cd||(this.Cd=[]);var f=!1,h=this.Cd[this.Cd.length-1];null!=h&&h.js!=a&&(this.Gu(),f=!0);null!=this.ZE||f||(setTimeout(function(){e.Gu();e.ZE=null},0),this.ZE=!0);h=!1;for(f=0;f<this.Cd.length;f++)this.Cd[f].js==a&&this.Cd[f].vf==b&&this.Cd[f].row==d&&(this.Cd[f]={js:a,vf:b,row:d},h=!0);h||this.Cd.push({js:a,vf:b,row:d})},Bw:function(c){this.bT();c&&this.Gu();if(this.xR()||!this.IR()&&!this.$v())if(this.qB(),this.kF(),null!=this.rG){var b,d,e=!1,f=this.zc();if(null!=f){for(b=
0;b<f.length;b++)if(d=f[b],a.b.xg(d,this.rG)){e=!0;break}e||this.za().sort(null)}}this.jF();this.hF();null!=this.za()&&this.za().Rc&&this.Sw();this.u().Mg(c)},hF:function(){var c=this.u().re(),b=this.za(),d=c.children(),e;for(e=0;e<d.length;e++)this.yF(0);if(b&&0!=b.size()&&0!=this.zc().length){this.vD();this.u().as();this.u().$r();var g=f(document.createDocumentFragment()),d=b.startIndex(),h=d+b.size(),k,l,m;for(e=d;e<h;e++)l=e-d,k=b.at(e),null!=k&&(m=this.u().tH(l),this.u().Hy(m),this.u().vI(l,
m,g),k instanceof a.bb?this.Qn(l,k,m,g):this.Rp(k));c.append(g);for(e=d;e<h;e++)for(l=e-d,this.u().wy(l),b=this.zc(),c=0;c<b.length;c++)this.u().vy(l,c);this.u().as();this.u().$r()}else this.rU()},Qn:function(c,b,d,e){var f=this.aQ(),h=this.zc();(isNaN(c)||0>c)&&a.D.error("Error: Invalid rowIdx value: "+c);this.vD();if(null==d)if(d=this.u().Ag(c))d.empty(),this.u().Bx(c,d);else return;if(f){var h=this.u().ps(b,d[0]),k={};k.gX=h;k.rowRenderer=f;k.Ky=d;k.row=b;this.u().gV(c,k);null==e&&(this.u().wy(c),
this.u().as())}else for(f=0;f<h.length;f++)k=this.Cq(f,"cell"),this.u().oX(c,f,d,b,k),null==e&&(this.u().vy(c,f),this.u().$r());this.SF=!0},jF:function(){var c=this.zc(),b=this.u().Hi();if(!b){if(this.XD())return;b=this.u().uH();this.u().lJ(b)}b=this.u().Qx();b.empty();if(c&&0<c.length){this.u().vH(b);var d,e,g,h;for(d=0;d<c.length;d++)e=c[d],g=this.Cq(d,"footer"),h=this.u().LV(),this.u().mJ(d,h),this.u().AW(d,h),g&&(e=g({footerContext:this.u().ps(null,h[0]),column:e}),null!=e?(h.empty(),h.append(e)):
(h=f(b.children(":not(."+a.j.J.Ef+")")[d]),this.u().mJ(d,h)))}},kF:function(){var c=this.zc(),b=this.u().Ii();if(!b){if(this.$v())return;b=this.u().wH();this.u().nJ(b)}b=this.u().Il();b.empty();if(c&&0<c.length){var d=this.u().MV();b.append(d);for(var e,g,h,d=0;d<c.length;d++){e=c[d];g=this.Cq(d,"header");h=this.u().NV(d);this.u().BW(d,h);var k=f(h.find("."+a.j.J.rm)[0]),l=k.width(),k=k.height(),m=f(h.find("."+a.j.J.Bz)[0]);m.css("width",l+"px");m.css("height",k+"px");g&&(e=g({headerContext:this.u().ps(null,
h[0]),column:e}),null!=e?(h.empty(),h.append(e)):(h=f(b.children(":not(."+a.j.J.bt+")")[d]),this.u().gJ(d,h),this.u().oJ(d,h)));this.u().OV(d,this.Dq())}this.zT=!0}},bT:function(){var a=this.u().yo();a[0].parentNode.removeChild(a[0]);this.u().xH()},fT:function(){var a=f.event.special;a.ojtablecurrentrow={handle:function(a,c){return a.handleObj.handler.apply(this,[a,c])}};a.ojtablebeforecurrentrow={handle:function(a,c){return a.handleObj.handler.apply(this,[a,c])}};a.ojtablescroll={handle:function(a,
c){return a.handleObj.handler.apply(this,[a,c])}};a.ojtableselect={handle:function(a,c){return a.handleObj.handler.apply(this,[a,c])}}},Rn:function(){var c=this.za();if(null!=c){this.Pj();this.rb=[];this.rb.push({eventType:a.N.v.REQUEST,eventHandler:this.qQ.bind(this)});this.rb.push({eventType:a.N.v.SYNC,eventHandler:this.Fv.bind(this)});this.rb.push({eventType:a.N.v.SORT,eventHandler:this.Qq.bind(this)});this.rb.push({eventType:a.N.v.ADD,eventHandler:this.Gv.bind(this)});this.rb.push({eventType:a.N.v.REMOVE,
eventHandler:this.Hv.bind(this)});this.rb.push({eventType:a.N.v.CHANGE,eventHandler:this.rQ.bind(this)});this.rb.push({eventType:a.N.v.RESET,eventHandler:this.Pq.bind(this)});this.rb.push({eventType:a.N.v.ERROR,eventHandler:this.pQ.bind(this)});var b,d;for(b=0;b<this.rb.length;b++)(d=c.on(this.rb[b].eventType,this.rb[b].eventHandler))&&(this.rb[b].eventHandler=d)}},gT:function(){null!=this.u().uo()&&this.u().uo().scroll(function(a){var b=f(a.target).scrollLeft(),d=f(a.target)[0].scrollWidth-f(a.target)[0].clientWidth;
"rtl"===this.Ec()&&(b=Math.abs(b),/webkit/.test(navigator.userAgent.toLowerCase())&&(b=d-b));var d=f(a.target).scrollTop(),e=this.u().Ii();e&&(this.u().Dg()?"rtl"===this.Ec()?e.css("right","-"+b+"px"):e.css("left","-"+b+"px"):(e=this.u().Il())&&("rtl"===this.Ec()?e.css("right","-"+b+"px"):e.css("left","-"+b+"px")),this._trigger("scroll",a,{scrollLeft:f(a.target).scrollLeft(),scrollTop:d}))}.bind(this))},gl:function(c){if(!this.Zv){var b=this;a.ba.ug(c[0],function(){var a=b.u().Id().outerHeight(),
c=b.u().Id().outerWidth();b.u().Mg(!1,c,a)});this.Zv=!0}},Hw:function(a){var b=this.Ge(),d;for(d=0;d<b.length;d++)b[d]==a&&b.splice(d,1)},yF:function(a){var b=this.u().Hl(),d=null;null!=b&&a<b.length&&0<=a&&(d=f(b[a]),null!=d&&(a=f.inArray(d[0],this.hoverable),-1<a&&this.hoverable.splice(a,1),d[0].parentNode.removeChild(d[0]),this.u().mo()))},RT:function(a){var b=this.u().re(),d=this.u().Hc(a);if(d){a=this.u().bI();var d=d.get(0).getBoundingClientRect(),e=b.get(0).getBoundingClientRect(),f=!1;d.left<
e.left&&(f=e.left-d.left,b.scrollLeft(b.scrollLeft()-f),f=!0);d.right>e.right-a&&!f&&(f=d.right-e.right+a,b.scrollLeft(b.scrollLeft()+f))}},ST:function(a){var b=this.u().Ag(a);a=this.u().nW();var b=b.get(0).getBoundingClientRect(),d=this.u().uo(),e=d.get(0).getBoundingClientRect(),f=!1;b.bottom>e.bottom-a&&(a=b.bottom-e.bottom+a,d.scrollTop(d.scrollTop()+a),f=!0);b.top<e.top&&!f&&(a=e.top-b.top,d.scrollTop(d.scrollTop()-a))},Kw:function(c,b){var d=this.Hk;if(null==c)this.Hk=null,this.options.currentRow=
null,this.qi(-1,!0,null,b),this.Oc("currentRow",d,this.options.currentRow,b);else{var e=this.za(),f=c.rowIndex,h=c.rowKey;null!=h?f=this.sv(h):h=this.Ok(f);c={rowIndex:f,rowKey:h};if(-1!=f&&(!e||0==e.size()||-1>f)){var e=this.xc.xK,k=a.ea.ub(this.xc.wK,{rowIdx:f});throw Error(e+"\n"+k);}if(!a.b.xg(this.Hk,c)){try{this._trigger("beforecurrentrow",b,{currentRow:{rowIndex:f,rowKey:h},previousCurrentRow:this.Hk})}catch(l){e=this.xc.DK,k=a.ea.ub(this.xc.CK,{error:l.toString()}),a.D.info(e+"\n"+k)}this.Hk=
{rowIndex:f,rowKey:h};this.options.currentRow={rowIndex:f,rowKey:h};this.qi(f,!0,null,b);this.Oc("currentRow",d,this.options.currentRow,b)}}},yh:function(a,b,d,e){if(b){var f=this.lh();null!=f&&f!=a&&this.yh(f,!1,!1,e);this.hu();d&&this.Ek();this.RT(a);this.GA=a}this.aG(a,{Oe:b},e)},rg:function(c,b,d,e){if(this.Dq()==this.Zg.wk||this.Dq()==this.Zg.Ap)(isNaN(c)||0>c)&&a.D.error("Error: Invalid column selection value: "+c),this.Dq()==this.Zg.wk&&b&&this.ju(),this.aG(c,{selected:b},d,e),this.cU(c,b),
c=this.u().iI(c),f(c.children("."+a.j.J.vz)[0]).prop("checked",b),b=this.vv(),this.options.selection=b},aG:function(c,b,d,e){if(d=this.u().Hc(c)){var f=b.Oe;b=b.selected;if(null!=b){var h=!1;d.hasClass(a.j.xa.qc)!=b&&(b?d.addClass(a.j.xa.qc):d.removeClass(a.j.xa.qc),h=!0);h&&this._trigger("select",e,{column:c,selectionAdded:b})}null!=f&&(f?(d.addClass(a.j.xa.Df),this.qG(c)):(d.removeClass(a.j.xa.Df),this.Aj(c,!0),this.Aj(c,!1)));this.TU(c)}},cU:function(a,b){this.gi||(this.gi=[]);var d;for(d=0;d<
this.gi.length;d++)if(this.gi[d]==a){this.gi.splice(d,1);break}b&&this.gi.push(a)},eU:function(a,b){this.hi||(this.hi=[]);for(var d=0;d<this.hi.length;d++)if(this.hi[d]==a){this.hi.splice(d,1);break}b&&this.hi.push(a)},qi:function(c,b,d,e){if(-1==c)this.hu();else{var f=this.u().Ag(c);if(f){if(b){var h=this.Nk();null!=h&&h!=c&&this.qi(h,!1,d,null);d=this.Ok(c);this.Kw({rowIndex:c,rowKey:d},e);f.addClass(a.j.xa.Df);this.ST(c);this.sl(c,{Oe:!0,hover:!1});this.sB();this.ju();this.Gr(!0)}else f.removeClass(a.j.xa.Df);
this.sl(c,{Oe:b})}}},sg:function(c,b,d,e){if(this.tv()==this.Zg.wk||this.tv()==this.Zg.Ap){(isNaN(c)||0>c)&&a.D.error("Error: Invalid row selection value: "+c);this.tv()==this.Zg.wk&&b&&this.Ek();d=this.u().Ag(c);var g=!1;d.hasClass(a.j.xa.qc)!=b&&(b?d.addClass(a.j.xa.qc):d.removeClass(a.j.xa.qc),g=!0);g&&this._trigger("select",e,{row:c,selectionAdded:b});g&&(b?this.sl(c,{hover:!1,Oe:!1,selected:!0}):this.sl(c,{selected:!1}));this.eU(c,b);c=this.u().eI(d);f(c.children("."+a.j.J.wz)[0]).prop("checked",
b);b=this.vv();this.options.selection=b}},Fr:function(){var c=this.options.selection;if(null!=c&&0<c.length){var b=this.vv();if(!a.b.xg(c,b)){b=this.za();b=null!=b?b.startIndex():0;this.Ek();var d,e,f,h,k,l;for(d=0;d<c.length;d++){e=c[d];if(null==e.startKey&&null==e.startIndex||null==e.endKey&&null==e.endIndex)return a.D.error("Error: Invalid range object in selection. Both start and end objects must be specified"),null;null!=e.startKey&&null!=e.startKey.row&&(f=this.sv(e.startKey.row));null!=e.endKey&&
null!=e.endKey.row&&(h=this.sv(e.endKey.row));null!=e.startKey&&null!=e.startKey.column&&(k=this.xC(e.startKey.column));null!=e.endKey&&null!=e.endKey.column&&(l=this.xC(e.endKey.column));null==f&&null!=e.startIndex&&(f=e.startIndex.row);null==h&&null!=e.endIndex&&(h=e.endIndex.row);null==k&&null!=e.startIndex&&(k=e.startIndex.column);null==l&&null!=e.endIndex&&(l=e.endIndex.column);if(null!=f&&null!=h&&null!=k&&null!=l)return a.D.error("Error: Invalid range object in selection - Can only support row or column selection. Not both"),
null;if(null!=f&&null!=h){if(f-=b,h-=b,0<=f&&0<=h)for(e=f;e<=h;e++)try{this.sg(e,!0,null)}catch(m){a.D.error("Error: "+m)}}else if(null!=k&&null!=l)for(e=k;e<=l;e++)try{this.rg(e,!0,null)}catch(n){a.D.error("Error: "+n)}else return a.D.error("Error: Invalid range object in selection - \n start row: "+f+"\nend row: "+h+"\nstart column: "+k+"\nend column: "+l),null}}}},Gr:function(a){this.BG=a},rU:function(){this.u().yo().css("display","inline")},Sw:function(){this.u().qs().css("display","inline")},
qG:function(c){if(this.zc()[c].sortable==this.Pd&&(c=this.u().Hc(c))&&null==c.data("sorted")){var b=c.find("."+a.j.J.qk);b.addClass(a.j.xa.xd);b.removeClass(a.j.xa.Bb);c.find("."+a.j.J.rm).removeClass(a.j.xa.Bb);c.find("."+a.j.J.op).addClass(a.j.xa.Bb)}},Pj:function(){var a=this.za();if(null!=this.rb&&null!=a){var b;for(b=0;b<this.rb.length;b++)a.off(this.rb[b].eventType,this.rb[b].eventHandler)}},TU:function(c){var b=this.bv(c).selected,d=this.uv(),e=this.za(),g,h,k,l;for(g=0;g<e.size();g++)if(k=
this.u().xo(g,c),b)f(k).addClass(a.j.xa.qc);else{l=!1;for(h=0;h<d.length;h++)if(g==d[h]){l=!0;break}l||f(k).removeClass(a.j.xa.qc)}},sl:function(c,b){var d=this.u().fI(c),e=b.Oe,g=b.selected,h=b.hover;if(d){if(null!=h){var k;for(k=0;k<d.length;k++)h?f(d[k]).addClass(a.j.xa.qp):f(d[k]).removeClass(a.j.xa.qp)}if(null!=e)for(k=0;k<d.length;k++)e?f(d[k]).addClass(a.j.xa.Df):f(d[k]).removeClass(a.j.xa.Df);if(null!=g)for(k=0;k<d.length;k++)g?f(d[k]).addClass(a.j.xa.qc):f(d[k]).removeClass(a.j.xa.qc)}}})})();
a.$a=function(c,b){b=b||{};if(!(c instanceof a.ga))throw Error(a.N.xc._ERR_DATA_INVALID_TYPE_SUMMARY+"\n"+a.N.xc._ERR_DATA_INVALID_TYPE_DETAIL);this.Ra=c;this.aa=new a.ta(c,b);this.Gm();this.Init();if(null!=b&&("enabled"==b.startFetch||null==b.startFetch)||null==b)this.Xn=!0};o_("FlattenedTreeTableDataSource",a.$a,a);a.b.sa(a.$a,a.N,"oj.FlattenedTreeTableDataSource");a.$a.prototype.Init=function(){a.$a.t.Init.call(this)};a.b.g("FlattenedTreeTableDataSource.prototype.Init",{Init:a.$a.prototype.Init});
a.$a.prototype.getCapability=function(){return"full"};a.b.g("FlattenedTreeTableDataSource.prototype.getCapability",{getCapability:a.$a.prototype.getCapability});a.$a.prototype.getWrappedDataSource=function(){return this.Ra};a.b.g("FlattenedTreeTableDataSource.prototype.getWrappedDataSource",{getWrappedDataSource:a.$a.prototype.getWrappedDataSource});a.$a.prototype.fetch=function(c){c=c||{};var b=this,d=c.success,e=c.error,f=null==c.context?this:c.context;return"init"!=c.fetchType||this.Xn?a.b.ha(function(a,
k){c.success=function(){null!=d&&d.call(f,b,c);a()};c.error=function(a,c){null!=e&&e.call(f,b,a,c);k()};"enabled"==c.startFetch?(b.aa.isEmpty()||"undefined"===typeof b.aa.size())&&b.aa.fetch(c):b.aa.fetch(c)}):a.b.ha(function(a){a()})};a.b.g("FlattenedTreeTableDataSource.prototype.fetch",{fetch:a.$a.prototype.fetch});a.$a.prototype.at=function(a){return this.aa.at(a)};a.b.g("FlattenedTreeTableDataSource.prototype.at",{at:a.$a.prototype.at});a.$a.prototype.collapse=function(a){this.aa.collapse(a)};
a.b.g("FlattenedTreeTableDataSource.prototype.collapse",{collapse:a.$a.prototype.collapse});a.$a.prototype.expand=function(a){this.aa.expand(a)};a.b.g("FlattenedTreeTableDataSource.prototype.expand",{expand:a.$a.prototype.expand});a.$a.prototype.get=function(a){return this.aa.get(a)};a.b.g("FlattenedTreeTableDataSource.prototype.get",{get:a.$a.prototype.get});a.$a.prototype.hasMore=function(){return this.aa.hasMore()};a.b.g("FlattenedTreeTableDataSource.prototype.hasMore",{hasMore:a.$a.prototype.hasMore});
a.$a.prototype.indexOf=function(a){return this.aa.indexOf(a)};a.b.g("FlattenedTreeTableDataSource.prototype.indexOf",{indexOf:a.$a.prototype.indexOf});a.$a.prototype.on=function(c,b){if("expand"==c||"collapse"==c)this.aa.on(c,b);else a.$a.t.on.call(this,c,b)};a.b.g("FlattenedTreeTableDataSource.prototype.on",{on:a.$a.prototype.on});a.$a.prototype.off=function(c,b){"expand"==c||"collapse"==c?this.aa.off(c,b):a.$a.t.off.call(this,c,b)};a.b.g("FlattenedTreeTableDataSource.prototype.off",{off:a.$a.prototype.off});
a.$a.prototype.size=function(){return this.aa.size()};a.b.g("FlattenedTreeTableDataSource.prototype.size",{size:a.$a.prototype.size});a.$a.prototype.sort=function(c){if(null==c)return a.b.ha(function(a){a()});var b=this;c.axis="column";return a.b.ha(function(a){b.aa.sort(c);a()})};a.b.g("FlattenedTreeTableDataSource.prototype.sort",{sort:a.$a.prototype.sort});a.$a.prototype.startIndex=function(){return this.aa.startIndex()};a.b.g("FlattenedTreeTableDataSource.prototype.startIndex",{startIndex:a.$a.prototype.startIndex});
a.$a.prototype.totalSize=function(){return this.aa.totalSize()};a.b.g("FlattenedTreeTableDataSource.prototype.totalSize",{totalSize:a.$a.prototype.totalSize});a.$a.prototype.Gm=function(){var c=this;this.aa.on(a.Q.v.ADD,function(b){a.N.t.handleEvent.call(c,a.N.v.ADD,b)});this.aa.on(a.Q.v.REMOVE,function(b){a.N.t.handleEvent.call(c,a.N.v.REMOVE,b)});this.aa.on(a.Q.v.REQUEST,function(b){a.N.t.handleEvent.call(c,a.N.v.REQUEST,b)});this.aa.on(a.Q.v.RESET,function(b){a.N.t.handleEvent.call(c,a.N.v.RESET,
b)});this.aa.on(a.Q.v.SORT,function(b){a.N.t.handleEvent.call(c,a.N.v.SORT,b)});this.aa.on(a.Q.v.CHANGE,function(b){a.N.t.handleEvent.call(c,a.N.v.CHANGE,b)});this.aa.on(a.Q.v.SYNC,function(b){a.N.t.handleEvent.call(c,a.N.v.SYNC,b)});this.aa.on(a.Q.v.ERROR,function(b){a.N.t.handleEvent.call(c,a.N.v.ERROR,b)})};a.j=function(a){this.va=a;this.options=a.options;this.element=a.element;this.Init();var b=this;setInterval(function(){null!=b.vr&&(b.iF(b.vr.width,b.vr.height),b.vr=null)},50)};o_("TableDomUtils",
a.j,a);a.b.sa(a.j,a.b,"oj.TableDomUtils");a.j.prototype.Init=function(){a.j.t.Init.call(this)};a.b.g("TableDomUtils.prototype.Init",{Init:a.j.prototype.Init});a.j.prototype.fV=function(a,b,d){this.jh||(this.jh=[]);var e=this.jh[a];e||(e=[]);e[b]=d;this.jh[a]=e};a.j.prototype.gV=function(a,b){this.nj||(this.nj=[]);this.nj[a]=b};a.j.prototype.BV=function(){this.mo();this.Ed=null};a.j.prototype.mo=function(){this.Ut=null};a.j.prototype.$r=function(){if(null!=this.jh)for(;0<this.jh.length;)this.jh.pop()};
a.j.prototype.as=function(){if(null!=this.nj)for(;0<this.nj.length;)this.nj.pop()};a.j.prototype.sH=function(a,b){var d=null,e=null,g,h=this;if(null!=this.options.contextMenu||null!=this.bc().attr("contextmenu"))e=this.QH(),d=f(e),g=d.find("[data-oj-command]"),g.each(function(){var a;0===f(this).children("a").length&&(a=f(this).attr("data-oj-command").split("-"),f(this).replaceWith(h.EV(a[a.length-1])))}),this.gr=d,this.va.KN=e,d.ojMenu("refresh"),d.on("ojbeforeopen",a),d.on("ojselect",b)};a.j.prototype.EV=
function(a){return"sort"===a?f(this.Ax(a)).append(f("\x3cul\x3e\x3c/ul\x3e").append(f(this.Ax("sortAsc"))).append(f(this.Ax("sortDsc")))):null};a.j.prototype.Ax=function(a){var b=f(document.createElement("li"));b.attr("data-oj-command","oj-table-"+a);b.append(this.FV(a));return b};a.j.prototype.FV=function(a){var b=f(document.createElement("a"));b.attr("href","#");var d=null;"sort"==a?d=this.va.O("labelSort"):"sortAsc"==a?d=this.va.O("labelSortAsc"):"sortDsc"==a&&(d=this.va.O("labelSortDsc"));b.append(d);
return b};a.j.prototype.GV=function(a,b,d,e){this.bc();this.JV();this.sH(d,e);this.Dg()&&this.KV();a||this.wH();b||this.uH();this.HV();this.xH();this.PV()};a.j.prototype.HV=function(){var a=this.bc(),b=f(document.createElement("tbody"));a.append(b);this.Tt=b};a.j.prototype.IV=function(){return f(document.createElement("td"))};a.j.prototype.Bx=function(c,b){var d=this.eI(b),e=null==this.Ii()?!0:!1;if(null==d){d=f(document.createElement("td"));d.addClass(a.j.J.Fp);d.addClass(a.j.J.Ef);e||d.attr("headers",
a.j.Az);e=f(document.createElement("input"));e.attr("id","acc_sel_row"+c);e.attr("type","checkbox");e.attr("tabindex","-1");var g=this.va.O(this.va.cb.Zz);e.attr("title",g);e.addClass(a.j.J.wz);d.append(e);b.prepend(d)}};a.j.prototype.tH=function(a){var b=f(document.createElement("tr"));this.Bx(a,b);return b};a.j.prototype.JV=function(){var a=f(document.createElement("div"));this.element.parent()[0].replaceChild(a[0],this.element[0]);a.prepend(this.element);this.Wp=a};a.j.prototype.uH=function(){var a=
this.bc(),b=f(document.createElement("tfoot")),d=f(document.createElement("tr"));this.vH(d);b.append(d);d=this.Ii();null!=d?d.after(b):(d=this.re(),null!=d?d.before(b):a.append(b));return b};a.j.prototype.vH=function(c){var b=c.find("."+a.j.J.Ef);null!=b&&0<b.length?f(b[0]):(b=f(document.createElement("td")),b.addClass(a.j.J.Ef),b.attr("tabindex","-1"),c.prepend(b))};a.j.prototype.LV=function(){return f(document.createElement("td"))};a.j.prototype.wH=function(){var a=this.bc(),b=f(document.createElement("thead")),
d=f(document.createElement("tr"));this.Xt=d;b.append(d);d=this.Hi();null!=d?d.before(b):(d=this.re(),null!=d?d.before(b):a.append(b));return this.Wt=b};a.j.prototype.MV=function(){var c=f(document.createElement("th"));c.addClass(a.j.J.bt);c.addClass(a.j.J.Ef);c.attr("id",a.j.Az);var b=this.va.O(this.va.cb.Zz);c.attr("title",b);c.append(b);return c};a.j.prototype.NV=function(c){var b=this.va.columnMetaData(c),d=f(document.createElement("th"));this.oJ(c,d);c=f(document.createElement("div"));c.addClass(a.j.J.yz);
b.sortable==a.j.Pd&&("rtl"===this.va.Ec()?c.css("padding-left","0px"):c.css("padding-right","0px"));d.append(c);d.attr("abbr",b.headerText);d.attr("title",b.headerText);this.va._hoverable(d);var e=f(document.createElement("div"));e.addClass(a.j.J.Cz);null!=b.headerStyle&&e.attr("style",b.headerStyle);null!=b.headerClassName&&e.addClass(b.headerClassName);c.append(e);e.append(b.headerText);e=f(document.createElement("div"));e.addClass(a.j.J.rm);c.append(e);if(b.sortable==a.j.Pd){var g=f(document.createElement("a"));
g.addClass(a.j.J.qk);g.addClass(a.j.J.dj);g.addClass(a.j.J.pK);g.addClass(a.j.xa.Bb);g.addClass(a.j.xa.Zi);this.va._hoverable(g);e.append(g);g=f(document.createElement("a"));g.attr("tabindex","0");g.attr("href","#");g.addClass(a.j.J.nK);g.addClass(a.j.J.Ef);g.append(this.va.O("labelSortAsc"));e.append(g);d.attr("data-oj-sortable",a.j.Pd);e=f(document.createElement("div"));e.addClass(a.j.J.Bz);e.css("display","inline-block");c.append(e)}e=f(document.createElement("div"));e.addClass(a.j.J.op);e.addClass(a.j.xa.Bb);
c.append(e);b.sortable==a.j.Pd&&(b=f(document.createElement("a")),b.addClass(a.j.J.sm),b.addClass(a.j.J.dj),b.addClass(a.j.J.qK),b.addClass(a.j.xa.Bb),b.addClass(a.j.xa.Zi),this.va._hoverable(b),e.append(b),b=f(document.createElement("a")),b.attr("tabindex","0"),b.attr("href","#"),b.addClass(a.j.J.oK),b.addClass(a.j.J.Ef),b.append(this.va.O("labelSortDsc")),e.append(b));return d};a.j.prototype.OV=function(c,b){if(b==a.j.Zg.wk||b==a.j.Zg.Ap){var d=this.Hc(c),e=this.iI(c);if(null==e){e=f(document.createElement("div"));
e.addClass(a.j.J.xz);e.addClass(a.j.J.Ef);var g=f(document.createElement("input"));g.attr("id","acc_sel_col"+c);g.attr("type","checkbox");g.attr("tabindex","-1");var h=this.va.O(this.va.cb.dL);g.attr("title",h);g.addClass(a.j.J.vz);e.append(g);d.prepend(e)}}};a.j.prototype.KV=function(){var c=this.bc(),b=this.Id(),d=f(document.createElement("div"));d.addClass(a.j.J.zA);b[0].replaceChild(d[0],c[0]);d.append(c);this.Vt=d};a.j.prototype.xH=function(){var c=this.Id(),b=f(document.createElement("div"));
b.addClass(a.j.J.yA);b.css("display","none");var d=null,d=null!=this.options.emptyText?this.options.emptyText:this.va.O(this.va.cb.oL);b.append(d);c.append(b);this.Yt=b};a.j.prototype.PV=function(){var c=this.Id(),b=f(document.createElement("div"));b.addClass(a.j.J.xt);b.css("display","none");b.append(this.va.O(this.va.cb.mL));c.append(b);this.Zt=b};a.j.prototype.QH=function(){return null==this.options.contextMenu?"#"+this.bc().attr("contextmenu"):this.options.contextMenu};a.j.prototype.qf=function(c){var b=
this.Gi(c,a.j.J.yk);if(null!=b)return b.parent().children("."+a.j.J.yk).index(b);b=this.Gi(c,a.j.J.rk);if(null!=b)return b.parent().children("."+a.j.J.rk).index(b);c=this.Gi(c,a.j.J.zk);return null!=c?c.parent().children("."+a.j.J.zk).index(c):null};a.j.prototype.ro=function(c){return this.Gi(c,a.j.J.Uh).index()};a.j.prototype.qW=function(){var a=this.Id();a.attr("style","");this.vX(a);var b,d=[];for(b=0;b<a.children().length;b++)d[b]=f(a.children()[b]).css("display").toString(),f(a.children()[b]).css("display",
"none");var e=a.css("display").toString();a.css("display","inline-block");b=a.outerWidth()-a.innerWidth();var g=a.outerHeight()-a.innerHeight(),g=a.outerHeight()>g?a.outerHeight():0;b=a.outerWidth()>b?a.outerWidth():0;g={height:g,width:b};for(b=0;b<a.children().length;b++)f(a.children()[b]).css("display",d[b]);a.css("display",e);return 0==a[0].clientWidth?null:g};a.j.prototype.Gi=function(a,b){var d;if(null==a)return null;a=f(a);if(a.hasClass(b))return a;d=a.parents("."+b);return 0!=d.length?d.eq(0):
null};a.j.prototype.ps=function(c,b){var d=[];d.component=this.va;var e=this.options.data;e instanceof a.Ya&&(e=e.getWrappedDataSource());d.datasource=e;d.parentElement=b;if(null!=c){d.status=this.mW(c);var e=c.context,f;for(f in e)e.hasOwnProperty(f)&&(d[f]=e[f])}return d};a.j.prototype.mW=function(a){return{rowIndex:this.options.data.indexOf(a),rowKey:a.id,currentRow:this.va.rP()}};a.j.prototype.nW=function(){var a=this.uo();return 0<a.get(0).clientHeight?a.get(0).offsetHeight-a.get(0).clientHeight:
0};a.j.prototype.bI=function(){var a=this.uo();return 0<a.get(0).clientWidth?a.get(0).offsetWidth-a.get(0).clientWidth:0};a.j.prototype.uo=function(){return this.Dg()?this.gI():this.re()};a.j.prototype.bc=function(){return f(this.element)};a.j.prototype.re=function(){if(!this.Tt){var c=this.bc(),b=null;c&&(b=c.find("."+a.j.J.vt))&&0<b.length&&(this.Tt=f(b.get(0)))}return this.Tt};a.j.prototype.xo=function(a,b,d){return(a=this.fI(a,d))?a.length>b?f(a[b]):null:null};a.j.prototype.eI=function(c){return null!=
c&&(c=c.find("."+a.j.J.Fp),null!=c&&0<c.length)?f(c[0]):null};a.j.prototype.fI=function(c,b){b||(b=this.Ag(c));if(!b)return null;var d=b.children("."+a.j.J.yk);return null!=d&&0<d.length?d:null};a.j.prototype.Ag=function(a){var b=this.Hl();return b&&null!=a?b.length>a?f(b[a]):null:null};a.j.prototype.Hl=function(){if(!this.Ut){var c=this.re().children("."+a.j.J.Uh);null!=c&&0<c.length&&(this.Ut=c)}return this.Ut};a.j.prototype.Id=function(){this.Wp||(this.Dg()?this.Wp=f(this.element.get(0).parentNode.parentNode):
this.Wp=f(this.element.get(0).parentNode));return this.Wp};a.j.prototype.Hi=function(){var c=this.bc(),b=null;return c&&(b=c.find("."+a.j.J.vA))&&0<b.length?f(b.get(0)):null};a.j.prototype.hI=function(c){var b=this.Qx(),b=f(b).children("."+a.j.J.zk);return b.length>=c?f(b[c]):null};a.j.prototype.Qx=function(){if(!this.eB){var c=this.Hi();if(!c)return null;this.eB=f(c.children("."+a.j.J.wA).get(0))}return this.eB};a.j.prototype.Ii=function(){if(!this.Wt){var c=this.bc(),b=null;c&&(b=c.find("."+a.j.J.wt))&&
0<b.length&&(this.Wt=f(b.get(0)))}return this.Wt};a.j.prototype.Hc=function(a){var b=this.Rx();return b?b.length>a?f(b[a]):null:null};a.j.prototype.iI=function(c){c=this.Hc(c);return null!=c&&(c=c.find("."+a.j.J.xz),null!=c&&0<c.length)?f(c[0]):null};a.j.prototype.Rx=function(){var c=this.Il();return null!=c&&(c=c.children("."+a.j.J.rk),null!=c&&0<c.length)?c:null};a.j.prototype.Il=function(){if(!this.Xt){var c=this.Ii();if(!c)return null;this.Xt=f(c.children("."+a.j.J.xA).get(0))}return this.Xt};
a.j.prototype.gI=function(){if(!this.Vt){var c=this.Id();c&&(c=c.find("."+a.j.J.zA))&&0<c.length&&(this.Vt=f(c.get(0)))}return this.Vt};a.j.prototype.yo=function(){if(!this.Yt){var c=this.Id();c&&(c=c.find("."+a.j.J.yA))&&0<c.length&&(this.Yt=f(c.get(0)))}return this.Yt};a.j.prototype.qs=function(){if(!this.Zt){var c=this.Id();c&&(c=c.find("."+a.j.J.xt))&&0<c.length&&(this.Zt=f(c.get(0)))}return this.Zt};a.j.prototype.zW=function(c,b,d,e){this.Ey(c,b,d);c=f(e).children("."+a.j.J.yk);0==b?(b=e.find("."+
a.j.J.Fp),null!=b&&0<b.length?f(b[0]).after(d):e.prepend(d)):c.length>=b?f(c.get(b-1)).after(d):f(e).append(d)};a.j.prototype.vI=function(c,b,d){var e=null;if(null==d)var g=this.re(),e=g.children("."+a.j.J.Uh);else e=d.children("."+a.j.J.Uh);null==d?0==c?g.prepend(b):e.length>=c?f(e.get(c-1)).after(b):g.append(b):d.append(b);this.mo()};a.j.prototype.AW=function(c,b){var d=this.Qx(),e=f(d).children("."+a.j.J.zk);0==c?(e=d.find("."+a.j.J.Ef),null!=e&&0<e.length?f(e[0]).after(b):d.prepend(b)):d.length>=
c?f(e.get(c-1)).after(b):d.append(b)};a.j.prototype.BW=function(c,b){var d=this.Il(),e=this.Rx();this.gJ(c,b);var g=this.Hc(c);g?g.replaceWith(b):0==c?(e=d.find("."+a.j.J.bt),null!=e&&0<e.length?f(e[0]).after(b):d.prepend(b)):e.length>=c?f(e.get(c-1)).after(b):d.append(b)};a.j.prototype.Dg=function(){return this.PD()&&10>this.PD()?!0:!1};a.j.prototype.DI=function(){var a=this.Id(),b=this.yo(),d=b.css("display").toString();b.css("display","none");var e=this.qs(),f=e.css("display").toString();e.css("display",
"none");var h=[];h[0]=0<this.Ed.height&&0<a[0].clientHeight&&a[0].scrollHeight>a[0].clientHeight?!0:!1;h[1]=0<this.Ed.width&&0<a[0].clientWidth&&a[0].scrollWidth>a[0].clientWidth?!0:!1;b.css("display",d);e.css("display",f);return h};a.j.prototype.Mg=function(a,b,d){a?this.iF(b,d):this.vr={width:b,height:d}};a.j.prototype.vy=function(c,b){var d=this.uP(c,b);if(null!=d){var e=d.xV({cellContext:d.vV,column:d.column,data:d.data,row:d.row.attributes});null!=e?d.BX.append(e):(d=f(d.Ky.children(":not(."+
a.j.J.Fp+")")[b]),this.Ey(c,b,d),this.Gy(b,d))}};a.j.prototype.wy=function(a){var b=this.vP(a);if(null!=b){var d=b.rowRenderer({rowContext:b.gX,row:b.row.attributes}),b=b.Ky;null!=d?b.append(d):(d=this.re(),b=f(d.children()[a]),this.mo(),this.Hy(b));this.Bx(a,b);d=b.children("td");for(b=1;b<d.length;b++){var e=f(d[b]);this.Ey(a,b-1,e);this.Gy(b-1,e)}}};a.j.prototype.oX=function(a,b,d,e,f){var h=this.va.columnMetaData()[b],k=this.xo(a,b,d);k?k.empty():(k=this.IV(),this.Gy(b,k),this.zW(a,b,k,d));var l=
null;null!=h.field&&(l=e.get(h.field));if(f){var m=this.ps(e,k[0]),n={};n.xV=f;n.vV=m;n.data=l;n.row=e;n.column=h;n.Ky=d;n.BX=k;this.fV(a,b,n)}else k.append(l)};a.j.prototype.Ey=function(a,b,d){var e=this.options.accessibility;b=this.va.columnMetaData(b);var f=null,h=null==this.Ii()?!0:!1,f=null!=e&&null!=e.rowHeader?e.rowHeader:this.va.columnMetaData(0).id;a=f+"_"+a;e=b.id;f==b.id?(d.attr("id",a),h&&(e="")):e=h?a:e+" "+a;d.attr("headers")||d.attr("headers",e)};a.j.prototype.gJ=function(a,b){var d=
this.va.columnMetaData(a);b.attr("id")||b.attr("id",d.id)};a.j.prototype.tX=function(){var a=this.bc(),b=this.Id(),d=a.children("thead"),d=0<d.length?f(d[0]):null,e=a.children("tfoot"),e=0<e.length?f(e[0]):null,g=a.children("tbody"),g=0<g.length?f(g[0]):null;a.attr("tabindex","0");this.va._focusable(a);this.va._focusable(b);this.nJ(d);this.lJ(e);this.uX(g)};a.j.prototype.uX=function(c){c.addClass(a.j.J.vt);c.attr(a.Components.Bp,this.va.widgetName)};a.j.prototype.Gy=function(c,b){var d=this.options,
e=this.va.columnMetaData(c);null!=e.style&&b.attr("style")!=e.style&&b.attr("style",e.style);b.hasClass(a.j.J.yk)||b.addClass(a.j.J.yk);d.verticalGridVisible==a.j.Pd&&(b.hasClass(a.j.J.AA)||b.addClass(a.j.J.AA));e.className&&(b.hasClass(e.className)||b.addClass(e.className))};a.j.prototype.Hy=function(c){c.hasClass(a.j.J.Uh)||c.addClass(a.j.J.Uh);this.options.horizontalGridVisible==a.j.Pd&&(c.hasClass(a.j.J.Am)||c.addClass(a.j.J.Am));this.va._hoverable(c)};a.j.prototype.vX=function(c){var b=this.options.rootAttributes;
c.attr("class","");var d,e;for(d in b)b.hasOwnProperty(d)&&(e=b[d],c.attr(d,e));c.addClass(a.j.J.uA);c.addClass(a.j.J.bM);c.addClass(a.j.xa.Bt);b=this.bc();null!=b.attr("style")&&c.attr("style",b.attr("style").toString());c.css("display","block")};a.j.prototype.lJ=function(c){c&&(c.addClass(a.j.J.vA),f(c.children("tr")[0]).addClass(a.j.J.wA))};a.j.prototype.mJ=function(c,b){var d=this.options,e=c==this.va.columnMetaData().length-1?!0:!1,f=this.va.columnMetaData(c);b.attr("style",f.footerStyle);b.hasClass(a.j.J.zk)||
b.addClass(a.j.J.zk);d.verticalGridVisible!=a.j.Pd||e||b.addClass(a.j.J.dM);f.footerClassName&&b.addClass(f.footerClassName)};a.j.prototype.nJ=function(c){c&&(c.addClass(a.j.J.wt),c.css("display","table-header-group"),c=f(c.children("tr")[0]),c.addClass(a.j.J.xA),c.css("position","relative"))};a.j.prototype.oJ=function(c,b){this.va.columnMetaData();var d=this.va.columnMetaData(c);b.addClass(a.j.J.rk);b.attr("style",d.headerStyle)};a.j.prototype.uP=function(a,b){return null!=this.jh&&null!=this.jh[a]?
this.jh[a][b]:null};a.j.prototype.vP=function(a){return null!=this.nj?this.nj[a]:null};a.j.prototype.PD=function(){var a=navigator.userAgent;if("Microsoft Internet Explorer"==navigator.appName){if(a=/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(a),null!=a)return parseFloat(a[1])}else if(0<=a.indexOf("Trident"))return 11;return null};a.j.prototype.iF=function(a,b){var d=this.options,e=this.bc(),g=this.Ii(),h=this.Hi(),k=this.Il(),l=this.Id(),m=this.re(),n=d.data;"undefined"==typeof this.Tw&&("undefined"==typeof e.attr("style")?
this.Tw=null:this.Tw=e.attr("style"));if(!(0<a&&0<b&&!1===this.Zn&&!1===this.Mr)){this.wT();e.attr("style",this.Tw);if(null!=this.Ed)0<a&&this.Zn&&(this.Ed.width=a),0<b&&this.Mr&&(this.Ed.height=b);else{this.Ed=this.qW();if(null==this.Ed){var q=this;setTimeout(function(){q.Mg(!1,null,null)},100);return}this.Zn=this.Mr=!0;0==this.Ed.height&&(this.Mr=!1);0==this.Ed.width&&(this.Zn=!1)}this.ri||(this.ri=l.outerWidth()-l.innerWidth());this.Kr||(this.Kr=l.outerHeight()-l.innerHeight());var r=this.DI()[0],
t=this.DI()[1],p=!1,d=parseInt(e.css("minHeight"),10),u=parseInt(e.css("minWidth"),10);if(0<d){var p=!0,s=0;null!=g&&(s=g.height());var v=0;null!=h&&(v=h.height());m.css("min-height",d-s-v-this.Kr+"px")}0<u&&m.css("min-width",u-this.ri+"px");r||t||this.Mr||this.Zn||p?!1===this.VT()?(q=this,setTimeout(function(){q.Mg(!1,null,null)},100)):(e.css("display","block"),p=0,s=e.children("caption"),null!=s&&0<s.length&&(p=f(s[0]).height(),s.css("position","absolute"),s.css("top","0px"),s.css("display","inline"),
null!=g&&g.css("border-top",l.css("border-top").toString())),s=0,null!=g?(g.css("position","absolute"),g.css("top",p+"px"),k.css("display","block"),s=g.height(),this.Dg()?l.css("padding-top",s+p+"px"):m.css("top",s+p+"px")):this.Dg()&&l.css("padding-top",p+"px"),v=0,null!=h&&(h.css("position","absolute"),h.css("display","block"),v=h.height()),m.css("display","block"),this.Dg()||(m.css("position","absolute"),m.css("overflow-y","auto"),this.Zn&&m.css("width",this.Ed.width-this.ri),t?(null!=n&&0<n.size()?
(m.css("overflow-x","auto"),null!=g&&g.css("width",this.Ed.width-this.ri),l.css("overflow-x","hidden")):l.css("overflow-x","auto"),null!=k&&k.css("position","relative")):m.css("overflow-x","hidden"),k=this.Ed.height-s-v-p-this.Kr,0<k&&(m.css("height",k+"px"),m.css("min-height",k+"px"))),t||(null==n||0==n.size())&&null!=g&&0<g.width()&&m.css("width",g.width()+"px"),k=m.width(),null!=g&&(n=this.bI(),0<n?(g.css("overflow","hidden"),g.css("width",k-n-this.ri+"px")):g.css("width",k+"px")),this.Dg()&&(g=
this.gI(),g.css("overflow","auto"),t&&g.css("width",this.Ed.width),r&&g.css("height",this.Ed.height-s-v),m.css("float","left")),null!=h&&(h.css("bottom","0px"),h.css("width",k+"px")),0==this.Ed.width&&(this.Dg()?l.css("width",m.width()+this.ri+"px"):(m.css("display","inline-block"),e.css("width",m.width()+this.ri+"px"),l.css("width",m.width()+this.ri+"px"),m.css("display","block"))),0==this.Ed.height&&(h=s+v+p+m.height()+this.Kr,h>d&&(this.Dg()||e.css("height",h+"px"),l.css("height",h+"px"))),this.zF(),
this.lF()):(null!=n&&0<n.size()?m.css("display","table-row-group"):m.css("display","block"),this.lF(),this.zF())}};a.j.prototype.lF=function(){var c=this.Id(),b=this.re(),d=this.qs(),e=this.yo(),f="rtl"===this.va.Ec(),c={my:"center",at:"center",collision:"none",of:c},c=a.he.Jg(c,f);d.position(c);c={my:"start top",at:"start top",collision:"none",of:b};c=a.he.Jg(c,f);e.position(c);e.css("left","0px;")};a.j.prototype.tT=function(){var a=this.options.data,b=this.va.columnMetaData(),d,e;for(d=0;d<b.length;d++)e=
this.Hc(d),null!=e&&e.css("min-width","");if(null!=a&&0<a.size()&&(d=this.Hl(),null!=d&&0<d.length))for(d=0;d<b.length;d++)a=this.xo(0,d,null),null!=a&&a.css("min-width","")};a.j.prototype.zF=function(){if(this.options.horizontalGridVisible==a.j.Pd){var c=this.bc(),b=this.Id(),d=this.Hl();if(null!=d&&0<d.length){var e;for(e=0;e<d.length;e++)f(d[e]).hasClass(a.j.J.Am)||f(d[e]).addClass(a.j.J.Am);d=f(d[d.length-1]);e=d[0].getBoundingClientRect();c=c[0].getBoundingClientRect();b=parseInt(d.css("borderBottomWidth"),
10)+parseInt(b.css("borderBottomWidth"),10);1>=Math.abs(e.bottom+b-c.bottom)&&d.removeClass(a.j.J.Am)}}};a.j.prototype.wT=function(){var a=this.bc(),b=this.Ii(),d=this.Il(),e=this.re();null!=b&&(b.attr("style",""),d.attr("style",""));a.css("display","");e.attr("style","");this.tT()};a.j.prototype.VT=function(){var c=this.options.data,b=this.va.columnMetaData(),d=null,e=[],f=[],h,k,l,m;for(h=0;h<b.length;h++)d=!1,k=this.Hc(h),null!=k&&(0<k.width()&&(d=!0),e[h]=k.width(),f[h]=parseInt(k.css("padding-right"),
10)+parseInt(k.css("padding-left"),10),l=null,(m=k.find("."+a.j.J.Cz))&&0<m.length&&(l=m.get(0).clientHeight),null!=l&&(k=k.find("."+a.j.J.yz),k.css("min-height",l+"px")));for(h=0;h<b.length;h++)k=this.Hc(h),null!=k&&k.css("min-width",e[h]+"px"),l=this.hI(h),null!=l&&l.css("min-width",e[h]+"px");if(null!=c&&0<c.size()&&(h=this.Hl(),null!=h&&0<h.length))for(h=0;h<b.length;h++)c=this.xo(0,h,null),null!=c&&(0<c.width()&&(d=!0),l=parseInt(c.css("padding-right"),10)+parseInt(c.css("padding-left"),10),
l=l>f[h]?e[h]-l+f[h]:e[h]+f[h]-l,c.css("min-width",l+"px"));return d};a.j.J={vz:"oj-table-checkbox-acc-select-column",wz:"oj-table-checkbox-acc-select-row",bM:"oj-table-container",zA:"oj-table-scroller",uA:"oj-table",cM:"oj-table-element",vA:"oj-table-footer",wA:"oj-table-footer-row",wt:"oj-table-header",xA:"oj-table-header-row",rk:"oj-table-column-header-cell",xz:"oj-table-column-header-acc-select-column",bt:"oj-table-column-header-acc-select-row",yz:"oj-table-column-header",Cz:"oj-table-column-header-text",
rm:"oj-table-column-header-asc",op:"oj-table-column-header-dsc",Bz:"oj-table-column-header-sort-placeholder",nK:"oj-table-column-header-acc-asc-link",oK:"oj-table-column-header-acc-dsc-link",qk:"oj-table-column-header-asc-link",sm:"oj-table-column-header-dsc-link",pK:"oj-table-column-header-asc-icon",qK:"oj-table-column-header-dsc-icon",vt:"oj-table-body",Uh:"oj-table-body-row",yk:"oj-table-data-cell",Fp:"oj-table-data-cell-acc-select",AA:"oj-table-vgrid-lines",Am:"oj-table-hgrid-lines",zk:"oj-table-footer-cell",
dM:"oj-table-footer-cell-vgrid-lines",xt:"oj-table-status-message",yA:"oj-table-no-data-message",dj:"oj-component-icon",Ef:"oj-helper-hidden-accessible"};a.j.xa={Bt:"oj-component",Od:"oj-active",Zi:"oj-clickable-icon",Bb:"oj-disabled",xd:"oj-enabled",Df:"oj-focus",qp:"oj-hover",qc:"oj-selected"};a.j.Az="_hdrColRowSel";a.j.Pd="enabled";a.j.ym="disabled";a.j.Zg={wk:"single",Ap:"multiple"}});
//# sourceMappingURL=oj-modular.map