"use strict";
/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojconveyorbelt"],function(a,f){(function(){var c={cut:"ojtabscut","paste-before":"ojtabspastebefore","paste-after":"ojtabspasteafter"};a.Oa("oj.ojTabs",f.oj.baseComponent,{widgetEventPrefix:"oj",delay:300,options:{selected:0,disabledTabs:null,truncation:"auto",selectOn:"click",orientation:"horizontal",removable:!1,removeCueText:"Removable",reorderable:!1,beforeSelect:null,select:null,beforeDeselect:null,deselect:null,beforeRemove:null,remove:null,
optionChange:null},_ComponentCreate:function(){var a=this.options;this._super();this.Ay=!1;this.jG(a.orientation);this.eG(a.disabledTabs);this.UE();this.Tr();var c=a.selected;a.selected=void 0;this.Za={};this.Za.we=!1;this.Za.xe=!1;this.Za.cm=!1;this.Za.dp=!1;this.un();this.Im();this.Wb();c=this.SC(c);void 0===c&&(c=this.sn(0));a.selected=c},_init:function(){this.oC(this.options.selected)},oC:function(a){this.xn(a)&&(a=this.QC(a),a=void 0===a?void 0:this.sn(a));this.Jp(a)},_OpenContextMenu:function(a,
c){a.open(c,{launcher:this.Uf.children("[tabindex\x3d0]"),initialFocus:"menu"})},AU:function(a){var c=f(this.document[0].activeElement).closest("li"),e=this.Kb.index(c),g=!0;if(!this.qD(a)){switch(a.keyCode){case f.ui.keyCode.RIGHT:case f.ui.keyCode.DOWN:e++;break;case f.ui.keyCode.UP:case f.ui.keyCode.LEFT:g=!1;e--;break;case f.ui.keyCode.END:e=this.Kb.length-1;break;case f.ui.keyCode.HOME:e=0;break;case 46:if(c=this.oa.find(".oj-tabs-close-icon"))a.preventDefault(),this.xF({target:c,currentTarget:c,
preventDefault:f.noop});return;default:return}a.preventDefault();clearTimeout(this.eV);var h=this.Ou(e,g);a.ctrlKey||(c.attr("aria-selected","false"),this.Rk(h).attr("aria-selected","true"),this.eV=this._delay(function(){this.option("selected",h)},this.delay))}},yS:function(a){!this.qD(a)&&a.ctrlKey&&a.keyCode===f.ui.keyCode.UP&&(a.preventDefault(),this.oa.focus())},qD:function(a){var c=this.Cj(this.options.selected);if(a.ctrlKey&&a.keyCode===f.ui.keyCode.PAGE_UP)return this.Jp(this.Ou(c-1,!1)),!0;
if(a.ctrlKey&&a.keyCode===f.ui.keyCode.PAGE_DOWN)return this.Jp(this.Ou(c+1,!0)),!0},xn:function(a){return 0<=a&&a<this.Kb.length?f(this.Kb[a]).hasClass("oj-disabled"):!1},bP:function(a,c){function e(){a>f&&(a=0);0>a&&(a=f);return a}for(var f=this.Kb.length-1;this.xn(e());)a=c?a+1:a-1;return a},Ou:function(a,c){a=this.bP(a,c);this.Nq(a).focus();return this.sn(a)},QC:function(a){a=this.Cj(a);for(var c=a+1,e=this.Kb.length-1;c<=e;){if(!this.xn(c))return c;c++}for(c=a-1;0<=c;){if(!this.xn(c))return c;
c--}},_setOption:function(a,c,e){"selected"===a?(c=this.SC(c),void 0!==c&&this.Jp(c)):"disabledTabs"===a?Array.isArray(c)&&(this.eG(c),this.refresh(),this.Tr()):"removable"===a?this.iU(c):"reorderable"===a?c!==this.options.reorderable&&(this.options.reorderable=c,this.kG(),this.refresh()):"orientation"===a?(this.jG(c),this.refresh()):"truncation"===a?(this.options.truncation=c,this.refresh()):("contextMenu"===a&&(this.aq(),c&&this.un(c)),this._super(a,c,e),"selectOn"===a&&(this.ol(),this._super(a,
c),this.Nj()),"removeCueText"===a&&this.refresh())},refresh:function(){this._super();this.wO();this.UE();this.Wb()},Wb:function(){var a=this.options,c=this.element.children(".oj-tabs-selected");this.oa=c.length?this.Rk(c.attr("id")):f();this.NN();this.ol();this.Nj();this.Kb.not(this.oa).attr({"aria-selected":"false",tabIndex:"-1"});this.Jc.not(this.di(this.oa)).hide().attr({"aria-expanded":"false","aria-hidden":"true"});this.oa.length?(this.oa.addClass("oj-selected").attr({"aria-selected":"true",
tabIndex:"0"}),c.show().attr({"aria-expanded":"true","aria-hidden":"false"})):this.Nq(0).attr("tabIndex","0");void 0!==this.Kp&&(this.oC(this.Kp),this.Kp=void 0);"horizontal"==a.orientation?(this.MU(),this.wM(),void 0===this.options.selected||0==this.Cj(this.options.selected)?this.element.addClass("oj-first-child-selected"):this.element.removeClass("oj-first-child-selected")):this.element.removeClass("oj-first-child-selected");this.kG()},wM:function(){var a=this.Uf.uniqueId().attr("id");this.zi=this.dD().parent().ojConveyorBelt({orientation:"horizontal",
contentParent:"#"+a})},UE:function(){var a=this;this.UB();this.Uf=f("\x3cul\x3e").addClass("oj-tabs-nav oj-helper-clearfix").attr("role","tablist").prependTo(this.element);this.Kb=f();this.Jc=f();this.ap=f();this.element.children(":not(.oj-tabs-nav)").each(function(){var c=f(this).find("\x3e :first-child"),e=c.clone();e.addClass("oj-tabs-title").css({display:""}).attr({"aria-hidden":"false"});a.ap=a.ap.add(e);var g=e.wrap("\x3cli\x3e\x3cdiv\x3e\x3ca href\x3d'#'\x3e\x3c/a\x3e\x3c/div\x3e\x3c/li\x3e").parent();
g.addClass("oj-tabs-anchor").attr({role:"presentation",tabIndex:"-1"});var h=g.parent().addClass("oj-tabs-tab-content").parent().addClass("oj-tabs-tab").attr({role:"tab","aria-hidden":"false",tabIndex:"-1"});h.appendTo(a.Uf);a.Kb=a.Kb.add(h);var k=e[0];k.id&&a.IA(k);e.find("[id]").each(function(){a.IA(this)});c.hide().attr({"aria-hidden":"true"});c=g.uniqueId().attr("id");e=h.attr("aria-controls");k=f(this);k.hasClass("oj-disabled")&&(h.addClass("oj-disabled").attr("aria-disabled","true"),g.removeAttr("href"));
e&&h.data("oj-tabs-aria-controls",e);h.attr({"aria-controls":a.TC(k),"aria-labelledby":c});a.Jc=a.Jc.add(k);k.attr("aria-labelledby",c)});"vertical"==this.options.orientation&&(a.Uf.addClass("oj-tabs-nav-root"),window.setTimeout(function(){if(a&&a.oa){var c=0;a.Kb.addClass("oj-selected").each(function(){var a=f(this);c=Math.max(c,a.outerWidth())}).removeClass("oj-selected");a.oa.addClass("oj-selected");a.Kb.css({width:c+"px"});var e=a.Uf.outerWidth(!0),g=a.Uf.outerHeight(!0),h="rtl"==a.Ec(),k=h?a.element.css("padding-right"):
a.element.css("padding-left"),k=parseInt(k,10);h?a.Jc.css({"margin-right":e-1+k+"px","min-height":g+"px"}):a.Jc.css({"margin-left":e-1+k+"px","min-height":g+"px"})}},0));this.Jc.addClass("oj-tabs-panel").attr("role","tabpanel")},Nj:function(){var a={keydown:this.AU},c=this.options.selectOn,e=!1;if(c){var g=this;f.each(c.split(" "),function(c,d){"click"==d&&(e=!0);/^[a-zA-Z]+$/.test(d)&&(a[d]=g.eC)})}c=this.Kb.not(".oj-disabled");this._on(c,a);e||this._on(c,{click:function(a){a.preventDefault()}});
this._on(this.Jc,{keydown:this.yS});if(this.options.removable){var h={click:this.xF};this._on(c.find(".oj-tabs-close-icon"),h)}this._focusable(c);this._hoverable(c);this.Lp(c)},ol:function(){var a=this.Kb.not(".oj-disabled");this._off(a);this._off(this.Jc)},eC:function(a){var c=this.options,e=this.oa,g=f(a.currentTarget).closest("li"),h=e&&g[0]===e[0],k=this.di(g),e=e&&e.length?this.di(e):f(),l={fromTab:e,toTab:k};a.preventDefault();g.hasClass("oj-disabled")||this.Ay||h||e&&e.length&&!1===this._trigger("beforeDeselect",
a,l)||!1===this._trigger("beforeSelect",a,l)||(c.selected=this.kn(g),this.oa=g,k.addClass("oj-tabs-selected"),e.removeClass("oj-tabs-selected"),l.fromTab.length||l.toTab.length||f.error("ojTabs: Mismatching fragment identifier."),this.GU(a,l))},GU:function(b,c){var e=c.toTab,g=c.fromTab,h,k;c&&(g&&(h=g.attr("id")),e&&(k=e.attr("id")));this.Ay=!0;var l=this.Rk(h).removeClass("oj-selected");g.hide();0<g.length&&a.Components.Iy(g[0]);this.Rk(k).addClass("oj-selected");"horizontal"==this.options.orientation&&
0<this.Kb.length&&(0==this.Cj(k)?this.element.addClass("oj-first-child-selected"):this.element.removeClass("oj-first-child-selected"));e.show();0<e.length&&a.Components.Jy(e[0]);this.Ay=!1;void 0!==h&&this._trigger("deselect",b,c);this._trigger("select",b,c);this.Oc("selected",this.kn(null,g,h),this.kn(null,e,k),b?!0:!1);g.attr({"aria-expanded":"false","aria-hidden":"true"});l.attr("aria-selected","false");e.length&&g.length?l.attr("tabIndex","-1"):e.length&&this.Kb.filter(function(){return"0"===
f(this).attr("tabIndex")}).attr("tabIndex","-1");e.attr({"aria-expanded":"true","aria-hidden":"false"});this.Rk(k).attr({"aria-selected":"true",tabIndex:"0"})},Jp:function(a){void 0!==a&&(a=this.Rk(a),this.oa&&a[0]===this.oa[0]||(a=a.find(".oj-tabs-anchor")[0],this.eC({target:a,currentTarget:a,preventDefault:f.noop})))},NN:function(){if(this.options.removable&&"horizontal"==this.options.orientation){var a=this.O(this.options.removeCueText);this.Kb.not(".oj-disabled").each(function(c){var e=f(this).find("\x3e :first-child");
e.addClass("oj-removable");c="ojtabs-id_rm_"+c;f(this).attr("aria-describedby",c);f("\x3ca href\x3d'#'\x3e").addClass("oj-tabs-icon oj-component-icon oj-clickable-icon oj-tabs-close-icon").attr({id:c,tabIndex:"-1","aria-label":a,role:"presentation"}).appendTo(e)})}},wO:function(){this.Kb.find("oj-tabs-close-icon").remove()},UB:function(){this.Jr=!1;this.pn&&(a.ba.Ti(this.element[0],this.me),this.pn=!1,this.GE=void 0);this.zi?(this.zi.ojConveyorBelt("destroy"),this.zi.remove(),this.oa=this.zi=null):
this.element.children(".oj-tabs-nav").remove()},_destroy:function(){this.aq();var a=this.options.orientation;"vertical"==a?this.element.removeClass("oj-tabs oj-component oj-tabs-vertical oj-helper-clearfix"):this.element.removeClass("oj-tabs oj-component oj-tabs-horizontal oj-first-child-selected");this.ol();this.UB();this.Jc.each(function(){f(this).removeAttr("tabIndex").removeAttr("aria-expanded").removeAttr("aria-selected").removeAttr("aria-labelledby").removeAttr("aria-hidden").removeAttr("role").removeClass("oj-active oj-disabled oj-tabs-selected oj-tabs-gid oj-tabs-panel").removeUniqueId().css("display",
"");"vertical"==a&&f(this).css("margin-left","").css("min-height","");f(this).find("\x3e :first-child").css("display","").removeAttr("aria-hidden")})},iU:function(a){a!==this.options.removable&&(this.options.removable=a,this.refresh())},xF:function(a){var c=f(a.currentTarget).closest("li"),e=this.di(c),g={tab:e};if(c&&!1!==this._trigger("beforeRemove",a,g)){if(c.hasClass("oj-selected")){var h=this.QC(e.attr("id"));void 0===h?this.oa=this.options.selected=void 0:(this.options.selected=this.kn(this.Kb[h]),
this.Kp=this.sn(h))}e.remove();c.remove();this.Tr();this.refresh();this.oa&&this.oa.focus();this._trigger("remove",a,g)}},addTab:function(a){this.element.append(a);this.element.children(".oj-tabs-selected").length||(this.Kp=this.TC(a));this.refresh();this.Kb.last()[0].scrollIntoView(!1)},kG:function(){if(this.options.reorderable&&this.options.disabledTabs.length!==this.Kb.length){var a=this;this.Uf.sortable({axis:"horizontal"==a.options.orientation?"x":"y",stop:function(c,e){var f=e.item;a.bC(f,f.prev())}})}else this.Uf.sortable({disabled:!0})},
jG:function(a){a||(a=this.options.orientation);if("horizontal"==a)"vertical"==this.options.orientation&&this.Jc&&(this.element.removeClass("oj-tabs-vertical oj-helper-clearfix"),this.Jc.each(function(){f(this).css("margin-left","").css("min-height","")})),this.element.addClass("oj-tabs oj-component oj-tabs-horizontal");else if("vertical"==a)"horizontal"==this.options.orientation&&this.Jc&&this.element.removeClass("oj-tabs-horizontal"),this.element.addClass("oj-tabs oj-component oj-tabs-vertical oj-helper-clearfix");
else return;this.options.orientation=a},NT:function(a){return a?a.replace(/[!"$%&'()*+,.\/:;<=>?@\[\]\^`{|}~]/g,"\\$\x26"):""},di:function(a){a=f(a).attr("aria-controls");return this.element.find(this.NT("#"+a))},Nq:function(a){return this.Kb.eq(a)},dD:function(){var a=this.Uf.parent();a.hasClass("oj-tabs-conveyor")||(a=this.Uf.wrap("\x3cdiv\x3e").parent().addClass("oj-tabs-conveyor"),a.wrap("\x3cdiv\x3e").parent().addClass("oj-tabs-nav-root").uniqueId().attr("id"));return a},IA:function(a){0>a.id.indexOf("ojtabs-id_")&&
f(a).attr("id","ojtabs-id_"+a.id)},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;var c=a.subId;a=a.index;if("oj-conveyorbelt"!=c&&("number"!==typeof a||0>a||a>=this.Jc.length))return null;switch(c){case "oj-conveyorbelt":return this.zi?this.zi[0]:null;case "oj-tabs-panel":return this.Jc[a];case "oj-tabs-tab":return this.Kb[a];case "oj-tabs-title":return this.ap[a];case "oj-tabs-close-icon":return this.Nq(a).find("."+c)[0]}return null},eD:function(){return this.element[0].clientWidth},
UD:function(){return this.GE>this.eD()},zY:function(){return this.Jr},dG:function(a){this.Jr=a},gQ:function(){var a=Math.floor(this.eD()/this.Kb.length);this.options.removable&&(a-=28);return a},UA:function(){if(!this.Jr){var a=this.gQ();this.ap.each(function(){f(this).css("max-width",""+a+"px").addClass("oj-tabs-title-overflow")});this.dG(!0)}},vT:function(){this.Jr&&(this.ap.each(function(){f(this).css("max-width","").removeClass("oj-tabs-title-overflow")}),this.dG(!1))},DY:function(){},He:function(){this.UD()?
this.UA():this.vT()},FR:function(){return"auto"==this.options.truncation||"progressive"==this.options.truncation},MU:function(){"horizontal"==this.options.orientation&&0<this.Kb.length&&this.FR()&&(null==this.me&&(this.me=this.He.bind(this)),a.ba.ug(this.element[0],this.me),this.pn=!0,this.GE=this.dD()[0].scrollWidth,this.UD()&&this.UA())},Oc:function(a,c,e,f){this._trigger("optionChange",f,{option:a,previousValue:c,value:e,optionMetadata:{writeback:f?"shouldWrite":"shouldNotWrite"}})},sh:function(a,
c){this.Za.tab="keydown"===a.originalEvent.originalEvent.type?this.oa:f(a.originalEvent.target).closest("li");this.Za.iZ=this.Za.tab.attr("id");c.openOptions.position={my:"start top",at:"start bottom",of:this.Za.tab[0]};if(this.Za.we&&(this.Za.cm||this.Za.dp)){var e=!this.Za.gs;this.Za.cm.hasClass("oj-disabled")!=e&&(e?(this.Za.cm.addClass("oj-disabled"),this.Za.dp.addClass("oj-disabled")):(this.Za.cm.removeClass("oj-disabled"),this.Za.dp.removeClass("oj-disabled")),this.Za.xe.ojMenu("refresh"))}},
dh:function(a){var d=c[a];a='\x3ca href\x3d"#"\x3e'+this.O(a)+"\x3c/a\x3e";return f("\x3cli id\x3d"+d+"\x3e"+a+"\x3c/li\x3e")},eS:function(a){if(!a||!a.length)return!1;this.Za.gs=a},oE:function(a,c){if(!a||!a.length||!this.Za.gs)return!1;var e=this.Za.gs;this.Za.gs=!1;this.bC(e,a,c)},th:function(a,c){var e=c?c.item.attr("id"):void 0;"ojtabscut"===e?this.eS(this.Za.tab):"ojtabspastebefore"===e?this.oE(this.Za.tab,!0):"ojtabspasteafter"===e&&this.oE(this.Za.tab,!1)},un:function(a){var c,e;a||this.options.contextMenu||
(c=this.element.attr("contextmenu"))&&(this.options.contextMenu="#"+c);if(a||this.options.contextMenu){c=a||this.options.contextMenu;e=f.type(c);if("function"==e){try{c=c()}catch(g){c=null}e=f.type(c)}if("string"===e){if(c=f(c)){c.css("display","none");e=this.Za;if(!e)return;e.xe=c;e.we=!0}this.Za.we&&a&&this.Im()}}},Im:function(){if(this.Za&&this.Za.we&&this.options.reorderable){var a=this.Za.xe,c=this;a.on("ojselect",f.proxy(this.th,this));a.on("ojbeforeopen",f.proxy(this.sh,this));var e=!1;a.find("[data-oj-command]").each(function(){if(0===
f(this).children("a").length){var a=f(this).attr("data-oj-command").slice(8);f(this).replaceWith(c.dh(a));f(this).addClass("oj-menu-item");e=!0}});e&&a.ojMenu("refresh");this.Za.cm=a.find("#ojtabspastebefore");this.Za.dp=a.find("#ojtabspasteafter")}},aq:function(){var a=this.Za;a&&a.we&&(a.we=!1,a.xe.off("ojselect"),a.xe.off("ojbeforeopen"),a.xe=null)},bC:function(a,c,e){this.xn(this.Kb.index(a))||(a=this.di(a),c.length?e?this.di(c).before(a):this.di(c).after(a):0<this.Jc.length&&this.Jc.first().before(a),
this.Tr(),this.refresh())},TC:function(a){var c=a.attr("id");c||(c=a.uniqueId().attr("id"),a.addClass("oj-tabs-gid"));return c},Rk:function(a){return this.Nq(this.Cj(a))},SC:function(a){if("number"===typeof a){if(0<=a&&a<this.Jc.length)return this.sn(a)}else if("string"===typeof a&&-1!=this.Cj(a))return a},sn:function(a){return this.Jc.eq(a).attr("id")},Cj:function(a){return"number"===typeof a?a:this.Jc.index(f("#"+a))},kn:function(a,c,e){if(a||c)return a&&(c=this.di(a),e=c.attr("id")),c.hasClass("oj-tabs-gid")?
this.Cj(e):e},eG:function(a){this.element.children().removeClass("oj-disabled");this.Kb&&f(this.Kb).removeClass("oj-disabled");if(a&&0<a.length)for(var c=this.element.children(),e=this.zi?c.index(this.zi)+1:0,g,h=0;h<a.length;h++)g=a[h],"number"===typeof g&&0<=g&&e+g<c.length?f(c[e+g]).addClass("oj-disabled"):"string"===typeof g&&this.element.find("#"+g).addClass("oj-disabled")},Tr:function(){var a=[],c=this;this.Uf.children(".oj-disabled").each(function(){a.push(c.kn(f(this)))});this.options.disabledTabs=
a}})})()});
//# sourceMappingURL=oj-modular.map