/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojmodel","ojs/ojdatacollection-common","ojs/ojtable"],function(a,f){a.qb=function(c,b){a.qb._init(this,c,b,null)};o_("ModelRow",a.qb,a);a.b.sa(a.qb,a.bb,"ModelRow.ModelRow");a.qb.prototype.Init=function(){a.bb.t.Init.call(this)};a.qb.prototype.attributes={};a.b.g("ModelRow.prototype.attributes",{attributes:a.qb.prototype.attributes});a.qb.prototype.id=null;a.b.g("ModelRow.prototype.id",{id:a.qb.prototype.id});a.qb.prototype.Se=null;a.b.g("ModelRow.prototype.idAttribute",
{Se:a.qb.prototype.Se});a.qb._init=function(a,b,d,e){var f=null;a.Init();a.Hj=b;a.id=b.id;a.Se=b.Se;a.attributes=b.attributes;a.index=b.index;d=d||{};for(f in e)e.hasOwnProperty(f)&&(a[f]=e[f]);a.context=d.context};a.qb.prototype.clone=function(){return this.Hj.clone()};a.b.g("ModelRow.prototype.clone",{clone:a.qb.prototype.clone});a.qb.prototype.get=function(a){return this.Hj.get(a)};a.b.g("ModelRow.prototype.get",{get:a.qb.prototype.get});a.qb.prototype.Px=function(){return this.Hj};a.b.g("ModelRow.prototype.getModel",
{Px:a.qb.prototype.Px});a.qb.prototype.set=function(a,b,d){return this.Hj.set(a,b,d)};a.b.g("ModelRow.prototype.set",{set:a.qb.prototype.set});a.qb.prototype.keys=function(){return this.Hj.keys()};a.b.g("ModelRow.prototype.keys",{keys:a.qb.prototype.keys});a.qb.prototype.values=function(){return this.Hj.values()};a.b.g("ModelRow.prototype.values",{values:a.qb.prototype.values});a.qb.prototype.pairs=function(){return this.Hj.pairs()};a.b.g("ModelRow.prototype.pairs",{pairs:a.qb.prototype.pairs});a.Ba=
function(c,b){a.Ba._init(this,c,b,null)};o_("CollectionRowSet",a.Ba,a);a.Ba.prototype.lf=null;a.b.g("CollectionRowSet.prototype.comparator",{lf:a.Ba.prototype.lf});a.Ba.prototype.Wl=null;a.b.g("CollectionRowSet.prototype.sortDirection",{Wl:a.Ba.prototype.Wl});a.Ba.prototype.Tf=!0;a.b.g("CollectionRowSet.prototype.sortSupported",{Tf:a.Ba.prototype.Tf});a.b.sa(a.Ba,a.Q,"CollectionRowSet.CollectionRowSet");a.Ba.prototype.Init=function(){a.Ba.t.Init.call(this)};a.Ba._init=function(a,b,d,e){var f;a.ib=
[];a.C=0;a.Init();if(e)for(f in e)e.hasOwnProperty(f)&&(a[f]=e[f]);a.Ib=b;a.tM()};a.Ba.prototype.at=function(c,b){var d=this.Ib.at(c,b);return null!=d?d instanceof a.q?new a.qb(d):a.b.ha(function(b){d.then(function(c){b(new a.qb(c))})}):null};a.b.g("CollectionRowSet.prototype.at",{at:a.Ba.prototype.at});a.Ba.prototype.fetch=function(a){if(this.oN.call(this)){this.Vw.call(this);a=a||{};var b=this,d=null!=a.startIndex?!0:!1;this.C=d?a.startIndex:0;this.Sv=!0;var e=0<a.pageSize?a.pageSize:-1;a.pageSize=
e;a.startIndex=this.C;a.refresh=!0;d?this.Ib.Js(this.C,e).then(function(){b.If.call(b,a,null)}):this.Ib.fetch({success:function(d){b.Ib=d;b.If.call(b,a,null)},error:function(d,e){b.Ib=d;b.If.call(b,a,e)}})}};a.b.g("CollectionRowSet.prototype.fetch",{fetch:a.Ba.prototype.fetch});a.Ba.prototype.get=function(c,b){return new a.qb(this.Ib.get(c,b))};a.b.g("CollectionRowSet.prototype.get",{get:a.Ba.prototype.get});a.Ba.prototype.getCollection=function(){return this.Ib};a.b.g("CollectionRowSet.prototype.getCollection",
{getCollection:a.Ba.prototype.getCollection});a.Ba.prototype.hasMore=function(){return this.Ib.hasMore};a.b.g("CollectionRowSet.prototype.hasMore",{hasMore:a.Ba.prototype.hasMore});a.Ba.prototype.indexOf=function(a,b){return this.Ib.indexOf(a.Px(),b)};a.b.g("CollectionRowSet.prototype.indexOf",{indexOf:a.Ba.prototype.indexOf});a.Ba.prototype.isEmpty=function(){return this.Ib.isEmpty()};a.b.g("CollectionRowSet.prototype.isEmpty",{isEmpty:a.Ba.prototype.isEmpty});a.Ba.prototype.size=function(){var a=
this.Ib.size();return this.Sv||this.Ib.ay(0,a)?a:0};a.b.g("CollectionRowSet.prototype.size",{size:a.Ba.prototype.size});a.Ba.prototype.sort=function(){this.comparator&&(this.Ib.comparator=this.comparator);this.sortDirection&&(this.Ib.sortDirection="ascending"===this.sortDirection?1:-1);return this.Ib.sort(null)};a.b.g("CollectionRowSet.prototype.sort",{sort:a.Ba.prototype.sort});a.Ba.prototype.totalSize=function(){return this.Ib.totalResults};a.b.g("CollectionRowSet.prototype.totalSize",{totalSize:a.Ba.prototype.totalSize});
a.Ba.prototype.eK=function(a){if(null==a)this.comparator=null,this.Ib.comparator=null;else{var b=a.key;a=a.direction;var d=null;this.Ib.ab()?(this.comparator=b,this.sortDirection=a):("ascending"==a?d=function(a){return f.isFunction(a.get)?a.get(b):a[b]()}:"descending"==a&&(d=function(a,c){var d,k;f.isFunction(a.get)?(d=a.get(b),k=c.get(b)):(d=a[b](),k=c[b]());return d===k?0:d>k?-1:1}),this.comparator=d)}};a.Ba.prototype.tM=function(){var c=this;this.Ib.on(a.X.v.SYNC,function(b){a.Ba.t.ac.call(c,a.Q.v.SYNC,
b)});this.Ib.on(a.X.v.ADD,function(b){a.Ba.t.ac.call(c,a.Q.v.ADD,new a.qb(b))});this.Ib.on(a.X.v.REMOVE,function(b){a.Ba.t.ac.call(c,a.Q.v.REMOVE,new a.qb(b))});this.Ib.on(a.X.v.RESET,function(b){a.Ba.t.ac.call(c,a.Q.v.RESET,b)});this.Ib.on(a.X.v.SORT,function(b,d){null!=d&&d.add||a.Ba.t.ac.call(c,a.Q.v.SORT,b)});this.Ib.on(a.X.v.CHANGE,function(b){a.Ba.t.ac.call(c,a.Q.v.CHANGE,new a.qb(b))});this.Ib.on(a.X.v.DESTROY,function(b){a.Ba.t.ac.call(c,a.Q.v.REMOVE,b)});this.Ib.on(a.X.v.REFRESH,function(b){a.Ba.t.ac.call(c,
a.Q.v.REFRESH,b)});this.Ib.on(a.X.v.ERROR,function(b){a.Ba.t.ac.call(c,a.Q.v.ERROR,b);c.If.call(c,null,null)})};a.Ba.prototype.oN=function(){return!this.MD};a.Ba.prototype.Vw=function(){this.MD=!0;a.Ba.t.ac.call(this,a.Q.v.REQUEST,null)};a.Ba.prototype.If=function(c,b){c=c||{};var d=c.success,e=c.error;this.MD=!1;null!=b?(a.Ba.t.ac.call(this,a.Q.v.ERROR,b),e&&e.call(this,c,b)):(a.Ba.t.ac.call(this,a.Q.v.SYNC,c),d&&d.call(this,c))};a.Zb=function(c,b){this.data={};if(!(c instanceof a.l))throw Error(a.N.xc._ERR_DATA_INVALID_TYPE_SUMMARY+
"\n"+a.N.xc._ERR_DATA_INVALID_TYPE_DETAIL);a.Zb.t.constructor.call(this,c,b);this.aa=new a.Ba(c,this.options);this.Gm();this.Init();if(null!=b&&("enabled"==b.startFetch||null==b.startFetch)||null==b)this.Xn=!0};o_("CollectionTableDataSource",a.Zb,a);a.b.sa(a.Zb,a.N,"oj.CollectionTableDataSource");a.Zb.prototype.Init=function(){a.Zb.t.Init.call(this)};a.b.g("CollectionTableDataSource.prototype.Init",{Init:a.Zb.prototype.Init});a.Zb.prototype.at=function(a){return this.aa.at(a)};a.b.g("CollectionTableDataSource.prototype.at",
{at:a.Zb.prototype.at});a.Zb.prototype.fetch=function(c){c=c||{};var b=this,d=c.success,e=c.error,f=null==c.context?this:c.context;if("init"==c.fetchType&&!this.Xn)return a.b.ha(function(a){a()});null!=c.startIndex&&a.Zb.t.startIndex.call(this,c.startIndex);return a.b.ha(function(a,k){c.success=function(){null!=d&&d.call(f,b,c);a()};c.error=function(a,c){null!=e&&e.call(f,b,a,c);k()};"enabled"==c.startFetch?(b.aa.isEmpty()||"undefined"===typeof b.aa.size())&&b.aa.fetch(c):b.aa.fetch(c)})};a.b.g("CollectionTableDataSource.prototype.fetch",
{fetch:a.Zb.prototype.fetch});a.Zb.prototype.get=function(a){return this.aa.get(a)};a.b.g("CollectionTableDataSource.prototype.get",{get:a.Zb.prototype.get});a.Zb.prototype.hasMore=function(){return null!=this.aa?this.aa.hasMore():!1};a.b.g("CollectionTableDataSource.prototype.hasMore",{hasMore:a.Zb.prototype.hasMore});a.Zb.prototype.indexOf=function(a){return this.aa.indexOf(a)};a.b.g("CollectionTableDataSource.prototype.indexOf",{indexOf:a.Zb.prototype.indexOf});a.Zb.prototype.size=function(){return this.aa.size()};
a.b.g("CollectionTableDataSource.prototype.size",{size:a.Zb.prototype.size});a.Zb.prototype.sort=function(c){this.aa.eK(c);if(null==c)return a.b.ha(function(a){a()});var b=this;return a.b.ha(function(a){b.aa.sort();a()})};a.b.g("CollectionTableDataSource.prototype.sort",{sort:a.Zb.prototype.sort});a.Zb.prototype.totalSize=function(){return this.aa.totalSize()};a.b.g("CollectionTableDataSource.prototype.totalSize",{totalSize:a.Zb.prototype.totalSize});a.Zb.prototype.Gm=function(){var c=this;this.aa.on(a.Q.v.ADD,
function(b){c.Rc=!1;a.N.t.handleEvent.call(c,a.N.v.ADD,b)});this.aa.on(a.Q.v.REMOVE,function(b){c.Rc=!1;a.N.t.handleEvent.call(c,a.N.v.REMOVE,b)});this.aa.on(a.Q.v.REQUEST,function(b){c.Rc=!0;a.N.t.handleEvent.call(c,a.N.v.REQUEST,b)});this.aa.on(a.Q.v.RESET,function(b){c.Rc=!1;a.N.t.handleEvent.call(c,a.N.v.RESET,b)});this.aa.on(a.Q.v.REFRESH,function(b){c.Rc=!1;a.N.t.handleEvent.call(c,a.N.v.REFRESH,b)});this.aa.on(a.Q.v.SORT,function(b){c.Rc=!1;a.N.t.handleEvent.call(c,a.N.v.SORT,b)});this.aa.on(a.Q.v.CHANGE,
function(b){c.Rc=!1;a.N.t.handleEvent.call(c,a.N.v.CHANGE,b)});this.aa.on(a.Q.v.SYNC,function(b){c.Rc=!1;a.N.t.handleEvent.call(c,a.N.v.SYNC,b)});this.aa.on(a.Q.v.ERROR,function(b){c.Rc=!1;a.N.t.handleEvent.call(c,a.N.v.ERROR,b)})}});
//# sourceMappingURL=oj-modular.map