"use strict";
/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojdvt-base","ojs/internal-deps/dvt/DvtThematicMap"],function(a,f){a.Oa("oj.ojThematicMap",f.oj.dvtBaseComponent,{version:"1.0.0",widgetEventPrefix:"oj",options:{select:null,load:null},Wn:{},cw:[],Lm:[],yU:"ar cs da de el es fi fr hu it iw ja ko nl no pl pt pt_BR ro ru sk sv th tr zh_CN zh_TW".split(" "),Cf:function(a,b,d){return DvtThematicMap.newInstance(a,b,d)},ef:function(){var a=this._super();a.push("oj-thematicmap");return a},aj:function(){var a=
this._super();a["oj-dvtbase oj-thematicmap"]={path:"animationDuration",property:"animation-duration"};a["oj-thematicmap-arealayer"]=[{path:"styleDefaults/areaStyle",property:"CSS_BACKGROUND_PROPERTIES"},{path:"styleDefaults/labelStyle",property:"CSS_TEXT_PROPERTIES"}];a["oj-thematicmap-area"]={path:"styleDefaults/dataAreaDefaults/borderColor",property:"border-top-color"};a["oj-thematicmap-area oj-hover"]={path:"styleDefaults/dataAreaDefaults/hoverColor",property:"border-top-color"};a["oj-thematicmap-area oj-selected"]=
[{path:"styleDefaults/dataAreaDefaults/selectedInnerColor",property:"border-top-color"},{path:"styleDefaults/dataAreaDefaults/selectedOuterColor",property:"border-bottom-color"}];a["oj-thematicmap-marker"]=[{path:"styleDefaults/dataMarkerDefaults/labelStyle",property:"CSS_TEXT_PROPERTIES"},{path:"styleDefaults/dataMarkerDefaults/color",property:"background-color"},{path:"styleDefaults/dataMarkerDefaults/opacity",property:"opacity"},{path:"styleDefaults/dataMarkerDefaults/borderStyle",property:"border-style"},
{path:"styleDefaults/dataMarkerDefaults/borderColor",property:"border-top-color"},{path:"styleDefaults/dataMarkerDefaults/borderWidth",property:"border-width"}];return a},bj:function(){return["load","select"]},hg:function(){this.SR();for(var a=0;a<this.Lm.length;a++)if(!this.cw[this.Lm[a]])return;this.Lm=[];this._super();this._trigger("load",null,null)},SR:function(){var c=this.options.basemap;if(c){var b=a.ia.qe(),c=c.charAt(0).toUpperCase()+c.slice(1),d=this.options.areaLayers;if(d)for(var e=0;e<
d.length;e++){var f=d[e].layer;f&&(f=f.charAt(0).toUpperCase()+f.slice(1),this.bE(c,f,b))}(d=this.options.pointDataLayers)&&0<d.length&&this.bE(c,"Cities",b)}},eE:function(c){if(!this.cw[c]){var b=a.ia.jb(c),d=this,e=this.cw;f.getScript(b,function(){e[c]=!0;d.hg()})}},bE:function(a,b,d){var e="resources/internal-deps/dvt/thematicMap/basemaps/DvtBaseMap"+a+b+".js";this.Lm.push(e);if(-1===d.indexOf("en")){var f=d.split("_");d=[];for(var h=0;h<f.length;h++){for(var k="",l=0;l<h+1;l++)0!=l&&(k+="_"),
k+=f[l];d.push(k)}a="resources/internal-deps/dvt/thematicMap/resourceBundles/"+a+b+"Bundle";for(b=d.length-1;0<=b;b++)if(-1!==this.yU.indexOf(d[b])){d=a+"_"+d[b]+".js";this.Lm.push(d);this.eE(d);break}}this.eE(e)},cj:function(a){var b,d,e;if((a&&a.getType?a.getType():null)===DvtSelectionEvent.TYPE){b=[];d=a.getSelection();var f=a.getParamValue("clientId");for(a=0;a<d.length;a++)e={id:d[a],dataLayerId:f},b.push(e),this.Wn[f]=d;this.WU();this._trigger("select",null,{items:b})}else this._super(a)},WU:function(){var a=
this.options.pointDataLayers;if(a)for(var b=0;b<a.length;b++)this.Wn[a[b].id]&&(a[b].selectedItems=this.Wn[a[b].id]);a=this.options.areaLayers;for(b=0;b<a.length;b++){var d=a[b].areaDataLayer;this.Wn[d.id]&&(d.selectedItems=this.Wn[d.id])}},getNodeBySubId:function(a){return this._super(a)},getSubIdByNode:function(a){return this._super(a)},getArea:function(c,b){var d=this.Va.getAutomation();return new a.eg(d.getData(c,"area",b))},getMarker:function(c,b){var d=this.Va.getAutomation();return new a.fg(d.getData(c,
"marker",b))}});a.fg=function(a){this.f=a};o_("ThematicMapMarker",a.fg,a);a.fg.prototype.od=function(){return this.f?this.f.color:null};a.b.g("ThematicMapMarker.prototype.getColor",{od:a.fg.prototype.od});a.fg.prototype.te=function(){return this.f?this.f.tooltip:null};a.b.g("ThematicMapMarker.prototype.getTooltip",{te:a.fg.prototype.te});a.fg.prototype.pe=function(){return this.f?this.f.label:null};a.b.g("ThematicMapMarker.prototype.getLabel",{pe:a.fg.prototype.pe});a.fg.prototype.isSelected=function(){return this.f?
this.f.isSelected:!1};a.b.g("ThematicMapMarker.prototype.isSelected",{isSelected:a.fg.prototype.isSelected});a.eg=function(a){this.f=a};o_("ThematicMapArea",a.eg,a);a.eg.prototype.od=function(){return this.f?this.f.color:null};a.b.g("ThematicMapArea.prototype.getColor",{od:a.eg.prototype.od});a.eg.prototype.te=function(){return this.f?this.f.tooltip:null};a.b.g("ThematicMapArea.prototype.getTooltip",{te:a.eg.prototype.te});a.eg.prototype.pe=function(){return this.f?this.f.label:null};a.b.g("ThematicMapArea.prototype.getLabel",
{pe:a.eg.prototype.pe});a.eg.prototype.isSelected=function(){return this.f?this.f.isSelected:!1};a.b.g("ThematicMapArea.prototype.isSelected",{isSelected:a.eg.prototype.isSelected})});
//# sourceMappingURL=oj-modular.map