/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(a,f){(function(){function c(a,c){var e=a.name,g=a.form;e?(e=e.replace(/'/g,"\\'"),e=":radio[name\x3d'"+e+"']:oj-button",g=c?c.filter(e):g?f(g).find(e):f(e,a.ownerDocument).filter(function(){return!this.form})):g=(c?c.filter(a):f(a)).filter(":oj-button");return g}a.Oa("oj.ojToolbar",f.oj.baseComponent,{widgetEventPrefix:"oj",options:{disabled:null},_create:function(){this.element.addClass("oj-toolbar oj-component").attr("role","toolbar");
null!==this.options.disabled&&a.D.warn("Caller attempted to set the 'disabled' option on Toolbar, but Toolbar does not support the 'disabled' option.  See API doc.");this.sb(!0);this._super()},_OpenContextMenu:function(a,c){a.open(c,{launcher:this.element.find(":oj-button[tabindex\x3d0]"),initialFocus:"menu"})},_setOption:function(b,c){"disabled"===b?a.D.warn("Caller attempted to set the 'disabled' option on Toolbar, but Toolbar does not support the 'disabled' option.  See API doc.  Ignoring the call."):
this._superApply(arguments)},refresh:function(){this._super();this.sb(!1)},sb:function(a){var c=this;this.Eg="rtl"===this.Ec();this.Wc=this.element.find(":oj-button").unbind("keydown"+this.eventNamespace).bind("keydown"+this.eventNamespace,function(a){c.Jv(a,f(this))}).unbind("click"+this.eventNamespace).bind("click"+this.eventNamespace,function(){f(this).ojButton("option","disabled")||c.Mj(f(this))}).unbind("focus"+this.eventNamespace).bind("focus"+this.eventNamespace,function(){c.Mj(f(this))});
this.Qg=this.Wc.filter(function(){return!f(this).ojButton("option","disabled")});this.Tv(a)},Tv:function(a){var c=f(this.Gj);this.Gj=void 0;this.Wc.attr("tabindex","-1");a=a||!c.is(this.Qg)?this.Qg.first():c;this.Mj(a)},gw:function(a){var d=this.Qg;return a.map(function(a,b){if("radio"!=b.type||b.checked||""==b.name)return b;var f=c(b,d).filter(":checked");return f.length?f[0]:b})},Mj:function(a){a=this.gw(a);var c=a[0],e=this.Gj;c!==e&&(f(e).attr("tabindex","-1"),a.attr("tabindex","0"),this.Gj=c)},
Jv:function(a,c){switch(a.which){case f.ui.keyCode.LEFT:case f.ui.keyCode.RIGHT:a.preventDefault();var e=this.Qg,g=e.length;if(2>g)break;var h=e.index(c);e.eq((h+(a.which==f.ui.keyCode.RIGHT^this.Eg?1:-1)+g)%g).focus();break;case f.ui.keyCode.UP:case f.ui.keyCode.DOWN:"radio"==c.attr("type")&&a.preventDefault()}},_destroy:function(){this.element.removeClass("oj-toolbar oj-component").removeAttr("role");this.Wc.attr("tabindex","0")}})})()});
//# sourceMappingURL=oj-modular.map