define(["ojs/ojcore","jquery","ojs/ojdatacollection-common","ojs/ojmodel"],function(a){a.ya=function(f){f=f||{};this.Xo=f.root;this.zV=f.childCollectionCallback;this.Pl=f.parseMetadata;this.fk=null;this.Xl="none";this.Bc={};a.ya.t.constructor.call(this)};o_("CollectionTreeDataSource",a.ya,a);a.ya.prototype.Pl=function(a){return{key:a.idAttribute+"\x3d"+a.id}};a.b.sa(a.ya,a.mc,"oj.CollectionTreeDataSource");a.ya.prototype.Init=function(){a.ya.t.Init.call(this)};a.b.g("CollectionTreeDataSource.prototype.Init",
{Init:a.ya.prototype.Init});a.ya.prototype.Yd=function(a){var c=this.Bc[a];if(c&&0<c.length)return c.length;this.Jx(a,{success:function(a){return a.length}});return-1};a.b.g("CollectionTreeDataSource.prototype.getChildCount",{Yd:a.ya.prototype.Yd});a.ya.prototype.Jx=function(a,c){this.Wd(a,null,{success:function(a){c.success(a.pa)},error:c.error})};a.b.g("CollectionTreeDataSource.prototype.getChildCollection",{Jx:a.ya.prototype.Jx});a.ya.prototype.Wd=function(a,c,b){c=c||{};var d=c.start?c.start:
0,e=c.count?c.count:-1;if(null===a)this.em(null,d,e,b,null);else{var g=this;this.jv(this.Xo,a,0).then(function(c){c?(c=g.gp(c.Ro),g.em(c,d,e,b,a)):b&&b.error&&b.error(a)})}};a.b.g("CollectionTreeDataSource.prototype.fetchChildren",{Wd:a.ya.prototype.Wd});a.ya.prototype.UJ=function(a,c,b){var d=0;b&&b.at&&(d=b.at);a=this.gq(this,"insert",d,this.Kq(c),this.YE(a));this.handleEvent("change",a)};a.ya.prototype.VJ=function(a,c,b){var d=0;b&&b.index&&(d=b.index);this.nT(a);a=this.gq(this,"delete",d,this.Kq(c),
null);this.handleEvent("change",a)};a.ya.prototype.WJ=function(a){var c=this.mP(a),b=null,d=null;c&&(b=c.index,d=this.Kq(c.pa));a=this.gq(this,"update",b,d,this.YE(a));this.handleEvent("change",a)};a.ya.prototype.GJ=function(a){a=this.gq(this,"refresh",null,this.Kq(a),null);this.handleEvent("change",a)};a.ya.prototype.YE=function(f){var c=[];c.push(f.attributes);var b={};b.idAttribute=f.idAttribute;f=new a.$(c,b);f.fetch();return f};a.ya.prototype.Kq=function(f){var c=[],b=null;do b=this.VP(f),null!==
b&&(b!==a.ya.iz&&c.unshift(b),f=this.nP(b));while(null!=b);return c};a.ya.iz="%!@ROOT%#@!";a.ya.prototype.Aq=function(f){var c=f instanceof a.q?this.Pl(f).key:f;return f?c:a.ya.iz};a.ya.prototype.EA=function(a){return this.Bc[this.Aq(a)]};a.ya.prototype.WF=function(f,c){c.on(a.X.v.ADD,this.UJ,this);c.on(a.X.v.REMOVE,this.VJ,this);c.on(a.X.v.CHANGE,this.WJ,this);c.on(a.X.v.SYNC,this.GJ,this);this.Bc[this.Aq(f)]=c};a.ya.prototype.nT=function(a){a=this.Aq(a);for(var c in this.Bc)if(this.Bc.hasOwnProperty(c)&&
c===a){this.Bc[a].off(null,null,this);delete this.Bc[a];break}};a.ya.prototype.QR=function(a,c){for(var b=c.length,d=0;d<b;d++){var e=this.Aq(c.at(d));if(a===e)return!0}return!1};a.ya.prototype.mP=function(a){for(var c in this.Bc)if(this.Bc.hasOwnProperty(c))for(var b=this.Bc[c],d=0;d<b.length;d++)if(b.at(d)===a)return{index:d,pa:b};return null};a.ya.prototype.nP=function(a){for(var c in this.Bc)if(this.Bc.hasOwnProperty(c)){var b=this.Bc[c];if(this.QR(a,b))return b}return null};a.ya.prototype.VP=
function(a){for(var c in this.Bc)if(this.Bc.hasOwnProperty(c)&&this.Bc[c]===a)return c;return null};a.ya.prototype.gp=function(a){var c=!0,b=this.EA(a);b||(c=!1,b=this.zV(this.Xo,a),null!=b&&(this.TA(b),this.WF(a,b)));return{pa:b,sx:c}};a.ya.prototype.gq=function(a,c,b,d,e){return{source:a,operation:c,index:b,parent:d,data:e}};a.ya.prototype.em=function(a,c,b,d,e){var g=this;null===a&&((a=this.EA(null))?a={pa:a,sx:!0}:(a={pa:g.Xo,sx:!1},g.WF(null,this.Xo)));a&&g.gC(a,function(a){d.success&&d.success(g.NP(a,
e,c,b))},d.error)};a.ya.prototype.NP=function(f,c,b,d){return new a.Lc(c,f,this,b,d)};a.ya.prototype.QT=function(f,c){var b=this;return a.b.ha(function(a){function e(c,f,k){c<f.length?f.at(c,{deferred:!0}).then(function(l){if(l){var m=b.Pl(l);if(k===m.key){a(l);return}}c++;e(c,f,k)}):a(null)}e(0,f,c)})};a.ya.prototype.jv=function(f,c,b){var d=this;return a.b.ha(function(a){d.QT(f,c).then(function(g){function h(d,g){if(d<k){var n=g.gp(f.at(d));n.pa?g.gC(n,function(f){g.jv(f,c,b+1).then(function(b){b?
a(b):(d++,h(d,g))})},null):(d++,h(d,g))}else a(null)}if(g)a({Ro:g,depth:b});else{var k=f.length;h(0,d)}})})};a.ya.prototype.gC=function(a,c,b){a.sx?c(a.pa):(this.fk&&"none"!==this.fk&&(a.pa.lf=this.fk,a.pa.Wl=this.Xl),0<a.pa.length?c(a.pa):a.pa.fetch({success:function(a){c(a)},error:b}))};a.ya.prototype.Dh=function(a,c){var b=this;null===a?this.em(null,0,-1,{success:function(a){a.Xy({success:function(){c.success&&c.success(a)}})}},null):this.jv(this.Xo,a,0).then(function(d){d&&(d=b.gp(d.Ro),b.em(d,
0,-1,{success:function(a){a.Xy({success:function(){c.success&&c.success(a)}})}},a))})};a.b.g("CollectionTreeDataSource.prototype.fetchDescendants",{Dh:a.ya.prototype.Dh});a.ya.prototype.sort=function(a,c){var b=a.key,d=a.direction,e=!1;b!==this.fk&&(this.fk=b,e=!0);d!==this.Xl&&(this.Xl=d,e=!0);if(e){"none"===this.Xl&&(this.Bc={});for(var g in this.Bc)this.Bc.hasOwnProperty(g)&&this.TA(this.Bc[g])}c&&c.success&&c.success()};a.b.g("CollectionTreeDataSource.prototype.sort",{sort:a.ya.prototype.sort});
a.ya.prototype.TA=function(a){a.comparator=this.fk;a.sortDirection="ascending"===this.Xl?1:-1;a.sort()};a.ya.prototype.wo=function(){return{key:this.fk,direction:this.Xl}};a.b.g("CollectionTreeDataSource.prototype.getSortCriteria",{wo:a.ya.prototype.wo});a.ya.prototype.move=function(){a.i.fa()};a.b.g("CollectionTreeDataSource.prototype.move",{move:a.ya.prototype.move});a.ya.prototype.Pi=function(){return"invalid"};a.b.g("CollectionTreeDataSource.prototype.moveOK",{Pi:a.ya.prototype.Pi});a.ya.prototype.getCapability=
function(a){return"sort"===a?"default":"move"===a?"none":"batchFetch"===a||"fetchDescendants"===a?"disable":null};a.b.g("CollectionTreeDataSource.prototype.getCapability",{getCapability:a.ya.prototype.getCapability});a.Lc=function(a,c,b,d,e){this.Ds=a;this.pa=c;this.wx=[];this.cp=b;this.start=d<c.length?d:c.length-1;this.count=-1===e?c.length:Math.min(c.length,e)};o_("CollectionNodeSet",a.Lc,a);a.Lc.prototype.Xy=function(a){this.jC(this).then(function(){a.success&&a.success()})};a.Lc.prototype.jC=
function(f){return a.b.ha(function(a){function b(e){e<d?f.MJ(e,{success:function(a){null!==a?f.jC(a).then(function(){b(e+1)}):b(e+1)}}):a()}var d=f.Z();b(0)})};a.Lc.prototype.MJ=function(a,c){var b=this.pa.at(a);if(this.cp.Pl(b).leaf)this.wx[a]=null,c.success(null);else{var d=this.cp.gp(b),b=this.cp.Pl(b).key,e=this;this.cp.em(d,0,-1,{success:function(b){e.wx[a]=b;c.success(b)}},b)}};a.Lc.prototype.getParent=function(){return this.Ds};a.b.g("CollectionNodeSet.prototype.getParent",{getParent:a.Lc.prototype.getParent});
a.Lc.prototype.Ka=function(){return this.start};a.b.g("CollectionNodeSet.prototype.getStart",{Ka:a.Lc.prototype.Ka});a.Lc.prototype.Z=function(){return this.count};a.b.g("CollectionNodeSet.prototype.getCount",{Z:a.Lc.prototype.Z});a.Lc.prototype.getData=function(a){this.du(a);return this.pa.at(a).attributes};a.b.g("CollectionNodeSet.prototype.getData",{getData:a.Lc.prototype.getData});a.Lc.prototype.du=function(a){if(a<this.start||a>this.start+this.count)throw"Out of range";};a.Lc.prototype.getMetadata=
function(a){this.du(a);var c={};a=this.pa.at(a);a=this.cp.Pl(a);c.key=a.key;c.leaf=a.leaf;c.depth=a.depth;return c};a.b.g("CollectionNodeSet.prototype.getMetadata",{getMetadata:a.Lc.prototype.getMetadata});a.Lc.prototype.Hd=function(a){this.du(a);return this.wx[a]};a.b.g("CollectionNodeSet.prototype.getChildNodeSet",{Hd:a.Lc.prototype.Hd})});
//# sourceMappingURL=oj-modular.map