"use strict";
/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojdvt-base","ojs/internal-deps/dvt/DvtTreemap"],function(a,f){a.Oa("oj.ojTreemap",f.oj.dvtBaseComponent,{version:"1.0.0",widgetEventPrefix:"oj",options:{isolate:null,optionChange:null,select:null},Cf:function(a,b,d){return DvtTreemap.newInstance(a,b,d)},ef:function(){var a=this._super();a.push("oj-treemap");return a},aj:function(){var a=this._super();a["oj-treemap-isolate-icon"]={path:"_resources/isolate",property:"CSS_URL"};a["oj-treemap-isolate-icon oj-hover"]=
{path:"_resources/isolateOver",property:"CSS_URL"};a["oj-treemap-isolate-icon oj-active"]={path:"_resources/isolateDown",property:"CSS_URL"};a["oj-treemap-restore-icon"]={path:"_resources/restore",property:"CSS_URL"};a["oj-treemap-restore-icon oj-hover"]={path:"_resources/restoreOver",property:"CSS_URL"};a["oj-treemap-restore-icon oj-active"]={path:"_resources/restoreDown",property:"CSS_URL"};a["oj-treemap-attribute-type-text"]={path:"styleDefaults/_attributeTypeTextStyle",property:"CSS_TEXT_PROPERTIES"};
a["oj-treemap-attribute-value-text"]={path:"styleDefaults/_attributeValueTextStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-treemap-node"]={path:"nodeDefaults/labelStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-treemap-node oj-hover"]={path:"nodeDefaults/hoverColor",property:"border-top-color"};a["oj-treemap-node oj-selected"]=[{path:"nodeDefaults/selectedOuterColor",property:"border-top-color"},{path:"nodeDefaults/selectedInnerColor",property:"border-bottom-color"}];a["oj-treemap-node-header"]=[{path:"nodeDefaults/header/backgroundColor",
property:"background-color"},{path:"nodeDefaults/header/borderColor",property:"border-top-color"},{path:"nodeDefaults/header/labelStyle",property:"CSS_TEXT_PROPERTIES"}];a["oj-treemap-node-header oj-hover"]=[{path:"nodeDefaults/header/hoverBackgroundColor",property:"background-color"},{path:"nodeDefaults/header/hoverOuterColor",property:"border-top-color"},{path:"nodeDefaults/header/hoverInnerColor",property:"border-bottom-color"}];a["oj-treemap-node-header oj-selected"]=[{path:"nodeDefaults/header/selectedBackgroundColor",
property:"background-color"},{path:"nodeDefaults/header/selectedOuterColor",property:"border-top-color"},{path:"nodeDefaults/header/selectedInnerColor",property:"border-bottom-color"}];return a},bj:function(){return["isolate","optionChange","select"]},wm:function(){var a=this._super();a["DvtTreemapBundle.COLOR"]=this.pc("labelColor");a["DvtTreemapBundle.SIZE"]=this.pc("labelSize");return a},cj:function(a){var b=a&&a.getType?a.getType():null,d,e;if(b===DvtSelectionEvent.TYPE){b=[];a=a.getSelection();
for(d=0;d<a.length;d++)e={id:a[d]},b.push(e);this.$g("selectedNodes",a);this._trigger("select",null,{items:b})}else b===DvtTreemapIsolateEvent.TYPE?(b=this.options.YD,b||(this.options.YD=[],b=this.options.YD),(a=a.getId())?(d="on",b.push(a),this.$g("isolatedNode",a)):(d="off",a=b.pop(),this.$g("isolatedNode",0<b.length?b[b.length]:null)),this._trigger("isolate",null,{item:{id:a},type:d})):this._super(a)},xk:function(a){return"isolatedNode"==a||"selectedNodes"==a},getNodeBySubId:function(a){return this._super(a)},
getSubIdByNode:function(a){return this._super(a)},getNode:function(c){var b=this.Va.getAutomation();return new a.df(b.getNode(c))}});a.df=function(a){this.f=a};o_("TreemapNode",a.df,a);a.df.prototype.od=function(){return this.f?this.f.color:null};a.b.g("TreemapNode.prototype.getColor",{od:a.df.prototype.od});a.df.prototype.pe=function(){return this.f?this.f.label:null};a.b.g("TreemapNode.prototype.getLabel",{pe:a.df.prototype.pe});a.df.prototype.vo=function(){return this.f?this.f.size:null};a.b.g("TreemapNode.prototype.getSize",
{vo:a.df.prototype.vo});a.df.prototype.te=function(){return this.f?this.f.tooltip:null};a.b.g("TreemapNode.prototype.getTooltip",{te:a.df.prototype.te});a.df.prototype.isSelected=function(){return this.f?this.f.selected:!1};a.b.g("TreemapNode.prototype.isSelected",{isSelected:a.df.prototype.isSelected})});
//# sourceMappingURL=oj-modular.map