define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(a,f){(function(){a.Oa("oj.ojTrain",f.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{steps:[],selected:"",optionChange:null,beforeDeselect:null,deselect:null,beforeSelect:null,select:null},Je:0,tb:null,_ComponentCreate:function(){this._super();var a=this.options,b=a.steps;this.Je=b.length;this.tl=f("\x3cdiv class\x3d'oj-train-wrapper'\x3e\x3c/div\x3e");this.tl.appendTo(this.element);this.Om=
f("\x3cdiv class\x3d'oj-train-connector-wrapper'\x3e\x3c/div\x3e");this.Om.appendTo(this.tl);(this.yG=0<=this.element.attr("class").indexOf("oj-train-stretch")?!0:!1)&&this.Om.css("padding","0 "+100/(2*this.Je)+"%");this.ku=f("\x3cdiv class\x3d'oj-train-connector'\x3e\x3c/div\x3e");this.ku.appendTo(this.Om);this.Dd=f("\x3cul\x3e");this.Dd.addClass("oj-train-step-list");this.bq=f("\x3cdiv class\x3d'oj-train-connector-fill'\x3e\x3c/div\x3e");this.bq.appendTo(this.Om);this.mU();this.jf=this.Av(a.selected);
-1===this.jf&&(this.jf=0,a.selected=b[0].id);for(a=0;a<this.Je;a++)b=f("\x3cli\x3e").addClass("oj-train-step-list-item").attr({id:this.tb[a][1]}),b.appendTo(this.Dd),this.HO(a),this.KO(a),this.GO(a),this.IO(a),this.yG&&b.css("width",100/this.Je+"%");this.bq.css({width:(this.Je-1===this.jf?100:100/(2*(this.Je-1))+this.jf/(this.Je-1)*100)+"%"});this.Dd.appendTo(this.tl);this.element.addClass("oj-train")},mU:function(){var a=this.options;this.tb=[];for(var b=0;b<this.Je;b++){var d=a.steps[b];this.tb[b]=
Array(5);this.tb[b][0]=d.label?d.label:null;this.tb[b][1]=d.id?d.id:null;this.tb[b][2]=d.disabled?!0:!1;this.tb[b][3]=d.visited?!0:!1;this.tb[b][4]=d.messageType?d.messageType:null}},GO:function(a){var b=f("\x3cdiv/\x3e").addClass("oj-train-button"),d=f("\x3cspan/\x3e"),e=this,g="";if(this.tb[a]){var h=this.tb[a][3],k=this.tb[a][2];this.jf===a?(b.addClass("oj-selected"),g=" current "):h&&!k?(b.addClass("oj-visited"),g=" visited "):h||k?b.addClass("oj-disabled"):(b.addClass("oj-default"),g=" not visited ");
this.tb[a][2]||this.jf===a||(this._hoverable(b),b.on("click"+this.eventNamespace,function(){var a=e.options.selected;e.options.selected=this.parentNode.parentNode.id;e.Oc("selected",a,this.parentNode.parentNode.id,!0);e.refresh()}));h=this.Dd.children().eq(a).find(".oj-train-button-connector");1<=h.length&&h.children().remove();h.append(b);d.text(g);d.addClass("oj-helper-hidden-accessible");this.Dd.children().eq(a).find("a").append(d)}},IO:function(a){var b=f("\x3cdiv/\x3e").addClass("oj-train-icon"),
d=f("\x3cspan/\x3e"),e="",g=this;if(this.tb[a]){var h=this.tb[a][4];"confirmation"===h?(b.addClass("oj-confirmation"),e=" Confirmation "):"info"===h?(b.addClass("oj-info"),e=" Info "):"error"===h?(b.addClass("oj-error"),e=" Error "):"fatal"===h?(b.addClass("oj-error"),e=" Error "):"warning"===h&&(b.addClass("oj-warning"),e=" Warning ");var k=this.Dd.children().eq(a).find(".oj-train-button");1<=k.children().length&&k.children().remove();this.tb[a][2]||this.jf===a||(this._hoverable(b),b.on("click"+
this.eventNamespace,function(){g.Oc("selected",g.options.selected,this.parentNode.parentNode.parentNode.id,!0);g.refresh()}));null!=h&&(d.text(e),d.addClass("oj-helper-hidden-accessible"),this.Dd.children().eq(a).find("a").append(d),k.append(b))}},Oc:function(a,b,d,e){var f={option:a,previousValue:b,value:d,optionMetadata:{writeback:e?"shouldWrite":"shouldNotWrite"}};a={option:a,fromStep:this.getStep(b),toStep:this.getStep(d),optionMetadata:{writeback:e?"shouldWrite":"shouldNotWrite"}};!1!==this._trigger("beforeDeselect",
null,a)&&!1!==this._trigger("beforeSelect",null,a)&&(b=this.Av(b),-1!==b&&(this.options.steps[b].visited=!0),this._trigger("deselect",null,a),this.options.selected=d,this._trigger("select",null,a),this._trigger("optionChange",e,f))},KO:function(a){var b=f("\x3cdiv/\x3e");b.addClass("oj-train-button-connector");this.tb[a]&&(a<=this.jf&&b.addClass("oj-train-fill"),a=this.Dd.children().eq(a).children(),b.insertBefore(a))},HO:function(a){var b=this;if(this.tb[a]){var d=f("\x3cdiv/\x3e").addClass("oj-train-label-wrapper"),
e=f("\x3ca\x3e"+this.tb[a][0]+"\x3c/a\x3e");d.append(e);e.addClass("oj-train-label");a===this.jf?e.addClass("oj-selected"):this.tb[a][3]?e.addClass("oj-visited"):this.tb[a][2]&&e.addClass("oj-disabled");this.tb[a][2]||this.jf===a||(e.attr("href","#"),this._hoverable(e),e.on("click keydown"+this.eventNamespace,function(a){if(a.keyCode===f.ui.keyCode.ENTER||"click"===a.type)a.preventDefault(),b.Oc("selected",b.options.selected,this.parentNode.parentNode.id,!0),b.refresh()}));e=this.Dd.children().eq(a).children();
1<=e.length&&e[0].remove();this.Dd.children().eq(a).append(d)}},Av:function(a){for(var b=0;b<this.Je;b++)if(this.tb[b]&&this.tb[b][1]===a)return b;return-1},getStep:function(a){for(var b=0;b<this.Je;b++)if(this.tb[b]&&this.tb[b][1]===a)return jQuery.extend({},this.options.steps[b]);return null},nextSelectableStep:function(){for(var a=this.jf;a<this.Je;a++)if(a+1<this.Je&&this.tb[a+1]&&!this.tb[a+1][2])return this.tb[a+1][1];return null},previousSelectableStep:function(){for(var a=this.jf;0<=a;a--)if(this.tb[a-
1]&&!this.tb[a-1][2])return this.tb[a-1][1];return null},setStep:function(a){if(a.id){var b=this.getStep(a.id),d=this.Av(a.id);-1!==d&&(d=this.options.steps[d],a.label&&(b[0]=a.label,d.label=a.label),"boolean"===typeof a.disabled&&(b[2]=a.disabled,d.disabled=a.disabled),"boolean"===typeof a.visited&&(b[3]=a.visited,d.visited=a.visited),a.messageType&&(b[4]=a.messageType,d.messageType=a.messageType))}},_setOption:function(a,b,d){if("selected"===a){var e=this.options.selected;this.options.selected=
b;e&&this.Oc("selected",e,b,!0)}this._super(a,b,d)},_setOptions:function(a){this._super(a);this.refresh()},refresh:function(){this._super();this._destroy();this._ComponentCreate()},_destroy:function(){this.element.removeClass("oj-train oj-train-bar oj-train-wrapper oj-train-connector-wrapper oj-train-connector oj-train-connector-fill oj-train-fill oj-component-initnode");this.tl.remove();this.Om.remove();this.ku.remove();this.bq.remove();this.Dd.remove();this.Dd.children().each(function(){f(this).remove()});
this._super()},getNodeBySubId:function(a){if(null===a)return this.element?this.element[0]:null;var b=a.index;if("number"!==typeof b||0>b||b>=this.Je)return null;switch(a.subId){case "oj-train-button":return this.Dd.children().eq(b).find(".oj-train-button");case "oj-train-button-connector":return this.Dd.children().eq(b).find(".oj-train-button-connector");case "oj-train-connector":return this.ku;case "oj-train-connector-fill":return this.bq;case "oj-train-icon":return this.Dd.children().eq(b).find(".oj-train-icon");
case "oj-train-label":return this.Dd.children().eq(b).find(".oj-train-button")}return null}})})()});
//# sourceMappingURL=oj-modular.map