"use strict";
/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2008, 2013, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2008, 2013, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2008, 2013, Oracle and/or its affiliates. 
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojL10n!ojtranslations/nls/localeElements","ojs/ojmessaging"],function(a,f,c){a.Ga={};o_("LocaleData",a.Ga,a);a.Ga.By=function(b){a.Ga.Ot=b};o_("LocaleData.setBundle",a.Ga.By,a);a.Ga.WH=function(){return a.Ga.Ev("firstDay")};o_("LocaleData.getFirstDayOfWeek",a.Ga.WH,a);a.Ga.sW=function(){return a.Ga.Ev("weekendStart")};o_("LocaleData.getWeekendStart",a.Ga.sW,a);a.Ga.rW=function(){return a.Ga.Ev("weekendEnd")};o_("LocaleData.getWeekendEnd",a.Ga.rW,a);a.Ga.Kx=function(b){if(null==
b||"abbreviated"!==b&&"narrow"!==b)b="wide";b=a.Ga.Qu().days["stand-alone"][b];return[b.sun,b.mon,b.tue,b.wed,b.thu,b.fri,b.sat]};o_("LocaleData.getDayNames",a.Ga.Kx,a);a.Ga.os=function(b){if(null==b||"abbreviated"!==b&&"narrow"!==b)b="wide";b=a.Ga.Qu().months["stand-alone"][b];return[b["1"],b["2"],b["3"],b["4"],b["5"],b["6"],b["7"],b["8"],b["9"],b["10"],b["11"],b["12"]]};o_("LocaleData.getMonthNames",a.Ga.os,a);a.Ga.BI=function(){var b=a.Ga.Qu().dateFormats["long"].toUpperCase(),c=b.indexOf("M"),
b=b.indexOf("Y");return c<b};o_("LocaleData.isMonthPriorToYear",a.Ga.BI,a);a.Ga.Ev=function(b){var c=a.Ga.jg(),d=a.Ga.ZP()||"001";b=c.supplemental.weekData[b];d=b[d];void 0===d&&(d=b["001"]);return d};a.Ga.Qu=function(){var b=a.Ga.jg().main,c,d;for(d in b)if(b.hasOwnProperty(d)){c=b[d];break}return c.dates.calendars.gregorian};a.Ga.ZP=function(){var b=a.ia.qe();if(b&&(b=b.toUpperCase().split(/-|_/),2<=b.length)){var c=b[1];if(4==c.length){if(3<=b.length)return b[2]}else return c}return null};a.Ga.jg=
function(){var b=a.Ga.Ot;return b?b:a.Cm()?(a.i.assert(void 0!==c,"LocaleElements module must be loaded"),c):{}};a.Ga.sM=function(a){c=a};a.ca={};o_("Validation",a.ca,a);a.ca.nu={};a.ca.lx={};a.ca.LB={};a.ca.OB={};a.ca.pp={converter:{name:"oj.ConverterFactory",type:a.Zf},validator:{name:"oj.ValidatorFactory",type:a.Tb}};a.ca.yi=function(b,c){var d;b&&!c?d=a.ca.Fq(b,a.ca.nu):b&&c&&(d=a.ca.fl(b,c,a.ca.nu,a.ca.pp.converter));return d};o_("Validation.converterFactory",a.ca.yi,a);a.ca.Xf=function(b,c){var d;
b&&!c?d=a.ca.Fq(b,a.ca.lx):b&&c&&(d=a.ca.fl(b,c,a.ca.lx,a.ca.pp.validator));return d};o_("Validation.validatorFactory",a.ca.Xf,a);a.ca.fW=function(b){return a.ca.Fq(b,a.ca.LB)};o_("Validation.getDefaultConverterFactory",a.ca.fW,a);a.ca.gW=function(b){return a.ca.Fq(b,a.ca.OB)};o_("Validation.getDefaultValidatorFactory",a.ca.gW,a);a.ca.FA=function(b,c){var d=a.ca.pp.converter;a.ca.fl(b,c,a.ca.LB,d);a.ca.fl(b,c,a.ca.nu,d)};a.ca.Bk=function(b,c){var d=a.ca.pp.validator;a.ca.fl(b,c,a.ca.OB,d);a.ca.fl(b,
c,a.ca.lx,d)};a.ca.EO=function(b,c,d){if(c&&!a.ca.XS(b,c))throw Error("Factory instance does not implement the methods expected by the factory of type "+d);};a.ca.Fq=function(b,c){a.i.Zr(b);var d=null;b&&(b=b.toLowerCase(),d=(c[b]||{}).instance||null);return d};a.ca.XS=function(b,c){var d=!0,e;a.i.oe(b);a.i.oe(c);for(e in c)if(c.hasOwnProperty(e)&&"function"===typeof c[e]&&!b[e]&&"function"!==typeof b[e]){d=!1;break}return d};a.ca.fl=function(b,c,d,e){a.i.Zr(b);a.i.oe(c);if(b){var f={};f.instance=
c;a.ca.EO(c,e.type,e.name);d[b.toLowerCase()]=f}};a.Zf={CONVERTER_TYPE_NUMBER:"number",CONVERTER_TYPE_DATETIME:"datetime",createConverter:function(){}};o_("ConverterFactory",a.Zf,a);a.Tb={VALIDATOR_TYPE_REQUIRED:"required",VALIDATOR_TYPE_REGEXP:"regexp",VALIDATOR_TYPE_NUMBERRANGE:"numberRange",VALIDATOR_TYPE_LENGTH:"length",VALIDATOR_TYPE_DATETIMERANGE:"dateTimeRange",VALIDATOR_TYPE_DATERESTRICTION:"dateRestriction",createValidator:function(){}};o_("ValidatorFactory",a.Tb,a);a.Mc=function(a){this.Init(a)};
o_("Converter",a.Mc,a);a.b.sa(a.Mc,a.b,"oj.Converter");a.Mc.prototype.Init=function(b){a.Mc.t.Init.call(this);this.Wa=b};a.b.g("Converter.prototype.Init",{Init:a.Mc.prototype.Init});a.Mc.prototype.Xb=function(){a.i.fa();return null};a.b.g("Converter.prototype.getHint",{Xb:a.Mc.prototype.Xb});a.Mc.prototype.rf=function(){return this.Wa||{}};a.b.g("Converter.prototype.getOptions",{rf:a.Mc.prototype.rf});a.Mc.prototype.parse=function(){a.i.fa();return null};a.b.g("Converter.prototype.parse",{parse:a.Mc.prototype.parse});
a.Mc.prototype.format=function(){a.i.fa();return null};a.b.g("Converter.prototype.format",{format:a.Mc.prototype.format});a.Mc.prototype.resolvedOptions=function(){var a={};f.extend(a,this.Wa);return a};a.b.g("Converter.prototype.resolvedOptions",{resolvedOptions:a.Mc.prototype.resolvedOptions});a.rd=function(b,c){var d=new a.U(b,c,a.U.Mb.ERROR);this.Init(d)};o_("ConverterError",a.rd,a);a.rd.prototype=Error();a.rd.prototype.Init=function(a){var b=a.detail,c=a.summary;this.hw=a;this.name="Converter Error";
this.message=b||c};a.b.g("ConverterError.prototype.Init",{Init:a.rd.prototype.Init});a.rd.prototype.Fl=function(){return this.hw};a.b.g("ConverterError.prototype.getMessage",{Fl:a.rd.prototype.Fl});a.$e=function(){this.Init()};o_("NumberConverter",a.$e,a);a.b.sa(a.$e,a.Mc,"oj.NumberConverter");a.$e.prototype.Init=function(b){a.$e.t.Init.call(this,b)};a.b.g("NumberConverter.prototype.Init",{Init:a.$e.prototype.Init});a.$e.prototype.format=function(b){return a.$e.t.format.call(this,b)};a.b.g("NumberConverter.prototype.format",
{format:a.$e.prototype.format});a.$e.prototype.parse=function(b){return a.$e.t.parse.call(this,b)};a.b.g("NumberConverter.prototype.parse",{parse:a.$e.prototype.parse});a.xb=function(a){this.Init(a)};o_("DateTimeConverter",a.xb,a);a.b.sa(a.xb,a.Mc,"oj.DateTimeConverter");a.xb.prototype.Init=function(b){a.xb.t.Init.call(this,b)};a.b.g("DateTimeConverter.prototype.Init",{Init:a.xb.prototype.Init});a.xb.prototype.format=function(b){return a.xb.t.format.call(this,b)};a.b.g("DateTimeConverter.prototype.format",
{format:a.xb.prototype.format});a.xb.prototype.Go=function(){a.i.fa()};a.b.g("DateTimeConverter.prototype.isHourInDaySet",{Go:a.xb.prototype.Go});a.xb.prototype.Fo=function(){a.i.fa()};a.b.g("DateTimeConverter.prototype.isHourInAMPMSet",{Fo:a.xb.prototype.Fo});a.xb.prototype.Jo=function(){a.i.fa()};a.b.g("DateTimeConverter.prototype.isMinuteSet",{Jo:a.xb.prototype.Jo});a.xb.prototype.Lo=function(){a.i.fa()};a.b.g("DateTimeConverter.prototype.isSecondSet",{Lo:a.xb.prototype.Lo});a.xb.prototype.Io=
function(){a.i.fa()};a.b.g("DateTimeConverter.prototype.isMilliSecondSet",{Io:a.xb.prototype.Io});a.xb.prototype.Mo=function(){a.i.fa()};a.b.g("DateTimeConverter.prototype.isYearSet",{Mo:a.xb.prototype.Mo});a.xb.prototype.Ko=function(){a.i.fa()};a.b.g("DateTimeConverter.prototype.isMonthSet",{Ko:a.xb.prototype.Ko});a.xb.prototype.Eo=function(){a.i.fa()};a.b.g("DateTimeConverter.prototype.isDaySet",{Eo:a.xb.prototype.Eo});a.xb.prototype.Do=function(){a.i.fa()};a.b.g("DateTimeConverter.prototype.isDayNameSet",
{Do:a.xb.prototype.Do});a.xb.prototype.parse=function(b){return a.xb.t.parse.call(this,b)};a.b.g("DateTimeConverter.prototype.parse",{parse:a.xb.prototype.parse});a.Nd=function(){this.Init()};o_("Validator",a.Nd,a);a.b.sa(a.Nd,a.b,"oj.Validator");a.Nd.prototype.Init=function(){a.Nd.t.Init.call(this)};a.b.g("Validator.prototype.Init",{Init:a.Nd.prototype.Init});a.Nd.prototype.validate=function(){a.i.fa()};a.b.g("Validator.prototype.validate",{validate:a.Nd.prototype.validate});a.Nd.prototype.Xb=function(){a.i.fa()};
a.b.g("Validator.prototype.getHint",{Xb:a.Nd.prototype.Xb});a.ze=function(b,c){var d=new a.U(b,c,a.U.Mb.ERROR);this.Init(d)};o_("ValidatorError",a.ze,a);a.ze.prototype=Error();a.ze.prototype.Init=function(a){var b=a.detail,c=a.summary;this.hw=a;this.name="Validator Error";this.message=b||c};a.b.g("ValidatorError.prototype.Init",{Init:a.ze.prototype.Init});a.ze.prototype.Fl=function(){return this.hw};a.b.g("ValidatorError.prototype.getMessage",{Fl:a.ze.prototype.Fl});var b;b=function(){function a(){return{format:function(a,
b,c,d){var g;if("number"===typeof a)g=new Date(a);else if("string"===typeof a){if(""===e.trim(a))return null;g=e.isoToLocalDate(a)}else return"Invalid Date";if("Invalid Date"===g.toString())return"Invalid Date";if(2>=arguments.length||void 0===c)c={year:"numeric",month:"numeric",day:"numeric"};g=m(g,b,c);var f=e.Vj(d,"nu");void 0===e.Kg[f]&&(f="latn");if("latn"!==f){var h,p=[];for(h=0;h<g.length;h++)"0"<=g[h]&&"9">=g[h]?p.push(e.Kg[f][g[h]]):p.push(g[h]);return p.join("")}return g},ls:function(a,
b,c){return q(a,b,c)},parse:function(a,b,c,d){return n(a,b,c,d)},resolvedOptions:function(a,c,g){if(3>arguments.length||void 0===g)g=e.Dl(a);if(2>arguments.length||void 0===c)c={year:"numeric",month:"numeric",day:"numeric"};var f=!1,h;h=e.Vj(g,"nu");void 0===e.Kg[h]&&(h="latn");if(void 0!==c&&void 0!==c.pattern)return h=t(g,h,c.pattern),h.pattern=c.pattern,h;if(void 0!==c){h={locale:g,numberingSystem:h,calendar:"gregorian"};var p=0;for(p in c)p++;if(0==p)return h.year="numeric",h.month="numeric",
h.day="numeric",h;var p=e.Fh(c,"OraDateTimeConverter.resolvedOptions"),l=p("year","string",["2-digit","numeric"]);void 0!==l&&(h.year=l,f=!0);l=p("era","string",["narrow","short","long"]);void 0!==l&&(h.era=l,f=!0);l=p("month","string",["2-digit","numeric","narrow","short","long"]);void 0!==l&&(h.month=l,f=!0);l=p("day","string",["2-digit","numeric"]);void 0!==l&&(h.day=l,f=!0);l=p("weekday","string",["narrow","short","long"]);void 0!==l&&(h.weekday=l,f=!0);l=p("hour","string",["2-digit","numeric"]);
void 0!==l&&(h.hour=l,f=!0,l=p("hour12","boolean",[!0,!1]),void 0===l&&(l=s(a)),h.hour12=l);l=p("minute","string",["2-digit","numeric"]);void 0!==l&&(h.minute=l,f=!0);l=p("second","string",["2-digit","numeric"]);void 0!==l&&(h.second=l,f=!0);h["two-digit-year-start"]=u(c);if(!f){var f=z(c,a,b.resolvedOptions),l=p("formatType","string",["date","time","datetime"],"date"),m=p("dateFormat","string",["short","medium","long","full"],"short"),p=p("timeFormat","string",["short","medium","long","full"],"short");
h.formatType=l;if("datetime"===l||"date"===l)h.dateFormat=m;if("datetime"===l||"time"===l)h.timeFormat=p;h.patternFromOptions=f;return h}h.patternFromOptions=d(c,a,"OraDateTimeConverter.resolvedOptions");return h}p=d({year:"numeric",month:"numeric",day:"numeric"},a,"OraDateTimeConverter.resolvedOptions");return{calendar:"gregorian",locale:g,numberingSystem:h,year:"numeric",month:"numeric",day:"numeric",patternFromOptions:p}},jo:function(a){a=e.isoToLocalDate(a);var b=new Date(a.getTime());b.setDate(b.getDate()+
4-(b.getDay()||7));a=b.getTime();b.setMonth(0);b.setDate(1);return Math.floor(Math.round((a-b)/864E5)/7)+1}}}var c,d,f,m,n,q,r,t,p,u,s,v,z,w={},y,H,x,O,B,A,D,C,I,P,F,G,N,J,K,E,S,Y,W,T,Q,da,R,L,aa,ea,U,ba,X,ca,na,M,ha,oa,fa,ga,ia,pa,ja,ka,la=/(\d{1,4})\D+?(\d{1,4})/g,ma=/(\d{1,4})\D+?(\d{1,4})\D+?(\d{1,4})/g,qa=/^[M][^M]|[^M]M[^M]/g,wa=/^[L][^L]|[^L]L[^L]/g,ra=/^[d][^d]|[^d]d[^d]/g,sa=/(?:^|[^h])h[^h]|[^H]H[^H]|[^k]k[^k]|[^K]K[^K]/,ta=/(\d{1,2})(?:\D+?(\d{1,2}))?(?:\D+?(\d{1,2}))?(?:\D+?(\d{1,3}))?/g,
ua=/h|H|K|k/g,va=/([\^\$\.\*\+\?\|\[\]\(\)\{\}])/g,Z=/ccccc|cccc|ccc|cc|c|EEEEE|EEEE|EEE|EE|E|dd|d|MMMMM|MMMM|MMM|MM|M|LLLLL|LLLL|LLL|LL|L|yyyy|yy|y|hh|h|HH|H|KK|K|kk|k|mm|m|ss|s|aa|a|SSS|SS|S|zzzz|zzz|zz|z|GGGGG|GGGG|GGG|GG|G/g,xa=/\s?(?:\(|\[)??z{1,4}(?:\)|\])?/g,ya=/^\d{4}(?:-\d{2}(?:-\d{2})?)?(?:T\d{2}:\d{2}(?::\d{2}(?:\.\d{1,3})?)?Z?)?$|^T\d{2}:\d{2}(?::\d{2}(?:\.\d{1,3})?)?Z?$/,za={0:"sun",1:"mon",2:"tue",3:"wed",4:"thu",5:"fri",6:"sat"},V={MMM:{token:"months",style:"format",mLen:"abbreviated",
matchIndex:0,key:"month",value:"short",regExp:"(\\D+|\\d\\d?\\D|\\d\\d?|\\D+\\d\\d?)"},MMMM:{token:"months",style:"format",mLen:"wide",matchIndex:0,key:"month",value:"long",regExp:"(\\D+|\\d\\d?\\D|\\d\\d?|\\D+\\d\\d?)"},MMMMM:{token:"months",style:"format",mLen:"narrow",matchIndex:0,key:"month",value:"narrow",regExp:"(\\D+|\\d\\d?\\D|\\d\\d?|\\D+\\d\\d?)"},LLL:{token:"months",style:"stand-alone",mLen:"abbreviated",matchIndex:1,key:"month",value:"short",regExp:"(\\D+|\\d\\d?\\D|\\d\\d?|\\D+\\d\\d?)"},
LLLL:{token:"months",style:"stand-alone",mLen:"wide",matchIndex:1,key:"month",value:"long",regExp:"(\\D+|\\d\\d?\\D|\\d\\d?|\\D+\\d\\d?)"},LLLLL:{token:"months",style:"stand-alone",mLen:"narrow",matchIndex:1,key:"month",value:"narrow",regExp:"(\\D+|\\d\\d?\\D|\\d\\d?|\\D+\\d\\d?)"},E:{token:"days",style:"format",dLen:"abbreviated",matchIndex:0,key:"weekday",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},EE:{token:"days",style:"format",dLen:"abbreviated",matchIndex:0,key:"weekday",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},
EEE:{token:"days",style:"format",dLen:"abbreviated",matchIndex:0,key:"weekday",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},EEEE:{token:"days",style:"format",dLen:"wide",matchIndex:0,key:"weekday",value:"long",regExp:"(\\D+|\\D+\\d\\d?)"},EEEEE:{token:"days",style:"format",dLen:"narrow",matchIndex:0,key:"weekday",value:"narrow",regExp:"(\\D+|\\D+\\d\\d?)"},c:{token:"days",style:"stand-alone",dLen:"abbreviated",matchIndex:1,key:"weekday",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},cc:{token:"days",style:"stand-alone",
dLen:"abbreviated",matchIndex:1,key:"weekday",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},ccc:{token:"days",style:"stand-alone",dLen:"abbreviated",matchIndex:1,key:"weekday",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},cccc:{token:"days",style:"stand-alone",dLen:"wide",matchIndex:1,key:"weekday",value:"long",regExp:"(\\D+|\\D+\\d\\d?)"},ccccc:{token:"days",style:"stand-alone",dLen:"narrow",matchIndex:1,key:"weekday",value:"narrow",regExp:"(\\D+|\\D+\\d\\d?)"},h:{token:"time",timePart:"hour",start1:0,
end1:11,start2:1,end2:12,key:"hour",value:"numeric",regExp:"(\\d\\d?)"},hh:{token:"time",timePart:"hour",start1:0,end1:11,start2:1,end2:12,key:"hour",value:"2-digit",regExp:"(\\d\\d?)"},K:{token:"time",timePart:"hour",start1:0,end1:11,start2:0,end2:11,key:"hour",value:"numeric",regExp:"(\\d\\d?)"},KK:{token:"time",timePart:"hour",start1:0,end1:11,start2:0,end2:11,key:"hour",value:"2-digit",regExp:"(\\d\\d?)"},H:{token:"time",timePart:"hour",start1:0,end1:23,start2:0,end2:23,key:"hour",value:"numeric",
regExp:"(\\d\\d?)"},HH:{token:"time",timePart:"hour",start1:0,end1:23,start2:0,end2:23,key:"hour",value:"2-digit",regExp:"(\\d\\d?)"},k:{token:"time",timePart:"hour",start1:0,end1:23,start2:1,end2:24,key:"hour",value:"numeric",regExp:"(\\d\\d?)"},kk:{token:"time",timePart:"hour",start1:0,end1:23,start2:1,end2:24,key:"hour",value:"2-digit",regExp:"(\\d\\d?)"},m:{token:"time",timePart:"minute",start1:0,end1:59,start2:0,end2:59,key:"minute",value:"numeric",regExp:"(\\d\\d?)"},mm:{token:"time",timePart:"minute",
start1:0,end1:59,start2:0,end2:59,key:"minute",value:"2-digit",regExp:"(\\d\\d?)"},s:{token:"time",timePart:"second",start1:0,end1:59,start2:0,end2:59,key:"second",value:"numeric",regExp:"(\\d\\d?)"},ss:{token:"time",timePart:"second",start1:0,end1:59,start2:0,end2:59,key:"second",value:"2-digit",regExp:"(\\d\\d?)"},S:{token:"time",timePart:"millisec",start1:0,end1:999,start2:0,end2:999,key:"millisecond",value:"numeric",regExp:"(\\d{1,3})"},SS:{token:"time",timePart:"millisec",start1:0,end1:999,start2:0,
end2:999,key:"millisecond",value:"numeric",regExp:"(\\d{1,3})"},SSS:{token:"time",timePart:"millisec",start1:0,end1:999,start2:0,end2:999,key:"millisecond",value:"numeric",regExp:"(\\d{1,3})"},d:{token:"dayOfMonth",key:"day",value:"numeric",getPartIdx:2,regExp:"(\\d\\d?)"},dd:{token:"dayOfMonth",key:"day",value:"2-digit",getPartIdx:2,regExp:"(\\d\\d?)"},M:{token:"monthIndex",key:"month",value:"numeric",getPartIdx:1,regExp:"(\\d\\d?)"},MM:{token:"monthIndex",key:"month",value:"2-digit",getPartIdx:1,
regExp:"(\\d\\d?)"},L:{token:"monthIndex",key:"month",value:"numeric",getPartIdx:1,regExp:"(\\d\\d?)"},LL:{token:"monthIndex",key:"month",value:"2-digit",getPartIdx:1,regExp:"(\\d\\d?)"},y:{token:"year",key:"year",value:"numeric",regExp:"(\\d{1,4})"},yy:{token:"year",key:"year",value:"2-digit",regExp:"(\\d\\d?)"},yyyy:{token:"year",key:"year",value:"numeric",regExp:"(\\d{1,4})"},a:{token:"ampm",key:"hour12",value:!0,regExp:"(\\D*)"},z:{token:"tz",key:"timeZoneName",value:"short",regExp:"([+-]?\\d{1,4})"},
zz:{token:"tz",key:"timeZoneName",value:"short",regExp:"([+-]?\\d{1,4})"},zzz:{token:"tz",key:"timeZoneName",value:"short",regExp:"([+-]?\\d{1,4})"},zzzz:{token:"tz",key:"timeZoneName",value:"long",regExp:"([+-]?\\d{1,4})"},G:{token:"era",key:"era",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},GG:{token:"era",key:"era",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},GGG:{token:"era",key:"era",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},GGGG:{token:"era",key:"era",value:"long",regExp:"(\\D+|\\D+\\d\\d?)"},
GGGGG:{token:"era",key:"era",value:"narrow",regExp:"(\\D+|\\D+\\d\\d?)"},"/":{token:"slash",regExp:"(\\/)"}};u=function(a){a=a["two-digit-year-start"];if(void 0===a||isNaN(a))a=1950;return a=parseInt(a,10)};s=function(a){var b=e.Es(e.Dl(a)).region||"001";return"h"===a.supplemental.prefferedHours[b]};y=function(a){return 0==a%400?!0:0==a%100?!1:0==a%4?!0:!1};H=function(a,b){switch(b){case 0:case 2:case 4:case 6:case 7:case 9:case 11:return 31;case 1:return y(a)?29:28;default:return 30}};z=function(a,
b,c){b=e.Zd(b);var d=e.Fh(a,c);a=d("formatType","string",["date","time","datetime"],"date");c=d("dateFormat","string",["short","medium","long","full"],"short");var d=d("timeFormat","string",["short","medium","long","full"],"short"),g=b.dates.calendars.gregorian;b=g.dateFormats;var g=g.timeFormats,f,h,p;switch(c){case "full":f=b.full;break;case "long":f=b["long"];break;case "medium":f=b.medium;break;case "short":f=b["short"]}switch(d){case "full":h=g.full;break;case "long":h=g["long"];break;case "medium":h=
g.medium;break;case "short":h=g["short"]}void 0===f||"datetime"!==a&&"date"!==a||(p=f);void 0===h||"datetime"!==a&&"time"!==a||(h=h.replace(xa,""),p=p?p+" "+h:h);return p};c=function(a,b){for(var c=0,d=!1,e=0,g=a.length;e<g;e++){var f=a.charAt(e);switch(f){case "'":d?b.push("'"):c++;d=!1;break;case "\\":d&&b.push("\\");d=!d;break;default:b.push(f),d=!1}}return c};r=function(a,b,c){var d;d=void 0!==b.year||void 0!==b.month||void 0!==b.weekday||void 0!==b.day;b=void 0!==b.hour||void 0!==b.minute||void 0!==
b.second;d=d&&b?"MM/dd/yy hh:mm:ss a":d?"MM/dd/yy":"hh:mm:ss a";c=new SyntaxError("Unexpected character(s) "+c+' encountered in the pattern "'+a+' An example of a valid pattern is "'+d+'".');c.errorInfo={errorCode:"optionValueInvalid",parameterMap:{propertyName:"pattern",propertyValue:a,"propertyValueHint ":d}};throw c;};D=function(a,b,c,d){b=e.Zd(b).dates.calendars.gregorian.dateTimeFormats.availableFormats;c=c?["era","year","month","weekday","day"]:["weekday","hour","minute","second"];var g=-Infinity,
f=void 0,h,p;for(p in b){var l={};l.pattern=b[p];for(var k=0;null!==(h=Z.exec(p));)h=h[0],("h"!==h&&"hh"!==h||d)&&("H"!==h&&"HH"!==h||!d)&&void 0!==V[h]&&(l[V[h].key]=V[h].value);for(var m in c){h=a[c[m]];var u=l[c[m]];if(void 0===h&&void 0!==u)k-=20;else if(void 0!==h&&void 0===u)k-=120;else if(void 0!==h&&void 0!==u){var s={"2-digit":0,numeric:1,narrow:2,"short":3,"long":4};h=Math.max(Math.min(s[u]-s[h],2),-2);2===h?k-=6:1===h?k-=3:-1===h?k-=6:-2===h&&(k-=8)}}k>g&&(g=k,f=l)}return void 0!==f?f.pattern:
null};O=function(a,b,c){var d="",g="",f={},h={};a=e.Fh(a,c);c=a("era","string",["narrow","short","long"]);d+=C(f,"era",c,{narrow:"GGGGG","short":"GGG","long":"GGGG"});c=a("year","string",["2-digit","numeric"]);d+=C(f,"year",c,{"2-digit":"yy",numeric:"y"});c=a("month","string",["2-digit","numeric","narrow","short","long"]);d+=C(f,"month",c,{"2-digit":"MM",numeric:"M",narrow:"MMMMM","short":"MMM","long":"MMMM"});c=a("weekday","string",["narrow","short","long"]);d+=C(f,"weekday",c,{narrow:"EEEEE","short":"E",
"long":"EEEE"});c=a("day","string",["2-digit","numeric"]);var d=d+C(f,"day",c,{"2-digit":"dd",numeric:"d"}),p=a("hour12","boolean",[!0,!1]);void 0===p&&(p=s(b));c=a("hour","string",["2-digit","numeric"]);g=!0===p?g+C(h,"hour",c,{"2-digit":"hh",numeric:"h"}):g+C(h,"hour",c,{"2-digit":"HH",numeric:"H"});c=a("minute","string",["2-digit","numeric"]);g+=C(h,"minute",c,{"2-digit":"mm",numeric:"m"});c=a("second","string",["2-digit","numeric"]);g+=C(h,"second",c,{"2-digit":"ss",numeric:"s"});return[d,g,f,
h]};C=function(a,b,c,d){return void 0!==c?(a[b]=c,d[c]):""};B=function(a,b,c){var d=a;b=e.Fh(b,c);c=b("year","string",["2-digit","numeric"]);var g={"2-digit":"yy",numeric:"yyyy"};void 0!==c&&(d=d.replace(/y{1,4}/,g[c]));c=b("month","string",["2-digit","numeric","narrow","short","long"]);if(void 0!==c){var g={"2-digit":"MM",numeric:"M",narrow:"MMMMM","short":"MMM","long":"MMMM"},f={"2-digit":"LL",numeric:"L",narrow:"LLLLL","short":"LLL","long":"LLLL"};void 0!==g[c]&&2<g[c].length?(d=d.replace(/M{3,5}/,
g[c]),d=d.replace(/L{3,5}/,f[c])):"2-digit"===c&&(qa.lastIndex=0,(c=qa.test(a))&&(d=d.replace("M","MM")),(c=wa.test(a))&&(d=d.replace("L","LL")))}c=b("weekday","string",["narrow","short","long"]);void 0!==c&&(d=d.replace(/E{1,5}/,{narrow:"EEEEE","short":"EEE","long":"EEEE"}[c]),d=d.replace(/c{1,5}/,{narrow:"ccccc","short":"ccc","long":"cccc"}[c]));c=b("day","string",["2-digit","numeric"]);void 0!==c&&"2-digit"===c&&(ra.lastIndex=0,(c=ra.test(a))&&(d=d.replace("d","dd")));return d};A=function(a,b,
c){var d=a;"2-digit"===e.Fh(b,c)("hour","string",["2-digit","numeric"])&&(sa.lastIndex=0,b=sa.exec(a),null!==b&&(d=b[0].length-2,d=a.replace(b[0][d],b[0][d]+b[0][d])));return d};d=function(a,b,c){var d=e.Zd(b),g=e.Dl(b),f=e.Fh(a,c),h=f("formatMatcher","string",["basic","munger"],"munger"),p=0;for(p in a)p++;0==p&&(a={year:"numeric",month:"numeric",day:"numeric"});p=O(a,b,c);if(void 0!==w[g]&&void 0!==w[g].dates.calendars.gregorian.dateTimeFormats[p[0]+p[1]])return w[g].dates.calendars.gregorian.dateTimeFormats[p[0]+
p[1]];if(""===p[0]&&""===p[1])return z(a,b,c);var l=d.dates.calendars.gregorian.dateTimeFormats.availableFormats,d=l[p[0]],f=f("hour12","boolean",[!0,!1]);void 0===f&&(f=s(b));void 0===d&&""!==p[0]&&(d=D(p[2],b,!0,f),d=null!==d?"basic"===h?d:B(d,a,c):p[0]);l=l[p[1]];void 0===l&&""!==p[1]&&(b=D(p[3],b,!1,f),l=null!==b?"basic"===h?b:A(b,a,c):p[1]);a=d||"";void 0!==l&&(a=""!==a?a+(" "+l):l);void 0===w[g]&&(w[g]={},w[g].dates={},w[g].dates.calendars={},w[g].dates.calendars.gregorian={},w[g].dates.calendars.gregorian.dateTimeFormats=
{});return w[g].dates.calendars.gregorian.dateTimeFormats[p[0]+p[1]]=a};m=function(a,b,g){function f(a,b){switch(b){case 0:return a.getFullYear();case 1:return a.getMonth()+1;case 2:return a.getDate();case 3:return za[a.getDay()]}}function p(a,b,c,d){b=f(b,c);a.push(1<d?e.Ve(b,d):b)}function l(a,b,c,d,g){var f;switch(d.timePart){case "hour":f=11===d.end1?b.getHours()%12:b.getHours();"h"===g||"hh"===g?0===f&&(f=12):"k"!==g&&"kk"!==g||0!==f||(f=24);break;case "minute":f=b.getMinutes();break;case "second":f=
b.getSeconds();break;case "millisec":f=b.getMilliseconds()}a.push(1<c?e.Ve(f,c):f)}var m=e.Zd(b),u=g.pattern||d(g,b,"OraDateTimeConverter.format");b=[];for(var s,n=0,m=m.dates.calendars.gregorian;;){s=Z.lastIndex;var v=Z.exec(u);s=u.slice(s,v?v.index:u.length);n+=c(s,b);if(!v)break;if(n%2)b.push(v[0]);else{s=v[0];var v=s.length,t=V[s];switch(t.token){case "days":s=m[t.token][t.style][t.dLen];b.push(s[f(a,3)]);break;case "months":s=m[t.token][t.style][t.mLen];b.push(s[f(a,1)]);break;case "dayOfMonth":case "monthIndex":b.push(p(b,
a,t.getPartIdx,v));break;case "year":s=a.getFullYear();2==v&&(s%=100);b.push(e.Ve(s,v));break;case "time":l(b,a,v,t,s);break;case "ampm":s=12>a.getHours()?m.dayPeriods.format.wide.am:m.dayPeriods.format.wide.pm;b.push(s);break;case "tz":break;case "era":s=m.eras.eraAbbr;b.push(s["1"]);break;case "slash":b.push("/");break;default:r(u,g,s)}}}return b.join("")};F=function(a,b){return a.getFullYear()==b.getFullYear()};G=function(a,b){return 1==b.getFullYear()-a.getFullYear()};N=function(a,b){return G(b,
a)};J=function(a,b){return F(a,b)&&a.getMonth()===b.getMonth()};K=function(a,b){return F(a,b)?1==b.getMonth()-a.getMonth():G(a,b)?11==a.getMonth()&&0==b.getMonth():!1};E=function(a,b){return K(b,a)};I=function(a,b){var c=a.getDate(),d=b.getDate();K(a,b)&&(d+=H(a.getFullYear,a.getMonth()));return d-c};P=function(a,b){var c=e.Es(e.Dl(a)).region||"001",c=b-a.supplemental.weekData.firstDay[c];0>c&&(c+=7);return c};S=function(a,b,c){if(b>c){var d=b;b=c;c=d}if(!J(b,c)&&!K(b,c))return!1;a=I(b,c)+P(a,b.getDay());
return 0<=a&&6>=a};Y=function(a,b,c){if(!J(b,c)&&!K(b,c))return!1;a=I(b,c)+P(a,b.getDay());return 7<=a&&13>=a};W=function(a,b,c){return Y(a,c,b)};T=function(a,b){return F(a,b)&&J(a,b)&&a.getDate()===b.getDate()};Q=function(a,b){return J(a,b)||K(a,b)?1===I(a,b):!1};da=function(a,b){return Q(b,a)};q=function(a,b,c){if("number"===typeof a)a=new Date(a);else if("string"===typeof a){if(""===e.trim(a))return null;a=e.isoToLocalDate(a)}else return"Invalid Date";if("Invalid Date"===a.toString())return"Invalid Date";
var d=e.Zd(b).dates.fields;c=e.Fh(c,"OraDateTimeConverter.formatRelative");c("formatUsing","string",["displayName"]);c=c("dateField","string",["day","week","month","year"]);var g=new Date;switch(c){case "day":if(T(g,a))return d.day["relative-type-0"];if(Q(g,a))return d.day["relative-type-1"];if(da(g,a))return d.day["relative-type--1"];break;case "week":if(S(b,g,a))return d.week["relative-type-0"];if(Y(b,g,a))return d.week["relative-type-1"];if(W(b,g,a))return d.week["relative-type--1"];break;case "month":if(J(g,
a))return d.month["relative-type-0"];if(K(g,a))return d.month["relative-type-1"];if(E(g,a))return d.month["relative-type--1"];break;case "year":if(F(g,a))return d.year["relative-type-0"];if(G(g,a))return d.year["relative-type-1"];if(N(g,a))return d.year["relative-type--1"]}return null};ga=function(a,b){var c;c=Error("The weekday "+a+" does not match the date "+b);c.errorInfo={errorCode:"dateToWeekdayMismatch",parameterMap:{weekday:a,date:b}};throw c;};fa=function(a,b,c){var d;2===c?(d='The value "'+
a+'" does not match the expected date-time format "'+b+'"',c="datetimeFormatMismatch"):0===c?(d='The value "'+a+'" does not match the expected date format "'+b+'"',c="dateFormatMismatch"):(d='The value "'+a+'" does not match the expected time format "'+b+'"',c="timeFormatMismatch");d=Error(d);d.errorInfo={errorCode:c,parameterMap:{value:a,format:b}};throw d;};R=function(a,b){100>b&&(b+=100*Math.floor(a/100)+(b<a%100?100:0));return b};ha=function(a,b){var c={sun:0,mon:1,tue:2,wed:3,thu:4,fri:5,sat:6},
d;for(d in a)if(e.trim(e.ce(a[d]))==e.trim(b))return c[d];return-1};oa=function(a,b){for(var c in a)if(e.trim(e.ce(a[c]))===e.trim(b))return c-1;return-1};X=function(a,b,c){var d=e.Zd(a),g;a=d.dates.calendars.gregorian.days.format;d=d.dates.calendars.gregorian.days["stand-alone"];switch(c){case 0:g=[a.abbreviated,a.wide];break;case 1:g=[d.abbreviated,d.wide]}b=e.ce(b);c=ha(g[0],b);-1===c&&(c=ha(g[1],b));return c};ca=function(a,b,c){var d=-1,g=e.Zd(a);a=g.dates.calendars.gregorian.months.format;g=
g.dates.calendars.gregorian.months["stand-alone"];switch(c){case 0:c=[a.wide,a.abbreviated];break;case 1:c=[g.wide,g.abbreviated];break;case 2:c=[a.wide,a.abbreviated,g.wide,g.abbreviated];break;default:return-1}b=e.ce(b);for(var f in c)if(d=oa(c[f],b),-1!==d)break;return d};na=function(a,b){for(var d=a.replace(va,"\\\\$1"),e=["^"],g=[],f=0,p=0,l;null!==(l=Z.exec(d));){var k=d.slice(f,l.index),f=Z.lastIndex,p=p+c(k,e);if(p%2)e.push(l[0]);else{var k=l[0],m;void 0!==V[k]?m=V[k].regExp:r(a,b,k);m&&e.push(m);
g.push(l[0])}}c(d.slice(f),e);e.push("$");d={regExp:e.join("").replace(/\s+/g,"\\s+"),groups:g};return{}[a]=d};M=function(a,b,c,d,e,g,f){if(b<c||b>d)throw b=new RangeError(e+" is out of range.  Enter a value between "+g+" and "+f+" for "+a),b.errorInfo={errorCode:"datetimeOutOfRange",parameterMap:{value:e,minValue:g,maxValue:f,propertyName:a}},b;};L=function(a,b){for(var c in a)for(var d in a[c])if(d===b)return parseInt(c,10);return 0};ba=function(a,b,c,d){var g=e.Zd(d).dates.calendars.gregorian.dayPeriods.format.wide.pm,
f=d=ta.lastIndex=0,h=0,p=0,l=ta.exec(b);null===l&&fa(b,c,1);void 0!==l[1]&&(d=parseInt(l[1],10));void 0!==l[2]&&(f=parseInt(l[2],10));void 0!==l[3]&&(h=parseInt(l[3],10));void 0!==l[4]&&(p=parseInt(l[4],10));ua.lastIndex=0;l=ua.exec(c);switch(l[0]){case "h":12===d&&(d=0);M("hour",d,0,11,d,1,12);b=e.ce(b).indexOf(e.ce(g));-1!==b&&12>d&&(d+=12);break;case "K":M("hour",d,0,11,d,0,11);b=e.ce(b).indexOf(e.ce(g));-1!==b&&12>d&&(d+=12);break;case "H":M("hour",d,0,23,d,0,23);break;case "k":24===d&&(d=0),
M("hour",d,0,23,d,1,24)}M("minute",f,0,59,f,0,59);M("second",h,0,59,h,0,59);M("millisec",p,0,999,p,0,999);a.setHours(d,f,h,p)};ka=function(a,b){var c=e.Zd(b),d=c.dates.calendars.gregorian.days.format,c=c.dates.calendars.gregorian.days["stand-alone"],d=[d.wide,d.abbreviated,c.wide,c.abbreviated],c=!1,g,f,h;for(f in d){for(h in d[f])if(g=d[f][h],(new RegExp(g+"\\b","i")).test(a)){c=!0;break}if(c)break;g=null}return g};ea=function(a,b,c,d,e){ma.lastIndex=0;var g=ma.exec(a);null===g&&fa(a,b,0);var f=
[{y:b.indexOf("y")},{M:b.indexOf("M")},{d:b.indexOf("d")}];f.sort(function(a,b){for(var c in a)break;for(var d in b)break;return a[c]-b[d]});var h,p,l,k,m,s,n=!1,v=!1;for(s=1;3>=s;s++){var r=g[s];if(2<r.length||31<r)h=r,n=!0,k=s-1}n||(k=L(f,"y"),h=g[L(f,"y")+1]);for(s=0;3>s;s++)if(s!==k&&12<g[s+1]){l=g[s+1];v=!0;m=s;break}if(v){for(s=0;3>s;s++)if(s!==m&&s!==k){p=g[s+1];break}void 0===p&&(p=g[L(f,"M")+1])}else k===L(f,"d")?(l=g[L(f,"y")+1],p=g[L(f,"M")+1]):k===L(f,"M")?(l=g[L(f,"d")+1],p=g[L(f,"y")+
1]):(l=g[L(f,"d")+1],p=g[L(f,"M")+1]);p-=1;g=H(h,p);M("month",p,0,11,p+1,1,12);M("day",l,1,g,l,1,g);h=R(u(c),parseInt(h,10));M("year",h,0,9999,h,0,9999);c=new Date(h,p,l);h=ka(a,d);null!=h&&(p=X(d,h,0),c.getDay()!==p&&ga(h,c.getDate()));c={value:c,warning:"lenient parsing was used"};e&&(a=a.substr(ma.lastIndex),0===a.length?c.value.setHours(0,0,0,0):ba(c.value,a,b,d));return c};U=function(a,b,c,d,g){var f=a;a=e.ce(a);var h=e.Zd(d),p=h.dates.calendars.gregorian.months.format,h=h.dates.calendars.gregorian.months["stand-alone"],
p=[p.wide,p.abbreviated,h.wide,h.abbreviated],h=!1,l,k,m,s;for(k in p){l=[];for(m in p[k])s=e.ce(p[k][m]),l.push({idx:m,name:s});l.sort(function(a,b){return b.idx-a.idx});for(m in l)if(s=l[m].name,-1!=a.indexOf(s)){h=!0;a=a.replace(s,"");break}if(h)break}if(!h)return ea(f,b,c,d,g);m=ca(d,s,2);M("month",m,0,11,m,1,12);s=ka(f,d);k=new RegExp(s+"\\W","i");null!==s&&(a=a.replace(k,""));la.lastIndex=0;p=la.exec(a);null===p&&fa(f,b,0);f=[{y:b.indexOf("y")},{d:b.indexOf("d")}];f.sort(function(a,b){for(var c in a)break;
for(var d in b)break;return a[c]-b[d]});var n,v,h=!1;for(k=1;2>=k;k++)if(l=p[k],2<l.length||31<l)n=l,h=!0,v=k-1;h||(v=L(f,"y"),n=p[L(f,"y")+1]);v=v===L(f,"d")?p[L(f,"y")+1]:p[L(f,"d")+1];n=R(u(c),parseInt(n,10));M("year",n,0,9999,n,0,9999);c=new Date(n,m,v);null!=s&&(k=X(d,s,0),c.getDay()!==k&&ga(s,c.getDate()));n=H(n,m);M("day",v,1,n,v,1,n);n={value:c,warning:"lenient parsing was used"};g&&(a=a.substr(la.lastIndex),0===a.length?n.value.setHours(0,0,0,0):ba(n.value,a,b,d));return n};aa=function(a,
b,c,d){switch(p(c,"OraDateTimeConverter.parse")){case 0:return U(a,b,c,d,!1);case 1:return c=new Date,ba(c,a,b,d),{value:c,warning:"lenient parsing was used"};case 2:return U(a,b,c,d,!0)}return null};ja=function(a,b,c,d,g,f,h,p,l,k,m){g=e.Zd(a).dates.calendars.gregorian[b][g];a="months"===b?ca(a,c,f):X(a,c,f);M(m,a,h,p,c,g[d][l],g[d][k]);return a};pa=function(a,b,c,d,e){b[c.timePart]=a;"h"===e||"hh"===e?12===a&&(b[c.timePart]=0):"k"===e||"kk"===e?24===a&&(b[c.timePart]=0):"S"===e&&(b[c.timePart]=
a*Math.pow(10,3-d));M(c.timePart,b[c.timePart],c.start1,c.end1,a,c.start2,c.end2)};f=function(a,b,c,d){var g=e.Zd(d);a=e.trim(a);var f=g.dates.calendars.gregorian.eras.eraAbbr["1"],h=e.Ng(f);a=a.replace(f,h);var f=na(b,c),p=(new RegExp(f.regExp)).exec(a);if(null===p)return aa(a,b,c,d);var l=f.groups,k=h=f=null,m=null,s;s=null;for(var n=!1,v,r,t={hour:0,minute:0,second:0,millisec:0},g=g.dates.calendars.gregorian.dayPeriods.format.wide.pm,q=u(c),w=0,z=l.length;w<z;w++){var E=p[w+1];if(E){var y=l[w],
K=y.length;v=parseInt(E,10);var x=V[y];switch(x.token){case "months":h=ja(d,x.token,E,x.mLen,x.style,x.matchIndex,0,11,"1","12","month name");break;case "days":r=E;m=ja(d,x.token,E,x.dLen,x.style,x.matchIndex,0,6,"sun","sat","weekday");break;case "time":pa(v,t,x,K,y);break;case "dayOfMonth":k=v;if(31<k)return aa(a,b,c,d);break;case "monthIndex":h=v-1;if(11<h)return aa(a,b,c,d);break;case "year":f=R(q,v);M("year",f,0,9999,f,0,9999);break;case "ampm":n=e.ce(E)===e.ce(g);break;case "tz":s=v/100<<0,M("TZ Offset",
s,-12,13,v,-12,13),v=Math.abs(v%100),M("TZ Offset",v,0,59,v,0,59),s=60*s+(e.Zo(E,"-")?-v:v)}}}a=new Date;b=a.getFullYear();null===f&&(f=b);null===h&&null===k?(h=a.getMonth(),k=a.getDate()):null===k&&(k=1);b=H(f,h);M("day",k,1,b,k,1,b);a.setFullYear(f,h,k);null!==m&&a.getDay()!==m&&ga(r,a.getDate());n&&12>t.hour&&(t.hour+=12);a.setHours(t.hour,t.minute,t.second,t.millisec);null!==s&&(r=a.getMinutes()-(s+a.getTimezoneOffset()),a.setHours(a.getHours()+(r/60<<0),r%60));return{value:a}};t=function(a,b,
d){var e=d.replace(va,"\\\\$1"),g=["^"],f=0,p=0;for(a={locale:a,numberingSystem:b,calendar:"gregorian"};null!==(b=Z.exec(e));){var l=e.slice(p,b.index),p=Z.lastIndex,f=f+c(l,g);if(!(f%2)&&(b=b[0],"/"!==b&&"zzzz"!==b&&"zzz"!==b&&"zz"!==b&&"z"!==b))if(void 0!==V[b])if(a[V[b].key]=V[b].value,"kk"===b||"HH"===b||"H"===b||"k"===b)a.hour12=!1;else{if("KK"===b||"hh"===b||"h"===b||"K"===b)a.hour12=!0}else r(d,a,b)}return a};v=function(a){a=t("","",a);var b=void 0!==a.hour||void 0!==a.minute||void 0!==a.second;
return void 0===a.year&&void 0===a.month&&void 0===a.weekday&&void 0===a.day||!b?b?1:0:2};p=function(a,b){if(void 0!==a.pattern)return v(a.pattern);var c=e.Fh(a,b),d=void 0!==c("hour","string",["2-digit","numeric"])||void 0!==c("minute","string",["2-digit","numeric"])||void 0!==c("second","string",["2-digit","numeric"]),g=void 0!==c("year","string",["2-digit","numeric"])||void 0!==c("month","string",["2-digit","numeric","narrow","short","long"])||void 0!==c("day","string",["2-digit","numeric"])||
void 0!==c("weekday","string",["narrow","short","long"]);if(g&&d)return 2;if(d)return 1;if(g)return 0;c=c("formatType","string",["date","time","datetime"],"date");return"datetime"===c?2:"time"===c?1:0};ia=function(a,b){var c,d;switch(a){case 0:d=b.getFullYear()+"-"+e.Ve(b.getMonth()+1,2)+"-"+e.Ve(b.getDate(),2);break;case 1:d="T"+e.Ve(b.getHours(),2)+":"+e.Ve(b.getMinutes(),2)+":"+e.Ve(b.getSeconds(),2);c=b.getMilliseconds();0<c&&(d+="."+c);break;default:d=b.getFullYear()+"-"+e.Ve(b.getMonth()+1,
2)+"-"+e.Ve(b.getDate(),2)+"T"+e.Ve(b.getHours(),2)+":"+e.Ve(b.getMinutes(),2)+":"+e.Ve(b.getSeconds(),2),c=b.getMilliseconds(),0<c&&(d+="."+c)}return d};n=function(a,b,c,g){var h=e.Vj(g,"nu");void 0===e.Kg[h]&&(h="latn");if("latn"!==h){var m,u=[];for(m=0;m<a.length;m++){var s=e.Kg[h].indexOf(a[m]);-1!=s?u.push(s):u.push(a[m])}a=u.join("")}if(2>=arguments.length||void 0===c)c={year:"numeric",month:"numeric",day:"numeric"};h=p(c,"OraDateTimeConverter.parse");u=c.pattern||d(c,b,"OraDateTimeConverter.parse");
m={};if(!0===ya.test(a))return u=new Date(Date.parse(a)),m.value=ia(h,u),m;u=f(a,u,c,b);s=u.value;m.warning=u.warning;m.value=ia(h,s);return m};return{Mx:function(){x||(x=a());return x}}}();a.lc=function(a){this.Init(a)};o_("IntlNumberConverter",a.lc,a);a.b.sa(a.lc,a.$e,"oj.IntlNumberConverter");a.lc.prototype.Init=function(b){a.lc.t.Init.call(this,b)};a.b.g("IntlNumberConverter.prototype.Init",{Init:a.lc.prototype.Init});a.lc.prototype.rh=function(){this.eo||(this.eo=d.Mx());return this.eo};a.lc.prototype.format=
function(b){if(null==b||"string"===typeof b&&0===a.fb.trim(""+b).length||"number"===typeof b&&isNaN(b))return"";var c=a.Ga.jg(),d=a.ia.qe(),e=this.resolvedOptions();try{return this.rh().format(b,c,e,d)}catch(f){throw b=this.li(f,b),b;}};a.b.g("IntlNumberConverter.prototype.format",{format:a.lc.prototype.format});a.lc.prototype.Xb=function(){return a.lc.t.Xb.call(this)};a.b.g("IntlNumberConverter.prototype.getHint",{Xb:a.lc.prototype.Xb});a.lc.prototype.rf=function(){return a.lc.t.rf.call(this)};a.b.g("IntlNumberConverter.prototype.getOptions",
{rf:a.lc.prototype.rf});a.lc.prototype.parse=function(b){var c=a.Ga.jg(),d=a.ia.qe(),e=this.resolvedOptions();if(null==b||""===b)return null;try{return this.rh().parse(a.fb.trim(b),c,e,d)}catch(f){throw b=this.li(f,b),b;}};a.b.g("IntlNumberConverter.prototype.parse",{parse:a.lc.prototype.parse});a.lc.prototype.resolvedOptions=function(){var b,c=a.ia.qe();if(c!==this.Zk||!this.Un){b=a.Ga.jg();try{this.Un=this.rh().resolvedOptions(b,this.rf(),c),this.Zk=c}catch(d){throw b=this.li(d),b;}}return this.Un};
a.b.g("IntlNumberConverter.prototype.resolvedOptions",{resolvedOptions:a.lc.prototype.resolvedOptions});a.lc.prototype.li=function(b,c){var d=b.errorInfo,e,f,n;if(d)if(e=d.errorCode,d=d.parameterMap,a.i.oe(d),b instanceof TypeError){if("optionTypesMismatch"===e||"optionTypeInvalid"===e)f=a.IntlConverterUtils.Ak(e,d)}else b instanceof RangeError?"optionOutOfRange"===e&&(f=a.IntlConverterUtils.Ak(e,d)):b instanceof SyntaxError?"optionValueInvalid"===e&&(f=a.IntlConverterUtils.Ak(e,d)):b instanceof Error&&
("decimalFormatMismatch"===e?n="oj-converter.number.decimalFormatMismatch.summary":"currencyFormatMismatch"===e?n="oj-converter.number.currencyFormatMismatch.summary":"percentFormatMismatch"===e&&(n="oj-converter.number.percentFormatMismatch.summary"),n&&(e=a.ea.O(n,{value:c||d.value,format:d.format}),f=a.ea.O("oj-converter.hint.detail",{exampleValue:this.cv()}),f=new a.rd(e,f)));f||(f=e=b.message,f=new a.rd(e,f));return f};a.lc.prototype.cv=function(){var b="";try{b=this.format(12345.98765)}catch(c){c instanceof
a.rd&&(b="")}finally{return b}};var d;d=function(){function a(){return{format:function(a,b,d,e){if(2>=arguments.length||void 0===d)d={useGrouping:!0,style:"decimal"};t(d,"OraNumberConverter.format");var g={};r(b,g,d,e);return c(a,d,b,g,e)},parse:function(a,b,c,d){if("number"===typeof a)return a;if("[object Number]"===Object.prototype.toString.call(a))return Number(a);if(2>=arguments.length||void 0===c)c={useGrouping:!0,style:"decimal"};var g=a;t(c,"OraNumberConverter.parse");var h=e.Zd(b),p={},l=
e.Vj(d,"nu");void 0===e.Kg[l]&&(l="latn");if("latn"!==l){var k,u=[];for(k=0;k<a.length;k++){var s=e.Kg[l].indexOf(a[k]);-1!=s?u.push(s):u.push(a[k])}a=u.join("")}r(b,p,c,d);k=h.numbers[p.numberingSystem].decimal;l=h.numbers[p.numberingSystem].group;u=NaN;u=a.replace(/ /g,"");if(A.test(u))return u=parseFloat(a);var w=f(a,c,p,h),u=w[0],s=w[1],u=u||"+";if(w[2])return u=parseFloat(u+s),v(u,c,p,g);var s=s.replace(/ /g,""),z=p.exponential,y=s.indexOf(z.toLowerCase());0>y&&(y=s.indexOf(e.ce(z)));0>y?(w=
s,s=null):(w=s.substr(0,y),s=s.substr(y+z.length));y=w.indexOf(k);0>y?(z=w,k=null):(z=w.substr(0,y),k=w.substr(y+k.length));z=z.split(l).join("");w=l.replace(/\u00A0/g," ");l!==w&&(z=z.split(w).join(""));l=u+z;null!==k&&(l+="."+k);null!==s&&(k=q(s,h,p),l+="e"+(k[0]||"+")+k[1]);D.test(l)?u=parseFloat(l):(l=n(a,p,h),u=parseFloat(l[0]+l[1]));return v(u,c,p,g)},resolvedOptions:function(a,b,c){if(3>arguments.length||void 0===c)c=e.Dl(a);if(2>arguments.length||void 0===b)b={useGrouping:!0,style:"decimal"};
var d={};t(b,"OraNumberConverter.resolvedOptions");r(a,d,b,c);d.numberingSystemKey=e.Vj(c,"nu");void 0===e.Kg[d.numberingSystemKey]&&(d.numberingSystemKey="latn");d={locale:c,style:void 0===b.style?"decimal":b.style,useGrouping:void 0===b.useGrouping?!0:b.useGrouping,minimumIntegerDigits:d.minimumIntegerDigits,minimumFractionDigits:d.minimumFractionDigits,maximumFractionDigits:d.maximumFractionDigits,numberingSystem:d.numberingSystemKey};"currency"===b.style&&(d.currency=b.currency,d.currencyDisplay=
void 0===b.currencyDisplay?"symbol":b.currencyDisplay);void 0!==b.pattern&&(d.pattern=b.pattern);return d}}}var b,c,d,f,n,q,r,t,p,u,s,v,z,w,y,H,x,O,B,A=/^[+\-]?infinity$/i,D=/^[+\-]?\d*\.?\d*(e[+\-]?\d+)?$/,C=/([^+-.0-9]*)([+\-]?\d*\.?\d*(E[+\-]?\d+)?).*$/,I=/([\^\$\.\*\+\?\|\[\]\(\)\{\}])/g,P=/(^0\.0*)([^0].*$)/;b=function(a,b,c){var d;for(d=a.length;d<b;d+=1)a=c?"0"+a:a+"0";return a};u=function(a,b,c,d){var e=new RangeError(a+" is out of range.  Enter a value between "+b+" and "+c+" for "+d);e.errorInfo=
{errorCode:"numberOptionOutOfRange",parameterMap:{value:a,minValue:b,maxValue:c,propertyName:d}};throw e;};s=function(a,b,c,d,e){a=a[b];return void 0!==a?(a=Number(a),(isNaN(a)||a<c||a>d)&&u(a,c,d,b),Math.floor(a)):e};r=function(a,b,c,g){var f=e.Zd(a);g=e.jW(f,g);b.numberingSystemKey=g;b.numberingSystem="symbols-numberSystem-"+g;if(void 0!==c.pattern&&0<c.pattern.length)g=c.pattern;else{switch(c.style){case "decimal":g="decimalFormats-numberSystem-";break;case "currency":g="currencyFormats-numberSystem-";
break;case "percent":g="percentFormats-numberSystem-";break;default:g="decimalFormats-numberSystem-"}g+=b.numberingSystemKey;g=f.numbers[g].standard}a=e.Es(e.Dl(a)).language.language;b.lang=a;b.pat=g;b.minusSign=f.numbers[b.numberingSystem].minusSign;b.decimalSeparator=f.numbers[b.numberingSystem].decimal;b.exponential=f.numbers[b.numberingSystem].exponential;b.groupingSeparator=f.numbers[b.numberingSystem].group;b.currencyDisplay=c.currencyDisplay;void 0!==c.currency&&(b.currencyCode=c.currency.toUpperCase());
b.style=c.style;d(c,g,f,b);void 0===c.pattern&&(b.minimumIntegerDigits=s(c,"minimumIntegerDigits",1,21,b.minimumIntegerDigits),void 0!==c.maximumFractionDigits&&(b.maximumFractionDigits=s(c,"maximumFractionDigits",0,20,b.maximumFractionDigits),b.maximumFractionDigits<b.minimumFractionDigits&&(b.minimumFractionDigits=b.maximumFractionDigits)),void 0!==c.minimumFractionDigits&&(b.minimumFractionDigits=s(c,"minimumFractionDigits",0,20,b.minimumFractionDigits)),b.maximumFractionDigits<b.minimumFractionDigits&&
(b.maximumFractionDigits=b.minimumFractionDigits))};p=function(a){var b=new TypeError('The property "currency" is required whenthe property "'+a+'" is "currency". An accepted value is a three-letter ISO 4217 currency code.');b.errorInfo={errorCode:"optionTypesMismatch",parameterMap:{propertyName:a,propertyValue:"currency",requiredPropertyName:"currency",requiredPropertyValueValid:"a three-letter ISO 4217 currency code"}};throw b;};t=function(a,b){var c=e.Fh(a,b),d=c("style","string",["currency","decimal",
"percent","perMill"],"decimal"),c=c("currency","string");"currency"===d&&void 0===c&&p("style")};w=function(a,c){var d=a+"",e=0,g=d.split(/e/i),f=g[0];P.lastIndex=0;var p=P.exec(f);null!==p?(e=p[1].length-1,f=p[2]):f=f.replace(".","");var p=1<g.length?parseInt(g[1],10):0,g=parseInt(f,10),l=c.minimumIntegerDigits+c.maximumFractionDigits;f.length>l&&(l-=f.length,g=Math.round(g*Math.pow(10,l)));l=c.minimumIntegerDigits+c.minimumFractionDigits;g=b(g+"",l,!1);p=-1!==d.indexOf(".")?p-(c.minimumIntegerDigits-
d.indexOf(".")+e):p-(l-f.length-c.minimumFractionDigits);d=Math.abs(p);d=b(d+"",c.minExponentDigits,!0);0>p&&(d=c.minusSign+d);e=g.slice(0,c.minimumIntegerDigits);return e=0<g.slice(c.minimumIntegerDigits).length?e+(c.decimalSeparator+g.slice(c.minimumIntegerDigits)+c.exponential+d):e+(c.exponential+d)};z=function(a,c,d){var e=d.groupingSize,g,f=(a+"").split(/e/i),p=1<f.length?parseInt(f[1],10):0;g=f[0];var f=g.split("."),l=1<f.length?f[1]:"";if(1<f.length&&l.length>p){var k=Math.min(d.maximumFractionDigits,
l.length-p);g=Math.pow(10,k);g=Math.round(a*g)/g;isFinite(g)||(g=a);a=g}f=(a+"").split(/e/i);p=1<f.length?parseInt(f[1],10):0;g=f[0];f=g.split(".");g=f[0];l=1<f.length?f[1]:"";0<p?(l=b(l,p,!1),g+=l.slice(0,p),l=l.substr(p)):0>p&&(p=-p,g=b(g,p+1,!0),l=g.slice(-p,g.length)+l,g=g.slice(0,-p));l=0<k?d.decimalSeparator+(l.length>k?l.slice(0,k):b(l,k,!1)):0<d.minimumFractionDigits?d.decimalSeparator:"";l=b(l,d.decimalSeparator.length+d.minimumFractionDigits,!1);a=d.groupingSeparator;k="";!1===c.useGrouping&&
void 0===c.pattern&&(a="");g=b(g,d.minimumIntegerDigits,!0);c=g.length-1;for(l=1<l.length?l:"";0<=c;){if(0===e||e>c)return e=g.slice(0,c+1)+(k.length?a+k+l:l);k=g.slice(c-e+1,c+1)+(k.length?a+k:"");c-=e}return e=g.slice(0,c+1)+a+k+l};c=function(a,b,c,d,g){c=e.Zd(c);if(!isFinite(a))return Infinity===a||-Infinity===a?c.numbers[d.numberingSystem].infinity:c.numbers[d.numberingSystem].nan;c=Math.abs(a);!0===d.isPercent||"percent"===b.style?c*=100:!0===d.isPerMill&&(c*=1E3);c=!0==d.useExponentialNotation?
w(c,d):z(c,b,d);b="";b=0>a?b+(d.negativePrefix+c+d.negativeSuffix):b+(d.positivePrefix+c+d.positiveSuffix);a=e.Vj(g,"nu");void 0===e.Kg[a]&&(a="latn");if("latn"!==a){g=[];for(d=0;d<b.length;d++)"0"<=b[d]&&"9">=b[d]?g.push(e.Kg[a][b[d]]):g.push(b[d]);return g.join("")}return b};f=function(a,b,c,d){a=e.Ng(a);var g="",f=!1,h=new RegExp("^"+d.numbers[c.numberingSystem].plusSign.replace(I,"\\$1"));a=a.replace(h,"");var p=e.Ng(c.positivePrefix),l=e.Ng(c.positiveSuffix),k=e.Ng(c.negativePrefix),h=e.Ng(c.negativeSuffix),
m=new RegExp("^"+(p||"").replace(I,"\\$1")),u=new RegExp((l||"").replace(I,"\\$1")+"$"),s=new RegExp("^"+(k||"").replace(I,"\\$1")),v=new RegExp((h||"").replace(I,"\\$1")+"$");if(!0==s.test(a)&&!0==v.test(a))a=a.replace(s,""),a=a.replace(v,""),g="-",f=!0;else if(!0==m.test(a)&&!0==u.test(a))a=a.replace(m,""),a=a.replace(u,""),g="+",f=!0;else if("currency"===b.style){b=m=c.currencyCode;var r;void 0!==d.numbers.currencies[m]&&(b=d.numbers.currencies[m].symbol);void 0===c.currencyDisplay||"symbol"===
c.currencyDisplay?r=b:"code"===c.currencyDisplay&&(r=m);void 0!==r&&(m=(p||"").replace(r,""),l=(l||"").replace(r,""),k=(k||"").replace(r,""),r=(h||"").replace(r,""),m=new RegExp(("^"+m).replace(I,"\\$1")),u=new RegExp(l.replace(I,"\\$1")+"$"),s=new RegExp(("^"+k).replace(I,"\\$1")),v=new RegExp(r.replace(I,"\\$1")+"$"),!0==s.test(a)&&!0==v.test(a)?(a=a.replace(s,""),a=a.replace(v,""),g="-",f=!0):!0==m.test(a)&&!0==u.test(a)&&(a=a.replace(m,""),a=a.replace(u,""),g="+",f=!0))}f?c=[g,a]:(c=n(a,c,d),
c[2]=!0);return c};n=function(a,b,c){var d=c.numbers[b.numberingSystem].group,g=c.numbers[b.numberingSystem].decimal,f="",h="";b=e.ce(c.numbers[b.numberingSystem].exponential);a=e.ce(a);a=a.split(b).join("E");a=a.split(d).join("");b=d.replace(/\u00A0/g," ");d!==b&&(a=a.split(b).join(""));a=a.split(g).join(".");"."===a.charAt(0)&&(a=a.substr(1),h=".");d=C.exec(a);h+=d[2];e.Zo(h,"-")?(h=h.substr(1),f="-"):e.Zo(a,"+")&&(h=h.substr(1),f="+");return[f,h]};q=function(a,b,c){var d=b.numbers[c.numberingSystem].minusSign;
b=b.numbers[c.numberingSystem].plusSign;var g;a=e.Ng(a);d=e.Ng(d);b=e.Ng(b);e.Zo(a,d)?g=["-",a.substr(d.length)]:e.Zo(a,e.Ng(b))&&(g=["+",a.substr(b.length)]);return g||["",a]};var F,G,N,J;B=function(a){var b;b=new SyntaxError('Unexpected character(s) encountered in the pattern "'+a+' An example of a valid pattern is "#,##0.###".');b.errorInfo={errorCode:"optionValueInvalid",parameterMap:{propertyName:"pattern",propertyValue:a,propertyValueHint:"#,##0.###"}};throw b;};H=function(a,b,c){return null!==
(new RegExp(c,"i")).exec(a.substr(b,c.length))};O=function(a,b){var c={};null!=F&&(b.positivePrefix=x(F,a,b,c));null!=G&&(b.positiveSuffix=x(G,a,b,c));null!=N&&(b.negativePrefix=x(N,a,b,c));null!=J&&(b.negativeSuffix=x(J,a,b,c));void 0!==c.name&&(b.positiveSuffix="\u00a0"+c.name,b.positivePrefix="","ar"===b.lang?(b.negativeSuffix=a.numbers[b.numberingSystem].minusSign+"\u00a0"+c.name,b.negativePrefix=""):(b.negativeSuffix="\u00a0"+c.name,b.negativePrefix=a.numbers[b.numberingSystem].minusSign))};
x=function(a,b,c,d){for(var e="",g=0;g<a.length;){var f=a.charAt(g++);if("'"!=f){switch(f){case "\u00a4":var h=f=c.currencyCode,p=f;void 0!==b.numbers.currencies[f]&&(h=b.numbers.currencies[f].displayName,p=b.numbers.currencies[f].symbol);void 0===c.currencyDisplay||"symbol"===c.currencyDisplay?f=p:"code"!==c.currencyDisplay&&(f=h,d.name=f);break;case "%":f=b.numbers[c.numberingSystem].percentSign;break;case "\u2030":f=b.numbers[c.numberingSystem].perMille;break;case "-":f=b.numbers[c.numberingSystem].minusSign}e=
e.concat(f)}}return e};d=function(a,b,c,d){for(var e=!1,g=!1,f=0,h=0,l=!0,k=1;0<=k&&h<b.length;--k){for(var m=!1,u="",s="",n=-1,v=1,r=0,t=0,q=0,w=-1,z,y=0,l=!0,x=h;x<b.length;++x){var A=b.charAt(x);switch(y){case 0:case 2:if(m){if("'"===A){x+1<b.length&&"'"===b.charAt(x+1)?(++x,l?u=u.concat("''"):s=s.concat("''")):m=!1;continue}}else if("#"===A||"0"===A||","===A||"."===A){y=1;--x;continue}else if("\u00a4"===A){void 0===a.currency&&p("pattern");a.style="currency";(A=x+1<b.length&&"\u00a4"===b.charAt(x+
1))&&++x;l?u=u.concat(A?"'\u00a4\u00a4":"'\u00a4"):s=s.concat(A?"'\u00a4\u00a4":"'\u00a4");continue}else if("'"===A){if("'"==A){x+1<b.length&&"'"==b.charAt(x+1)?(++x,l?u=u.concat("''"):s=s.concat("''")):m=!0;continue}}else if(";"===A){0!==y&&0!==k||B(b);h=x+1;x=b.length;continue}else if("%"===A){a.style="percent";1!=v&&B(b);d.isPercent=!0;v=100;l?u=u.concat("'%"):s=s.concat("'%");continue}else if("\u2030"===A){1!=v&&B(b);a.style="perMill";d.isPerMill=!0;v=1E3;l?u=u.concat("'\u2030"):s=s.concat("'\u2030");
continue}else if("-"===A){l?u=u.concat("'-"):s=s.concat("'-");continue}l?u=u.concat(A):s=s.concat(A);break;case 1:if(1===k)++f;else{0===--f&&(y=2,l=!1);continue}if("#"===A)0<t?++q:++r,0<=w&&0>n&&++w;else if("0"===A)0<q&&B(b),++t,0<=w&&0>n&&++w;else if(","===A)w=0;else if("."===A)0<=n&&B(b),n=r+t+q;else if(H(b,x,"E")){g&&B(b);g=!0;z=0;for(x+=1;x<b.length&&"0"===b.charAt(x);)++z,++f,++x;(1>r+t||1>z)&&B(b);y=2;l=!1;--x}else y=2,l=!1,--x,--f}}0===t&&0<r&&0<=n&&(t=n,0===t&&++t,q=r-t,r=t-1,t=1);(0>n&&0<
q||0<=n&&(n<r||n>r+t)||0==w||m)&&B(b);1===k?(F=u,G=s,N=F,J=G,m=r+t+q,d.minimumIntegerDigits=(0<=n?n:m)-r,d.maximumIntegerDigits=g?r+d.minimumIntegerDigits:2147483647,d.maximumFractionDigits=0<=n?m-n:0,d.minimumFractionDigits=0<=n?r+t-n:0,d.groupingSize=0<w?w:0):(N=u,J=s,e=!0)}0==b.length&&(F=G="",d.minimumIntegerDigits=0,d.maximumIntegerDigits=2147483647,d.minimumFractionDigits=0,d.maximumFractionDigits=2147483647);d.useExponentialNotation=g;d.minExponentDigits=z;if(!e||0==N.localeCompare(F)&&0==
J.localeCompare(G))"currency"===a.style&&"ar"===d.lang?(J=G+"'\u200f-",N=F):(J=G,N="'-"+F);O(c,d)};v=function(a,b,c,d){if(isNaN(a)){var e;a="Unparsable number "+d+" The expected number pattern is "+c.pat;switch(b.style){case "decimal":e="decimalFormatMismatch";break;case "currency":e="currencyFormatMismatch";break;case "percent":e="percentFormatMismatch"}b=Error(a);b.errorInfo={errorCode:e,parameterMap:{value:d,format:c.pat}};throw b;}!0===c.isPercent||"percent"===b.style?a/=100:!0===c.isPerMill&&
(a/=1E3);return a};return{Mx:function(){y||(y=a());return y}}}();a.Sg=function(a){this.Init(a)};o_("DateRestrictionValidator",a.Sg,a);a.b.sa(a.Sg,a.Nd,"oj.DateRestrictionValidator");a.Sg.prototype.Init=function(b){a.Sg.t.Init.call(this);this.pO=b.dayFormatter;this.Ub=a.IntlConverterUtils.getConverterInstance(b.converter);b&&(this.oO=b.message||{})};a.b.g("DateRestrictionValidator.prototype.Init",{Init:a.Sg.prototype.Init});a.Sg.prototype.cR=function(a){var b=this.pO;if(b){var c=a.getFullYear(),d=
a.getMonth()+1;a=a.getDate();return(b=b({fullYear:c,month:d,date:a}))&&b.disabled}return!1};a.Sg.prototype.validate=function(b){var c="",d="",d=a.ea,c=this.oO,e=b?this.Ub.format(b):b,f=e?a.IntlConverterUtils.isoToLocalDate(e):null;if(null===b)return b;if(this.cR(f))throw b=c.messageDayMetaData,c=d.O("oj-validator.restriction.date.dayMetaData.summary"),d=b?d.ub(b,{value:e}):d.O("oj-validator.restriction.date.dayMetaData.detail",{value:e}),new a.ze(c,d);return b};a.b.g("DateRestrictionValidator.prototype.validate",
{validate:a.Sg.prototype.validate});a.vd=function(a){this.Init(a)};o_("RegExpValidator",a.vd,a);a.b.sa(a.vd,a.Nd,"oj.RegExpValidator");a.vd.Ys="oj-validator.regExp.detail";a.vd.Zs="oj-validator.regExp.summary";a.vd.prototype.Init=function(b){a.vd.t.Init.call(this);this.Wa=b};a.b.g("RegExpValidator.prototype.Init",{Init:a.vd.prototype.Init});a.vd.prototype.validate=function(b){var c=this.Wa&&this.Wa.pattern||"",d,e,f;if(null===b||void 0===b||""===b)return!0;b=b?b.toString():b;var n;n=b.match("^("+
c+")$");if(null===n||n[0]!==b)throw this.Wa&&(e=this.Wa.messageSummary||null,f=this.Wa.messageDetail||null,d=this.Wa&&this.Wa.label||""),b={label:d,pattern:c,value:b},e=e?a.ea.ub(e,b):a.ea.O(this.Cv(),b),f=f?a.ea.ub(f,b):a.ea.O(this.Vu(),b),new a.ze(e,f);return!0};a.b.g("RegExpValidator.prototype.validate",{validate:a.vd.prototype.validate});a.vd.prototype.Xb=function(){var b=null,c={};this.Wa&&this.Wa.hint&&(c={pattern:this.Wa.pattern},b=a.ea.ub(this.Wa.hint,c));return b};a.b.g("RegExpValidator.prototype.getHint",
{Xb:a.vd.prototype.Xb});a.vd.prototype.Cv=function(){return a.vd.Zs};a.vd.prototype.Vu=function(){return a.vd.Ys};a.La=function(a){this.Init(a)};o_("IntlDateTimeConverter",a.La,a);a.b.sa(a.La,a.xb,"oj.IntlDateTimeConverter");a.La.tK=(new Date(1998,10,29,15,45,31)).toISOString();a.La.prototype.Init=function(b){a.La.t.Init.call(this,b)};a.b.g("IntlDateTimeConverter.prototype.Init",{Init:a.La.prototype.Init});a.La.prototype.rh=function(){this.eo||(this.eo=b.Mx());return this.eo};a.La.prototype.format=
function(b){var c=a.Ga.jg(),d=a.ia.qe(),e=this.resolvedOptions();if(null==b||"string"===typeof b&&0===a.fb.trim(""+b).length)return"";try{return this.rh().format(b,c,e,d)}catch(f){throw b=this.li(f,b),b;}};a.b.g("IntlDateTimeConverter.prototype.format",{format:a.La.prototype.format});a.La.prototype.ls=function(b,c){var d=a.Ga.jg(),e=a.ia.qe();try{return this.rh().ls(b,d,c,e)}catch(f){throw d=this.li(f,b),d;}};a.b.g("IntlDateTimeConverter.prototype.formatRelative",{ls:a.La.prototype.ls});a.La.prototype.Xb=
function(){var a=this.resolvedOptions().patternFromOptions;return a?a:""};a.b.g("IntlDateTimeConverter.prototype.getHint",{Xb:a.La.prototype.Xb});a.La.prototype.cv=function(){var b="";try{b=this.format(a.La.tK)}catch(c){c instanceof a.rd&&(b="")}finally{return b}};a.La.prototype.rf=function(){return a.La.t.rf.call(this)};a.b.g("IntlDateTimeConverter.prototype.getOptions",{rf:a.La.prototype.rf});a.La.prototype.resolvedOptions=function(){var b,c=a.ia.qe(),d=this.rf();if(c!==this.Zk||!this.Un){b=a.Ga.jg();
try{this.Un=this.rh().resolvedOptions(b,d,c),this.Zk=c}catch(e){throw b=this.li(e),b;}}return this.Un};a.b.g("IntlDateTimeConverter.prototype.resolvedOptions",{resolvedOptions:a.La.prototype.resolvedOptions});a.La.prototype.Go=function(){var a=this.resolvedOptions(),b=a.hour12;return a.hour&&!b?!0:!1};a.b.g("IntlDateTimeConverter.prototype.isHourInDaySet",{Go:a.La.prototype.Go});a.La.prototype.Fo=function(){var a=this.resolvedOptions(),b=a.hour12;return a.hour&&b?!0:!1};a.b.g("IntlDateTimeConverter.prototype.isHourInAMPMSet",
{Fo:a.La.prototype.Fo});a.La.prototype.Jo=function(){return this.Dj("minute")};a.b.g("IntlDateTimeConverter.prototype.isMinuteSet",{Jo:a.La.prototype.Jo});a.La.prototype.Lo=function(){return this.Dj("second")};a.b.g("IntlDateTimeConverter.prototype.isSecondSet",{Lo:a.La.prototype.Lo});a.La.prototype.Io=function(){return this.Dj("millisecond")};a.b.g("IntlDateTimeConverter.prototype.isMilliSecondSet",{Io:a.La.prototype.Io});a.La.prototype.Mo=function(){return this.Dj("year")};a.b.g("IntlDateTimeConverter.prototype.isYearSet",
{Mo:a.La.prototype.Mo});a.La.prototype.Ko=function(){return this.Dj("month")};a.b.g("IntlDateTimeConverter.prototype.isMonthSet",{Ko:a.La.prototype.Ko});a.La.prototype.Eo=function(){return this.Dj("day")};a.b.g("IntlDateTimeConverter.prototype.isDaySet",{Eo:a.La.prototype.Eo});a.La.prototype.Do=function(){return this.Dj("weekday")};a.b.g("IntlDateTimeConverter.prototype.isDayNameSet",{Do:a.La.prototype.Do});a.La.prototype.jo=function(b){return this.rh().jo(b,a.Ga.jg(),a.ia.qe())};a.b.g("IntlDateTimeConverter.prototype.calculateWeek",
{jo:a.La.prototype.jo});a.La.prototype.parse=function(b){var c,d;if(null==b||""===b)return null;var e=a.Ga.jg(),f=a.ia.qe(),n=this.resolvedOptions();try{return c=this.rh().parse(b,e,n,f),(d=c.value)&&c.warning&&a.D.warn("The value "+b+" was leniently parsed to represent a date "+d.toString?d.toString():d),d}catch(q){throw b=this.li(q,b),b;}};a.b.g("IntlDateTimeConverter.prototype.parse",{parse:a.La.prototype.parse});a.La.prototype.li=function(b,c){var d=b.errorInfo,e,f,n,q;if(d)if(e=d.errorCode,d=
d.parameterMap,a.i.oe(d),n=d.propertyName,b instanceof TypeError){if("optionTypesMismatch"===e||"optionTypeInvalid"===e)f=a.IntlConverterUtils.Ak(e,d)}else b instanceof RangeError?"optionOutOfRange"===e?f=a.IntlConverterUtils.Ak(e,d):"datetimeOutOfRange"===e&&(e=a.ea.O("oj-converter.datetime.datetimeOutOfRange.summary",{propertyName:n,value:d.value}),f=a.ea.O("oj-converter.datetime.datetimeOutOfRange.detail",{minValue:d.minValue,maxValue:d.maxValue}),f=new a.rd(e,f)):b instanceof SyntaxError?"optionValueInvalid"===
e&&(f=a.IntlConverterUtils.Ak(e,d)):b instanceof Error&&("dateFormatMismatch"===e?q="oj-converter.datetime.dateFormatMismatch.summary":"timeFormatMismatch"===e?q="oj-converter.datetime.timeFormatMismatch.summary":"datetimeFormatMismatch"===e?q="oj-converter.datetime.datetimeFormatMismatch.summary":"dateToWeekdayMismatch"===e&&(e=a.ea.O("oj-converter.datetime.dateToWeekdayMismatch.summary",{date:d.date,weekday:d.weekday}),f=a.ea.O("oj-converter.datetime.dateToWeekdayMismatch.detail"),f=new a.rd(e,
f)),q&&(e=a.ea.O(q,{value:c||d.value,format:d.format}),f=a.ea.O("oj-converter.hint.detail",{exampleValue:this.cv()}),f=new a.rd(e,f)));f||(f=e=b.message,f=new a.rd(e,f));return f};a.La.prototype.Dj=function(a){return this.resolvedOptions()[a]?!0:!1};var e={Kg:{latn:"0123456789",arab:"\u0660\u0661\u0662\u0663\u0664\u0665\u0666\u0667\u0668\u0669",thai:"\u0e50\u0e51\u0e52\u0e53\u0e54\u0e55\u0e56\u0e57\u0e58\u0e59"},DJ:/^(?:(en-GB-oed|i-(?:ami|bnn|default|enochian|hak|klingon|lux|mingo|navajo|pwn|tao|tay|tsu)|sgn-(?:BE-FR|BE-NL|CH-DE))|(art-lojban|cel-gaulish|no-(?:bok|nyn)|zh-(?:guoyu|hakka|min|min-nan|xiang)))$|^(x(?:-[0-9a-z]{1,8})+)$|^(?:((?:[a-z]{2,3}(?:(?:-[a-z]{3}){1,3})?)|[a-z]{4}|[a-z]{5,8})(?:-([a-z]{4}))?(?:-([a-z]{2}|[0-9]{3}))?((?:-(?:[a-z0-9]{5,8}|[0-9][a-z0-9]{3}))*)?((?:-[0-9a-wy-z](?:-[a-z0-9]{2,8}){1,})*)?(-x(?:-[0-9a-z]{1,8})+)?)$/i,
$W:/^\s+|\s+$|\u200f|\u200e/g,aX:/\s+|\u200f|\u200e/g,HX:["0","00","000"],isoToLocalDate:function(a){if(!a||"string"!==typeof a)return null;var b=new Date(a),c=a.indexOf("T");-1===c?b=new Date(b.getUTCFullYear(),b.getUTCMonth(),b.getUTCDate()):"Invalid Date"===b.toString()&&0===c&&(b=(new Date).toISOString(),a=b.substring(0,b.indexOf("T"))+a,b=new Date(a));return b},trim:function(a){return(a+"").replace(e.$W,"")},Ng:function(a){return(a+"").replace(e.aX,"")},Zo:function(a,b){return 0===a.indexOf(b)},
ce:function(a){return a.split("\u00a0").join(" ").toUpperCase()},Ve:function(a,b){var c;c=a+"";return 1<b&&c.length<b?(c=e.HX[b-2]+c,c.substr(c.length-b,b)):c},jW:function(a,b){if(void 0===b)return"latn";var c=e.Vj(b,"nu")||"";void 0===a.numbers["symbols-numberSystem-"+c]&&(c="latn");return c},Es:function(a){a=e.DJ.exec(a);if(!a)return null;var b=a[4],b=b?b.split("-"):null,c=null;b&&(c=b.shift());var d=a[7];(d=d?d.split("-"):null)&&d.shift();var f=a[9];if(f=f?f.split("-"):null)f.shift(),f.shift();
var n=a[3];(n=n?n.split("-"):null)&&n.shift();return{language:{language:c,OY:b||[]},eZ:a[5]||null,region:a[6]||null,variant:d||null,NY:e.VW(a[8]),bZ:f||n||[],QY:{TY:a[1]||null,cZ:a[2]||null}}},VW:function(a){if(!a)return[];for(var b=[],c,d,e=!1,f=!1,q="",r=!1,t=0,p=a.length;t<p;t++)d=a[t],"-"!==d||e?e&&!f?(f=!0,c.singleton=d):"-"===d?r?1===q.length?(f=r=!1,b.push(c),c={singleton:null,extension:[]}):(c.extension.push(q),q=""):(q="",r=!0):q+=d:(e=!0,c={singleton:null,extension:[]});c.extension.push(q);
b.push(c);return b},Vj:function(a,b){var c=e.Es(a||"en-US");if(null===c||void 0===c)return null;var c=c.extension,d,f;for(f in c)if("u"===c[f].singleton){for(var n in c[f].extension)if(c[f].extension[n]===b){n++;d=c[f].extension[n];break}break}return d},Zd:function(a){a=a.main;var b,c;for(c in a){b=c;break}return a[b]},Dl:function(a){a=a.main;var b,c;for(c in a){b=c;break}return b},Fh:function(a,b){if(void 0===a)throw Error("Internal "+b+" error. Default options missing.");return function(c,d,e,f){if(void 0!==
a[c]){f=a[c];switch(d){case "boolean":f=Boolean(f);break;case "string":f=String(f);break;case "number":f=Number(f);break;default:throw Error("Internal error. Wrong value type.");}if(void 0!==e&&-1===e.indexOf(f)){d=[];for(f=0;f<e.length;f++)d.push(e[f]);e=new RangeError("The value '"+a[c]+"' is out of range for '"+b+"' options property '"+c+"'. Valid values: "+d);e.errorInfo={errorCode:"optionOutOfRange",parameterMap:{propertyName:c,propertyValue:a[c],propertyValueValid:d,caller:b}};throw e;}}return f}}};
a.$f=function(a){this.Init(a)};o_("DateTimeRangeValidator",a.$f,a);a.b.sa(a.$f,a.Nd,"oj.DateTimeRangeValidator");a.$f.prototype.Init=function(b){a.$f.t.Init.call(this);this.Ub=a.IntlConverterUtils.getConverterInstance(b.converter);this.le=b.min?a.IntlConverterUtils.isoToLocalDate(b.min):null;this.Ie=b.max?a.IntlConverterUtils.isoToLocalDate(b.max):null;b&&(this.qn=b.hint||{},this.Tm=b.messageSummary||{},this.Sm=b.messageDetail||{})};a.b.g("DateTimeRangeValidator.prototype.Init",{Init:a.$f.prototype.Init});
a.$f.prototype.validate=function(b){var c=this.Tm,d=this.Sm,e=d.rangeOverflow,d=d.rangeUnderflow,f=c.rangeOverflow,c=c.rangeUnderflow,n=this.le,q=this.Ie,r="",t="",p=a.ea,u=null,s=(u=b?this.Ub.format(b):b)?a.IntlConverterUtils.isoToLocalDate(b):null,v=n&&this.Ub?this.Ub.format(n.toISOString()):n,z=q&&this.Ub?this.Ub.format(q.toISOString()):q;if(null===b)return b;if(null!==n&&null!==q){if(s>=n&&s<=q||n>q)return b}else if(null!==n){if(s>=n)return b}else if(null===q||s<=q)return b;null!==q&&s>q?(u={value:u,
max:z},r=f?f:p.O("oj-validator.range.datetime.messageSummary.rangeOverflow"),t=e?p.ub(e,u):p.O("oj-validator.range.datetime.messageDetail.rangeOverflow",u)):null!==n&&s<n&&(u={value:u,min:v},r=c?c:p.O("oj-validator.range.datetime.messageSummary.rangeUnderflow"),t=d?p.ub(d,u):p.O("oj-validator.range.datetime.messageDetail.rangeUnderflow",u));throw new a.ze(r,t);};a.b.g("DateTimeRangeValidator.prototype.validate",{validate:a.$f.prototype.validate});a.$f.prototype.Xb=function(){var b=null,c=this.qn,
d=c.inRange,e=c.min,c=c.max,f=this.le,n=this.Ie,q=f&&this.Ub?this.Ub.format(f.toISOString()):f,r=n&&this.Ub?this.Ub.format(n.toISOString()):n,t=null,p=a.ea;null!==f&&null!==n?(t={min:q,max:r},b=d?p.ub(d,t):p.O("oj-validator.range.datetime.hint.inRange",t)):null!==f?(t={min:q},b=e?p.ub(e,t):p.O("oj-validator.range.datetime.hint.min",t)):null!==n&&(t={max:r},b=c?p.ub(c,t):p.O("oj-validator.range.datetime.hint.max",t));return b};a.b.g("DateTimeRangeValidator.prototype.getHint",{Xb:a.$f.prototype.Xb});
a.wd=function(a){this.Init(a)};o_("RequiredValidator",a.wd,a);a.b.sa(a.wd,a.Nd,"oj.RequiredValidator");a.wd.Ys="oj-validator.required.detail";a.wd.Zs="oj-validator.required.summary";a.wd.prototype.Init=function(b){a.wd.t.Init.call(this);this.Wa=b};a.b.g("RequiredValidator.prototype.Init",{Init:a.wd.prototype.Init});a.wd.prototype.validate=function(b){var c,d,e={},e="";if("number"===typeof b&&0===b||b&&0!==b.length)return!0;this.Wa&&(c=this.Wa.messageDetail||this.Wa.message||null,d=this.Wa.messageSummary||
null,e=this.Wa.label||"");e={label:e};b=d?a.ea.ub(d,e):a.ea.O(this.Cv(),e);c=c?a.ea.ub(c,e):a.ea.O(this.Vu(),e);throw new a.ze(b,c);};a.b.g("RequiredValidator.prototype.validate",{validate:a.wd.prototype.validate});a.wd.prototype.Xb=function(){var b="";this.Wa&&this.Wa.hint&&(b=a.ea.O(this.Wa.hint));return b};a.b.g("RequiredValidator.prototype.getHint",{Xb:a.wd.prototype.Xb});a.wd.prototype.Cv=function(){return a.wd.Zs};a.wd.prototype.Vu=function(){return a.wd.Ys};a.Vg=function(a){this.Init(a)};o_("LengthValidator",
a.Vg,a);a.b.sa(a.Vg,a.Nd,"oj.LengthValidator");a.Vg.prototype.Init=function(b){a.Vg.t.Init.call(this);this.le=b.min;this.Ie=b.max;b&&(this.qn=b.hint||{},this.Tm=b.messageSummary||{},this.Sm=b.messageDetail||{})};a.b.g("LengthValidator.prototype.Init",{Init:a.Vg.prototype.Init});a.Vg.prototype.Xb=function(){var b=null,c=this.qn,d=c.inRange,e=c.min,f=c.max,c=c.exact,n=a.ea,q=void 0!==this.le?parseInt(this.le,10):null,r=void 0!==this.Ie?parseInt(this.Ie,10):null;null!==q&&null!==r?q!==r?(b={min:q,max:r},
b=d?n.ub(d,b):n.O("oj-validator.length.hint.inRange",b)):(b={length:q},b=c?n.ub(c,b):n.O("oj-validator.length.hint.exact",b)):null!==q?(b={min:q},b=e?n.ub(e,b):n.O("oj-validator.length.hint.min",b)):null!==r&&(b={max:r},b=f?n.ub(f,b):n.O("oj-validator.length.hint.max",b));return b};a.Vg.prototype.validate=function(b){var c="",d="",c=""+b,e=c.length,f=this.Sm,n=this.Tm,d=f.tooShort,f=f.tooLong,q=n.tooShort,r=n.tooLong,n=a.ea,t=void 0!==this.le?parseInt(this.le,10):null,p=void 0!==this.Ie?parseInt(this.Ie,
10):null;if((null===t||e>=this.le)&&(null===p||e<=this.Ie))return c;e<this.le?(b={value:b,min:t},c=q?n.ub(q,b):n.O("oj-validator.length.messageSummary.tooShort"),d=d?n.ub(d,b):n.O("oj-validator.length.messageDetail.tooShort",b)):(b={value:b,max:p},c=r?n.ub(r,b):n.O("oj-validator.length.messageSummary.tooLong"),d=f?n.ub(f,b):n.O("oj-validator.length.messageDetail.tooLong",b));throw new a.ze(c,d);};a.b.g("LengthValidator.prototype.validate",{validate:a.Vg.prototype.validate});a.bg=function(a){this.Init(a)};
o_("NumberRangeValidator",a.bg,a);a.b.sa(a.bg,a.Nd,"oj.NumberRangeValidator");a.bg.prototype.Init=function(b){a.bg.t.Init.call(this);b&&(this.le=b.min,this.Ie=b.max,this.Ub=a.IntlConverterUtils.getConverterInstance(b.converter),this.qn=b.hint||{},this.Tm=b.messageSummary||{},this.Sm=b.messageDetail||{})};a.b.g("NumberRangeValidator.prototype.Init",{Init:a.bg.prototype.Init});a.bg.prototype.validate=function(b){var c=b?b.toString():b,d=parseFloat(c),e=this.Tm,f=this.Sm,n=f.rangeOverflow,f=f.rangeUnderflow,
q=e.rangeOverflow,e=e.rangeUnderflow,r=void 0!==this.le?parseFloat(this.le):null,t=void 0!==this.Ie?parseFloat(this.Ie):null,p=r&&this.Ub?this.Ub.format(r):r,u=t&&this.Ub?this.Ub.format(t):t,s="",v="",z=null,w=a.ea;if(null===b)return b;if(null!==r&&null!==t){if(d>=r&&d<=t||r>t)return c}else if(null!==r){if(d>=r)return c}else if(null===t||d<=t)return c;null!==t&&d>t?(z={value:b,max:u},s=q?q:w.O("oj-validator.range.number.messageSummary.rangeOverflow"),v=n?w.ub(n,z):w.O("oj-validator.range.number.messageDetail.rangeOverflow",
z)):null!==r&&d<r&&(z={value:b,min:p},s=e?e:w.O("oj-validator.range.number.messageSummary.rangeUnderflow"),v=f?w.ub(f,z):w.O("oj-validator.range.number.messageDetail.rangeUnderflow",z));throw new a.ze(s,v);};a.b.g("NumberRangeValidator.prototype.validate",{validate:a.bg.prototype.validate});a.bg.prototype.Xb=function(){var b=null,c=this.qn,d=c.inRange,e=c.min,c=c.max,f=a.ea,n=void 0!==this.le?parseFloat(this.le):null,q=void 0!==this.Ie?parseFloat(this.Ie):null,r=n&&this.Ub?this.Ub.format(n):n,t=q&&
this.Ub?this.Ub.format(q):q;null!==n&&null!==q?b=d?f.ub(d,{min:r,max:t}):f.O("oj-validator.range.number.hint.inRange",{min:r,max:t}):null!==n?b=e?f.ub(e,{min:r}):f.O("oj-validator.range.number.hint.min",{min:r}):null!==q&&(b=c?f.ub(c,{max:t}):f.O("oj-validator.range.number.hint.max",{max:t}));return b};a.b.g("NumberRangeValidator.prototype.getHint",{Xb:a.bg.prototype.Xb});a.ZJ=function(){return{createConverter:function(b){return new a.lc(b)}}}();a.ca.FA(a.Zf.CONVERTER_TYPE_NUMBER,a.ZJ);a.JJ=function(){return{createConverter:function(b){return new a.La(b)}}}();
a.ca.FA(a.Zf.CONVERTER_TYPE_DATETIME,a.JJ);a.cK=function(){return{createValidator:function(b){return new a.wd(b)}}}();a.ca.Bk(a.Tb.VALIDATOR_TYPE_REQUIRED,a.cK);a.bK=function(){return{createValidator:function(b){return new a.vd(b)}}}();a.ca.Bk(a.Tb.VALIDATOR_TYPE_REGEXP,a.bK);a.KJ=function(){return{createValidator:function(b){return new a.$f(b)}}}();a.ca.Bk(a.Tb.VALIDATOR_TYPE_DATETIMERANGE,a.KJ);a.IJ=function(){return{createValidator:function(b){return new a.Sg(b)}}}();a.ca.Bk(a.Tb.VALIDATOR_TYPE_DATERESTRICTION,
a.IJ);a.$J=function(){return{createValidator:function(b){return new a.bg(b)}}}();a.ca.Bk(a.Tb.VALIDATOR_TYPE_NUMBERRANGE,a.$J);a.SJ=function(){return{createValidator:function(b){return new a.Vg(b)}}}();a.ca.Bk(a.Tb.VALIDATOR_TYPE_LENGTH,a.SJ);a.IntlConverterUtils={};a.IntlConverterUtils.isoToLocalDate=function(a){return e.isoToLocalDate(a)};a.IntlConverterUtils.getConverterInstance=function(b){var c="",d={},e=null;b&&("object"===typeof b&&(b instanceof a.Mc||b.parse&&"function"===typeof b.parse||
b.format&&"function"===typeof b.format?e=b:(c=b.type,d=b.options||{})),e||(c=c||b)&&"string"===typeof c&&(b=a.ca.yi(c),e=b.createConverter(d)));return e};a.IntlConverterUtils.Ak=function(b,c){a.i.oe(c);var d="",e="",f=c.propertyName,n;"optionTypesMismatch"===b?(e=c.requiredPropertyName,n=c.requiredPropertyValueValid,d=a.ea.O("oj-converter.optionTypesMismatch.summary",{propertyName:f,propertyValue:c.propertyValue,requiredPropertyName:e}),e=a.IntlConverterUtils.Jq(e,n)):"optionTypeInvalid"===b?(f=c.propertyName,
n=c.propertyValueValid,d=a.ea.O("oj-converter.optionTypeInvalid.summary",{propertyName:f}),e=a.IntlConverterUtils.Jq(f,n)):"optionOutOfRange"===b?(d=a.ea.O("oj-converter.optionOutOfRange.summary",{propertyName:f,propertyValue:c.propertyValue}),n=c.propertyValueValid,e=a.IntlConverterUtils.Jq(f,n)):"optionValueInvalid"===b&&(d=a.ea.O("oj-converter.optionValueInvalid.summary",{propertyName:f,propertyValue:c.propertyValue}),n=c.propertyValueHint,e=a.IntlConverterUtils.Jq(f,n));return new a.rd(d,e)};
a.IntlConverterUtils.Jq=function(b,c){var d;return c?("string"===typeof c?d="oj-converter.optionHint.detail":(d="oj-converter.optionHint.detail-plural",c=c.join(a.ea.O("oj-converter.plural-separator"))),a.ea.O(d,{propertyName:b,propertyValueValid:c})):""};a.IntlConverterUtils.VX=function(){return""}});
//# sourceMappingURL=oj-modular.map